### ISSUE TITLE
NavBars

### ISSUE THREAD

**Issue by richbryant** [stsrki/Blazorise#1]
This is extraordinary.  Well done.

Do you plan to do Navbars?

**Comment by stsrki** [comment]
Hello, thanks for trying out Blazorise.

You already have Navbar component, but it's called `Bar `instead. Check it out.

**Comment by richbryant** [comment]
I will! An example would be nice though

**Comment by stsrki** [comment]
Still working on [documentation](https://blazorise.com/docs/). The Bar component is next to be explained but it shouldn't be too hard for you to get it.

Basically just go with the structure:
- Bar 
  - BarBrand
  - BarToggler
  - BarStart (left side of navigation)
    - BarItem
      - BarLink
  - BarEnd (right side of navigation)
    - BarItem
      - BarLink

**Comment by stsrki** [comment]
I have updated documentation with the [Bars](https://blazorise.com/docs/components/bars/) section so have a look.

**Comment by richbryant** [comment]
It's good.  I tried it and it looks great, although nav links don't work.  The tag produced is 

`<null href="mylink">`

**Comment by richbryant** [comment]
Great!  Let me know it's up, please.

**Comment by stsrki** [comment]
Published!

**Comment by richbryant** [comment]
Looks great!

Okay.  How do you click a button when it has no onclick event and throws errors if you try to use one?
