### ISSUE TITLE
Datagrid Field bind array

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#1002]
Hi, I see the Field needs to bind to method, can it support arrays?

` <DataGridColumn     TItem = "XX"        Field = "XXX.MyArray.GetValue (0)"  />`

My data column is dynamic stored in array.

**Comment by stsrki** [comment]
Field is binding to a name on your model, not the method. There is no support for arrays. Maybe you could bind it like `Field = "XXX.MyArray"` and then use `DisplayTemplate` but it's a long shot.

**Comment by imtrobin** [comment]
Ok, I think that's a good workaround, thanks.
