### ISSUE TITLE
String icon names don't work in razor

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1006]
If I add the following code it wont compile:

`<Icon Name="home" />`

instead you need to write this: 

`<Icon Name="@("home")" />`

This is because the underlying `Icon.Name` property is of type `object`. What probably would be better is to just make that property of type `IconName` and add an additional property of type `string` so it's no longer needed to have the obscure "@("xxxx")" syntax.

Maybe it would also be good it the following code would work

`<Icon>home</Icon>`

**Comment by stsrki** [comment]
Name is made as an `object` type to allow for a custom name as a string. Since not all icons can exist in `enum` this is a valid approach.
