### ISSUE TITLE
Text-Alignment on DataGridCommandColumn seems not to work

### ISSUE THREAD

**Issue by XoraX2002** [stsrki/Blazorise#1011]
Hi Mladen,

first of all thank you for all your work on blazorise, it's amazing!

While using the datagrid I came across an issue trying to center the buttons within the DataGridCommandColumn:

**Doesn't work:**
`<DataGridCommandColumn TItem="SomeObject" Width="150px" TextAlignment="TextAlignment.Center">`

**Works:**
`<DataGridColumn TItem="SomeObject" Field="@nameof(SomeObject.Id)" Caption="Id" TextAlignment="TextAlignment.Center" />`

Would be great if you could check that. Thanks a lot in advance!

Cheers
Jan

**Comment by stsrki** [comment]
It seems alignment is not set for command cell. I will do it for next milestone.

**Comment by XoraX2002** [comment]
Awesome! Thx!

**Comment by scottk4016** [comment]
TextAlignment is woking for EditCommand and DeleteCommand, however it doesn't seem to work for NewCommand,
Does it just need to be set in DataGridCommandColumn?

**Comment by scottk4016** [comment]
> TextAlignment is woking for EditCommand and DeleteCommand, however it doesn't seem to work for NewCommand,
> Does it just need to be set in DataGridCommandColumn?

Never mind. I worked out that it is set with HeaderTextAlignment in DataGridCommandColumn  :-)
