### ISSUE TITLE
Allow DateEdit date to be typed

### ISSUE THREAD

**Issue by vbray1979** [stsrki/Blazorise#1018]
Currently DateEdit component only allow date picking, an option to allow user to type the date would be very nice. 

_Options:_
1/ Date picking
2/ Date typing
3/ Both displayed like a dropdown item allowing text edition

**Comment by stsrki** [comment]
You can already enter date in DateEdit just fine.

![Eq6ecqgfkD](https://user-images.githubusercontent.com/900302/85625098-311d9680-b66b-11ea-84a8-d72638b7230a.gif)

**Comment by vbray1979** [comment]
Hi Mladen,

Thank you for your answer.
Indeed, this is working using chrome but not in edge for exemple.

![image](https://user-images.githubusercontent.com/55980308/85662566-55ec2b00-b6b8-11ea-80c8-498255ded8f4.png)

**Comment by stsrki** [comment]
I just tried it in Edge and FIrefox and it's also working. Although in Firefox it shows dropdown you can still enter date by typing.

Maybe you're still on older version of Edge?

**Comment by vbray1979** [comment]
Indeed using Edge Version 83.0.478.56 (Official build) (64-bit) works perfectly.
Thank you
