### ISSUE TITLE
Question: Material is just Bootstrap?

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1020]
Question: Our UX designer want us to swap to material.io and I thought that the Blazorize.Material was based on that, but when I was looking at the code. None of the [densities ](https://material.io/design/layout/spacing-methods.html#baseline-grid)(margins and paddings) or material.io classes are being used.

Is it a misconception that Blazorize.Material is using the [Material Components]( https://material.io/components), because the used classes all same to be bootstrap

**Comment by MitchellNZ** [comment]
Its based off [Daemonites Material implementation](https://github.com/Daemonite/material), which is basically applying the Material theme to Bootstrap.

However, they aren't actively maintaining this right now.
But it is still being maintained by djibe [here](https://github.com/djibe/material), and there is still comprehensive [documentation](https://djibe.github.io/material/docs/4.5/getting-started/introduction/) on it.

**Comment by njannink** [comment]
But if I look for example the material demo website: https://materialdemo.blazorise.com/tests/buttons

Then I miss the animations on the buttons etc. Or this that because of the used underlying stylesheets

**Comment by MitchellNZ** [comment]
I did not notice that those aren't working!

If you would like those animations, all you need to do is download the **latest** JavaScript ([found here](https://github.com/djibe/material/tree/master/js)), put in in your project and reference it in your `index.html` file (e.g. `<script src="js/material.min.js"></script>`), and they should all work fine.

It appears that the Blazorise Material demo applications JavaScript is out-of-date, but the CSS is up-to-date.
