### ISSUE TITLE
Question DataGrid Edit

### ISSUE THREAD

**Issue by kofinn** [stsrki/Blazorise#1034]
Hi,

I am using DataGrid component with inline edit mode. Is it possible to change Editable parameter of one column while editing entry?

![image](https://user-images.githubusercontent.com/22171329/85910091-50f4bc00-b81d-11ea-9e9a-fbb9ce8e1190.png)
For example, if I change gateway to NO, Column "Jméno Gateway" should not be editable
Thank you

**Comment by stsrki** [comment]
Not directly. You could use EditTemplate on a columns and then create custom fields where you can react to whatever you need.

Example

```cshtml
<DataGridSelectColumn TItem="Employee" Field="@nameof( Employee.Gender )" Caption="Gender" Editable="true">
    <EditTemplate>
        <Select TValue="string" Disabled="@yourDisabledFlag" SelectedValue="@((string)( ( (CellEditContext)context ).CellValue ))" SelectedValueChanged="@(( v ) => ( (CellEditContext)context ).CellValue = v)">
            <SelectItem TValue="string" Value="null"></SelectItem>
            <SelectItem TValue="string" Value="@("M")">Male</SelectItem>
            <SelectItem TValue="string" Value="@("F")">Female</SelectItem>
        </Select>
    </EditTemplate>
</DataGridSelectColumn>
```

**Comment by kofinn** [comment]
Thank you
