### ISSUE TITLE
Sample not using new vertical bar 0.9.1

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#1037]
Hi, can you update the sample project demo to new vertical bar with toggle?

**Comment by imtrobin** [comment]
Ok, I know why. The bar toggle is hidden unless the sidebar is in collapsed. Is that intended?

**Comment by MitchellNZ** [comment]
Yes, the demo project has a custom function that overrides the default behaviour of the top bar's toggle (which is to show/hide the top bar contents when the breakpoint is hit).
This is just one way of doing it.

Currently, the vertical bar does not have a good implementation of the `BarToggler` for itself out of the box, so you will need to handle it another way.

The most simple way of doing this is just to make copy the [demo project](https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Layouts/MainLayout.razor), but make the `BarToggler` on the top bar always visible by adding `<BarToggler Style="display: block" />`.
If you want it to be close to the sidebar, just move it above the `<BarBrand>`.

Additionally, you can create your own button to do this.

Hope this helps!

**Comment by imtrobin** [comment]
Cool, got it. Is there a way to adjust the width of the sidebar when un-collapsed? My BarItems are being cut off.

**Comment by stsrki** [comment]
You can use `ThemeProvider` and set the `BarOptions` to control the vertical bar width. Or you can just use regular CSS. Either way it should work.

**Comment by imtrobin** [comment]
Thanks working. It seems there is still the SideBarOptions which I presume should be removed?

**Comment by stsrki** [comment]
No, SidebarOptions are still valid for Sidebar extension component.

**Comment by imtrobin** [comment]
ok, I thought the new bar replaces it.
