### ISSUE TITLE
Shadow Elevation

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#1040]
Hi, like to request for this shadow like this

https://www.matblazor.com/Elevation

**Comment by stsrki** [comment]
I can consider it for one of the next milestones.

**Note for me:**
https://getbootstrap.com/docs/4.4/utilities/shadows/

**Comment by itsLollo1000** [comment]
Any updates on this? 

@imtrobin did you use a different design than a Card?

**Comment by stsrki** [comment]
Hi, it's currently low on the list. I can make it part of #942 since I have a plan to do it soon.

**Comment by itsLollo1000** [comment]
Hi, thanks for the fast response! 
Okay cool to hear, I would love to see it! 

`        <div class="shadow p-3 mb-5 bg-white rounded">
            <Card>...</Card>
         </div>
`
As a quick workaround I went for this solution.
