### ISSUE TITLE
Barbrand using image

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#1041]
Hi, like the barbrand to display an image instead of text. Now it doesn't take account of the the image size, image will overlap onto other BarItems

**Comment by MitchellNZ** [comment]
Code you please provide a screenshot or code example of the issue you are having?

**Comment by imtrobin** [comment]
Using a random logo

![image](https://user-images.githubusercontent.com/531606/85973543-a25f9f80-ba05-11ea-831d-b5493979295d.png)

I use an img in barbrand

**Comment by stsrki** [comment]
Do you have image height specified?

**Comment by imtrobin** [comment]
No.  Anyway, it's a low priority issue, I changed it to have header on top always, so I put the branding there

**Comment by stsrki** [comment]
You should define image size. Even in the our demo app you can see that it's specified

`RenderFragment customIcon =@<img src="/brand-logo.png" style="width:32px; height: 32px" />;`

**Comment by imtrobin** [comment]
Ok I specified a size to make it fit. But it would still overlap if it exceed a baritem. My initial thought is it would be calculated
