### ISSUE TITLE
[Extension Autocomplete] Can we define the type of TextEdit ?

### ISSUE THREAD

**Issue by Remy-Be** [stsrki/Blazorise#1044]
Hello !

**Is your feature request related to a problem? Please describe.**
I am currently using autocompletion to search through a list via the onInput event.
My problem is that my browser (Chrome) pre-fills the field with the login email of the login form, and so, launches an unexpected search... 

**Describe the solution you'd like**
Can we have the possibility to define the Type attribut (type="search" here) of the TextEdit included in the autocompletion ?

Thank you very much;

Regards,
Rémy

**Comment by stsrki** [comment]
I can just define built-in TextEdit as `type="search"`. Is that OK?

**Comment by Remy-Be** [comment]
Thank you for your prompt response, that would be perfect for my case 👍
