### ISSUE TITLE
Bootstrap 4.5.0 - ColumnSize="ColumnSize.Is12.OnMobile"  still use 'col-xs-12' (deprecated)

### ISSUE THREAD

**Issue by Remy-Be** [stsrki/Blazorise#1045]
Hello :) 

**Describe the bug**
When I use the Columsize.Is12.onMobile property the generated css class is 'col-xs-12', but this one is no longer used in the current version of bootstrap (v4.5.0).

**To Reproduce**
 ```
<Column ColumnSize="ColumnSize.Is3.OnDesktop.Is4.OnTablet.Is12.OnMobile">
        <div style="border:1px solid red;">Box col-xs-12</div>
</Column>
```

**Expected behavior**
Is it possible to replace it with the class 'col-12' to avoid display problems on mobile?

**Screenshots**
Bug :
![image](https://user-images.githubusercontent.com/16755574/86020511-4b1ef680-ba28-11ea-8ddc-16f21f4ca3c4.png)
Expected :
![image](https://user-images.githubusercontent.com/16755574/86020424-2e82be80-ba28-11ea-8240-44c8769a787e.png)

Thank you !

Regards
Rémy

**Comment by stsrki** [comment]
I have no idea how I missed that!? Thank you for letting me know. It will be fixed!

**Comment by Remy-Be** [comment]
You're welcome ! Thank you :)
