### ISSUE TITLE
Passing Values to MODAL

### ISSUE THREAD

**Issue by raheelaklodhi** [stsrki/Blazorise#1047]
I am trying to create a Modal for EDIT and DELETE confirmation, can anyone please advise how to do it ?

**Comment by stsrki** [comment]
It's simple as creating new component and placing Modal dialog code inside of it. 

Create new component, something like **ConfirmDeleteDialog.razor**

**Example**:

```cshtml
<Modal @ref="modalRef">
    <ModalBackdrop />
    <ModalContent>
        <ModalHeader>
            <ModalTitle>
                Confirm
            </ModalTitle>
            <CloseButton Clicked="@OnCancel" />
        </ModalHeader>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@OnCancel">Cancel</Button>
            <Button Color="Color.Danger" Clicked="@OnDelete">Delete</Button>
        </ModalFooter>
    </ModalContent>
</Modal>
@code{
    private Modal modalRef;
    private Result result;

    public void Show()
    {       
        modalRef.Show();
    }

    private void OnCancel()
    {
        result = Result.Canceled;
        modalRef.Hide();
    }

    private void OnDelete()
    {
        result = Result.Delete;
        modalRef.Hide();
    }
}
```

**Comment by raheelaklodhi** [comment]
Bundle of thanks for your help.

Can you please explain this Result as well ? Is it a separate class i can define as per my requirement or its part of this package ?
private Result result;

**Comment by stsrki** [comment]
It's just s simple enum to give you an example. You can create it by yourself.

**Comment by raheelaklodhi** [comment]
Thanks a lot for your quick reply. I am struggling with EDITING of a Table Row using Blazorise Modal. It is somehow working but I am not satisfied with what i am doing. Can you refer me with some working example for editing a record from a table using BLAZORISE MODAL.. I would be really obliged with your help. Thanks again

**Comment by stsrki** [comment]
Why not use DataGrid with `EditMode=Popup`? https://blazorise.com/docs/extensions/datagrid/

**Comment by raheelaklodhi** [comment]
Ok...Let me try and will revert..

**Comment by stsrki** [comment]
Closing as I think original question is answered.
