### ISSUE TITLE
Bug: Dropdowns not working correctly in all UI frameworks

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1059]
When testing my changes to the dropdown I found some issues various UI frameworks:

**Ant Design**
- All dropdown indicators are points downwards
- Left, Right and Up direction not working

**Bulma**
- All dropdown indicators are points downwards
- Left and Right not working

**eFrolic**
- Not working at all

**Comment by stsrki** [comment]
The issues are already known, just didn't had time to track them. I will schedule them for next milestone if that's OK.

**Comment by stsrki** [comment]
Done with #1709
