### ISSUE TITLE
Feature Change Background image

### ISSUE THREAD

**Issue by janellesnowy** [stsrki/Blazorise#106]
Hi, is it able to specify a background image? I tried adding the background image in site.css, it still remains unchanged. Where is the place to change it?

**Comment by stsrki** [comment]
Setting the background image can be set like [this](https://www.w3schools.com/cssref/pr_background-image.asp). Blazorise is not stopping you from using regular html or css. 

The other way of setting the background image can be by using the `Style` attribute that can be found on every component. eg.

`<SomeComponent Style="background-image: url("paper.gif");" />`

**Comment by janellesnowy** [comment]
I see. It was a mistake with the path in the url. It's working, thanks. But I'm also thinking in the themeing, we can have options to set this in the base classes.
