### ISSUE TITLE
24h format for TimeEdit

### ISSUE THREAD

**Issue by hypercodeplace** [stsrki/Blazorise#1060]
Am I right if there is only 12h + AM/PM format for now? It will be good to have 24h format too in this case. Probably, the best way is taking into account the current UI culture.

**Comment by stsrki** [comment]
TimeEdit is using `<input type="time">` and unfortunately it is completely controlled by the browser. The only way, **might be**, is to set locale but even that is not guaranteed to work https://www.w3.org/International/questions/qa-html-language-declarations
