### ISSUE TITLE
Alert visibility

### ISSUE THREAD

**Issue by akusmin** [stsrki/Blazorise#1061]
I've tried to implement alerts to be visible on a special context but it is always visible. I tried both samples from demo and documentation and behavior is the same... Alert is always visible.

Here is component sources inspired by Blazorise demo samples:

```
@layout RootLayout
@page "/test"

<Alert Dismisable="true" Visible="@visible">
    <AlertMessage>Test alert.</AlertMessage>
    <CloseButton Clicked="@(() => visible = false)" />
</Alert>

    @code {
        bool visible = true;
    }
```

I'm using the version 0.9.1.1. 

Please advice how can I force Alert to be hided.

**Comment by stsrki** [comment]
Well you have initialized it as visible by default. Just set it to false:  `bool visible = false;`

I just tried it and it should work.

**Comment by akusmin** [comment]
@stsrki thanks for your fast response.

Unfortunately it's not working for me.

Posting here another option with default hidden state (in fact visible). 

```
@layout RootLayout
@page "/test"

<Alert @ref="@alert" Dismisable="true" Visible="@visible">
    <AlertMessage>Test alert.</AlertMessage>
    <CloseButton Clicked="@(() => visible = false)" />
</Alert>
<Button Clicked="@(()=>alert.Toggle())">Toggle</Button>

    @code {
        Alert alert;

        bool visible = false;
    }
```

On Clicked event there is no any changes in alert visibility state.

**Comment by stsrki** [comment]
Try this

```
<Alert @ref="@alert" Dismisable="true" Visible="@visible">
    <AlertMessage>Test alert.</AlertMessage>
    <CloseButton Clicked="@(() => visible = false)" />
</Alert>
<Button Clicked="@OnClicked">Toggle</Button>

@code {
    Alert alert;

    bool visible = false;

    Task OnClicked()
    {
        visible = !visible;

        return Task.CompletedTask;
    }
}
```

**Comment by akusmin** [comment]
I'm able to achieve normal behavior. I have created new page component without pure html with Blazorise components only.

So now previous code works as expected.

```
   <Alert Color="Color.Warning" Visible="@visible">
        <AlertMessage>test alert</AlertMessage>
        <CloseButton Clicked="(()=>visible = false)"/>
    </Alert>

@code {
    bool visible = true;
}
``` 
Don't know the reason of misbehavior.

**Comment by akusmin** [comment]
Looks that something was done wrong from my end. Just one more alert visibility behavior observation.

Working code as expected:
```
<Alert @ref="alert" Dismisable="true" Visible="@visible">
        <AlertMessage>Test alert.</AlertMessage>
        <CloseButton Clicked="@(() => visible = false)" />
    </Alert>
    <Button Clicked="@(()=>visible = !visible)">Toggle</Button>

        @code {
            Alert alert;

            bool visible = true;
        }
```

Code is not working as expected. Toggle is not working.

```
<Alert @ref="alert" Dismisable="true" Visible="@visible">
    <AlertMessage>Test alert.</AlertMessage>
    <CloseButton Clicked="@(() => visible = false)" />
</Alert>
<Button Clicked="@(()=>alert.Toggle())">Toggle</Button>

@code {
    Alert alert;

    bool visible = true;
}
```

**Comment by stsrki** [comment]
The thing with `Toggle `is that it only applies the internal visibility. And since you also have `Visible="@visible"` after each change it will reset to `bool visible = true;`. You use either one or another, not both.

I can add `VisibleChanged` event so that two-way binding (`@bind-Visible="@visible"`) can work. That should not be a problem I think.

**Comment by stsrki** [comment]
In the next release this should work

```
<Alert @ref="alert" Dismisable="true" @bind-Visible="@visible">
    <AlertMessage>Test alert.</AlertMessage>
    <CloseButton Clicked="@(() => visible = false)" />
</Alert>
<Button Clicked="@(()=>alert.Toggle())">Toggle</Button>

@code {
    Alert alert;

    bool visible = true;
}
```
