### ISSUE TITLE
<Heading Size=HeadinSize.IsSomething> generate Non semantic Html

### ISSUE THREAD

**Issue by StephaneJourdois** [stsrki/Blazorise#1063]
Hi,

Strange behavior for the Heading Component witch generate non semantic HTML tag 

**Describe the bug**
The Heading component generate a `<p class="h1">` (or else) instead of `<h1>` tag

**To Reproduce**
```
<Heading Size="HeadingSize.Is1">
     My title H1
</Heading>
```
**Expected behavior**
`<h1>My title H1</h1>`

**Screenshots**
![image](https://user-images.githubusercontent.com/22419870/86258471-27d88080-bbbb-11ea-9ca6-f4dd866494bf.png)

Thanks for your great job !

Stephane

**Comment by stsrki** [comment]
`<p class="h1">` is still valid markup. See https://getbootstrap.com/docs/4.5/content/typography/#headings

**Comment by njannink** [comment]
Problem is that certain html interperters and scrapers don't interpret that very well. Eg html to markdown would transform a `<h2>Heading 2</h2>` to `##Heading 2##` and would transform the `<p class="h1">` to plain text. So I agree with @StephaneJourdois that actual `<h*>` tags should be generated.

**Comment by stsrki** [comment]
Fixed. Going to be available in the next preview!
