### ISSUE TITLE
DataGrid component editing mode needs to be customized

### ISSUE THREAD

**Issue by 199621616** [stsrki/Blazorise#1064]
功能请求是否与问题相关：是的，直接相关
![image](https://user-images.githubusercontent.com/25498672/86304147-8eec4880-bc40-11ea-9666-517122e27d92.png)
这是我们目前应用中在DataGrid编辑时的状态
需要自定义以下三点：
一、标题：Row Edit，需要自定义为中文合适的名称
二、回复内容，需要自定义为使用textarea回复，它的内容可能很多
三、日期，需要自定义为yyyy-MM-dd HH:mm:ss格式

或者，整个模态窗口可以自定义，也可解决这几个问题

Sorry, my English is not good

Whether the function request is related to the problem: Yes, it is directly related. This is the status of our current application when editing the DataGrid. We need to customize the following three points: first, the title: row edit, which needs to be customized to the appropriate Chinese name; second, the reply content needs to be customized to reply with textarea, which may have many contents; third, the date needs to be customized as yyyy-MM-dd HH: mm:ss  format

Or, the whole modal window can be customized to solve these problems

**Comment by imtrobin** [comment]
一，二，用 
https://blazorise.com/docs/extensions/datagrid/#templates
三， 不知

**Comment by stsrki** [comment]
Guys as much as I would like to, I don't know how to read mandarin(I guess that's it). Can you write in English please?
