### ISSUE TITLE
The layoutfoot component is not pinned to the bottom of the window

### ISSUE THREAD

**Issue by 199621616** [stsrki/Blazorise#1069]
当Body的内容高度超出窗口高度后，LayoutFoot组件没有Fixed属性可用，会随Body内容上下移动。

预期的行为，像LayoutHeader组件一样，可将Fixed属性调为true，以固定在底部。

When the body content height exceeds the window height, the layoutfoot component has no fixed property available and will move up and down with the body content.

The expected behavior, like the layoutheader component, can be pinned to the bottom by setting the fixed property to true.

**Comment by stsrki** [comment]
@MitchellNZ wanna take a look at this after you finish with your current work?

**Comment by MitchellNZ** [comment]
@stsrki Yeah, sure thing.

**Comment by MitchellNZ** [comment]
Fixed as part of https://github.com/stsrki/Blazorise/issues/1089 (in 0.9.2).
You will need to added `<LayoutFooter Fixed="true">...</LayoutFooter>`.
