### ISSUE TITLE
Bar expand/collapse not working on mobile devices

### ISSUE THREAD

**Issue by tynor88** [stsrki/Blazorise#1091]
**Describe the bug**
The bar is not able to expand on mobile devices in latest version. It worked fine in 0.9.0.3

**To Reproduce**
1) Add Bar component . Minimize display and click on the 3 lines to expand the bar menu.
2) Nothing happens. From the HTML i see the "_show_" class is not being added to the div with classes "collapse navbar-collapse"

**Expected behavior**
It should expand the menu.

Possibly related to https://github.com/stsrki/Blazorise/issues/766

**Comment by MitchellNZ** [comment]
@tynor88 Could you please provide an example of your code.
Or if you were experiencing this in the demo app, could you please tell me your device type/browser?

Also, I'm assuming your referring to the _horizontal_ bar (top bar) not expanding/collapsing correctly?

**Comment by tynor88** [comment]
Hi @MitchellNZ. 
Yes the horizontal bar. Please check this code example. Make your browser window small. And try to toggle the menu bar:

```csharp 
<Layout>
    <LayoutHeader>
        <Bar Breakpoint="Breakpoint.Desktop">
            <BarBrand>Hi</BarBrand>
            <BarToggler>
            </BarToggler>
            <BarMenu>
                <BarStart>
                    <BarItem>
                        <BarLink To="/test">test</BarLink>
                    </BarItem>
                </BarStart>
            </BarMenu>
        </Bar>
    </LayoutHeader>
    <LayoutContent>
    </LayoutContent>
</Layout>
```

**Comment by StephaneJourdois** [comment]
Hi all, 
same issue here since last update :) 
Thanks all.

**Comment by MitchellNZ** [comment]
Thanks guys.
Can confirm this one is a bug.

I have been able to fix it in the current set of changes I am working on for the 0.9.2 release.
But unfortunately its going to have to wait till the 0.9.2 release due to it being tied into relying on some other changes I have made, sorry about this!
