### ISSUE TITLE
Bar default vertical scrollbar in Firefox and Edge (pre Chromium)

### ISSUE THREAD

**Issue by hesuruio** [stsrki/Blazorise#1092]
Hi!

It seems on Firefox (77.0.1) and Edge (pre Chromium version) the Bar has a default vertical scrollbar.

![image](https://user-images.githubusercontent.com/13237805/86583824-ca0db500-bf7b-11ea-895f-d6b45a0c39d8.png)

I think it's caused by **_height: 100vh;_** as setting height to 99vh solved the problem.
https://github.com/stsrki/Blazorise/blob/a8c24ce105ecf33c92b00de54a238d89505363a1/Source/Blazorise/wwwroot/blazorise.css#L227

**Comment by MitchellNZ** [comment]
Thanks for raising this!

**Comment by MitchellNZ** [comment]
Fixed as part of #1287
