### ISSUE TITLE
Problem with vertical BarItem longer text

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1093]
When BarItem text is longer than expected in vertical bar mode, it will show the ellipsis.

![image](https://user-images.githubusercontent.com/900302/86589998-fa128380-bf8e-11ea-956f-2c61066ebc4e.png)

There are couple of issues:

- `.b-bar-dropdown-item` padding is set to `.5rem 3rem !important`, Maybe `padding-right` can be set to 0?
- because of `!important` I cannot override it in application `site.css`

Ways to fix:

- remove `padding-right`
- add property to `BarItem` to disable `text-overflow: ellipsis;`
- remove `!important`

@MitchellNZ

**Comment by MitchellNZ** [comment]
@stsrki Ahh yes, good find!
I personally think we should remove or reduce the `padding-right` (and probably them `!important`, if possible).

I will need to address this as part of #1042 "multi-level items" anyway.
So I will fix it up then!

**Comment by stsrki** [comment]
Excellent, thank you!

**Comment by hesuruio** [comment]
Here is an example of multi line bar items in github pages docs for reference

https://docs.github.com/en/github/working-with-github-pages
