### ISSUE TITLE
Select component doesn't recognize changes by code

### ISSUE THREAD

**Issue by martinscholz83** [stsrki/Blazorise#1100]
**Describe the bug**
For example you have an edit form with a multiple select component. When select items `SelectedItems` contains the selected values. But when changing `SelectedItems` by code, the Select component doesn't recognize this change. 
```razor
<Select  class="form-control" Multiple="true" TValue="int" @bind-SelectedValues="@selectedTags">
..
..
@code {

IReadOnlyList<int> selectedTags;
...
...

private void ShowEditForm()
{
var newTags = new List<int>() { 1, 2 };
selectedTags = newTags.AsReadOnly();
...
}
```

**To Reproduce**

**Expected behavior**
Select component should update itself when `SelectedItems` is changed by code.

**Comment by martinscholz83** [comment]
Is there a way to get the component with `@ref` to set `SelectedValuesChanged`. When setting `selectedTags` in code before selecting anything on UI, component set the selected items. But after you select something and the `OnChangeHandler` EventCallback is raised, it doesn't detect the change when changing in code.

**Comment by stsrki** [comment]
Try calling `StateHasChanged()` after setting the `SelectedValues` property. That usually help.

**Comment by martinscholz83** [comment]
Already tried. But it didn’t help. It seems that the select component holds a different reference of `selectedTags`. Because when reopen the select it has selected the old value. To better understand I have a modal to edit settings. Before reopen the modal I load settings from database. But when reopen the modal the select component has selected the item(s) you selected before.

**Comment by martinscholz83** [comment]
I think the problem is because you always get the selected items from DOM with javascript.
https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Select.razor.cs#L80
So you will never notice any update made by code.

**Comment by stsrki** [comment]
I didn't check it yet, but I will put it on the list for 0.9.2 release and try to fix it for one of the next previews.

**Comment by martinscholz83** [comment]
It seems that the error is somewhere else when the select component is re-rendered. `CurrentValue` always returns the correct count when setting `SelectedValues`. One other thing i saw is that `ContainsValue` is called many times (5 or 6 times) when the component is rendered.

**Comment by stsrki** [comment]
I'm using this code to test the select

```cshtml
<Select Multiple="true" TValue="int" @bind-SelectedValues="@selectedTags" MaxVisibleItems="10">
    @foreach ( var item in tags ?? Enumerable.Empty<int>() )
    {
        var value = item;

        <SelectItem @key="@value" TValue="int" Value="@value">@value</SelectItem>
    }
</Select>

<p>
    Selected:

    @foreach ( var item in selectedTags ?? Enumerable.Empty<int>() )
    {
        <span>@item</span>
    }
</p>

<Button Color="Color.Primary" Clicked="@ShowEditForm">TEST</Button>

@code {
    IReadOnlyList<int> tags = new int[] { 1, 2, 3, 4, 5, 6, 7, 8 };

    IReadOnlyList<int> selectedTags = new int[] { 1, 2, 3 };

    private Task ShowEditForm()
    {
        selectedTags = new int[] { 2, 4, 6 }.ToList().AsReadOnly();

        return Task.CompletedTask;
    }
}
```

The select works great, It will get and set the values as expected. BUT the weird bug happen as soon as I CLICK on any options. Everything breaks. Select component will not refresh after I click on the TEST button, and when I inspect elements in devtools everything seems fine. And `SelectedValues` are fine. Only thing not working is the refresh. 🤯

I need to clear head before I continue with this one :)

**Comment by martinscholz83** [comment]
Got also some headache 😉

**Comment by stsrki** [comment]
More I'm thinking this is not going to be fixed that soon:

- https://github.com/dotnet/aspnetcore/issues/5519
- https://github.com/dotnet/aspnetcore/issues/16942
- https://stackoverflow.com/questions/58777642/blazor-fire-onchange-event-when-chosen-drop-down-value-changes

**Comment by stsrki** [comment]
Going to pause this ticket. I've being searching for a solution entire day, and whatever I try nothing works. So for now I'm going to proceed with other tickets and in the meantime I will try to research some more options. Maybe all I need is a different perspective. I hope this OK with you @martinscholz83

**Comment by martinscholz83** [comment]
Fine for me. As a workaround we show in a textfield what tags are currently saved in database. Thx for investigating on this issue!

**Comment by martinscholz83** [comment]
Oh, one more question I have if it’s ok. I also use tab elements. And on every tab change the whole page is reloading. Is that wanted? Is it the concept of blazor to reload the complete razor page when something is triggered an onchange event?

**Comment by martinscholz83** [comment]
@stsrki, seems that this is fixed is already fixed. Can you confirm?

**Comment by stsrki** [comment]
Nop, still not working for me.

**Comment by martinscholz83** [comment]
For me when changing `selectedTags` with code, the `Select` show the correct values.

**Comment by stsrki** [comment]
I tried the example https://github.com/stsrki/Blazorise/issues/1100#issuecomment-657058545

- select something with the mouse
-  Now click on the Test button
- Again, select something with the mouse
- click on Test

you will see it doesn't update

**Comment by martinscholz83** [comment]
https://user-images.githubusercontent.com/19551763/109510645-8fc0cd00-7aa2-11eb-841e-886325f8e4da.mov

**Comment by stsrki** [comment]
Now I'm really confused...

What version do you use? 0.9.2 or 0.9.3 RC?

**Comment by martinscholz83** [comment]
<img width="320" alt="Bildschirmfoto 2021-03-01 um 15 30 00" src="https://user-images.githubusercontent.com/19551763/109511147-0d84d880-7aa3-11eb-9f01-f3130e11b126.png">

**Comment by stsrki** [comment]
And browser?

**Comment by martinscholz83** [comment]
Safari Version 14.0.3 (16610.4.3.1.4)

**Comment by stsrki** [comment]
The only one I can't test with :)

So far I tried Chrome, Firefox and Edge. Same problem.

**Comment by martinscholz83** [comment]
Oh, I see. In Edge or Chrome it doesn't work

**Comment by martinscholz83** [comment]
I switched while testing from Chrome to Safari

**Comment by martinscholz83** [comment]
But what is then the main issue. The underlying javascript engine?

**Comment by stsrki** [comment]
> But what is then the main issue. The underlying javascript engine?

That is the only reason that comes to my mind.

**Comment by stsrki** [comment]
Safari does not always go with the standards so in this case, it works, unlike with other browsers that are probably following some (to me) unknown rule.

**Comment by martinscholz83** [comment]
Ok. But for me the question is, who will fix this? Not specially for your `Select` component. More the core issue.

**Comment by stsrki** [comment]
I was trying something new this afternoon and I had some good results. It's a little ugly still but I think I will be able to make it work 🤞
