### ISSUE TITLE
Remove .razor files for all core components

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1101]
The idea is to remove all `.razor` files from Blazorise project. All of the components markup would then be generated through the code

```cs
protected override void BuildRenderTree( RenderTreeBuilder builder )
{
    base.BuildRenderTree( builder );

    builder.OpenElement( 0, "div" );

    builder.AddElementReferenceCapture( 2, capturedRef => { ElementRef = capturedRef; } );
    builder.AddContent( 3, childContent );

    builder.CloseElement();
}
```

The good: 

- Better control over what needs to be included in the rendering tree
- Empty `style` attribute would not be rendered for every component like in this example:
  ![image](https://user-images.githubusercontent.com/900302/86766556-ff350880-c04a-11ea-85ab-db97158c782a.png)
- I didn't tested this one, but I would guess the build would also be faster since there is not going to be transpile from .razor into .cs generated code done by Blazor

The bad:

- A lot more work required since everything must be written by hand
- Easier to mess something

**Comment by njannink** [comment]
This will create a quite steep learning curve for new contributors to the project, because everybody more or less expects razor files with the html elements inside. As for the empty style attributes isn't there a different solution for this?

**Comment by njannink** [comment]
```
<a @attributes="BuildAttributes()">My link</a>

@code {
IDictionary<string,object> BuildAttributes()
{   
    var attr = new Dictionary<string,object>(Attributes); 
    if (!string.IsNullOrEmpty(StyleNames)) {
        attr["style"] = StyleNames;
    }

    if (!string.IsNullOrEmpty(ClassNames)) {
        attr["class"] = ClassNames;
    }     

    return attr;
}
}
```

**Comment by stsrki** [comment]
It's not just about attributes. There could be different tags based on the condition. This separation of rendering tree under `@if` condition can sometimes lead to some other problems.

**Current:**

```cshtml
@if ( SomeCondition )
{
    <div class="@ClassNames" style="@StyleNames" @attributes="@Attributes">
        @ChildContent
    </div>
}
else
{
    <span class="@ClassNames" style="@StyleNames" @attributes="@Attributes">
        @ChildContent
    </span>
}
```

**New:**

```cs
builder.OpenElement( 0, SomeCondition ? "div" : "span" );

builder.AddAttribute( 1, "class", ClassNames );
builder.AddAttribute( 2, "style", StyleNames );
builder.AddMultipleAttributes( 3, Attributes );

builder.CloseElement();
```

**Comment by stsrki** [comment]
Make sense to use only for most specific components, not all. Closing now.
