### ISSUE TITLE
DataGrid access to FilteredData

### ISSUE THREAD

**Issue by weeksdev** [stsrki/Blazorise#1106]
I am trying to do get access to the list of `FilteredData` but it appears to be not exposed as a Parameter

Would be nice to have it exposed as `FilteredData` that I could retrieve into another variable.

```
private List<TItem> filteredData = new List<TItem>();
```

I found the above and would be nice if this could be exposed as public?

**Comment by stsrki** [comment]
`FilteredData` is used to get the current list of data based on all of the parameters sets by the internal and external sources. It cannot be made as a parameter as that would brake existing code.

**Comment by weeksdev** [comment]
Sorry not as parameter but rather the filtered dataset be exposed publicly so that I can retrieve the list of filtered results

**Comment by bawilderman1** [comment]
Would it be possible to expose an EventCallback with a readonly copy of the filtered data on filter changes that we can assign from the DataGrid Component's attributes?

**Comment by stsrki** [comment]
@bawilderman1 that might work actually. But instead EventCallback I can add Action.

**Comment by bawilderman1** [comment]
Yeah I think Action<T> would work. So I'll admit that I'm still pretty new to Blazor but if you know where you would want the Action to reside I'd be happy to take a stab at making a PR. Feel free to let me know.

**Comment by 45software** [comment]
This is the one item that's missing for me.  Unfortunately without it I'm stuck.  Any timeline on getting this completed?

**Comment by stsrki** [comment]
I might add it for next preview, it shouldn't be a big problem to add. But instead of making FilteredData public I think I will add an event that raises after data is changed.

**Comment by stsrki** [comment]
I have added new `FilteredDataChanged `event and I plan to release new preview probably tomorrow or during the weekend.
