### ISSUE TITLE
Style-Property on CheckEdit: has no effect

### ISSUE THREAD

**Issue by Garios** [stsrki/Blazorise#112]
Hello,
I can set the class-prop, but not the style-prop. It has no effect. I think this also happens on other controls.

<CheckEdit Style="background-color: red"></CheckEdit>

**Comment by stsrki** [comment]
You're right, it seems that I forgot to add Style to some of the components. It will be in the next minor version 0.7.7

**Comment by stsrki** [comment]
@Garios I'm trying to figure what is the best way add Style for CheckEdit. The issue with this type of input is that it always comes with a `<label>` element. In case of Bootstrap the `<label>` is positioned next to the `<input type="checkbox">`. In case of Bulma or maybe other frameworks the input is inside of a label.

Bootstrap example:
```
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Default checkbox
  </label>
</div>
```
Bulma example:
```
<label class="checkbox">
  <input type="checkbox">
  Remember me
</label>
```

What I'm not sure is to which of these I should pass a Style attribure. To a checkbox, label or maybe to both of them? What are your thouths on this?
