### ISSUE TITLE
Radios and Sliders vertical alignment

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1121]
Just like #893, but also for radios and sliders:

![image](https://user-images.githubusercontent.com/56033692/87059586-da25ce80-c1df-11ea-96d0-2debdce310f0.png)

https://materialdemo.blazorise.com/tests/forms

**Comment by WillianGruber** [comment]
Also for switches, if used with labels:
![image](https://user-images.githubusercontent.com/56033692/87087890-45849600-c20a-11ea-91af-d9ae3d2b6a4d.png)

**Comment by stsrki** [comment]
@WillianGruber

I was investigating this and I think it is working as expected. Natively bootstrap does not have any padding or height on radio, check, range, and switch components.

After some playing with height for `Slider` component I was able to adjust it. But as I mentioned before I'm not sure if this is the right way to go for. The purpose of these controls is to be able to be as compact as they can be. So making them the same size as other components would look weird.

That is just my reasoning, maybe I'm wrong. But I was not able to find any example where this is not the case. So I guess it is good 🤷‍♂️

I will close this ticket and if someone writes good reasoning to hard-code the padding and height I will gladly listen.

**Comment by WillianGruber** [comment]
No problem! Thanks for the effort!

If needed, I'll write a wrapper in my own project.

(Yes, I'm still here, but not actively working on this right now. I'll be back end of month...)
