### ISSUE TITLE
getComputedStyle

### ISSUE THREAD

**Issue by hardkorehak** [stsrki/Blazorise#1122]
Using Sidebar (v0.9.1.1) for our Blazor WASM menu and seeing the following error in Console:

blazorise.js:518 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getBreakpoint (blazorise.js:518)
    at blazorise.js:601

**Comment by MitchellNZ** [comment]
Where have you placed your reference to `blazorise.js?`

**Comment by hardkorehak** [comment]
In the <head> of index.html

**Comment by MitchellNZ** [comment]
Could you please try moving into the `body`, below the `app` tag?

**Comment by hardkorehak** [comment]
That worked…thanks.
