### ISSUE TITLE
Bar Theming

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#1123]
**Ideas for Horizontal & Vertical Bar Theming**

My thinking is to expand on the existing `ThemeBarOptions` to include settings for the Horizontal Bar and _possibly_ remove the Dark/Light override options to only provide a "Custom" set.

**Examples:**

- Update `ThemeContrast` to support `Custom`:
```
public enum ThemeContrast
{
    None,
    Light,
    Dark,
    Custom
}
```

- Remove the `Background` parameter from the `Bar` and use `ThemeContrast.Custom` instead (to avoid confusion about how to theme/color the Bar):
```
<Bar ... ThemeContrast="ThemeContrast.Custom">
```

- Change the `ThemeBarOptions` to something like (only showing theme colors for brevity):
```
public class ThemeBarOptions
{
    ...
    public ThemeBarColorOptions VerticalColors { get; set; }
    public ThemeBarColorOptions HorizontalColors { get; set; }
}

public class ThemeBarColorOptions
{
    public string BackgroundColor { get; set; }
    public string Color { get; set; }
    public ThemeBarItemColorOptions ItemColorOptions { get; set; }
    public ThemeBarDropdownColorOptions DropdownColorOptions { get; set; }
    public ThemeBarBrandColorOptions BrandColorOptions { get; set; }
}
```

By doing this, `ThemeContrast.Custom` is the only setting that would use the `ThemeBarOptions`, and the `Light`/`Dark` would be Blazorise defaults. 

Perhaps even the `Light`/`Dark` could somehow be influenced by the `Primary` app colors chosen?

@stsrki @WillianGruber would love to hear your thoughts/ideas!

**Comment by stsrki** [comment]
One thing that a lot of people don't understand is that `ThemeContrast` is not used to change color of the Bar(navbar), but to only adjust contrast so the text is easier to read. For example if you have purple as a background then the best option is to give it `ThemeContrast.Dark` as that would change the text color to light to make it more readable.  So, I'm not so sure we need new `Custom` option. I think it would lead to more confusion, I feel.

We can possibly remove `ThemeContrast` completely as we have the way of calculating text color/contrast through the theme generator. The same thing is already working on button and other components. But by removing it then people who don't use theming would not be able to adjust contrast.

In the end, I think the best option is to leave `ThemeBarOptions` as it is, and then apply what needs to be applied to the Bar background and color.

```cs
public class ThemeBarOptions
{
    ...
    public ThemeBarColorOptions DarkColors { get; set; }
    public ThemeBarColorOptions LightColors { get; set; }
}
```

**Comment by MitchellNZ** [comment]
Thanks for your input @stsrki, that makes sense now 😊
It sounds good to me to remove `ThemeContrast` completely and control it how you mentioned.

> In the end, I think the best option is to leave `ThemeBarOptions` as it is, and then apply what needs to be applied to the Bar background and color.

I personally think that having `DarkColors` and `LightColors` for _only_ the Bar component doesn't really make sense...
If I was going to create a Light & Dark theme that users of my app could toggle, I would create two entirely separate `Themes` to manage this.

What makes more sense to me is to remove the `ThemeContrast` and `Background` (to avoid theming confusion) from the Bar component and have options on the `ThemeBarOptions` to set the `VerticalColors` and `HorizontalColors`.

```C#
public class ThemeBarOptions
{
    ...
    public ThemeBarColorOptions VerticalColors { get; set; }
    public ThemeBarColorOptions HorizontalColors { get; set; }
}
```

I personally would always want my Vertical Bar colors to separate from the Horizontal Bar colors!

**Comment by stsrki** [comment]
I think you missed my last sentence in the second paragraph

> But by removing it then people who don't use theming would not be able to adjust contrast.

I would leave `ThemeContrast` and `Background`, They are good option to quickly set something without going through the advanced scenario with themes.

I agree with your idea to separate vertical and horizontal theme options. When using them they would override whatever user has used before(`ThemeContrast` and `Background`).

**Comment by MitchellNZ** [comment]
Oops, yes I did miss that! 😅

Hmm, I take your point! It is nice to be able to quickly change component colors when needed (especially for things like `Buttons`). But I wonder how much that translates to a component that is really only design to be used once (like the Bar)? 🤔

Regardless, I still feel `ThemeContrast` is a rather confusing one!
Wouldn't it be better to offer `BackgroundColor` and `TextColour`, or only `Background` and somehow leverage "the way of calculating text color/contrast through the theme generator", you mentioned?

Also, what are your thoughts about removing the need for both `DarkColors` and `LightColors` on `ThemeBarOptions` and providing `VerticalColors` and `HorizontalColors`?

_**P.S**. this is an area I know little about the inner workings of Blazorise, so I am just bouncing my ideas!_

**Comment by stsrki** [comment]
`ThemeContrast` and `Background` are natively supported by the CSS frameworks, so they have a use case, see https://getbootstrap.com/docs/4.5/components/navbar/#color-schemes

Also I would leave `DarkColors` and `LightColors` on `ThemeBarOptions`. One use case would be when we, or user, want to have dark/light theme switch.

In the and I think best is to leave current options and properties and then grow from there. Horizontal and Vertical options can be split into two, with each option having light/dark options.

And of course, we should update documentation and explain it really well. With links to bootstrap, bulma and other frameworks so people can have some deeper knowledge on the subject.

**Comment by WillianGruber** [comment]
I just agree with everything @stsrki said. Also, predefined themes are planned, dont remember the issue though.

**Comment by MitchellNZ** [comment]
Sounds good guys!
Just wanted to get some alternative ideas out there!

But you're right @stsrki, that way makes the most sense.
I'll close this discussion issue and create a new one for the work of adding Horizontal Dark/Light bar theming options (to keep any confusion of this chat out of it).
