### ISSUE TITLE
Custom ModalTitle

### ISSUE THREAD

**Issue by bestpika** [stsrki/Blazorise#1124]
**Describe the solution you'd like**

In insert/edit template (popup mode), could you add a parameter let developer can custom the `ModalTitle`?

![image](https://user-images.githubusercontent.com/5698157/87106337-cf2a7700-c28f-11ea-8652-a47461aee0db.png)

**Comment by stsrki** [comment]
This is already done with #1070 and #1071 

It is available in `0.9.2-preview2`. You can get it by following https://github.com/stsrki/Blazorise#try-preview
