### ISSUE TITLE
Modifying the Breadcrumb component

### ISSUE THREAD

**Issue by grahamallwood** [stsrki/Blazorise#1125]
On the bootstrap site, there are a few different ways a Nav bar can be styled. As the Blazorise Breadcrumb component is a Nav element, are there any plans to allow it to be styled a few different ways?

Thanks

**Comment by stsrki** [comment]
Can your provide few examples and key features of what needs to be styled?

**Comment by grahamallwood** [comment]
Hi. I think i'm getting confused with the Bar component (which I've just found)!! Sorry.
