### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by chilikbayevabay** [stsrki/Blazorise#1128]
For example, the DataGrid Pager is in English only. I want to be able to change the text. Need localization of components. How to do?

**Comment by DDDenisSobek** [comment]
You can use Pre-, Next-, First- and LastButtonTemplate to change text with your localization. In 9.2.0 you can change with PageButtonTemplate page number.

**Comment by DDDenisSobek** [comment]
@stsrki Templates are missing in documentation. I will add it, if you want it.

**Comment by stsrki** [comment]
@chilikbayevabay only through the templates for now. But I think there should be some other, better way to handle localization. 

@DDDenisSobek yeah it would be good to add theme to the documentation. But on the dev092 as these features are still in preview.
