### ISSUE TITLE
Adding Tooltip (Property: Title)

### ISSUE THREAD

**Issue by Garios** [stsrki/Blazorise#113]
Hello,
is there any plan to add tooltips? On Material Design there is a guidline for it: https://material.io/design/components/tooltips.html#usage

Also it would be nice, to have the title-property.

**Comment by stsrki** [comment]
It is definitely on the list. Probably in the 0.8 version.

**Comment by stsrki** [comment]
Moving to backlog because I have behind the schedule with v0.8.
