### ISSUE TITLE
Slider refresh value

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1134]
Probably the same reason as #1053
If you click and release a slider, and then try moving it to left or right with the arrow keys, they will go back and fourth.

Expected behavior: smooth acting of slider

**Comment by stsrki** [comment]
What framework you're using?

**Comment by WillianGruber** [comment]
material, server-sided. I try moving with arrows holding right or left.
If you cant reproduce I'll make a gif

**Comment by stsrki** [comment]
I think what would be better. Until I got some time to create new material project for testing.

**Comment by WillianGruber** [comment]
Here is a gif for it:
C:\Users\willi\AppData\Local\Temp\c791482a-d5b1-4b7d-a3c8-c18b7ccc6289.gif
- In the start, I just hold right arrow, and it keeps coming back left
- When my pointer starts to circle, that means I'm not pressing any more keys and the sliders still moves right
- In the end, I try to click in a left position, and it jumps back to the right soon after

**Comment by stsrki** [comment]
Yeah that's strange. I'm still trying to reproduce it without luck.

**Comment by WillianGruber** [comment]
Did you test with material, server side?
