### ISSUE TITLE
Pop-Up Menu Width property in Vertical Bar

### ISSUE THREAD

**Issue by techierathore** [stsrki/Blazorise#1152]
**Menu Option Text gets Truncated on when the text exceeds menu width.**
When we have some menu options in a vertical bar whose title exceeds the width of the vertical menu it gets truncated and three dots appear. A way to solve this is to increase the width of the bar using **VerticalWidth** property of Bar using **ThemeBarOptions**. But there is **no option to increase the width of the pop-up menu which appears when the vertical bar is minimized**. see below screenshot  
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7636999/87739396-60a06880-c7fd-11ea-9b14-c44683271776.png)

**Solution**
There should be a **PopUpMenuWidth** property in Vertical Bar in **ThemeBarOptions**

**Comment by MitchellNZ** [comment]
This sounds like a good idea to me!

I will add it in as part of the 0.9.2 work I'm doing.

**Comment by angelru** [comment]
@techierathore how did you make the menu with blazorise?

**Comment by techierathore** [comment]
@angelru , I just followed the Sample application example , the only difference is that I added a Icon button in horizontal bar with Bartoggler implemented.
