### ISSUE TITLE
Sidebar Controls

### ISSUE THREAD

**Issue by tootaaa** [stsrki/Blazorise#1155]
**Dears,**
this is my first comment, first of all, need to thank you all on this efforts, this is beyond the mind to link bootstrap with Blazor technology,

In Sidebar control the Background property and  ThemeContrast are missed, this is important so everything can be controlled from Theme class after that
Background="Background.Dark" 
ThemeContrast="ThemeContrast.Dark"

Hope to be fixed in next near version
<Sidebar   @ref="_sidebar" Data="@_sidebarInfo">
   
</Sidebar>
BR,
Mohamed Farouk Shahin

**Comment by stsrki** [comment]
Hi @tootaaa, you should look into new vertical mode for Bar component https://blazorise.com/docs/components/bar/#vertical-bar-sidebar

Sidebar extensions will slowly become obsolete. The Bar component has all the properties you mentioned.

**Comment by tootaaa** [comment]
> Hi @tootaaa, you should look into new vertical mode for Bar component https://blazorise.com/docs/components/bar/#vertical-bar-sidebar
> 
> Sidebar extensions will slowly become obsolete. The Bar component has all the properties you mentioned.

Dear stsrki,
Thanks for your reply
I chose the side bar from begining as it has **Data** property which can be used to fill sub Items from C# code from DB
but the Bar Control doesn't has this property

do you have advise to solve this issue or this will be handled in next versrions

Thanks and BR,
Mohamed Farouk

**Comment by WillianGruber** [comment]
You can fill the bar component dynamically using treebuilder

**Comment by tootaaa** [comment]
Dear Willian, 
Thanks for your reply,
can you give me an example how to link Bar with tree builder

**Comment by tootaaa** [comment]
> You can fill the bar component dynamically using treebuilder

Dear Willian,
Thanks for your reply,
can you give me an example how to link Bar with tree builder

**Comment by WillianGruber** [comment]
https://www.google.com/amp/s/chrissainty.com/building-components-via-rendertreebuilder/amp/

**Comment by WillianGruber** [comment]
Just remember to use hardcoded indexes. DO NOT fill index with a variable!

**Comment by tootaaa** [comment]
> Just remember to use hardcoded indexes. DO NOT fill index with a variable!

**Dear Willian,**
Thanks for your support, appreciated
