### ISSUE TITLE
Select component wrong display value in AntDesign

### ISSUE THREAD

**Issue by akusmin** [stsrki/Blazorise#1156]
Select component displays Value instead of Label value.

Native HTML <select></select> element behavior is to display option label but not value on selection. 

Code to reproduce:
```
        <Select TValue="int">
            <SelectItem TValue="int" Value="1">One</SelectItem>
            <SelectItem TValue="int" Value="2">Two</SelectItem>
        </Select>
```

On selection there will be "1" but not "One".

IMO components behavior should be similar to native HTML.

Please either implement similar display value as it is implemented for native HTML either add component option to display Value or Label for selected option.

Thanks.

**Comment by akusmin** [comment]
UPDATE: such behavior is true for AntDesign only

**Comment by stsrki** [comment]
Fixed in the latest version
