### ISSUE TITLE
Uri(builder.HostEnvironment.BaseAddress) in program.cs (client-side)

### ISSUE THREAD

**Issue by SetantaMiguel** [stsrki/Blazorise#1157]
builder.Services.AddSingleton(new HttpClient
            {
                BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
            });

it returns error in .HostEnviroment

**Comment by stsrki** [comment]
All our demo apps are working with the the line without any issues so far.

**Comment by StefanOssendorf** [comment]
I can confirm that this works, too.
Are you on the latest Blazor release? They changed a lot in the RC before release.
