### ISSUE TITLE
Writing in TextEdit raises exception after updating 0.9.03 -> 0.9.1.*

### ISSUE THREAD

**Issue by almog-luz** [stsrki/Blazorise#1158]
**Describe the bug**
After upgrading from Blazorize 0.9.0.3 to 0.9.1.* the TextEdit (and other edit) components throw an exception when trying to write to them:

Unhandled exception rendering component: Could not find 'getCaret' in 'window.blazorise'.

**To Reproduce**
1. Create a page with a TextEdit Component
2. Run the program and write anything in the TextEdit

**Expected behavior**
No exception, the bound value/event changes properly

**Screenshots**
![image](https://user-images.githubusercontent.com/9496257/87875310-1d025600-c9d9-11ea-8152-0cfc3c8e365f.png)

**Additional context**
I tried this with an almost empty page with just this code and it still happens: 
(the regular InputText works properly)

![image](https://user-images.githubusercontent.com/9496257/87875496-36f06880-c9da-11ea-8067-1f4a3bf3aff7.png)

**Comment by stsrki** [comment]
Try refreshing browser by pressing Ctrl+F5.

**Comment by almog-luz** [comment]
Ok that worked, thanks!

Can you explain why the refresh was needed? Is there some sort of browser cache for the blazorise code?

**Comment by stsrki** [comment]
It's Blazor thing I think. There is nothing special about Blazorise.

I think best is to label css and js files by version or some id so they aren't cached by file.
