### ISSUE TITLE
  bar toggle color difficult to customize

### ISSUE THREAD

**Issue by FrederikNygart** [stsrki/Blazorise#1168]
First of all, thank you very much for this library. It is very well made, and i really find it useful for creating basic elements and expanding from there on.

**Problem**
When working with the bar item, i cannot set the color of the toggler, as the toggle icon is an image,which is a problem as i have a dark nav background.

![Screenshot_31](https://user-images.githubusercontent.com/15687959/88039640-24943d00-cb48-11ea-9cce-b02398c157bc.png)

![Screenshot_30](https://user-images.githubusercontent.com/15687959/88039725-3bd32a80-cb48-11ea-8a9c-bc7a2b34895c.png)

Making the toggler easier to customize and further documentation of how we use and customize toggler and dropdown functionality would be appreciated.

**Comment by stsrki** [comment]
@FrederikNygart First, thank you for good words :)

We are already actively working on improving the Bar component. Have you tried setting the `ThemeContrast `attribute to dark mode?

`<Bar Breakpoint="Breakpoint.Desktop" NavigationBreakpoint="Breakpoint.Tablet" ThemeContrast="ThemeContrast.Dark" Mode="BarMode.VerticalInline" CollapseMode="BarCollapseMode.Small" @bind-Visible="siderVisible">`

**Comment by FrederikNygart** [comment]
@stsrki  thank you for the quick reply. Yes, but i have chosen my own color palette, as i want different shades of my primary, secondary and so on. And therefore interact directly with the style attribute. 

But thank you for the tip. 

Another related feedback/question. Is it posssible to make the sidebar place itself under the topbar?

**Comment by stsrki** [comment]
This `ThemeContrast="ThemeContrast.Dark" `just controls the theme mode of the bar, you still need to apply other colors if needed.

Look at #1038 for sidebar placement.

**Comment by FrederikNygart** [comment]
Yes it works very well. 

But i guess i am arguing for a future solution where both the icon and color of the toggler i customisable. It is not somethin vitally important, just wanted to provide the feedback, so you knew it is wanted :)

Btw thank you for the link. Just what i was looking for.
