### ISSUE TITLE
Checking validations status of all fields through the Validations.StatusChanged event handler

### ISSUE THREAD

**Issue by cowsen** [stsrki/Blazorise#1171]
Referencing: Expose EditContext as an attribute of Validations #851

The StatusChange attribute of Validations now calls an event handler.  But within that event handler, I cannot call EditContext.Validate() to check the status of all field validations.  I would like to be able to enable/disable a button based on the validation status of all fields.

**Comment by stsrki** [comment]
Wouldn't `EditContext.Validate()` trigger the validation again? And in turn it would also call `StatusChange `again and again. I think better idea is to add additional property to `ValidationsStatusChangedEventArgs`, something like an array of validation result for each validated field.

**Comment by cowsen** [comment]
The EditContext.Validate() returns a boolean: true if all fields are valid and false otherwise.  I would definitely prefer a method that checks all fields and returns a simple boolean rather than for me to include that code in all my event handles.

**Comment by stsrki** [comment]
Well, `StatusChanged `already have that information under the `Status `property. It is going to `ValidationStatus.Success` only after all fields are valid.

```cs
Task OnValidationsStatusChanged(ValidationsStatusChangedEventArgs eventArgs )
{
    if ( eventArgs.Status == ValidationStatus.Success )
        // do something
    else
        // do something else

    return Task.CompletedTask;
}
```

**Comment by cowsen** [comment]
A combination of Validations.ValidatedAll and Validations.StatusChanged allows full control over enabling/ disabling a processing button.  There is a little overlap between their functions, so I use StatusChanged to disable and ValidatedAll to enable since it also covers initialization of the page.  Your use of eventcallbacks is a little cleaner than registering events.  Thank you for the help.
