### ISSUE TITLE
Material Progress Bar Percentage Indicator formatting

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1173]
Hi,

At https://materialdemo.blazorise.com/tests/progressbars
The "25%" value is hard to read, and not centered:
![image](https://user-images.githubusercontent.com/56033692/88109763-72796700-cb81-11ea-938d-5fc11892ad1e.png)

Compating with boodstrap:
![image](https://user-images.githubusercontent.com/56033692/88109793-7f965600-cb81-11ea-8c7e-070b183f2d14.png)

Is it possible to improve this, for readability purposes?

Thanks!

**Comment by janseris** [comment]
percentage is not there. only the number
