### ISSUE TITLE
Plan for upgrade to .Net 5

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1175]
Blazorise is still running on .Net Core 3.1.x so the plan is in long term to upgrade everything to .Net 5 since it is slowly coming to RC https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-7/ 

Initial plan is to add support for multiple target frameworks so we don't break existing people project. Sometimes after the release of .Net 5 preview 8 I will start refactoring components with some new features in that version. My guess is from 0.9.4 to be fully on .Net 5, but the time will tell.

**Comment by MitchellNZ** [comment]
Looking forward to this! 🎉

Let me know how I can help, when you get round to doing this.

**Comment by stsrki** [comment]
@MitchellNZ I think best is to start after we finish current milestone. But we'll see. Support for multiple frameworks shouldn't be a problem.

**Comment by stsrki** [comment]
Already done.
