### ISSUE TITLE
Add Reset() method to FileEdit

### ISSUE THREAD

**Issue by intiharj** [stsrki/Blazorise#1177]
I'm using the FileEdit component in a popup modal to enable the user the upload files.  After uploading one file, if the parent page is not refreshed, and the user opens the modal a second time, the FileEdit progress still shows 100%.  Would like the ability to reset the FileEdit component to 0%.

**Comment by stsrki** [comment]
Thanks for reporting this. I will try to add it for next release.

Not for me: https://stackoverflow.com/questions/20549241/how-to-reset-input-type-file
