### ISSUE TITLE
LayoutFooter floats with scrolling

### ISSUE THREAD

**Issue by cowsen** [stsrki/Blazorise#1178]
In version 0.9.03 the LayoutFooter was fixed to the bottom; but with version 0.9.1.2 it now floats with scrolling.

**Comment by MitchellNZ** [comment]
I have changes for this coming in 0.9.2 to make it more flexible and give you the option (more details #1089).

This will give you the option to set `Fixed` on the `LayoutFooter`.
- `Fixed=true` will sticky to the bottom of the browser window.
- `Fixed=false` (_default_) will sticky to the bottom of the `LayoutContent`.

**Comment by cowsen** [comment]
Thank you.
