### ISSUE TITLE
Autocomplete - add local ChangeTextOnKeyPress property

### ISSUE THREAD

**Issue by vbray1979** [stsrki/Blazorise#1179]
Hi, I would like to use the `Autocomplete` component but the global `ChangeTextOnKeyPress` set to false prevent the autocomplete to work on key press. Which is meant on purpose but, it somehow prevent the usage of autocomplete, indeed we do not expect to loose focus to get the suggestions.

Would it be possible to set the `ChangeTextOnKeyPress` at the component level and maybe make it available at all components level to override the global settings ?

**Comment by stsrki** [comment]
I have already implemented `ChangeTextOnKeyPress` on TextEdit but I forgot to include it into `Autocomplete` component. I will fix it and release it as part of next preview.

**Comment by mnelvers** [comment]
Can you implement ChangeTextOnKeypress on  NumericEdit?

**Comment by stsrki** [comment]
@mnelvers It's already implemented in `dev092 `branch and is already available as preview on MyGet feed.

**Comment by mnelvers** [comment]
We aren't using preview code, so is there a release date for it?

**Comment by stsrki** [comment]
Basically, "when it's done". I'm currently working mostly on a new project in parallel with Blazorise so it takes me longer than usual. It's not easy or fast do it all in my spare time 😅 

You can safely use a preview channel. It's not any less stable than in release. I'm also using it in production on several projects. In case you're going to update here are some things to be aware of https://github.com/stsrki/Blazorise/issues/1024

**Comment by mkchandler** [comment]
> Basically, "when it's done". I'm currently working mostly on a new project in parallel with Blazorise so it takes me longer than usual. It's not easy or fast do it all in my spare time 😅
> 
> You can safely use a preview channel. It's not any less stable than in release. I'm also using it in production on several projects. In case you're going to update here are some things to be aware of #1024

@stsrki Would love to see this released to production as well because we are running into this issue. Even if it's just this one fix. While I can test it locally from MyGet, getting a MyGet feed introduced into our entire CI pipeline is not feasible. Thanks for all your work on this project!
