### ISSUE TITLE
Is there an easy way to set Dark Theme for whole app

### ISSUE THREAD

**Issue by Sohojoe** [stsrki/Blazorise#118]
Hi, loving the project - is there an easy way to set Dark theme for my whole app - i'm using material 

(Sorry if this is a dumb question - i'm kinda of new to web)

**Comment by stsrki** [comment]
Hi, please look at this answer https://github.com/stsrki/Blazorise/issues/101#issuecomment-497053863

I'm still trying to figure best way to add theming to Blazorise. It will not be that soon so the given answer is you best way for now.

**Comment by Sohojoe** [comment]
Thanks!
