### ISSUE TITLE
BarDropdownToggle component hover/click does not work over chevron icon

### ISSUE THREAD

**Issue by intiharj** [stsrki/Blazorise#1180]
The BarDropdownToggle works as expected except in the area occupied by the chevron icon.  If I hover anywhere else on the BarDropdownToggle component, I see the pointer cursor.  If I hover over the chevron icon, I see the default (arrow) cursor.  Likewise, the BarDropdownToggle component does not respond to clicks on the chevron icon.  I think if this limitation were removed, the user experience would be moderately increased.

**Comment by MitchellNZ** [comment]
Thanks for reporting.

I also had noticed this as part of my changes for #1042.
I have fixed it in there and it will be part of the 0.9.2 release.

**Comment by intiharj** [comment]
Thank you, Mitchell.

John
434.228.1183

**Comment by MitchellNZ** [comment]
Fixed as part of #1287
