### ISSUE TITLE
CardImage generates empty space in excess when object-fit: scale-down is used

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1181]
Hi,

When using the CardImage, with object-fit: scale-down so it does not fill/stretch, the space it would use is still used by the Card,
```<CardImage Source="logos/Logo 256x256.png" Alt="Logo Image" Style="object-fit: scale-down;"/>```
This happens:
![image](https://user-images.githubusercontent.com/56033692/88336799-0119ef80-cd0c-11ea-853b-85158dc4dd9b.png)

What I think it should happen:
![image](https://user-images.githubusercontent.com/56033692/88336943-3cb4b980-cd0c-11ea-8840-cf39b1482d35.png)

**Comment by stsrki** [comment]
I guess `object-fit: scale-down` is some custom styling you applied on the image? So I don't think this is actually a Blazorise problem but more of a bootstrap/material.

**Comment by WillianGruber** [comment]
Ops, forgot to enclose source with ` ... updated the post, and here it is too:
``` <CardImage Source="logos/Logo 256x256.png" Alt="Logo Image" Style="object-fit: scale-down;"/>```

**Comment by WillianGruber** [comment]
So, when keeping the image size, it still draws a square with the height being the same as the width of the card... and then it makes huge space above and under the image...

But if this is not from Blazorise, I'll close this :)
