### ISSUE TITLE
ToggleIconVisible in Theme.DropdownOptions only works for split-dropdown

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1196]
Hi,

I updated the theme page with ToggleIconVisible in Theme.DropdownOptions, and seems the icon don't disappear from normal dropdown:
![image](https://user-images.githubusercontent.com/56033692/88513947-9a246100-cfbf-11ea-9f41-a76752cb3543.png)
![image](https://user-images.githubusercontent.com/56033692/88513970-a6102300-cfbf-11ea-90ba-0f93275056d4.png)

Also, please check extra space when the icon is hidden, it is not symmetrical:
![image](https://user-images.githubusercontent.com/56033692/88514051-c93ad280-cfbf-11ea-94f6-1528d34c8870.png)

Code: https://github.com/stsrki/Blazorise/pull/1146/commits/d05bd74b6f540f05041cb1a9ab3b38efd0b9021c

**Comment by stsrki** [comment]
That's strange. If I try remove it in developer tools it just resizes automatically. I will schedule it for 0.9.3.
