### ISSUE TITLE
want to reference local resources by default

### ISSUE THREAD

**Issue by 199621616** [stsrki/Blazorise#1197]
index.html or _Host.cshtml 

bootstrap.min.css
all.css

and

jquery-3.5.1.slim.min.js
popper.min.js
bootstrap.min.js

These external resources can not be used normally in some countries or regions. After using other accessible resources, we found several exceptions. It hasn't been debugged well.
You want to reference this resource by default, and all resources are required for direct loading. If the user needs to use external resources, the original referenced external resource address will be kept as the suggested address annotation.
For example:

href="lib/css/ bootstrap.min.css "
href="lib/css/fontawesome/ all.css

And

src="lib/js/jquery/jquery.slim.min.js
src="lib/js/dist/popper.min.js"
src="lib/js/bootstrap/bootstrap.min.js"

**Comment by stsrki** [comment]
Nothing stops you from using those files locally. You don't need to use them from CDN. I used a CDN as an example as it's easiest to setup for the most people, without downloading and copying those files to the wwwroot folder.

**Comment by 199621616** [comment]
是的，我们已经改用为直接引用本地源。但是，没有查清什么原因，一直有异常出现，导致Blazorise组件不能正常使用

**Comment by 199621616** [comment]
已找出原因。关闭它。
