### ISSUE TITLE
TableRowCell - vertical center

### ISSUE THREAD

**Issue by rad765** [stsrki/Blazorise#1199]
I have a table witch contains rows with three TableRowCell. The first TableRowCell contains an Icon, the rest contains text.
I would like to align (center)  the content of the TableRowCells vertically.  The **Alignment** attrinute only alows for horizontal center. Would it be possible to make an vetical alignment attribute?

![image](https://user-images.githubusercontent.com/16493230/88636913-cde3b180-d0b9-11ea-84ee-225c4dc400fc.png)

**Comment by stsrki** [comment]
Try using `Style` attribute. Every component should have it.

**Comment by rad765** [comment]
`<TableRowCell` Style="vertical-align: middle;" >

:-)
