### ISSUE TITLE
Support ColorEdit as Field in DataGridColumn

### ISSUE THREAD

**Issue by SunnyOswal** [stsrki/Blazorise#1200]
**Is your feature request related to a problem? Please describe.**
I would like to have color chooser as a row in DataGrid that is editable . 

**Describe the solution you'd like**
Support ColorEdit as Field in DataGridColumn

**Comment by stsrki** [comment]
You can just use `EditTemplate` and place the `ColorEdit` inside of it. https://blazorise.com/docs/extensions/datagrid/#edittemplate

**Comment by SunnyOswal** [comment]
thanks for super fast response. Tried and it worked fine.
