### ISSUE TITLE
[Question] Can you Edit inside a DataGrid, without having to click edit and save on every row?

### ISSUE THREAD

**Issue by codrzywolski** [stsrki/Blazorise#1201]
Hi All,

Apologies if this is not the right forum for this sort of thing, if so please direct me to the appropriate place and I'll be happy to post there.

I am building a DataGrid where there are many rows and on each row there is an Order Qty box that the users need to input for each Store in the grid. The user had a list of stores and qtys ahead of time and just wants to bang through the list then click save when they are done. 

Is there a way to do this in a Blazorize DataGrid? Again the key is to not have to click Edit on every row, just fill in the value, hit tab fill in the next value, hit tab, fill in the next value........ect........click save when done.

For Context, here is a screen shot of the Old application that I am rewriting. Ideally I'd like do it like this:

![image](https://user-images.githubusercontent.com/68967069/88846228-52662b00-d1b3-11ea-9e3f-bfc99223f16b.png)

**Comment by stsrki** [comment]
This is not an "official" way of doing the editing but you can use `DisplayMode` to render `NumericEdit`. Then bind it's value to the `contect.YourField`. Since context has a reference to the original list it should work, I guess. Then just save the original Data after you're done.

**Comment by codrzywolski** [comment]
Thanks I'll give that a try and let you know how it works.

**Comment by codrzywolski** [comment]
This looks to do the trick, Thanks!

```
<DataGridNumericColumn TItem="SalesOrderEntryViewModel" Field="@nameof(SalesOrderEntryViewModel.OrderQuantity)" Caption="Order Quantity" Editable="true">
            <DisplayTemplate>
                <NumericEdit TValue="long" @bind-Value="@context.OrderQuantity"/>
            </DisplayTemplate>
        </DataGridNumericColumn>
```
