### ISSUE TITLE
problem when speed typing in autocomplete

### ISSUE THREAD

**Issue by tamunaKap** [stsrki/Blazorise#1206]
I'm using autocomplete component which works fine on local machine, but it gets buggy on speed typing after deployment,
typed letters change place, sometimes letters even are deleted.

**Comment by stsrki** [comment]
It's going to be fixed with #1179. I just need to add new features introduced for `TextEdit`, like `ChangeTextOnKeyPress` and `DelayTextOnKeyPress`.

**Comment by vip32** [comment]
This also happens in the normal TextEdit component, very awkward an sluggish behavior but only happens when 2 way databinding is used.

```
<TextEdit @bind-Text="@customFilterValue" Placeholder="Search" />
``` 

browser: edge, blazorise: 0.9.1.2, blazor: server
is this a known issue too?

**Comment by stsrki** [comment]
@vip32 TextEdit is used inside of Autocomplete so that's why they're acting the same. The fix is available in `0.9.2-preview3` on MyGet feed.

In case you switch to preview this is how _fix_ is applied: `<TextEdit @bind-Text="@value" DelayTextOnKeyPress="true" />`

**Comment by CJMarinacci** [comment]
Can you apply this feature to the filter fields in DataGrid?

**Comment by stsrki** [comment]
Not directly but maybe I could add additional parameters to the DataGridColumn. In the meantime you can use FilterTemplate

```cshtml
<DataGridColumn TItem="Employee" Field="@nameof( Employee.FirstName )" Caption="First Name" Validator="@CheckFirstName" Editable="true">
    <FilterTemplate>
        <TextEdit Placeholder="Search name" DelayTextOnKeyPress="true" TextChanged="@(v=>context.TriggerFilterChange(v))" />
    </FilterTemplate>
</DataGridColumn>
```

**Comment by CJMarinacci** [comment]
Thanks, that works!
