### ISSUE TITLE
Material datepicker behaves strangely

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#1207]
Hi,

These scripts seems to interfere with each other.
```
    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Material/blazorise.material.js"></script>
```
When opening the date picker, the first try I try to edit the date, 2 calendars open up. The next times it is always the colored calendar:
![dateedit1](https://user-images.githubusercontent.com/56033692/88972581-2bc7f300-d28c-11ea-9083-aaaff60202ac.gif)

Commenting out one of those scripts, this happens:
![dateedit2](https://user-images.githubusercontent.com/56033692/88972638-400bf000-d28c-11ea-8c12-0d393df95c86.gif)

**Comment by Unlink** [comment]
I can confirm this, in Firefox it behaves like this, but, in Chrome it opens and closes immediately, so it is not usable in Chrome.

**Comment by stsrki** [comment]
Can you try with https://github.com/djibe/material ? There was an issue with daemonite material and since that project is not maintained anymore it is best to switch to the forked djibe material.

**Comment by Unlink** [comment]
When i updated material css and js it starts working on Chrome.
The weird stuff mentioned by @WillianGruber still persists on Firefox.

I think that it is because Firefox handles date imputs differently. And there is no posiibility to disable builtin calendar. https://github.com/revelrylabs/harmonium/issues/140

So i had to override DateEdit to be text input
```
@typeparam TValue
@inherits Blazorise.DateEdit<TValue>

<input @ref="@ElementRef" id="@ElementId" type="text" class="@ClassNames" style="@StyleNames" disabled="@Disabled" readonly="@ReadOnly" pattern="@Pattern" value="@CurrentValueAsString" @onchange="@OnChangeHandler" @onclick="@OnClickHandlerMaterial" placeholder="@Placeholder" @attributes="@Attributes" />
@ChildContent
@Feedback
```
And it seems working on Firefox and Chrome like this

**Comment by kaismatt** [comment]
@Unlink I would to copy your fix, but I don't find the method "OnClickHandlerMaterial". Can you indicate in where namespace this method is present?

@stsrki this issue is not flag like a bug, is it normal?

**Comment by stsrki** [comment]
@kaismatt 

It's a bug with **daemonite** material. The solution should be to download and use **djibe** version instead. https://github.com/djibe/material

**Comment by kaismatt** [comment]
> Can you try with https://github.com/djibe/material ? There was an issue with daemonite material and since that project is not maintained anymore it is best to switch to the forked djibe material.

@stsrki in the [documentation](https://blazorise.com/docs/usage/material/) the daemonite project is already recommended. This must be updated or the djibe project is not the futur version recommended for Blazorise?

**Comment by stsrki** [comment]
I will update it to mention djibe. Thanks

**Comment by Unlink** [comment]
@kaismatt 

I forgot, it is a method from parent class (Blazorise.DateEdit)
https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/DateEdit.razor.cs#L50
I needed to override it because I wanted to have a different date format

**Comment by stsrki** [comment]
Download links in documentation updated to lead to **djibe** material
