### ISSUE TITLE
LayoutSider not working in Blazor Webassembly

### ISSUE THREAD

**Issue by cowsen** [stsrki/Blazorise#1217]
LayoutSider worked beautifully in Blazor Server,  but when I ported to Blazor Webassembly the LayoutContent is under the LayoutSider.  It is as if the navigation bar occupies the whole screen, and then you have the main content underneath.

**Comment by MitchellNZ** [comment]
Could you please share a code example of your Layout structure?

**Comment by cowsen** [comment]
<Layout Sider="true">
    <LayoutSider>
        <LayoutSiderContent>
            <NavMenu />
        </LayoutSiderContent>
    </LayoutSider>
    <Layout Style="overflow-x:scroll">
        <LayoutHeader Style="text-align:right; margin-top:10px; margin-right:20px; color:mediumblue">
            <LoginDisplay />
        </LayoutHeader>
        <LayoutContent Style="margin-left:60px">
            <CascadingValue Value="@UserId" Name="UserId">
                <CascadingValue Value=StatusChanged Name="StatusChanged">
                    <CascadingValue Value="@Status" Name="Status">
                        @Body
                    </CascadingValue>
                </CascadingValue>
            </CascadingValue>
        </LayoutContent>
        <LayoutFooter Fixed="true" Margin="Margin.Is4" Style="font-size:18px; font-weight:bold; color:red">
            @Status
        </LayoutFooter>
    </Layout>
</Layout>

**Comment by cowsen** [comment]
My mistake!  I missed step 2 in your installation instructions:

2. Source filesPermalink
The next step is to change your index.html or _Host.cshtml file and include the CSS and JS source files:


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

<link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
<link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<script src="_content/Blazorise/blazorise.js"></script>
<script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
