### ISSUE TITLE
Add fluent ui

### ISSUE THREAD

**Issue by khoshroomahdi** [stsrki/Blazorise#1219]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I think it would be nice if you add microsoft fluent ui to this project. Microsoft has a css library as fluent ui. 
https://developer.microsoft.com/en-us/fluentui

**Comment by stsrki** [comment]
Thanks, I'm aware of FluentUI #1049 but currently there is no plan to add any new provider until API stabilizes. After 1.0 version is released I can start looking into adding new provider(s).
