### ISSUE TITLE
DataGrid dynamic column is not removed

### ISSUE THREAD

**Issue by JanVargovsky** [stsrki/Blazorise#1222]
**Describe the bug**
Have `DataGrid` with a `DataGridColumn(s)` and one column is dynamic, it means its wrapped in an `if` statement.
```razor
@if (showIdColumn)
{
    <DataGridColumn TItem="Employee" Field="@nameof( Employee.Id )" Caption="#" Sortable="false" Width="60px" />
}
```
When we change `showIdColumn` variable it should change whether its visible or not but it doesn't, it just adds more and more *same* columns as its added (showIdColumn was set to `true`).

**To Reproduce**
1. clone https://github.com/JanVargovsky/Blazorise/tree/bugreport/datagrid/dynamic-column
2. Run Blazorise.Demo.Bootstrap.RC
3. Go to https://localhost:44359/tests/datagrid
4. Uncheck Id column
5. Nothing happens - column is not hidden
6. Check Id column
7. Column is added as last

**Expected behavior**
5. Column should hide
7. Column is added back as second column.

**Screenshots**
As we repeat check/uncheck we end up with something like this:
![image](https://user-images.githubusercontent.com/13921215/89505442-ed6d8f00-d7c9-11ea-8804-16fc5ee80f83.png)

**Proposed solution for 5**
Hiding the column is quite simple to fix, we just need to remove the disposed column from datagrid. I can submit PR already - [see branch here](https://github.com/JanVargovsky/Blazorise/tree/bugfix/datagrid/dynamic-column).

**Discussion for 7**
Problem is how to determine position of lately hooked column. I believe in XAML UIs they add a position parameter that can be optional only for those dynamic scenarios or do you have idea how to determine its position?

**Comment by stsrki** [comment]
That's by design, When you define columns through razor they will internally be generated and added as a table columns. And they will be created just once. But in your case since you're using the `@if` it basically generates new component every time. This is more of a Blazor behavior and not Blazorise thing. It's not so obvious at first until it hits you in the face :)

Anyways, try use `Displayable` property to show or hide column. If that doesn't help I can maybe add some other _visibility_ property.

**Comment by JanVargovsky** [comment]
Thanks for quick response.
`Displayable` works for most of our columns - thats great. I was looking for the property but did not find it.

However we also plan to have ability to create columns based on filter such as customer or customer type, so its configurable (extensible). I think we don't mind recreating whole `DataGrid` once we switch e.g. to another customer, is there a way how to achieve this? For more context, we have a simple DTO that represents a column
```csharp
public class WorkflowItemCustomColumnDto
{
    public string Name { get; set; }
    public WorkflowItemCustomColumnType Type { get; set; }
    public Func<WorkflowItemDto, string> Content { get; set; }
}

public enum WorkflowItemCustomColumnType
{
    Text,
    Link
}
```
you have collection of those custom columns and just render them in a loop
```razor
@foreach (var customColumn in workflowItemCustomColumns)
{
    <DataGridColumn TItem="WorkflowItemDto" Field="@(nameof(WorkflowItemDto.Data))" Caption="@customColumn.Name">
        <DisplayTemplate>
            @if (customColumn.Type == WorkflowItemCustomColumnType.Link)
            {
                <Blazorise.Link To="@customColumn.Content(context)">
                    Open
                </Blazorise.Link>
            }
        </DisplayTemplate>
    </DataGridColumn>
}
```
