### ISSUE TITLE
RadioGroup vertical mode

### ISSUE THREAD

**Issue by Remy-Be** [stsrki/Blazorise#1224]
Hello !

**Describe the bug**

I have a problem with the radiogroup componentwith Bootstrap, I would like to display it in vertical mode via the 'Inline' property but it still remains horizontal.

**To Reproduce**
My component :
![image](https://user-images.githubusercontent.com/16755574/89625083-8c13f180-d897-11ea-910a-e400055dfc14.png)
Unexpected result :
![image](https://user-images.githubusercontent.com/16755574/89625171-acdc4700-d897-11ea-8e16-984c71fe099c.png)

If I manually replace 'btn-group' by 'btn-group-vertical' : 
![image](https://user-images.githubusercontent.com/16755574/89625234-c8dfe880-d897-11ea-912a-481c388141b1.png)

**Expected behavior**

I think the problem is with BoostrapClassProvider.cs line 87:
![image](https://user-images.githubusercontent.com/16755574/89624903-40f9de80-d897-11ea-8559-eb949e9968a0.png)

Shouldn't we add the class 'btn-group-vertical'?

Thank you very much !

Rémy B.

**Comment by stsrki** [comment]
The best option would be to add support for vertical mode. In the meantime try setting the `class`(must use lower case) attribute with "`btn-group-vertical btn-group-toggle`". By setting the `class `it should overwrite anything Blazorise is doing.

**Comment by Remy-Be** [comment]
Yes I did like that, thank you again ! 👍
