### ISSUE TITLE
Tooltip like view for DataGrid row cell value having long text

### ISSUE THREAD

**Issue by SunnyOswal** [stsrki/Blazorise#1226]
**Is your feature request related to a problem? Please describe.**
Nice view for long text in DataGrid row cell

**Describe the solution you'd like**
I would like to have a view of DataGrid column field values (like we see in a tool tip) when we hover over the row cell for text which is very long and can't fit nicely in the row cell. And the row cell value for that column can have some initial characters and then dots at the end.
Example:
In Cell it can look like: dsvsdghsgh......
When hovered over cell, it should give a tooltip like view and have full text: dsvsdghsgh. sjfkbsfkjlbslfjbl lfsljbfljbfljbf kfsjbksfb.

**Comment by stsrki** [comment]
I think this feature is too specific for your scenario to have it in data-grid. It's best for you to just use `DisplayTemplate` and add `Tooltip` where you need it.

**Comment by SunnyOswal** [comment]
don't know why i always miss the super cool DisplayTemplate feature of DataGrid. 
I tried and it works fine. Thanks again for quick help.
