### ISSUE TITLE
Alert close button doesn't work

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1239]
**Describe the bug**
When we click on the close button of the alert, the alert remain visible

**To Reproduce**
Put an alert like this 👍 
![image](https://user-images.githubusercontent.com/69345012/90000470-80a63900-dc90-11ea-8471-60bcaa98f2e1.png)

**Expected behavior**
Close when you click on the close button 

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
![image](https://user-images.githubusercontent.com/69345012/90000610-b0554100-dc90-11ea-8de8-15a948f1f756.png)

Thank-you

**Comment by stsrki** [comment]
You need to manually set the Alert Visible property. Here are the examples https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/ElementsPage.razor

**Comment by NicolasFVS** [comment]
Thats right, thank-you
