### ISSUE TITLE
How to customize paging button in datagrid

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1240]
**Is your feature request related to a problem? Please describe.**
I want to customize paging button and i want to use localisation for them in my datagrid

### Additional context
![image](https://user-images.githubusercontent.com/69345012/90017331-aa208e00-dcab-11ea-8476-2cf17df3699e.png)

How to have text in French for example?

Thank-you for your answer

**Comment by stsrki** [comment]
In preview version of Blazorise you can use these templates to customize pagination buttons

- FirstPageButtonTemplate
- LastPageButtonTemplate
- PreviousPageButtonTemplate
- NextPageButtonTemplate
- PageButtonTemplate

**Comment by NicolasFVS** [comment]
Thank-you I will try it

**Comment by NicolasFVS** [comment]
Can you give us an example, we don't know how to use this kind of template?

Thank-you

**Comment by stsrki** [comment]
Here you go :), It's just a standard usage of render templates in Blazor https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1

```cshtml
<DataGrid TItem="Employee"
            Data="@dataModels"
            ... >
    <PreviousPageButtonTemplate>
        <span style="color: blue; font-size: 2rem;">
            Get back
        </span>
    </PreviousPageButtonTemplate>
    <PageButtonTemplate>
        <span style="color: red; font-size: 2rem;">
            @context.PageNumer
        </span>
    </PageButtonTemplate>
    <NextPageButtonTemplate>
        <span style="color: green; font-size: 2rem;">
            Go forward
        </span>
    </NextPageButtonTemplate>
</DataGrid>
```

Notice that only `PageButtonTemplate` have `@context`, and it's because it needs to have page number for each button.

**Comment by NicolasFVS** [comment]
I thought thats it works like that, but in my project it doesn't recognize PageButtonTemplate. any idea?

![image](https://user-images.githubusercontent.com/69345012/90250535-7759cf80-de3c-11ea-9894-2696ca4c3e67.png)

**Comment by stsrki** [comment]
You probably missed when I mention it's only available in preview. You can get it by following https://github.com/stsrki/Blazorise#try-preview

**Comment by SimonAndrews** [comment]
Would it be possible to provide away to allow full override of the pagination display via a <PagerTemplate> or similar to the other templates in the DataGrid? and provide a context that has the current page and either total records or total pages.

This would allow full customisation for people to display the paging in anyway they need to.

**Comment by stsrki** [comment]
We already have something similar in work but it's still not ready. Check https://github.com/stsrki/Blazorise/pull/1580
