### ISSUE TITLE
Collapsed sidebar with long submenu's

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1241]
We use the sidebar component and show in the submenu a list of projects. In the non collapsed version it will show a scrollbar when the list becomes too long what is ok. But the collapsed version grows off the screen. Is there any way to improve this. Like hide the items that don't fit eg `overflow-y: hidden`

![image](https://user-images.githubusercontent.com/3843546/90025445-b4c32f00-dc7b-11ea-9d60-db52c3ad6b47.png)

**Comment by stsrki** [comment]
@MitchellNZ cay you comment on this?

**Comment by MitchellNZ** [comment]
Thanks for reporting.

I have also noticed this and have a "band-aid fix" for next release as part of #1042.
Basically what it will is cap the height of the dropdown list to 60/70% of the view-height, and make the rest scrollable.

Once I get chance to work on #1137, I can provide a much better fix for this issue!
This should give us the ability to better position the dropdown list on the screen (based of its own height + the view-height) and only making in scrollable when needed.

**Comment by MitchellNZ** [comment]
@njannink Could you please see if this is resolved for you in 0.9.3? 
I have added a fixed max height for now - if this isn't what you want, we can look into alternatives.

**Comment by njannink** [comment]
I updated to 0.9.2 today, but the sidebar layout is now completely screwed. So I probably need to update a bit my css before I can give a definitive answer. 

@MitchellNZ I see you wrote 0.9.3. Is it that version or the just release 0.9.2?

**Comment by MitchellNZ** [comment]
@njannink oops - that was a typo! I meant **0.9.2**.

Hmm - possibly. 
Let me know how you get on with it, there have been quite a few changes/fixes.

**Comment by stsrki** [comment]
@njannink Don't forget to clear the cache. There were a lot of changes in js and css files.

**Comment by stsrki** [comment]
@njannink Did clearing the cache help?

**Comment by njannink** [comment]
No, but after I updated a bit of my css it was working fine again. Need to migrate to the new Sidebar extension to see what of my custom code I can remove. This defect can be closed
