### ISSUE TITLE
Datagrid custom filter and ReadData

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1245]
**Describe the bug
I have a problem when I use ReadData and CustomFilter whitin Datagrid. We never enter in the callback OnCustomFilter

**To Reproduce**
Create Datagrig filled within OnReadData Callback and try to implement custum filter

Also please provide a sample code or point us to a minimalistic GitHub repo
![image](https://user-images.githubusercontent.com/69345012/90108751-11414f80-dd4b-11ea-940a-ef5c10f17263.png)
![image](https://user-images.githubusercontent.com/69345012/90108802-261de300-dd4b-11ea-9938-fcacd2118130.png)

Thank-you

**Comment by stsrki** [comment]
OnCustomFilter is working only for in-memory data. There is no way to know how to filter when `ReadData` is used. The data can be fetched from Rest API call, a call to DB via EF, or million other ways of fetching the data. That's why CustomFilter is possible only with in-memory data.

**Comment by stsrki** [comment]
🤔 The only way I can think of is to have additional parameter `CustomFilter` in `DataGridReadDataEventArgs` and then you make a filtering by yourself.

**Comment by NicolasFVS** [comment]
Thank-you for your answer I will try it

**Comment by NicolasFVS** [comment]
Thats fine Thank-you
