### ISSUE TITLE
Is it possible to force a modal view to stay open

### ISSUE THREAD

**Issue by Sohojoe** [stsrki/Blazorise#125]
Currently a user can click away from a modal (or press escape) and it will close - I want to put in a 'are you sure' pop up so they do not lose what they have entered

thanks!

**Comment by stsrki** [comment]
Actually there is already a way to stop the modal from closing but it is currently not visible to users. I think I can do it fairly quick today and publish it in 0.7.8 which was scheduled for publish today.

**Comment by stsrki** [comment]
0.7.8 is published. You can see the usage for closing in the docs for [modal](https://blazorise.com/docs/components/modal/#closing)

**Comment by Sohojoe** [comment]
Awsome, thanks!
