### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by arc488** [stsrki/Blazorise#1256]
When I open my app, it doesn't load properly and I get the following error in the console.

```
blazorise.js:518 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getBreakpoint (blazorise.js:518)
    at blazorise.js:601
```
 Line 518:  `return window.getComputedStyle(document.body, ':before').content.replace(/\"/g, '');`

Line 601: `window.blazorise.breakpoint.lastBreakpoint = window.blazorise.breakpoint.getBreakpoint();`

**Comment by stsrki** [comment]
JS error usually comes when you miss some scripts. Try Ctrl+F5 and also check that all the css files are present.

@MitchellNZ ?

**Comment by MitchellNZ** [comment]
Most common reason for this is including the JavaScript inside the `<head>` element (as reported in #1122).

If you also have it in the `<head>`, try moving it to the `<body>` below the `<app>` element.

If that doesn't work, could you please post an example of your code from `index.html`?

**Comment by MitchellNZ** [comment]
@arc488 any update?
Or can I close this?

**Comment by stsrki** [comment]
Closing since there is no feedback.
