### ISSUE TITLE
Linebreak in Tooltip

### ISSUE THREAD

**Issue by BuzzDee3000** [stsrki/Blazorise#1257]
**Describe the bug**
I have the multiline property set to true, but I can't control the linebreak. "<br/>" tags rendered as text.

**To Reproduce**
1. Create a Tooltip component
2. Try to set a text with a linebreak

**Expected behavior**
It would be an option enable html content in tooltip text so the user can format the text.

**Additional context**
I'm not sure this is a bug or a feature request.

**Comment by stsrki** [comment]
Can you try with `&#10;` for new line break?

**Comment by BuzzDee3000** [comment]
This will also appear as text.
![grafik](https://user-images.githubusercontent.com/17178704/90253724-e84fb600-de41-11ea-8ed8-1df51adbf57c.png)

**Comment by stsrki** [comment]
It seems it is a bug. Sooner I can get on this is for next milestone.

**Comment by lancelarsen** [comment]
What about html in tooltip?  Thank you for all your work on this library btw!  Very awesome.

**Comment by stsrki** [comment]
@lancelarsen I don't think it's possible to use html with current setup. For that scenario the best option is to use something like Popper https://popper.js.org/

**Comment by lancelarsen** [comment]
So in non-Blazor apps, have used Tooltipster (http://calebjacob.github.io/tooltipster/) with great results -- can definitely use HTML in that...  So don't see any reason we wouldn't be able to get that to work here. <shrug>
