### ISSUE TITLE
Remove Bootstrap's dependency on JS

### ISSUE THREAD

**Issue by gb1337** [stsrki/Blazorise#1258]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Remove Bootstrap's dependency on JS and use native blazor DOM manipulation instead.

### Additional context
This is not an issue but more of a suggestion or even a rambling at this point. I'm new to Blazor AND Bootstrap. However, a big thing I like about Blazor is that you can basically throw Javascript out the window. But using some of Bootstrap's components, you're forced to bring JS back in because that's what Bootstrap needs. Now would it be possible to design Bootstrap razor components that do not use JS but instead make use of Blazor native DOM manipulation functions? Maybe that's what Telerik's Blazor UI does, not sure?

**Comment by stsrki** [comment]
Unfortunately there is no way around it. You still must use JS for DOM manipulation. Basic things can still be done with Blazor but if you want some slightly more non-standard things then JS is the only option. Trust me, I would be the happiest to throw away JS. But until there is support for DOM access in WebAssembly this is what we need to live with. Oh, and I bet Telerik is also using JS.

**Comment by gb1337** [comment]
I don't doubt you for a second, but isn't manipulating the DOM with JS completely redondant if Blazor can re-render part of the DOM at will? What's a use case where JS can do something that Blazor can't? Again I know you're right but I'm trying to learn this technology and I like going deep and not take things at face value. And yes you're right Telerik uses JS for the parts where they say they can't use Blazor. But I'm not finding more detailed explanations to help me learn the limitations of Blazor.

**Comment by stsrki** [comment]
You can look at `blazorise.js` to see everything in details. Bu to mentioned a few things not possible at the time of implementing them:

- Option to add or remove classes from `body` tag
- Get info about the DOM element, like **getBoundingClientRect**, and similar
- Easy preventDefault without some spaghetti code, I know you can use `@onclick:preventDefault` but most of times it will not work as you want it
- input masks
- addEventListener on document element
- reading of files
- and many more

**Comment by gb1337** [comment]
Very instructing, thank you very much for answering. I will close this discussion now.
