### ISSUE TITLE
Hybrid Blazor apps 

### ISSUE THREAD

**Issue by rmzn2907rmzn** [stsrki/Blazorise#1259]
I try this link

https://devblogs.microsoft.com/aspnet/hybrid-blazor-apps-in-mobile-blazor-bindings-july-update/

throw exception this  code line
 builder.Services.AddBlazorise(options =>
            {
                options.ChangeTextOnKeyPress = false;
            }).AddBootstrapProviders()
              .AddFontAwesomeIcons();

**Comment by stsrki** [comment]
Hybrid apps are not supported. Maybe I can focus on supporting them in the future but for now, it's not a priority. Closing the ticket

**Comment by oleinselmannhaagensen** [comment]
Is Blazor Hybrid supported now
