### ISSUE TITLE
DateEdit component not working on Safari (OS X) - replace with new component?

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#1260]
Today I discovered that the DateEdit component does not work properly on Safari OS X (iPhone is ok). The calendar dropdown icon is missing and non-functional. The reason for this is not so much to do with Blazorise as more to do with the fact that Apple have not implemented the standard html5 date picker on Safari for input type="date" components on which the DateEdit relies:

https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

So in order to resolve this either the DateEdit component needs overhauling or a new additional DatePicker component adding to Blazorise - what would people prefer?

At this time I have been replacing the DateEdit component with NodaTimePicker:
https://github.com/nheath99/NodaTimePicker

This works well but carries a lot of Nodatime functionality that I do not need. I could try and port this to Blazorise, but replace any nodatime functionality with standard DateTime.

Any suggestions on where to go from here?

**Comment by stsrki** [comment]
I would rather for `DateEdit` to stay as native `input type="date"`. In the end, it's the Apple laziness and ignorance to standard that it doesn't work on their .

If you would like to create a new component then it's best to do it as an extension for Blazorise. tnx

**Comment by stsrki** [comment]
Closing this as there is no plan to leave `input type="date"`. As stated in https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari, you can try with Placeholder as a workaround.

**Comment by robalexclark** [comment]
Fair enough. I have written a blazor component for date - [](https://github.com/robalexclark/BlazorDatePicker ). It is a port of a noda time version (with timezone removed). Its a but rough around the edges but could be a starting point for a component if there is any interest.

**Comment by stsrki** [comment]
Dates and date pickers are really, really, complex area. Better to have native support than reinvent things. It's a lot less pain 😅
