### ISSUE TITLE
Link button

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1266]
**Is your feature request related to a problem? Please describe.**
I want to have a button that of clicked, will function the same as a classic link. What is the best way to go about it?
doing:

```
<Button>
           <Link To="Identity/Account/Register">Register</Link>
</Button>

```

Causes the resulting button text to have the same color as link, instead of button color. Also I do not want to use OnClick and redirect through a method.
I noticed that if I do this:

```
<Link To="Identity/Account/Register">
     <Button>Register</Button>
</Link>
```

The colors start looking fine, but I can no longer connect buttons using `<Buttons>` tag

**Describe the solution you'd like**
An example of correctly creating such buttons being added to documentation. We already have BarLink which does a simmilar thing, but that is for the `Bar` object. Also I would like to avoid manually styling the `Link` object.

### Additional context
I am just starting with blazorise and I was never very good with HTML in the first place so please go easy on me.

**Comment by stsrki** [comment]
You're right, a button link is missing currently. I planned to do it as I need it also in one of my project. Not sure jet on how to best implement it. There are two options:

- Add `ButtonType.Link` Type to existing Button
- Create completely new `ButtonLink` component

The first one could be the easiest, but I need to see if all existing properties makes sense for button link. If not they I will just go with new component.

**Comment by Luk164** [comment]
Thank you, I would appreciate if it was the same component personally. Currently my workaround is just using plain links and adding `Class="btn btn-primary"`. Maybe you could add the link to button as an automated setter? Also technically OnClick and LinkTo do not actually exclude each other. You could do something like call the OnClick and then redirect once it is finished,

**Comment by stsrki** [comment]
Yeah, that how my thinking goes also. I'l probably just expand existing Button in the end.

**Comment by Luk164** [comment]
Please let me know when I can try a preview, I am currently working on a new project and I do not want to have to redo all buttons later on.

**Comment by Luk164** [comment]
@stsrki Hello, I would like to ask you if you made any progress

**Comment by stsrki** [comment]
I plan to do it over the weekend. And then release it as part of next preview.
