### ISSUE TITLE
DataGridColumn should inherit object type from it's parent DataGrid

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1267]
**Is your feature request related to a problem? Please describe.**
Having to explicitly state type for each column is bothersome, especially since it is always equal to it's parent datagrid.

**Describe the solution you'd like**
Instead of explicitly stating object type for each column, could we inherit it from the parent DataGrid?

**Comment by stsrki** [comment]
Not possible at the moment. There is still an open issue on .NetCore repo for this https://github.com/dotnet/aspnetcore/issues/7268

Since this a Blazor issue I will close this ticket. Thanks!

**Comment by Luk164** [comment]
@stsrki I would like to reopen this issue because of https://github.com/dotnet/aspnetcore/issues/29349. It should finally be possible.

**Comment by stsrki** [comment]
It is for .Net 6 only. And as long we support .Net 5 we will not be able to implement it. The plan is to support .Net 5 until the third quarter of 2022.

**Comment by Luk164** [comment]
@stsrki Noted, I will bring it up again then
