### ISSUE TITLE
Async Validations

### ISSUE THREAD

**Issue by danbaechtold** [stsrki/Blazorise#1270]
Validation with async Validator functions don't work (when e.Status is set asynchroniously):

```html
<Validations @ref="validations" ValidateOnLoad="false" StatusChanged="OnValidationsChanged">
    <Field>
        <FieldLabel>Label</FieldLabel>
        <Validation Validator="@ValidateFunc">
            <TextEdit @bind-Text="@Text">
                <Feedback>
                    <ValidationError>Error</ValidationError>
                </Feedback>
            </TextEdit>
        </Validation>
    </Field>
</Validations>
```

```javascript
private async void ValidateFunc(ValidatorEventArgs e)
{
    // e.Status = ValidationStatus.Success; // THIS WORKS

    bool valid = await RemoteValidateFunc(e.Value);
    e.Status = ValidationStatus.Success; // THIS DOESN'T WORK (StatusChanged not fired)

    // validations.ValidateAll(); // WORKAROUND (but invalidates all blank fields)
}
```

It would be very helpful if this could be supported - or is there another way this should be done?

**Comment by stsrki** [comment]
For this scenario I should probably refactor Validator and convert it to `EventCallback `instead of plain `event`. It makes sense as it should be more flexible, especially for this kind of situations.

But since it's probably a larger change, and breaking change I will schedule it for one of next milestones.

**Comment by CPlusPlus17** [comment]
Is there a workaround? I'm facing multiple problems to get this working:

- I'm using fluent validations
- One validation uses a REST endpoint

The HttpClient only work as async, waiting with .Result isn't supported with Blazor. 

`validations.ValidateAll()`

Throws an 

`Object reference not set to an instance of an object.`

at this stage in the code path. So I'm out of solutions for the moment?

**Comment by stsrki** [comment]
The first prototype of async validation #1958
