### ISSUE TITLE
DirtyClasses call might not be necessary anymore

### ISSUE THREAD

**Issue by vstribrny** [stsrki/Blazorise#1275]
In `BaseComponent.DirtyClasses` method, there is a comment:
`use this until https://github.com/aspnet/Blazor/issues/1732 is fixed!!`

As the https://github.com/aspnet/Blazor/issues/1732 issue is fixed, the DirtyClasses call might not be necessary anymore and we could gain some performance benefits when removing it.

**Comment by stsrki** [comment]
If I remember it correctly it was a completely different problem and the comment has just left there. `DIrtyClasses `call should always be called whenever there is a change on some property that affect classanames. One of the ways to optimize it to skip the call in setters if the property value is not changed.
