### ISSUE TITLE
Table Component Behaves Strangely with C# Razor

### ISSUE THREAD

**Issue by hammonjj** [stsrki/Blazorise#1281]
**Describe the bug**
When working with a table, Blazorise has strange interactions with surrounding C# blazor code. I haven't experimented to see if this is the case with other Blazorise components or just this one

**To Reproduce**
If you create a razor component with the following code, you will see the issue. 

EDIT: I'm struggling with the code formatting, so I am uploading a screenshot of the code sample

![BlazoriseTableCode](https://user-images.githubusercontent.com/4194631/91322602-2bcced00-e77d-11ea-9b77-59798f4e5146.PNG)

<Table>
    <TableHeader>
        <TableRow>
            <TableHeaderCell>Day 1</TableHeaderCell>
            <TableHeaderCell>Day 2</TableHeaderCell>
            <TableHeaderCell>Day 3</TableHeaderCell>
        </TableRow>
    </TableHeader>
    <TableBody>
        <TableRow>
            @{DateTime dtCurrent = @DateTime.Now;}
           <TableRowCell>@dtCurrent.ToString();</TableRowCell>
            @{dtCurrent = dtCurrent.AddDays(1);}
            <TableRowCell>@dtCurrent.ToString();</TableRowCell>
            @{dtCurrent = dtCurrent.AddDays(1);}
            <TableRowCell>@dtCurrent.ToString();</TableRowCell>
        </TableRow>
    </TableBody>
</Table>

**Expected behavior**
I would expect the first cell in the second row to be today, the second cell to be tomorrow, and the third to be the day after that. Instead, each cell shows a datetime that is two days from now (note that I took the screen shot on 8/26)

**Screenshots**
![BlazoriseTable](https://user-images.githubusercontent.com/4194631/91322175-ab0df100-e77c-11ea-9d86-889891ea922d.PNG)

**Comment by stsrki** [comment]
I think this is Blazor issue and it is a known limitation. See rhis https://stackoverflow.com/questions/54812427/for-loop-not-returning-expected-value-c-sharp-blazor

**Comment by hammonjj** [comment]
I'll have to take a look at that, but if I use a standard table (ex. <table class="table">) it works as I would expect

**Comment by stsrki** [comment]
This was already answered so closing this.
