### ISSUE TITLE
eFrolic BarToggler menu does not have required checkbox

### ISSUE THREAD

**Issue by Kronos11** [stsrki/Blazorise#1282]
**Describe the bug**
eFrolic BarToggler is missing the checkbox input which is required to make the Menu items show up once minimized

**To Reproduce**
1. Go to the eFrolic navbar demo site: https://efrolic.github.io/css//navbars/h
2. Shrink the window until the hamburger appears 
3. Click on the hamburger
4. See that the menu items show up correctly

Now go to the eFrolic blazorise demo site and try to do the same, notice that the menu items do not show up when the hamburger is clicked.

**Expected behavior**
The menu items should show up on clicking

**Additional context**
adding an input checkbox with id of e-menu resolves the issue.
<input type="checkbox" id="e-menu">

**Comment by stsrki** [comment]
The same this is happening for other providers. And I think @MitchellNZ has already fixed this bug on his branch but I'm not sure if it's fixed for eFrolic also?

**Comment by MitchellNZ** [comment]
@Kronos11 @stsrki Yup, this will be fixed in 0.9.2 as part of #1042 & #1091

**Comment by stsrki** [comment]
Excellent! @MitchellNZ you rock! :)

Closing this issue.
