### ISSUE TITLE
Question: how can I make square button with icon?

### ISSUE THREAD

**Issue by bazarniy** [stsrki/Blazorise#1284]
Hello! I need just button with icon. There are no another content. Just icon. If I do this:
```
<Button Color="Color.Link">
    <Blazorise.Icons.Material.Icon Name="MaterialIcons.Create" />
</Button>
```
I get rectangular button. There are margins and paddings because of min-width and padding preferences in .btn class.
Is there way to do this without custom styles?

**Comment by stsrki** [comment]
Hi, there is already a task for this #1220. Your only option for now is to create your own component or just use regular html tags. Until we add the component to Blazorise.

**Comment by bazarniy** [comment]
Ok! Thank you
