### ISSUE TITLE
Title tag conflicts with Blazor new Title Tag

### ISSUE THREAD

**Issue by AhmedHemdan21** [stsrki/Blazorise#1288]
Microsoft has introduced a Title tag for influencing the HTML head

> Multiple components use the tag 'Title'. Components: Blazorise.Title, Microsoft.AspNetCore.Components.Web.Extensions.Head.Title

I think we could add a prefix for Title to avoid the conflict

https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-8

**Comment by stsrki** [comment]
I'm not a fan of prefixes so I would rather not use them. The new components are behind `Microsoft.AspNetCore.Components.Web.Extensions.Head.Title` namespace and I guess it will not be in conflict too often. Also if people are using Blazorise they would expect to use Blazorise component by default. And in cases they need those new tags they can always write a full path.
