### ISSUE TITLE
How to custom TimeEdit values

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1290]
**Describe the bug**
TimeEdit print only six hours and six minutes after its time value

**To Reproduce**
Click on the clock in TimeEdit

**Expected behavior**
I whant to have all days hours and only 00 and 30 for minutes for instance

**Comment by stsrki** [comment]
What browser you use? And on what culture is your system running?

TimeEdit is basically just a wrapper around `<input type="time">` so it's the browser that really controls it at this point.

**Comment by stsrki** [comment]
Closing since no additional info was provided.
