### ISSUE TITLE
Toggle RowDetail

### ISSUE THREAD

**Issue by davazlan** [stsrki/Blazorise#1291]
I have a DataGrid with 

`@bind-SelectedRow="@selectedPlant"`
`DetailRowTrigger="@((item) => item.Projects?.Count > 0 && item == selectedPlant)"`

currently, when clicking on a row, I can see the detailrow (nice 👍). However, I'd like the possibility to hide the detailrow when clicking on it's parent row again.

Is this possible?

**Comment by stsrki** [comment]
Maybe you use a combination of `RowClicked` and `DetailRowTrigger`, where on RowClicked event you could toggle the row state.

**Comment by davazlan** [comment]
That worked! I don’t know why I didn’t think about it. Thanks!! 😊


Kind Regards,
David Vazquez Landa
CAE IT @ Digitalization & IT

Phone: +49 621 60-97951, Mobile: +49 173 307-4665, Email: david.vazquez-landa@basf.com
Postal Address: BASF SE , GE/DI - Q920, Carl-Bosch-Strasse 38, 67056 Ludwigshafen am Rhein, Germany
[cid:image001.png@01D6850A.C5071070]
BASF SE, Registered Office: 67056 Ludwigshafen, Germany
Registration Court: Amtsgericht Ludwigshafen, Registration No.: HRB 6000
Chairman of the Supervisory Board: Kurt Bock
Board of Executive Directors:
Martin Brudermueller, Chairman; Hans-Ulrich Engel, Vice Chairman;
Saori Dubourg, Michael Heinz, Markus Kamieth, Wayne T. Smith
