### ISSUE TITLE
Autocomplete - Selection list does not close

### ISSUE THREAD

**Issue by kthe** [stsrki/Blazorise#1293]
When the selection list is open and you select another control the list remains open.

This can be seen in the sample https://rcbootstrapdemo.blazorise.com/tests/components

It should be closed with current text value remaining.

**Comment by CPlusPlus17** [comment]
Can confirm this issue, is there a chance to close the dropdown list by code? We are using multiple autocomplete fields in combination and should close old dropdown list if another field is selected.

**Comment by stsrki** [comment]
It's but and should be fixed. Since it's not critical I will schedule it for the next milestone.
