### ISSUE TITLE
Autocomplete - If no matches are found, a small empty dropdown is shown.

### ISSUE THREAD

**Issue by kthe** [stsrki/Blazorise#1296]
When using the autocomplete, If no matches are found, a small empty dropdown is shown.

This is shown in the samples at https://rcbootstrapdemo.blazorise.com/tests/components

Either do not show the dropdown while nothing matches, or add an option to configure behavior to show a user provided message on no matches.

**Comment by jlopez788** [comment]
Yeah, I found this as well. I'll give it a try and see if I can add a parameter to display when no value has been found.
