### ISSUE TITLE
Setting Modal Size removes margin

### ISSUE THREAD

**Issue by AhmedHemdan21** [stsrki/Blazorise#1298]
Modal works fine if ModalContent tag size not set but whenever I add size for ModalContent the Modal goes to the most left top with no margin at all 
for example 
`<ModalContent Centered="true" >` this would work fine 
but with `<ModalContent Centered="true" Size="ModalSize.Small">` the modal breaks my workaround for this is to set the Modal tag class to  `Class="modal-dialog modal-xl"` after that it works fine

**Comment by stsrki** [comment]
I just tried it and there is no issue on my side. 

Try and see if you have some custom css that overlap with modal styles. Also make sure that none of your page content is going outside of screen boundaries, That can also affect the modal placement.
