### ISSUE TITLE
TextEdit exception

### ISSUE THREAD

**Issue by qwerty101key** [stsrki/Blazorise#1299]
Hi, i am trying to use TextEdit component.

**My steps:**

1. Create new project from template (Blazor Server);
2. Add these rows into ConfigureServices method of startup.cs:
> services.AddSingleton<ComponentMapper>();
> services.AddBlazorise().AddBootstrapProviders().AddFontAwesomeIcons();
3. Add this row into Configure method of  of startup.cs:
> app.ApplicationServices.UseBootstrapProviders().UseFontAwesomeIcons();
4. Add TextEdit into index.razor:
> <Blazorize.TextEdit />
5. Click F5;

**And the result is the following:**
> [2020-09-07T02:14:01.097Z] Error: Microsoft.JSInterop.JSException: Could not find 'blazorise' in 'window'.
> Error: Could not find 'blazorise' in 'window'.

![1  Index razor](https://user-images.githubusercontent.com/60126495/92342421-45095e00-f0da-11ea-897c-732d99cf4702.png)
![2  Startup cs](https://user-images.githubusercontent.com/60126495/92342429-489ce500-f0da-11ea-904d-3b4f33074bff.png)
![3  Result](https://user-images.githubusercontent.com/60126495/92342434-4c306c00-f0da-11ea-96b3-40744b5376cd.png)

**Comment by MitchellNZ** [comment]
Looks like you a missing the JavaScript file required for the JSInterop methods.

Take a look at this step in the docs:
https://blazorise.com/docs/start/#2-source-files

**Comment by qwerty101key** [comment]
I tried several Blazorise-components at this moment (Switch, Memo, DataGrid, DataTable, and others) and all of them worked without missing JavaScript file. Now I added all required files and this component worked too.
Thanks a lot!

**Comment by MitchellNZ** [comment]
Not every component needs to use JSInterop, so some would have worked fine without it.

Glad to hear, no worries!
