### ISSUE TITLE
Autocomplete not working properly

### ISSUE THREAD

**Issue by riccardobecker** [stsrki/Blazorise#1301]
We use the Autocomplete component inside an EditForm like this:

<Blazorise.Field>
            <FieldLabel>Search...</FieldLabel>
            <Autocomplete Data="@items"
                          TextField="@((item) => item.id)"
                          ValueField="@((item) => item)"
                          SelectedValue="@selectedItem"
                          SelectedValueChanged="@ItemSelected"
                          Placeholder="Select item..." />
        </Blazorise.Field>

The Autocomplete only works when the component loses the focus (by pressing TAB e.g.).

I would expect by typing part of the item.id a dropdown list shows up while typing.

**Comment by stsrki** [comment]
Maybe you have `ChangeTextOnKeyPress` property set to false? It can be enabled globally in **Startup.cs**. To enable it only on Autocomplete you need to have preview version of Blazorise.

**Comment by riccardobecker** [comment]
Yes i think you are right! Which version do I need to use for this?

**Comment by stsrki** [comment]
I believe it was introduced in 0.9.2.preview3 but it's best to go with latest version. 

https://github.com/stsrki/Blazorise#try-preview

**Comment by stsrki** [comment]
@ricardoromaobr Have you tried with `ChangeTextOnKeyPress `?
