### ISSUE TITLE
Link component error in foreach loop

### ISSUE THREAD

**Issue by tzengshinfu** [stsrki/Blazorise#1305]
**Describe the bug**
Getting errors while placing link component in foreach loop.

**To Reproduce**
`@foreach (var url  in new List<string>(){"user/settings", "#foo"}) {
    <Link To="@url">
        Link text
    </Link>
}`

**Expected behavior**
compile with no errors.

**Screenshots**
![error2](https://user-images.githubusercontent.com/2170033/92883832-d57dd080-f443-11ea-89a0-ee5b6d90faa2.png)

**Additional context**
IDE:Visual Studio 2019 16.7.3
Framework:.dotNet Core 3.1
Project Type:Blazor Server

**Comment by stsrki** [comment]
Try writing it as `<Blazorise.Link>`. It's a bug in Visual studio where it expects Link to be a regular html `<link>` tag.

**Comment by tzengshinfu** [comment]
That's right, thank you very much.
