### ISSUE TITLE
Toggle open or close of Sidebar

### ISSUE THREAD

**Issue by Duelbat** [stsrki/Blazorise#1306]
Not an issue, but rather how does one toggle the visibility of the Sidebar?

So say adding an OnClick event for a button we can open the Sidebar if closed or close it if open?

Thanks
Luke

**Comment by stsrki** [comment]
The simple example can be found in the documentation https://blazorise.com/docs/extensions/sidebar/#manual

Note however that Sidebar component is slowly being obsolete so you should try to go with the Bar component that has much more features and it's going to be improved even more.
