### ISSUE TITLE
Bar component pushing content to bottom of page at small screen sizes

### ISSUE THREAD

**Issue by Duelbat** [stsrki/Blazorise#1308]
I followed the steps to set up the BAR component in my Visual Studio project.

All works fine, except when I narrow the screen with the mouse, my page contents are pushed to the bottom of the page. Please see screenshot.

**To Reproduce**
1 Set up Blazorise  for the application as per instructions from the Website.
2. Add standard BAR code (vertical) to the _mainLayout page.
3. Narrow the page with the mouse, the page contents are pushed to bottom.

**Expected behavior**
Content on page should remain at the top, but is pushed to bottom of page.

![blazorize](https://user-images.githubusercontent.com/46680351/93142608-7a492800-f73a-11ea-93d2-b3bfa01c017e.png)

**Comment by MitchellNZ** [comment]
Could you please show a code example of how you added the Vertical `Bar` from you `_MainLayout` page?

**Comment by Duelbat** [comment]
Thanks for the reply Mitchell
The standard Blazor app (.net core hosted) comes with a Navmenu component. I deleted the code in there and added in the Blazorise BAR code from the website, see code below. I suspect there is some CSS floating around that may be interfering with the Blazorise stuff. 

<LayoutSiderContent>
    <Bar Mode="BarMode.VerticalInline"
         CollapseMode="BarCollapseMode.Small"
         Breakpoint="Breakpoint.Desktop"
         NavigationBreakpoint="Breakpoint.Tablet"
         ThemeContrast="ThemeContrast.Dark">
        <BarBrand>
            <BarItem>
                <BarLink To="">
                    <BarIcon IconName="IconName.Dashboard" />
                    Blazorise Demo
                </BarLink>
            </BarItem>
        </BarBrand>
        <BarMenu>
            <BarStart>
                <BarItem>
                    <BarLink To="#home">
                        <BarIcon IconName="IconName.Dashboard" />
                        Home
                    </BarLink>
                </BarItem>
                <BarItem>
                    <BarLink To="#docs">Documentation</BarLink>
                </BarItem>
                <BarItem>
                    <BarDropdown>
                        <BarDropdownToggle>
                            <BarIcon IconName="IconName.Edit" />
                            Dropdown
                        </BarDropdownToggle>
                        <BarDropdownMenu>
                            <BarDropdownItem>Action</BarDropdownItem>
                            <BarDropdownItem>Another action</BarDropdownItem>
                        </BarDropdownMenu>
                    </BarDropdown>
                </BarItem>
            </BarStart>
        </BarMenu>
    </Bar>
</LayoutSiderContent>

**Comment by MitchellNZ** [comment]
Oh I see, It most likely is the CSS then!

If its not the CSS, the important to follow the documentation on exactly how to have the layout structured for `_MainLayout`.

As [this example](https://blazorise.com/docs/components/layout/#with-sider) shows:
``` HTML
<Layout Sider="true">
    <LayoutSider>
        <LayoutSiderContent>
            Sider
        </LayoutSiderContent>
    </LayoutSider>
    <Layout>
        <LayoutHeader Fixed="true">
            Header
        </LayoutHeader>
        <LayoutContent>
            Content
        </LayoutContent>
    </Layout>
</Layout>
```

**Comment by Duelbat** [comment]
Hey Mitchell !!!

Thank you ever so much!!! I used your guidelines and all is working fine now!!
I can now go ahead with my project thanks to you!
Kind regards
Luke

**Comment by MitchellNZ** [comment]
Great to hear!
