### ISSUE TITLE
Not a feature request, just plain gratitude !

### ISSUE THREAD

**Issue by Duelbat** [stsrki/Blazorise#1309]
I just want to thank the author of this suburb Blazor component suite!! This gives us functionality that is practical and super time saving. And it looks fantastic!! Love the BAR component, it sets the "bar", no pun intended!

Kind regards
Luke

**Comment by stsrki** [comment]
Thank you for the kind words 😊 

And I believe @MitchellNZ is also proud of his work on Bar component!

**Comment by LukeTOBrien** [comment]
Also just to add that I am pleased you are spelling 'Blazorise' with an **S** and not a **Z** as in 'Blazorize'.  
American's would prefer 'i**z**e', but 'i**s**e' is the correct spelling.
