### ISSUE TITLE
Tooltip on focus

### ISSUE THREAD

**Issue by AchimStuy** [stsrki/Blazorise#1313]
**Is your feature request related to a problem? Please describe.**
Bootstrap offers option to show Tooltip triggered by focus. How can this be done with Blazorize?

**Describe the solution you'd like**
Tooltip has a Property `Trigger` of flags enum type `TooltipTrigger` which can be `hover`, `focus` or both (default `hover`).

***Alternative solution***
Provide Methods `Show()` and `Hide()` to Tooltip, which could be called manually in a `focus`-EventHandler. Currently I set `AlwaysActive`, but I get warning "Component parameter 'AlwaysActive' should not be set outside of its component."

**Comment by AchimStuy** [comment]
I could also implement it and create PR if you explain me, where to implement. :)

**Comment by stsrki** [comment]
Seems like a cool feature to have. In case you're going to implement I think you need to focus on code in `Blazorise\Styles\_positions.scss`. Notice the usage of SCSS. To compile it into CSS you will need to install VS extension called Web Compiler: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebCompiler

Other than that you will have to probably create separate CSS classes for each of the enums and then apply them in `BuildClasses` in `Tooltip.razor.cs`.

**Comment by AchimStuy** [comment]
Much easier: For me it would be enough to add the pseudo-classes `&:focus-within::before` and `&:focus-within::after` to the `_positions.scss\@mixin tooltip-hover`. Then Tooltip would be triggered also on every focus-within. (It is already triggered by focus of the tooltip - maybe a bug?) In my opinion it would make sense to be also triggered by focus-within. (I need it to go through the inputs of a form via Tabulator - there hover is useless.)

Do you want to add this or shall I and create PR or should we create the complex behavior proposed in the first post?

**Comment by stsrki** [comment]
Should be a lot easier with the new tooltip. Going on the list.
