### ISSUE TITLE
Snackbar won't work on the page with Authorize attribute

### ISSUE THREAD

**Issue by MuhammedBalta** [stsrki/Blazorise#1314]
**Describe the bug**
Snackbar won't work on the page with Authorize attribute. This issue occurs only the first load of the page. Snackbar starts working after refreshing the page
```

@page "/"
@attribute [Authorize]
<Button Clicked="@(()=>snackbar.Show())">Snackbar</Button>

<Snackbar @ref="snackbar">
    <SnackbarBody>
        Message
    </SnackbarBody>
</Snackbar>
@code{
    Snackbar snackbar;
}
```

**Comment by stsrki** [comment]
Closing because I was unable to reproduce it.
