### ISSUE TITLE
Ability to disable spell checking on text, memo and autocomplete components

### ISSUE THREAD

**Issue by jffaust** [stsrki/Blazorise#1316]
First things first, awesome framework. I really enjoy working with it 😎 .
I've got a small feature request. I'm currently using the Autocomplete component to select from a list of git branches and those often contain usernames and other words that aren't meant to be spell checked.

I would like to have the ability to specify if an input of text type should have spell checking enabled or disabled.

```
<Field>
    <FieldLabel>Branch</FieldLabel>
    <Autocomplete Data="@_repoBranches.Branches"
        TextField="@((item)=>item)"
        ValueField="@((item)=>item)"
        SelectedValue="@_tmpSelectedBranch"
        SelectedValueChanged="@BranchSelectionChangedHandler"
        Placeholder="Search..." 
        **Spellcheck="false"** />
</Field>
```

**Comment by stsrki** [comment]
Try just setting the `spellcheck="false"` attribute. All Blazorise component support attribute splatting and it should be applied to the underline input element.

**Comment by jffaust** [comment]
Ahh, didn't know about that feature. Pretty handy.
Thanks!
