### ISSUE TITLE
Change Width of Sider

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1319]
Can you change the width of the Sider? I tried forcing it with Style="width: 300px", for example, but it doesn't work.

Also, can someone explain why when Sider="false" the content (on the right) disappears? It seems to do the opposite of what I'd expect Sider="false" to do: if it's false, the Sider should disappear. I seem to be fundamentally misunderstanding something.

**Comment by WillianGruber** [comment]
You can do that with the Theme options

**Comment by stevenlupo** [comment]
> You can do that with the Theme options

You mean this?
```
SidebarOptions = new ThemeSidebarOptions
{
     Width = "800px"
}
```
this does not seem to have any effect.

**Comment by WillianGruber** [comment]
If you are using Bar, try the BarOptions

**Comment by stevenlupo** [comment]
> If you are using Bar, try the BarOptions

I think I did (not at work computer right now), the problem I believe is that `BarOptions` returns type `ThemeBarOptions`, which does not contain anything for horizontal width.

source:
https://github.com/stsrki/Blazorise/blob/3f3d58b8aaf775222bc5987a9d16da106d4a1ffe/Source/Blazorise/Theme.cs

**Comment by MitchellNZ** [comment]
The terminology `Vertical` and `Horizontal` is used to describe the Bars behaviour.

A `Horizontal` bar is designed for the top bar (which has no width, it's always 100%).

A `Vertical` bar was introduced to replace the need for the `Sidebar` extension and use the already familiar bar component (likewise, this has no need for height, as it's always 100%).

In the `ThemeBarOptions` you will be able to set the Vertical bars width (as you found with `VerticalWidth`) and the Horizontal bars height (`HorizontalHeight` available from 0.9.2).

As for the `Sider=false`, this is a `Layout` specific option that describes to the Layout what it should do. It is not designed to show/hide the sider (as briefly mentioned in the [Layout docs](https://blazorise.com/docs/components/layout/#layout)).

If you are wanting to show/hide the bar, you can do so using the `Breakpoint` options available on the `Bar`, or by using the `BarToggler` component.

However, the `BarToggler` is not fully supported for the vertical bar yet in 0.9.1.X, but it is in 0.9.2 which is now available on the preview channel.

Hope this helps clear things up for you. If you have any suggestions on how things might be better worded or described, please let us know!

**Comment by stevenlupo** [comment]
> It is not designed to show/hide the sider (as briefly mentioned in the Layout docs)

I did read the docs, where is it mentioned?

>A Vertical bar was introduced to replace the need for the Sidebar extension 

Good to know, I was wondering why there was a separate Sidebar extension and started to think maybe it was old as I didn't see a reason for it.

>which is now available on the preview channel.

Sounds like I want to try this preview channel, how do I do that? 

Thanks for your help.

**Comment by stsrki** [comment]
@stevenlupo You can try the preview channel by following these instructions https://github.com/stsrki/Blazorise#try-preview

**Comment by stevenlupo** [comment]
> You can try the preview channel by following these instructions https://github.com/stsrki/Blazorise#try-preview

I followed the instructions, but how exactly do i _get_ it? Does it show up when I go into _Manage NuGet Packages_? I don't see it there.

**Comment by stsrki** [comment]
It should show in a sources selectbox under a name BlazoriseMyGet. And you also need to tick "Include prerelease" checkbox.
