### ISSUE TITLE
Customize Edit popup in DataGrid

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1323]
**Is your feature request related to a problem? Please describe.**
I need to customize the content of the popup. All fiels are printed in 2 columns.

**Describe the solution you'd like**
I would like, at least, to choose the order, number of colums  for each rows.

### Additional context
![image](https://user-images.githubusercontent.com/69345012/93777906-9ca0e100-fc25-11ea-8178-6b5b93821e15.png)

**Comment by stsrki** [comment]
@AjaxSantos has implemented this feature in #1071. You can use `PopupFieldColumnSize` on a column to define how much space the editing field will occupy.

**Comment by stsrki** [comment]
PS. Sorry, I forgot to mention that the PopupFieldColumnSize feature is available only in the 0.9.2 preview channel. https://github.com/stsrki/Blazorise#try-preview

**Comment by NicolasFVS** [comment]
Ok thank-you and do you know the date of availability for the new version please?

**Comment by stsrki** [comment]
Basically, when it's done. There is not a date planned to finish.

**Comment by angelru** [comment]
@NicolasFVS @stsrki I am not done knowing how to use the data grid yet, can't I add a button to add a new item if the button is not inside the grid? How do I change the text of the modal of the datagrid?

**Comment by Luk164** [comment]
@NicolasFVS Heads-up, 0.9.2 is out today
