### ISSUE TITLE
DataGrid Lockup when upgrading from version 8.8.4 to current release

### ISSUE THREAD

**Issue by taylorjimbo** [stsrki/Blazorise#1327]
I upgraded from version 8.8.4 an noticed that when I refresh the data and call StateHasChanged() the DataGrid is frozen. 

Here is a snippet from the Blazorise.Demo (DataGridPage.razor) that mimics the issue and is similar to how I'm populating the data in 8.8.4. I start with a blank List and then populate it during either the OnInitializedAsync or OnAfterRenderAsync. I tried the Onreaddata, but then I lose all the build in sorting and filtering. 

`  

    bool _updated = false;
    List<Employee> dataModels = new List<Employee>();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!_updated)
        {
           List<Employee> dataModels = new List<Employee> {
                new Employee {Id = 1,FirstName = "Christoper",LastName = "Moorton",EMail = "cmoortonm@gizmodo.com",City = "Jambangan",Zip = null,Salary = 76787.57m },
                new Employee {Id = 2,FirstName = "Trina",LastName = "Seamen",EMail = "tseamenn@foxnews.com",City = "Song",Zip = "54120",Salary = 43598.06m },
                new Employee {Id = 3,FirstName = "Douglass",LastName = "Amor",EMail = "damoro@house.gov",City = "Castillos",Zip = null,Salary = 49865.8m, Childrens=2, IsActive = true },
                new Employee {Id = 4,FirstName = "Reeta",LastName = "Acom",EMail = "racomp@fc2.com",City = "Baoping",Zip = null,Salary = 61296.4m },
                new Employee {Id = 5,FirstName = "Chandler",LastName = "Franzonetti",EMail = "cfranzonettiq@archive.org",City = "Emin",Zip = null,Salary = 67458.07m, Childrens=1 }

           StateHasChanged();
          
           _updated = true;
        }

    }`

**Comment by stsrki** [comment]
Try setting `_updated = true;` before `StateHasChanged();`

**Comment by stsrki** [comment]
Also, you should check for `firstRender` and initialize data only once.

**Comment by taylorjimbo** [comment]
I have a breakpoint on the line `"_updated = true;"`
With or without checking the` firstRender` flag it never gets to the line `"_updated = true;"` Using the Demo if I comment out the `<DataGrid> </DataGrid>` it makes it to the `"_updated=true;"`

If I roll back to version 8.8.4 everything works.

**Comment by taylorjimbo** [comment]
I found the issue in MY code. A cut and paste error. I was re-declaring the `dataModels` object. I do not know why this caused a lockup. I would have expected the `DataGrid` to be empty. Also, I had original declaration as  `List<Employee> dataModels = null;`
