### ISSUE TITLE
Object Validation

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1329]
**Is your feature request related to a problem? Please describe.**
We would like to have addon on validation

**Describe the solution you'd like**
Is it possible to have the field with a right star when its empty and required before inserting any character?
And the field become red only when you try to validate forms.

### Additional context
Now its like this when you open the form and we have to add manually the riht star on label
![image](https://user-images.githubusercontent.com/69345012/94011916-6049be00-fda8-11ea-9eb4-6475b5e20326.png)

**Comment by stsrki** [comment]
No there is currently no way of doing this. It might be doable by adding a `StatusChanged` event on each `Validation` component. That way you could know of each change and then update your UI accordingly. 

I will need to investigate more about this to see if would break any existing validation.

**Comment by NicolasFVS** [comment]
Thank-you. Perhaps its a new intersting feature

**Comment by stsrki** [comment]
I just quickly tried it and it seems it's working fine. Might be something fishy because if I remember it correctly I already tried to implement it before but there was an issue with multiple event calls. Anyways I will let you know how it goes :)

**Comment by stsrki** [comment]
I think this will do it #1331 

Going to have some more testing before I merge it.
