### ISSUE TITLE
Scatter Chart

### ISSUE THREAD

**Issue by SebiRaff** [stsrki/Blazorise#1330]
Hey, I need your help how I can make a Scatter-Chart with x and y for the position. I looked at the issues, but I didn't understood the solution. I can't figure out what I did wrong, but on my Chart the points are like always on the line and one point per line.
Here's my code:
```
@code
{
    public class Point
    {
        public Point(double _x, double _y)
        {
            x = _x;
            y = _y;
        }
        public double x { get; set; }
        public double y { get; set; }
    }
        
    private Chart<Point> lineChart = new Chart<Point>();

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await lineChart.Clear();
        await lineChart.AddLabelsDatasetsAndUpdate(Labels, GetLineChartDataset());
        lineChart.OptionsJsonString= "{ \"elements\":{\"line\":{\"tension\": 0}},\"animation\": {\"duration\": 0} ,\"scales\": { \"yAxes\": [{ \"ticks\": { \"min\": 0.6, \"max\": 1.9 } }] },\"legend\":{\"display\": false}}";
    }

    LineChartDataset<Point> GetLineChartDataset()
    {
        return new LineChartDataset<Point>
        {
            Label = "FEQ",
            Data = new List<Point> { new Point(1.12,1.45) , new Point(1.22,1.69)},
            Fill = false,
            PointRadius = 5,
            BorderDash = new List<int> {4,8 },
            LineTension = 0,
            ShowLine =false
        };
    }

    string[] Labels = {"", "Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "December" };
            }
    <Chart @ref="lineChart" TItem="Point"></Chart>

}
```
Then it looks like this:
![Chart](https://user-images.githubusercontent.com/69220509/94013755-d5b68e00-fdaa-11ea-8349-95b310fa1905.PNG)

And what I want is that it looks like this but without the title:
![untitled](https://user-images.githubusercontent.com/69220509/94014409-c5eb7980-fdab-11ea-9761-13fb3f51b51a.png)

How can I do it? I really have no idea and didn't understood the solutions of the other issues

**Comment by stsrki** [comment]
Hi, instead of `OptionsJsonString` use `OptionsObject`. It will be a lot easier than formating the json string.

Example:

```cs
<LineChart @ref="lineChart" TItem="DataPoint" OptionsObject="@someOptions">

object someOptions = new
    Scales = new
    {
        X = new
        {
            Type = "linear",
            Position = "bottom"
        }
    }
};
```

Currently there is no Scatter chart in Blazorise. You might be able do it with the base Chart and if that doesn't work for you I might consider adding it for next milestone.

**Comment by SebiRaff** [comment]
Hi, Thank you for your fast response. I have to try, but it would be great, if you add it, maybe there are more people that need it.
When is the next milestone planned?
And thank you a lot for your great job. When I become 18, I will donate you some coffee's.

**Comment by stsrki** [comment]
There is no release date, basically when-it's-done. I hope to finish it soon, once I'm done with another project for Blazorise. Also, I agree it's best to create a new chart type. That is the option I think.

And ☕ is always nice but not required 😄

**Comment by SebiRaff** [comment]
Thank you a lot. Have a great day 🥇

**Comment by stsrki** [comment]
https://github.com/stsrki/Blazorise/discussions/2127
