### ISSUE TITLE
BarLink Ignores Attributes

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1332]
I wanted to do this so the page would open in another tab:

`<BarLink To="http://example.com" target="_blank" Title="this is the title of help" >Help</BarLink>`

but it would ignore the target.

I looked at the code and `BarLink` completely ignores attributes that are passed in if `To` is not null.

See https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/BarLink.razor

**Comment by stsrki** [comment]
Definitely a bug. It seems I have accidentally forgotten to define attributes for the `Link` component. Thank you for letting me know.

**Comment by stevenlupo** [comment]
Cool, I did something useful :)
