### ISSUE TITLE
Carousel: How to I change the color of the indicators/controls?

### ISSUE THREAD

**Issue by csk1nner** [stsrki/Blazorise#1338]
Thanks for building out this great body of work!  I'm trying to change the indicators on the carousel control to something that is much darker as the content I'm showing is mostly white centric.  Is there a style/css that I can set to do this?

**Comment by stsrki** [comment]
There are no built-in theme options for the carousel and I might consider adding them. In the meantime, if we're talking about bootstrap provider for Blazorise then you can just set CSS, eg:

```css
.carousel-indicators li{
    background-color: red;
}
```

PS. you can always inspect elements and see what are their classes. Blazorise is always using native ones for each of the providers, Bootstrap, Bulma Antdesign, etc. and then apply what you need. Hope I help a little :)

**Comment by csk1nner** [comment]
Thanks so much for the fast response.  That's exactly what I was looking for!
