### ISSUE TITLE
[Question]How to make TextEdit fill the remaining horizontal space?

### ISSUE THREAD

**Issue by tzengshinfu** [stsrki/Blazorise#1339]
**Describe the problem**
I tried to set TextEdit to fill the remaining horizontal space, and keep TextEdit and Field Label to stay on the same line, but failed.
![Image 004](https://user-images.githubusercontent.com/2170033/94217485-b0de2a00-ff14-11ea-80db-f5ae36b02d70.png)

**To Reproduce**
![Image 007](https://user-images.githubusercontent.com/2170033/94168672-72b71b00-fec0-11ea-9a0b-2690f1390ad2.png)

**Expected behavior**
![Image 10](https://user-images.githubusercontent.com/2170033/94218024-0961f700-ff16-11ea-85aa-d0406424e8a9.png)

**Comment by stsrki** [comment]
All Blazorise providers work with 12 column sizes. So instead of `ColumnSize.IsFull` you should set `ColumnSize.Is10`. That way with a label that is already set to `Is2` it will be full width (12).

**Comment by tzengshinfu** [comment]
Ok, I got it. Thank you.
