### ISSUE TITLE
BarToggler does not work

### ISSUE THREAD

**Issue by Unterhosengummi** [stsrki/Blazorise#1342]
First of all: Thanks for your great work 👍 

I've some problems to get the BarToggler of Bar working. I've copied the example code from https://blazorise.com/docs/components/bar/#top-bar-with-dropdown. If I resize the screen the hamburger button appears as expected, but clicking on it seems to have no effect. The content of the nav bar is not displayed.

Did I forget something or is the documentation not complete at this point?

Thanks in advance

**Comment by MitchellNZ** [comment]
I assume you are referring to the horizontal (top) bar?

If so, this has been broken for a couple of releases, sorry!

However, I have fixed in 0.9.2 (which is available on the preview channel).

See https://github.com/stsrki/Blazorise/issues/1091 for related issue.

**Comment by stsrki** [comment]
Hi, you can get the preview version from MyGet https://github.com/stsrki/Blazorise#try-preview

Since this is fixed I will now close this ticket.

**Comment by Raysapps** [comment]
I've installed version 0.9.2 but unfortunately the toggle menu is not working. Could you please suggest if  I am missing something ?

**Comment by iberisoft** [comment]
I have found this bug in the latest stable version 0.9.1.2 although older version 0.9.0.3 had no problem.

**Comment by MitchellNZ** [comment]
@Raysapps Have you tried clearing your browser cache? 
This fixed required CSS/JS changes.

@iberisoft this is fixed in 0.9.2, please see above for how to test out the 0.9.2 preview.

**Comment by Raysapps** [comment]
@MitchellNZ 👍  will  try .
