### ISSUE TITLE
Chart Ability To Remove And Set Data On Datasets

### ISSUE THREAD

**Issue by Yoropiata** [stsrki/Blazorise#1343]
### **Problem**
I need to move a single Datapoint on a Dataset while I have multiple other datasets that live on the same chart.
The solution I thought of exists in chart.js but there is no adaption in the chart.js library.

### **Suggested Solution**
An implementiation that provides a:

1. SetData(int dataSetIndex, params Point[] data) on BaseChart (Replace data of specific dataset)
2. RemoveDataset(int dataSetIndex) on BaseChart (Remove specific dataset)
3. ReplaceDataset(int dataSetIndex, TDataSet dataset) (Replace specific dataset, keep index position)

**Comment by Yoropiata** [comment]
I will look into fixing it myself, but I have no idea how to test if it works as I have no experience working with Nuget libaries.

**Comment by stsrki** [comment]
You don't need NuGet packages for testing. Everything you have is already in the solution. You can run tests by modifying `ChartsPage.razor` in `Blazorise.Demo` project. And to run the demo you need to start `Blazorise.Demo.Bootstrap.Server`, or any other project that ends with _Server_.

**Comment by Yoropiata** [comment]
@stsrki I have made some ui tests and fixed some logic errors.

Do you want the test ui code I used committed into the PR  aswell? #1344

**Comment by stsrki** [comment]
Yes, you can include them in the PR. If they make sense for the demo I will leave them, or I can just remove them after I review the code. So yeah, its better to include it :)

**Comment by Yoropiata** [comment]
I have added the sample code used for testing to the PR, it should be ready for review.
