### ISSUE TITLE
Question DataGrid

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1349]
First of all, thanks for all this work, I don't know if there will be this functionality because I haven't seen it in the documentation, is there to export the datagrid in csv or excel? Can I modify the datagrid layout or edit modal layout in datagrid?

**Comment by stsrki** [comment]
Hi, thank you for trying out Blazorise. As of your first question, there will never be any export of data from DataGrid. Blazorise is a UI library and that kind of functionality would not make sense for Blazorise.

For your second question. There are going to be some new features coming up with v0.9.2 that will allow you to change column sizes and some other layout properties. You can try the preview https://github.com/stsrki/Blazorise#try-preview

**Comment by angelru** [comment]
Many thanks, an amazing job of you
