### ISSUE TITLE
Possible to set / add autocomplete TextEdit attribute

### ISSUE THREAD

**Issue by odskee** [stsrki/Blazorise#1351]
Currently using the TextEdit component in a number of areas and I'm having insane issues with Chrome's autofill suggestions being completely wrong (everything has appropriate ID's etc.).

The easiest solution is to just disable autocomplete as it's not needed for the data I'm capturing - is there a way of passing this to the HTML <Input> element with the TextEdit component so it can be disabled?

**Comment by stsrki** [comment]
Yes, just set the `autocomplete="off"` on `TextEdit`. Every Blazorise component has support for attribute splitting so it should be applied to the `input` in this case.
