### ISSUE TITLE
</Link> warning in Visual Studio

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1353]
[The docs give an example](https://blazorise.com/docs/components/link/#example) of how to use the `Link `component:

```
<Link To="user/settings">
    Link text
</Link>
```
But in Visual Studio 2019, I get this warning with a squiggle beneath the `</Link>`:

> Closing tag supplied for self-closing element. Remove closing tag.

What is causing this?

**Comment by stsrki** [comment]
It's a bug in visual studio tooling https://github.com/dotnet/aspnetcore/issues/18685 Still waiting for the bug to be fixed...

As a workaround just use a full path with namespace, eg. `Blazorise.Link`

**Comment by stevenlupo** [comment]
Worked, thanks.
