### ISSUE TITLE
DropDowns with filter

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1354]
Is it possible to add a filter within the dropdown menu? as [jquery chosen](https://harvesthq.github.io/chosen/)

**Comment by stsrki** [comment]
The closer we have is Autocomplete https://blazorise.com/docs/extensions/autocomplete/

But nothing stops you from creating your own component by using Dropdown and placing an input field inside of DropdownItem.

**Comment by angelru** [comment]
Many thanks! great job!
