### ISSUE TITLE
DataGrid Item

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1355]
Suppose I have a datagrid with some columns, but for example when adding a new item I want it to have more fields than the one shown in the datagrid, same for editing or viewing details, would this be possible ? Or do I have to implement something on my own? summing up: I want to show less data than I want to add / edit or show

**Comment by stsrki** [comment]
Yes, this is possible. You can set `Displayable="false"` parameter to hide the column from the grid and use `Editable="true"` parameter to show it in edit mode.

**Comment by angelru** [comment]
thank you very much again! looking forward to the next stable version :)
