### ISSUE TITLE
Field in datagrid, possible bug??

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1364]
I don't know if it's c # or blazorise thing or mine

`nameof(Person.Patient.Reason)`

Patient is an object
Reason is a string

```
ArgumentException: 'Reason' is not a member of type

System.Linq.Expressions.Expression.PropertyOrField(Expression expression, string propertyOrFieldName)
Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, string fieldName)
Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter<TItem>(string fieldName)
Blazorise.DataGrid.DataGridColumn<TItem>.<.ctor>b__4_2()

```

```
@($"{nameof(Person.Patient)}.{nameof(Person.Patient.Reason)}")

An unhandled exception occurred while processing the request.
ArgumentException: fieldName is not specified.
Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, string fieldName)
```

**Comment by stsrki** [comment]
`nameof` will return the name of `Reason` field in the `Patient` object, while Datagrid expected it to be present in `TItem `object. So you should write the path as a string instead of `nameof`, eg. "Patient.Reason"

**Comment by angelru** [comment]
I'm sorry I can't make it work

```
 Field="@("Patient.Reason")"

ArgumentException: fieldName is not specified.
Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, string fieldName)
```

**Comment by stsrki** [comment]
Just to confirm. Your `TItem` is set to `Person`?

**Comment by angelru** [comment]
Yes, I don't tend because the exception keeps getting, can you try?

**Comment by angelru** [comment]
any idea why it happens? I am with blazor server

**Comment by stsrki** [comment]
I have no idea to tell you the truth. You have defined it as it should be. No issues with that. The only thing I can think of is that your `Patient` field is null and when it tries to access `Reason` it will break.

**Comment by angelru** [comment]
Many thanks! ref #165
