### ISSUE TITLE
Height of LayoutFooter

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1367]
Is there any way to control the height of the `<LayoutFooter>`? I tried controlling it with the `Style` attribute, but that breaks the behavior in that my sidebar then scrolls above the header. I didn't see anything in the Theme options in `App.razor` that could help.

**Comment by stsrki** [comment]
Have you tried setting the height on an element that is placed inside of LayoutFooter? eg 

```
<LayoutFooter>
    <div height="150px">
```

**Comment by stevenlupo** [comment]
Sorry, no luck. I tried it a couple of different ways.

I also tried 
```
<LayoutFooter>
     <div style="height:20px">
```
as well. 

It's not a big deal for me, I think I can get away without a footer for now. I just thought I'd bring it up.

**Comment by stsrki** [comment]
Strange. I'm using it in my own project and it's working fine for me. Here is my code snippet.

```cshtml
<LayoutFooter Class="page-footer">
</LayoutFooter>
```

```css
.page-footer {
    height: 6rem;
    ...
}
```

Maybe something is messing with your css. Try to inspect it in dev tools.

**Comment by stevenlupo** [comment]
Happy to report this issue somehow got fixed along the way. Something must have changed in the latest releases that fixed it.
