### ISSUE TITLE
Can't assign a value to the "Class" parameter on TreeView component

### ISSUE THREAD

**Issue by FrancisValade** [stsrki/Blazorise#1369]
**Describe the bug**
I can't assign a value to the "Class" parameter on a TreeView component. When I try to add a value and I run the app on a browser, the attribute class doesn't show the values that I added.

**To Reproduce**
Create a normal TreeView and add a value to the Class parameter:

```
<TreeView` Class="overflow-auto"
              Context="nodeContent" Nodes="Items"
              GetChildNodes="@(item => item.Children)"
              HasChildNodes="@(item => item.Children?.Any() == true)"
              @bind-SelectedNode="selectedNode"
              @bind-ExpandedNodes="ExpandedNodes">
        <NodeContent>
            <span class="text-nowrap">
                @nodeContent.Text
            </span>

        </NodeContent>
    </TreeView>
```
**Expected behavior**
The div that contains the treeview shoud have the value "overflow-auto" in the class attribute.

**Comment by stsrki** [comment]
I can confirm this is a bug. It seems attributes are not passed to the underline component in the TreeView.

**Comment by stsrki** [comment]
Implemented in the latest version with `NodeStyling` parameter.
