### ISSUE TITLE
Bar toggle all text gets highlighted on multiple click

### ISSUE THREAD

**Issue by rlavaud** [stsrki/Blazorise#1378]
When clicking multiple times on a Bar dropdown, the text from all the sub items get highlighted.

**To Reproduce**
1. https://bootstrapdemo.blazorise.com/
2. Click a few times on UI Elements
3. See the Either UI Elements gets highlighted or all the subitems or both

**Expected behavior**
Multiple click should not highlight all the items

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
![image](https://user-images.githubusercontent.com/11966443/95949229-3a6c7380-0dc0-11eb-853e-98d21a906984.png)

**Comment by MitchellNZ** [comment]
I agree, thanks for showing this.

Should be an easy enough fix.
