### ISSUE TITLE
Datagrid <NewTemplate>

### ISSUE THREAD

**Issue by Gege00** [stsrki/Blazorise#1380]
My issue is I'd like to make one of the column editable during the row creation, but I want to lock that cell when the user is editing the given row. 

The question is if I'm able to implement this use-case without having two different templates for editing and creating.

**Comment by AlexMarble** [comment]
You can use the **DataGridColumn** parameters **CellsEditableOnEditCommand**  and **CellsEditableOnNewCommand** to accomplish this currently so long as your EditMode is set to **DataGridEditMode.Inline** or **DataGridEditMode.Form**.

If you want to use **DataGridEditMode.Popup**, #1362 is currently open to allow those parameters to be used. If you still want to use popup mode you can use this workaround.

> I don't know if this will help anyone but I got around this by adding a reference to the DataGrid in my Code{...} Section.
> Then I compared the DataGrid.EditState against one of the DataGridEditState options (None, New, Edit), and use the returned Boolean to manage the Disabled state on the input.
> 
> 
>     <DataGrid TItem="TItem"  @ref="DataGridRef" 
>           Editable="true" EditMode="DataGridEditMode.Popup"
>           Data="@Data">
> 
>         <DataGridColumn TItem="TItem" Field="@nameof(TItem.Value)" Editable="true">
>             <EditTemplate>
>                 <TextEdit Disabled="@( DataGridRef.EditState == DataGridEditState.Edit )" />
>             </EditTemplate>
>         </DataGridColumn>
>     </DataGrid>
> 
>     @code {
>         DataGrid<TItem> DataGridRef;
>     }
