### ISSUE TITLE
Modal columns

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1382]
is it possible to form columns in modal?

**Comment by stsrki** [comment]
Sure, just add `Row` and `Column`(s) as you would usually do and place it in the `ModalBody`.

**Example**

```
<ModalBody>
    <Row>
        <Column>
            ...
        </Column>
        <Column>
            ...
        </Column>
    </Row>
</ModalBody>
```

**Comment by angelru** [comment]
Thank you very much, it should be in the documentation, although I imagine you will have little time, if there is any way I can contribute :)
