### ISSUE TITLE
Check component doesn't include <label> which makes the checkbox invisible

### ISSUE THREAD

**Issue by glecetre** [stsrki/Blazorise#1385]
**Describe the bug**
When using the `Check` component, it is rendered with an invisible checkbox because the text in the component is not rendered inside a `<label>`.

**To Reproduce**
1. Just add `<Field><Check TValue="bool">Toto le haricot</Check></Field>` anywhere

**Expected behavior**
It is rendered with a `<label>`, which allows for the custom checkbox to be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43233602/96098268-33ce2100-0ed2-11eb-9d0b-af7f5e6e48cc.png)
![image](https://user-images.githubusercontent.com/43233602/96098298-3df01f80-0ed2-11eb-842d-9d8c595eb171.png)

**Additional context**
I use the latest version: 0.9.1.2.
I use Bootstrap, Blazorise as well as Radzen but I doubt it impacts the rendering of the Blazorise Check component.

**Comment by stsrki** [comment]
It's missing more than just the label, Also `custom-component` part. 

See this example from demo app

![image](https://user-images.githubusercontent.com/900302/96098770-cb337400-0ed2-11eb-83e8-ce59326840b4.png)

There is no reason to hide the label.

🤔 Maybe you didn't include the `Use...` part in a startup?

![image](https://user-images.githubusercontent.com/900302/96098992-08980180-0ed3-11eb-99bf-ac733eba399f.png)

**Comment by glecetre** [comment]
I did add the services in `Startup.ConfigureServices`:

```cs
services
  .AddBlazorise(options =>
  {
    options.ChangeTextOnKeyPress = false; // Change on key press disabled because latency may interfere with typing
  })
  .AddBootstrapProviders()
  .AddFontAwesomeIcons();
```

**Comment by stsrki** [comment]
You also need to add in `Configure` part

```cs
app.ApplicationServices
      .UseBootstrapProviders()
      .UseFontAwesomeIcons();
```

**Comment by glecetre** [comment]
That was the problem. Thank you and very sorry for the inconvenience.

**Comment by stsrki** [comment]
No problem :)
