### ISSUE TITLE
Change black border

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1387]
I have noticed that in some components pressing it selects a black border, how can I change?
I can't find it in the css

**Comment by stsrki** [comment]
Can you show us an example? Also what Blazorise provider you're using?(Bootstrap, Bulma, ...)

**Comment by angelru** [comment]
I'm using bootstrap, it also happens when you click on a tab
![Sin título](https://user-images.githubusercontent.com/11645585/96120137-5b32e700-0eee-11eb-9908-8bfaccff8d25.png)

**Comment by stsrki** [comment]
It seems bootstrap is having the same problem, I just checked on their site https://getbootstrap.com/docs/4.5/components/navs/

![image](https://user-images.githubusercontent.com/900302/96122014-296f4f80-0ef1-11eb-8b34-8ce3adcf1fb8.png)

**Comment by angelru** [comment]
this can be a possible solution:

```
.classname: focus {
     outline: none;
}
```

**Comment by Jimmys20** [comment]
Hello, I also wanted to remove this black border and found this old issue. What I don't understand is how on the bootstrap page it's not showing any border when you click on tab. https://getbootstrap.com/docs/4.5/components/navs/#javascript-behavior
I know you can trigger the effect by applying focus to the element using browser dev-tools. For some reason when you click blazorise tab the link element get's focused but when you click plain bootstrap tab the element doesn't get focused.

**Comment by stsrki** [comment]
So, I have tried to see what are the differences. Blazorise has an additional `tabindex`. If I remove it, it works.

**Comment by Jimmys20** [comment]
If you remove `tabindex` then navigating the tabs using keyboard (Tab key) stops working. In "vanilla" bootstrap you can still navigate the tabs using tab key even when tabindex attribute is not set.

**Comment by angelru** [comment]
.classname: focus {
     outline: none;
}

**Comment by stsrki** [comment]
> If you remove `tabindex` then navigating the tabs using keyboard (Tab key) stops working. In "vanilla" bootstrap you can still navigate the tabs using tab key even when tabindex attribute is not set.

When you navigate through vanilla bootstrap tabs you also get the outline.

**Comment by Jimmys20** [comment]
Yes I know, but you don't get outline when you simply click the tab.

**Comment by stsrki** [comment]
Considering I can't simply remove `tabindex`, the only option is to apply CSS. Same as what @angelru did.

Here is slight modification:

```css
.nav .nav-item a.nav-link:hover,
.nav .nav-item a.nav-link.active {
    outline: none;
}
```
