### ISSUE TITLE
DialogService

### ISSUE THREAD

**Issue by LukeTOBrien** [stsrki/Blazorise#1388]
Hello there,

I am currently using [Radzen DialogService](https://blazor.radzen.com/dialog) in my app.  
Users can have more than one dialog open at a time and I have some post-init JS to remove the overlay and make the dialog draggable using [Interact.js](https://interactjs.io/).

I have tried using your Modal component but that doesn't work in my situation because I am using [Golden Layout](https://golden-layout.com/) and so the whole app is divided into panels.  
The `DialogService` works for me because it renders the dialog as a fragment outside of the main layout of the app.

As I see it there are two ways of displaying modals/dialogs, as hidden elements and as `RenderFragments`.  
So I prepose a `DialogService` perhaps something like:

```csharp
var result = await DialogService.Open<TDialog, TResult>(string titile, Action<TDialog> parameters, DialogOptions options)
// Doesn't return a result
DialogService.Open<TDialog>(string titile, Action<TDialog> parameters, DialogOptions options)
```

What do you think?

> The [Blazored Modal](https://github.com/Blazored/Modal) seems similar to my idea.

**Comment by stsrki** [comment]
I have just recently implemented this exact thing for one project that I work on. And I was also thinking of adding it into Blazorise, probably as an extension, or possibly built-in as it's using only Blazorise components.

**Comment by LukeTOBrien** [comment]
Oh well great minds think alike 🙂

**Comment by stsrki** [comment]
Going to be done as part of #1634
