### ISSUE TITLE
NumericEdit with TValue="decimal" won't allow fractional numbers

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#139]
When using the NumericEdit as follows

```html
<NumericEdit TValue="decimal?" Value="@DefaultValue" ValueChanged="@ValueChanged" />
```

and submitting the form with fractional numbers, I get the following:

![image](https://user-images.githubusercontent.com/26474006/60638055-13966200-9e47-11e9-9c71-4e3c0686cdee.png)

**Comment by stsrki** [comment]
Can you post the sample code for your form?

**Comment by brettwinters** [comment]
oops! after you asked me that question, I realised that I had dropped your `<NumericEdit>` on a legacy page inside an `<EditForm>` control. 

I removed the `<EditForm>` and converted the page to 100% Blazorise and now it works! Sorry about that, I never realised that there would be a clash. Next time I will look out for that before posting issues

**Comment by stsrki** [comment]
Yes `Validation` component was created long before the `EditForm` was introduced. Glad it works for you now :)
