### ISSUE TITLE
BarLink Still Ignores Attributes 

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1390]
I don't know if an issue can be reopened, but the #1332 still exists in `0.9.2-preview9`.

I can see the change to `<BarLink>` in #1333, but shouldn't it work in the latest preview?

So we're clear, I'm doing this:

     <BarLink To="http://example.com" target="_blank">Help</BarLink>

**Comment by stsrki** [comment]
It's not working because Blazorise `Link` is already setting `target` internally. 

Try with:

```
<BarLink To="http://example.com" Target="Target.Blank">Help</BarLink>
```

**Comment by stevenlupo** [comment]
I expected that to work, but it didn't. It did not set the target. This is my exact code:

`<BarLink To="http://example.com" Target="Target.Blank">Help</BarLink>`

**Comment by stsrki** [comment]
I added the Target parameter to Link components. It should be available with the next preview. Probably in the day or two :)
