### ISSUE TITLE
Blazorise.DataGrid - System.InvalidOperationException: The render handle is not yet assigned.

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1391]
**Describe the bug**
Trying to set a value after the DataGrid CTOR has run, throws the exception The render handle is not yet assigned only when setting PageSize, I am setting other properties like and it's working properly: 
            base.Bordered = true;
            base.ShowPager = true;
            base.Filterable = true;
            base.Hoverable = true;
            base.Class = "datagrid";
            base.Editable = true;
            base.EditMode = DataGridEditMode.Popup;
            base.UseInternalEditing = true;
            base.Responsive = true;
            base.Striped = false;
            base.FilterRowStyling = new DataGridRowStyling() { Class = "datagrid-row-filter" };
            base.SelectedRowStyling = (x, y) => y.Class = "datagrid-selectedRow";

**To Reproduce**
1. Inherit from DataGrid<TItem> 
2. Setup a CTOR something like 
        public ODOCDataGrid() : base()
        {
            SetDefaults();
        }
3. Try to set PageSize to 10
base.PageSize = 10;

**Expected behavior**
Property set normally.

**Screenshots**
<img width="538" alt="blazorise datagrid setpage" src="https://user-images.githubusercontent.com/22283161/96248511-93e0c800-0fa3-11eb-9ab7-91d09caa9ce0.png">

**Comment by David-Moreira** [comment]
I forgot to point out that this is happening in the preview, not on the release.
Thanks!

**Comment by David-Moreira** [comment]
Here's a repo for this, 
https://github.com/David-Moreira/DGridRenderHandle
still happens:
![image](https://user-images.githubusercontent.com/22283161/99861568-6680ce80-2b8e-11eb-9f23-ee86dc27013b.png)

**Comment by David-Moreira** [comment]
It's been a while, retested, does not happen on latest blazorise (0.9.3). Not sure what fixed it. Eitherway it's solved! Closing... :)

**Comment by stsrki** [comment]
I like it when issues close by themself haha
