### ISSUE TITLE
Modal state

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1392]
when using a modal with textedit, radio, etc, if you populate them and close the modal and then reopen those values they are still there, shouldn't they be removed?

**Comment by stsrki** [comment]
No, you should take care of those. The same modal is always active in the DOM. and when you Show() or Hide() it, you only change its visibility state. Also, every app is different and every app can have anything placed inside of the modal body. It would be impossible to "know" what to reset. Modal by its self is pretty dumb, so to speak. 

So, before you call the Show() you just need to set all of your model values to their default values, based on your app requirements.

**Comment by angelru** [comment]
many thanks :+1:

**Comment by angelru** [comment]
@stsrki
 I am using a radiogroup

                  <RadioGroup TValue = "int" Name = "Genders" @ bind-CheckedValue = "@ patientRequest.Person.GenderId">
                                             @foreach (var item in genericResponse.Data.PatientGenders)
                                             {
                                                 <Radio TValue = "int" Value = "@ (item.Id)"> @ item.Type </Radio>
                                             }
                                         </RadioGroup>

when I close the modal I set the entire object to null, however, when I open the modal all the fields are empty except the radius, the last one is selected but in the genderid object it is 0, it does not correspond to any

**Comment by stsrki** [comment]
You have `bind-CheckedValue` instead of `@bind-CheckedValue`. If that doesn't help try to get the latest preview. Radio group had this kind of problem in 0.9.1.x that is fixed in one of 0.9.2 previews.

**Comment by angelru** [comment]
thanks!
