### ISSUE TITLE
TemplatedSelect allow for background images and more styling

### ISSUE THREAD

**Issue by LukeTOBrien** [stsrki/Blazorise#1393]
HTML`<select>` and `<option>` have very limited styling, for example with a list of countries it is not possible to display a background image of the country's flag next to each `<option>`, the only [way to do it is with `<div>`s and `<li>`s](https://addwebsolution.com/blog/adding-image-select-list-cross-browser-compatibility).

However the `<select>` has advantage on mobile as a model pops up a model with options:

So what I think the project could have as well as the default `<Select>` is a templated Select to allow for background imaged and more styles.  
With something like [adaptive styles opening up a model of options on mobile](https://demos.devexpress.com/Bootstrap/Editors/ComboBox.aspx#Adaptivity)

```html
<Select TValue="object" Data="@Countries">
    <SelectItem Value="1">
        <Template>
            <img src="@context.FlagSVG" /> @context.Name
        </Template>
    </SelectItem>
</Select>
````

What do you think?

**Comment by stsrki** [comment]
I'm not sure about this. It feels like a hack to me and it would be a mess dealing DOM elements. Especially considering the different structures of elements for some providers, like AntDesign. Even in your first link they use JavaScript to convert select into <div>s and <li>s.

So I would close this ticket. :)

**Comment by LukeTOBrien** [comment]
Okey doke

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
