### ISSUE TITLE
TextEdit in a Field in Server applications have an input and cursor issue 

### ISSUE THREAD

**Issue by JaredMRomano** [stsrki/Blazorise#1397]
**Describe the bug**
When entering text in the TextEdit component in a Field in Server applications. The cursor jumps around and only some of the text actually gets captured.  You will see the character get typed, but then it will erase.  The input only works when typing really slow.  You can experience the bug by going to the  Blazor Server Bootstrap Demo. You'll notice on the Forms page, it does it on the first text box entered only, and does not do it on fields after the first text box looses focus.  On the Validations page, it does it always.

Edit: On the forms page it stops the issue after the first box because there is an unhandled exception, causing the circuit to close.

**To Reproduce**
1. Go to the Blazor Server Bootstrap Demo [](https://rcbootstrapdemo.blazorise.com/)
2. Under the 'Forms' section, go to either 'Forms' or 'Validations'
3. Type something in any of the TextEdit fields.

**Expected behavior**
Text to appear in box exactly how the user types it.

**Screenshots**
![blazoriseBug](https://user-images.githubusercontent.com/10646171/96473430-df3ae680-11ee-11eb-91ba-d5e2c6a9174b.gif)

**Comment by stsrki** [comment]
Hey, you can find the solution in #1232

**Comment by JaredMRomano** [comment]
Thanks for the quick response. I am not sure where to set DelayTextOnKeyPress.  It is not an available property on the components TextEdit, Field, Validation, Validations.  It is also not a property in BlazorOptions.  Is my only option for now to disable ChangeTextOnKeyPress?

**Comment by stsrki** [comment]
DelayTextOnKeyPress is only available im preview version of Blazorise. If you cannot get it, they yes disabling  ChangeTextOnKeyPress will work also.
