### ISSUE TITLE
Idea : SelectEdit with support for <OptGroup>

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#140]
Would it be possible for your Select to include support for [OptGroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)

I guess something like this:

```html
<SelectEdit TValue="int">
    <SelectGroup Label="Group 1">
        <SelectItem Value="1-1">1</SelectItem>
        <SelectItem Value="1-2">2</SelectItem>
    </SelectGroup>
    <SelectGroup Label="Group 2">
        <SelectItem Value="2-1">1</SelectItem>
        <SelectItem Value="2-2">2</SelectItem>
    </SelectGroup>
</SelectEdit>
```

**Comment by stsrki** [comment]
To tell you the truth this is the first time I hear about this tag. As far as I can see it is very basic and simple to implement. It's used just to group option items. I think it will not be a problem.

**Comment by brettwinters** [comment]
great thanks @stsrki . Actually it's quite useful if there is a long list of select items.

**Comment by stsrki** [comment]
Done!
