### ISSUE TITLE
SelectList defaultvalue

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1401]
I think it would be good to put one more field to put an element by default, so that the first one appears and disabled for example: "select a country", "select a color"

**Comment by stsrki** [comment]
It's not a bad idea. I would call it a `DefaultItemValue` and `DefaultItemText`. And if both parameters are defined then it would create a default `option `element.

**Comment by angelru** [comment]
that is, DefaultItemValue seems the right thing to do, and it appears as disabled, since it is an option to tell you that you should choose

**Comment by sonphamit** [comment]
Is feature available now?

**Comment by stsrki** [comment]
No, not yet.

**Comment by angelru** [comment]
any idea when it will be available?

**Comment by stsrki** [comment]
I can add it for 0.9.4. Thanks for reminding me!

**Comment by stsrki** [comment]
@angelru Does it really need to be disabled? Feels strange to not be able to select a default item.

![image](https://user-images.githubusercontent.com/900302/112501611-aef10880-8d89-11eb-80a4-79e64fba3046.png)

![image](https://user-images.githubusercontent.com/900302/112501682-bdd7bb00-8d89-11eb-8551-b783bc515d3c.png)

**Comment by angelru** [comment]
@stsrki no, it is not necessary, although you could be given the option to be able to disable it, if possible, if not through css :)

**Comment by stsrki** [comment]
The same source I was looking at :)

I was also thinking about adding something like `DefaultItemDisabled`. It's one of the ways.
