### ISSUE TITLE
Empty TextEdit is Null instead of Empty String

### ISSUE THREAD

**Issue by CDarbonne** [stsrki/Blazorise#1402]
**Is your feature request related to a problem? Please describe.**
When backspacing or clearing out the TextEdit component, the bound property is set to null instead of an empty string. Is this/should this be intended logic?

**Describe the solution you'd like**
In my opinion it seems that empty text components should generally default to an empty string. This seems logical to me as we arent nullifying the input, just emptying it.

**Comment by stsrki** [comment]
I just checked and you're right, it should be an empty string for TextEdit. I will see what can be done and hopefully change will not affect other components since they are all based on the same code.

**Note for me:** The problem is in `BaseInputComponent.CurrentValueHandler`

```cs
if ( string.IsNullOrEmpty( value ) )
{
    empty = true;
    CurrentValue = default; // This should be fixed because default of string is null
}
```

**Comment by CDarbonne** [comment]
Ok, thank you!

**Comment by ATP-IAS** [comment]
Hello!
@stsrki do you have any estimation for this bug fix? We are also interested in this topic. 
Thanks a lot!

**Comment by stsrki** [comment]
Hi @ATP-IAS  it's planned for the next milestone.
