### ISSUE TITLE
PageSize Button

### ISSUE THREAD

**Issue by DDDenisSobek** [stsrki/Blazorise#1404]
**Is your feature request related to a problem? Please describe.**
My actual problem is, that i want to make PageSize able to change for my site like this:
```xml
        <DataGrid ... PageSize="@PageSize" ReadData="@ReadCallback">
            ...
        </DataGrid>
        <Select TValue="int" @bind-SelectedValue="PageSize">
            <SelectItem TValue="int" Value="10">10</SelectItem>
            <SelectItem TValue="int" Value="20">20</SelectItem>
            <SelectItem TValue="int" Value="50">50</SelectItem>
            <SelectItem TValue="int" Value="100">100</SelectItem>
        </Select>
```
but `DataGrid` does not call `ReadCallback`, when `Select` change `PageSize`, even not when `PageSize` setter call `StateHasChange`.

**Describe the solution you'd like**
Short solution:
`PageSize` setter call `ReadData`.
Long solution:
`PageSize` setter call `ReadData`.
`DataGird` gets a property `PageSizes` type of `int[]`, a property `PageSizeSelectTemplate` type of `RenderFragment<PageSizeContext>` and a property `PageSizeChanged` type of `EventCallback<int>`.
`PageSizeSelectTemplate` or default select for page size will be used next to paging.

**Comment by stsrki** [comment]
You don't need to do this. Page sizes are now implemented in Blazorise

![image](https://user-images.githubusercontent.com/900302/97015110-75527200-154b-11eb-9d95-f1384144fb4a.png)

But it's still in preview, so if that is not a problem just get it from MyGet.

**Comment by DDDenisSobek** [comment]
Thank you for this information. Sorry for unnecessary issue.

**Comment by stsrki** [comment]
No problem. It's still not documented so you had no way of knowing :)
