### ISSUE TITLE
Example of using CellStyle / CellClass for DataGrid

### ISSUE THREAD

**Issue by thuhaile** [stsrki/Blazorise#1405]
Hi, is there an example on how to use CellStyle or CellClass for DataGridColumn? Thank you.

**Comment by stsrki** [comment]
Sorry, I'm a little too late 😅

```cshtml
<DataGridColumn
  CellClass="@((item)=>"your-class-name")"
  CellStyle="@((item)=>item.IsActive ? "color: green;" : "color: red;")"
```

**Comment by MGabala** [comment]
this wont work for me. 


`        <DataGridColumn CellClass="@((item)=>"red-column")" Field="@nameof(OutputClass.Kod)" Caption="Kod" Editable />
`
