### ISSUE TITLE
Table with fixed header position

### ISSUE THREAD

**Issue by rad765** [stsrki/Blazorise#1408]
Is it possible to have a Table with fixed TableHeader position while TableRows in TableBody is vertically scrolling`?

**Comment by stsrki** [comment]
You can do it with CSS and it's fairly easy. Here is one example https://stackoverflow.com/questions/21168521/table-fixed-header-and-scrollable-body

**Comment by rad765** [comment]
Thank you I will probably find somthing there, but that leaves me with a quesion. 
When is Blazorise the appropriate tool, and why shold we use it, if we easely can revert to html and CSS?
Sorry if this is a very stupid question, but I'am not very used to web-programming, Html and CSS, as I'm comming from the Xamarin Android world, so I saw Blazor an Blazorise as my entry to this world. (By the way I'm using the Material variant of Blazorise and found this page: [https://mdbootstrap.com/docs/jquery/tables/scroll/](https://mdbootstrap.com/docs/jquery/tables/scroll/) whitch contain mutch what I want.

**Comment by stsrki** [comment]
Blazorise is an abstraction over different CSS frameworks so there is always going to be something missing that is specific to one framework. I try to create new features where they are most needed, but that takes time and resources. So until I cover most of it you will need to fall back to CSS. This is perfectly fine, as CSS is a perfect tool for customizing the look of your app. You should embrace it :)

And why should you use it? If you want to quickly prototype your app without building your own component, which takes time. Also, you can easily switch between frameworks if you desire.

**Comment by rad765** [comment]
Thank you, You do a very great job. It is just beacuse I'm getteing lost in all the differnet tools in the web programming world, as this is a little new to me. I will continue to use Blazorise as far as I can :-)
