### ISSUE TITLE
Prerelease version's naming scheme does not show newest properly after v9

### ISSUE THREAD

**Issue by Welchen** [stsrki/Blazorise#1409]
Due to the naming scheme, any version after -preview9 isn't shorted properly nor will notify that a newer version exists in the NuGet Package Manager in VS. 

Updating to -preview12 causes PackageManager to think -preview9 is the newer version. 

<img width="556" alt="Versioning" src="https://user-images.githubusercontent.com/5358349/97119810-be87fa80-16e0-11eb-9e97-b167106fc1b6.png">

**Comment by stsrki** [comment]
I'm aware od the issue and I don't think there is much I can do now. For future releases, I can start naming with zero prefix so that they're properly sorted. But for now there is no better way.

**Comment by Welchen** [comment]
Understandable. Just wanted to make sure you were aware.
