### ISSUE TITLE
ModalBackdrop didn't work as expected

### ISSUE THREAD

**Issue by howardgod** [stsrki/Blazorise#141]
I reference the sample code for Modal in document.

But it didn't seem like working. The ModelBackdrop block the whole page including the popup modal.

In your document, it said "Place the modal markup somewhere at root of you component layout.", would you elaborate more about this?
![sc1](https://user-images.githubusercontent.com/10459637/60793617-9f3b2600-a19a-11e9-9cd9-b7650f0cdccf.JPG)

**Comment by stsrki** [comment]
By the placement it basically means to put it on the bottom of your razor markup, but it's just a recommended way of doing it.

Now back to your problem. I guess you have forgot to remove the default _bootstrap.css_ from the _index.html_ or __Host.razor_ file. Can you post the content of that file so I can look at it?

**Comment by howardgod** [comment]
I do remove the original bootstrap.css
The only thing I can think of is that I don't follow the last part of your ReadMe "Server-Side Blazor" to link those blazorise.css or blazorise.js...etc.

Here's my _Host.cshtml. Forget about the .txt extension which only for upload the file.

[_Host.cshtml.txt](https://github.com/stsrki/Blazorise/files/3367373/_Host.cshtml.txt)

**Comment by stsrki** [comment]
You should definitely include  those js and css files because they contain necessary bits to make it work.

**Comment by howardgod** [comment]
After including those css, Modalbackdrop works. thank you.
