### ISSUE TITLE
DataGrid in ABP no longer scrolls after Popup (Blazorise Modal) closes

### ISSUE THREAD

**Issue by 274188A** [stsrki/Blazorise#1410]
This [problem](https://github.com/stsrki/Blazorise/issues/296) has reportedly been fix, however I can still see the problem within the `ABP framework (3.0.0.0-rc2)`

I have a grid with an Accordion below the grid.  the accordion contains other grids and each of those can show a modal to add/edit/delete.

Once any modal is hidden the vertical scroll bar on the browser is hidden making the UI unusable.

**Comment by stsrki** [comment]
Should be fixed with #1818
