### ISSUE TITLE
Probems with RichTextEdit

### ISSUE THREAD

**Issue by DDDenisSobek** [stsrki/Blazorise#1414]
**Describe the bug**
ContentChanged throws exception at writing text in RichTextEdit and does not call EventCallback.
Maybe i do something wrong.

**To Reproduce**
Write code like below.
Write one char.
Look in debug console.

TestPage:
```xml
@page "/TestPage"
@using Blazorise.RichTextEdit 
<h3>DataGridTestPage</h3>
<RichTextEdit @ref="richTextEditRef" ContentChanged="OnContentChanged" PlaceHolder="Test text"></RichTextEdit>
<p>
  @contentAsHtml
</p>
<p>
  @contentAsDeltaJson
</p>
<p>
  @contentAsText
</p>
```
```
@code {
    private RichTextEdit richTextEditRef;
    private string contentAsHtml;
    private string contentAsDeltaJson;
    private string contentAsText;

    public async Task OnContentChanged()
    {
        contentAsHtml = await richTextEditRef.GetHtmlAsync();
        contentAsDeltaJson = await richTextEditRef.GetDeltaAsync();
        contentAsText = await richTextEditRef.GetTextAsync();
    }
}
```

Startup:
```
services.AddBlazoriseRichTextEdit(
                options =>
                {
                    options.UseShowTheme = true;
                }
            );
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65016836/97207731-a1bff580-17ba-11eb-969d-b2df7680c52a.png)
![grafik](https://user-images.githubusercontent.com/65016836/97207798-b0a6a800-17ba-11eb-80b2-8a857bcc5fab.png)
![grafik](https://user-images.githubusercontent.com/65016836/97207834-bd2b0080-17ba-11eb-90dc-1c30666de24e.png)
![grafik](https://user-images.githubusercontent.com/65016836/97207874-ca47ef80-17ba-11eb-9711-893147d56233.png)

**Comment by Unlink** [comment]
https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.RichTextEdit/wwwroot/blazorise.richtextedit.js#L49
Needs to be changed to 
`dotnetAdapter.invokeMethodAsync(onContentChanged);`

**Comment by stsrki** [comment]
@njannink Can you look at this?
