### ISSUE TITLE
Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.

### ISSUE THREAD

**Issue by juliushuck** [stsrki/Blazorise#1424]
**Describe the bug**
I always get the following error:
Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.

**To Reproduce**
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="/" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" rel="stylesheet" />
    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
</head>
<body class="h-100">
    <app>
        <div style="height: 100vh;">
            <div class="container-fluid h-100">
                <div class="row h-100 justify-content-center align-items-center">
                    <div class="col text-center">
                        <h1>Loading</h1>
                        <div id="blazor-error-ui" style="display: none;">
                            <p class="text-danger">An unhandled error has occurred.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </app>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
</body>
</html>
```

As you can see the jQuery file is linked above the Bootstrap file.
Also, the bar component is not uncollapsing or collapsing in mobile mode.

**Screenshots**
![a](https://user-images.githubusercontent.com/41862965/97696607-1db18a80-1aa6-11eb-80af-ddfcec041c7b.png)

**Comment by stsrki** [comment]
All I can think of is that electron is doing something. There is no reason to not work 🤔

**Comment by aburke972** [comment]
Hi,

Is your problem solved ? How did you do ?
Everything was going well for me till yesterday. Today, the firefox and chrome are unable to load it while the url is properly reachable....

I'm a bit confused...

**Comment by stsrki** [comment]
Yesterday was the release of .Net 5. It's a long shot, but have you updates VS or some NuGet packages?

**Comment by aburke972** [comment]
Hi,

Thanks for helping but I've just solved my problem. I cleared both cache
and cookies at the jdn url level from the network tab of the inspector.

I tried to add the info to my last comment but I couldn't

Le mer. 11 nov. 2020 à 22:21, Mladen Macanović <notifications@github.com> a
écrit :
