### ISSUE TITLE
Creating a new item in the detail row fails with NullReferenceException

### ISSUE THREAD

**Issue by TH80807** [stsrki/Blazorise#1425]
**Describe the bug**
I have a datagrid where each item contains a list of subitems, displayed with the DetailRowTemplate. The datagrid of the subitems also has button for "new", "edit", "delete" etc. All buttons seem to work as expected except the "new" button. Clicking it results in a NullReferenceException.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MyApplication
  StackTrace:
   at MyApplication.Pages.Destinations.<>c__DisplayClass0_13.<BuildRenderTree>b__54(RenderTreeBuilder __builder4)

**To Reproduce**
1. Create a datagrid with items that each contain a list of subitems.
2. In the DetailRowTemplate, create a datagrid for those subitems. It should contain the columns for the subitems as well as the DataGridCommandColumn section. Ensure that you have the context of the subitem datagrid set to something different than the context of the item datagrid, for example <DataGrid ... Context="innerContext">. Configure the NewCommandTemplate like this:
<NewCommandTemplate>
   <Button Color="Color.Success" Clicked="@innerContext.Clicked">New</Button>
</NewCommandTemplate>
3. In the datagrid for the subitems, click the new button.
4. A NullReferenceException occurs.

**Expected behavior**
A new subitem will be created.

**Screenshots**
![2020-10-30 15_03_17-LogisticsServiceFrontend](https://user-images.githubusercontent.com/73703926/97714417-6cb8e900-1ac1-11eb-8524-9ff1fdfe0099.png)

**Comment by stsrki** [comment]
Hi, can you prepare a small project where you can reproduce this error?

**Comment by TH80807** [comment]
Hello, sorry for the false alarm. The exception occurred because inside the inner DataGrid, I had a nullable Enum but the Select template for that column was configured for the non-nullable Enum. Preparing a repro-project made me realize that...
