### ISSUE TITLE
SelectList SelectedValueChanged is displaying error with documented example

### ISSUE THREAD

**Issue by Welchen** [stsrki/Blazorise#1426]
I'm trying to use the SelectList in my project and was running into issues using SelectedValueChanged, so I decided to just copy your example line for line. 

Visual Studio is displaying the error: 

`Argument 12: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback<object>'`

Code 

```
     <SelectList Data="@myDdlData"
         TextField="@((item)=>item.MyTextField)"
         ValueField="@((item)=>item.MyValueField)"
         SelectedValue="@selectedListValue"
         SelectedValueChanged="@MyListValueChangedHandler" />

    object selectedListValue { get; set; } = 3;

    void MyListValueChangedHandler(object newValue)
    {
        selectedListValue = newValue;
        StateHasChanged();
    }
```

**Comment by stsrki** [comment]
What Blazorise version you're using?

This is how it's used in the latest preview:

```cshtml
<SelectList TItem="MySelectModel"
            TValue="object"
            Data="@myDdlData"
            TextField="@((item)=>item.MyTextField)"
            ValueField="@((item)=>item.MyValueField)"
            SelectedValue="@selectedListValue"
            SelectedValueChanged="@MyListValueChangedHandler" />
```

**Comment by Welchen** [comment]
@stsrki Literally 5 seconds ago I got it to work.  I am using rc1 and I got it working by setting TItem and TData.  Didn't realize it changed in the preview versions.   Makes sense that the demo and documentation wouldn't reference that then.

**Comment by stsrki** [comment]
Yep, I plan to do something with documentation and create my own CMS that will support versioning.

There are too many time like this that people are using preview while still looking at the live documentation :)
