### ISSUE TITLE
DataGrid: Support for button bar

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1427]
**Is your feature request related to a problem? Please describe.**
Instead of having row by row buttons, occupying column space, have the option to have a button bar, similar to pager.
(Also would be nice to move these around. I.E: Button bar left, Pager: center)

**Describe the solution you'd like**
An example from jqGrid, a javascript plugin I've used previously.
![image](https://user-images.githubusercontent.com/22283161/97749006-40fc2a00-1ae6-11eb-980f-71abf204a56f.png)

**Comment by stsrki** [comment]
I must say it's not a bad idea. Now I'm thinking is it best to handle this mode inside of DataGrid or expose an API that can extent DataGrid to work in any way possible. Maybe expose methods to activate new item command, edit item command, paging, etc. 🤔

**Comment by David-Moreira** [comment]
That actually seems like a good idea. That gives more flexibility to your users.
A use case I think people will have is, by exposing those methods, they can wrap them under their own generic interfaces for implementing their own CRUD operations and then handling and validating those operations. 

And on that note, I'm actually  trying to figure out a good way to bind RowInserting/RowUpdating/RowDeleting to a generic CRUD interface, since those are event call backs there does not seem to be any way to bind callbacks except trough the razor component. Personally what I am trying to achieve is have a base class, that says that for this model, there will be a "service" that will handle the CRUD operations something like:
```        
protected virtual void RowInserting(CancellableRowChange<T, Dictionary<string, object>> rowChange)
        {
            //validator
            try
            {
                SetDictionaryToModelProperties(rowChange.Item, rowChange.Values);
                var result = _service.CreateAsync(rowChange.Item);
                toastService.ShowSuccess($"Registo criado com sucesso. Id: {result.Result.Id}", this.Title);
            }
            catch (System.Exception)
            {
                rowChange.Cancel = true;
                toastService.ShowError("Ocorreu um erro. ID: ", this.Title);
            }
        }
``` 
However,you have to manually go and set something like:
``` RowInserting="RowInserting"```  on every component, instead of once somehow. 
I can't figure out a way to set an EventCallBack to some method on code behind, do you have any ideas?

And on yet another note, why on RowInserting, you have a dictionary with the properties and not the model itself for the changes?
``` CancellableRowChange<T, Dictionary<string, object>>``` 
It's usefull to have the model to do validation and other logic from a rigid type. If the idea, is to compare the changes to the original, then why not have a second model instead of the dictionary??

Would appreciate your thoughts on this points. Thanks! ^^

**Comment by stsrki** [comment]
I think you can `EventCallback.Factory.Create` to bind any callback type.

Dictionary is used because it will give you only the items that are being edited. The problem with the actual Item instance is that it is not immutable. It still has a reference to the actual data item. So if you change anything on `RowEditing` it could affect the editor and they will not be in sync. That's why using a dictionary is used. And Item is just for the extra context in case you need it.

**Comment by David-Moreira** [comment]
@stsrki Thank you for your answers!

> I think you can EventCallback.Factory.Create to bind any callback type.
I did not know about this, I just tested and it works! Thanks! 👍 

I understand why you did it. I still don't quite agree with it. If I need to do validation on a centralized place, and without having to use Blazorise Validator on each field, the Dictionary seems a bit "wonky" to go through the properties/changes. In my use case, I ended up just converting the Dictionary into properties to do validation through a rigid type. Wouldn't a deep cloned instance instead of the dictionary work or am I thinking wrong about this?

**Comment by stsrki** [comment]
The problem is that there are no good clone methods. Every method has its pros and clones. The only good clone method is serialization, but that requires users to mark their models with SerializableAttribute and I didn't want to introduce that kind of constraint.

**Comment by David-Moreira** [comment]
I see. Thanks for the feedback. 👍

**Comment by David-Moreira** [comment]
Hello @stsrki ,
Hope you've been well. :)

Following up on this. 
The pager isn't in fact very customizable. I can apply styles or templates to certain bits of the pager, like the FirstPageButton etc. But I can't actually fully style it. And there isn't a very good workaround since the API for paging isn't exposed, neither the wrapping row has a specific class. 
I think exposing both the API like you suggested that activates the DataGrid Commands and also providing a better way to template the pager. That would give a good flexibility.

**Suggestion:** 
- **Exposed API:**

Have an IssueCommand API based on Enums (NewCommand, EditCommand, etc) that translate to the Internal Commands. That you can easily extend as you add functionality to the DataGrid.

- **Pager Component**

Imbue PagerComponent on Datagrid that utilizes this exposed API you suggested and that exposes the pager templates that currently exist: FirstPageButtonTemplate / LastPageButtonTemplate / NextPageButtonTemplate / PreviousPageButtonTemplate / ItemsPerPageTemplate to not fully break the existing functionality.
Optionally you can define a General Template, where you can use the exposed API and constuct the Pager yourself.

(Side note: I have to do more testing but I think ItemsPerPageTemplate is missing the [ParameterAttribute] on preview, 
That's not intended is it? It's usefull for translation at the very least)
![image](https://user-images.githubusercontent.com/22283161/98031531-897b5680-1e0a-11eb-9078-d415bfafaa6b.png)

**Comment by David-Moreira** [comment]
Hello @stsrki 
I do need this. Would you mind that I work on this? Does the proposed solution seem good to you?

Basically I want to be able to extend DataGrid functionality by being able to add buttons to the pager (Add my own export/import functionality, maybe a refresh button..., etc), also being able to call the internal commands to migrate the existing by row buttons to the bar, like in the following print:
![image](https://user-images.githubusercontent.com/22283161/100227702-734c4c00-2f19-11eb-92be-e1d926e73de9.png)

**Comment by stsrki** [comment]
Hi @David-Moreira 

I think you can try and do it. You're already quite familiar with how DataGrid works.

The proposed solution seems good. We will need to:

- somehow expose pagination API
- expand current pagination templates and add what is missing
- add a new region or container for button row. Maybe like a new render template that will expose API for manipulation of DataGrid

eg.

```
class ButtonRowContext
{
  EventCallback NewClicked { get; set; }
  EventCallback EditClicked { get; set; }
  EventCallback DeleteClicked { get; set; }
}
```

```
<DataGrid>
  <ButtonRow>
    <Button Clicked="@context.EditClicked">Edit</Button>
  </ButtonRow>
</DataGrid>
```

**Comment by David-Moreira** [comment]
Hello @stsrki 
I haven't started this yet. I'm still debating whether a more general pager component is the best choice, or just doing the additional ButtonRow fragment which in turn would be injected to your `_DataGridPagination` component, as you suggest.
I say this, because personally I found it difficult to customize the pager current look and html elements positioning, and currently I can't make use of any of the available pager space to allocate more html elements (like buttons).

What do you think of a Pager component, something like this:

```
<DataGrid>
  <Pager context="pagerContext">
      //Existing related pager templates 
      <FirstPageButtonTemplate>
          etc...
      <ButtonRowTemplate>
  </Pager>
</DataGrid>
```

Where I can use the existing templates like above, or just create everything myself, since that gives the pogrammer so much more flexibility, simple example:
```
<DataGrid>
  <Pager context="pagerContext">
      <ChildContent>
        <div class="col btn-group">
          <Button Clicked="@pagerContext.ButtonContext.NewClicked">New</Button>
          <Button Clicked="@pagerContext.ButtonContext.EditClicked">Edit</Button>
          <Button Clicked="@pagerContext.ButtonContext.Refresh">Refresh</Button>
          <Button Clicked="@MyOwnButtonClick">DoSomething</Button>
        </div>
        <div class="col>
          <ul class="my-ul-class">
            <li><a onclick="@pagerContext.Pagination.PreviousPageClick"></a></li>
            <li>@pagerContext.Pagination.CurrentPage</li>
            <li><a onclick="@pagerContext.Pagination.NextPageClick></a> </li>
          </ul>
        </div>
        <div class="col">
          <span class="my-total-items">
            @pagerContext.Pagination.CurrentTotalItems
          </span>
        </div>
     </ChildContent>
  </Pager>
</DataGrid>
```

**Comment by stsrki** [comment]
Makes sense to have `PagerTemplate` which you can customize as you wish. I don't like having sub-templates like FirstPageButtonTemplate or ButtonRowTemplate inside of PagerTemplate. It's better to have them as they are currently, to allow per button customization. And if anyone wishes to customize the entire pager then PagerTemplate is the right way. As long as it has full API to use. And the API should also have all the information about the current page, sizes, or maybe which buttons should be disabled, based on the current page state.

So yeah, the second example is the better approach.

**Comment by David-Moreira** [comment]
Great. Seems good. 
- Create ButtonRowTemplate as you suggested. (Internally will be an extra column in `_DataGridPagination` component)
- Create PagerTemplate that has access to the internal context API to fully customize.

Probably will do these in separate PRs, since ButtonRowTemplate will be simpler and faster to do. Will let you know when I have something, Thanks!

**Comment by stsrki** [comment]
That sounds good :)

**Comment by stsrki** [comment]
@David-Moreira is this safe to close?

**Comment by David-Moreira** [comment]
I haven't fully tested it on my project yet but I guess you can close. 

This already gives some more freedom. 
We were thinking on the customizable pager with access to alot of the internal data grid, but I guess that can hold off for now. it seems to me that for now it's more important to develop the api that exposes internal commands on a controlled manner publicly somehow and not limited to any context.
