### ISSUE TITLE
ValidateAll() Broken in Preview

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1434]
I verified this bug by rolling back to `v0.9.1.2`.

First note how it should work by looking at the Forms -> Validations page in the [Blazorise Demo](https://bootstrapdemo.blazorise.com/tests/validations). Click **Submit** in the _Manual Annotation Validation_ form. You'll notice that it validates properly.

But try that with the latest Preview and it will not validate on the _first_ click, it will validate on the second. For some reason, it passes validation on the first click. The `annotationsValidations.ValidateAll()` code in the demo returns true on the first click.

I first noticed this because my own code stopped validating properly.

**Comment by stsrki** [comment]
You're right, I can confirm the issue. Thank you for notifying us!
