### ISSUE TITLE
DataGrid: Column Order Issue

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1435]
**Describe the bug**
If you wrap a DataGridColumn in a component to reuse common markup / defaults, then somehow the order is lost once rendering the grid together with regular DataGridColumn

**To Reproduce**
1 - Wrap a DataColumn in a component.
2 - Use the wrapped DataColumn component in first place on the Grid DataGridColumns definition
3 - Use a normal DataGridColumn after this one
4 - The normal DataGridColumn will render in first place.

**Expected behavior**
Render in the order of the markup or able to set order somehow. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22283161/98053665-face0000-1e30-11eb-92d2-14aeb767eca2.png)

**Comment by David-Moreira** [comment]
DisplayOrder is a workaround for this. Even if a bit manual.
And if you just want to set something rapidly to the top without configuring order on every other column, just set it to a negative display order.

@stsrki #1880 fixes this indirectly. There's now tools to assert the order. However, I don't know if you'd still like to take a look into this, and make it faithful to the actual markup order, even if the component is composed(wrapped) of another one.

**Comment by stsrki** [comment]
I have completely forgotten about this ticket. Who can track all of them!? 😅

Yeah, it seems DisplayOrder has fixed this and I think we can close it. Agree?

**Comment by David-Moreira** [comment]
Yep. Closing.  👍
