### ISSUE TITLE
Material Horizontal bar not toggling

### ISSUE THREAD

**Issue by MathieuDR** [stsrki/Blazorise#1438]
**Describe the bug**
When you create a horizontal bar using the Material provider, have a breakpoint set. Using the 'toggler' does nothing.

**To Reproduce**
1. Create a blazorised blazor app using the Material provider
2. Create a horizontal bar component with some items
3. Resize your browser to hit your breakpoint
4. Click toggler
5. Nothing happens

**Expected behavior**
A dropdown like on the [example](https://blazorise.com/examples/bars/basic/). To use as a mobile menu.

Code example of the bar
```
<Bar Mode="BarMode.Horizontal" Breakpoint="Breakpoint.Widescreen" Background="Background.Dark" ThemeContrast="ThemeContrast.Dark" >
    <BarBrand>Blazorise</BarBrand>
    <BarToggler></BarToggler>       
    <BarMenu>
        <BarStart>
            <BarItem>
                <BarLink To="#front">Link in the start</BarLink>
            </BarItem>
        </BarStart>
        <BarEnd>
            <BarItem>
                <BarLink To="#1">Link 1</BarLink>
            </BarItem>
            <BarItem>
                <BarLink To="#2">Link 2</BarLink>
            </BarItem>
            <BarItem>
                <BarLink To="#3">Link 3</BarLink>
            </BarItem>
            <BarItem>
                <BarLink To="#4">Link 4</BarLink>
            </BarItem>
            <BarItem>
                <Button Size="ButtonSize.Large" Color="Color.Secondary">CTA</Button>
            </BarItem>           
        </BarEnd>
    </BarMenu>
</Bar>
```

**Additional context**
First time using Blazor/Blazorise. Might be on my end.
Someone validating this bug would be appreciated.

**Comment by stsrki** [comment]
I tried to reproduce it but it works on my end. Not sure what material CSS version you're using but please try https://github.com/djibe/material. It's a fork from **daemonite** and is actively maintained.

All future work in Blazorise will be based on **djibe** since http://daemonite.github.io/material/ is abandoned.

**Comment by MathieuDR** [comment]
Hey

Thanks for the reply, I was doubting to use Blazorise.Material because it was so outdated, I've fixed this, updated the JS and SCSS files.

I'm still unable to toggle the navbar, but I'm fairly sure it's the "show/showing" not toggling on the bar menu.

I'll be creating a Repo with my issue.

**Comment by stsrki** [comment]
I forgot to tell you. This was the issue with 0.9.1.x version but in one of the previews of 0.9.2 it was fixed. In case you want to try it just follow this https://github.com/stsrki/Blazorise#try-preview

Anyways, the plan is to release it sometime next week or so.

**Comment by MathieuDR** [comment]
> I forgot to tell you. This was the issue with 0.9.1.x version but in one of the previews of 0.9.2 it was fixed. In case you want to try it just follow this https://github.com/stsrki/Blazorise#try-preview
> 
> Anyways, the plan is to release it sometime next week or so.

This fixed the issue! thanks 👍
