### ISSUE TITLE
Bug on nullable value for select

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1439]
select can not handle  nullable value
selected event doesn't worked

public enParenatalRating? ParentalRating { get; set; }

<Select TValue="enParenatalRating?" @bind-SelectedValue="@Content.ParentalRating">
                @foreach (var item in Enum.GetValues(typeof(enParenatalRating)).Cast<enParenatalRating>())
                {
                    <SelectItem Value="@item">@item</SelectItem>
                }
            </Select>

I can handle with this code but is it can be changed on component side ?

`
<Select TValue="string" SelectedValue="@ParentalRating" SelectedValueChanged="OnParentalRatingChanged">
                <SelectItem Value="@("")" Display="Display.None"></SelectItem>
                @foreach (var item in Enum.GetValues(typeof(enParenatalRating)).Cast<enParenatalRating>())
                {
                    <SelectItem Value="@item.ToString()">@item</SelectItem>
                }
            </Select>

 private string ParentalRating = "";
        private void OnParentalRatingChanged(string _ParentalRating)
        {
            ParentalRating = _ParentalRating;
            if (!ParentalRating.Equals("") && Enum.TryParse(_ParentalRating, out enParenatalRating _Type))
                Content.ParentalRating = _Type;
        }
`

**Comment by justslon** [comment]
It seems, that all components doesn't work well with nullable item types. "Changed" event not raising when selected value changed to null from non-null. I think this is bug.

**Comment by stsrki** [comment]
This is unfortunately a known limitation. See this https://github.com/stsrki/Blazorise/issues/185
