### ISSUE TITLE
Datagrid Filter speed typing issue

### ISSUE THREAD

**Issue by taylorjimbo** [stsrki/Blazorise#1442]
I've had this issue since version 9.0 and it is still in version 9.1.2. If you type quickly in the one of the column filters the cursor jumps back as you are type causing character to be typed over which messes up the filter. Example: when trying to filter the name "James". When typed quickly you end up with "Jms" or "Js". 

I have noticed this does not happen with the DEMO ( [https://bootstrapdemo.blazorise.com/tests/datagrid](https://bootstrapdemo.blazorise.com/tests/datagrid) ), but if I download the latest source and republish it to my server then it does happen. I have also noticed it does not happen when running in debug mode. 

I have tried adding the following Filter Template, but it did not resolve the issue. 

```
<DataGridColumn TItem="Employee" Field="@nameof(Employee.FirstName)" Caption="First" Sortable="true">
      <FilterTemplate>
          <TextEdit DelayTextOnKeyPress="true" TextChanged="@(v=>context.TriggerFilterChange(v))" />
      </FilterTemplate>
</DataGridColumn>

```

Any Ideas or Suggestions?

**Comment by stsrki** [comment]
It's a known issue and a workaround can be found here https://github.com/stsrki/Blazorise/issues/1429

You can try to increase the delay but even that is not guaranteed to work. For this milestone, it's too late but for the next, I plan to do some major refactorings of edit components and I hope it will help.

**Comment by taylorjimbo** [comment]
Thanks Mladen.

 I increased the delay all the way to 3000, but still had the issue. 

        ChangeTextOnKeyPress="false"
        DelayTextOnKeyPress="true"
        DelayTextOnKeyPressInterval="3000"

I ended up going with the standard input with CSS to match TextEdit style:

```
<DataGridColumn TItem="Employee" Field="@nameof(Employee.FirstName)" Caption="First">
    <FilterTemplate>
            <input type="text" class="filter" @oninput="@(v=>context.TriggerFilterChange(v.Value.ToString()))" />
    </FilterTemplate>
</DataGridColumn>


.filter {
    display: inline-block;
    box-sizing: border-box;
    padding: 0.4em;
    margin: 0em;
    margin-top: 0.6em;
    outline: none;
    border: 1px solid #dadada;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    width: 100%;
}

    .filter:focus {
        border: 2px solid #7bc1f7;
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        -moz-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
    }

```

This fixed the speed typing issue for me in the Data grid filter.

**Comment by stsrki** [comment]
That is a perfectly good approach as long as it works for you :)

I will close this ticket since there are already similar issues open.
