### ISSUE TITLE
Steps component

### ISSUE THREAD

**Issue by LukeTOBrien** [stsrki/Blazorise#1455]
Hello,

In my app I am currently using the [Radzen Steps component](https://blazor.radzen.com/steps) which works very nicely, but doesn't seem to have an API for programatically changing the steps.  
I also like [jQuery Steps](http://www.jquery-steps.com/).

I think this could be simple addition, it's basically very similar to tabs.

What do you think?

Luke

....
As an aside, I see in your [Roadmap](https://blazorise.com/docs/roadmap/#long-term) that you have Long term **Completely remove JavaScript** and I would just like to say woah there (as in to stop a horse), let's not go crazy, wasm is designed to **complement** JS not to replace it, this long-term goal is probably not possible either as wasm can't do DOM manipulation.

**Comment by LukeTOBrien** [comment]
@stsrki  .... I see you have been busy...

**Comment by stsrki** [comment]
@LukeTOBrien Yep. It was NOT easy I must say 😅

**Comment by LukeTOBrien** [comment]
@stsrki Still you'll be a better man for it ;-)
