### ISSUE TITLE
DataGrid styling documentation

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1460]
I am having trouble finding a correct way to set font size for an entire datagrid, or at least parts of it, and there is no example in the docs. Can somebody please provide an example and add it to the documentation?

**Comment by stsrki** [comment]
The only option is to use CSS and target table by `.table` selector. To make it more specific you can add a custom class name to DataGrid. eg. `<DataGrid Class="my-class">` which will be rendered as `<table class="table my-class">`.
