### ISSUE TITLE
Provide new object/objectFactory for DataGrid

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1464]
**Is your feature request related to a problem? Please describe.**
I do not see any way to provide a new object for dataGrid to use for new command. It tries to create one itself but that is not enough for me. I know I can modify it before it is inserted, but that is hacky at best.

**Describe the solution you'd like**
Instead I would like to create a fresh object myself and give it to dataGrid to populate with fresh values. Alternatively (and this does not exclude the previous approach) I would like to be able to provide an object factory to dataGrid instead,

### Additional context
I have a fairly complex entityFramework object with many built in safeties that are causing trouble when dataGrid starts assigning values that have not been properly initialized, and I do not want to create an entirely separate object just for it to save the values and then copy them manually into properly prepared new object.

**Comment by stsrki** [comment]
Have you tried `NewItemDefaultSetter`?

https://blazorise.com/docs/extensions/datagrid/#newitemdefaultsetter

**Comment by Luk164** [comment]
@stsrki Oh my god I am blind, thx for the tip.

**Comment by Luk164** [comment]
@stsrki Weird, for some reason intelliSense is not picking it up. Though that is probably a fault on my side, the latest update screwed my IDE up a little.

**Comment by stsrki** [comment]
I just released the new version 0.9.2 :)

**Comment by Luk164** [comment]
@stsrki Explains a lot :)

**Comment by stsrki** [comment]
Don't forget to read about breaking changes :) https://blazorise.com/news/release-notes/092/

**Comment by Luk164** [comment]
@stsrki For sure, have a coffee on me

**Comment by stsrki** [comment]
Thank you 😉

**Comment by Luk164** [comment]
Well it turns out I still need to be able to provide a new object factory it would seem. Specifically I use lazy-loading proxies in my DB. Considering your code just creates a new object of the required type, this would have two benefits:

- We could use objects w/o a parameterless constructor
- We could use proxies instead of objects themselves

**Comment by Luk164** [comment]
@stsrki Do you think this could be added? It does share some functionality with the NewItemDefaultSetter but it is not the same. Maybe I could completely replace the reference it gives me for setting but then we have wasted resources creating an object from scratch just to be thrown out.
