### ISSUE TITLE
DataGrid Cannot Display Foreign Key Values With Same Name as Parent

### ISSUE THREAD

**Issue by ddelella** [stsrki/Blazorise#1466]
**Describe the bug**
I have a list of Items each with a Brand.  I want to display the Item.Name property and the Item.Brand.Name property in the DataGrid component.  When I place the fields in the DataGrid I see the Item.Name repeated twice.

**To Reproduce**
1. Create a class with a foreign key one-to-one relationship to another class.
2. Populate each class with sample data.
3. Create a DataGrid component to display the Name property of class A and class B.
4. No error with display but the class A Name property will display twice instead of class A and class B.

**Expected behavior**
I should see the Name of the Item class and the Name of the Brand class.

**Sample Code**
NOTE: The following is the short definitions for the Item and Brand classes, the DbContext which I use through EFCore to connect to a SQLite database.  I also included the DataGrid code and service to gather the data.
```

public partial class Item
{
	[Key]
	public int Id { get; set; }

	public string Name { get; set; }

	public int BrandId { get; set; }

	public virtual Brand Brand { get; set; }
}

public partial class Brand
{
	[Key]
	public int Id { get; set; }

	public string Name { get; set; }

	public virtual Item Item { get; set; }
}

public class MyContext : DbContext
{
	public MyContext(DbContextOptions<MyContext> options) : base(options) { }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Item>()
			.HasOne<Brand>(i => i.Brand)
			.WithOne(b => b.Item)
			.HasForeignKey<Brand>(b => b.Id);
	}

	public DbSet<Brand> Brands { get; set; }
	public DbSet<Item> Items { get; set; }
}

public class ItemsService
{ 
	private readonly MyContext _context;

	public ItemsService(DaintyvilleContext context)
	{
		this._context = context;
	}

	public async Task<List<Item>> Get(int ListingId)
	{
		return await _context.Items
			.Include(x => x.Brand)
			.ToListAsync();
	}
}

<DataGrid TItem="Item"
		  Data="@Items"
		  @bind-SelectedRow="@SelectedItem">
	<ChildContent>
		<DataGridCommandColumn TItem="Item" />
		<DataGridColumn TItem="Item" Field="@nameof(Item.Name)" Caption="Name" />
		<DataGridColumn TItem="Item" Field="@nameof(Item.Brand.Name)" Caption="Brand" />
	</ChildContent>
	<EmptyTemplate>
		<div class="box">
			No Items Found
		</div>
	</EmptyTemplate>
</DataGrid>

```

**Screenshots**
You can see in one of the screen shots that the Item.Name should display Item #1 and the Item.Brand.Name should display Integrity Toys.  Instead the second screen shot shows it displays Item #1 twice.  It does not appear to recognize the foreign key binding.

<img width="960" alt="datagrid-issue-1" src="https://user-images.githubusercontent.com/548747/99207524-2c798c00-278c-11eb-8b83-17d1a0cdab3e.png">
<img width="960" alt="datagrid-issue-2" src="https://user-images.githubusercontent.com/548747/99207525-2d122280-278c-11eb-8292-caaee59aec73.png">

**Additional context**

**Comment by stsrki** [comment]
Hi, thank you for the very detailed report :)

The problem here is that there is no problem. It's actually working as it needs to. You have defined column fields with `nameof` but the thing is that `nameof` will return the name of the last object defined.

So for both of these the grid will get "Name" as a field name.

```
<DataGridColumn TItem="Item" Field="@nameof(Item.Name)" Caption="Name" />
<DataGridColumn TItem="Item" Field="@nameof(Item.Brand.Name)" Caption="Brand" />
```

You should instead write the "path" of the _nested field_  manually.

```
<DataGridColumn TItem="Item" Field="Brand.Name" Caption="Brand" />
```

**Comment by ddelella** [comment]
Thanks!  I was not aware you could just reference the item properties directly.  The examples on the documentation could still use some updating.
