### ISSUE TITLE
Antdesign bugs on v0.9.2

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1473]
Hi
after upgrading ro v0.9.2 Select List,Autocomplete,Dropdown List dosent work propebly 

[link](https://antdesigndemo.blazorise.com/tests/components)

**Comment by stsrki** [comment]
I can confirm. It's strange for all of them to not work. Thank you for the report!

**Comment by stsrki** [comment]
Patch 0.9.2.1 is just released!
