### ISSUE TITLE
Demo Website not loading.

### ISSUE THREAD

**Issue by itsLollo1000** [stsrki/Blazorise#1480]
Hey,

I have been trying to get to you bootstrap demo website via your See it in Action button on "https://blazorise.com/".
Console shows a lot of errors and 404's. 

Hope you can fix that soon.

**Comment by stsrki** [comment]
What demo is not working? I just tried them all and there are no errors.

**Comment by itsLollo1000** [comment]
https://bootstrapdemo.blazorise.com/

Just shows the Cube animations. Give me a second and ill screen my Console Output

**Comment by itsLollo1000** [comment]
[bootstrapdemo.blazorise.com-1605778564735.log](https://github.com/stsrki/Blazorise/files/5565802/bootstrapdemo.blazorise.com-1605778564735.log)


Just uploaded my console log.

**Comment by stsrki** [comment]
That's strange. Try hitting Ctrl+F5 or clear the cache.

**Comment by itsLollo1000** [comment]
Yes strange but it worked hitting Ctrl+F5. Interesting tried that before but didnt work.
