### ISSUE TITLE
AutoComplete ignores TValue and boxes value?

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1483]
**Describe the bug**
I was experimenting with AutoComplete. And it seems to me that we always box the value into an object no matter what. Should it not respect the TItem definition?

**To Reproduce**
![image](https://user-images.githubusercontent.com/22283161/99661231-73e96c00-2a5b-11eb-9e25-03ab43bc0600.png)
results in this with a compiler error:
![image](https://user-images.githubusercontent.com/22283161/99661285-882d6900-2a5b-11eb-912b-f2977799d82f.png)
`__builder3.AddAttribute(40,` "SelectedValueChanged", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<**System.Object**>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<**System.Object**>(this, Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => context.RuleValue = __value, `context.RuleValue))));`

**Expected behavior**
Able to use Blazor's @bind- keyword to automatically bind SelectedValue + SelectedValueChanged.
Should respect TItem and not do a boxing conversion to object?

**Comment by stsrki** [comment]
It's on the list and it's going to be done soon. Here is the tracking ticket #1484 

So, I will close now since it is a duplicate. Tnx
