### ISSUE TITLE
CardTitle "Size" property ignored

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#149]
The following code:

```
<Card Margin="Margin.Is4.FromTop.Is4.FromBottom">
    <CardHeader>
        <CardTitle Size="10">
            Large title
        </CardTitle>
    </CardHeader>
</Card>

<Card Margin="Margin.Is4.FromBottom">
    <CardHeader>
        <CardTitle Size="1">
            Small title
        </CardTitle>
    </CardHeader>
</Card>
```

produces cards with titles exactly the same size. I would have expected "Small title" to be smaller.
![image](https://user-images.githubusercontent.com/11410374/61055786-23371d00-a3ea-11e9-9946-95c56f377d4a.png)

Can you advise how I change the title text size pls?

**Comment by stsrki** [comment]
It should be a number from 1 to 6, where smaller number is larger text. It's basically a `<h>` tag.

**Comment by aford22** [comment]
Hey thanks for the response. I have changed the code to:
```
<Card>
    <CardHeader>
        <CardTitle Size="1">
            Large title
        </CardTitle>
    </CardHeader>
</Card>

<Card>
    <CardHeader>
        <CardTitle Size="6">
            Small title
        </CardTitle>
    </CardHeader>
</Card>
```
but the text sizes are still identical in the cards produced, as shown in the screenshot I attached earlier.

I am using the Material provider, if that makes any difference...

**Comment by stsrki** [comment]
It seems size is ignored for Material CSS provider. I will investigate more for v0.8.1.
Until then you can try to fix it by adding some custom css rules for `card-title` class in `<h*>` tags.
