### ISSUE TITLE
Mix Bar Line Chart

### ISSUE THREAD

**Issue by pvagnini** [stsrki/Blazorise#1490]
Is it possible to generate a chart with both bar and line series in the same chart , the same as it is directly with chart.js please?

**Comment by stsrki** [comment]
Not at the moment, but by looking [at this](https://www.chartjs.org/docs/latest/charts/mixed.html) it should be fairly easy to implement.

It's just a matter of adding an additional type field to the dataset object. Until I add it to the Blazorise, as a workaround you could inherit from `ChartDataset` and add `Type` yourself.

Please let me know if that works.

**Comment by stsrki** [comment]
@pvagnini Have you tried the suggested solution?

**Comment by pvagnini** [comment]
Hi @stsrki, yes extending the ChartDataset appears to work fine. I had to use the generic Chart object rather than the specific BarChart object.

Thanks for your help.

**Comment by pvagnini** [comment]
One more question please. Using native Chart.js to format the axis tick labels you need to provide a js callback function in the Axes=>Ticks=>Callback. Is there any way to achieve this? Callbacks are also used to format the tooltips.

The Title appears to be missing, so I have also successfully created a ChartTitle class which is extended to ChartOptions to show the chart title.

Thanks for your help.

**Comment by stsrki** [comment]
Callbacks are a little tricky so I'm not sure really. I will probably need to do a major change on charts and at this time I don't have much time to do it as I'm too busy with other things. Maybe I can try it for the 0.9.4 milestone.
