### ISSUE TITLE
0.9.2 Breaking Change: Validation.Validate() now requires a parameter

### ISSUE THREAD

**Issue by FStolte** [stsrki/Blazorise#1495]
The public `Validate()` method of the `Validation` component can be used to trigger individual validations manually. It was parameterless in 0.9.1, but in 0.9.2 this method now requires a parameter `newValidationValue`.

Is this method meant to be public API? I am not sure, since it isn't mentioned in the documentation (there, only `Validations.ValidateAll()` is mentioned, which does the same, just for all child `Validation` components).

If it really isn't supposed to be used, it might be worth making it `internal`. Otherwise, it would be nice to have an overload for the method without parameter which defaults to the private `inputComponent.ValidationValue` field.

**Comment by stsrki** [comment]
Hi, it's meant to be used but it seems I missed it by accident. I will add it :)

**Comment by stsrki** [comment]
Patch 0.9.2.1 is just released!
