### ISSUE TITLE
Removing transition in Sidebar

### ISSUE THREAD

**Issue by MAndrade1980** [stsrki/Blazorise#1497]
Hi, is it possible to remove the sliding transition in the sidebar?

**Comment by MitchellNZ** [comment]
@MAndrade1980 are you using the `Sidebar` extension, or the `Bar` with `Mode=Vertical`?

**Comment by MAndrade1980** [comment]
> @MAndrade1980 are you using the `Sidebar` extension, or the `Bar` with `Mode=Vertical`?

Hi, we are using the sidebar extension. It's floating from left to right each time it loads and each time a nav link is clicked, would like to not have the transitions.

**Comment by stsrki** [comment]
@MAndrade1980 `Sidebar` is no longer actively maintained. All new work is now done on `Bar` component with vertical mode. It is advised to switch since it has a lot more features.
