### ISSUE TITLE
Blazorize DataGrid 0.9.1.2 throws exception

### ISSUE THREAD

**Issue by RachelTerry** [stsrki/Blazorise#1498]
**Describe the bug**
TypeLoadException: Method 'CheckSize' in type 'Blazorise.Bootstrap.BootstrapClassProvider' from assembly 'Blazorise.Bootstrap, Version=0.9.1.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.

First found when using DataGrid, but AutoComplete also affected.

**To Reproduce**
1. Install-Package Blazorise.DataGrid
2. @using Blazorise.DataGrid
3. Define simple data grid
4. F5 in VS2019

**Expected behavior**
Grid should work. Already have TreeView installed and working.

**Comment by stsrki** [comment]
It sounds to me like you have different assemblies loaded. Can you re-check and also please upgrade to the latest v0.9.2. I don't have plans to support 0.9.1.x any more.

**Comment by RachelTerry** [comment]
I did install the latest and thus the errors. I am currently using 0.9.1.2 because those work. But something in the 0.9.2 release broke all components.

**Comment by stsrki** [comment]
Did you upgrade your project to support .Net 5? There were some changes that you need to do. You can look at demo apps for reference https://github.com/stsrki/Blazorise/tree/master/Demos

**Comment by stsrki** [comment]
Also, look at this https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio

Please let me know how it goes so I can close this ticket.
