### ISSUE TITLE
Autocomplete feature request

### ISSUE THREAD

**Issue by ikkyGH** [stsrki/Blazorise#150]
Apologies if any of these are already implemented and i am missing them, but here are some suggestions for the autocomplete component:

1. It does not expose a size property like a textedit or other controls.

2.  Once you start typing, you cannot use the arrows to refine your selection.

3.  There isn't a way to clear it after a selection

Thanks in advance

**Comment by stsrki** [comment]
Third issue is already on schedule to fix #142 

They will be done in v0.8.1

**Comment by stsrki** [comment]
Done, Will be in 0.8.1
