### ISSUE TITLE
form-group row - doesn't work well when it's at a low resolution

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1504]
![image](https://user-images.githubusercontent.com/12803050/99907057-6b8e6c80-2cb9-11eb-9f77-0c8a2b3297b1.png)
![image](https://user-images.githubusercontent.com/12803050/99907069-734e1100-2cb9-11eb-9218-7640a156bca1.png)

```
<Field Horizontal="true">
                            <FieldLabel ColumnSize="ColumnSize.Is4"><Icon Name="Blazorise.Icons.FontAwesome.FontAwesomeIcons.User"></Icon> Nome / Apelido</FieldLabel>
                            <FieldBody ColumnSize="ColumnSize.Is8">
                                <TextEdit Placeholder="Ex: Paulo ou Paulinho"></TextEdit>
                            </FieldBody>
                        </Field>
```

when I use this 'form-group row' concept, in the original bootstrap if I lower the resolution, the default behavior is to leave the label above the textbox. but in the blazorise it keeps it fixed in the same place, breaking the layout.

**Comment by stsrki** [comment]
You need to define different breakpoints for each device that you want.

**Example:**

```cshtml
<Field Horizontal="true">
    <FieldLabel ColumnSize="ColumnSize.IsFull.OnTablet.Is2.OnDesktop">Name</FieldLabel>
    <FieldBody ColumnSize="ColumnSize.IsFull.OnTablet.Is10.OnDesktop">
        <TextEdit Placeholder="Some text value..." />
    </FieldBody>
</Field>
```

**Comment by stsrki** [comment]
@drma-dev Have you tried the solution from above?

**Comment by stsrki** [comment]
I think the posted answer should work and I will close the ticket now. In case it does not work, please reopen.

**Comment by drma-dev** [comment]
that works. thanks.
