### ISSUE TITLE
cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<Enum.Intent[]>' to 'Microsoft.AspNetCore.Components.EventCallback'

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1506]
```
<Select TValue="Intent" Multiple="true" @bind-SelectedValues="@profile.Intent">
                                        @foreach (var item in EnumHelper.GetArray<Intent>())
                                        {
                                            <SelectItem Value="@item">@item.GetName()</SelectItem>
                                        }
                                    </Select>
```

The only way I can work with collections is this way:
`public IReadOnlyList<Intent> Intent { get; set; }`

If I try to work with another type (eg array) it gives this error.

I know it's probably a limitation of blazor, but as you worked on those components, you should know how to get around that.

**Comment by stsrki** [comment]
It's working that way because `SelectedValues` is of type `IReadOnlyList<TValue>`. And the array is not inherited from `IReadOnlyList`.

Your solution is OK. and if you want to be able to add items to the `Intent` then use `List<>`.

**Comment by drma-dev** [comment]
I've tried it too, but it always keeps giving me the following errors:

`'Microsoft.AspNetCore.Components.EventCallback<System.Collections.Generic.List<VerusDate.Shared.Enum.Intent>>' to 'Microsoft.AspNetCore.Components.EventCallback'`

`Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type	VerusDate.Client`

**Comment by stsrki** [comment]
I would say `@bind-` is not an option here. Instead, use `SelectedValues` and `SelectedValuesChanged` to bind the values manually.
