### ISSUE TITLE
Antdesign datagrid pager issue

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1509]
there is a problem with datagrid pager in antdesign . page sizes dose not shown.

[link](https://ibb.co/kK3NJs4)

**Comment by stsrki** [comment]
That's strange. It doesn't show you any item at all? Can you inspect through dev tools? 

Also what version of Blazorise you're using?

**Comment by mortezabarzkar** [comment]
i'm using last version 

                <PackageReference Include="Blazorise.AntDesign" Version="0.9.2.1" />
		<PackageReference Include="Blazorise.Charts" Version="0.9.2.1" />
		<PackageReference Include="Blazorise.Charts.Streaming" Version="0.9.2.1" />
		<PackageReference Include="Blazorise.Components" Version="0.9.2.1" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" Version="0.9.2.1" />

[link](https://ibb.co/rdShny7)

**Comment by mortezabarzkar** [comment]
I have same problem with select . select list and dropdown.
if you want i can give you access to my project

**Comment by mortezabarzkar** [comment]
i tried  to use bootstrap but view is very different when i used antdesign

**Comment by stsrki** [comment]
If you can give me access to the project that would be for the best. It's hard to guess what is wrong.

**Comment by mortezabarzkar** [comment]
how can i send user and password for you ?

**Comment by stsrki** [comment]
Just add me as a contributor to the project.

![image](https://user-images.githubusercontent.com/900302/100083421-c1921a00-2e49-11eb-9e4c-457daf816b14.png)

**Comment by mortezabarzkar** [comment]
i mean give you user name and password for running project.
i can send it via email or from your LinkedIn  profile

**Comment by stsrki** [comment]
You can send it to st.srki@gmail.com

**Comment by mortezabarzkar** [comment]
ok . pls check your mail

**Comment by stsrki** [comment]
Can you also send a username and pass over email or linkedin?

**Comment by mortezabarzkar** [comment]
check your email pls

**Comment by stsrki** [comment]
OK, I found your problem. You have `TabPanel` (`ant-tabs-tabpane`) that is the same size as it's content. In this case, it's the same size as DataGrid and because of that, when select is opened it will be under the div boundaries. 

As a workaround, you can set the height of the `TabPanel` manually, or try setting the `z-index` of one of the select `div` tags. But I think increasing `TabPanel` size is the best options.

**Comment by mortezabarzkar** [comment]
thank you.
also is it possible to define min height to datagrid to have space between rows and pagination ?

**Comment by stsrki** [comment]
Currently, it's possible only by using CSS and targeting the table element.

**Comment by stsrki** [comment]
PS. your app looks really nice :)

**Comment by mortezabarzkar** [comment]
![image](https://user-images.githubusercontent.com/6237492/100089101-32ddc700-2e62-11eb-840f-00329f3c5146.png)
how can i dissable this ?
and also change item per page select item open direction ?

**Comment by mortezabarzkar** [comment]
my app looks really nice because of your grate components

**Comment by stsrki** [comment]
You can disable it with CSS. I can try adding support for render template for that select but it's not going to be any time soon.

**Comment by mortezabarzkar** [comment]
is it possible to catch item per page changed event ?

**Comment by stsrki** [comment]
No, but it is a good idea.
