### ISSUE TITLE
z-index issue with autocomplete (and other items)

### ISSUE THREAD

**Issue by matt-goldman** [stsrki/Blazorise#1510]
**Describe the bug**
Similar to the issue reported in #636 

I have seen this happen with other UI elements but the current problem I'm having is with Autocomplete using Material provider.

When typing, the list appears, but it doesn't extend outside the container so only the first item is visible.

**To Reproduce**
1. Add a container element, e.g. an HTML table cell, an accordion body, etc.
2. Inside this container add an autocomplete
3. Start typing in the autocomplete to populate the list

I have a sample repo that demonstrates the issue here: https://github.com/MattGoldmanSSW/blazorise-overflow-test

**Expected behavior**
Autocomplete list extends outside the container (as can be seen with the two select lists in the same container)

**Additional context**
I have tried setting Overflow="visible" to no effect. I have also tried setting the z-index with a style and forcibly setting the z-index in an inline style, both also to no effect.

**Comment by matt-goldman** [comment]
I have also noticed this occurs in your demo: https://materialdemo.blazorise.com/tests/components

I tested this in Chrome, Edge (Chromium) and Firefox and observed the same behavior in each.

**Comment by mortezabarzkar** [comment]
I have same issue with antdesign

**Comment by devinbandara** [comment]
Any updates on this issue? I am experiencing it as well.

**Comment by stsrki** [comment]
It's scheduled for the next milestone.

**Comment by UltimateForm** [comment]
I believe I am experiencing this with the LayoutSideBar and Button components while using MaterialUI toolkit. A class named `b-layout-sider-content` add `z-index` attribute with value 2 which seems to hide the ripple effect on button click. Removing that rule  or setting it to 1 reveals the ripple effect

**Comment by GG-Garcia** [comment]
with the issue of it hiding behind with Autocomplete.

if you set the Autocomplete element with a class that has `min-height: 10px(example)`, and height:auto, and the dropdown-menu class position is set to relative  `position:relative` it shows all the fields. however, i have no idea how to overide the the dropdown-menu class. any ideas?
