### ISSUE TITLE
DateEdit control does not accept a typed year when using binding and DataAnnotations validation

### ISSUE THREAD

**Issue by Welchen** [stsrki/Blazorise#1515]
When typing in the DateEdit textbox and entering a valid date, when you get to the year section it won't fill out all 4 digits. 

It works when not using Validation but when I add Validation it starts to have issues.

```
<Validations Mode="ValidationMode.Auto" Model="@_ValidationModel" @ref="_Validations">
       <Validation>
            <Field Horizontal="true">
                  <FieldLabel ColumnSize="ColumnSize.Is3">Expiration</FieldLabel>
                  <FieldBody ColumnSize="ColumnSize.Is9">
                       <DateEdit @bind-Date="@_ValidationModel.End" TValue="DateTime?"  />
                  </FieldBody>
             </Field>
       </Validation>
</Validations>

    public class ValidationModel
    {
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date)]
        public DateTime? End { get; set; }
    }
```

**Comment by jn10414** [comment]
@Welchen 

I have the same problem.
Is it not good to not accept key input?

`
<DateEdit @bind-Date="@_ValidationModel.End" TValue="DateTime?" onkeydown="return false" />
`

**Comment by stsrki** [comment]
This is the old problem https://github.com/stsrki/Blazorise/issues/1029#issuecomment-650560390

Basically, I don't have a quick way to fix this unless I do a major rewrite of the date component and that can be a one-way down the rabbit hole.

**Comment by Welchen** [comment]
Can the textbox be disabled and only use the calendar control?

**Comment by stsrki** [comment]
Do you mean to show the browser popup?

![image](https://user-images.githubusercontent.com/900302/100114474-c66ac400-2e71-11eb-8e95-220a9abc0d72.png)

🤔 it might be a good alternative

**Comment by Welchen** [comment]
Yeah.  Clicking the icon on the control gives that and works just fine.  The only bug is when typing in the control.  A way to disable being able to type and only select (and be able to clear) would at least make the control usable in this scenario of being nullable and using a validator.
