### ISSUE TITLE
Command no longer called upon clicking a button

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1516]
**Describe the bug**
I updated to 0.9.2 and the buttons no longer work in my app. I have the idea that with the new programmatic rendertree the commands are no longer called.

https://github.com/stsrki/Blazorise/blob/dev092/Source/Blazorise/Button.cs

I think the ClickHandler method is never bound.

For me this a blocker so I can't upgrade Blazorise

**Comment by stsrki** [comment]
You're right, sorry about that. I missed it while testing. It's going to be fixed with next patch.
