### ISSUE TITLE
SelectList no longer working for objects

### ISSUE THREAD

**Issue by JaredMRomano** [stsrki/Blazorise#1517]
**Describe the bug**
In latest 0.9.2 from nuget
When using a complex object as a value in selectList, in the callback, it returns a string containing the name of the type object, instead of the actual object.

**To Reproduce**
```razor 
<SelectList
     TItem="Team"`
     TValue="Team"
     Data="@DataContext.User.Organization.Teams"
     TextField="@(item=>item.DisplayName)"
     ValueField="@(item=>item)"
     SelectedValue="@DataContext.SelectedHostTeam"
     SelectedValueChanged="@MyListValueChangedHandler">
</SelectList> 

@code {
    void MyListValueChangedHandler(object newValue)
    {
        DataContext.SelectedHostTeam = (Team) newValue;
    }
}
```

When MyListValueChangedHandler gets called the parameter is a string which contains the name of the type "Team".
If I try to setup the paramter for the handler to be of type Team, it never calls the handler.
Using @bind-SelectedValue never sets the value, so I cant do that either.

The only workaround for now is doing something like this:

```razor 
                    <SelectList
                                TItem="Team"
                                TValue="int"
                                Data="@DataContext.User.Organization.Teams"
                                TextField="@((item)=>item.DisplayName)"
                                ValueField="@((item)=>item.Id)"
                                SelectedValue="@DataContext.SelectedHostTeam"
                                SelectedValueChanged="@MyListValueChangedHandler">
                    </SelectList>
@code {
    void MyListValueChangedHandler(int id)
    {
            DataContext.SelectedHostTeam = DataContext.HostTeams.FirstOrDefault(t => t.Id == id);
    }
}
```
Then just use a computed value or something. 

**Expected behavior**
I would expect it to work like all the other controls, SelectedValue should bind to the type defined for TValue and the SelectedValueChanged Callback should provide the same type in the parameter.

**Comment by stsrki** [comment]
`Select `cannot work with complex types. Under the hood, all values must be converted to `string` so that they be assigned to the `<option>` tag in the DOM. And a complex object cannot be converted to a string, or not easily. There's no way around it.

Your workaround is actually the proper way to do it.

**Comment by JaredMRomano** [comment]
Thanks,  just making sure I didn't miss anything.
