### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by nic0l45** [stsrki/Blazorise#152]
![image](https://user-images.githubusercontent.com/48603062/61153128-48925c80-a4b8-11e9-8dbb-ffef660bc73a.png)

Hi to all  i have this error when i try to open a page with an Alert. Thanks in advance for any help.

**Comment by stsrki** [comment]
Hi, just change the attribute `ref` to `@ref`

**Comment by nic0l45** [comment]
![image](https://user-images.githubusercontent.com/48603062/61156541-a37c8180-a4c1-11e9-8ebf-cd527db94185.png)

I have this now, it doesn't allow me to build.

**Comment by stsrki** [comment]
What version of visual studio are you using? You must have VS 2109 **Preview** to work with Blazor and Blazorise.

**Comment by nic0l45** [comment]
![image](https://user-images.githubusercontent.com/48603062/61156762-361d2080-a4c2-11e9-8622-ed54eed12ced.png)

**Comment by stsrki** [comment]
The RC is not supported yet by Blazor. You must download VS2019 preview from here https://visualstudio.microsoft.com/vs/preview/
Community version is just fine.

Also, in case you have something else missing here is the full installation guide for Blazor https://docs.microsoft.com/hr-hr/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

**Comment by nic0l45** [comment]
First: I tried with VS 2019 Community Preview.
Second: A Coworker have the same version of VS (2019 Professional).

**Comment by stsrki** [comment]
@nic0l45 Did you managed to find the solution?
