### ISSUE TITLE
Validation does not work as desired

### ISSUE THREAD

**Issue by NicolasFVS** [stsrki/Blazorise#1520]
The validation component behaves strangely. In automatic mode the fields should be normal on opening and indicate mandatory on validation. But they are all in red as soon as the page loads

Normals fields when opening, red indications on submit button

Regards

**Comment by stsrki** [comment]
That's the default behavior. Look at this https://blazorise.com/docs/components/validation/#auto-validation

**Comment by NicolasFVS** [comment]
Thank-you we need to put ValidateOnLoad at false value...
