### ISSUE TITLE
Tabs Components

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1529]
When Tabs count increased more than view width tabs can not displayed .
![Tabs](https://user-images.githubusercontent.com/6237492/100199683-9a515080-2f0e-11eb-8dd9-10448d9004f1.PNG)

**Comment by mortezabarzkar** [comment]
@stsrki  ??

**Comment by stsrki** [comment]
Sorry I missed this. It's a missing feature that I will need to add for AntDesign. Going on 0.9.4 milestone for now.

**Comment by mortezabarzkar** [comment]
Thank you

**Comment by mortezabarzkar** [comment]
@stsrki 

For now i can  handle with css


 .ant-tabs-nav-scroll {
        white-space: normal !important;
    }

    .ant-tabs-nav-container {
        white-space: normal !important;
    }
