### ISSUE TITLE
Using TextChanged and @bing-Text error

### ISSUE THREAD

**Issue by ikkyGH** [stsrki/Blazorise#153]
When i have a textEdit and try to use the @bind-Text & TextChanged property, I get the below error:

`<TextEdit Placeholder="First Name" @bind-Text="@currentUser.firstName" TextChanged="@UpdateUserName" />`

> The component parameter 'TextChanged' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'TextChanged' is generated by the '@bind-Text' directive attribute.

They seem to be stepping on each other.  Are there any other events that i can use for this functionality?  I need to keep that field binded, but i want to update another field when the value changes.  OnKeyUp would be the idea event.

**Comment by stsrki** [comment]
You can't use both at the same time. That's actually a limitation by the Blazor itself. You just need to set your variable inside of the UpdateUserName(). 

Here is an example: https://blazorise.com/docs/components/text/#with-bind-attribute

**Comment by ikkyGH** [comment]
That worked, thanks.
