### ISSUE TITLE
Datagrid filter

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1531]
is it possible to filter  date column by range ?
and also set filter mode per fields ?

**Comment by stsrki** [comment]
You can only use `CustomFilter` on DataGrid. Regarding the custom filter per column, that seems like a good idea to have. I will try to make it.

**Comment by mortezabarzkar** [comment]
@stsrki also if you can prepare refresh button on pagination bar it will be usable

**Comment by David-Moreira** [comment]
Adding to this:
A clickable filter icon by the filter field that when you press let's you select the type of filter to apply on that column (contains, starts with, equals, less then, more then, etc...) based on the type of data, string, date, numeric, etc...
And able to take in custom filters defined by the programmer. 👋

**Comment by stsrki** [comment]
@David-Moreira  Filter icon can be done through the FilterTemplate, but it still needs an API to set the actual filter method.

**Comment by David-Moreira** [comment]
Fine. Just saying, in my opinion, If you're gonna implement various filter modes per column, might as well have them available not only programmatically (you're probably thinking of making it a parameter of the datagrid column?) but if the programmer chooses to do so, also readily available on the interface, for the end user to select them. 
Can be an icon, an arrow or anything, it would be great to already have the filters you have created quickly available there on the interface, 

than if the programmer wants to customise,  comes the part that if you expose the api then the programmer can further do as he pleases. But if he has that option out of the box, it's a plus!! 👍

It's a bit like the command buttons... They're already "opinated" in how they are setup, the out of the box option is that they come on a per row basis with the internal commands mostly abstracted from the programmer.

I'll see if I can get you some examples later.

**Comment by stsrki** [comment]
No no, I completely agree with you. I just said that we will also need to have some kind of API to extend filtering. And I will create it once I get to it.

**Comment by stsrki** [comment]
done with #2187
