### ISSUE TITLE
SelectedValueChanged never called

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1533]
**Describe the bug**
SelectedValueChanged never gets called, even though it should.

**To Reproduce**
See attached code

**Expected behavior**
SelectedValueChanged gats called and the value is changed according to users selection.

**Additional context**
I was trying to create a selection element that is dynamically filled with available products, though it seems I will have to go with a shopping cart instead. While this approach will probably get dropped it is still something I would consider useful to have working.

Here is a sample of the misbehaving code:

```
<DataGridSelectColumn TItem="OrderRow" Field="@(nameof(OrderRow.Product))" Caption="Produkt" Editable="true">
        <EditTemplate>
            <Select TValue="Product" SelectedValue="@((Product) context.CellValue)" SelectedValueChanged="value => { throw new NullReferenceException(); context.CellValue = (object) value; }">
                @foreach (var product in ViewModel.GetAvailableProducts())
                {
                    <SelectItem Value="product">@product.Kind</SelectItem>
                }
            </Select>
        </EditTemplate>
        <DisplayTemplate>
            @(((OrderRow) context).Product.Kind)
        </DisplayTemplate>
    </DataGridSelectColumn>

```

**Comment by Luk164** [comment]
Ok, just found out I should have been using selectList, still an interesting bug to squash though.

**Comment by stsrki** [comment]
You're using a complex object for the select value (`TValue="Product"`), which is not supported. While it might work in some cases, the bigger problem is that everything runs on the browser. So the object value must be somehow converted to a string to be assigned to the `<select>` or `<option>` element in the DOM. 

And for the complex that is not so easy. So you should probably use an `int` or ID of your `Product` and assign it as a Select value.

**Comment by Luk164** [comment]
@stsrki Ok, I will see if I can do it with plain html select and manually code everything.
