### ISSUE TITLE
OnFilterChanged Callback

### ISSUE THREAD

**Issue by odskee** [stsrki/Blazorise#1538]
**Is your feature request related to a problem? Please describe.**
When filtering the table, the SelectedRow is not set to null if the selected row is removed by the filter.

**Describe the solution you'd like**
A callback such "OnFilterChanged" that we can use to determine if a filter action has taken place to manually clear the SelectedRow.

### Additional context
Displaying a list of users, when SelectedUser != null further details in a different area are shown.  When filtering by a term that does not display the currently selected user, this needs to be cleared.

**Comment by stsrki** [comment]
It can be done with `FilteredDataChanged` event handler.
