### ISSUE TITLE
ColumnSize not properly working with multiple horizontal form fields

### ISSUE THREAD

**Issue by Muffin1611** [stsrki/Blazorise#1544]
ColumnSize is not properly applying for me as you'd expect it to. I tried several things, but I suspect the issue is persisting and I can't find anything helpful in the docs.

To give an abstract example of how I'm building the form in question:

```
                <Fields>
                    <Validation>
                        <Field Horizontal="true">
                            <FieldLabel ColumnSize="ColumnSize.Is2">Hours</FieldLabel>
                            <FieldBody ColumnSize="ColumnSize.Is4">
                                    <NumericEdit Placeholder="something" @bind-Value="@employee.hours">
                                        <Feedback>
                                            <ValidationError />
                                        </Feedback>
                                    </NumericEdit>
                            </FieldBody>
                        </Field>
                    </Validation>
                    <Validation>
                        <Field Horizontal="true">
                            <FieldLabel ColumnSize="ColumnSize.Is2">Change Date</FieldLabel>
                            <FieldBody ColumnSize="ColumnSize.Is4">
                                <DateEdit TValue="DateTime?">
                                    <Feedback>
                                        <ValidationError />
                                    </Feedback>
                                </DateEdit>
                            </FieldBody>
                        </Field>
                    </Validation>
                </Fields>
```

Followed by similar field groups, whole thing is inside a card. One horizontal field always defaults to taking half the space, no matter what column size I enter. Column size for Field label also isn't respected, but determined by the length of the word in the field label, which makes multiple field groups below not match up. Image is included below:

![blazorise_issue](https://user-images.githubusercontent.com/30754577/100461670-6a9a7800-30c9-11eb-972d-09dcf7d872cb.PNG)

I'm either completely missing something or there is something wrong with how ColumnSize is applied. I'm on v0.9.2.2.

**Comment by stsrki** [comment]
As far as I know, Bootstrap can have only one label and only one input in horizontal mode. If you want to have more, you will need to either adjust CSS or don't use `Horizontal="true"` at all.

**Comment by mdick1611** [comment]
> As far as I know, Bootstrap can have only one label and only one input in horizontal mode. If you want to have more, you will need to either adjust CSS or don't use `Horizontal="true"` at all.

I feared it would be something like this. Thanks for the quick reply, I will have to think about how to solve this via CSS then.
