### ISSUE TITLE
Date component - Placeholder attribute doesn't kick in

### ISSUE THREAD

**Issue by jensengbg-jakob-reesalu** [stsrki/Blazorise#1545]
**Describe the bug**
The placeholder attribute does not change the date component's default placeholder "yyyy-mm-dd". 

**To Reproduce**
1. Add this code:
` <DateEdit TValue="DateTime?" Placeholder="From"/>
  <DateEdit TValue="DateTime?" Placeholder="To"/>`

2. Run the application.

3. See that the date field still shows "yyyy-mm-dd" instead of "From" or "To".

**Expected behavior**
I expected the fields to show "From" and "To", not "yyyy-mm-dd".

**Comment by stsrki** [comment]
DateEdit is using `<input type="date" />`, and unfortunately `placeholder` attribute is not supported for date inputs. The only way around this is to use `<input type="text" />` but that would lead to a lot more trouble with edit mask, date formats, etc.

**Comment by jensengbg-jakob-reesalu** [comment]
Oh, I see! Maybe you want to change the documentation for Date component then, because it says at the bottom that placeholder is an attribute for it.

**Comment by stsrki** [comment]
I have removed `Placeholder` from Date documentation.

Thank you!

**Comment by TheTonyHansen** [comment]
"Placeholder" still appears as an attribute in the DateEdit documentation.  If this isn't supported, please remove it ... I wasted hours trying to get this to work.

https://blazorise.com/docs/components/date/
