### ISSUE TITLE
Only Supporting .NET Core 5

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1546]
I tried upgrading to `0.9.3-Preview 2` and it's telling me I must have .NET Core 5 installed. Is this true?

**Comment by stevenlupo** [comment]
I decided to upgrade to .NET 5. Now the Blazorise packages upgraded to the latest preview just fine. Only now I can't run the project. The problem is in the Startup.cs, I get a compiler error on this line:

`app.ApplicationServices.UseBootstrapProviders();`

The error is:

`'IServiceProvider' does not contain a definition for 'UseBootstrapProviders' and no accessible extension method 'UseBootstrapProviders' accepting a first argument of type 'IServiceProvider' could be found`

**Comment by stsrki** [comment]
Yep, starting with 0.9.3 only .Net 5 is supported. This was needed so that a lot of new features and optimizations could be done. And because of that optimization you don't need and of `.UseMethodName()` like `UseBootstrapProviders`. So just remove them.

**Comment by stevenlupo** [comment]
Okay. Since I'm here, now I'm getting this error:

`CS1503	Argument 12: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback<object>'`

which looks familiar to an issue you had a while back: https://github.com/dotnet/aspnetcore/issues/8385

**Comment by stsrki** [comment]
Are those in Autocomplete or DropdownList? If yes, you need to define TValue.
