### ISSUE TITLE
Blazorise emitting multiple col classes for fields

### ISSUE THREAD

**Issue by Enritski** [stsrki/Blazorise#1548]
**Describe the bug**
When I try to have multiple fields in a field group, using ColumnSize to specify the relative width of each field, the widths are split evenly between them even when I specify an uneven split of widths.  See below:

**To Reproduce**
```
<Fields>
   <Field ColumnSize="ColumnSize.IsHalf">
       <TextEdit @bind-Text="@field1" />
   </Field>
   <Field ColumnSize="ColumnSize.IsQuarter">
      <TextEdit @bind-Text="@field2" />
   </Field>
   <Field ColumnSize="ColumnSize.IsQuarter">
      <TextEdit @bind-Text="@field3" />
   </Field>
</Fields>
```

**Expected behavior**
I would expect the three textboxes in the above sample the be laid out so that the first one is half the full width, and the other two are each one quarter of the full width.

The actual behaviour is that each textbox is the same size: i.e., one third of the full width.

**Additional context**
On closer inspection of the emitted html, I see that we get something like:
```
<div class="form-row">
    <div class="col col-6 form-group">
        <input id="0HM4LB360RLUO" type="text" class="form-control">
    </div>
    <div class="col col-3 form-group">
        <input id="0HM4LB360RLUP" type="text" class="form-control">
    </div>
    <div class="col col-3 form-group">
        <input id="0HM4LB360RLUQ" type="text" class="form-control">
    </div>
</div>
```

Notice that each `form-group` div has the `col` class in addition to the proper one (e.g., `col-6`  or `col-3`).  If I manually remove these extra `col` classes, the layout is rendered properly.  Blazorise should not be outputting the `col` classes if another col-width is specified.

I am using Blazorise.Material v0.9.2.2.

**Comment by WillianGruber** [comment]
I solved this months ago by changing the css load order. I think....
It's been a while...

**Comment by Enritski** [comment]
> I solved this months ago by changing the css load order. I think....
> It's been a while...

I have the following in my `_Host.cshtml`:

```
    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Material/blazorise.material.css" rel="stylesheet" />
```

Is this not right?

**Comment by stsrki** [comment]
In the older version of bootstrap and material, an additional `col` was required so I guess this was a leftover from that time. According to the [bootstrap documentation](https://getbootstrap.com/docs/4.5/components/forms/#form-row) it is now safe to remove extra class and I will do that as soon as possible.

Also, I tried your example and for me, it's working, but I'm using a [djibe material](https://github.com/djibe/material) instead of http://daemonite.github.io/material/. I advise you to switch to **djibe** since it is maintained regularly.

**Comment by Enritski** [comment]
I never noticed the change from Daemonite to djibe material.  When did that come in? I don't see it mentioned in any of the release notes.  I'll install it and give it a go.  Thanks!

**Comment by stsrki** [comment]
I was thinking about it for a long time and I have "silently" switched it in the documentation just recently. Sorry about that :)
