### ISSUE TITLE
DataGrid 'FilterMethod' not taking arguments

### ISSUE THREAD

**Issue by jensengbg-jakob-reesalu** [stsrki/Blazorise#1553]
**Describe the bug**
The FilterMethod attribute of the DataGrid extension does not accept arguments provided in the documentation [(here).](https://blazorise.com/docs/extensions/datagrid/#filtering) It says "StartsWith" doesn't exist in the current context, here's my setup:
```
  <DataGrid TItem="@CalloutStatistic"
              Data="@CalloutStatisticDtos"
              Filterable="true"
              FilterMethod="StartsWith"
              ShowPager="true"
              Hoverable="true">

```

**To Reproduce**
1. Add a DataGrid
2. Add attributes Filterable="true" and FilterMethod="" with any of it's the arguments (StartsWith, Contains, EndsWith etc).
3. You now see the error before running the app.

**Expected behavior**
I expected to change the filter method ^^

**Comment by stsrki** [comment]
You need to define it as

```diff
<DataGrid TItem="@CalloutStatistic"
              Data="@CalloutStatisticDtos"
              Filterable="true"
+              FilterMethod="DataGridFilterMethod.StartsWith"
              ShowPager="true"
              Hoverable="true">
```

**Comment by jensengbg-jakob-reesalu** [comment]
Oh I see! I failed to read this out from the documentation, maybe a clarification could be added?

**Comment by stsrki** [comment]
Example added to the docs. Thanks!
