### ISSUE TITLE
Repeater component

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1562]
For my own project I created a general control that can render a list of multiple items and also has support for `INotifyCollectionChanged`. Maybe it's a good addition for Blazorise aswell. If you like I can add it to Blazorise and create a PR.

Usage:

        <ItemsViewFor Items="@Projects">
            <Button href="/project/@context.Id">@context.Name</Button>
        </ItemsViewFor>

Maybe we need to think of a more clear name.

**Comment by stsrki** [comment]
Maybe `ListView`?

**Comment by njannink** [comment]
I though about it but it doesn't really render a list or div around it. So in the case above it will render the following html:

    <btn>A</btn>
    <btn>B</btn>
    <btn>C</btn>
    ....

**Comment by njannink** [comment]
`ItemsView` or `ItemsRenderer` maybe

**Comment by stsrki** [comment]
So it's more like a repeater?

**Comment by njannink** [comment]
Yep you don't have to write the `for` or `foreach` yourself and it has support for `INotifyCollectionChanged`

**Comment by stsrki** [comment]
So something like this https://www.meziantou.net/creating-a-repeater-component-with-blazor.htm ?

Might be useful. You can create a PR for `dev093` branch and I can have a look at the code.

**Comment by stsrki** [comment]
PS. name it a Repeater and be place in the `Blazorise.csproj` for start.

**Comment by njannink** [comment]
So you can also reuse it within Blazorise eg in a ComboBox. 

So instead of
```
<select name="cars" id="cars">
   @foreach(var item in Items)
   {
      <option value="@item.Key">@item.Name</option>
   }  
</select>
```

you can write
```
<select name="cars" id="cars">
   <ItemsViewFor Items="@Projects">
      <option value="@item.Key">@item.Name</option>
   </ItemsViewFor>  
</select>
```

And you will get support for `INotifyCollectionChanged` aswell

**Comment by njannink** [comment]
@stsrki have a look

**Comment by stsrki** [comment]
Thanks, I will try it later :)
