### ISSUE TITLE
Page selector does not work and is disappeared on demo sites

### ISSUE THREAD

**Issue by DDDenisSobek** [stsrki/Blazorise#1572]
**Describe the bug**
1. Selector for current page is not available on demo sites.
2. For manual read mode selector for current page does not trigger ReadData.

**To Reproduce**
1.1 Look at https://bootstrapdemo.blazorise.com/tests/datagrid
2.1 Build a page like this:
```xml
@page "/TestPage"
<h3>DataGridTestPage</h3>

<DataGrid TItem="TestItem" ShowPager="true" ShowPageSizes="true" Data="@selectedItem" ReadData="@ReadData" TotalItems="@allItems.Count()">
    <DataGridColumn TItem="TestItem" Field="Prop" Caption="Prop" />
</DataGrid>
```
```csharp
    public class TestItem
    {
        public int Prop { get; set; }
    }

    List<TestItem> allItems = Enumerable.Range(0, 100).Select(i => new TestItem() { Prop = i }).ToList();
    List<TestItem> selectedItem = new List<TestItem>();

    public void ReadData(DataGridReadDataEventArgs<TestItem> args)
    {
        selectedItem = allItems.Skip((args.Page - 1) * args.PageSize).Take(args.PageSize).ToList();
    }
```
2.2. Visit it
2.3 Change over selector the current page

**Expected behavior**
ReadData will be called after changing current page over selector.

**Screenshots**
1.1:
![Bug_3_Pic_1](https://user-images.githubusercontent.com/65016836/101052027-6f0dd780-3586-11eb-9b08-32c2ad68bf38.PNG)
2.3:
![Bug_3_Pic_2](https://user-images.githubusercontent.com/65016836/101052028-6fa66e00-3586-11eb-9992-ea9fc4752ee0.PNG)
![Bug_3_Pic_3](https://user-images.githubusercontent.com/65016836/101052029-6fa66e00-3586-11eb-904b-d69f03332a19.PNG)
![Bug_3_Pic_4](https://user-images.githubusercontent.com/65016836/101052030-6fa66e00-3586-11eb-9d2d-6b66b380ab2c.PNG)
![Bug_3_Pic_5](https://user-images.githubusercontent.com/65016836/101052031-703f0480-3586-11eb-83dd-a1d0c875dcff.PNG)

**Comment by DDDenisSobek** [comment]
@stsrki Hey, is this a bug or do i something wrong?

**Comment by stsrki** [comment]
It seems like a bug. Going on the list.

PS. sorry for not answering before.

**Comment by DDDenisSobek** [comment]
> It seems like a bug. Going on the list.
> 
> PS. sorry for not answering before.

No problem.
