### ISSUE TITLE
Layout Grid ColumnSize behavior change .9.1 => .9.2

### ISSUE THREAD

**Issue by CJHCapture** [stsrki/Blazorise#1578]
The  ColumnSize Attribute in Grid Layout is working differently in .9.1 => .9.2

Using the following markup
```
<Row>  
    <Column ColumnSize="ColumnSize.IsAuto">
        <Image style="width:auto;" source="doesn't matter">
   </Column>
   <Column ColumnSize=ColumSize.IsAuto.WithOffset>
        <div class="float-right">
            HTML Table Content
        </div>
   </Column>
</Row>
```

Using .9.1 the first column took only the space it needed (width of the image) and the second column "auto-filled" the remaining space in the browser window and the div with the float:right put all the content of the second column all the way to the right side of the browser.

Using .9.2 the first column performs the same, but the second column only takes the space it needs, no longer "auto-filling" the remaining browser window.

Is there a way to have the .9.1 behavior in .9.2, such as an "auto-fill" for column 2?

**Comment by stsrki** [comment]
Any way you could show us a html markup generated for both 0.9.1 and 0.9.2 version?

**Comment by CJHCapture** [comment]
Yes...

.9.1
![image](https://user-images.githubusercontent.com/52252947/101209240-6d551a00-3641-11eb-90c2-4a9a4e5976fd.png)


.9.2.3
![image](https://user-images.githubusercontent.com/52252947/101209493-cfae1a80-3641-11eb-9f7f-9ae62fee24eb.png)

**Comment by CJHCapture** [comment]
Any update on this issue?

**Comment by stsrki** [comment]
First, sorry for not answering sooner.

This behavior was intentional after we realized in the latest versions of bootstrap having an extra `col` class name is invalid.

- `col-6` is valid
- `col col-6` is invalid

Now, I'm really not sure what is the right behavior for `offset-auto`. But considering it's a pretty rare use-case I think it's best for you to just define it explicitly. 

**Example**

```diff
<Row>
    <Column ColumnSize="ColumnSize.IsAuto">
        <Alert Color="Color.Success" Visible="true">
            <AlertMessage>Well done!</AlertMessage>
            <AlertDescription>You successfully read this important alert message.</AlertDescription>
        </Alert>
    </Column>
+    <Column ColumnSize="ColumnSize.IsAuto.WithOffset" Class="col">
        <Alert Color="Color.Success" Visible="true">
            <AlertMessage>Well done!</AlertMessage>
            <AlertDescription>You successfully read this important alert message.</AlertDescription>
        </Alert>
    </Column>
</Row>
```

**Comment by CJHCapture** [comment]
Thank you for the response and work-around!
