### ISSUE TITLE
Something wrong with the layout when using the addon with the navbar

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1582]
![image](https://user-images.githubusercontent.com/12803050/101298217-a640ea80-380b-11eb-922a-724dbb0ca931.png)

Buttons within the addon, for some reason, have a z-indez 2, and this causes a failure when you move the page's scroll bar over the navbar

**Comment by stsrki** [comment]
Button `z-indez 2` is from Bootstrap so I would say that is OK.

@MitchellNZ It seems the problem is in `b-layout-header-fixed` being 1

```diff
.b-layout-header-fixed {
    position: sticky;
+    z-index: 1;
    top: 0;
    flex: 0;
}
```

Maybe we can increase it?

**Comment by drma-dev** [comment]
Yes, that is the idea. I also noticed that the footer has the same problem.

I just don't know if there would be another component to worry about.

**Comment by MitchellNZ** [comment]
@stsrki Yeah I think we should just increase it for the `header` and `footer` elements.
I just don't like to go wild with `z-index` values! 
But these elements should always be on top (with the expcetion of the `Modal`).

I will investigate a safe level of `z-index` 👍

**Comment by stsrki** [comment]
@MitchellNZ Thanks. Once you work on it, just make sure the number fits for all providers.
