### ISSUE TITLE
manual NumericEdit input can't be less like 0.01

### ISSUE THREAD

**Issue by MiroslavKabat** [stsrki/Blazorise#1586]
I am not able write float number less like "0.01" in to Numeric Edit.

<NumericEdit TValue="float" @bind-Value="@SomeValue" />

![image](https://user-images.githubusercontent.com/34449536/101472887-77309300-3949-11eb-822e-1a12b17e0aab.png)

**Comment by stsrki** [comment]
Try setting `Decimals` parameter:

`<NumericEdit TValue="float" Decimals="6" />`

**Comment by MiroslavKabat** [comment]
Oh, thank you.
