### ISSUE TITLE
Stacked Bar Chart

### ISSUE THREAD

**Issue by AidasS** [stsrki/Blazorise#159]
Could you please give a short example how to set Stacked Bar chart. As I understand such option is not implemented in SetOptions() and whatever I try to put into OptionsJsonString just blanks out the chart.

**Comment by stsrki** [comment]
I'm not home now so I cannot test it, but here is the example from chartjs docs https://www.chartjs.org/docs/latest/charts/bar.html.

**Comment by stsrki** [comment]
Try this for OptionsJsonString:
`string myStackedOptions  = "{\"scales\": {\"xAxes\": [{\"stacked\": true}],\"yAxes\": [{\"stacked\": true}]}}";`

`<Chart @ref="barChart" OptionsJsonString="@myStackedOptions  " Type="ChartType.Bar" TItem="double" />`

Also you need to add multiple data to datasets:
`barChart.AddDataSet( data1, data2, data, etc. );`

**Comment by AidasS** [comment]
Awsome, works! 
Thank you
