### ISSUE TITLE
Modals visuals are kinda broken

### ISSUE THREAD

**Issue by madks13** [stsrki/Blazorise#1596]
**Describe the bug**
I upgraded my project to .NET 5, and updated Blazorise to 0.9.2.3. Since then : 
 - Dropdown inside the modal stays inside the modal causing visual glitch where there is a scrollbar inside the modal but the drop down menu doesn't move.

**To Reproduce**
1. Create Blazor WASM with Progressive Web App option
2. Add Blazorise nuget
3. Set it up
4. Create a modal with a dropdown and some element for selection

**Expected behavior**
 - The dropdown menu in front of the modal
Edit :
 - At least, the scrolldown bar inside the modal should be able to properly show the full list, if it should not be displayed on top of the modal.

Also please provide a sample code or point us to a minimalistic GitHub repo

[Project Url](https://dev.azure.com/nt-tooling/Crafter/_git/Crafter.UI.Blazor)

**Screenshots**
[Screenshot](https://ibb.co/T03BPkh)

**Additional context**
I tried downloading the libraries manually and even updating them but only got more problems and even code errors

**Comment by stsrki** [comment]
I have investigated this and I think it is working as expected. My guess is you're using `MaxHeight` to limit modal size, which means it will show scrollbars once overflow happens. That is just how Boostrap works. If you want to change it you will need to adjust CSS manually for your project.
