### ISSUE TITLE
ChartModels missing label property

### ISSUE THREAD

**Issue by netclectic** [stsrki/Blazorise#1600]
**Describe the bug**
The LineChartModel and RadarChartModel do not have a Label property. 

**To Reproduce**
Add a LineChart, add an OnClick event handler, cast the model to a LineChartModel - no label property

**Expected behavior**
I would expect the label property for the clicked data point to be available as part of the model

**Comment by stsrki** [comment]
It's easy to add. I will do it for the next milestone. Tnx
