### ISSUE TITLE
DataGrid interferes with NavMenu

### ISSUE THREAD

**Issue by itsLollo1000** [stsrki/Blazorise#1601]
Updating to Preview 9.3.1 and using a DataGrid with a VerticalInline Bar desing make the Navigation Bar glitch.

1. Use any kind of DataGrid with a VerticalInline Bar
2. Open the page containing the Grid
3. Scroll down or close the NavBar and hover on any categorie with a pop up menu.

Expected to only have one scroller and not a second one for the nav menu.
Expected to not see the current page index of the datagrid over the pop up menu.

![image](https://user-images.githubusercontent.com/10349466/101881952-78560000-3b95-11eb-91fb-f5b2345eff46.png)
![image](https://user-images.githubusercontent.com/10349466/101881969-7ee47780-3b95-11eb-842e-b8a4ad9cb0a7.png)
![image](https://user-images.githubusercontent.com/10349466/101881911-696f4d80-3b95-11eb-9812-386d29c6b922.png)

Worked before updating to the preview.

**Comment by stsrki** [comment]
@MitchellNZ can you look into this?

**Comment by itsLollo1000** [comment]
Any news on that?

**Comment by stsrki** [comment]
Working in the latest version.
