### ISSUE TITLE
Autocomplete with some data containing null

### ISSUE THREAD

**Issue by itsLollo1000** [stsrki/Blazorise#1602]
Using the 9.3.1 Autocomplete with TValue and TItem crashes when having a certain amount of data. Typing a search with only 6 items in Data works but having 331 items crashes using the same DataGrid and Autocomplete.

1. Create a gird a custom filtertemplete using autocomplete
2. Fill the same grid with the same data just different amount of data
3. Try any filter

On 9.2 it worked like a charm with "huge" data.

![image](https://user-images.githubusercontent.com/10349466/101882629-70e32680-3b96-11eb-9958-63550a0d8ef8.png)
![image](https://user-images.githubusercontent.com/10349466/101882656-7a6c8e80-3b96-11eb-9827-a409084b902d.png)
![image](https://user-images.githubusercontent.com/10349466/101882680-80fb0600-3b96-11eb-970c-c733358c9e2d.png)

**Comment by stsrki** [comment]
Can you provide us with a sample project to reproduce the issue?

Also, are you using latest **0.9.3-preview3.1**?

**Comment by itsLollo1000** [comment]
Yes I am using the latest preview 3.1.

Unfortunately this it not possible since it has confidential data. But let me have a look into this if it is possibel for me to create a sample projec with the same error.

**Comment by stsrki** [comment]
I'm aware you can't post a real project. We just need a small fully working project with the error to reproduce.

**Comment by itsLollo1000** [comment]
Yes I am doing that right now.

**Comment by itsLollo1000** [comment]
Interseting it was the TItem which was faulty. Using a inherted class for the TItem in the Autocomplete did not work but for the GridColumn it does.
Strange.

**Comment by itsLollo1000** [comment]
Edit: this did only fix it for my first column

**Comment by itsLollo1000** [comment]
Can it be because not every item in the grid has a value in the description?

**Comment by itsLollo1000** [comment]
Can be fixed by changing this:
`                          TextField="@((item)=>item.Name.ToString())"
                          ValueField="@((item)=>item.Name)"`
to this
`                          TextField="@((item)=>item.Name.ToString() ?? "")"
                          ValueField="@((item)=>item.Name ?? "")"`
