### ISSUE TITLE
Table attributes Responsive not working

### ISSUE THREAD

**Issue by abelvalle** [stsrki/Blazorise#1603]
**Describe the bug**
Hi, I tried the table component with the attribute `Responsive='true'` in my project and it doesn't work.

**To Reproduce**
I have used the example code from the Blazorise project, more specifically the code found in [TablesPage.razor](https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/TablesPage.razor) . 

From line 504 to the last line. 
That's where you can find the example table with the Responsive attribute.

**Expected behavior**
I expected that having many columns would show a horizontal scroll in the table as you can see in the example.

**Screenshots**
![table-responsive-bug](https://user-images.githubusercontent.com/26121474/101891229-0cc65f80-3ba2-11eb-95aa-a0ce7ef972b1.gif)

**Additional context**

I have Blazorise running locally and it does work for me, but in my new project it doesn't. 

Am I doing something wrong?

**Comment by abelvalle** [comment]
it has happened to nobody else

**Comment by stsrki** [comment]
Maybe you forgot to include some CSS files in your second project? Check that you have all Blazorise static files in index.html or _Host.cshtml.

**Comment by abelvalle** [comment]
Hi I have checked my _Host.cshtml settings and gone through it and it seems I have fixed it.

Thanks a lot.
