### ISSUE TITLE
Set colors  for LayoutSider/SiderItem when item is active

### ISSUE THREAD

**Issue by jinghua395** [stsrki/Blazorise#1606]
Hi,

I have a feature request to LayoutSider.

I would like to be able to set the background-color and color when BarItem is Active/Clicked, instead of hardedcoded blue color, to fit the theme completely.

Thanks!

**Comment by stsrki** [comment]
LayoutSider is used to structure your app layout. It's not supposed to be styled, at least not directly. You can always use CSS and adjust it for your use case.

**Comment by jinghua395** [comment]
Thanks for the reply, I am totally agree with you about LayoutSider.

I should rephrase my request:
I would like to set the background-color and color in BarItems when it is become Active(the url match To link).

I am able to set BackgroundColor and Color in Bar component to fit my theme, that's perfect.
However when I clicked the BarLink in one of the BarItems, The "problem" is, I cannot set the BackgroundColor and Color of the BarLink, it seems always the same color regardless the theme primary/secondary color is.

I looked the in browser debug tool, the background color is set in .b-bar-vertical-inline.b-bar-dark .b-bar-link.active, with background: var(--b-bar-item-dark-active-background, #0288D1); 

E.g., if I set the theme color as red, I would like set BackgroundColor to be the same, and Color be white.
![capture](https://user-images.githubusercontent.com/4208171/102064921-2d87f280-3df8-11eb-813d-baf2f957a3e2.PNG)

Do you see a way to do it?

**Comment by stsrki** [comment]
Try this

![image](https://user-images.githubusercontent.com/900302/102076277-ca05c100-3e07-11eb-9034-d79edc8d2d56.png)

**Comment by jinghua395** [comment]
Hi,

It is exactly what I was looking for, sorry i missed in the first place.

I tried it, however, I got an error when my webassembly project started up,

![Capture](https://user-images.githubusercontent.com/4208171/102082886-04c12680-3e13-11eb-90f8-f1d550d136c4.PNG)

I also put the same config in your demo project, same error, by using below


    private Theme theme = new Theme
    {
        BarOptions = new ThemeBarOptions
        {
            HorizontalHeight = "64px",
            LightColors = new ThemeBarColorOptions
            {
                ItemColorOptions = new ThemeBarItemColorOptions
                {
                    ActiveBackgroundColor = "#ff0000",
                }
            }
        }
    };

**Comment by stsrki** [comment]
It might be expecting all properties defined in `ItemColorOptions`. Just set every property in it, and see if it works. I might do a null check for the future versions so it doesn't break.

**Comment by stsrki** [comment]
It needs this two:

```diff
private Theme theme = new Theme
{
    BarOptions = new ThemeBarOptions
    {
        HorizontalHeight = "64px",
        DarkColors = new ThemeBarColorOptions
        {
+            BackgroundColor = "#ff0000",
+            Color = "#ff0000",
            ItemColorOptions = new ThemeBarItemColorOptions
            {
                ActiveBackgroundColor = "#ff0000",
                ActiveColor = "#ff0000",
                HoverBackgroundColor = "#ff0000",
                HoverColor = "#ff0000",
            }
        },
    },
}
```

I agree, it's a bug and it needs to have better error handling.

**Comment by jinghua395** [comment]
Thanks for the quick reply, yes, setting these two props made it works, thanks a lot.

And thanks for identify the potential bug, if we are creating bug, I would also like to create bug report
It is a minor error from my personal usage.

The Clicked call in `BarLink` (under `BarItem`) does not work, it does not invoke the my method.

**Comment by stsrki** [comment]
Just open separate ticket for new issues.

Regarding the Clicked event. You probably have `To` defined and click event is only used when `To` is not set.

**Comment by jinghua395** [comment]
Yes, thanks for the hint, I will try and test.

Just did a complete test on `BarOptions`, it seems the below three props are not working anyways.
![Capture](https://user-images.githubusercontent.com/4208171/102087302-a0ee2c00-3e19-11eb-9839-4bd6490ecea8.PNG)

But I can work with it for now, thanks!

**Comment by jinghua395** [comment]
This is identified as a Bug.
