### ISSUE TITLE
Column Aggregate.Average on Average values

### ISSUE THREAD

**Issue by jbennink** [stsrki/Blazorise#1608]
**Is your feature request related to a problem? Please describe.**
On dashboards I regularly display average callduration per Agent. This is cacluated by taking the sum of all calldurations for the Agent and divide by the number of calls made by the agent. Then on the summary Aggregate I display the average over alle agent rows giving me the average "campaign" callduration. 
The current DataGridAggregateType.Average calculates the average of the column value divided by the number of rows (values) in the grid. However since my column values are already an average you *cannot* calculate the summary aggregate in this way. or you would end up with a weighted average.

In this example check the two highlighted column which contain Sum of callduration and number of calls.
![msedge_2020-12-14_16-15-28](https://user-images.githubusercontent.com/49071903/102098716-d3068a80-3e27-11eb-8bc9-cfc1551424cf.png)
Here the total for today is 10.02.21:46 over 12517 calls with an average Live callduration of 01:10 (one minute 10 seconds). 
This is an example of the average aggregate column for the Live Callduration / Calls, which says 1:20 which is too high due to the weighted average. My display template refers to a field in my model "AverageLiveSS" that used the Model fields LiveSS and Calls to calculate the Average callduration for this Agent (row). 
![msedge_2020-12-14_16-16-26](https://user-images.githubusercontent.com/49071903/102098726-d6017b00-3e27-11eb-9c51-407740e264d5.png) 

**Describe the solution you'd like**
On custom reports , and Excel you would calculate the average callduration with a formula = (callduration / calls) for the respoective columns. And the summary aggregate would simply divide th summary sum values for those same columns instead of summarising over the actuale column values.

I think this is not an easy fix but, in fact I don't really know how to fix this but I want it :-) 
If I could somehow keep track of a cumulative sum I could calulate both sum values and have the average for the summary row calculated on those values in much the same way as you would do in Excel.

**Comment by stsrki** [comment]
One way would be to use `DisplayTemplate` in `DataGridAggregate` and calculate whatever you need.

The other way could be to introduce a **custom** function for aggregates. Something like

`<DataGridAggregate TItem="Employee" Field="@nameof( Employee.Salary )" Aggregate="DataGridAggregateType.Custom" Function="@MyCustomFunction" />`. 

It's just an idea out of my head now.

**Comment by jbennink** [comment]
@stsrki But in the `DisplayTemplate` context is of type `AggregateContext` Even if you could use the `TItem` type that would not give you an object that has access to the values I would need! In the Aggregate column I would need access to the Cumulative sum of (in my case) the Live callduration and the number of calls. My `TItem` has a value "LiveSS" Live call duration in seconds and has a value "Calls" with the number of calls. But in the Aggregate column you need the Sum of these columns.

Also the Custom function route seems interesting as well but Again, how would this cust omfunction access the data. Would I have to calculate ths aggregates on the "RAW" data myselve?

Since there already is an `DataGridAggregates` type would it be possible to let each DataGridAggregate receive a dynamic row that contains alle aggregate columns (not sure how to do this) but:

Instead of the context being of type "AggregateContext" make this context contain all aggregate columns that have been defined. That way if I have an aggregate on the Live call duration and on the number of calls (usually you would) I could calculate the Average by dividing the two.
I do feel you Customfunction comes close to my brainstorm even though I have not look at the source of the DataGridAggregates. Will try to look at the source to see how I could try to implement my "feature"

**Comment by stsrki** [comment]
With the `CustomFunction` you would get the `Item` and you can then calculate the value with whatever formula you want. You just need to return a result.

With `DisplayTemplate`, you can show any value or content. If you want you can directly use your data-source and calculate the value from there.

**Comment by stsrki** [comment]
Done with https://github.com/stsrki/Blazorise/pull/2162
