### ISSUE TITLE
Cascading

### ISSUE THREAD

**Issue by padnom** [stsrki/Blazorise#1616]
Hello,
Thx for your work it's awesome.

I try to implemant a another DetailRowTemplate into an DetailRowTemplate.
Look like i have some issue with context.
Does it's possible ?

Thx

**Comment by stsrki** [comment]
Not sure if I understood correctly. Can you give more information and maybe a small usage sample so that we can know what you want to accomplish?

**Comment by padnom** [comment]
Of course,


 <DataGrid TItem="RgddPeriodesAppel"
                      Data="@appels"
                      @bind-SelectedRow="@selectedAppel"
                      Striped="false"
                      Bordered="false"
                      Hoverable="true"
                      Responsive="true"
                      Sortable="true"
                      Filterable="true"
                      ShowPager="true"
                      DetailRowTrigger="@((item)=> item.PeriodeDirect == selectedAppel?.PeriodeDirect)"
                      RowStyling="@OnRowStyling"
                      SelectedRowStyling="@OnSelectedRowStyling"
                      PageSize="15">
                <DataGridColumns>
                    <DataGridCommandColumn TItem="RgddPeriodesAppel" />
                    <DataGridColumn TItem="RgddPeriodesAppel" Field="@nameof(RgddPeriodesAppel.PeriodeDirect)" Caption="#" Sortable="false" />
                    <DataGridColumn TItem="RgddPeriodesAppel" Field="@nameof(RgddPeriodesAppel.LibelleTypeAppel)" Caption="Relevé général des dépenses" Sortable="false" />
                    <DataGridColumn TItem="RgddPeriodesAppel" Field="@nameof(RgddPeriodesAppel.DateDebut)" Caption="Date de début" Editable="false">
                        <DisplayTemplate>
                            @{
                                var date = (context as RgddPeriodesAppel)?.DateDebut;

                                if (date != null)
                                {
                                    @($"{date.Value.ToString("d")}")
                                }
                            }
                        </DisplayTemplate>
                    </DataGridColumn>
                    <DataGridColumn TItem="RgddPeriodesAppel" Field="@nameof(RgddPeriodesAppel.DateFin)" Caption="Date de fin" Editable="false">
                        <DisplayTemplate>
                            @{
                                var date = (context as RgddPeriodesAppel)?.DateFin;

                                if (date != null)
                                {
                                    @($"{date.Value.ToString("d")}")
                                }
                            }
                        </DisplayTemplate>
                    </DataGridColumn>
                </DataGridColumns>
                <DetailRowTemplate>
                    @{

                        <DataGrid TItem="RgddLigneDepenseViewModel"
                                  Data="@details"
                                  @bind-SelectedRow="@selectedImmeuble"
                                  Striped="true"
                                  Bordered="true"
                                  Hoverable="true"
                                  Responsive="true"
                                  Sortable="true"
                                  ReadData="@GetDetailsAsync"
                                  DetailRowTrigger="@((item)=> item.NumBatiment == selectedImmeuble?.NumBatiment && item.NumRubrique==selectedImmeuble.NumRubrique)">
                            <DataGridColumns>
                                <DataGridCommandColumn TItem="RgddLigneDepenseViewModel" />
                                <DataGridColumn TItem="RgddLigneDepenseViewModel" Field="@nameof(RgddLigneDepenseViewModel.LibelleBatiment)" Caption="Batiment" />
                                <DataGridColumn TItem="RgddLigneDepenseViewModel" Field="@nameof(RgddLigneDepenseViewModel.Rubrique)" Caption="Rubrique" />
                            </DataGridColumns>
                            <DetailRowTemplate Context="contextRgddLigne">
                                @{

                                    <DataGrid TItem="RgddLigneDepense"
                                              Data="lignes"
                                              @bind-SelectedRow="@selectedRgdd"
                                              ReadData="@GetRgdds"
                                              Striped="true"
                                              Bordered="true"
                                              Hoverable="true"
                                              Responsive="true"
                                              PageSize="15"
                                              Sortable="true"
                                              DetailRowTrigger="@((item)=> item.NumBatiment == selectedImmeuble.NumBatiment)">
                                        <DataGridColumns>
                                            <DataGridColumn TItem="RgddLigneDepense" Field="@nameof(RgddLigneDepense.Libelle)" Caption="Libellé" />
                                            <DataGridColumn TItem="RgddLigneDepense" Field="@nameof(RgddLigneDepense.Reference)" Caption="Référence" />
                                            <DataGridColumn TItem="RgddLigneDepense" Field="@nameof(RgddLigneDepense.MontantARepartir)" Caption="A répartir" />
                                            <DataGridColumn TItem="RgddLigneDepense" Field="@nameof(RgddLigneDepense.NomFournisseur)" Caption="Fournisseur" />
                                            <DataGridColumn TItem="RgddLigneDepense" Field="@nameof(RgddLigneDepense.GedParam)" Caption="Fichier">
                                                <DisplayTemplate Context="contexteLigneDetails">
                                                    <Button Clicked="OnDocumentClick">Test</Button>
                                                </DisplayTemplate>
                                            </DataGridColumn>
                                        </DataGridColumns>
                                    </DataGrid>
                                }
                            </DetailRowTemplate>
                        </DataGrid>
                    }
                </DetailRowTemplate>
            </DataGrid>

**Comment by stsrki** [comment]
I see it now. The `context` cannot be determined because you use it inside of another with the same name. The solution is simple. Just give it a different name.

**Example**

`<DetailRowTemplate Context="YourContextName">`

**Comment by padnom** [comment]
Thank you very much...
I need to better understand the use of context.
So for each DetailRowTemplate  in need to set a different context.

**Comment by stsrki** [comment]
It's a Blazor convention, to have it named `context` by default. You only need to rename it if you have nested templates or if it makes sense for your use case.
