### ISSUE TITLE
Using Bar (vertical), first render as Visible = false

### ISSUE THREAD

**Issue by sks-ttaylor** [stsrki/Blazorise#1617]
When my component first renders, I would like to have the vertical bar visible = false. Then let the BarToggler control Visibility.

Is this possible?

**Comment by stsrki** [comment]
It seems this is a bug. Setting `Visible="false"` should work, but it's not.

@MitchellNZ Can I assign this to you?

**Comment by MitchellNZ** [comment]
@stsrki Yup!

I have was having quite a lot of trouble with this originally (which mostly seemed due to the old rendering before `IComponentActivator`).

So I will take another look at fixing this in the latest version!
