### ISSUE TITLE
Snackbar not closing (Server-side)

### ISSUE THREAD

**Issue by banicg** [stsrki/Blazorise#162]
When a snackbar is shown on server-side Blazor, it does not close after the timer interval elapsed. Some unrelated UI actions will eventually cause the snackbar to close.

**Comment by stsrki** [comment]
Thanks for report, I will investigate.

**Comment by banicg** [comment]
I got the answer... 

    private void Timer_Elapsed(object sender, ElapsedEventArgs e)
    {
        InvokeAsync(() => {
            Hide();
        });
    }

This article is referenced: [https://stackoverflow.com/questions/54496040/is-it-safe-to-call-statehaschanged-from-an-arbitrary-thread](https://stackoverflow.com/questions/54496040/is-it-safe-to-call-statehaschanged-from-an-arbitrary-thread)

**Comment by stsrki** [comment]
@banicg Thank you for the effort to find the solution. The bug is now fixed and merged.
