### ISSUE TITLE
Getting DI issues with adding Font Awesome icons

### ISSUE THREAD

**Issue by daveabrock** [stsrki/Blazorise#1631]
Hello. In my Blazor WASM app, I'm trying to work with font awesome icons. As the documentation states, I added this to my app's `Program.cs` (and also added the files to my `index.html`:

```csharp
builder.Services.AddBlazorise().AddFontAwesomeIcons();
```

I'm getting issues with needing to inject `ComponentMapper`.

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'ComponentMapper' on type 'Blazorise.Icon'. There is no registered service of type 'Blazorise.IComponentMapper'.
```

When I manually add that, it clears up but asks me to inject another service. Do I need to keep manually injecting service dependencies, or am I doing something wrong?

**Comment by stsrki** [comment]
I would guess you're using 0.9.2 version?

If that is the case you also need to include `.Use` methods

Example from https://blazorise.com/docs/usage/bootstrap/#4a-blazor-webassembly

```
host.Services
      .UseBootstrapProviders()
      .UseFontAwesomeIcons();
```

**Comment by stsrki** [comment]
PS. I noticed you also didn't use `.AddBootstrapProviders()` in your example.

**Comment by daveabrock** [comment]
I'm on `0.9.2.4`. I have this line in `Program.cs`:

```csharp
builder.Services.AddBlazorise().AddFontAwesomeIcons();
```

When I try to invoke `UseBootstrapProviders`, I get an error saying it doesn't exist. Do you support .NET 5?

**Comment by stsrki** [comment]
@daveabrock 

0.9.2.x supports both .Net 5 and .Net 3.1.x. 

Starting with 0.9.3 we only support .Net 5 and because of that, `UseBootstrapProviders` and all `.UseXXX` are removed.

**Comment by bestpika** [comment]
@stsrki Can you please add a comment to "README.md"? I updated to 0.9.3 and found that I couldn't compile it, so I found this paragraph after a long time.

**Comment by stsrki** [comment]
@bestpika README.md and documentation will be updated once we release an official 0.9.3. Until then, the documentation should mention only the official 0.9.2.x.
