### ISSUE TITLE
Slider: Support for Timespan

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [stsrki/Blazorise#1636]
I want to use the Slider Component for a replacement for a seekbar for audio playback in blazor. Since in audio playback you normally work with timespans (position, max), I tried using Slider with TValue="Timespan", but this doesn't work, only saying: 
"Unsupported type Timespan".

**Comment by stsrki** [comment]
You can use ValueChanged and convert the value to TimeSpan

**Example**

```cshtml
<Slider TValue="decimal" Value="@sliderValue" ValueChanged="@OnSliderValueChanged"  />
@code{
    decomal sliderValue;

    Task OnSliderValueChanged(decimal value)
    {
        sliderValue = value;

        yourTimeSpan = TimeSpan.FromSeconds(sliderValue); // something like this

        return Task.CompletedTask;
    }
}
```

**Comment by NeoCoderMatrix86** [comment]
Thanks for your help. I will currently use this workaround. But why not add a support for Timespans?

**Comment by stsrki** [comment]
TimeSpan goes more into the complex type territory and is too specific so it would complicate stuff. And since you can do almost everything with simple types,(int, short, double, etc.), there is no need to add TimeSpan support.

**Comment by NeoCoderMatrix86** [comment]
Ok, thanks for your support :). I will use the suggested workaround :)!
