### ISSUE TITLE
Class-less version?

### ISSUE THREAD

**Issue by marcusjm** [stsrki/Blazorise#1637]
Wondering since we talked about tailwind. How about a version where you have no defined classes but have to add them yourself. Blazorize Vanilla :).

I mean isn't that what you get without adding any of the supported libs?

**Comment by stsrki** [comment]
You can already do that. Inherit from `IClassProvider` and write all your class-names manually, and the register class provider within DI.

Or just use `EmptyClassProvider`, which basically returns `null` for all classnames.

**Comment by marcusjm** [comment]
Aha but can I choose none instead of bootstrap as the base theme when using nuget also?

**Comment by stsrki** [comment]
That ia what EmptyClassProvider is used for. But in that case you will have no styles at all.

**Comment by marcusjm** [comment]
Which is basically what you need for tailwind.

**Comment by stsrki** [comment]
Not sure if we're on the same track. Yes, you can have _vanilla_ Blazorise, without any providers included. Yes you can override `IClassProvider` and then go through the long process of implementing all of the tailwind classes. But, classes are just one side of a coin. You also need to override some of the components in case they have a different structure for the DOM elements.

Also, the problem with tailwind is that it's a utility-first CSS framework. This means you will have to combine MANY different classes to build even a simple components, like a button. You don't have just `btn` class, You have `w-1/2 flex items-center justify-center rounded-md bg-black text-white`. It's a lot :)
