### ISSUE TITLE
BUG: in 0.9.2.4: System.ArgumentNullException: Value cannot be null. (Parameter 'element')

### ISSUE THREAD

**Issue by RobertChanphakeo** [stsrki/Blazorise#1644]
Blazorise: 0.9.2.4
.NET 5.0

**How to reproduce error**
Upgrade from 0.9.1.2 to 0.9.2.4

**Solution:** 
Downgrade from 0.9.2.4 (latest) to 0.9.1.2 

------------------------------------
![image](https://user-images.githubusercontent.com/1288153/103153328-f0523600-47e3-11eb-9970-bfaa09300eec.png)

**Error**
---------------
[23:02:02 WRN] Unhandled exception rendering component: Value cannot be null. (Parameter 'element')
System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at Blazorise.Utils.ValidationAttributeHelper.GetValidationAttributes(PropertyInfo propertyInfo)
   at Blazorise.EditContextValidator.TryGetValidatableProperty(FieldIdentifier& fieldIdentifier, ValidationPropertyInfo& validationPropertyInfo, Boolean forLocalization)
   at Blazorise.EditContextValidator.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier& fieldIdentifier, Func`3 messageLocalizer)
   at Blazorise.Validation.ValidateUsingDataAnnotation(Object newValidationValue)
   at Blazorise.Validation.Validate(Object newValidationValue)
   at Blazorise.Validation.OnValidatingAll(ValidatingAllEventArgs e)
   at Blazorise.Validations.TryValidateAll()
   at Blazorise.Validations.ValidateAll()
   at ......Test.OnSubmitAsync() in .....Test.razor:line 66
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.Button.ClickHandler()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
[23:02:02 INF] Session started; Key:2af0174b-1b61-f6b3-f352-0b57f3033c03, Id:265e6e47-a84f-984d-8dc9-591bba47a17c
 

----------------

**Code**
(Removed all code except for the specific code that caused the exception error)

```
@page "/test"
@using PlatformModels.Accounts

<Validations @ref="_validations" Mode="ValidationMode.Auto" ValidateOnLoad="false" Model="@_updateAccountRequestRec">
    <Validation>
        <TextEdit @bind-Text="_dateOfBirth">
        </TextEdit>
    </Validation>
</Validations>
<Button Color="Color.Info" Float="Float.Right" Clicked="OnSubmitAsync">Submit</Button>

@code{
    private Validations _validations;

    private UpdateAccountRequest _updateAccountRequestRec = new UpdateAccountRequest();
  
    private string _dateOfBirth = string.Empty;

    private async Task OnSubmitAsync()
    {

        if (_validations.ValidateAll()) //error occurs here
        {

        }

    }

}

```

**Comment by RobertChanphakeo** [comment]
Inspecting "_validations" it was found that there are 16 items in Blazorise.Validation, and two items are null, but im unable to determine which item is null.

Note: this app was working before but something changed in blazorise?

**Comment by RobertChanphakeo** [comment]
If I leave only "Date of Birth" field on the form, an exception error occurs.

when I debug it, it show null validations, is that normal?

![image](https://user-images.githubusercontent.com/1288153/103163032-7efa9d80-484c-11eb-9ff2-071abee85660.png)

**Comment by RobertChanphakeo** [comment]
@stsrki Source code (with error)
[BlazoriseWebApp.zip](https://github.com/stsrki/Blazorise/files/5744073/BlazoriseWebApp.zip)

**Comment by RobertChanphakeo** [comment]
@stsrki I downgraded from blazorise 0.9.2.4 (latest) to blazorise 0.9.1.2 (the issue went away, same code)

Blazorise 0.9.2.4 (error occurs in this version)
[BlazoriseWebApp-0.9.2.4.zip](https://github.com/stsrki/Blazorise/files/5744086/BlazoriseWebApp-0.9.2.4.zip)

Blazorise 0.9.1.2 (no error)
[BlazoriseWebApp-0.9.1.2.zip](https://github.com/stsrki/Blazorise/files/5744087/BlazoriseWebApp-0.9.1.2.zip)

**Comment by stsrki** [comment]
It's probably something that I recently did in the patch. Going on the list.

**Comment by RobertChanphakeo** [comment]
Btw has any style tags changed from 9.1.2 onwards? There are some issues with styles after upgrading aswell.

**Comment by stsrki** [comment]
I just realized you're talking about moving from 0.9.**1** to 0.9.2. My brain somehow converted that into 0.9.**2.1** 😅

Yeah, there was a lot of changes between 0.9.1 and 0.9.2, it's hard to tell what changed. https://github.com/stsrki/Blazorise/issues/1024

**Comment by RobertChanphakeo** [comment]
Do you know which specific changes caused this bug? How would you know this specific issue has been resolved, via a merge, (there were so many changes was made)?

**Comment by stsrki** [comment]
No way to tell at this point. Validations and input fields also had a major rewrite. Once I test and debug your example I will see what is actually wrong.

**Comment by stsrki** [comment]
I found your problem. You're working with data-annotations validation but you're trying to validate private member instead of a field inside of you model.

**Instead of**

 `<TextEdit @bind-Text="_dateOfBirth">`

**it should be**

`<TextEdit @bind-Text="_updateAccountRequestRec.DateOfBirth">`

**Comment by RobertChanphakeo** [comment]
As you can see from the source code provided, it works in 0.9.1.2 but fails in 0.9.2.4

Note:
1. there is no data annotation validation for "UpdateAccountRequest.Individual.DateOfBirth"
2. DateOfBirth data type is "DateTime" rather than a string , hence the reason to use _dateOfBirth input string, once the user's input is assigned it is then validated, if the string is valid it is then converted to a DateTime value and assigned to "UpdateAccountRequest.Individual.DateOfBirth"

Download model source code via https://1drv.ms/u/s!AtQl8eIX84DQgP4CZ-iHxxLkDbFtpw?e=HqcCPd

**Comment by stsrki** [comment]
The thing is that as soon as you apply `Model` on `Validations`, it will go into the data-annotations mode so it expects to find the binded field on the model. 

And that is what you have on your example

`<Validations @ref="_validations" Mode="ValidationMode.Auto" ValidateOnLoad="false" Model="@_updateAccountRequestRec">`

The older code in **0.9.1.x** was more _forgiving_ so that's the reason why it worked before.

**Comment by stsrki** [comment]
OK I made some more testings and you can make it work by making `_dateOfBirth`  a public property.

`public string _dateOfBirth { get; set; } = string.Empty;`

**Comment by RobertChanphakeo** [comment]
I can confirm this works "public string _dateOfBirth { get; set; } = string.Empty;"
Would this be a temporary workaround? Will it break in the future? (i.e _dateOfBirth property is not apart of the validation model itself but had to do this since DateTime is not supported)

Will there  be support for other data type such as DateTime, Guid?

**Comment by stsrki** [comment]
What do you mean? As far as I know, all types are supported by data-annotations. In case something is not supported you can always implement your own `ValidationAttribute`.

In your case for `DateTime` you can use `DateEdit` component.

**Comment by RobertChanphakeo** [comment]
There is a reason why the DateEdit component was not used, initially I believe in version 0.8 ? I experienced issues with this DateEdit component, when I click on the input field the date picker would open and then close, there was no way I could manually input the date or select the date from the data picker. I tested the latest version and it still has exactly the same issue - if the issue was fixed I would use it.

**Comment by stsrki** [comment]
You're using a material provider? In that case you have the option of moving to [djibe](https://github.com/djibe/material) version instead of now abandoned [daemonite](https://github.com/Daemonite/material) Material CSS. In djibe version, the problem with datepicker was fixed since the problem was in their javascript.

**Comment by RobertChanphakeo** [comment]
I tried it, replacing daemonite material css with djibe material, datepicker issue went away, however the date picker component UX isn't great for date of birth, you can't skip years. Is there another library?

**Comment by stsrki** [comment]
I can add an option to select year and month if needed

![image](https://user-images.githubusercontent.com/900302/103226481-84c7b000-492c-11eb-9e2e-397478ad36f2.png)

**Comment by RobertChanphakeo** [comment]
Yes

But it would be better to make the ux work like bootstrap date picker, 
1. Input Mask for date
2. Date picker icon on right side (this brings up the date picker window dialogue, which also has month and year dropdown combo as shown above)

**Comment by stsrki** [comment]
Well, it turns out djibe has a new DatePicker that is similar to what you describe https://djibe.github.io/material/docs/4.5/plugins/picker-flatpickr/

**Comment by RobertChanphakeo** [comment]
I mean work like this, mask + date picker https://1drv.ms/v/s!AtQl8eIX84DQgP8S5XLpE-OfJccn2g?e=mKrXYM

**Comment by stsrki** [comment]
Going to close this original report had private field instead of public property. Simple change to:

```cs
[Required]
public string _dateOfBirth { get; set; } = string.Empty;
```

made it work as expected.

Note, however, I tested on 0.9.3 only since I plan to release it soon.

**Comment by RobertChanphakeo** [comment]
> Going to close this original report had private field instead of public property. Simple change to:
> 
> ```cs
> [Required]
> public string _dateOfBirth { get; set; } = string.Empty;
> ```
> 
> made it work as expected.
> 
> Note, however, I tested on 0.9.3 only since I plan to release it soon.

Great, thank you!
