### ISSUE TITLE
Bar component dynamic generation

### ISSUE THREAD

**Issue by athrayee** [stsrki/Blazorise#1645]
Hi,
Appreciate your work with Blazorise. I am using it to do some evaluation and was looking to use bar component, I am wondering if bar component can be dynamically generated based on a json or through code. I see in documentation sidebar extension provides that capability but looks like you have bar component added recently which supercedes sidebar. Could you please provide your input

**Comment by stsrki** [comment]
I believe @MitchellNZ already has dynamic Bar generation in mind. In any case, it's not that difficult to do it on your side as a workaround. It's just a basic `for` loop that does all the work :)

**Comment by athrayee** [comment]
I thought so and thanks for confirming.

 I'll update with my implementation and experience so could provide some thought for the implementation

**Comment by MitchellNZ** [comment]
Related to #1304

**Comment by stsrki** [comment]
Closing since @MitchellNZ already has it on schedule.
