### ISSUE TITLE
Modal dialog in WebAssembly using .Net 5 throws an exception when opened

### ISSUE THREAD

**Issue by rperazzolli** [stsrki/Blazorise#1647]
I'm migrating a web page from Blazor Server with .Net 3.1 to Blazor WebAssembly with .Net 5.
When opening a dialog, the following message appears:

System.ArgumentException: There is not loaded assembly with the name 'TableroPecasV5' at Microsoft.JSInterop.Infraestructure.DotNetDispatcher.GetRequiredLoadedAssembly(AssemblyKey assemblyKey) at ....

I guess the assembly name should be TableroPecasV5.Client, but I don't know if there's any way to set it.

The same message is displayed when opening a menu or editing the contents of the dialog components.

**Comment by stsrki** [comment]
You probably dont have `Sdk="Microsoft.NET.Sdk.BlazorWebAssembly"` in your WebAssembly csproj file.

Also check our demo projects for reference to see what else you might be missing https://github.com/stsrki/Blazorise/tree/master/Demos

**Comment by stsrki** [comment]
@rperazzolli Did you manage to fix it?

**Comment by rperazzolli** [comment]
I checked the project and the first line is <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">.
On the other hand, I have downloaded the test project, added a modal dialog and it worked properly.
I have to investigate what difference exists between both projects. 
Thanks a lot.

**Comment by rperazzolli** [comment]
The first line is Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly".

**Comment by stsrki** [comment]
Any progress? Can I close this?

**Comment by rperazzolli** [comment]
Yes, you can close it. I forgot the issue, sorry. It was all my fault. Blazor is working properly.
