### ISSUE TITLE
DataGrid pager combo box doesn't have a binded event

### ISSUE THREAD

**Issue by lrequena** [stsrki/Blazorise#1650]
Hi! Doesn't this combo box lacks the event to actually refresh the selected page on it?
I'm changing the page but nothing happens.

https://github.com/stsrki/Blazorise/blob/4afffb790d50e9902af54571833ffc1d7a06596a/Source/Extensions/Blazorise.DataGrid/_DataGridPagination.razor#L42-L50

Thanks in advance!

**Comment by stsrki** [comment]
No this is OK. The actual event is raised in the property

![image](https://user-images.githubusercontent.com/900302/103273535-d1a89680-49bf-11eb-8d77-31fe468b38af.png)
