### ISSUE TITLE
Divider does not use DividerType specified on component

### ISSUE THREAD

**Issue by gwgrubbs** [stsrki/Blazorise#1653]
**Describe the bug**
When the divider component is used with a specified divider type, the divider renders with the theme divider setting or the default solid line.

**To Reproduce**
Given the following component markup:
```c#
<Divider Type="DividerType.Dotted" />
<Divider Type="DividerType.Dashed" />
```
The divider(s) will render with the type specified in a configured theme, or as a solid line.  If there is no theme setting for the divider, they always render as solid lines.

**Expected behavior**
The component specified divider type will be honored, regardless of the theme setting.

**Additional context**
Dividers render with the correct styles if a style is applied with a theme:
```c#
 DividerOptions = new ThemeDividerOptions { DividerType = DividerType.Dotted }
```
This will render all dividers as expected.

**Comment by stsrki** [comment]
Sorry for not getting it sooner. I just tested and it's working. But, you have a typo. It should be `DividerType` instead if `Type`.

```cshtml
<Divider DividerType="DividerType.Dotted" />
<Divider DividerType="DividerType.Dashed" />
```

This was also wrongly explained in the docs and that is also fixed now.
