### ISSUE TITLE
Modal Property Centered="true" does not work

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [stsrki/Blazorise#1654]
Modal Property Centered is set to "true" but the modal is clearly in the left top corner.

Sample Code used:

```
<Modal @ref="modalTextImport">
    <ModalBackdrop />
    <ModalContent Centered="true" Size="ModalSize.ExtraLarge">
        <ModalHeader>
            <ModalTitle>
                @localizer["TextImportAssistance"]
            </ModalTitle>
            <CloseButton @onclick="TextImportAbortClicked"><span aria-hidden="true">&times;</span></CloseButton>
        </ModalHeader>
        <ModalBody>
....

```

Result is:
![grafik](https://user-images.githubusercontent.com/40752681/103354847-f2024f00-4aac-11eb-9970-a056fd637eec.png

**Comment by stsrki** [comment]
This usually happens when you have some custom CSS overriding the default bootstrap styles. Can you inspect element styles in dev tools?

**Comment by NeoCoderMatrix86** [comment]
Where should I have a look? The generated HTML is this:

<app><!--!--><!--!--><!--!--><!--!--><!--!--><section id="0HM5CP60808CH" class="b-layout b-layout-root" _bl_2=""><!--!--><!--!--><header class="b-layout-header"><!--!--><!--!--><!--!--><nav class="navbar bg-primary navbar-light b-bar-light b-bar-horizontal" data-broken="false"><!--!--><div class="navbar-brand"><!--!--><!--!--><a href="/" class="active nav-link"><!--!--><span style="color:white;"><svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"></path>
                            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"></path></svg>
                        AudioCuesheetEditor
                    </span></a></div><!--!-->
            <!--!--><!--!--><!--!--><div class="nav-item"><span style="color:white;"><!--!-->Kultureinstellung:<!--!-->

<select class="form-control ml-1" style="width:150px; display:inherit;"><option value="en-US">en (US)</option><option value="de-DE">de (DE)</option></select></span></div><!--!-->
            <!--!--><!--!--><!--!--><div class="nav-item"><!--!--><a href="about" style="color:white;" class="ml-md-auto">About</a></div></nav></header><!--!-->
    <!--!--><main class="b-layout-content"><!--!--><!--!--><section id="0HM5CP60808CI" class="b-layout" _bl_3=""><!--!--><!--!--><header class="b-layout-header b-layout-header-fixed"><!--!--><!--!--><!--!--><nav class="navbar bg-dark navbar-light b-bar-light b-bar-horizontal" data-broken="false"><!--!--><!--!--><!--!--><div class="nav-item"><!--!--><!--!--><!--!--><div class="dropdown" data-visible="false"><!--!--><a id="0HM5CP60808D7" class="nav-link dropdown-toggle btn btn-success" style="color:white" role="button">Ergebnis exportieren</a><!--!-->
                    <!--!--><!--!--><div><div class="dropdown-menu" data-visible="false"><!--!--><a class="dropdown-item"><!--!--><div class="b-tooltip b-tooltip-right b-tooltip-inline" role="tooltip" data-tooltip="Bitte prüfen sie die Bearbeitungshinweise auf Fehler. Andernfalls ist Datei nicht exportierbar." _bl_27=""><!--!--><!--!--><button id="0HM5CP60808DF" type="button" class="btn btn-primary" disabled="" _bl_32="">Cuesheet herunterladen</button></div></a><!--!-->
                        <!--!--><a class="dropdown-item"><!--!--><button id="0HM5CP60808DB" type="button" class="btn btn-secondary" _bl_28="">Export Profile anzeigen</button></a></div></div></div></div><!--!-->
            
            <!--!--><!--!--><!--!--><div class="nav-item"><!--!--><!--!--><!--!--><div class="dropdown" data-visible="false"><!--!--><a id="0HM5CP60808D8" class="nav-link dropdown-toggle btn btn-danger" style="color:white" role="button">Zurücksetzen</a><!--!-->
                    <!--!--><!--!--><div><div class="dropdown-menu dropdown-menu-right" data-visible="false"><!--!--><a class="dropdown-item"><!--!--><button id="0HM5CP60808DC" type="button" class="btn btn-danger" _bl_29="">Alle Tracks löschen</button></a><!--!-->
                        <!--!--><a class="dropdown-item"><!--!--><button id="0HM5CP60808DD" type="button" class="btn btn-danger" _bl_30="">Cuesheet zurücksetzen</button></a><!--!-->
                        <!--!--><hr id="0HM5CP60808DA" class="divider divider-solid"><!--!-->
                        <!--!--><a class="dropdown-item"><!--!--><button id="0HM5CP60808DE" type="button" class="btn btn-danger" _bl_31="">Komplette Anwendung neustarten</button></a></div></div></div></div></nav></header><!--!-->
    <!--!--><main class="b-layout-content m-2"><!--!--><div class="accordion"><!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Eingabedateien hier her ziehen</h3><!--!-->
                        <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path></svg></div></a></div><!--!-->
                <!--!--><div class="collapse"><div class="card-body"><div class="fileUploadDragNDrop mb-3" ondragover="dragOver(event, this)" ondragleave="dragLeave(event, this)" ondrop="dropFiles(event, this, 'dropInputfiles')"><!--!--><svg class="fileUploadDragNDropIcon" xmlns="http://www.w3.org/2000/svg" width="50" height="43" viewBox="0 0 50 43"><path d="M48.4 26.5c-.9 0-1.7.7-1.7 1.7v11.6h-43.3v-11.6c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v13.2c0 .9.7 1.7 1.7 1.7h46.7c.9 0 1.7-.7 1.7-1.7v-13.2c0-1-.7-1.7-1.7-1.7zm-24.5 6.1c.3.3.8.5 1.2.5.4 0 .9-.2 1.2-.5l10-11.6c.7-.7.7-1.7 0-2.4s-1.7-.7-2.4 0l-7.1 8.3v-25.3c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v25.3l-7.1-8.3c-.7-.7-1.7-.7-2.4 0s-.7 1.7 0 2.4l10 11.6z"></path></svg>
                        <!--!--><input id="dropInputfiles" class="inputfile" multiple="" type="file" _bl_18=""><!--!-->
                        <label for="dropInputfiles"><!--!--><strong>Wählen Sie die Dateien</strong><span> oder ziehen Sie diese hier her</span></label></div><!--!-->
                    <!--!--><!--!--><!--!--><div id="0HM5CP60808D5" class="alert alert-danger d-none" role="alert" _bl_24=""><!--!--><strong id="0HM5CP60808D9" _bl_26="">Ungültige Datei</strong><!--!-->
                        <!--!-->Sie haben eine ungültige Datei selektiert (""), die nicht verarbeitet werden kann. Bitte wählen Sie nur gültige Dateien (Textimportdateien, Cuesheets, Audiodateien)!</div></div></div></div><!--!-->
            <!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Import aus vorhandenen Dateien</h3><!--!-->
                        <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path></svg></div></a></div><!--!-->
                <!--!--><div class="collapse"><div class="card-body"><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="importTextFileLabel">Textdatei</span></div><!--!-->
                        <!--!--><input class="form-control" accept="text/plain" aria-label="Textfile" aria-describedby="importTextFileLabel" type="file" _bl_19=""></div><!--!-->
                    <div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="importCuesheetFileLabel">Cuesheet</span></div><!--!-->
                        <!--!--><input class="form-control" accept=".cue" aria-label="Cuesheetfile" aria-describedby="importCuesheetFileLabel" type="file" _bl_20=""></div></div></div></div><!--!-->
            <!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Cuesheet Daten</h3><!--!-->
                        <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"></path></svg></div></a></div><!--!-->
                <!--!--><div class="collapse show"><div class="card-body"><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="cdArtistLabel">CD Künstler</span></div><!--!-->
                        <input type="text" class="form-control alert-warning" id="Cuesheet.Artist_1bb8e366-c1a3-47bd-963b-341cf6660d99" aria-label="CD Artist" aria-describedby="cdTitleLabel" placeholder="CD Künstler eingeben" data-toggle="tooltip" data-placement="top" title="Künstler hat keinen Wert!"></div><!--!-->
                    <div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="cdTitleLabel">CD Titel</span></div><!--!-->
                        <input type="text" class="form-control alert-warning" id="Cuesheet.Title_5be21127-347e-42e0-8f73-6c280fee9a04" aria-label="CD Title" aria-describedby="cdTitleLabel" placeholder="CD Titel eingeben" data-toggle="tooltip" data-placement="top" title="Titel hat keinen Wert!"></div><!--!-->
                    <div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="cdAudioFileLabel">Audio Datei</span></div><input type="file" class="form-control alert-danger" id="Cuesheet.AudioFile_b1e6fb5a-adb3-45c8-9f00-35abc564f957" accept="audio/*" aria-label="Audiofile" aria-describedby="cdAudioFileLabel" placeholder="Audio Datei auswählen" onchange="audioFileChanged('Cuesheet.AudioFile_b1e6fb5a-adb3-45c8-9f00-35abc564f957')" data-toggle="tooltip" data-placement="top" title="Audio Datei hat keinen Wert!"></div></div></div></div><!--!-->
            
            <!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Cuesheet Tracks</h3><!--!-->
                        <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"></path></svg></div></a></div><!--!-->
                <!--!--><div class="collapse show"><div class="card-body"><div class="table-responsive-md"><table class="table table-bordered"><thead><tr class="thead-light"><!--!--><th><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-button-wide" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M0 1.5A1.5 1.5 0 0 1 1.5 0h13A1.5 1.5 0 0 1 16 1.5v2A1.5 1.5 0 0 1 14.5 5h-13A1.5 1.5 0 0 1 0 3.5v-2zM1.5 1a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-13zM14 7H2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1zM2 6a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H2z"></path>
                                            <path fill-rule="evenodd" d="M15 11H1v-1h14v1zM2 12.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-10a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5zm0 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5z"></path>
                                            <path d="M12.823 2.823l-.396-.396A.25.25 0 0 1 12.604 2h.792a.25.25 0 0 1 .177.427l-.396.396a.25.25 0 0 1-.354 0z"></path></svg></th>
                                    <!--!--><th>#</th>
                                    <th>Künstler</th><!--!-->
                                    <th>Titel</th><!--!-->
                                    <th>Begin</th><!--!-->
                                    <th>Ende</th><!--!-->
                                    <th>Länge</th><!--!-->
                                    <th>Hinweise</th></tr></thead><!--!-->
                            <tbody></tbody></table></div><!--!-->
                    <button class="btn btn-primary">Neuen Track hinzufügen</button><!--!-->
                    <button class="btn btn-warning">Alle Tracks löschen</button></div></div></div><!--!-->
            <!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Cuesheet Ergebnis</h3><!--!-->
                        <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"></path></svg></div></a></div><!--!-->
                <!--!--><div class="collapse show"><div class="card-body"><!--!--><div class="accordion"><!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Bearbeitungshinweise</h3><!--!-->
                                    <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path></svg></div></a></div><!--!-->
                            <!--!--><div class="collapse"><div class="card-body"><!--!--><div class="accordion"><!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Warnungen</h3><!--!-->
                                                    <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"></path></svg></div></a></div><!--!-->
                                            <!--!--><div class="collapse show"><div class="card-body"><a onclick="document.getElementById('Cuesheet.Artist_1bb8e366-c1a3-47bd-963b-341cf6660d99').focus();"><div class="alert alert-warning" role="alert">Cuesheet : Künstler hat keinen Wert!</div></a><a onclick="document.getElementById('Cuesheet.Title_5be21127-347e-42e0-8f73-6c280fee9a04').focus();"><div class="alert alert-warning" role="alert">Cuesheet : Titel hat keinen Wert!</div></a></div></div></div><!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><!--!--><a class="active" style="justify-content: space-between;display: flex;-webkit-box-pack:justify"><h3>Fehler</h3><!--!-->
                                                    <div><!--!--><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"></path></svg></div></a></div><!--!-->
                                            <!--!--><div class="collapse show"><div class="card-body"><a onclick="document.getElementById('Cuesheet.AudioFile_b1e6fb5a-adb3-45c8-9f00-35abc564f957').focus();"><div class="alert alert-danger" role="alert">Cuesheet : Audio Datei hat keinen Wert!</div></a></div></div></div></div></div></div></div></div></div></div></div></div><!--!-->

        <br>

        <!--!--><!--!--><div class="card"><!--!--><!--!--><div class="card-header"><h3>Wiedergabe</h3></div><!--!-->
    <!--!--><!--!--><div class="card-body"><div class="row"><div class="col-1"><div>--:--:--</div></div><!--!-->
            <div class="col-10"><!--!--><input type="range" class="form-control-range" step="0" min="0" max="100"></div><!--!-->
            <div class="col-1"><div>--:--:--</div></div></div><!--!-->
        <div class="row"><!--!--><div class="col-1"><button class="btn btn-primary oi oi-media-play disabled" disabled=""></button></div>
                <div><button class="btn btn-secondary oi oi-media-step-backward disabled" disabled="" data-toggle="tooltip" data-placement="top" title="Wiedergabeposition auf Begin von vorherigen Track setzen"></button><!--!-->
                    <button class="btn btn-primary oi oi-media-stop disabled" disabled=""></button>
                    <button class="btn btn-secondary oi oi-media-step-forward disabled" disabled="" data-toggle="tooltip" data-placement="top" title="Wiedergabeposition auf Begin von nächstem Track setzen"></button></div></div></div></div></main></section><!--!-->

<!--!--><!--!--><!--!--><!--!--><div id="0HM5CP60808CL" class="modal fade" tabindex="-1" role="dialog" _bl_6=""><!--!--><div id="0HM5CP60808CO" class="modal-backdrop fade"></div><!--!-->
    <!--!--><div class="modal-content" modalsize="Small"><!--!--><div class="modal-header"><!--!--><h4 class="modal-title"><!--!--><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"></path></svg>
                Bestätigung erforderlich</h4><!--!-->
            <!--!--><button type="button" class="close" aria-label="Close"><!--!--><span aria-hidden="true">×</span></button></div><!--!-->
        <!--!--><div class="modal-body">Bitte Bestätigen Sie, dass die komplette Anwendung neugestartet werden soll. Alle ungespeicherten Änderungen werden dadurch verloren!</div><!--!-->
        <!--!--><div class="modal-footer"><!--!--><button id="0HM5CP60808CR" type="button" class="btn btn-primary" _bl_11="">Bestätigen</button><!--!-->
            <!--!--><button id="0HM5CP60808CS" type="button" class="btn btn-secondary" _bl_12="">Abbrechen</button></div></div></div><!--!-->

<!--!--><!--!--><!--!--><div id="0HM5CP60808CJ" class="modal fade show" tabindex="-1" role="dialog" _bl_4="" style="display: block; padding-right: 17px"><!--!--><div id="0HM5CP60808CM" class="modal-backdrop fade show"></div><!--!-->
    <!--!--><div class="modal-content modal-xl"><!--!--><div class="modal-header"><!--!--><h4 class="modal-title">Importassistent für Textdateien</h4><!--!-->
            <!--!--><button type="button" class="close" aria-label="Close"><!--!--><span aria-hidden="true">×</span></button></div><!--!-->
        <!--!--><div class="modal-body"><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="textImportScheme">Import Textschema</span></div><!--!-->
                    <input type="text" class="form-control" aria-label="TextImportScheme" aria-describedby="textImportScheme" placeholder="Textschema für den Import hier eingeben" data-toggle="tooltip" data-placement="top" title="Textschema für den Import hier eingeben. Die Identifikation wird über reguläre Ausdrücke ausgeführt."><!--!-->
                    <div class="input-group-append"><!--!--><!--!--><!--!--><div id="0HM5CP60808DL" class="dropdown" _bl_33=""><!--!--><button id="0HM5CP60808DM" type="button" class="btn dropdown-toggle btn-secondary" data-toggle="dropdown" _bl_34="">Platzhalter zum Importschema hinzufügen</button><!--!-->
                            <!--!--><div class="dropdown-menu"><!--!--><a class="dropdown-item">Position</a><!--!--><a class="dropdown-item">Künstler</a><!--!--><a class="dropdown-item">Titel</a><!--!--><a class="dropdown-item">Begin</a><!--!--><a class="dropdown-item">Ende</a><!--!--><a class="dropdown-item">Länge</a></div></div></div></div><div class="table-responsive-md"><table class="table table-bordered"><thead><tr class="thead-light"><!--!--><th>#</th>
                            <th>Künstler</th><!--!-->
                            <th>Titel</th><!--!-->
                            <th>Begin</th><!--!-->
                            <th>Ende</th><!--!-->
                            <th>Länge</th></tr></thead><!--!-->
                    <tbody><tr><td></td><!--!-->
                                    <td>Sample Artist 1</td><!--!-->
                                    <td>Sample Title 1</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:05:00</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 2</td><!--!-->
                                    <td>Sample Title 2</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:09:23</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 3</td><!--!-->
                                    <td>Sample Title 3</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:15:54</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 4</td><!--!-->
                                    <td>Sample Title 4</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:20:13</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 5</td><!--!-->
                                    <td>Sample Title 5</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:24:54</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 6</td><!--!-->
                                    <td>Sample Title 6</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:31:54</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 7</td><!--!-->
                                    <td>Sample Title 7</td><!--!-->
                                    <td></td><!--!-->
                                    <td>00:45:54</td><!--!-->
                                    <td></td></tr><tr><td></td><!--!-->
                                    <td>Sample Artist 8</td><!--!-->
                                    <td>Sample Title 8</td><!--!-->
                                    <td></td><!--!-->
                                    <td>01:15:54</td><!--!-->
                                    <td></td></tr></tbody></table></div></div><!--!-->
        <!--!--><div class="modal-footer"><!--!--><div class="b-tooltip b-tooltip-top b-tooltip-inline" role="tooltip" _bl_7=""><!--!--><!--!--><button id="0HM5CP60808CT" type="button" class="btn btn-primary" _bl_13="">Tracks importieren</button></div><!--!-->
            <!--!--><button id="0HM5CP60808CP" type="button" class="btn btn-secondary" _bl_8="">Abbrechen</button></div></div></div><!--!-->

<!--!--><!--!--><!--!--><div id="0HM5CP60808CK" class="modal fade" tabindex="-1" role="dialog" _bl_5=""><!--!--><div id="0HM5CP60808CN" class="modal-backdrop fade"></div><!--!-->
    <!--!--><div class="modal-content"><!--!--><div class="modal-header"><!--!--><h4 class="modal-title">Export Profile</h4><!--!-->
            <!--!--><button type="button" class="close" aria-label="Close"><!--!--><span aria-hidden="true">×</span></button></div><!--!-->
        <!--!--><div class="modal-body"><!--!--><!--!--><div class="form-group row justify-content-end"><!--!--><label class="col-form-label col-2">Exportprofil auswählen</label><!--!-->
                <!--!--><!--!--><div class="col-10"><!--!--><!--!--><select id="0HM5CP60808D6" class="custom-select" _bl_25=""><!--!--><!--!--><option value="ebd47753-1369-4c22-b68e-5dfa1dbe50ae" selected="">CSV Export</option><!--!--><option value="8fd22e2b-8311-4cd9-b23c-9de8430c497a">Tracks only</option></select></div></div><!--!-->
            <button class="btn btn-primary">Neues Exportprofil hinzufügen</button><!--!-->
            <button class="btn btn-danger">Aktuelles Exportprofil löschen</button><!--!-->
            <hr><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="exportProfileNameLabel">Name</span></div><!--!-->
                    <input class="form-control" aria-describedby="exportProfileFilenameLabel"></div><!--!-->
                <div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="exportProfileFilenameLabel">Dateiname</span></div><!--!-->
                    <input class="form-control" aria-describedby="exportProfileFilenameLabel"></div><!--!-->
                <div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="exportProfileSchemeHeadLabel">Schema Kopf</span></div><!--!-->
                    <input class="form-control" aria-describedby="exportProfileSchemeHeadLabel" placeholder="Bitte geben Sie hier das Kopf Schema für den Export an" data-toggle="tooltip" data-placement="top" title="Bitte geben Sie hier das Kopf Schema für den Export an. Jeder Platzhalter wird durch seinen zugehörigen Wert ersetzt. Platzhalter beginnen und enden mit %."><!--!-->
                    <div class="input-group-append"><!--!--><!--!--><!--!--><div id="0HM5CP60808CU" class="dropdown" _bl_14=""><!--!--><button id="0HM5CP60808D2" type="button" class="btn dropdown-toggle btn-secondary" data-toggle="dropdown" _bl_21="">Platzhalter zum Kopf Export Schema hinzufügen</button><!--!-->
                            <!--!--><div class="dropdown-menu"><!--!--><a class="dropdown-item">Künstler</a><!--!--><a class="dropdown-item">Titel</a><!--!--><a class="dropdown-item">AudioFile</a></div></div></div></div><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="exportProfileSchemeTrackLabel">Schema Tracks</span></div><!--!-->
                    <input class="form-control" aria-describedby="exportProfileSchemeTrackLabel" placeholder="Bitte geben Sie hier das Track Schema für den Export an" data-toggle="tooltip" data-placement="top" title="Bitte geben Sie hier das Track Schema für den Export an. Jeder Platzhalter wird durch seinen zugehörigen Wert ersetzt. Platzhalter beginnen und enden mit %."><!--!-->
                    <div class="input-group-append"><!--!--><!--!--><!--!--><div id="0HM5CP60808CV" class="dropdown" _bl_15=""><!--!--><button id="0HM5CP60808D3" type="button" class="btn dropdown-toggle btn-secondary" data-toggle="dropdown" _bl_22="">Platzhalter zum Track Export Schema hinzufügen</button><!--!-->
                            <!--!--><div class="dropdown-menu"><!--!--><a class="dropdown-item">Position</a><!--!--><a class="dropdown-item">Künstler</a><!--!--><a class="dropdown-item">Titel</a><!--!--><a class="dropdown-item">Begin</a><!--!--><a class="dropdown-item">Ende</a><!--!--><a class="dropdown-item">Länge</a></div></div></div></div><div class="input-group mb-3"><div class="input-group-prepend"><span class="input-group-text" id="exportProfileSchemeFooterLabel">Schema Fuß</span></div><!--!-->
                    <input class="form-control" aria-describedby="exportProfileSchemeFooterLabel" placeholder="Bitte geben Sie hier das Fuß Schema für den Export an" data-toggle="tooltip" data-placement="top" title="Bitte geben Sie hier das Fuß Schema für den Export an. Jeder Platzhalter wird durch seinen zugehörigen Wert ersetzt. Platzhalter beginnen und enden mit %."><!--!-->
                    <div class="input-group-append"><!--!--><!--!--><!--!--><div id="0HM5CP60808D0" class="dropdown" _bl_16=""><!--!--><button id="0HM5CP60808D4" type="button" class="btn dropdown-toggle btn-secondary" data-toggle="dropdown" _bl_23="">Platzhalter zum Fuß Export Schema hinzufügen</button><!--!-->
                            <!--!--><div class="dropdown-menu"><!--!--><a class="dropdown-item">Künstler</a><!--!--><a class="dropdown-item">Titel</a><!--!--><a class="dropdown-item">AudioFile</a></div></div></div></div></div><!--!-->
        <!--!--><div class="modal-footer"><!--!--><div class="b-tooltip b-tooltip-top b-tooltip-inline" role="tooltip" _bl_9=""><!--!--><!--!--><button id="0HM5CP60808D1" type="button" class="btn btn-primary" _bl_17="">Exportdatei herunterladen</button></div><!--!-->
            <!--!--><button id="0HM5CP60808CQ" type="button" class="btn btn-secondary" _bl_10="">Schließen</button></div></div></div></main></section></app>

**Comment by stsrki** [comment]
Right-clicking on a modal and choosing **Inspect** will show you **dev tools**. Here you can select different elements and on the right side(mine is on the right), you can see every applied style. Play with it and see what is messing with modal center.

![image](https://user-images.githubusercontent.com/900302/103355624-f7f92f80-4aae-11eb-895f-8d9a4e9392a2.png)

**Comment by NeoCoderMatrix86** [comment]
Ok, I just selected the element with class="modal fade show", so here you are:

![grafik](https://user-images.githubusercontent.com/40752681/103356001-0ac03400-4ab0-11eb-8f1e-e5d26e39d0e9.png)

I can see no override currently :(.

**Comment by NeoCoderMatrix86** [comment]
I just found out, I'm missing the complete div for centered:

`<div class="modal-dialog modal-dialog-centered" role="document">....</div>`

So, you have any idea, why this div is not rendered into the HTML?

**Comment by stsrki** [comment]
Do you have this in your app startup?

```diff
builder.Services
    .AddBlazorise( options =>
    {
        options.ChangeTextOnKeyPress = true;
    } )
+    .AddBootstrapProviders()
    .AddFontAwesomeIcons();
```

**Comment by NeoCoderMatrix86** [comment]
Currently I'm not using the FontAwesomeIcons, so my startup is:

`builder.Services.AddBlazorise(options =>
            {
                options.ChangeTextOnKeyPress = true;
            })
            .AddBootstrapProviders();`

**Comment by stsrki** [comment]
What version of Blazorise you have?

**Comment by NeoCoderMatrix86** [comment]
I'm using 0.9.2.4:

`   <PackageReference Include="Blazorise.Bootstrap" Version="0.9.2.4" />
    <PackageReference Include="Blazorise.Components" Version="0.9.2.4" />`

**Comment by stsrki** [comment]
In that case I hope you also have `.UseXY` method along with the `.AddXY`:

```diff
host.Services
      .UseBootstrapProviders()
+      .UseFontAwesomeIcons();
```

**Comment by NeoCoderMatrix86** [comment]
That was the Problem, thanks for your help. I didn't know, that I also have to use this methods, since it is not included in documentation :(. But now I'm save :).

**Comment by stsrki** [comment]
It's in the documentation :) https://blazorise.com/docs/start/#4a-blazor-webassembly

**Comment by NeoCoderMatrix86** [comment]
Ok, than I was just a bit blind :). Update the project to use 0.9.2.4 and didn't add this code. But well, now it works :)!
