### ISSUE TITLE
Documentation should be bound to demo app!

### ISSUE THREAD

**Issue by tesar-tech** [stsrki/Blazorise#1656]
I am new to blazorise. When I try to understand something I need to switch between demo app to see how it looks and between documentation to understand what my options are. It is just slower, really is.
It is done for some components (e.g [button](https://blazorise.com/docs/components/button/)), but for the others, the demo are missing ([rich text](https://blazorise.com/docs/extensions/richtextedit/)).

It would be great to have it on one place.

**Comment by stsrki** [comment]
I agree completely. It's currently at work but it will take some time before I finish it.

Look at this answer https://github.com/stsrki/Blazorise/issues/1642#issuecomment-750337311

**Comment by tesar-tech** [comment]
Glad to hear that!
