### ISSUE TITLE
DataGrid with custom ReadData cannot sort

### ISSUE THREAD

**Issue by tesar-tech** [stsrki/Blazorise#1661]
**Describe the bug**

This works as expected (sorts data without the problem).
```
   <DataGrid TItem="MyDto" Data="@Dtos"
 ...

  protected override async Task OnInitializedAsync()
    {
       Dtos = //get them from api
    }
```
But in this case, when I click on column I want to sort, OnReadData is called and no sort is applied. 
```
 <DataGrid TItem="MyDto" Data="@Dtos" ReadData="@OnReadData"
...
  async Task OnReadData(DataGridReadDataEventArgs<TrainingCycleDto> e)
    {
        Dtos = //get them from api
    }
```

**Comment by paulosdfigueiredo** [comment]
When you use ReadData, you are using manual read.

In this cases you probably want to get the items paginated from server. The DataGridReadDataEventArgs has all the parameters you need to send them to your api and sort / paginate on server:

- Page
- PageSize
- Columns - contains filter and sorting information from each column

**Comment by tesar-tech** [comment]
Yes, it does make sense.
