### ISSUE TITLE
[BUG] Set e.ErrorText don't update ValidationError message

### ISSUE THREAD

**Issue by gaffkins** [stsrki/Blazorise#1665]
In manual validation function I set e.ErrorText but after validation message don't appear.
ver 9.2.4

**Comment by stsrki** [comment]
Already fixed in 0.9.3 https://github.com/stsrki/Blazorise/commit/58b4e5dbc5ea280488fc500bce516d0c0a20d6cd

I just need to transfer it to 0.9.2.x

**Comment by gaffkins** [comment]
Thank tou for response. When you publish nuget with this fix?

**Comment by stsrki** [comment]
Hopefully by the end of the week.

**Comment by gaffkins** [comment]
Hi, any news about release this fix?

**Comment by stsrki** [comment]
Still not ready. It's the holiday season so I didn't work as much as I usually do 😅

**Comment by gaffkins** [comment]
Please can you apply this fix to 9.2 ver. Client wants to kill me ;p

**Comment by stsrki** [comment]
Working on patch

**Comment by gaffkins** [comment]
you are great, thank you
