### ISSUE TITLE
Incorrect render html output when build <Select> with for/foreach

### ISSUE THREAD

**Issue by ruslankiskinov** [stsrki/Blazorise#1666]
When you create a simple **Select** using for loop as shown below, the renderd select **text** part contains only the last value of the iterator variable for each of the **SelectItem**, the **value** is rendered correctly.

```html
<Select SelectedValue="3" >
      @for (int i = 0; i < 5; i++)
      {
      <SelectItem Value="@i">@i</SelectItem>
      }
</Select>
```

**Actual render is the following:**

```html
<select >
    <option value="0">5</option>
    <option value="1">5</option>
    <option value="2">5</option>
    <option value="3" selected="">5</option>
    <option value="4">5</option>
</select>
```

The strange part is that the value is correct but the text is not. 
If you build a normal html <select> instead there is no ptoblem with the rendered output.

Please advice what is the problem or are there any workarrounds?

Thank you
Ruslan

**Comment by stsrki** [comment]
Aaahhh, the famous Blazor for each loop problem :) If you google it you will learn more [about it](https://stackoverflow.com/questions/54812427/for-loop-not-returning-expected-value-c-sharp-blazor). 

To fix your code just use a temporary variable

```cshtml
<Select SelectedValue="3" >
  @for (int i = 0; i < 5; i++)
  {
    var text = i.ToString();
    <SelectItem Value="@i">@text</SelectItem>
  }
</Select>
```

**Comment by nlertola** [comment]
This solution works for <RadioGroup> too! I was having almost the exact same issue. Thanks!
