### ISSUE TITLE
Datagrid: Pager page selection showing incorrectly on 0.9.3 - Preview 4

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1669]
**Describe the bug**
Now shows up both a sequencial selection and a dropdown selection:
![image](https://user-images.githubusercontent.com/22283161/103759002-f11c7080-500a-11eb-8fba-499de3f77cd7.png)

**Expected:**
![image](https://user-images.githubusercontent.com/22283161/103760096-8a985200-500c-11eb-9484-5072b1ae965e.png)

**To Reproduce**
I'm guessing this is easily reproducable since I haven't made any changes, only updated package, which was previously on preview 3
Additionally, did a version rollback to preview 3 and it's back to normal.

**Comment by stsrki** [comment]
I made this change before testing it through. It's already fixed and will be available in preview 5 :)
