### ISSUE TITLE
label label-danger - bootstrap class

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1672]
By default, you already have a css to replace the bootstrap, but I was looking to use the 'label' class. And apparently it is not directly accessible. Is there any way to solve it?

**Comment by stsrki** [comment]
You mean to add `Color` support to the `Label` component?

**Comment by drma-dev** [comment]
No, the class label. Is similar to badge, but it's different.

https://www.w3schools.com/bootstrap/bootstrap_badges_labels.asp

**Comment by stsrki** [comment]
That's for Bootstrap 3 as far as I can see. There is no `label` for Bootstrap 4: https://getbootstrap.com/docs/4.5/components/badge/

**Comment by drma-dev** [comment]
it is true.  I was reading the bootstrap 4 documentation. badge replaced the label.  and badge-bill replaced the old badge.  do you have it?

**Comment by stsrki** [comment]
Yep

```cshtml
<Badge Pill="true">Hello</Badge>
```
