### ISSUE TITLE
Not able to change primary text color.

### ISSUE THREAD

**Issue by kunalpgithub** [stsrki/Blazorise#1674]
I want to change text color of my heading in blazorise component using  theme.

It looks like colors are getting override by boostrap mixing scss.

Here is  my code for theme and usage of heading component.

```
<Blazorise.ThemeProvider Theme="@theme">
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</Blazorise.ThemeProvider>

@code{

    private Theme theme = new Theme
    {
        
        BackgroundOptions = new ThemeBackgroundOptions {
            Primary = "#212336",
            // #FF4A57
        },

        TextColorOptions = new ThemeTextColorOptions {
            Primary = "#FF4A57",
        },
        
    };
}
```
Here is usage of my theme colors
```

<Heading Size="HeadingSize.Is1" Color="TextColor.Primary" >
        Skill Sets
    </Heading>
```
But in browser I don't see this color getting applied, instead if picks up default primary blue color.

![image](https://user-images.githubusercontent.com/17749200/103864996-8726c880-50e9-11eb-9290-651cde8f44db.png)

I would like to see color applied in theme variable instead of default. 

I have also tried overriding class in component css and in global css file, but still its picking default blue color.

Let me know if I am doing anything wrong.

**Comment by stsrki** [comment]
It seems like a missing `!important` flag. Should be an easy fix.

**Comment by kunalpgithub** [comment]
Tried adding important as well, but its not working. Do you mean to add important in theme class, that is also not working.

```
    private Theme theme = new Theme
    {
        
        BackgroundOptions = new ThemeBackgroundOptions {
            Primary = "#212336",
            // #FF4A57
        },

        TextColorOptions = new ThemeTextColorOptions {
            Primary = "#FF4A57 !important",
        },
        
    };
```

**Comment by stsrki** [comment]
Adding it there would not work. It needs to be built with ThemeGenerator.

**Comment by kunalpgithub** [comment]
is there good document around it, on how to use theme generator?

**Comment by stsrki** [comment]
`ThemeGenerator` is not something to be used directly. It is an _internal builder_ that creates CSS styles based on the `Theme` options. Every Blazorise provider has its own theme generator with its own rules.

**Comment by wflouw** [comment]
Having the exact same issue. I implemented a Theme using the ThemeProvider as explained in the documentation. I set the Primary value for the TextColorOptions and I get the same behaviour as @kunalpgithub. 

```
private Theme CustomTheme = new Theme
{
    ColorOptions = new ThemeColorOptions
    {
        Primary = ThemeColors.Red.Shades["400"].Value,
        Secondary = ThemeColors.Blue.Shades["400"].Value
    },
    BackgroundOptions = new ThemeBackgroundOptions
    {
        Primary = ThemeColors.Red.Shades["400"].Value,
        Secondary = ThemeColors.Blue.Shades["400"].Value
    },
    TextColorOptions = new ThemeTextColorOptions
    {
        Primary = ThemeColors.Orange.Shades["400"].Value,
        Secondary = ThemeColors.Yellow.Shades["400"].Value
    }
};
```
I check the values in the developer console (Chrome) and I can clearly see that the value I defined in the ThemeTextColorOptions is correct but is striked through and overridden by the default value.

![image](https://user-images.githubusercontent.com/5871124/104132118-9de44e00-537b-11eb-9ebd-07f701335f4c.png)

I could solve the issue by adding the **!important** value in my app.css but it feels dirty and I think it should work via the the ThemeProvider as described in the documentation.

```
.text-primary {
    color: #FFA726 !important;
}
```

**Comment by kunalpgithub** [comment]
@wflouw in my case, even important is also not working. Difference I see is , you are using material and I am using boostrap.

**Comment by nvassell** [comment]
@stsrki How should we include the `!important` in the theme CSS? I can't get the important tag.

**Comment by kunalpgithub** [comment]
@nvassell  adding style in <Head> my index.html with important worked for me. You can try  that.

```
 <style>
        .text-primary {
            color: #FF4A57 !important;
        }
        .nav-link {
            color: #FDFDFD !important;
        }
    </style>
```

**Comment by nvassell** [comment]
@kunalpgithub Oh interesting! I haven't tried that yet!

**Comment by stsrki** [comment]
@nvassell As a workaround use the @kunalpgithub example. In the meantime, I will fix it in the code.
