### ISSUE TITLE
Not able to set default filtering on DataGrid component 

### ISSUE THREAD

**Issue by PatrickBig** [stsrki/Blazorise#1676]
**Describe the bug**
Setting a default filter on a `DataGrid` component is currently not functioning.

I was expecting to be able to set the Filter attribute on any type of `DataGridColumn` as a way to set the default filter but that does not appear to work.

**To Reproduce**
1. Create a new `DataGrid` component
2. Add a `DataGridColumn`
3. Set the `Filter` attribute to a new value, eg `Filter="@(new FilterContext { SearchValue = "something" })"`

**Expected behavior**
The DataGrid would initialize with the filter set for each column.

**Comment by DDDenisSobek** [comment]
@stsrki 
I have not that problem.
I use an injected class, that give allways the same FilterContext, so that there is no problem with subscription (I think thats the problem with `Filter="@(new FilterContext { SearchValue = "something" })"`).
I have only the problem, that when i press "Clear Filter", filters will be set to null, but controls of filters will be not reset. Just when i switch sites, i get cleared filters.
```
@inject GridFilterService FilterService

...

<DataGridColumn TItem="TestClass" Field="@nameof(TestClass.TestProperty)" Caption="TestColumn"
                Filter="@FilterService.GetFilterContext(GRID_NAME,nameof(TestClass.TestProperty))" 
                Editable="true" Filterable="true" >
    <FilterTemplate>
        <TextEdit TextChanged="@context.FilterValueChanged" Text="@context.SearchValue" 
                  DelayTextOnKeyPress="true" />
    </FilterTemplate>
</DataGridColumn>

...
```

I also tried to force rerendering of filters with `StateHasChanged`, but it does not work.
```
public async Task ClearFilter(CommandContext context)
{
    await context.Clicked.InvokeAsync();
    StateHasChanged();
}
```

**Comment by stsrki** [comment]
@DDDenisSobek The bug with Clear Filter not clearing `<FilterTemplate>` is fixed for 0.9.3.

**Comment by JoelRHall** [comment]
What is the namespace for FilterTemplate.

**Comment by stsrki** [comment]
`FilterTemplate` is an attribute for the `DataGridColumn`.

**Comment by JoelRHall** [comment]
Then why does the IDE complain that it isn’t found?

**Comment by David-Moreira** [comment]
Hmm there are still times that the razor intelisense fails. It should still compile if you have everything well defined.

**Comment by JoelRHall** [comment]
The issue was with my code. I had misplaced the close of my DataGridColumn. Intellisense then proceeded to totally mislead me. Thanks for your quick response.

**Comment by JoelRHall** [comment]
I added an issue in support about this: https://support.blazorise.com/issues/37/What-is-the-namespace-for-FilterTemplate
