### ISSUE TITLE
Datagrid: Loads 2 times on first render

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1678]
Hello @stsrki 
hope you've been well... :)
**Describe the bug**
I'm not sure if this is something to do with Blazor triggering a re-render or Datagrid or if it's just me missing something.
But I noticed that on the first load, datagrid actually ends up loading 2 times, meaning that it calls ReadData twice.

**To Reproduce**
Tested with a new project, with Blazor Server set to render-mode="**Server**"
Just init datagrid with ReadData set. It will call it two times. Here's the demo source in screenshots... :P

![image](https://user-images.githubusercontent.com/22283161/103936247-17333500-511f-11eb-9acb-a0e481faf89b.png)
![image](https://user-images.githubusercontent.com/22283161/103936283-22866080-511f-11eb-8a61-e0a7ffc0a000.png)

Doesn't seem to make sense taking into account the source code, do you know what it could be?:
```
       protected override Task OnAfterRenderAsync( bool firstRender )
        {
            if ( firstRender )
            {
                if ( ManualReadMode )
                    return HandleReadData();

                // after all the columns have being "hooked" we need to resfresh the grid
                InvokeAsync( () => StateHasChanged() );
            }

            return base.OnAfterRenderAsync( firstRender );
        }
```

**Comment by paulosdfigueiredo** [comment]
Hi, 

It's a known issue, duplicate of #1609.

There's an open PR #1662 to fix it.

**Comment by David-Moreira** [comment]
Oh I'm blind, haven't been paying attention to the latest issues!! Great thanks @paulosdfigueiredo! Closing issue. 👍
