### ISSUE TITLE
Modal not centered any more

### ISSUE THREAD

**Issue by tacoWanneeJama** [stsrki/Blazorise#1680]
**Describe the bug**
I can't get a modal to center the dialog. It sticks to left side

**Difference with example**
I use "dotnet.5.0.1.js" , in the example 5.0.0 is used

I compared my HTML with the example and found out that the **<div "modal-dialog">** was not generated.

My workaround:
`<Modal @ref="modalRef">`
**`  <div class="modal-dialog modal-dialog-centered" role="document">`**
`<ModalContent Centered="true" IsCentered="true" >`

**Additional context**
Maybe the dotnet version is the problem?

**Comment by stsrki** [comment]
Possible the same problem as #1654

Check the answer https://github.com/stsrki/Blazorise/issues/1654#issuecomment-752651065

**Comment by tacoWanneeJama** [comment]
That fixed it
