### ISSUE TITLE
Add OpenReadStream to FileEntry

### ISSUE THREAD

**Issue by Meberem** [stsrki/Blazorise#1681]
Would it be possible to add an `OpenReadStream()` to `FileEntry` so the File can be streamed to the Application rather than read in all at once? This would mirror the API found in the [`InputFile`](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0#inputfile-component) component in Blazor 5.0.

**Comment by stsrki** [comment]
Not sure what you mean. FileEntry has a `WriteToStreamAsync` method that reads and writes the file content to your stream in chunks. So, the file is not read all at once.

The chunk size can be controlled by `MaxMessageSize` parameter.

**Comment by Meberem** [comment]
I see what you mean, it is possible to write a file to a destination in chunks. I however am trying to do something a little different, I am trying to stream the file into a parser. I have an example working with the AspNet Core `InputFile` and a non working attempt under Blazorize:

```
@page "/"
@using Blazorise;
@using System.IO
@using Microsoft.Extensions.Logging

<InputFile OnChange="OnAspNetFileChange"/>

<FileEdit Changed="@OnBlazoriseChanged" />

@code
{
    private static int OneMb = 1024 * 1024;

    [Inject]
    public ILogger<Index> Logger { get; set; }

    private async Task OnAspNetFileChange(InputFileChangeEventArgs args)
    {
        if (args.FileCount == 0)
        {
            return;
        }


        var buffer = new byte[OneMb];
        using (var bufferedStream = new BufferedStream(args.File.OpenReadStream(long.MaxValue), OneMb))
        {
            int readCount = 0;
            int readBytes;
            while ((readBytes = await bufferedStream.ReadAsync(buffer, 0, OneMb)) > 0)
            {
                Logger.LogInformation($"Read:{readCount++} {readBytes / (double) OneMb} MB");
                // Do work on the first 1MB of data
            }
        }

        Logger.LogInformation("Done");
    }

    async Task OnBlazoriseChanged(FileChangedEventArgs args)
    {
        var file = args.Files.FirstOrDefault();
        if (file == null)
        {
            return;
        }

        var buffer = new byte[OneMb];
        using (var memoryStream = new MemoryStream(new byte[OneMb]))
        {
            await file.WriteToStreamAsync(memoryStream);

            int readCount = 0;
            int readBytes;
            while ((readBytes = await memoryStream.ReadAsync(buffer, 0, OneMb)) > 0)
            {
                Logger.LogInformation($"Read:{readCount++} {readBytes / (double) OneMb} MB");
                // Do work on the first 1MB of data
            }
        }

        Logger.LogInformation("Done");
    }
}
```

In the AspNet `InputFile` I can stream the results into my buffer and do the work on each chunk, where as, if I am understanding this correctly, I should stream the Blazorise file to a destination (such as a File on disk) then stream that result into my parser. Do you have any advice on this?

**Comment by stsrki** [comment]
I see what you mean. Unfortunately, it's not possible for now. The only way I can think of is that you implement your own class that inherits from `Stream` and then on each write you notify your parser of each change.

Sometime in the future, I might try doing something similar to `InputFile`, but considering all other work it's low on a priority list..

**Comment by Meberem** [comment]
I completely understand that it would be low priority. I have created a PR with the functionality as a reference point if you wanted to include this in the future. Thank you for your work!
