### ISSUE TITLE
blazorize.js error in console

### ISSUE THREAD

**Issue by plsft** [stsrki/Blazorise#1683]
Using Chrome and have all blazorize components installed for Bootstrap. 

blazorise.js:526 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.getBreakpoint (blazorise.js:526)
    at blazorise.js:609

included the following in the index.html 
<link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />

    <script src="_content/Blazorise/blazorise.js"></script>
    <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>

**Comment by stsrki** [comment]
Try hitting CTRl+F5 to clear the cache. This is usually the case with Blazor.

**Comment by plsft** [comment]
That did not work.  I tried it quite a bit.

**Comment by plsft** [comment]
breakpoint: {
        // Get the current breakpoint
        getBreakpoint: function () {
            return window.getComputedStyle(document.body, ':before').content.replace(/\"/g, '');
        },

this is the code causing the exception

**Comment by Hajir2005** [comment]
You need to put the blazorise.js file inside the body tag and not in the header.

**Comment by plsft** [comment]
Thank you! That solved the issue. 

Thanks
George
