### ISSUE TITLE
Figure - The image does not respect the size

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1684]
When the height of the image is greater than the width, it does not fit properly.
![image](https://user-images.githubusercontent.com/12803050/104107916-03164180-529f-11eb-807a-4ccf257b2483.png)

But if you think this behavior is right, at least you should force the components below to respect the new image size.
![image](https://user-images.githubusercontent.com/12803050/104107947-41abfc00-529f-11eb-8e93-8e0f94d9f279.png)

**Comment by stsrki** [comment]
I think this is how Bootstrap figures are working. See the comment on their documentation page https://getbootstrap.com/docs/4.6/content/figures/

> Images in figures have no explicit size, so be sure to add the .img-fluid class to your <img> to make it responsive.
