### ISSUE TITLE
Validations mode default

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1688]
**Describe the bug**
Validations Mode has no official default, yet it sets a default value in case of `null` to `Auto` in `Validation.cs`

```
private ValidationMode Mode
    {
      get
      {
        Validations parentValidations = this.ParentValidations;
        return parentValidations == null ? ValidationMode.Auto : parentValidations.Mode;
      }
    }
```

**Expected behavior**
Either set a default value to Auto or throw an exception of not set.

**Comment by stsrki** [comment]
Not sure what you mean. The Auto mode is the default mode for the `Validations `component. It's mentioned in the docs https://blazorise.com/docs/components/validation/#attributes

The part of the code you posted is from `Validation`, which inherits mode from the `Validations`. If it's used on it's own it will also have a default Auto mode.

**Comment by Luk164** [comment]
I meant that you could just initialize it as Auto instead of doing a null check down the road, sorry I was a bit tired yesterday and did not make it clear. Anyway taking a second look it is not really a problem as much as a difference in writing styles, so I am closing the issue.
