### ISSUE TITLE
Alert - Close button doesnt work

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1693]
![image](https://user-images.githubusercontent.com/12803050/104192571-c3b23700-53fd-11eb-96ce-c32e16dc10ed.png)

Or did I forget to configure something?

**Comment by stsrki** [comment]
Close will not work automatically. By default `CloseButton` is stupid so it doesn't know what to do. You can use it with Alert like this:

```cshtml
<Alert Color="Color.Success" Visible="@dismisableAlert1" Dismisable="true">
    <AlertDescription>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </AlertDescription>
    <AlertMessage>
        Alert Link.
    </AlertMessage>
    <CloseButton Clicked="@(()=>dismisableAlert1 = false)" />
</Alert>
@code{
    bool dismisableAlert1 = true;
}
```
