### ISSUE TITLE
Carousel doesn't render

### ISSUE THREAD

**Issue by Sossenbinder** [stsrki/Blazorise#1701]
**Describe the bug**
I am trying to get the Carousel to work as described in the documentation, but there's nothing rendered at all

I'm currently using this code:

```
<div>
        <Carousel @bind-SelectedSlide="@selectedSlide">
	        <CarouselSlide Name="1">
		        Bla
	        </CarouselSlide>
	        <CarouselSlide Name="2">
		        Bla
	        </CarouselSlide>
	        <CarouselSlide Name="3">
		        Bla
	        </CarouselSlide>
        </Carousel>
</div>
```

The carousel is not only invisible, but it's also not even being rendered at all. The DOM is completely missing the component.

I tried to check its state by setting a @ref and was able to figure out that it is indeed properly initialized with all the CarouselSlides, but it's just not doing anything.

I'm using blazorise with the following configuration:

```
services
        .AddBlazorise()
        .AddBootstrapProviders()
        .AddMaterialIcons();

```

If required, I'm happy to provide more input, and thanks for the awesome library by the way! Much appreciated

**Comment by Sossenbinder** [comment]
Okay, that was a quick one...

It seems like I was merely missing the 

	```
var builtHost = builder.Build();

	builtHost
		.Services
		.UseBootstrapProviders()
		.UseMaterialIcons();
```
part. Didn't think it would make a difference!

**Comment by stsrki** [comment]
Yeah, `UseBootstrapProviders` is needed so that Blazorise can override a default component. At least this was needed until 0.9.2. Starting from 0.9.3 these `Use` methods are removed :)
