### ISSUE TITLE
Layout documentation

### ISSUE THREAD

**Issue by adverst** [stsrki/Blazorise#171]
Is there any documentation available with more detail on general layout? I'm getting all kinds of bizarre results using <row><column> columnsize etc.

I couldn't see column or row listed in docs, and the columnsize document section is brief.

I'm not sure if that's all standard nomenclature from one of the base frameworks, if it is can you point me to anything that might explain in more detail?

**Comment by stsrki** [comment]
Sorry I couldn't response earlier. The layout basically follows standard flex-box grid system. Just an implementation in Blazor.

You can look at the demo to see how it is used.

eg. https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/CardsPage.razor
