### ISSUE TITLE
dev093: DataGridColumn Width Property does not render correctly

### ISSUE THREAD

**Issue by sks-ttaylor** [stsrki/Blazorise#1711]
**Describe the bug**
When a DataGridColumn has the Width property set, the output html is incorrectly.

**To Reproduce**
```<DataGridColumn TItem="PageComment" Field="@nameof(PageComment.CreatedDate)" Caption="Date" Width="20em" Readonly="true" Sortable="true" Filterable="false" />```

generates

```<td width="20em">10/8/2020 10:02:47 AM</td>```

**Expected behavior**
Properly formatted html

**Comment by sks-ttaylor** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td  the width is a deprecated attribute.
So, I would think Width would need to be rendered in a <col /> tag.

**Comment by stsrki** [comment]
Yeah, style would be the most appropriate here.

**Comment by sks-ttaylor** [comment]
as a work around i'm using CellStyle="@((PageComment r) => "width:12em")"

**Comment by stsrki** [comment]
You can also try `HeaderCellStyle`.
