### ISSUE TITLE
Select component not working in multiple mode

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1714]
**Describe the bug**
The SelectedValues always returns an array with a single null value. Also I noticed there is some exception being thrown that does not show up in either developer or browser consoles.

**To Reproduce**
Code:
```
<Select TValue="Tag" Multiple="true" SelectedValuesChanged="TestCallback">
            @foreach (var tag in ProductViewModel.Tags)
            {
                 <SelectItem Value="tag">@tag.Name</SelectItem>
            }
</Select>

private void TestCallback(IReadOnlyList<Tag> obj)
{
    var test = obj;
}
```

**Expected behavior**
List contains all elements selected by user.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/104788569-d082b200-5792-11eb-951c-d22e6fa74834.png)

**Additional context**
I do not particularly like this multi-select as it requires the user to use ctrl-click. Checkboxes would be a lot nicer and ideally an autocomplete for tags like on stackoverflow would be used. (I already opened a [question regarding that](https://stackoverflow.com/questions/65744610/blazor-autocomplete-tagging))

**Comment by stsrki** [comment]
`Select` doesn't work with complex objects, so `Tag` will not work. You must remember that everything must end in a DOM and DOM `select` elements can only work with basic types like `string` or `int`.

I modified your example slightly and it now it is working.

```cshtml
<Select TValue="string" Multiple="true" SelectedValuesChanged="TestCallback">
    @foreach ( var tag in Tags )
    {
        <SelectItem Value="tag.Name">@tag.Name</SelectItem>
    }
</Select>
@code{
    class Tag
    {
        public string Name { get; set; }
    }

    List<Tag> Tags = new List<Tag>()
    {
        new Tag { Name = "a" },
        new Tag { Name = "b" },
    };

    private void TestCallback( IReadOnlyList<string> obj )
    {
        var test = obj;

        Console.WriteLine( string.Join( ",", test ?? Enumerable.Empty<string>() ) );
    }
}
```

**Comment by Luk164** [comment]
@stsrki Is there a specific reason why it is made like this? Because if not then maybe I will take a look at upgrading it so that it can take any object once I have the free time. (Exam season this month)

**Comment by stsrki** [comment]
It's a limitation with how browsers are working and not with Blazorise. Look at some of the links where you can learn more about the reasons

- https://www.telerik.com/forums/binding-dropdownlist-value-to-complex-model
- https://stackoverflow.com/questions/59176644/how-to-bind-object-to-select-option-in-blazor

Basically, you can try converting your entire model into a string. Maybe a simple override of `.ToString` would help but I haven't tried it so I cannot guarantee.

**Comment by Luk164** [comment]
@stsrki I see, so we cannot assign a value directly to select option other than a string. In that case, I think I have a workaround. If we create a dictionary<GUID, TValue> we could assign a guid string and then translate it into the relevant object before returning it as a value. A bit of an overhead but it should work. What do you think?

**Comment by stsrki** [comment]
You mean internally in Blazorise? I'm not sure if I would like to go that way. While it might work, it feels like a hack to me. Let me think it through...

**Comment by Luk164** [comment]
@stsrki I would suggest creating a separate component, like GenericSelect or something, and if it works out we could either have two - a lightweight one and a powerful one, or merge them together in some way. Considering the power of most devices today, a single dictionary and a translation function should not be that big of a deal, unless the select has an enormous amount of options.

**Comment by Luk164** [comment]
@stsrki On second thought, the new component would merely have to wrap the old select with the value translation added in between

**Comment by stsrki** [comment]
I would rather have a single component with new functionality than creating new.

**Comment by Luk164** [comment]
@stsrki I understand. We can see about that once we see it works and does not put undue strain on either the server or browser.

**Comment by Luk164** [comment]
@stsrki Did you resolve this already?

**Comment by stsrki** [comment]
The original issue was because you used complex objects and those are not supported. The only way is to use primitive types for the Select component.

**Comment by Luk164** [comment]
@stsrki So should I create a feature request for the change we talked about?

**Comment by stsrki** [comment]
Please open. Once I have more time I can investigate.
