### ISSUE TITLE
[Question] Question about blazorise and IntelliSense

### ISSUE THREAD

**Issue by Luk164** [stsrki/Blazorise#1723]
@stsrki I have a quick question, did you do anything special to make intelliSense work better with your library?

Because I was making a custom component and I wanted an Action parameter as a callback, but while it works, the intelliSense does not fill in the lambda like yours does. The only thing related I see in blazorise code is this:
```
        /// <summary>
        /// Occurs when the button is clicked.
        /// </summary>
        [Parameter] public EventCallback Clicked { get; set; }
```

Example:
 Neither of these gets intelliSense
```
    [Parameter]
    public Action<Product, int> Test { get; set; }

    [Parameter]
    public EventCallback<(Product, int)> TestEventCallback { get; set; }

    [Parameter]
    public EventCallback TestEventCallback2 { get; set; }
```
![image](https://user-images.githubusercontent.com/30559213/104933047-b28e9a80-59a8-11eb-9c04-25a5b8ceedc3.png)

On the other hand, blazorise does this:
![image](https://user-images.githubusercontent.com/30559213/104933119-c76b2e00-59a8-11eb-9108-7b159e96a3c3.png)

**Comment by stsrki** [comment]
Nothing special is done in Blazorise. I guess you're using Rider as your IDE? It tends to not work that well with razor syntax.

**Comment by Luk164** [comment]
> Nothing special is done in Blazorise. I guess you're using Rider as your IDE? It tends to not work that well with razor syntax.

VS with ReSharper actually

**Comment by stsrki** [comment]
I really cant talk or know much about the reasons since I only use VS intellisense. Maybe you can ask on JetBrain/Resharper help desk?

**Comment by Luk164** [comment]
@stsrki No reason for that, they both already know blazor support sucks and needs more work. I wanted to check just in case you used something special I did not notice.

**Comment by stsrki** [comment]
>  they both already know blazor support sucks and needs more work

🤣
