### ISSUE TITLE
DataGrid: Multiple Sorting doubt

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1726]
Hello @stsrki 
is this the expected behaviour for multiple sorting? 
`SortMode="DataGridSortMode.Multiple"`

I'm trying to filter by ID Desc, and then by "Estado" ASC. Should it not apply the ID Desc filter and then the "Estado" ASC on top of it cumulatively? In fact it doesn't seem to be doing anything at all. Or am I missing something or thinking wrongly about it?

However if I apply "Estado" ASC first and then by ID Desc it works as expected:

**Comment by stsrki** [comment]
Well, I think it's doing it like that. As far as I can see your IDs don't have duplicates so they are always sorted in either ASC or DESC. As a result, nothing else can be sorted in between.

If you would have duplicate IDs then sort would make sense in your case

| ID | Name |
|----|------|
| 10 | a    |
| 10 | b    |
| 10 | c    |
| 11 | a    |
| 12 | d    |
| 13 | e    |

**Comment by David-Moreira** [comment]
I see that explains, so it was something logical after all and it has to do with "common records"(duplicates). That's why first filtering by "Estado" would make it work. Since among the common records "Estado" it can then further sort by ID.
Thanks for your help and fast response @stsrki.
Closing issue.
