### ISSUE TITLE
DataGridColumn TItem Field does not support inherited interface types

### ISSUE THREAD

**Issue by alexR148** [stsrki/Blazorise#1731]
**Describe the bug**
If TItem is type of inherited interface, it is not possible to access the fields of the base interface. 

**To Reproduce**

1. Make sure IEmployee is an inherited interface

```
public interface IPerson
    {
        int ID { get; set; }
        string Name { get; set; }
    }
    
    public interface IEmployee : IPerson 
    {
        string Organization { get; set; }
    }
```
2. Try to access a field in the base interface
`<DataGridColumn TItem="IEmployee" Field="Name" Caption="Name"  Editable="true" />`

3. Run. 
4. An exception is thrown indicating that the 'Name' field does not exist.

**Comment by stsrki** [comment]
That should definitely work. Thanks for reporting it!

**Comment by alexR148** [comment]
Maybe this peace of code will help you

`
 public static class Filterextension
    {
        public static IEnumerable<PropertyInfo> GetPublicProperties(this Type type)
        {
            if (!type.IsInterface)
                return type.GetProperties();

            return (new Type[] { type })
                   .Concat(type.GetInterfaces())
                   .SelectMany(i => i.GetProperties());
        }

        public static object getPropertyValue<U>(U obj, string propName)
        {
            var props = GetPublicProperties(typeof(U));
            var prop = props.Where(prop => prop.Name == propName).FirstOrDefault();
            return prop.GetValue(obj, null);
        }
    }
`
