### ISSUE TITLE
NumericEdit with steps button

### ISSUE THREAD

**Issue by d-oit** [stsrki/Blazorise#1733]
Current implentation has no button up/down steps

What is the best way for the implementation? Use html <button> or the Blazorise Button Control? 

**razor**:

```
<span @ref="@ElementRef" style="@Style" @attributes="Attributes" class="@StyleNames" id="@ElementId">
        <input @ref="@input" inputmode="numeric" class="@ClassNames" style="input-spinner @StyleNames" placeholder="@Placeholder" disabled="@Disabled" readonly="@ReadOnly" size="@VisibleCharacters" step="@Step" pattern="@Pattern" value="@CurrentValueAsString" @onchange="@OnChangeHandler" @oninput="@OnInputHandler" @onfocus="@OnFocus" @onfocusin="@FocusIn" @onfocusout="@FocusOut" @attributes="@Attributes" />
        <Button Class="spinner-button spinner-up" Clicked="@((args) => UpdateValueWithStep(true))" tabindex="-1"><Icon Name="IconName.ArrowUp"></Icon></Button>
        <Button Class="spinner-button spinner-down" Clicked="@((args) => UpdateValueWithStep(false))" tabindex="-1"><Icon Name="IconName.ArrowDown"></Icon></Button>
    </span>

```

**cs**

```
 private async System.Threading.Tasks.Task UpdateValueWithStep( bool stepUp )
        {
            if ( Disabled || ReadOnly )
            {
                return;
            }

            var step = Step.GetValueOrDefault(1);

            var valueToUpdate = Value != null ? Convert.ChangeType( Value, typeof( decimal ) ) : (decimal)Convert.ChangeType( default( decimal ), typeof( decimal ) );

            var newValue = ( (decimal)Convert.ChangeType( valueToUpdate, typeof( decimal ) ) ) + (decimal)Convert.ChangeType( stepUp ? step : -step, typeof( decimal ) );

            var hasMax = Converters.TryChangeType<decimal>( Max, out var max );
            var hasMin = Converters.TryChangeType<decimal>( Min, out var min );
            
                if (( hasMax && ( newValue > max )) || (hasMin && ( newValue < min )) || object.Equals( Value, newValue ) )
                {
                    return;
                }

            Converters.TryChangeType<string>( Max, out var newStringValue );
            await SetValue( newStringValue );

            StateHasChanged();
        }
```

**Comment by stsrki** [comment]
@d-oit Using `<input type='number' />` is the easiest, since it's natively supported by the browsers. But you will have to implement validations and any other logic if you would like to use it within Blazorise.

Your example from above could work, although you're still using a regular `<input>`. You should instead use a `<NumericEdit>`. Obviously, you still need to adjust CSS for spin buttons to appear right. This will probably be something that I will also implement in the future.

**Comment by d-oit** [comment]
@stsrki Already changed NumericEdit with the code:

![image](https://user-images.githubusercontent.com/6849456/105189217-05955880-5b35-11eb-8543-4c6696d1ea1e.png)

**Comment by d-oit** [comment]
If you are already changed the numeric blazorise control i could wait for your changes :-)

**Comment by stsrki** [comment]
Still didn't change it. It's on the list.

I find this that is exactly the same as we want to have: https://demos.devexpress.com/blazor/SpinEdit

**Comment by stsrki** [comment]
Also, https://codepen.io/Thomas-Lebeau/pen/csHqx

**Comment by d-oit** [comment]
@stsrki  My working changes without css:  https://github.com/d-oit/Blazorise/commit/a1217781ac668605e6b2fc0472e2c3361d5662bb

Could you take over the css / naming conventation part? On Sunday or next week i could write the unit test part.

ToDo 
- [ ] CSS
- [ ] Unit Test

**Comment by stsrki** [comment]
All new work should go from dev093 branch. Also, please remember that the sam functionality must be implemented for all providers, not just for bootstrap.

**Comment by stsrki** [comment]
Harder than I anticipated it would be but it is finally done.

![image](https://user-images.githubusercontent.com/900302/114725051-787d2c80-9d3c-11eb-92e4-2e841e78483a.png)

It will be available with the next preview.

**Comment by d-oit** [comment]
@stsrki  Good job.
shame on me at all - i forgot to publish my code

Atm i use my own control based on the NumericEdit with the Addon component and plus/minus for better mobile / touch experience. Like this:
https://shaack.com/projekte/bootstrap-input-spinner/ 

For read-only / disabled i don't show the icons. 
an option would be nice:
https://docs.devexpress.com/Blazor/DevExpress.Blazor.DxSpinEdit-1#hide-spin-buttons

**Comment by stsrki** [comment]
I forgot about readonly 🤦‍♂️

Going to fix it!

**Comment by d-oit** [comment]
BTW - i changed the bunit unit test with the keys up / down:

https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Tests/Components/NumericEditComponentTest.cs

https://bunit.egilhansen.com/api/Bunit.Key.html#Bunit_Key_Up

element.KeyPress(Key.Up);
