### ISSUE TITLE
Clicked event isn't firing if `BarLink` has property `To` set

### ISSUE THREAD

**Issue by Morasiu** [stsrki/Blazorise#1734]
**Describe the bug**
`Clicked` event is not firing in `BarLink` if `BarLink` has `To` property set. Is it intended behaviour?

**To Reproduce**
Steps to reproduce the behaviour:

I mean you can see in the source code that clicked event is not assigned. 

```csharp
    @if ( To != null )
    {
        <Blazorise.Link Class="@ClassNames" Style="@StyleNames" To="@To" Target="@Target" Title="@Title" Match="@Match" Attributes="@Attributes">
            @ChildContent
        </Blazorise.Link>
    }
    else
    {
        <a class="@ClassNames" style="@StyleNames" title="@Title" @onclick="@ClickHandler" @attributes="@Attributes">
            @ChildContent
        </a>
    }
}

```

**Expected behaviour**
`Clicked` event should be firing (I guess?)

**Additional context**
I can make a PR and help develop `Blazorise` if needed :)

**Comment by stsrki** [comment]
This was done intentionally. When `<a href>` is defined, once the link is clicked it will navigate to the URL. And click in that case has little context.

It's an easy change if that is desired but most of the time I had more problems when clicking and href are both present.

**Comment by Morasiu** [comment]
`Blazorise.Link` has `Clicked` property so it would be nice to have consisted behaviour with `BarLink` and their `Clicked` property. 

Also, I was going to use that `Clicked` property in my project :)

**Comment by stsrki** [comment]
It was done a long time ago so I had to look it up. You're right it really has a `Clicked` event. Maybe it wouldn't hurt to have it on all component 🤔

**Comment by Morasiu** [comment]
I can work on it and a even add a test if you want :)

**Comment by stsrki** [comment]
Sure, that would be great :)

Just don't forget to follow [CONTRIBUTING](https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md) guide. A lot of people fail to do it.. 😅
