### ISSUE TITLE
'form-control' class appended twice for Components that inherit BaseTextInput<TValue>

### ISSUE THREAD

**Issue by Jimmys20** [stsrki/Blazorise#1736]
Hi,

BootstrapClassProvider.cs has the line:
`public override string DateEdit() => "form-control";`

but because DateEdit Component inherits from BaseTextInput<TValue> it already gets the form-control class from:
`public override string TextEdit( bool plaintext ) => plaintext ? "form-control-plaintext" : "form-control";`

So in the end the generated html element has the 'form-control' class twice.
![Capture](https://user-images.githubusercontent.com/34100964/105366414-fdf2b400-5c07-11eb-9c1d-0bb63a80cc2f.PNG)

This is probably not breaking anything in the functionality. It's just an observation I made and thought I should share.

**Comment by stsrki** [comment]
You're right. While not breaking anything it shouldn't still generate duplicate names. Going on the list!
