### ISSUE TITLE
tooltip - detect page width

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1739]
Is there a way to detect the page boundaries and show the tooltip completely?

![image](https://user-images.githubusercontent.com/12803050/105417200-081dae00-5c1a-11eb-8308-532172cc631c.png)

**Comment by stsrki** [comment]
Probably yes, but it's a complex component so I will need to investigate it more.

With quick inspections I modified this and it seems to work:
```
[data-tooltip]:not(.is-loading)::before, [data-tooltip]:not(.is-disabled)::before, [data-tooltip]:not([disabled])::before
{
  left: 100%;
}
```

You can now proceed from here and add custom `media` breakpoints.

**Comment by drma-dev** [comment]
It didn't work or I don't think I understood.

My knowledge of CSS is not advanced.

**Comment by drma-dev** [comment]
@stsrki

**Comment by stsrki** [comment]
> It didn't work or I don't think I understood.
> 
> My knowledge of CSS is not advanced.

Just copy paste the css code from above into your `site.css` and it should work.

**Comment by drma-dev** [comment]
Yes, I did that part, but it doesn't work alone.

I was referring to the second thing you mentioned: custom media breakpoints

**Comment by drma-dev** [comment]
```
[data-tooltip]:not(.is-loading).b-tooltip-fade::before, [data-tooltip]:not(.is-loading).b-tooltip-fade::after, [data-tooltip]:not(.is-disabled).b-tooltip-fade::before, [data-tooltip]:not(.is-disabled).b-tooltip-fade::after, [data-tooltip]:not([disabled]).b-tooltip-fade::before, [data-tooltip]:not([disabled]).b-tooltip-fade::after {
    left: 100% !important;
}
```
I think I understand. My code was different.

But how to solve this when the component is on the right side. I tried with right: 100%, but it didn't work.
![image](https://user-images.githubusercontent.com/12803050/107118983-485c6d80-6863-11eb-98b2-6c6a7038c9f1.png)
