### ISSUE TITLE
Blazor Server - Version 0.9.3-preview6 not working

### ISSUE THREAD

**Issue by AlexTeixeira** [stsrki/Blazorise#1744]
**UseBootstrapProviders**  is not accessible from **IApplicationBuilder.ApplicationServices**.

Migrate from 0.9.2.5 to 0.9.3-preview6 in net5 application

![image](https://user-images.githubusercontent.com/6555080/105580662-0117ac80-5d8e-11eb-9db0-68e085b7e52a.png)

**Comment by stsrki** [comment]
Use methods are obsolete from 0.9.3. You should just remove those.

**Comment by AlexTeixeira** [comment]
Hi, 

I remove the lines and now project does not work anymore

![image](https://user-images.githubusercontent.com/6555080/105635946-1102bf80-5e66-11eb-8b4c-a54608129df1.png)
![image](https://user-images.githubusercontent.com/6555080/105635958-18c26400-5e66-11eb-8a7d-72e9ae9468c8.png)

**Comment by stsrki** [comment]
Did you convert from 3.1 to .Net 5? Maybe you're missing `Microsoft.NET.Sdk.BlazorWebAssembly` defined in a csproj file. Look through our demo projects for reference on what you might be missing https://github.com/stsrki/Blazorise/tree/dev093/Demos

**Comment by AlexTeixeira** [comment]
My Bad, I was making another change.... My project compile, I need to use the french language now 👍
