### ISSUE TITLE
RichTextEdit collapses at async initialization

### ISSUE THREAD

**Issue by DDDenisSobek** [stsrki/Blazorise#1752]
**Describe the bug**
RichTextEdit will throw exception, if editor content is loaded asyncron.

**To Reproduce**
1. Build this page:
```
@page "/Test"
@using Blazorise.RichTextEdit
<h3>TestPage</h3>
<RichTextEdit @ref="_RichTextEdit" 
              ContentChanged="@ContentChanged"
              PlaceHolder="Write here!"
              SubmitOnEnter="false">
    <Editor>
        @((MarkupString) _MyContent)
    </Editor>
</RichTextEdit>

@code {
    private RichTextEdit _RichTextEdit;
    private string _MyContent;
    private string _NewContent;

    protected async override Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Task.Delay(1000);
        _MyContent = "<p>Test</p>";
    }

    private async Task ContentChanged()
    {
        if (_RichTextEdit == null)
            return;
        _NewContent = await _RichTextEdit.GetHtmlAsync();
    }
}
```
2. Open this page.

**Expected behavior**
Asyncron loading of content should not throw exception and should work like syncron.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65016836/105973080-99fb4000-608c-11eb-870a-7bc1dda12c9a.png)
![grafik](https://user-images.githubusercontent.com/65016836/105973048-8ea81480-608c-11eb-975b-b8d398d4ebf2.png)

**Comment by DDDenisSobek** [comment]
@stsrki Hey, could you reproduce the problem?

**Comment by stsrki** [comment]
@DDDenisSobek Sorry for not getting to this sooner. Yes, I was able to reproduce.

@njannink Can you look at this, please?

**Comment by njannink** [comment]
Yes I will have a look. Can't promise anything for this and next week depending how deep this rabbit-hole goes :)

**Comment by njannink** [comment]
@DDDenisSobek it has nothing to do with async/sync. The problem is that changing the editor-content after it has been rendered isn't working. It's something from Blazor, because it can't seem to find it's parent element to render the content markup. I have been trying to fix this behavior but no luck so far. Maybe for your case it might make more sense to use the `SetHtmlAsync ` method. That one works fine.

I will try to fix the render of the content markup after first render.

**Comment by DDDenisSobek** [comment]
> 
> 
> @DDDenisSobek it has nothing to do with async/sync. The problem is that changing the editor-content after it has been rendered isn't working. It's something from Blazor, because it can't seem to find it's parent element to render the content markup. I have been trying to fix this behavior but no luck so far. Maybe for your case it might make more sense to use the `SetHtmlAsync ` method. That one works fine.
> 
> I will try to fix the render of the content markup after first render.

`SetHtmlAsync` works, if delay will be high enough. At a delay of 200ms i get sometimes the error "Error: System.InvalidOperationException: RichTextEdit not initialized yet".
```
 protected async override Task OnInitializedAsync()
    {
            await base.OnInitializedAsync();
            await Task.Delay(200);
            _MyContent = "<p>Test</p>";
            await _RichTextEdit.SetHtmlAsync(_MyContent);
    }
```
![grafik](https://user-images.githubusercontent.com/65016836/108349058-d5e47980-71e2-11eb-9b61-bbcad1eb63f9.png)

**Comment by stsrki** [comment]
@DDDenisSobek You should do it in `OnAfterRenderAsync`.

**Comment by DDDenisSobek** [comment]
> 
> 
> @DDDenisSobek You should do it in `OnAfterRenderAsync`.
@stsrki 
I also get the error.
```
protected async override Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Task.Delay(200);
        _MyContent = "<p>Test</p>";
    }

    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        await _RichTextEdit.SetHtmlAsync(_MyContent);
    }
```
![grafik](https://user-images.githubusercontent.com/65016836/108351531-f104b880-71e5-11eb-85bc-1d56f8acc5fd.png)
It also does not work, when i do it after first render.
```
protected async override Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Task.Delay(200);
        _MyContent = "<p>Test</p>";
    }

    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if(!firstRender)
            await _RichTextEdit.SetHtmlAsync(_MyContent);
    }
```

@stsrki and @njannink I want to say thanks for your commitment. I hope, that i do not bug you.

**Comment by njannink** [comment]
Maybe I will have to remove the Editor fragment. Updating the editor content through the renderfragment after the RTE has been rendered doesn't work. This because the QuillJS library replaces this content with something of it's own. If you then update it Blazor cannot find the original data in the Html tree causing the exception seen.

The SetxxxxAsync should work as expected. I will have a look why it's throwing the exception

**Comment by njannink** [comment]
@stsrki I found a fix for all of the exceptions above and also a workaround to support content updates. Have a look at my changes. I added a helper method to BaseComponent for async OnAfterRender with return values
