### ISSUE TITLE
Adding another UI

### ISSUE THREAD

**Issue by c0fe** [stsrki/Blazorise#1756]
I am looking into adding another UI, specifically I am looking into adding Core UI into Blazorise but I didn't see any documentation in regards to what are the best practices to go about this. Is there something I missed?

**Comment by stsrki** [comment]
From what I can see Core UI is based on Bootstrap, so simply replacing `bootstrap.css` files in your `index.html` should work.

On the other hand, if you want to add Core UI as an additional provider for Blazorise, eg. `Blazorise.CoreUI` then you can follow the implementation of our `Blazorise.Material` project.

**Comment by c0fe** [comment]
@stsrki it is based on bootstrap but it has a lot of unique named css elements as well though.

**Comment by stsrki** [comment]
In that case, the second option is the right way to do it. I just tried replacing `bootstrap.min.css` with `coreui.min.css` just to see what would happen and I would say it works for the most part. Somewhere around 80-90%, it is OK. The last 10-20% you should have to cover with `ClassProvider` and/or custom CSS styles.

Note that it is not an easy task but considering that almost everything is already implemented with Bootstrap it would be a lot easier than doing a completely new provider.
