### ISSUE TITLE
Preview4 to Preview8: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1780]
Upgraded from v0.9.3-preview4 to preview8. 

In the morning I upgraded and it seemed to work. But later in the day, I suddenly got the error:

`System.UriFormatException: Invalid URI: The hostname could not be parsed.`

It came out of nowhere. I could not even start the application. I tried deleting my .vs folder (as is the common recommendation) and restarting. As a last resort, I rolled back Blazorise to preview4 and it worked again.

![image](https://user-images.githubusercontent.com/4267021/106598134-58074980-6525-11eb-81d7-3247ee0c198a.png)

**Comment by stsrki** [comment]
That's really strange. Which parts did you change during the update? Maybe you missed something. You can always check in our demo projects for reference: https://github.com/stsrki/Blazorise/tree/dev093/Demos

**Comment by stevenlupo** [comment]
I already use the demo projects for reference. 

I don't understand what you mean by "change during the update? Maybe you missed something". Missed what, for example? I updated every Blazorise NuGet package I have to the latest preview.

**Comment by stsrki** [comment]
Well, I meant what parts of your projects did you change during the update process? It's hard to guess or know without any example or code. That's why I said to look at demo projects and see what are the differences between them and your project.

**Comment by stevenlupo** [comment]
I'm on to something. I think it has to do with other Core packages that I updated in addition to Blazorise. This "old code" was working fine but stopped after the package updates.

Maybe you can help. I was doing this:

`return LocalRedirect(Url.Content("~/")`

after I authenticate in `Login.cshtml.cs` (it's the only way I can authenticate with cookies). But now, evidently, that's bad and is causing the exception.

How can I redirect without causing the exception?

**Comment by stsrki** [comment]
I just checked one of my projects and I just do `return LocalRedirect("/")`.

**Comment by stevenlupo** [comment]
Did more testing. This definitely has something to do with Blazorise and not other packages. I can reliably duplicate the exception when using Preview8, if I roll back to Preview4, the problem goes away.

See the stack trace in the image I gave. See the `Blazorise.Link.OnParametersSet()`? Could that have something to do with it?

Blazorise doesn't seem to like some code that is running after I authenticate. And it's probably in my `MainLayout.razor` page. I'm trying to pin it down.

**Comment by stevenlupo** [comment]
Found the problem! Preview8 definitely broke it, but maybe I shouldn't be doing it the way I am, but it was the only way I could get it to work. Here's the offending code:

```
<BarDropdownItem href="mailto:test@example.com;test2@example.com;test3@example.com?subject=test subject">
     click link to email
</BarDropdownItem>
```
The idea was, I wanted the user to click a link to start a new email. I couldn't use the `To` attribute because (if I remember correctly) it could not parse the `mailto` (invalid uri error). But it worked with an `href`. Yea, it looks kinda hacky.

But what's the right way? It's in the middle of a `BarDropDownMenu` so it has to blend in.

**Comment by stsrki** [comment]
The problem is in the `Link `component, on line with `NavigationManager.ToAbsoluteUri( To ).AbsoluteUri`. Since you're giving it a bunch of emails separated by `;` it doesn't know what to do with it.

```cshtml
<BarDropdownItem To="mailto:test@example.com;test2@example.com;test3@example.com?subject=test subject">
     click link to email
</BarDropdownItem>
```

If I use just one email it seems to work

```cshtml
<BarDropdownItem To="mailto:test@example.com?subject=test subject">
    click link to email
</BarDropdownItem>
```

**Comment by stsrki** [comment]
Note for me! This should fix it:

```cs
string ParseAbsoluteUri( string relativeUrl )
{
    try
    {
        if ( relativeUrl == null )
            return string.Empty;

        return NavigationManager.ToAbsoluteUri( To ).AbsoluteUri;
    }
    catch
    {
        return string.Empty;
    }
}
```

**Comment by stevenlupo** [comment]
It needs to be multiple emails though. I might just build a form instead and just send the email through the back end. But a regular `<a href=...></a>` allows multiple emails with the semi-colon, so this should to.

You can close this if you want because I don't consider this a showstopper for me.

thanks.

**Comment by stsrki** [comment]
I can put it on the list for the next milestone.
