### ISSUE TITLE
Menu Colors

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1782]
Just upgraded from Preview4 to Preview8.

Did something happen to the menu colors? I don't even know how to write this one up. I'm using `<BarItem>` and `<BarDropdown>` and the coloring is all messed up. Are there new behaviors we're supposed to know about?

**Comment by stsrki** [comment]
Can you show an example?

**Comment by stevenlupo** [comment]
It's probably because I set custom color options as shown below, but I'm not sure why these are a problem.

```
    private Theme theme = new Theme
    {
        ColorOptions = new ThemeColorOptions
        {
            Primary = "#14558F"
        },
        BackgroundOptions = new ThemeBackgroundOptions
        {
            Primary = "#14558F",
            Dark = "#14558F"
        },
        BarOptions = new ThemeBarOptions
        {
            HorizontalHeight = "75px"
        }
    };
```

**Comment by stsrki** [comment]
Screenshot?

**Comment by stevenlupo** [comment]
The image shows two screenshots side-by-side. The colors are changing on-the-fly after I click another menu option. It seems unpredictable. here's the sample menu:

```
                                <BarItem>
                                    <BarDropdown>
                                        <BarDropdownToggle>Reports</BarDropdownToggle>
                                        <BarDropdownMenu >
                                            <BarDropdownItem To="">
                                                Option 1
                                            </BarDropdownItem>
                                            <BarDropdownItem To="">
                                                Option 2
                                            </BarDropdownItem>
                                            <BarDropdownItem To="">
                                                Option 3
                                            </BarDropdownItem>
                                            <BarDropdownItem To="">
                                                Option 4
                                            </BarDropdownItem>
                                        </BarDropdownMenu>
                                    </BarDropdown>
                                </BarItem>
```
![image](https://user-images.githubusercontent.com/4267021/106654375-134fd280-6566-11eb-8aae-7475b9cd9501.png)

This isn't the way I originally had it. I had Classes assigned to get the look I wanted, but that was so messed up after the update I removed them to see how it would look. I can adjust the classes if something changed, but it doesn't seem to be working correctly.

**Comment by stsrki** [comment]
Can you inspect and see what is causing the style issue?

As far as I remember I have only changed `.dropdown-item` color recently.

**Comment by stevenlupo** [comment]
I figured it out. If you look at the screenshot, I was using `To=""` as a placeholder. That was causing it. I replaced it with `To="#"` and it fixed it. 

But I think `To=""` should work because I think it might be common for someone to do this in the beginning not realizing it makes a difference. But if you want to close it I'm fine with that.

**Comment by stsrki** [comment]
Ah, I know what is wrong now. Recently I changed all _linkable_ items to use `Link` component. And when `Link` detects the current URL is the same as in `To` it will apply the `active` classname to the item.

Good catch, I should have tested it better 😅

**Comment by stsrki** [comment]
I was thinking more about this and I think it works as expected. When you define `To=""` as an empty string it will get **active** when it detects a _homepage_ URLs. And `To=""` also means to navigate to _homepage_ when you click on a link.
