### ISSUE TITLE
I am requesting to have AppBar, Drawer component

### ISSUE THREAD

**Issue by sorainnosia** [stsrki/Blazorise#1783]
**Is your feature request related to a problem? Please describe.**
When I want to start with Blazorise, I start from designing menu template razor file, but cant find any sample of how to make a Drawer with navigation link to start with.

**Describe the solution you'd like**
I would like to have an AppBar and Drawer component, where it interacts with one another. For example the AppBar has a hamburger icon, clicking on it will popup Drawer menu on left or right side in overlay mode. Clicking on content area, will dismiss the overlay Drawer and the content didn't get pushed/squished by menu due to overlay. This is important because this is how menu behaves in Android App.

The Demo sample show that content getting squished or push by menu, which is kind of weird because the content get animated (text wrapping down) for wrong reason.

Probably author can make Drawer having attribute for options of overlay or squish content. Also making options when the Drawer is collapse, whether to keep showing the Icons or totally hide the Drawer.

Also AppBar title will be hidden when overlay (or in mobile) and will push when squish (optional in desktop, desktop can have overlay too). And options for Drawer to appear from left or right side of the screen. Right for example for navigation related to User Account/Setting/Privacy/Change Password. While left will be the menu to uses the app's different modules.

### Additional context
I saw other creators created this features, but hoping Blazorise to have the same because I see Blazorise has more other features/components and would like to try out.

**Comment by stsrki** [comment]
Hi @sorainnosia. There is no plan to create the components that you requested. The reason is that most of these features are already available with our Bar component? Your _AppBar_ is basically `Bar` with `Horizontal` mode, and _Drawer_ is `Bar` with `Vertical` mode. The easiest for you is to look at our demo app and then adjust what you need to https://github.com/stsrki/Blazorise/tree/master/Demos/Blazorise.Demo

Also, look at the documentation to learn about [Layout](https://blazorise.com/docs/components/layout/) and more about [Bar](https://blazorise.com/docs/components/bar/) components.

**Comment by sorainnosia** [comment]
> Hi @sorainnosia. There is no plan to create the components that you requested. The reason is that most of these features are already available with our Bar component? Your _AppBar_ is basically `Bar` with `Horizontal` mode, and _Drawer_ is `Bar` with `Vertical` mode. The easiest for you is to look at our demo app and then adjust what you need to https://github.com/stsrki/Blazorise/tree/master/Demos/Blazorise.Demo
> 
> Also, look at the documentation to learn about [Layout](https://blazorise.com/docs/components/layout/) and more about [Bar](https://blazorise.com/docs/components/bar/) components.

Oh never know the Bar component has so many options available. Even the popup overlay mode also exist.

Thanks, will try to test out my app using blazorise. Thanks

**Comment by stsrki** [comment]
Yep, our Bar component is a beast. All thanks to @MitchellNZ help 💪
