### ISSUE TITLE
Sizing for DataGrid Filter Box

### ISSUE THREAD

**Issue by pvagnini** [stsrki/Blazorise#1787]
Is it possible to apply a Size property to the Filter Boxes similar to what is allowed for other controls such as TextEdit.

Currently it is possible to set the font-size that is inherited by most of the DataGrid, but if the font-size is set to say 75% to get more data on the page the Filters remain at 100% and so look out of place.

Great set of controls. Thanks for your help

Regards
Paolo

**Comment by stsrki** [comment]
You can use `FilterTemplate` and create your own input fields with Size parameter

```
<DataGridColumn TItem="Employee" Field="@nameof( Employee.FirstName )" Caption="First Name" Validator="@CheckFirstName" Editable="true">
    <FilterTemplate>
        <TextEdit Size="Size.Small" Placeholder="Search name" Text="@context.SearchValue" TextChanged="@(v=> context.TriggerFilterChange(v))" />
    </FilterTemplate>
</DataGridColumn>
```

**Comment by pvagnini** [comment]
Thankyou this works great.
