### ISSUE TITLE
DataGrid problems with nested fields

### ISSUE THREAD

**Issue by paulosdfigueiredo** [stsrki/Blazorise#1788]
**Describe the bug**
I'm having problems with nested properties after update to preview8. 

I get an ArgumentException with the message "Cannot detect the member of {item.Type}".

**To Reproduce**
To reproduce it in demo i added a new property to Employee.

```
public class Employee
{
	public Boss ReportsTo { get; set; }
}

public class Boss
{
	public string FirstName { get; set; }
}
```
And then added new column to datagrid

`<DataGridColumn TItem="Employee" Field="ReportsTo.FirstName" Caption="Reports To" Editable="false" />`

**Expected behavior**
Should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/50837250/106889182-9183b480-66df-11eb-945f-d373f28aebfa.png)

**Additional context**
I suspect i found the problem https://github.com/stsrki/Blazorise/commit/0b7f43b1359d70170969b2c8c43a00bdfa3d40d9#r46727285

**Comment by stsrki** [comment]
In your example, Boss is not inherited from Employee class. Is that a typo?

**Comment by stsrki** [comment]
Sorry, I misunderstood it. Ignore my previous comment 😅
