### ISSUE TITLE
Setting background color for entire website?

### ISSUE THREAD

**Issue by Filiecs** [stsrki/Blazorise#1799]
I feel like this is really simple and I'm just missing something really obvious, but I have looked everywhere for how to set the background color for an entire website using the Blazorise themes and I just cannot figure it out. Setting it in css or using Style is trivial, but is there an intended way to do this?

**Comment by stsrki** [comment]
There is no way to set the entire background-color for `body` (or website) in Blazorise. With theming you get the option to quickly define standard colors (primary, danger, success, etc.) for buttons, alerts, etc., without going over all the manual work yourself.

For everything else, you must use custom CSS.

**Comment by Filiecs** [comment]
Thanks for the quick answer.
