### ISSUE TITLE
TreeView: SelectedClass

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1803]
Hello @stsrki 
I've also started using the Tree view for a use case I have.
I noticed that the selected class is already put there by Blazorise, In the case of bootstrap, bg-primary. 
Would be nice to just have a SelectedClass to set my own freely. Otherwise I have to endup overriding bg-primary.

**Comment by stsrki** [comment]
I agree, there should be an API to configure TreeView.

It was done by a community member some time ago and still needs some optimizations. I can do it as part of #994

**Comment by David-Moreira** [comment]
@stsrki Mind if I grab these two:

- "Would be nice to just have a SelectedClass to set my own freely. Otherwise I have to endup overriding bg-primary."
- "It would be nice to have a way to customise the icons for opening and closing a node. For example, I would like to replace the plus and minus icons for a right and down arrow."

Personally I'd like to have at least these two features soon to further customize these simple things on an ongoing project that I have. I would grab the whole #994 but I'm not quite in a mood to be figuring out how validation internals work in Blazorise... :X

**Comment by stsrki** [comment]
I already started work on #994 so if you wish you can only focus on SelectedClass implementation. 

It's a big change so no need for you to do it all.
