### ISSUE TITLE
DataGrid Sorting for large data

### ISSUE THREAD

**Issue by rubeesh** [stsrki/Blazorise#1807]
I am trying to use Blazorise DataGrid extension to load large data.
I use ReadData  handler to call my api endpoint. I am trying to pass current sort column, search text and current current page no to my api end point.

It works fine with server side paging and search, **but i am confused how can i get the current sort column and direction**

```
      private async Task ReadData (DataGridReadDataEventArgs<ItemsDto>  args)
        {
            var currentPage = args.Page;
            var currentSort =  "";  ///To be completed
            var response = await http.GetAsync(
                          $@"Items?filter={searchValue}&skip={currentPage-1}&top=12&orderBy={currentSort}");
            if (response.IsSuccessStatusCode)
            {
                var pagedModel = await response.Content.ReadFromJsonAsync<PagedList<ItemsDto>>();
                count = pagedModel.Count.Value;
                items = pagedModel.Items;
            }
            else
            {
                /// error handling
            }
            isBusy = false;
            StateHasChanged();
        }
```

**Comment by Merhex** [comment]
Hi rubeesh, I might be a little late to the party and hope you found a solution already, but in the `DataGridReadDataEventArgs<ItemsDto>  args` you have access to the Columns field. Where you have access to all columns in the grid. which is of type `DataGridColumnInfo`.

Which in turn you can take out any information you need.

Here is a small example which I used in my own project, I take, in your case, the `args.Columns` into this method and take out the state of the columns.

```C#
private static IEnumerable<ColumnState> GetColumnState(List<DataGridColumnInfo> columns)
{
    foreach (var column in columns)
    {
        yield return new ColumnState
        {
             Direction = column.Direction,
             Field = column.Field
        };
    }
}
```

Here is how the ColumnState class looks like, simple but what I need.
```C#
public class ColumnState
{
    public string Field { get; set; }
    public SortDirection Direction { get; set; }
}
```

**Comment by Merhex** [comment]
This in turn I convert to a suitable query string, that your API needs.

**Comment by Merhex** [comment]
```C#
        public string GetSortQueryString()
        {
            if (Sortables.Count is 0) return "";

            var sortList = new List<string>();
            foreach (var sortable in Sortables)
            {
                var direction = sortable.Descending ? " desc" : null;

                sortList.Add($"{sortable.PropertyName}{direction}");
            }

            return "sortBy=" + string.Join(',', sortList);
        }
```

**Comment by rubeesh** [comment]
Tha

> This in turn I convert to a suitable query string, that your API needs.
> The sortable in this case is simply the same as column state, but I map the direction to be in descending sort order or not.
> In the backend I used Dynamic Linq Core which simply takes this string, and it's really easy to order.
> https://dynamic-linq.net/basic-simple-query
> 
> Hope this helps.
> 
> Par example:
> 
> ```cs
>         public string GetSortQueryString()
>         {
>             if (Sortables.Count is 0) return "";
> 
>             var sortList = new List<string>();
>             foreach (var sortable in Sortables)
>             {
>                 var direction = sortable.Descending ? " desc" : null;
> 
>                 sortList.Add($"{sortable.PropertyName}{direction}");
>             }
> 
>             return "sortBy=" + string.Join(',', sortList);
>         }
> ```

Thanks for the response. 
Actually i took the same approach
