### ISSUE TITLE
How to using DataGrid editing function

### ISSUE THREAD

**Issue by yorytang** [stsrki/Blazorise#1810]
I have read the documentation and don't know how to edit data in grid row.
the doc specify "Inline" mode but how to set the propertiy?
---------
The grid can work in two different editing modes that can provide different user experiences.

Form editing is done in the internal DataGrid form
Inline editing is done in the current row
Popup editing is done in the the modal dialog

**Comment by stsrki** [comment]
Look at the demo for reference https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor

**Comment by yorytang** [comment]
thanks
