### ISSUE TITLE
Primary Color Not Changing for Hero

### ISSUE THREAD

**Issue by catriname** [stsrki/Blazorise#1813]
**Describe the bug**
Theming color change to "hero" style not working.  (Bulma)

**To Reproduce**
1. Set primary as instructed per Blazorise docs
Use (as per Bulma docs):
```csharp
<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      Primary hero
    </p>
    <p class="subtitle">
      Primary subtitle
    </p>
  </div>
</section>
```

**Expected behavior**
primary green color should change to color specified in App.razor

Example Repo:  https://github.com/catriname/BlazoriseTest

**Comment by stsrki** [comment]
Fixed.

For future reference, the `hero` is named Jumbotron in Blazorise so you should use that instead of writing manual Bulma tags.

https://blazorise.com/docs/components/jumbotron/
