### ISSUE TITLE
DataGrid Row Height

### ISSUE THREAD

**Issue by pvagnini** [stsrki/Blazorise#1814]
I am styling with a smaller font size to fit more data onto large screens.
Wraping the DataGrid in a <div> with font-size set to 75% works fine, however the row height remain the same.

Is there anyway to reduce the row heights in the datagrid to match the font-size please

Regards
Paolo

**Comment by stsrki** [comment]
Maybe this? #1787

**Comment by stsrki** [comment]
PS. I think you can also target header with CSS:

```css
table thead tr th{
  font-size: .75rem;
}
```
