### ISSUE TITLE
DataGrid: Able to fire multiple edit/delete commands of the same type when Modal is set

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1815]
Hello @stsrki 
Noticed a strange one. 
1. Datagrid set to modal
2. Click Edit or Delete
3. Modal opens with edit or delete content
4. You can press Spacebar or Enter, and since the button is still focused on the background, it keeps triggering new instances of the modal.

![image](https://user-images.githubusercontent.com/22283161/107487857-8963c300-6b7e-11eb-9060-20dbc840665f.png)

I think we could have it so, if a modal is already open it won't open another one on top for these cases.
However, in the case of modals, and this is also a matter of accessibility, pressing tab for example, should only work on the modal inputs, you shouldn't be able to access the DOM behind the modal backdrop.

I saw a library solving this by using focus trap.

**Comment by stsrki** [comment]
We can solve it simply by adding `Autofocus="true"` to the first input component on modal.

**Comment by David-Moreira** [comment]
That seems fine.

I also have to apologize because I seem to have tested a custom modal of mine, and not the automatic from Datagrid by mistake, I just retested what happens on the datagrid one, is that it only keeps one open it seems, and that seems about correct. However, I can tab the background and still trigger edit modal for a different record for example.

There's also the question  about accessibility if you don't want to access the dom by tabbing.
I'm not sure if you'd like to consider the background dom tabbing or not. Probably the same happens with Blazorise.Modal?

At the very least there are workarounds, thanks.

**Comment by stsrki** [comment]
I guess that is just how browsers work. I'm not sure if it makes sense to lose too much time on that.

**Comment by David-Moreira** [comment]
@stsrki  That's fine then. It really does not seem a big bother if it already does not open more then one modal and there's the auto focus workaround.

So that's more to do if you want Blazorise to be as much user accessible as possible or not.

Closing issue. Thanks for your help as always. ^^
