### ISSUE TITLE
Getting "Microsoft.JSInterop.JSException: Chart is not defined" with pie chart

### ISSUE THREAD

**Issue by katiep23** [stsrki/Blazorise#182]
Using server-side blazor & only the chart extension, so I only manually copied over "blazorise.css," "blazorise, js," & "blazorise.charts.js" & added them in _Host.cshtml file.  Also added "services.AddEmptyProviders();" in the Startup.cs. But still getting error "Microsoft.JSInterop.JSException: Chart is not defined" on line 37 of blazorise.charts.js.

I also have `@using Blazorise.Charts` in my main _Imports.razor page. 

Any thoughts on what I may have been missing in setting up?  Thanks!!

**Comment by stsrki** [comment]
Have you included a chartjs script tag?

It should be placed after the `<app>` tag in the **_Host.cshtml**

`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>`

**Comment by katiep23** [comment]
Nope!  I only had `<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">`. That fixed it, thanks!

**Comment by stsrki** [comment]
I think you should be ok with just the blazorise.charts.js so you can remove blazorise.js
Other scripts are all required if you're using bootstrap.
