### ISSUE TITLE
User badge on left menu

### ISSUE THREAD

**Issue by jerpic** [stsrki/Blazorise#1820]
Hi @stsrki,

Hope you are doing well.

It's not a bug but a question.

What would be the best implementation for a "User badge" in the left menu like this picture?

![image](https://user-images.githubusercontent.com/8591455/107626045-8095ee80-6c5d-11eb-8ee0-485367747a91.png)

Best Regards,

**Comment by stsrki** [comment]
Basically, whatever works for you. You can't escape from doing manual adjustments

**Few examples**

```cshtml
<BarItem>
    <Figure Size="FigureSize.Is32x32" Padding="Padding.Is3.FromLeft">
        <FigureImage Source="https://adminlte.io/themes/v3/dist/img/user2-160x160.jpg" AlternateText="32x32" Style="border-radius:50%;" />
    </Figure>
</BarItem>
```

```cshtml
<BarItem>
    <div style="display: inline-block; padding-left: 1rem;">
        <Image Source="https://adminlte.io/themes/v3/dist/img/user2-160x160.jpg" style="height:auto; width:2.1rem; border-radius:50%;" />
    </div>
</BarItem>
```

**Comment by jerpic** [comment]
Thanks for your answer and reactivity!

I tried with that code, but I’m pretty sure it’s not the right way….
<BarItem>
   <Row>
       <Column Style="color: darkgray;border-bottom:solid;border-bottom-color:darkgray;border-bottom-width:1px;padding-top: 0.50rem;">
           <Figure Size="FigureSize.Is64x64" Padding="Padding.Is3.FromLeft" Margin="Margin.Is0">
               <FigureImage Source="https://adminlte.io/themes/v3/dist/img/user2-160x160.jpg" AlternateText="64x64" Style="border-radius:50%;"/>
           </Figure>
           FirstName LastName
       </Column>
   </Row>
</BarItem>

In fact, I’m really not satisfied with the render.

1 - The space between the image and the bottom border is too large.



2 - And when I resize the screen (ex : for tablet), I get that render which is very not good, the text « Firstname LastName » is still displayed and the bottom border is not resized (see the picture).



I will take any idea/suggestion and even code that you want to give me ;-)

Best Regards,

**Comment by jerpic** [comment]
Thanks for your answer and reactivity!

I tried with that code, but I’m pretty sure it’s not the right way….

`<BarItem>
   <Row>
       <Column Style="color: darkgray;border-bottom:solid;border-bottom-color:darkgray;border-bottom-width:1px;padding-top: 0.50rem;">
           <Figure Size="FigureSize.Is64x64" Padding="Padding.Is3.FromLeft" Margin="Margin.Is0">
               <FigureImage Source="https://adminlte.io/themes/v3/dist/img/user2-160x160.jpg" AlternateText="64x64" Style="border-radius:50%;"/>
           </Figure>
           FirstName LastName
       </Column>
   </Row>
</BarItem>`

In fact, I’m really not satisfied with the render.

![Attachment](https://user-images.githubusercontent.com/8591455/107634466-d40e3980-6c69-11eb-875a-18b7db864185.png)

2 - And when I resize the screen (ex : for tablet), I get that render which is very not good, the text « Firstname LastName » is still displayed and the bottom border is not resized (see the picture).

![Attachment-1](https://user-images.githubusercontent.com/8591455/107634502-e2f4ec00-6c69-11eb-8a10-7e639aee2711.png)

I will take any idea/suggestion and even code that you want to give me ;-)

Best Regards,
