### ISSUE TITLE
TextEdit FocusAsync "Event is already tracked" exception

### ISSUE THREAD

**Issue by Jimmys20** [stsrki/Blazorise#1823]
Hello, 

I'm trying Blazorise version 0.9.3-preview9 and I noticed an error when using TextEdit Focus and FocusAsync methods. I'm calling FocusAsync inside OnAfterRenderAsync using the TextEdit reference object as suggested [here](https://github.com/stsrki/Blazorise/issues/1730). I'm getting the error when I click the "reload page" button on my browser (chrome). This error doesn't seem to appear until version 0.9.3-preview6. It appears after 0.9.3-preview7 and onwards.

Repository with reproduction:
https://github.com/Jimmys20/BlazoriseAutofocusDemo

Exception I'm getting:
![Exception](https://user-images.githubusercontent.com/34100964/107636548-7a137100-6c75-11eb-8c87-c43da7bb4685.PNG)

**Comment by stsrki** [comment]
I'm also getting the error. Something is messing with input events, but I don't see a reason for now. Going on the backlog!

**Comment by Jimmys20** [comment]
Same error with simple html input and ElementReference class
https://github.com/dotnet/aspnetcore/issues/30070

It seems that this issue is not related to blazorise
