### ISSUE TITLE
Additional layouts/styles of material date picker

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#1824]
Is it possible to manipulate the way the date picker looks for material layout? I need a birthdate picker and so it should be possible to easily switch the year with have to click 12*40 times previous to get to 1980

**Comment by stsrki** [comment]
Do you mean like this?

![image](https://user-images.githubusercontent.com/900302/107659954-09298480-6c88-11eb-9643-83e68121e60b.png)

It's already done in 0.9.3

**Comment by njannink** [comment]
ok how can I turn that on?

**Comment by stsrki** [comment]
You need to get the preview Blazorise https://github.com/stsrki/Blazorise#try-preview

It's on by default.
