### ISSUE TITLE
Filter lag

### ISSUE THREAD

**Issue by Wolfenry** [stsrki/Blazorise#1825]
I have a grid with +50 columns, data is not massive, just 200 registers, so i don't use the Large Data method (api) but **when i search in the column filter, it lags my input**

1. Type fast in the filter of a big grid
2. See error

I expect that either works fluent (jquery datatables type) or have the capability to put some delay on it.

What i notice is that is a cursor problem or some. probably caused by the fast search or the resizing of the columns, btw, is there a way to keep column size after searching? everything rezises, making UX lose focus on data

**Comment by stsrki** [comment]
It's a known problem. In the latest preview, I have made many optimizations to make it less obvious but it can still happen. See this https://github.com/stsrki/Blazorise/issues/1429 and adjust your code based on it.

Closing since it's already on the list for more optimizations.
