### ISSUE TITLE
No way to style save and cancel buttons in datagrid form editing

### ISSUE THREAD

**Issue by devinbandara** [stsrki/Blazorise#1826]
![Capture24](https://user-images.githubusercontent.com/71271116/107691732-d4aecc00-6c79-11eb-898c-d4da9362fa1f.PNG)
![Capture23](https://user-images.githubusercontent.com/71271116/107691790-e7290580-6c79-11eb-8324-e93b139c16db.PNG)
I am attempting to style the "Save" and "Cancel" buttons in the edit form of my datagrid.

Any suggestions on how to do this? I have not been able to find where I can edit just these buttons. I can set a theme using the theme provider but then it will style all of my buttons.

**Comment by stsrki** [comment]
Look at the demo https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor#L119

Every command like EditCommandTemplate or CancelCommandTemplate can be customized.

**Comment by devinbandara** [comment]
Yes but when I add a class to it to add margins it does not get applied

**Comment by stsrki** [comment]
It should be applied

![image](https://user-images.githubusercontent.com/900302/107920169-cbb94580-6f6c-11eb-837f-5a30ac8d9944.png)

![image](https://user-images.githubusercontent.com/900302/107920196-d7a50780-6f6c-11eb-8a7a-91ef2683e7c1.png)
