### ISSUE TITLE
Carousel - Not working properly

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1831]
`string[] imageDataUriGallery = _profile.GetGalleryPhotos();`
```
<Carousel>
    @foreach (var item in imageDataUriGallery)
    {
        <CarouselSlide>
            <Image Source="@item" Display="Display.Block" Style="width: 100%;" />
        </CarouselSlide>
    }
</Carousel>
```
Now that it has 3 images, it hangs on the last one and doesn't show the others.
When I had two images, I was stuck too, but showing one image overlapping another.

```
<CarouselSlide Name="@Guid.NewGuid().ToString()">
    <Image Source="@item" Display="Display.Block" Style="width: 100%;" />
</CarouselSlide>
```
When I try to name it, an error occurs.
![image](https://user-images.githubusercontent.com/12803050/107787239-970b7b00-6d2d-11eb-93d2-322f22aadb3f.png)

What am I doing wrong?

**Comment by stsrki** [comment]
Slide Name must be persistent and not random. Also, SelectedSlide must be used `@bind-SelectedSlide="selectedImage"`.

Here is updated example:

```cshtml
<Carousel @bind-SelectedSlide="selectedImage">
    @foreach ( var item in imageDataUriGallery )
    {
        <CarouselSlide @key="@item" Name="@item">
            <Image Source="@item" Display="Display.Block" Style="width: 100%;" />
        </CarouselSlide>
    }
</Carousel>
@code{
    string selectedImage = "https://image.shutterstock.com/z/stock-photo-young-woman-exercising-at-home-doing-push-ups-and-looking-at-her-mobile-phone-457908448.jpg";

    string[] imageDataUriGallery = new string[] {
        "https://image.shutterstock.com/z/stock-photo-young-woman-exercising-at-home-doing-push-ups-and-looking-at-her-mobile-phone-457908448.jpg",
        "https://image.shutterstock.com/z/stock-photo-beautiful-young-woman-sitting-in-lotus-pose-and-meditating-at-yoga-studio-1017829420.jpg",
        "https://image.shutterstock.com/z/stock-photo-young-man-doing-exercising-at-home-on-the-couch-hardwoking-t-shirtless-guy-sportsman-in-workout-1746727358.jpg",
    };
}
```

PS. I also added `@key` to optimize it a little.

**Comment by drma-dev** [comment]
I had already tried that example.

I used exactly the code that you just showed me.

![image](https://user-images.githubusercontent.com/12803050/107789739-bce64f00-6d30-11eb-803c-14ec08f03ee8.png)

**Comment by stsrki** [comment]
I tried on the dev version. You probably have 0.9.2.x?

**Comment by drma-dev** [comment]
I have the latest version. I think I know how to reproduce the two errors.

if I read exclusively from dynamic content (from my api), it gives the following error:
![image](https://user-images.githubusercontent.com/12803050/107790584-b1475800-6d31-11eb-8264-e10281e771ce.png)

If I declare the variable with that static content of 3 images (which you showed) and then concatenate it with my dynamic content, the overlap error occurs.
![image](https://user-images.githubusercontent.com/12803050/107790958-261a9200-6d32-11eb-8fb5-7c6a116412e8.png)

**Comment by stsrki** [comment]
The overlap is happening because of the different aspect ratio for the given images. For that, you will need to manage it with CSS.
