### ISSUE TITLE
Be able to change the ranges of Min and Max on Numeric edit

### ISSUE THREAD

**Issue by Smurf-IV** [stsrki/Blazorise#1832]
**Is your feature request related to a problem? Please describe.**
`<NumericEdit TValue="float" Decimals="3" Min="@lookupTable.MinValue" Max="@lookupTable.MaxValue" Value="@lookupTable.CurrentMinValue" ValueChanged="OnMinValueTyped" ChangeTextOnKeyPress="false" />`

**Describe the solution you'd like**
i.e. when the values of `CurrentMinValue` change I want the `NumericEdit` to reflect the new min (or Max etc.)

**Comment by stsrki** [comment]
Hi, this is already done for 0.9.3 preview, with #1797
