### ISSUE TITLE
Add Toggle() method for component Bar

### ISSUE THREAD

**Issue by rayder2007** [stsrki/Blazorise#1833]
I wanted to make a function to automatically hide the bar after a specified time, for example, after 30 seconds.  But the method Toggle() is not available in code.

**Comment by stsrki** [comment]
You can just bind it to the `Visible `parameter and then refresh.

```cshtml
<Bar Visible="@barVisible "/>

@code{
  bool barVisible = true;

  Task OnElapsed()
  {
    barVisible = false;

    return InvokeAsync(StateHasChanged);
  }
}
```

**Comment by rayder2007** [comment]
Thanks
