### ISSUE TITLE
Datagrid cross-column validation

### ISSUE THREAD

**Issue by Jossec101** [stsrki/Blazorise#1834]
Hi! Great work!

I have a question since ValidatorEventArgs only receives a value of the property, how can we perfom cross-validation of two columns?

For example, we want to validate that  the start is not later than the end
![image](https://user-images.githubusercontent.com/53834183/107795624-31cd7f00-6d59-11eb-9467-cac9604ba296.png)

Is it possible to use the validation of each column for cross-validation? If instead of the property we would receive the full TItem of the edited/inserting row we would have a lot of power to validate between columns.

Another question, do you have in your roadmap to add auto mode validation for datagrid columns (based on data annotations)? It would be really nice since forms have it but the internal ones of the datagrid form not.

Thanks again!

**Comment by stsrki** [comment]
It's not possible out of the box. The only way is for you to save each value and then check it with each validator separately.

There is no plan to add this feature internally.
