### ISSUE TITLE
Blazorise.BarDropdownToggle:  JavaScript interop calls cannot be issued during server-side prerendering

### ISSUE THREAD

**Issue by crjc** [stsrki/Blazorise#1835]
**Describe the bug**
The `<BarDropdownToggle>` component attempts to do JavaScript interop calls when pre-rendering a Web Assembly Blazor application. 

**To Reproduce**
1. Use the first example snippet from https://blazorise.com/docs/components/bar/ in a web assembly blazor app
2. Set `render-mode="WebAssemblyPrerendered"` on server's _Host
3. Navigate to page
4. See server error

_InvalidOperationException: Unable to set property 'ParentStore' on object of type 'Blazorise.BarDropdownToggle'. The error was: JavaScript interop calls cannot be issued during server-side prerendering, because the page has not yet loaded in the browser. Prerendered components must wrap any JavaScript interop calls in conditional logic to ensure those interop calls are not attempted during prerendering._

**Expected behavior**
No error should appear.

**Additional context**
Commenting out `BarDropdownToggle` will remove the error.

It seems to be originating from around https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/BarDropdownToggle.razor.cs#L106

I can provide a repo if needed.

**Comment by stsrki** [comment]
Thank you for reporting this. Somehow we overlooked this, definitely shouldn't call JS before it's rendered. Going on the list.
