### ISSUE TITLE
Switch toggle functionality is broken

### ISSUE THREAD

**Issue by BruhWhatGives** [stsrki/Blazorise#1836]
For component testing, I added an id to the switch (which works great) and found this breaks the toggle functionality in the UI.

<Switch id="compliance-service-switch" Disabled="@(!this.EditComplianceService)" TValue="bool" @bind-Checked="@this.ViewModel.IsComplianceServiceEnabled">Enabled</Switch>

**Comment by stsrki** [comment]
It probably messes with the internally generated ID when you use `id`.

Instead, you should define it as:

```cshtml
<Switch ElementId="compliance-service-switch" Disabled="@(!this.EditComplianceService)" TValue="bool" @bind-Checked="@this.ViewModel.IsComplianceServiceEnabled">
Enabled
</Switch>
```
