### ISSUE TITLE
Remove info text next to datagrid pagination

### ISSUE THREAD

**Issue by stieven76** [stsrki/Blazorise#1837]
Hi,

I'm build a site with Blazorise, really nice looking components! Now I've got a question about the Datagrid  Pagination. There is a text next to it displaying 1 - 7 of 7 items. On the demo page it's not there: [https://bootstrapdemo.blazorise.com/tests/datagrid](https://bootstrapdemo.blazorise.com/tests/datagrid). I've dowloaded the demo code but can't seem to find the setting to hide this. Can anyone help?
![image](https://user-images.githubusercontent.com/6266999/107845630-2e7bd700-6ddd-11eb-8939-aecff9857ed9.png)
Thx!

**Comment by stsrki** [comment]
You can hide it by just defining `TotalItemsTemplate` and leaving it empty.

![image](https://user-images.githubusercontent.com/900302/107921068-4040b400-6f6e-11eb-967c-35a914f0fedf.png)

**Comment by stieven76** [comment]
I must be missing something because TotalItemsTemplate doesn't exists for my DataGrid. My nuget are 0.9.2.5.

![image](https://user-images.githubusercontent.com/6266999/107965508-e90d0480-6faa-11eb-9317-2c977ee5c0b8.png)

**Comment by stsrki** [comment]
Sorry, I forgot. It's available in 0.9.3 preview only.

**Comment by stsrki** [comment]
Just a quick info. The plan is to release 0.9.3 soon. How soon it depends, but I hope by the end of next week.

**Comment by stieven76** [comment]
ah nice. I'll follow up and update my nugets when possible.
Thx!
