### ISSUE TITLE
Feature request: extend DataGrid to support each Master row to display a Details subgrid if there is associated data

### ISSUE THREAD

**Issue by githubfanster** [stsrki/Blazorise#184]
In our current Windows Presentation Foundation (WPF) app, which we are hoping to port to Server-Side Blazor, we are able to define a RowDetailTemplate for our Customer Datagrid to show related Orders data (if available) below each Customer master row.

(The Customer-Orders Master-Details example is just an example)

Is it possible to do something like this in version 0.8 of Blazorise DataGrid?

If not, could you please consider supporting such a feature?

Thanks for looking into this

**Comment by stsrki** [comment]
I haven't work much in WPF. Can you please post a screenshot of your current implementation so I can have better understanding of what to do?

**Comment by githubfanster** [comment]
is this link ok?
https://www.devcurry.com/2011/05/silverlight-4-nested-datagrid-for.html

Step 3 shows an image of a DataGrid of Customers.
Underneath each customer row is a nested grid representing the orders for a specific customer

**Comment by githubfanster** [comment]
here is another example:
http://www.howdoicode.net/2011/10/wpf-binding-example-part-5.html

Here the "master" grid represents high-level process info (name etc).
underneath each process row is a nested grid representing details for that process

**Comment by stsrki** [comment]
I see what you want now. Yeah I think it should be fairly easy to do. Probably in the next 0.8.2 or 0.8.3.

Soon I will release 0.8.1 so I will investigate more after that.

**Comment by stsrki** [comment]
Is detail row going to be visible only for currently **selected row**?
Or does it need to be visible for **all** currently displayed rows?

**Comment by githubfanster** [comment]
We're ok with displaying the nested grid data for only the currently selected row or for all rows visible in a page. So no strong preference.

WPF allows the specification of a Visibility Function (the data trigger in the xaml below) to conditionally determine whether the nested grid should render or not.
In our very specific case, we set it up so that even though each of our Master Row has at least one Child Detail Row, we only want the nested grid to render if it contains more than one detail row.
In the case of a Customer-Orders relationship, only Customer rows with more than one Orders would have their nested grids displayable.
Is it possible to give the RowDetailsTemplate you're planning to work on a configurable Visibility Function?

```
<DataGrid.RowDetailsTemplate>
	<DataTemplate>
		<DataGrid x:Name="rdGrid"
			CanUserAddRows="False"
			RowBackground="Beige"
			ItemsSource="{Binding Model.MatConvertFroms}" AutoGenerateColumns="False">
			<DataGrid.Columns>
				<DataGridTextColumn Header="Material From" 
					Binding="{Binding MaterialFrom.MaterialCode}"/>
				<DataGridTextColumn Header="Description" 
					Binding="{Binding MaterialFrom.MaterialDesc}"/>
				<DataGridTextColumn Header="Ratio" Width="80"
					Binding="{Binding SourceQty}" IsReadOnly="True"/>
			</DataGrid.Columns>
		</DataGrid>
		<DataTemplate.Triggers>
			<DataTrigger Binding="{Binding HasMoreThanOneRecordOrHasTargetQty}" Value="False">
				<Setter TargetName="rdGrid" Property="Visibility" Value="Collapsed"/>
			</DataTrigger>
		</DataTemplate.Triggers>

	</DataTemplate>
</DataGrid.RowDetailsTemplate>
```

**Comment by stsrki** [comment]
So controlling the row visibility is through the custom function `<DataTrigger Binding="{Binding HasMoreThanOneRecordOrHasTargetQty}" Value="False">` and the return value must match the `Value` attribute?

Also I see the attribute `CanUserAddRows`. That means potentially the detail row(s) can also be edited?

I'm still planning and researching so the more informations I can get, the better.

**Comment by githubfanster** [comment]
In our case, the snippet below:

```
<DataTemplate.Triggers>
	<DataTrigger Binding="{Binding HasMoreThanOneRecordOrHasTargetQty}" Value="False">
		<Setter TargetName="rdGrid" Property="Visibility" Value="Collapsed"/>
	</DataTrigger>
</DataTemplate.Triggers>
```

means

If the function HasMoreThanOneRecordOrHasTargetQty() returns the configured trigger value (the Value= "False"), then the "Setter" rule will be executed.
That is, the grid named "rdGrid" (the row detail Grid)  for the current master row should not be rendered (Visibility = Collapsed).


See the attached screenshots for the discussion below:

We do our data editing thru buttons in a separate sidebar panel (see MatConversion.png) and we edit the parent and its children records as a group.

For example, if we click the parent row (Target Material = B-BKQ-FPP) or any of its children, and then click on the "Edit" button, the form that pops up has SEPARATE sections for the Parent and Children Materials (see MatConversion-Edit-B-BKQ-FPP.png).

It is in that Edit Form that we do all our editing.

The CanUserAddRows="False" that you see prevents WPF from displaying extra empty rows in the subgrids/row detail grids themselves.

The "Add" and "Delete" button in the sidebar panel allows users to add a new Parent and Children group, or delete an existing Parent and its children as a group.

```
 <DataGrid x:Name="rdGrid"
                            CanUserAddRows="False"
                            RowBackground="Beige"
```

We set each row detail row to have a Beige background color to easily identify them as children rows.
[MatConversion.zip](https://github.com/stsrki/Blazorise/files/3479818/MatConversion.zip)

**Comment by stsrki** [comment]
Thank you for the detailed description. I think for now I have enough information.

Also I think I could also create a `Popup` editor that could be similar to the one that you already have. Currently I have `InRow` and `Form` edit mode, so I guess `Popup` mode will be also good to have.

If I need any more info I will contact you here, if that's OK with you?

**Comment by githubfanster** [comment]
Yes. Thank you very much for considering our request

**Comment by stsrki** [comment]
Done. The usage will be in the documentation.
