### ISSUE TITLE
DateEdit 2 way binding doesn't work.

### ISSUE THREAD

**Issue by stieven76** [stsrki/Blazorise#1852]
I have a DateEdit component on my form and it works fine on my Add page, value gets passed with the post. However when I try to load it on my Edit page then the binding doesn't work. The value is in my model but doesn't show on my view.

`<DateEdit TValue="DateTime?" @bind-Value="@_updateModel.PurchaseDate" />`
Value: 2021-02-12 not shown:
![image](https://user-images.githubusercontent.com/6266999/108119732-7da55e80-70a0-11eb-911f-231f03338ca6.png)

When I use the Blazor standard InputDate then my date is bind and shown on the page:
`<InputDate @bind-Value="@_updateModel.PurchaseDate" />`

Value shown:
![image](https://user-images.githubusercontent.com/6266999/108119785-96157900-70a0-11eb-81a3-a7d206c67ee0.png)

I've looked in the Demo project but found nothing. Is this a bug or I'm missing something?

I've the same issue with the RichTextEdit component, so I guess I'm mising something. :)

**Comment by stsrki** [comment]
You have a typo. Instead of `Value` it should be `Date`:

`<DateEdit TValue="DateTime?" @bind-Date="@_updateModel.PurchaseDate" />`

**Comment by stieven76** [comment]
Ah so stupid. That fixed it. :)
How to 2way bind the RichTextEdit?

You have a great set of tools!

**Comment by stsrki** [comment]
Thanks!
