### ISSUE TITLE
NumericEdit ValueChanged fires twice and sets value back to zero

### ISSUE THREAD

**Issue by pvagnini** [stsrki/Blazorise#1853]
I am on v0.9.3-preview9

I am using basic configuration like 

`<NumericEdit TValue="int"  @bind-Value="@Test" ChangeTextOnKeyPress="false" Size="Size.Small" />`

When entering a value in the NumericEdit the bound value is updated correctly, but then immediately after updated again to zero.
This incorrect behavior also happens when using the ValueChanged event rather than direct binding.

**Comment by stsrki** [comment]
Fixed value reset with #1855 

As of ValueChanged fired twice, it was necessary since there was no way to make a Min-Max value check unless onblur event was used. Basically, onblur will check if the entered value is in range and then adjust, making a second call to ValueChanged.
