### ISSUE TITLE
Validations are not cleared

### ISSUE THREAD

**Issue by vignatov** [stsrki/Blazorise#186]
Calling Validations.ClearAll() does not clear Validations on the form as expected.

I have a simple form with few text fields on a modal dialog. I configured validations to run manually on submit. After validation is passed the data from the form is sent to server and the form is cleared. However the old validations are still active in their states despite me calling ClearAll(). I tried even to call clear for each individual validation, but it did not work either.

It can be issue only with Modal forms I haven't tried it on page.

**Comment by stsrki** [comment]
Can you provide a sample code so I can test it?

**Comment by stsrki** [comment]
Closing as there is no code sample to test. Please reopen the issue of you still need help.
