### ISSUE TITLE
Animation types

### ISSUE THREAD

**Issue by curelom** [stsrki/Blazorise#1864]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I am trying to do [...] but [...]
All the Animation types are transition animations, i.e. object showing up or dissappearing in an animated way.  Would love to see some animation types that are "attention getters"  i.e. animations for objects that are already displayed, such as wiggles, size changes from normal to big, back to normal, etc.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by stsrki** [comment]
We have no plan to add this kind of animations, The idea with Blazorise is to be as close as possible to the native provider frameworks like Bootstrap, Bulma, etx.
