### ISSUE TITLE
SelectEdit adding "col"  Bootstrap classes forces the form-group inline even in vertical mode

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#187]
Hello

Not a big issue (since there is a workaround), but when adding any "col" class to the SelectEdit, the html goes inline as follows:

```html
<Field>
    <FieldLabel>My Label</FieldLabel>
    <SelectEdit Class="col-4" TValue="int?">
        <SelectItem Value="@((int?)null)">None</SelectItem>
    </SelectEdit>
</Field>
```

![image](https://user-images.githubusercontent.com/26474006/62596092-09b2c380-b90b-11e9-95c1-fd7078a74716.png)

The workaround is to wrap the SelectEdit in `div` as follows:

```html
<Field>
    <FieldLabel>My Label</FieldLabel>
    <div>
        <SelectEdit Class="col-4" TValue="int?">
            <SelectItem Value="@((int?)null)">None</SelectItem>
        </SelectEdit>
    </div>
</Field>
```

![image](https://user-images.githubusercontent.com/26474006/62596109-17684900-b90b-11e9-84bf-4cd624affc9a.png)

**Comment by stsrki** [comment]
Adding column size on editors is not actually supported. The right way is by setting the `ColumnSize` attribute on `Field` component. Or if you're going with inline then you can/should also use a `FieldBody`. 

https://blazorise.com/docs/components/field/

PS. I see you're using the `Class` attribute to manually set the bootstrap column size(s). Generally how I imagined Blazorise is to use `Class` attribute as the last option and use it only for custom classes that are specific to the user/developer project. I hope one day custom css classes will go away and everything could be done through Blazorise components and attributes. But that is the distant future :)

**Comment by brettwinters** [comment]
Actually I get the same issue using the Blazorise attributes: 

```html
<Field>
    <FieldLabel>My Label</FieldLabel>
    <SelectEdit ColumnSize="ColumnSize.Is3" TValue="int?">
        <SelectItem Value="@((int?)null)">None</SelectItem>
    </SelectEdit>
</Field>
```

outputs: 
![image](https://user-images.githubusercontent.com/26474006/62686589-3cce8300-b9ef-11e9-9c43-ef96e7490e68.png)

Explicitly setting `<Field IsHorizontal="false">` also doesn't help...

But using the same workaround: 

```html
<Field>
    <FieldLabel>My Label</FieldLabel>
    <div>
        <SelectEdit ColumnSize="ColumnSize.Is3" TValue="int?">
            <SelectItem Value="@((int?)1)">One</SelectItem>
        </SelectEdit>
    </div>
</Field>
```
Outputs

![image](https://user-images.githubusercontent.com/26474006/62686628-4a840880-b9ef-11e9-8da1-de05dbd43fc1.png)

Am I using the ColumnSize correctly?

**Comment by stsrki** [comment]
I guess you need to have editors in column grid layout. So to that you can use `Fields` and `Field` component.

example from demo: https://bootstrapdemo.blazorise.com/tests/forms

```
<Fields>
    <Field ColumnSize="ColumnSize.Is6.OnDesktop">
        <FieldLabel>City</FieldLabel>
        <TextEdit />
    </Field>
    <Field ColumnSize="ColumnSize.Is4.OnDesktop">
        <FieldLabel>State</FieldLabel>
        <SelectEdit TValue="string">
        </SelectEdit>
    </Field>
    <Field ColumnSize="ColumnSize.Is2.OnDesktop">
        <FieldLabel>Zip</FieldLabel>
        <TextEdit />
    </Field>
</Fields>
```

The thing is that `ColumnSize` was used on editors in older versions of Blazorise. But it was a lot of spaghetti code to make it work so I had to introduce `Fields` component so that everything could work as expected for all of the CSS providers. I still haven't decided if I'm going to bring back `ColumSize` to the edit components. I will have to see the pros and cons before I finally decide what to do.

In the meantime I will need to describe it better in the documentation what are use cases for Fields, Field and column layouts.

**Comment by brettwinters** [comment]
Yeah I see that you’re trying to abstract the different css libraries within Blazorise. It won’t be easy...  

I agree that it would be nice to be able to switch css library’s but in most cases most projects just stick to one system and then customise from there...

Anyway let me try next week to get the layout working using the fields approach
