### ISSUE TITLE
Carousel Indicators z-index higher than Fixed Layout Header. 

### ISSUE THREAD

**Issue by mcguireuk** [stsrki/Blazorise#1870]
**Describe the bug**
The Carousel indicators are set to a z-index of 15. However the LayoutHeader fixed (.b-layout-header-fixed) has a z-index of 1.

I have a page with a carousel on and when scrolling the indicators are in front of the app header. 

**To Reproduce**
Use basic App Layout.
```
 <Layout>
        <LayoutHeader Fixed="true">
            <Bar Mode="BarMode.Horizontal"
                 CollapseMode="BarCollapseMode.Small"
                 Breakpoint="Breakpoint.Desktop"
                 Background="Background.Primary"
                 ThemeContrast="ThemeContrast.Light">
                <BarToggler />
                <BarMenu>
                    <BarStart>
                       </BarStart>
                    <BarEnd>
                        <LoginDisplay />
                    </BarEnd>
                </BarMenu>
            </Bar>
        </LayoutHeader>
        <LayoutContent>
            <ComponantWithCarousel/>
    </Layout>

```
**Expected behavior**
z-index needs to be reviewed. I'd suggest a higher value on the header fixed as I'd expect this to be over everything else on the page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20006090/108379258-a8f19000-71fd-11eb-961e-9aa3eda4b49f.png)

**Comment by stsrki** [comment]
A problem similar to #1582

I will add it to the list so we can test it along with Addons.
