### ISSUE TITLE
First time selection from SelectList provides the correct Value in SelectedValueChanged handler, but always gets set to the first item in the dropdown

### ISSUE THREAD

**Issue by mithril52** [stsrki/Blazorise#188]
This issue shows up in the demo website as well. Go to the Components page, and note that the current selection in the Select list is Armenia and the Selected Value is 3. This is correct.

Now, select, for example, Austria from the list. The Selected Value changes to 4 correctly, but the list now displays Albania, which is ID 1, not 4.

If you now select another from the list, it will update both the value and the list properly, and will from there on out. It seems to only happen the first time a selection is made.

I see the same behavior in my own app.

**Comment by stsrki** [comment]
Thank you for the detailed report, I managed to reproduce it on my side. I will try to fix it for 0.8.2
