### ISSUE TITLE
Datagrid: Is Async missing?

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1883]
Hello @stsrki 
Shouldn't the async state machine be set up on these delegates?

**This:**
![image](https://user-images.githubusercontent.com/22283161/108592807-ac088f80-7367-11eb-898f-2551aa9c06b6.png)
**To this:**
![image](https://user-images.githubusercontent.com/22283161/108592816-b7f45180-7367-11eb-81c3-6ce340da9329.png)

**Comment by stsrki** [comment]
I guess you're right. Did you test it and see how it behaves?

**Comment by David-Moreira** [comment]
Nope, I am starting work on resizable, and noticed that.

I'm guessing the delegate signature should also have return Task instead of void since that also affects async negatively. 
But since those delegates are bound to events I'm not 100% sure how it behaves under the curtains and that's why I was questioning.

I guess I can do some reading up and testing.

**Comment by stsrki** [comment]
That is also my concern with delegates. If you have time see what can be done. Or I can try it later.

**Comment by David-Moreira** [comment]
Either way, that shouldn't be critical. 
I am still gonna be finishing the resizing feature first.

I did notice something else which can be critical, possible memory leaks, but again I'm not sure, if this is gonna hang on memory or not, I generally just take the safe approach and always unscribe events:
![image](https://user-images.githubusercontent.com/22283161/108598271-93f33900-7384-11eb-8799-c8b897fcd49f.png)

**Comment by David-Moreira** [comment]
@stsrki 
No real reading up yet about the async event/delegate stuff.

But done some initial testing. 
As expected without async it will not await any of the lines and will move right on.
The only downside is if we wanted to do something firstly in `InvokeAsync( () => PageSizeChanged.InvokeAsync( pageSize ) );` just before` InvokeAsync( HandleReadData );` happens, HandleReadData could possibly run before PageSizeChanged has done its whole work.
```
               paginationContext.SubscribeOnPageSizeChanged( pageSize =>
                {
                    InvokeAsync( () => PageSizeChanged.InvokeAsync( pageSize ) );

                    // When using manual mode, a user is in control when StateHasChanged will be called
                    // so we just need to call HandleReadData.
                    if ( ManualReadMode )
                    {
                        InvokeAsync( HandleReadData );
                    }
                    else
                    {
                        InvokeAsync( StateHasChanged );
                    }
                } );
```
Trying to throw an exception inside HandleReadData on this version, will have an incomplete stack trace:
```
This exception was originally thrown at this call stack:
    Blazorise.Demo.Pages.Tests.DataGridPage.OnReadData(Blazorise.DataGrid.DataGridReadDataEventArgs<Blazorise.Demo.Pages.Tests.DataGridPage.Employee>) in DataGridPage.razor.cs
    [External Code]
    Blazorise.DataGrid.DataGrid<TItem>.HandleReadData() in DataGrid.razor.cs
    [External Code]
    Blazorise.DataGrid.DataGrid<TItem>.HandleReadData() in DataGrid.razor.cs
```

Moving on to make it async, it now clearly awaits each execution: 
```
                paginationContext.SubscribeOnPageSizeChanged( async pageSize =>
                {
                    await InvokeAsync( () => PageSizeChanged.InvokeAsync( pageSize ) );

                    // When using manual mode, a user is in control when StateHasChanged will be called
                    // so we just need to call HandleReadData.
                    if ( ManualReadMode )
                    {
                        await InvokeAsync( HandleReadData );
                    }
                    else
                    {
                        await InvokeAsync( StateHasChanged );
                    }
                } );
```
Trying to throw an exception inside HandleReadData on this version, will now have a clearer stack trace, tracing back to the actual origin:
This exception was originally thrown at this call stack:
```
Blazorise.Demo.Pages.Tests.DataGridPage.OnReadData(Blazorise.DataGrid.DataGridReadDataEventArgs<Blazorise.Demo.Pages.Tests.DataGridPage.Employee>) in DataGridPage.razor.cs
    [External Code]
    Blazorise.DataGrid.DataGrid<TItem>.HandleReadData() in DataGrid.razor.cs
    [External Code]
    Blazorise.DataGrid.DataGrid<TItem>.HandleReadData() in DataGrid.razor.cs
    [External Code]
    Blazorise.DataGrid.DataGrid<TItem>.OnAfterRenderAsync.AnonymousMethod__39_0(int) in DataGrid.razor.cs
```

Making the delegate take in Task or Void doesn't seem to make any difference. 
I think I had read something that they had made events a bit smarter about taking async delegates that return void.

So adding async seems the right thing to do here.
Also, I'm not sure how easy it is to implement this, but an improvement would be to be able to cancel a running async method with a cancellation token.

If you put a delay of 2.5s for example on HandleReadData, and switch between pages, it will always do the full work even if the page is no longer the one originally selected.

I also did this to simulate different time spent grabbing the data for different pages... it you switch between the pages... they will end up with the wrong data for the page. Since they will display the data that ended up taking the longest to load.
```
            Random random = new Random();
            await Task.Delay( random.Next(2500) );
```
3rd page with 2nd page data:
![image](https://user-images.githubusercontent.com/22283161/108603308-2ef90c80-739f-11eb-9d66-17ad1087f114.png)

**Comment by stsrki** [comment]
Wow, you did a lot of investigation. Thanks!

Yeah, I already had a feeling it wouldn't be much difference between the regular void delegate and the one with Task. In fact, `async void` for events is the only one that should be _safe_ to do. So I think we can safely do it that way. Just create a PR and if anything happens in the future we can improve it.

Regarding the memory leaks, that sounds more dangerous and should be dealt with as soon as possible.

**Comment by David-Moreira** [comment]
#1886 for async.
#1889 for event unsubscribing.
I guess you can close this issue.
