### ISSUE TITLE
After added the closing event  in modal component ,how to use it?

### ISSUE THREAD

**Issue by Jasoneng2017** [stsrki/Blazorise#189]
need help

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by stsrki** [comment]
You can see a full example in the demo source: https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/ModalsPage.razor

But anyways you need just define a `@ref` to use a Show() and Hide() methods.

```
<SimpleButton Clicked="@ShowModal">
    Show Modal
</SimpleButton>

<Modal @ref="modalRef">
    <ModalBackdrop />
    <ModalContent>
        <ModalHeader>
            <ModalTitle>
                <Icon Name="IconName.Edit" />
                Employee edit
            </ModalTitle>
            <CloseButton Clicked="@HideModal" />
        </ModalHeader>
        <ModalBody MaxHeight="@maxHeight">
            <Field>
                <FieldLabel>Name</FieldLabel>
                <TextEdit Placeholder="Enter name..." />
            </Field>
            <Field>
                <FieldLabel>Surname</FieldLabel>
                <TextEdit Placeholder="Enter surname..." />
            </Field>
            <Field>
                <FieldLabel>Date of birth</FieldLabel>
                <DateEdit Placeholder="Pick a date" />
            </Field>
        </ModalBody>
        <ModalFooter>
            <SimpleButton Color="Color.Secondary" Clicked="@HideModal">Close</SimpleButton>
            <SimpleButton Color="Color.Primary" Clicked="@HideModal">Save Changes</SimpleButton>
        </ModalFooter>
    </ModalContent>
</Modal>
@code{
    private Modal modalRef;

    private void ShowModal()
    {
        modalRef.Show();
    }

    private void HideModal()
    {
        modalRef.Hide();
    }
}
```

**Comment by Jasoneng2017** [comment]
@stsrki I already did,I want to prevent modal from closing when i click other area. according the document i added closing event and set e.cancel=true, and then what should i do to close the modal?

please !!!


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by stsrki** [comment]
You should set `e.Cancel=true` only when you really need to stop modal from closing. For example if validation has not passed, or maybe saving data has failed, or whatever.

So if you really need to use Closing event it would look something like this.
```
private void OnModalClosing( CancelEventArgs e )
{
    if ( sometingHasFailed )
        e.Cancel = true;
}
```

Otherwise just remove that event and you're OK.

**Comment by Jasoneng2017** [comment]
@stsrki thanks! i understand.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Jasoneng2017** [comment]
@stsrki thanks! i understand.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
