### ISSUE TITLE
WithOffset attribute not working anymore

### ISSUE THREAD

**Issue by ATP-IAS** [stsrki/Blazorise#1894]
**Describe the bug**
Hello,
After I updated to the latest version of Blazorise, WithOffset attribute used in ColumnSize no longer moves the column to the right.

**To Reproduce**
I used WithOffset as follows:
ColumnSize="ColumnSize.IsAuto.WithOffset"

I must use ColumnSize.IsAuto because the number of buttons is not static.

Before updating to version V0.9.2 the column was moved to the right as you can see below. (the div containing all the buttons is circled in red)
![image](https://user-images.githubusercontent.com/74247901/108705854-82419b00-7516-11eb-91d2-691a40df8669.png)
After updating to version V0.9.2 the output is:
![image](https://user-images.githubusercontent.com/74247901/108706019-b321d000-7516-11eb-9773-9d89843a6dd2.png)

After a bit of digging, I noticed that the css classes used for the div changed from **class="col offset-auto"** to **class="offset-auto"**

I saw in [this ticket](https://github.com/stsrki/Blazorise/issues/1548) that you removed the extra **col**. If I add it manually, everything works as expected.

Also my index.html uses the latest bootstrap versions.

Is this something that should happen?
Please assist.

Many thanks !

**Comment by stsrki** [comment]
Yeah, it seems `"ColumnSize.IsAuto.WithOffset"` is a special case where `col` is still needed. I will need to fix. In the meantime you can just define it manually `Class="col" ColumnSize="ColumnSize.IsAuto.WithOffset"`.

**Comment by stsrki** [comment]
@ATP-IAS Are you sure `col` is needed. From what I can see in the [Bootstrap Offset](https://getbootstrap.com/docs/4.6/layout/grid/#offsetting-columns) documentation there is no example where `col` is used along with offset. There is always the column size and offset size, both defined, eg. `col-md-4 offset-md-4`. There is no example where the offset is used alone

**Comment by ATP-IAS** [comment]
I see what you mean.
But in my case the size of the column is not static which means that the offset must be also dynamic in order to move the column to "max" right.
Were you able to use `ColumnSize.IsAuto.WithOffset` and get the desired effect?

**Comment by ATP-IAS** [comment]
Okay, it seems that I did not fully understood how `WithOffset` works. My bad. 
This is the example from Blazorise Docs:

![image](https://user-images.githubusercontent.com/74247901/108847464-63133e00-75e8-11eb-8c7b-c4af970bfca3.png)

What I am trying to accomplish is to have the second column in the "max" right position.
Thanks.

**Comment by stsrki** [comment]
```cshtml
<Column ColumnSize="ColumnSize.Is4">
    ...
</Column>
<Column ColumnSize="ColumnSize.Is4" Margin="Margin.IsAuto.FromLeft">
    ...
</Column>
```

or

```cshtml
<Column ColumnSize="ColumnSize.Is4">
    ...
</Column>
<Column ColumnSize="ColumnSize.Is4.Is4.WithOffset">
    ...
</Column>
```

**Comment by ATP-IAS** [comment]
Thanks a lot. 
The Margin version is exactly what I need because no matter the size of the first column the second one will always be in the "max" right position.

This was just a mistake from my end. Will close this now.
Have a good day.
