### ISSUE TITLE
smaller side bar

### ISSUE THREAD

**Issue by ikkyGH** [stsrki/Blazorise#190]
New thread started from [157](https://github.com/stsrki/Blazorise/issues/157).

Can you look at making the sidebar have a “small” state. Where it would be smaller, but not completely hidden. Just big enough to show some icons that would fly out the menu when selected? Would be a nice UI feature.

Thanks in advance.

**Comment by WillianGruber** [comment]
@ikkyGH this would be very nice indeed

**Comment by stsrki** [comment]
The plan is to rewrite Sidebar from scratch so when the time comes this will also be the part of the new version.

**Comment by MitchellNZ** [comment]
Completed as part of #763.
