### ISSUE TITLE
RC1: Microsoft.JSInterop.JSException: Could not find 'blazorise.setProperty' ('setProperty' was undefined).

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1910]
@stsrki 
Have this on latest version. Does this tell you anything right off the bat? Or gotta dig deeper?

RC1: Microsoft.JSInterop.JSException: Could not find 'blazorise.setProperty' ('setProperty' was undefined).
![image](https://user-images.githubusercontent.com/22283161/108996821-cb205d80-7696-11eb-8edd-aa1b15ff41bf.png)

**Comment by stsrki** [comment]
Blazorise js is changed so you have an old version. Refresh page with Ctrl+F5.

**Comment by David-Moreira** [comment]
You're right, the js changed. And I don't know why I was using my own version of blazorise.js, I think I wanted to minify it. 

Speaking of minifying it, can that be supported? Target minified versions of blazorise javascript resources?
Thanks for the fast response!

**Comment by stsrki** [comment]
Quick google and it seems it can be done https://stackoverflow.com/questions/59103892/bundling-css-and-js-in-net-core-3-and-blazor

**Comment by David-Moreira** [comment]
Yes. That's the extension I personally use to simplify / automate the process. With a task set to automatically minify the files either when they are saved or when build project happens. That also would mean that the development process would now have a dependency with that extension. 

Would you be willing to open a feature for 0.9.4 to provide blazorise minified files in addition to the standard ones? I could set it up if you'd like.

**Comment by stsrki** [comment]
We already use a similar extension to compile scss into css, so I think this is the right way. A long time ago I had an idea of refactoring existing JS code into separate modules and classes instead of keeping all in one large file. So maybe we can do it all as part of it.

**Comment by David-Moreira** [comment]
Yep. I do have something similar like that setup myself. While it is not using the js module import/export functionality. 

I have my js separated into stuff like app.js, app.Utils.js, app.somethingelse.js and then there's a compiler that just grabs the 3 of them and brings them together into an appBundle.js for the final product.

So agreed.
