### ISSUE TITLE
Datagrid Empty : No pager

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1913]
Hello @stsrki 
I was finally finishing up migrating the buttons to ButtonRow.

But I noticed that when the Datagrid is empty, the pager doesn't render which kinda makes sense, but that also means that buttons that can have logic that makes sense even if the grid is empty, will not render... :'( 

Think we can add something to enable pager even when empty? It does make sense now that devs can configure buttons on the pager.
![image](https://user-images.githubusercontent.com/22283161/109049030-b3190000-76cf-11eb-8f55-8266dd01b578.png)

**Comment by stsrki** [comment]
How do you get the DataGrid to be empty and not show the pager? I cannot reproduce it.

**Comment by David-Moreira** [comment]
Oh... What the heck? I thought it was a feature. 😅 I'll try to reproduce later.
You did define empty template in your attempt, right?

**Comment by David-Moreira** [comment]
@stsrki Here's a demo.
Happens when you define an empty template.
https://github.com/David-Moreira/DGridRenderHandle

**Comment by stsrki** [comment]
I tried your demo and I can't decide if it's a feature or a bug 😅

**Comment by David-Moreira** [comment]
Hahaha. I'm guessing that if it was already like that since Datagrid was born... There may be people that now expect it to behave like that? 
I don't like adding yet another flag to make the pager show... when empty... 

I just think it's better to have it show, and if people really wanted to hide the pager they can just bind a flag to the show pager and check themselves for the empty data. 

This way we can have both worlds. Otherwise I don't see a way to make it show... I don't know about UX, but I checked a few tables/grids and they show it. And now there's the button row feature that kinda depends upon pager showing...

**Comment by stsrki** [comment]
I would leave it as it is. We can always revisit later if more people want the change.

**Comment by David-Moreira** [comment]
Damn, but I do need it.
Fine, I'll have to figure out a weird workaround then... Like just not setting it at all. 😆

Thanks.

**Comment by stsrki** [comment]
How about making all `protected` properties and methods in DataGrid and making them `protected virtual`? Then you can override from DataGrid in your custom implementation. That can also be the first way into making the API more flexible.

**Comment by David-Moreira** [comment]
That seems like an idea. But making too much stuff virtual can lead to unexpected behaviour. Of course that ends up being the developer fault, but if we can make it hard for him to mess up the better.

I was thinking of doing a demo with a few ideas that I have and then you help pick one that we think it's best. It's still gonna take a while to get there though... 😅

**Comment by stsrki** [comment]
Yeah I know, devs can break something but as you said, it's on them.

Can you change `IsPagerVisible` behavior and show it if the button row is used? That is what you want, right?

**Comment by David-Moreira** [comment]
I guess it can additionally check for the current command mode and button row template not empty.

That would still maintain the current behaviour, while "fixing" for the new feature we introduced.

**Comment by David-Moreira** [comment]
It's a good idea.

Would you mind changing it or should I submit a PR?

**Comment by stsrki** [comment]
You change it and submit a PR. I'm currently in the middle of some major work 😅
