### ISSUE TITLE
Independent command

### ISSUE THREAD

**Issue by Wolfenry** [stsrki/Blazorise#1914]
I'm trying to have a custom clear filter command in the filtertemplate section (the broom in picture below), since i **don't** want a new column to clear all the filters (the command column). 

_DataGridClearFilterCommand depends on the command column and click eventhandler, so i can't make my own clear button easily

I've tried:
```
<DataGridCheckColumn TItem="Aitem" Field="@nameof(Aitem._chk)" Filterable="true">
    <FilterTemplate>
        <Icon Name="@("fa-broom")"  @onmousedown="@(e => clear = true)"/>
    </FilterTemplate>
    <DisplayTemplate>
        <Check Inline="true" TValue="bool" @bind-Checked="@context._chk" />
    </DisplayTemplate>
</DataGridCheckColumn>
```

and trigger the ClearFilter event with my 'clear' boolean but had no luck, is there any way to do this?

![image](https://user-images.githubusercontent.com/33076177/109051201-0a5fa600-76b9-11eb-8379-36de702b1a30.png)

**Comment by David-Moreira** [comment]
@stsrki one more case about exposing the internal API, right? I think we should get on this soon.

@Wolfenry as a dirty and hopefully **ONLY TEMPORARY** workaround you could hide the button and invoke it either by using a reference and calling it in c# or by giving it an id and by using javascript. 
Since you don't want the command column to be showing up. You could use the API thats exposed in the ButtonRowTemplate:
```
  <ButtonRowTemplate>
          <Button hidden id="triggerThisFromJavascript" @ref="orTriggerThisFromC#" Color="Color.Link" Clicked="@context.ClearFilterCommand.Clicked">Clear Filter</Button>
  </ButtonRowTemplate>
```

I haven't tested it, but pretty sure it should work as a workaround. Let me know the results if you try it!

**Comment by David-Moreira** [comment]
I was testing something else, and ended up testing this workaround, the c# version, it works:
**Full code:**

```
<DataGrid Data="Data"
          TItem="Test"
          ShowPager="true"
          Filterable="true">
    <EmptyTemplate>No records... :(</EmptyTemplate>
    <DataGridColumns>
        <DataGridColumn TItem="Test" Field="@nameof(Test.name)" Caption="Testing">
        </DataGridColumn>
    </DataGridColumns>
    <ButtonRowTemplate>
        <Blazorise.Button @ref="@HiddenClearFilterButton" hidden Clicked="@context.ClearFilterCommand.Clicked"  ></Blazorise.Button>
    </ButtonRowTemplate>
</DataGrid>


<button @onclick="Clear">CLEAR!</button>

@code{
    public Blazorise.Button HiddenClearFilterButton { get; set; }

    private Task Clear()
    {
       return HiddenClearFilterButton.Clicked.InvokeAsync();
    }

    public List<Test> EmptyData { get; set; } = new List<Test>();
    public List<Test> Data { get; set; } = new List<Test>() { new Test() { name = "1" } };

    public class Test
    {
        public string name { get; set; }
    }

}
```

![captured](https://user-images.githubusercontent.com/22283161/109080933-516d8b80-76f9-11eb-9bd5-95ae59d8c11a.gif)

**Comment by Wolfenry** [comment]
Great, i tried something like this but i still have the same problem (accesing `ClearFilter` )

Can't find <ButtonRowTemplate> component: 
![image](https://user-images.githubusercontent.com/33076177/109160817-0bdeac00-7755-11eb-9d88-a64c7c88f9e6.png)

Maybe i am missing something, just tell me!

Also with the actual `ClearFilter` found a bug on resetting <FilterTemplate> (just the text, not the value)
To reproduce in https://bootstrapdemo.blazorise.com/tests/datagrid: Change value con filter combo box > click on Clear Filter.

**Comment by David-Moreira** [comment]
Sorry! ButtonRow is a new feature coming in **0.9.3**  sometimes I just forget not everyone is using the pre-releases. :P
Anyway should be coming out soon, if you'd like to upgrade. @stsrki still end of week, right?

For another temporary workaround, but compatible with **0.9.2**, the one posted on #1915 by @kswoll should work.

> To reproduce in https://bootstrapdemo.blazorise.com/tests/datagrid: Change value con filter combo box > click on Clear Filter.
- It's fixed on the next release.

**Comment by Wolfenry** [comment]
Haha ok! i will try the new release im hyped now, excelent job guys, i'll be into it!
Good luck.

**Comment by stsrki** [comment]
Yes, it's still planned to be released soon. If not this week it will be the beginning of the next, guaranteed.
