### ISSUE TITLE
Sidebar / SidebarNavigation - keep selected item

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1919]
Is there a way, programmatically, to keep the selected menu after clicking?

![image](https://user-images.githubusercontent.com/12803050/109184489-d1cdd400-776d-11eb-837d-0a8e7188196d.png)

**Comment by stsrki** [comment]
The bar items are meant to be active when the current URL is detected. There is currently no way to disable that behavior.

We might consider adding a different `Match` option or maybe add an `Active` parameter that could override the default behavior.

**Comment by drma-dev** [comment]
The item is not getting active. And there may also be cases where I enter a sub-page.

**Comment by stsrki** [comment]
So you need to have it active when one of your sub-pages is currently visited? In that case try different Match. Default is set to All which means the entire URL must match.

**Try:**

**Comment by drma-dev** [comment]
![image](https://user-images.githubusercontent.com/12803050/109211063-77903b80-778c-11eb-963c-d44ca4f847eb.png)

The only way the item is activated is if I use chrome device mode

**Comment by stsrki** [comment]
I just noticed you're using Sidebar component. I must warn you it is obsolete and our Bar component is what you should use. It has many more features and is more stable.

**Comment by drma-dev** [comment]
I had followed examples from the documentation. there doesn't talk about it

**Comment by stsrki** [comment]
You probably overlooked it: https://blazorise.com/docs/components/bar/

**Comment by drma-dev** [comment]
Got it. Now I noticed a difference in the Dark color between the item Brand and Menu

![image](https://user-images.githubusercontent.com/12803050/109215546-0f445880-7792-11eb-9a0e-87d14649ee6d.png)

**Comment by drma-dev** [comment]
`    background: var(--b-bar-brand-dark-background, rgba(255, 255, 255, 0.025));`
```
    background: var(--b-bar-dark-background, #001529);
    color: var(--b-bar-dark-color, rgba(255, 255, 255, 0.5));
```
or is it intentional?

**Comment by stsrki** [comment]
I can only guess that it was intentional to make the brand more visible, compared to the items.

@MitchellNZ created most of the features so maybe he can answer the reasons.
