### ISSUE TITLE
Flex Layout Resizing

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1922]
Is it possible to _not_ use a flex layout? The reason is that when the screen is maximized, the content too stretched out. When I use the OnDesktop, OnTablet, etc. flexible sizing, it seems to not kick-in when I like and ends up being too squished if the browser is not maximized--like maybe half the desktop size.

I guess what I'm saying is that if the window is resized, I would like a horizontal scroll bar would appear.

Or maybe I'm just bad at this. I studied the demo, and the demo always looks good but the content there is simple.

**Comment by stsrki** [comment]
I cannot see your app so can only guess. The best is to inspect in devtools and see what is causing the horizontal scroll to not show. And add custom CSS to where you need to.

**Comment by stevenlupo** [comment]
I think you misunderstand. I'm saying that the layout resizes (it's flexible, so a horizontal scroll would never show). This is normal behavior.

I'm saying that if I design the layout to look good on a maximized browser window, and then I normalize the window (i.e., not maximized) and resize it to be smaller — yet still in the OnDesktop range (I assume), it doesn't look good because the content becomes too compressed—by wrapping, etc.

It would be helpful to know exactly where the breakpoints are occurring.

I think my only option is to use a class to set the width of the column to a fixed pixel size. I will try that today.

**Comment by stevenlupo** [comment]
I found a solution. I just need to set a max width. So it's still flexible, but won't stretch across the page when the browser is maximized.

`<Column Style="max-width:800px">`

Thanks.
