### ISSUE TITLE
Breaking change in v0.9.2 validation changes

### ISSUE THREAD

**Issue by dewitman** [stsrki/Blazorise#1923]
In version 0.9.2 the
`public ValidationStatus Validate()` method in `Validation.razor.cs`
was changed to 
`public ValidationStatus Validate( object newValidationValue )`
This was done to fix a problem with validation not using the new model reference for annotated validation.

The fix was correct, but the parameterless version of `public ValidationStatus Validate()` should still exist as an overload as follows:
`public ValidationStatus Validate() => Validate(inputComponent.ValidationValue);`

We call the parameterless version of this method in a project at our company. We are now stuck on version v0.9.2 because of this.
Could you please add this overload in the next release?

Thanks in advance and keep up the good work!

**Comment by stsrki** [comment]
The method was reverted in one of the patches for 0.9.2(https://github.com/stsrki/Blazorise/pull/1496). Please check your NuGet references.
