### ISSUE TITLE
DataGrid: How to implement a common render fragment template?

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1926]
Hello @stsrki 

Got any good idea how to define a common RenderFragment and easily share it?

I was trying something like this, but I'm having difficulties getting this to work.
![image](https://user-images.githubusercontent.com/22283161/109337109-3b2c1080-785c-11eb-9e7f-8b25a19587f8.png)

What I want across every DataGridColumn: 
```
<DataGridColumn 
                TItem="DocumentViewModel"
                Field="@nameof(DocumentViewModel.Id)"
                Caption="@GetDisplayName(nameof(DocumentViewModel.Id))">
    <FilterTemplate>
        <Blazorise.TextEdit 
                            Text="@context.SearchValue"
                            TextChanged="@context.TriggerFilterChange"
                            Class="@(string.IsNullOrWhiteSpace(context.SearchValue) ? "": "filter-active")"></Blazorise.TextEdit>
    </FilterTemplate>
</DataGridColumn>
```

I also tried wrapping the DataGridColumn inside another component, but I wasn't able to get it working due to the other RenderFragments... like Caption Template Display Template etc...

**Comment by paulosdfigueiredo** [comment]
I'm also interested. I tried something very similar and couldn't get it to work.😒

**Comment by stsrki** [comment]
I tried this and it kinda works. But I'm still not sure what you want to accomplish.

**MyColumn.razor**

```cshtml
@typeparam TItem
@inherits DataGridColumn<TItem>
@code{
    protected override Task OnInitializedAsync()
    {
        this.FilterTemplate = ( filter ) => ( builder ) =>
        {
            builder.OpenComponent<TextEdit>( 0 );

            builder.AddAttribute( 1, nameof( TextEdit.Text ), filter.SearchValue );
            builder.AddAttribute( 2, nameof( TextEdit.TextChanged ), EventCallback.Factory.Create<string>( this, ( value ) =>
            {
                filter.SearchValue = value;
                filter.TriggerFilterChange( value );

                return InvokeAsync( StateHasChanged );
            } ) );

            builder.AddAttribute( 3, "class", string.IsNullOrEmpty( filter.SearchValue ) ? "" : "filter-active" );

            builder.CloseComponent();
        };

        return base.OnInitializedAsync();
    }
}
```

**Comment by paulosdfigueiredo** [comment]
If you want to do it for DisplayTemplate, how do you have access to the cell value?

**Comment by stsrki** [comment]
This?

```cs
this.DisplayTemplate = ( item ) => ( builder ) =>
        {
            builder.OpenElement( 6, "span" );

            builder.AddContent( 7, ( item as DataGridPage.Employee )?.FirstName );

            builder.CloseElement();
        };
```

**Comment by David-Moreira** [comment]
> I tried this and it kinda works. But I'm still not sure what you want to accomplish.
> 
> **MyColumn.razor**
> 
> ```
> @typeparam TItem
> @inherits DataGridColumn<TItem>
> @code{
>     protected override Task OnInitializedAsync()
>     {
>         this.FilterTemplate = ( filter ) => ( builder ) =>
>         {
>             builder.OpenComponent<TextEdit>( 0 );
> 
>             builder.AddAttribute( 1, nameof( TextEdit.Text ), filter.SearchValue );
>             builder.AddAttribute( 2, nameof( TextEdit.TextChanged ), EventCallback.Factory.Create<string>( this, ( value ) =>
>             {
>                 filter.SearchValue = value;
>                 filter.TriggerFilterChange( value );
> 
>                 return InvokeAsync( StateHasChanged );
>             } ) );
> 
>             builder.AddAttribute( 3, "class", string.IsNullOrEmpty( filter.SearchValue ) ? "" : "filter-active" );
> 
>             builder.CloseComponent();
>         };
> 
>         return base.OnInitializedAsync();
>     }
> }
> ```

I just want to be able to implement common standard  behaviour on all my columns easily changed by going to the base implementation.
In this case I want to provide a filter template that always places filter-active if there's text in the column. 

I'm not on the pc right now... But it wasn't working very well... The state wasn't being synced well... I can try again with your implementation since you've done the callback slightly different.

**Comment by paulosdfigueiredo** [comment]
> I tried this and it kinda works. But I'm still not sure what you want to accomplish.
> 
> **MyColumn.razor**
> 
> ```
> @typeparam TItem
> @inherits DataGridColumn<TItem>
> @code{
>     protected override Task OnInitializedAsync()
>     {
>         this.FilterTemplate = ( filter ) => ( builder ) =>
>         {
>             builder.OpenComponent<TextEdit>( 0 );
> 
>             builder.AddAttribute( 1, nameof( TextEdit.Text ), filter.SearchValue );
>             builder.AddAttribute( 2, nameof( TextEdit.TextChanged ), EventCallback.Factory.Create<string>( this, ( value ) =>
>             {
>                 filter.SearchValue = value;
>                 filter.TriggerFilterChange( value );
> 
>                 return InvokeAsync( StateHasChanged );
>             } ) );
> 
>             builder.AddAttribute( 3, "class", string.IsNullOrEmpty( filter.SearchValue ) ? "" : "filter-active" );
> 
>             builder.CloseComponent();
>         };
> 
>         return base.OnInitializedAsync();
>     }
> }
> ```

With this example i'm able to define a common FilterTemplate, but StateAsChanged is not invoked for DataGrid, don't know why. After change filter value, I have to click somewhere else to see the data filtered.

> This?
> 
> ```cs
> this.DisplayTemplate = ( item ) => ( builder ) =>
>         {
>             builder.OpenElement( 6, "span" );
> 
>             builder.AddContent( 7, ( item as DataGridPage.Employee )?.FirstName );
> 
>             builder.CloseElement();
>         };
> ```

Just as @David-Moreira i'm trying to define some common behaviour, so i should do something like GetValue(item), to get the value defined by "Field", but GetValue is internal. 

That is just a nive to have, because i can always use reflection and implement my owm GetValue.

@David-Moreira sorry for using your issue, but helped me a lot 😊. I was able to do what i wanted, i just have to figure why statehaschanged is not triggered.

**Comment by David-Moreira** [comment]
I was just retesting this now. That's the exact problem I'm having... it just doesn't sync up... :( No idea why yet. It's driving me crazy!! :P
No problem @paulosdfigueiredo you're trying the same thing, and this is helpfull to define common content which has some more dynamic aspects to it.

**Comment by David-Moreira** [comment]
Well... adding this to the callback does work.. since it does inform the parent to refresh... 
this.ParentDataGrid.Reload();
Might be a good workaround while we don't figure it out.

**Comment by paulosdfigueiredo** [comment]
The function triggered in DataGrid is OnFilterChanged, maybe it should trigger StateHasChanged too...

```
protected internal Task OnFilterChanged( DataGridColumn<TItem> column, string value )
{
	column.Filter.SearchValue = value;
	dirtyFilter = dirtyView = true;

	if ( ManualReadMode )
		return HandleReadData( CancellationToken.None );

	return Task.CompletedTask;
}
```

Now i don't understand how default filters trigger StateHasChanged 🤔

**Comment by David-Moreira** [comment]
I know Blazor behind the scenes calls StateHasChanged itself in certain places.

I was taking a look at the generated code from microsoft on the component file and it's quite similar to ours. My guess it that we should not do this on Initialized, since it does not have knowledge of the originall builder, but here:         
**`protected override void BuildRenderTree(RenderTreeBuilder builder)`** 

I have had success with this pertaining the state has changed, but it now creates two columns instead of one. :P
(And you don't need the microsoft type check boilerplate, I was just copying it)
```
public class DataGridFilterColumn2<TItem> : DataGridColumn<TItem>
{
    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        //base.BuildRenderTree(builder);

        builder.OpenComponent<Blazorise.DataGrid.DataGridColumn<TItem>>(0);
        builder.AddAttribute(1, "Field", Field);
        builder.AddAttribute(2, "Caption", Caption);

        builder.AddAttribute(10, "FilterTemplate", (Microsoft.AspNetCore.Components.RenderFragment<Blazorise.DataGrid.FilterContext>)((context) => (__builder3) =>
        {
            __builder3.OpenComponent<Blazorise.TextEdit>(11);
            __builder3.AddAttribute(12, "Text",
                Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(context.SearchValue));

            __builder3.AddAttribute(13, "TextChanged",
                Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(
                    Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, x => { context.SearchValue = x; context.TriggerFilterChange(x); })));

            __builder3.AddAttribute(14, "test", string.IsNullOrWhiteSpace(context.SearchValue) ? "" : "filter-active");
            __builder3.CloseComponent();
        }));

        builder.CloseComponent();
    }
}
```

**Comment by David-Moreira** [comment]
Never mind my rant about overriding the `BuildRenderTree`, it doesn't quite make sense for these type of components that render stuff mainly based on their state (properties) and not their markdown.

I think we were on the right track. I just changed the method you mentioned to call StateHasChanged and it works. 

If using static data, the workaround of calling the ParentDataGrid.Reload is enough for this case.
If using ReadData, then the ReadData itself has a StateHasChanged. 

I'll be trying tomorrow to implement this on the project I'm working on, but I think my problem is solved, Thanks guys!

**Comment by stsrki** [comment]
The main thing to know here is that `DataGridColumn` is just giving information to the `DataGrid` on how to build itself. The column on its own does nothing(or almost nothing). That's why calling `this.ParentDataGrid.Reload()` worked. Column changed and Datagrid just picked those changes.

**Comment by David-Moreira** [comment]
Problem solved. Thanks for helping. Closing....

**Comment by stsrki** [comment]
What was the solution? 😁

**Comment by David-Moreira** [comment]
> I tried this and it kinda works. But I'm still not sure what you want to accomplish.
> 
> **MyColumn.razor**
> 
> ```
> @typeparam TItem
> @inherits DataGridColumn<TItem>
> @code{
>     protected override Task OnInitializedAsync()
>     {
>         this.FilterTemplate = ( filter ) => ( builder ) =>
>         {
>             builder.OpenComponent<TextEdit>( 0 );
> 
>             builder.AddAttribute( 1, nameof( TextEdit.Text ), filter.SearchValue );
>             builder.AddAttribute( 2, nameof( TextEdit.TextChanged ), EventCallback.Factory.Create<string>( this, ( value ) =>
>             {
>                 filter.SearchValue = value;
>                 filter.TriggerFilterChange( value );
> 
>                 return InvokeAsync( StateHasChanged );
>             } ) );
> 
>             builder.AddAttribute( 3, "class", string.IsNullOrEmpty( filter.SearchValue ) ? "" : "filter-active" );
> 
>             builder.CloseComponent();
>         };
> 
>         return base.OnInitializedAsync();
>     }
> }
> ```

Oh, pretty similar to the code you gave, just added this `ParentDataGrid.Reload` to the `TextChanged` callback since like we've talked `TriggerFilterChange `does not trigger a `StateHasChanged`, and `return InvokeAsync( StateHasChanged );` itself in this context, is not enough to notify the parent datagrid itself there have been changes:
>If using static data, the workaround of calling the ParentDataGrid.Reload is enough for this case.
>If using ReadData, then the ReadData itself has a StateHasChanged.
