### ISSUE TITLE
DataGrid - Resize triggers sort

### ISSUE THREAD

**Issue by paulosdfigueiredo** [stsrki/Blazorise#1928]
**Describe the bug**
When DataGrid is resizable, clicking on the "resize line", the column on the left triggers Sort.

This happens with both ResizeModes, even if we click it out of the Header with ResizeMode.Column.

**To Reproduce**
1. Open Demo
2. With resize and sort enabled, click/drag "resize line" to resize the column.

**Comment by stsrki** [comment]
@David-Moreira can you investigate?

**Comment by David-Moreira** [comment]
Confirmed, most of the times ends up triggering sort. I didn't notice when testing, maybe I was too focused on the resizing. :P
I'll fix it.
