### ISSUE TITLE
Using regular edit and create by going to a different page

### ISSUE THREAD

**Issue by manasimahajann** [stsrki/Blazorise#1929]
**Describe the bug**
This is not a bug - I am not sure if this is already been answered.
I am trying to use regular create and edit button in the overview screen as there are just too many fields to enter.

```
                             @foreach (var Sale in Sales)
                             {
                                    <a href="@($"Salesedit/{Sale.SalesId}")" class="btn btn-primary table-btn">
                                        <i class="fas fa-edit"></i>
                                    </a>
                             }
```

Is there a way - we could use a button(navigates to a different page) in the Datagrid

**Comment by stsrki** [comment]
Maybe button link?

```cshtml
<Button To="@($"Salesedit/1")" Type="ButtonType.Link" Color="Color.Primary">
    <Icon Name="IconName.Edit" />
</Button>
```

**Comment by manasimahajann** [comment]
oh great.. so this could go inside <EditCommandTemplate> tag..?
how could we be able to get salesid dynamically there instead of 1?

**Comment by David-Moreira** [comment]
Adding to @stsrki answer. And to your most recent question about grabbing the SalesId in the DataGrid.

That DataGrid is composed by DataGridColumns amongst a few other components.
And this should be what're you looking for, it's a column inside the DataGridColumns component of the DataGrid, you can either use the DataGridCommandColumn which is a column dedicated to Commands, or just add your own column with the Button, both of these options have access to a "context" Parameter where you can grab your item(Sale) properties.
```
<DataGridCommandColumn TItem="Sale" Width="170px">
      <EditCommandTemplate>
          <Button To="@($"Salesedit/{context.Item.SalesId}")" Type="ButtonType.Link" Color="Color.Primary">
              <Icon Name="IconName.Edit" />
          </Button>
          <Button Color="Color.Primary"  Clicked="@context.Clicked">@context.LocalizationString</Button>
      </EditCommandTemplate>
</DataGridCommandColumn>
```

**Comment by manasimahajann** [comment]
oh good. this works. Thank you both for your help.
@David-Moreira  -- Thank you. are you talking about this docs link for datagrid examples [](https://blazorise.com/docs/extensions/datagrid/)

**Comment by David-Moreira** [comment]
Glad to help. :D
Yes, those. They're pretty good and there should be some examples accessing context.

**Comment by manasimahajann** [comment]
Sure.  Thank you! :)
