### ISSUE TITLE
Is there a way - we can remove Delete button from DataGrid

### ISSUE THREAD

**Issue by manasimahajann** [stsrki/Blazorise#1931]
Sorry to bother you..
I have set Editable="true" on DataGrid ..
Is there a way .. We can not display delete button? - I do not see any tag specific to delete button in DataGrid.

Thank you for your help.

Thank you,
Manasi

**Comment by manasimahajann** [comment]
---
Adding to this I just found https://blazorise.com/docs/release-notes/release087/
 In DataGridCommandColumn tag set DeleteCommandAllowed = "false" 
 
 I must be missing something .. as I am reading more -- this is already been worked on :)

**Comment by David-Moreira** [comment]
Yes  DeleteCommandAllowed="false" should not display neither the default DeleteCommand or the DeleteCommandTemplate if you have provided it.
It should work, but you can also try to just provide it an empty template:
                            
```
        <DeleteCommandTemplate >
        </DeleteCommandTemplate>
```

**Comment by stsrki** [comment]
Hi @manasimahajann 

As @David-Moreira already answered, DeleteCommandAllowed should hide the Delete button. And on top of that, you can define an empty `DeleteCommandTemplate`.
