### ISSUE TITLE
Suggestion: match attribute on the button

### ISSUE THREAD

**Issue by drma-dev** [stsrki/Blazorise#1934]
Since the button component also behaves like a link, it should have the match attribute. If the person tries to use buttons on the bar, like me. :)

**Comment by stsrki** [comment]
The button with `a href` is just used to show a link as a regular button. It was never meant to be used or behave like Bar items or other Link's for that matter.

I don't want it to have too much logic, and it's best to leave it as generic as possible. You can always make it active by setting the `Active` parameter yourself.

**Comment by drma-dev** [comment]
@stsrki 
I tried this approach, but the site stops working.

the scenario is as follows: several buttons of type link and using the active attribute. after a few clicks, the site crashes and the links stop working. After a lot of research, I noticed that it was only because of the active attribute. I removed them and now I'm using another approach.

**Comment by stsrki** [comment]
That's strange. The `Active` attribute should not make the app go crashing. It's just a different styling of a button, nothing else. Are you sure you don't have any null reference or something else crashing the site?

**Comment by drma-dev** [comment]
I went to test it again to make sure it wasn't some other error involved. But no, there is really something wrong with this attribute.
