### ISSUE TITLE
Brave Rewards

### ISSUE THREAD

**Issue by AjaxSantos** [stsrki/Blazorise#1936]
Hey,
i would like to spend your something over the project "[Brave Rewards](https://brave.com/de/brave-rewards/)". But you are not verified, so that i can not send your some BAT's.
Do you think, that you will be verified in future?

**Comment by stsrki** [comment]
Hmm I don't think i heard abou Brave rewards before. Seems like i good idea, in theory. What are the benefits if I sign up?

**Comment by AjaxSantos** [comment]
Everybody, who use the Brave browser and get advertising about it, can send you active or automatical crypto money.
You can set up the browser, so that everybody, who be verified, you visit, get some money.
That crypto money you can into "real" money. https://creators.brave.com/
