### ISSUE TITLE
Snackbar seems broken in version 0.9.3

### ISSUE THREAD

**Issue by Jimmys20** [stsrki/Blazorise#1944]
I noticed some visual problem with Snackbar in Blazorise version 0.9.3. When Snackbar is not visible it still takes space at the bottom of the html document.

To reproduce: I cloned the Blazorise github repository. Checked out dev-093 branch run the Blazorise.Demo.Bootstrap project and navigate to General UI page.

![Snackbar](https://user-images.githubusercontent.com/34100964/109661485-b2221b80-7b72-11eb-85c9-91c9254f54fd.jpg)

**Comment by stsrki** [comment]
I was able to reproduce it. It is because I changed `position: fixed;` into `position: absolute;`. Thanks for reporting it!

**Comment by Jimmys20** [comment]
Wow that was fast! :)

**Comment by stsrki** [comment]
I got to act fast. Release is around the corner 😄
