### ISSUE TITLE
Datagrid: MultiSelectAll not auto unselecting when 1 item unselected.

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#1947]
Hello @stsrki overall, so far so good. I only found this problem. Which I'll take a look on Blazorise later today. 

When only 1 item, it does not seem to be unselecting the multi select all, while it does work on the other cases.
Still not sure if it's my fault on the project I'm working on, or smthg on Blazorise Datagrid, I'll be first trying to replicate on Blazorise Datagrid later today.
![image](https://user-images.githubusercontent.com/22283161/109786512-22797d00-7c05-11eb-89a6-557e2ed1715f.png)

**Comment by stsrki** [comment]
Hi @David-Moreira, it would be great if you could fix it soon. I'm just writing final release notes and updating docs before release.

**Comment by David-Moreira** [comment]
Alright, then I'll try to take a look on my lunch time!(in about 3h) :P See if it's something on blazorise end or not. I'll let you know.

**Comment by stsrki** [comment]
I feel guilty for stealing your time 🙈

**Comment by David-Moreira** [comment]
No problem. My bad. It's a bug, where we're syncronizing the state of the multi select all check according to the current state of the Grid. Forgot to add a case, to uncheck when there are no SelectedRows.
Only happens when there's only one row, new Indeterminate feature logic was hiding it. I'll submit a PR soon.

Also I think the feature ended with too many ifs. :X I might review, if there's a more readable way to do it in 0.9.4 if you don't mind.

**Comment by David-Moreira** [comment]
Not sure why PR did not auto close. Solved closing.
