### ISSUE TITLE
Toggled Sidebar 

### ISSUE THREAD

**Issue by ZhangYue-vhyt** [stsrki/Blazorise#195]
# Code
`MainLayout.razor`
```
@inherits MainLayoutCode

<Sidebar @ref="sidebar">
    <SidebarContent>
        <SidebarBrand>
            <a href="#">
                Sidebar Brand
            </a>
        </SidebarBrand>
    </SidebarContent>
</Sidebar>

<div class="app-main">
    <Bar Breakpoint="Breakpoint.Desktop" ThemeContrast="ThemeContrast.Dark" Background="Background.Dark">
        <BarBrand>
            Bar Brand
        </BarBrand>
        <BarToggler Clicked="sidebar.Toggle" />
    </Bar>

    <div class="app-content">
        @Body
    </div>
</div>
```
`MainLayout.razor.cs`
```
namespace BlazorClient.Shared
{
    public class MainLayoutCode : LayoutComponentBase
    {
        protected Sidebar sidebar;
    }
}
```

# Problem
The height of toggled sidebar is not zero. Firefox, Chrome and Edge have the same behavior. 
Do I miss something, such as CSS?

![image](https://i.imgur.com/ZiZjvSM.gif)

**Comment by stsrki** [comment]
Have a look at [demo.css](https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/wwwroot/demo.css)

**Comment by ZhangYue-vhyt** [comment]
Thank you, This .css works. 
Another question, how can I achieve this layout?

![image](https://user-images.githubusercontent.com/9450184/63002598-de9b1780-bea8-11e9-928e-11d29b1bd746.png)
