### ISSUE TITLE
Blazor Validation not working when using Child Component

### ISSUE THREAD

**Issue by rifatozturk** [stsrki/Blazorise#1953]
I have a component (lets say **_ParentComponent.razor_**) that uses modal with validations and its elements. 

```
<Modal @ref="CreateModal">
    <ModalBackdrop />
    <ModalContent IsCentered="true">
        <Form id="CreateForm">
            <ModalHeader>
                <ModalTitle>New</ModalTitle>
                <CloseButton Clicked="CloseCreateModal"></CloseButton>
            </ModalHeader>
            <ModalBody>
                <Validations Mode="ValidationMode.Auto" Model="CreateModal" ValidateOnLoad="false">

                    ...

                    <Validation>
                        <Field>
                            <FieldLabel>Test Field Name</FieldLabel>
                            <Select TValue="Guid?" @bind-SelectedValue="@Model="CreateModal.TestDataId">
                                @foreach (var data in TestData)
                                {
                                    <SelectItem TValue="Guid" Value="@data.Id">
                                        @data.Name
                                    </SelectItem>                                    
                                }
                            </Select>
                        </Field>
                    </Validation>

                    ...

            </ModalBody>
            <ModalFooter>
                ...
            </ModalFooter>
        </Form>
    </ModalContent>
</Modal>
```

I also have annotations like [Required] on my model class with no problem.
With these options, auto validation just works fine.

But, when I move `<Select> ... </Select>` component into another component (lets say _**ChildComponent.razor**_) and replace <Select... part on my ParentComponent.razor with `<ChildComponent> ... </ChildComponent>` the validation doesn't work.

After a little research I ended up with this:
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#nested-models-collection-types-and-complex-types

So, after I read microsoft's document, I figured out that the DataAnnotationsValidator only validates top-level properties of the model bound to the form that aren't collection- or complex-type properties.

And I want to apply the following solution as refered :

> To validate the bound model's entire object graph, including collection- and complex-type properties, use the **ObjectGraphDataAnnotationsValidator** provided by the experimental [Microsoft.AspNetCore.Components.DataAnnotations.Validation](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation) package.
...
> Annotate model properties with [ValidateComplexType]. In the following model classes, the ShipDescription class contains additional data annotations to validate when the model is bound to the form:

Can you help me? Thanks.

**Comment by stsrki** [comment]
To tell you the truth I didn't know it will only work with top-level properties. I use the same validation process internally so it will not work and I will need to investigate more about `<ObjectGraphDataAnnotationsValidator />`.

BTW, you need to have the same TValue for both Select and SelectItem, (`TValue="Guid?"`).

**Comment by rifatozturk** [comment]
OK then, I am waiting for your research. (Y)
(I had just wrote the code above for a quick example, everything is as it should be in my original code, but thanks for your notice.)

**Comment by murat-yuceer** [comment]
Hi @stsrki we have same problem i using blozorise with abp

**Comment by stsrki** [comment]
@rifatozturk Can you show how you define parameters for **ChildComponent.razor** component?

**Comment by rifatozturk** [comment]
> @rifatozturk Can you show how you define parameters for **ChildComponent.razor** component?

@stsrki I am sending you the all code parts :

_**Genders.razor**_ _(ParentComponent.razor)_
```
...
<Modal @ref="CreateGenderModal">
    <ModalBackdrop />
    <ModalContent IsCentered="true">
        <Form id="CreateGenderForm">
            <ModalHeader>
                <ModalTitle>"NewGender</ModalTitle>
                <CloseButton Clicked="CloseCreateGenderModal" />
            </ModalHeader>
            <ModalBody>
                <Validations @ref="@NewGenderValidations"
                            Mode="ValidationMode.Auto"
                            Model="@NewGender"
                            ValidateOnLoad="false">

                    ...

                    <Validation>
                        <Field>
                            <FieldLabel>"Code"</FieldLabel>
                            <GenderSelector @bind-Value="@NewGender.Code">
                                <ValidationFeedback>
                                    <ValidationError />
                                </ValidationFeedback>
                            </GenderSelector>
                        </Field>
                     </Validation>
					
		     ...
					
	    </ModalBody>
            <ModalFooter>
		<Button Color="Color.Secondary" Clicked="CloseCreateGenderModal">
                  "Cancel"
                </Button>
                <Button Type="Blazorise.ButtonType.Submit" PreventDefaultOnSubmit="true" Color="Color.Primary" Clicked="CreateGenderAsync">
                   "Save"
                </Button>
            </ModalFooter>
        </Form>
    </ModalContent>
</Modal>
...
```

**_GenderSelector.razor_** _(ChildComponent.razor)_
```
<NumericEdit TValue="int?" @bind-Value="Value">
    <Feedback>
        @if (ValidationFeedback != null)
        {
            @ValidationFeedback
        }
    </Feedback>
</NumericEdit>

@code {
    private int? _value;
    [Parameter]
    public int? Value {
        get => _value;
        set
        {
            if (value == _value) return;
            _value = value;
            ValueChanged.InvokeAsync(_value);
        }
    }

    [Parameter]
    public EventCallback<int?> ValueChanged { get; set; }

    [Parameter]
    public RenderFragment ValidationFeedback { get; set; }
}
```

**_Genders.razor.cs_**
```
public partial class Genders
    {
        ...

        private GenderCreateDto NewGender { get; set; }

        ...
        
        public Genders()
        {
            ...
            NewGender = new GenderCreateDto();
            ...
        }
        ...
        private async Task CreateGenderAsync()
        {
            if (NewGenderValidations.ValidateAll())
            {
                await GenderAppService.CreateAsync(NewGender);
                await GetGendersAsync();
                CreateGenderModal.Hide();
            }
        }
       ...
    }
```

**_GenderCreateDto.cs_**
```
public class GenderCreateDto
    {
        ...
        [Required]
        public int? Code { get; set; }
        ...
    }
```

**Comment by stsrki** [comment]
In `GenderSelector.razor` add

```cs
[Parameter]
public Expression<Func<int?>> ValueExpression { get; set; }
```

and

```cshtml
<NumericEdit TValue="int?" @bind-Value="Value" ValueExpression="@ValueExpression">
```

And if that doesn't work do:

```cshtml
<NumericEdit TValue="int?" Value="@Value" ValueChanged="@OnValueChanged" ValueExpression="@ValueExpression">
@code{
  Task OnValueChanged(int? value)
  {
    Value = value;
    return Task.CompletedTask;
  }
}
```

**Comment by murat-yuceer** [comment]
hi @stsrki 

if we add child
[Parameter]
public Expression<Func<int?>> ValueExpression { get; set; }

what we have to change from parent?
<GenderSelector @bind-Value="@NewGender.Code">
                                <ValidationFeedback>
                                    <ValidationError />
                                </ValidationFeedback>
                            </GenderSelector>

**Comment by stsrki** [comment]
@murat-yuceer Nothing. It will be automatically picked by the Blazor whenever you have `@bind-`.

See https://mladenmacanovic.com/2021/01/19/blazor-expression.html

**Comment by rifatozturk** [comment]
> In `GenderSelector.razor` add
> 
> ```cs
> [Parameter]
> public Expression<Func<int?>> ValueExpression { get; set; }
> ```
> 
> and
> 
> ```
> <NumericEdit TValue="int?" @bind-Value="Value" ValueExpression="@ValueExpression">
> ```
> 
> And if that doesn't work do:
> 
> ```
> <NumericEdit TValue="int?" Value="@Value" ValueChanged="@OnValueChanged" ValueExpression="@ValueExpression">
> @code{
>   Task OnValueChanged(int? value)
>   {
>     Value = value;
>     return Task.CompletedTask;
>   }
> }
> ```

Great! ValueExpression solved my problem. Thanks.
