### ISSUE TITLE
How to use IIdGenerator in tests to create repeatable Ids?

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#1955]
I'm taking a look into the new IIdGenerator interface that can be used as a service to generate repeatable ids (thanks for creating this). 

Can I please have some guidance how to use it to generate repeatable Ids for my tests AND keep the JS working!

I've got a simple implementation of the generator working:
   ```
 class MockIdGenerator : IIdGenerator
    {
        public string Generate => "TESTID";
    }
```
but obviously the JS breaks because  the ids are all the same.

**Comment by stsrki** [comment]
If you want to have the same ID for the test components why you don't use ElementId and define it for each component.

eg.

```cshtml
<Button ElementId="TESTBTN">Click</Button>
<Button ElementId="TESTBTN2">Click 2</Button>
```

**Comment by robalexclark** [comment]
Thats actually a great idea and I'll start doing that - thanks!
