### ISSUE TITLE
SelectedValueChanged callback of DropdownList

### ISSUE THREAD

**Issue by tacoWanneeJama** [stsrki/Blazorise#1956]
**Describe the bug**

With the latest 0.9.3 version I get a compile-error for a SelectedValueChanged callback of a DropdownList

cannot convert from 
'Microsoft.AspNetCore.Components.EventCallback' to 
'Microsoft.AspNetCore.Components.EventCallback<object>'	

With the previous version (0.9.2.5) it compiles OK.

The error is in part: SelectedValueChanged="@OverrideKeyChangedHandler"

My function is like:
 protected async void OverrideKeyChangedHandler(object newValue){.........}

Should we use another syntax with this versions of Blazorise?

**To Reproduce**

**Expected behavior**

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**

**Comment by stsrki** [comment]
You probably didn't follow the migration guide: https://blazorise.com/news/release-notes/093/#migration-

TValue and TItem are now required. Look at the documentation for example https://blazorise.com/docs/extensions/dropdownlist/

**Comment by tacoWanneeJama** [comment]
Mladen,


Thank you for the quick response. I could not find the release notes and migration guide. But I am sure this will solve the problem.


Regards, Taco Wannee

________________________________
Van: Mladen Macanović <notifications@github.com>
Verzonden: donderdag 4 maart 2021 11:33:06
Aan: stsrki/Blazorise
CC: Taco Wannee; Author
Onderwerp: Re: [stsrki/Blazorise] SelectedValueChanged callback of DropdownList (#1956)


You probably didn't follow the migration guide: https://blazorise.com/news/release-notes/093/#migration-

TValue and TItem are now required. Look at the documentation for example https://blazorise.com/docs/extensions/dropdownlist/

**Comment by stsrki** [comment]
Closing now, if you have any problems please reopen.
