### ISSUE TITLE
Major/minor ticks on Blazorise.Charts

### ISSUE THREAD

**Issue by Ozzyz** [stsrki/Blazorise#1957]
Hey! Thank you for the great library. It has been really nice to use so far, but I am struggling with customizing Blazorise.Charts for my needs.
I am trying to create a chart where the labels only appear on the major ticks. Currently, it seems to me that Charts only support a 1:1 relationship between labels and datapoints. For instance, I would like to have one datapoint per hour, but only labels per day. I.e labels on major ticks, but minor ticks in between. 
The example below (taken from matplotlib). 
![image](https://user-images.githubusercontent.com/6113447/109944805-e31b6100-7cd6-11eb-9c35-388b112a3560.png)
![image](https://user-images.githubusercontent.com/6113447/109956428-ee28be00-7ce3-11eb-84b3-7d3956bd5495.png)

I have tried creating a `LineChartOptions` object, but the `AxisTicks` object does not seem to contain any reference to step size or similar, only references to fontsize, display etc. 

**Suggsted solution**
Introduce a step-size variable to ticks, [similar to chart.js](https://www.chartjs.org/docs/latest/axes/cartesian/linear.html#step-size) 
So a similar solution in the OptionsObject could be something like a StepSize in `AxisTicks` if I understand this options object correctly.

```
LineChartOptions opts = new LineChartOptions
    {
        Scales = new Scales
        {
            XAxes = new List<Axis>
            {
                new Axis
                {
                    Ticks = new AxisTicks
                    { 
                        StepSize = 0.5
                    }
                }
            }
        }
    };
``` 
Alternatively, drawing labels per Nth datapoint would also be an acceptable solution for my use case.

If I understand it correctly, it is maybe possible to specify this in the OptionsJsonString (similar to #480), but it would be nice if this was supported in the OptionsObject.

**Comment by stsrki** [comment]
You can use `OptionsObject` to build an anonymous object which will then be properly serialized. This is much better option than using OptionsJsonString as it is somewhat similar to how JSON objects are built.

Example

```cs
object chartOptions = new
{
    Scales = new
    {
        XAxes = new[] {
            new {
                Ticks = new
                {
                    StepSize = 0.5
                }
            }
        }
    }
};
```

And then apply it `<LineChart @ref="lineChart" TItem="double" OptionsObject="@chartOptions" />`

I agree that it should also exist in the option and I can add it soon.

**Comment by Ozzyz** [comment]
Great! Thanks for the quick response :)
