### ISSUE TITLE
Hamburger Menu Drop Down Not Correct when Browser is Refreshed

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1959]
I stumbled across this behavior in my own app and can reproduce it in the [Blazorise demo](https://bootstrapdemo.blazorise.com/) app.

Steps to Repro:
1. Resize browser so that hamburger menu is visible (see screenshot).
2. Click hamburger menu -- the menu drops down properly.
3. Refresh browser.
4. Click hamburger menu -- the menu is messed up.

Not a big deal for me, but thought I'd mention it.

![image](https://user-images.githubusercontent.com/4267021/109989694-bebf8480-7cd6-11eb-97e4-9c19ae9efad2.png)

**Comment by stsrki** [comment]
I was able to reproduce it. Thank you for the report.
