### ISSUE TITLE
Charts - Support AddData

### ISSUE THREAD

**Issue by LukasDufka** [stsrki/Blazorise#196]
Is it possible to add a single data item to the chart, or can I change only the entire data set?

Source:
Blazorise.Charts.Base.BaseChart - AddDataSet()

Thank you for response.

**Comment by stsrki** [comment]
Blazorise.Charts are using [charts.js](https://www.chartjs.org/) and they are required to use datasets. I think nothing stops you from sending one point to the dataset.

eg
```
new LineChartDataset<double>
{
    Label = "# of randoms",
    Data = new List<double> { 105 },
    // other settings
}
```

**Comment by LukasDufka** [comment]
Uh, of course. Thank you, I misread the source code.
