### ISSUE TITLE
Can not reload with Blazorise 0.9.3.0

### ISSUE THREAD

**Issue by KroMignon** [stsrki/Blazorise#1962]
**Describe the bug**
I have updated my Blazor WebAssembly project from Blazorise 0.9.2.5 to 0.9.3.0.
All works fine, until I reload. After reload, the site layout is broken.

**To Reproduce**
1. Build the project with Visual Studio.
2. Run in (with Ctrl+F5)
3. Click on reload

When rolling back to 09.2.5 all works fine.

**Comment by stsrki** [comment]
I'm unable to reproduce. All works fine on my side. Can you create a small project to reproduce the issue?

**Comment by andreatosato** [comment]
I have no problem with reload button_

**Comment by jipjan** [comment]
no problem here either

**Comment by KroMignon** [comment]
@stsrki @andreatosato @jipjan Thanks for your time.

I am very busy today, I will try to create ASAP a minimal project to show my problem.
My feeling is that it has to do with the page layout / **Bar** item.

But, as I have begun developing with Blazor for 2 months ago, it could also be my fault, by miss using something!

**Comment by KroMignon** [comment]
@stsrki @andreatosato @jipja 
Finally, I found why my app is crashing on refresh with Blazorise 0.9.3.0!

I had a problem with Blazorise 0.9.2.5 to setup focus to a **TextEdit**, so I use what @stsrki suggest me (see https://github.com/stsrki/Blazorise/discussions/1778).

By removing the ` InvokeAsync(() => loginText.Focus());` call in `OnAfterRenderAsync()` and using **AutoFocus** which is now available all works fine again 👍
