### ISSUE TITLE
Mixed Chart without Line fill

### ISSUE THREAD

**Issue by kachna96** [stsrki/Blazorise#1963]
Hello, I'm fighting with one issue regarding mixed charts (bar/line)
By default, the Line chart [is set to be filled ](https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.Charts/ChartData.cs#L137)
Unfortunately, it doesn't look very nice in my mixed chart a I can't find a way around it, because the Datasets I'm providing to the chart have to be of type BarChartDataset and they don't have Fill property
![image](https://user-images.githubusercontent.com/22668596/110073500-c4bd7000-7d7f-11eb-9bdd-be39864c2549.png)

Do you know by any chance how I might remove the filled part? Could serializing it directly to an Options object be a way?

Thanks!

**Comment by stsrki** [comment]
Seems to work just fine. Just need to use `Chart` component.

```cshtml
<Chart @ref="mixedChart" TItem="double" Type="ChartType.Bar" />

@code{
    Chart<double> mixedChart;
    bool isAlreadyInitialised;

    protected override async Task OnAfterRenderAsync( bool firstRender )
    {
        if ( !isAlreadyInitialised )
        {
            isAlreadyInitialised = true;

            await mixedChart.Clear();
            await mixedChart.AddLabelsDatasetsAndUpdate( Labels, GetMixedChartDataset() );
        }
    }

    ChartDataset<double>[] GetMixedChartDataset()
    {
        return new ChartDataset<double>[]
        {
            new BarChartDataset<double>
            {
                Label = "# of randoms",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                BorderWidth = 1,
                Type = "bar",
                Order = 1,
            },
            new LineChartDataset<double>
            {
                Label = "# of randoms",
                Data = RandomizeData(),
                BackgroundColor = backgroundColors,
                BorderColor = borderColors,
                Fill = false,
                PointRadius = 3,
                BorderWidth = 1,
                PointBorderColor = Enumerable.Repeat( borderColors.First(), 6 ).ToList(),
                Type = "line",
                Order = 2,
            },
        };
    }
}
```

**Comment by stsrki** [comment]
![image](https://user-images.githubusercontent.com/900302/110082337-7e6f0d80-7d8d-11eb-8b17-cae2e4199a6e.png)

**Comment by kachna96** [comment]
Thank you very much, it's working now for me as well if I change my code based on your example
I tried to use the generic chart before but it didn't work as expected, because I didn't specify the Type property in <Chart>, but it's all good now
Thanks again!
![image](https://user-images.githubusercontent.com/22668596/110090242-5ab0c500-7d97-11eb-83e5-3c395922b968.png)
