### ISSUE TITLE
ModalBackdrop

### ISSUE THREAD

**Issue by stevenlupo** [stsrki/Blazorise#1967]
Did something happen that caused `ModalBackdrop` to become unrecognized by Visual Studio? I think it started after upgrading Blazorise to the latest.

`Found markup element with unexpected name 'ModalBackdrop'. If this is intended to be a component, add a @using directive for its namespace.`

I also no longer see it in Intellisense when I type: `<Blazorise.`

It still builds though, although the problem is categorized as an Error and shows in the Error List window.

**Comment by paulosdfigueiredo** [comment]
ModalBackdrop was removed.

You can read the breaking changes and migration steps in the release notes.

https://blazorise.com/news/release-notes/093

**Comment by stsrki** [comment]
As @paulosdfigueiredo mention, ModalBackdrop is obsolete and you can remove it.
