### ISSUE TITLE
Setting basic colors via theme

### ISSUE THREAD

**Issue by seyfeb** [stsrki/Blazorise#1968]
I didn’t find any info in the documentation or the issues regarding this, although I’m certainly not the first one wondering, so first of all: sorry!

(How) Can I define the default text and link color using a theme? For the text I tried setting

```
 private readonly Theme theme = new Theme()
    {
        TextColorOptions = new ThemeTextColorOptions()
        {
            Body = "#FF0000"
        }
    }
```

and expected all `<Text>` and `<Paragraph>` components to have a red font as default. For `<Link>` I didn’t even have a suspicion which property I could set. Any input would be much appreciated! :)

I’m using v0.9.3.

**Comment by stsrki** [comment]
The `Body = "#FF0000"` will work as a variant color eg. `<Text Color="TextColor.Body"></Text>`. The same is for `<Paragraph>`. It is not going to be applied as the default color. To make the default color you would need to add some custom CSS targeting `<p>` element.

As of `<Link>`, there is no additional theme setting. It is just a regular `<a>` with some navigational helpers. No styling whatsoever.

**Comment by seyfeb** [comment]
Thanks for your quick reply. If I may ask, what is the reasoning behind not setting a default color? It seems cumbersome to manually set the property on every element. Especially if you want to switch between themes you have to be sure to have set the color to `Color.Body` on each text element otherwise the, e.g.,  black text in a light theme won't be converted to white text in a dark theme.

**Comment by stsrki** [comment]
I'm not sure what you mean. The purpose of theming is to override all colors that are using that same variant. It's basically overwriting these https://getbootstrap.com/docs/4.1/utilities/colors/

**Comment by InzeNL** [comment]
Currently, `Link` does not have a `Color` attribute (See (https://getbootstrap.com/docs/4.1/utilities/colors/)[https://getbootstrap.com/docs/4.1/utilities/colors/] "Primary link"). It might be an idea to add this?
Would just work the same as the `Color` attribute for `Paragraph` or `Text`

**Comment by stsrki** [comment]
I can try adding colors for `<Link>` component.
