### ISSUE TITLE
FluentValidation sample

### ISSUE THREAD

**Issue by andreatosato** [stsrki/Blazorise#1971]
Hi, I need sample for FluentValidation.
I see this for 0.9.3 version:

https://github.com/stsrki/Blazorise/blob/0b50988ea6b6d1535ba8f49f87b600b495507f80/docs/_posts/2021-03-03-release-notes-093.md#validation

I need to create FluentValidationHandler?

@stsrki 

Thanks a lot

I create 
```html
<Validation HandlerType="typeof(ReviewValidator)" />
```

```cs
public class ReviewValidator : AbstractValidator<ReviewInsertModel>
{
        public ReviewValidator()
        {
            RuleFor(t => t.User).SetValidator(new UserInsertValidator());
        }
}

 public class UserInsertValidator : AbstractValidator<UserInsertModel>
    {
        public UserInsertValidator()
        {
            RuleFor(f => f.FirstName).NotEmpty();
        }
    }
```

But not work

**Comment by stsrki** [comment]
It needs to be inherited from `IValidationHandler` and then you implement fluent logic in `Validate` method.

```cs
public class YourValidationHandler : IValidationHandler
{
    /// <inheritdoc/>
    public void Validate( IValidation validation, object newValidationValue )
    {
        validation.NotifyValidationStarted();

        // do something here

        validation.NotifyValidationStatusChanged( validatorEventArgs.Status, matchMessages );
    }
}
```

**Comment by andreatosato** [comment]
Do HandlerType validate only single field?
<Validation HandlerType="typeof(FluentValidationHandler)" /> 

I want to validate all form field with single FluentValidatorHandler. Can I do this?

**Comment by stsrki** [comment]
Yes, it validates on a per-field basis. Just like all other validators. Essentially with `HandlerType="typeof(FluentValidationHandler)"` you're overriding built-in validators with your custom implementation. So however you implement is entirely up to you. With `IValidationHandler` and `IValidation` you have API access to all the information needed to do the validation.

To tell you the truth I'm not that familiar with the fluent validator, but by seeing this `RuleFor(f => f.FirstName).NotEmpty();` I think you want to have the rule for every field on your model. Correct me if I am wrong! So, maybe you can somehow use the information from `validation.FieldIdentifier`. It will give you a model and field name.

**Comment by stsrki** [comment]
It might help you https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/

**Comment by andreatosato** [comment]
FluentValidator validates every single field in a model.
I expected there to be a single validation method for the entire form.

**Comment by stsrki** [comment]
That is what `Validations` is supposed to be for.

**Comment by andreatosato** [comment]
@stsrki yes, I use it before blazorise, but Blazorise validation is very complete.
I'd like it to work for the entire form, a bit like it does for DataAnnotations.
I had already used a workaround to make FluentValidation work with Validations.
I thought there was a new way to natively support them.

[Latest issue](https://github.com/stsrki/Blazorise/issues/838)

**Comment by stsrki** [comment]
I understand. Well, i have the plan to create a new validations extension for Blazorise that will be just for fluent validation. So as part of it it can also work in the way you're familiar with.

**Comment by adamhathcock** [comment]
I did this:
```
 public class FluentValidator<TValidator> : IValidationHandler 
        where TValidator: IValidator, new()
    {
        public void Validate(IValidation validation, object newValidationValue)
        {
            var validator = new TValidator();

            var context = new ValidationContext<object>(newValidationValue);
            var validationResult = validator.Validate(context);

            if (validationResult.IsValid)
            {
                validation.NotifyValidationStatusChanged(ValidationStatus.Success, new List<string>());
            }
            else
            {
                var messages = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
                validation.NotifyValidationStatusChanged( ValidationStatus.Error, messages );
            }
        }
    }
 ```

Need to add to DI:
`services.AddTransient(typeof(FluentValidator<>));`

And then I could use on a control:
`<Validation HandlerType="typeof(FluentValidator<CustomDateRangeValidator>)">`

The validator was derived from `AbstractValidator<T>`

**Comment by niem94** [comment]
@stsrki I've been playing around with this and can't get it to work. Fluent Validation validates properties against its model, and is not able to validate single values. I tried to work around this problem by using reflection with `validation.FieldIdentifier`, but this property is not populated with any data, so it impossible to translate the incoming value to a model that Fluent Validation can validate on. Any idea why FieldIdentifier wouldn't be populated?

This is my code: 

```csharp
            if (newValidationValue == null) return;
            validation.NotifyValidationStarted();
            var validator = new TValidator();
            //Only true when newValidationValue is not a primitive type.
            if (validator.CanValidateInstancesOfType(newValidationValue.GetType()))
            {
                var context = new ValidationContext<object>(newValidationValue);
                var validationResult = validator.Validate(context);

                if (validationResult.IsValid)
                {
                    validation.NotifyValidationStatusChanged(ValidationStatus.Success);
                }
                else
                {
                    var messages = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
                    validation.NotifyValidationStatusChanged(ValidationStatus.Error, messages);
                }
            }

            //Is not populated. Why?
            var fieldIdentifier = validation.FieldIdentifier;

            //I need the name of the field and model to validate the single property in the model like so:
            var properties = new[] { fieldIdentifier.FieldName };
            var context = new ValidationContext<IValidatable>((IValidatable)fieldIdentifier.Model, new PropertyChain(),
                new MemberNameValidatorSelector(properties));
            var validationResult = validator.Validate(context);
            if (validationResult.IsValid)
            {
                validation.NotifyValidationStatusChanged(ValidationStatus.Success);
            }
            else
            {
                var messages = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
                validation.NotifyValidationStatusChanged(ValidationStatus.Error, messages);
            }
```

And it is used like so in a DataGrid:
```csharp
 <DataGridColumn TItem="Role" Field="@nameof(Role.Description)" Caption="Description" Sortable="true"
                    Editable="true">
        <EditTemplate>
            <Validation HandlerType="typeof(FluentValidationHandler)">
                <TextEdit Placeholder="Type a description..." Text="@((string) context.CellValue)"
                          TextChanged="@(v => context.CellValue = v)">
                    <Feedback>
                        <ValidationError/>
                    </Feedback>
                </TextEdit>
            </Validation>
        </EditTemplate>
    </DataGridColumn>
```

**Comment by stsrki** [comment]
It's not populated because you didn't give it any information about the model field. I wrote an article about this _secret_ Blazor feature a while ago https://mladenmacanovic.com/2021/01/19/blazor-expression.html

The TextEdit should look like this:

```cshtml
<TextEdit Placeholder="Type a description..."
    Text="@((string) context.CellValue)"
    TextChanged="@(v => context.CellValue = v)"
    TextExpression="@(()=>(string)context.CellValue)">
```

Although there might be a problem with `context` 🤔. It is not part of any model but a value in the dictionary. Anyways, try it and let me know.

**Comment by niem94** [comment]
@stsrki Thank you it worked like this:

```csharp
<TextEdit Placeholder="Type a name..." Text="@((string)context.CellValue)"
    TextChanged="@(v => context.CellValue = v)" TextExpression="@(() => context.Item.Name)">
    <Feedback>
        <ValidationError />
    </Feedback>
</TextEdit>
```

I'm a bit confused with the context.CellValue and context.Item. What is the preferred way to use these, and is there any articles about the inner workings?
In the above solution the context.Item seems unneeded (which it probably isn't) if I use the context.CellValue to save the value from the TextField.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/26203420/113909332-dad3ab80-97d7-11eb-984b-57c143a9513a.png">

**Comment by stsrki** [comment]
I added `context.Item` only recently because a lot of people wanted to get access to the underline item that is being edited. Just keep in mind that you should use it only for reading. While you can write to it directly it is not advised since basically you skip the DataGrid logic and that can lead to some unwanted scenarios.

**Comment by niem94** [comment]
Ahh makes sense! I haven't seen it before either, so I was pretty confused about it. It's a godsend in cases like this.

Seems Fluent Validation will work pretty well with these new changes. I will add a comment with an updated FluentValidationHandler and some info on how i use it for reference, when I have finished the logic in it :-)

**Comment by stsrki** [comment]
@niem94 Thanks that would be great. Maybe I could finally write some new article with your help 😊

**Comment by niem94** [comment]
So this is the approach i choose to go with:

```csharp
public class FluentValidationHandler<TValidator> : IValidationHandler
    where TValidator : IValidator, new()
{
    public void Validate(IValidation validation, object value)
    {
        var validator = new TValidator();

        if (value != null && validator.CanValidateInstancesOfType(value.GetType()))
        {
            ValidateInstance(validation, validator, value);
            return;
        }

        ValidateProperty(validation, validator, value);
    }

    public static void ValidateInstance(IValidation validation, TValidator validator, object value)
    {
        validation.NotifyValidationStarted();
        var context = new ValidationContext<object>(value);
        var validationResult = validator.Validate(context);

        if (validationResult.IsValid)
        {
            validation.NotifyValidationStatusChanged(ValidationStatus.Success);
            return;
        }

        var messages = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
        validation.NotifyValidationStatusChanged(ValidationStatus.Error, messages);
    }

    private static void ValidateProperty(IValidation validation, TValidator validator, object value)
    {
        validation.NotifyValidationStarted();
        var fieldName = validation.FieldIdentifier.FieldName;
        var model = CreateModelWithPopulatedProperty(value, validation.FieldIdentifier);
        var properties = new[] { validation.FieldIdentifier.FieldName };
        var context = new ValidationContext<IValidatable>((IValidatable)model, new PropertyChain(),
            new MemberNameValidatorSelector(properties));
        var validationResult = validator.Validate(context);
        if (validationResult.IsValid)
        {
            validation.NotifyValidationStatusChanged(ValidationStatus.Success);
            return;
        }
        var messages = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
        validation.NotifyValidationStatusChanged(ValidationStatus.Error, messages);
    }

    public static object CreateModelWithPopulatedProperty(object newValidationValue, FieldIdentifier fieldIdentifier)
    {
        var model = Activator.CreateInstance(fieldIdentifier.Model.GetType());
        var propertyInfo = model.GetType().GetProperty(fieldIdentifier.FieldName);
        var convertedValue = Convert.ChangeType(newValidationValue, propertyInfo.PropertyType);
        propertyInfo.SetValue(model, convertedValue, null);
        return model;
    }
}
```

This makes the fluent validation able to be handled mostly by blazor internals. All that is needed is to add FluenValidators to to the application aswell as the above FluentValidationHandler.

```csharp
builder.Services.AddValidatorsFromAssembly(currentAssembly);
builder.Services.AddTransient(typeof(FluentValidationHandler<>));
```

Then validation will work when the HandlerType is set, and TextExpression points to the property that the CellValue matches up against. This is important for FluentValidation, as  FluentValidation validates against models and not just values.

```csharp
<Validation HandlerType="typeof(FluentValidationHandler<RoleValidator>)">
  <TextEdit Text="@((string)context.CellValue)" TextChanged="@(v => context.CellValue = v)" TextExpression="@(() => context.Item.PropertyName)">
      <Feedback>
          <ValidationError />
      </Feedback>
  </TextEdit>
</Validation>
```

**Comment by stsrki** [comment]
@niem94 Looking good. Although a little more reflection than needed, it works. Maybe it can be improved with Expressions and prrebuild/cached methods.

Regarding the Select and other inputs. It should work the same for all of them. Internally in Blazorise handlers, I don't have anything special for them. They all go through the same validation process. Must be the same for FluentValidationHandler.

**Comment by niem94** [comment]
@stsrki I'm not very knowledgeable with Expressions and prebuild/cache methods, so if that is possible, I would need some reference code to get me started. But I was kind of hoping I could find a way to instantiate an object that did not rely on reflection. :-)

Good to hear, I am currently looking into this. The only problem for me is that Selects cant handle complex objects, which makes it a bit more challenging to make work.

**Comment by stsrki** [comment]
Expressions can be hard to grasp at the beginning but in the long run, they're worth the effort when performance is critical.

You can find some simple example in DataGrid source: https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.DataGrid/Utils/FunctionCompiler.cs#L137

Those are just for getters and setters. Once compiled they are cached and can be reused without using reflection every time.

PS. I might at some point create a utility package for fluent validation, based on your code :)

**Comment by niem94** [comment]
@stsrki Is this better? :-)

```csharp
 private static object CreateModelWithPopulatedProperty(object value, FieldIdentifier fieldIdentifier)
{
    var model = Activator.CreateInstance(fieldIdentifier.Model.GetType());
    SetPropertyValue(model, fieldIdentifier.FieldName, value);
    return model;
}

public static object SetPropertyValue(object target, string fieldName, object value)
{
    var constant = Expression.Constant(target);
    var memberExpression = Expression.Property(constant, fieldName);
    if (memberExpression != null)
    {
        if (memberExpression.Member is not PropertyInfo property)
            throw new ArgumentException($"{nameof(fieldName)} is not specified.");
        var convertedValue = Convert.ChangeType(value, property.PropertyType);
        property.SetValue(target, convertedValue, null);
    }

    return target;
}
```

**Comment by stsrki** [comment]
> @stsrki Is this better? :-)
> 
> ```cs
> private static object CreateModelWithPopulatedProperty(object value, FieldIdentifier fieldIdentifier)
> {
>     var model = Activator.CreateInstance(fieldIdentifier.Model.GetType());
>     SetPropertyValue(model, fieldIdentifier.FieldName, value);
>     return model;
> }
> 
> public static object SetPropertyValue(object target, string fieldName, object value)
> {
>     var constant = Expression.Constant(target);
>     var memberExpression = Expression.Property(constant, fieldName);
>     if (memberExpression != null)
>     {
>         if (memberExpression.Member is not PropertyInfo property)
>             throw new ArgumentException($"{nameof(fieldName)} is not specified.");
>         var convertedValue = Convert.ChangeType(value, property.PropertyType);
>         property.SetValue(target, convertedValue, null);
>     }
> 
>     return target;
> }
> ```

Yes, looking cleaner now :)

**Comment by ryanbuening** [comment]
Is this FluentValidation sample available somewhere or linked in the docs? I think it would help a lot of devs get started as FluentValidation is commonly used in .NET/Blazor projects.

**Comment by stsrki** [comment]
No, it's still not. We plan to make it part of Blazorise as an extension package. Probably for the next milestone.

**Comment by stsrki** [comment]
@knight1219 the PR is still open. Just need to fix one small bug before it is merged. Probably next week I will also release preview packages.
