### ISSUE TITLE
Mixed chart glitch when awaiting Task.Delay

### ISSUE THREAD

**Issue by kachna96** [stsrki/Blazorise#1981]
**Describe the bug**
Hello, I came across one weird issue when using Mixed (Line&Bar) charts. The Line chart Filled property is not respected when I'm simulating awaiting call from API with data. When I remove the call, it works as expected.

**To Reproduce**
<Blazorise.Charts.Chart @ref="MixedChart" TItem="int" Type="Blazorise.Charts.ChartType.Bar" />

    Chart<int> MixedChart;

    private readonly List<string> _backgroundColors = new()
    {
        ChartColor.FromRgba(255, 99, 132, 0.8f),
        ChartColor.FromRgba(54, 162, 235, 0.8f)
    };

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await Task.Delay(1000); // Simulate getting data from API, Chart renders as expected when I remove this line

            await MixedChart.Clear();
            await MixedChart.AddLabelsDatasetsAndUpdate(new[] { "A", "B", "C" }, GetMixedChartDataset());
        }
    }

    ChartDataset<int>[] GetMixedChartDataset()
    {
        return new ChartDataset<int>[]
        {
            new BarChartDataset<int>
            {
                Label = "Bar Data",
                Data = new List<int>{1, 2, 3},
                BackgroundColor = _backgroundColors[0],
                Type = "bar"
            },
            new LineChartDataset<int>
            {
                Label = "Line Data",
                Data = new List<int>{4, 5, 6},
                Fill = false,
                BackgroundColor = _backgroundColors[1],
                Type = "line"
            },
        };
    }

**Expected behavior**

![image](https://user-images.githubusercontent.com/22668596/110306549-402c5500-7ffe-11eb-84be-daddf0ed5922.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/22668596/110306665-59cd9c80-7ffe-11eb-9c6d-22a7b526c39d.png)

**Comment by stsrki** [comment]
This will fix it:

`<Blazorise.Charts.Chart @ref="@MixedChart" TItem="int" OptionsObject="@options" Type="Blazorise.Charts.ChartType.Bar" />`

```cs
object options = new
    {
        Elements = new
        {
            Line = new
            {
                Fill = false
            }
        }
    };
```

**Comment by stsrki** [comment]
Taken from https://stackoverflow.com/questions/38222345/chartjs-line-charts-remove-color-underneath-lines

**Comment by kachna96** [comment]
I does fix it, thank you! So I guess this is not a bug but a feature?

**Comment by stsrki** [comment]
I would guess it is how chartjs works 🤷‍♂️ 😅

**Comment by kachna96** [comment]
I see, thanks again, I'm closing this :)
