### ISSUE TITLE
[QUESTION] CommandMode

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#1986]
`CommandMode `is only shown if `ShowPager `is true, is it normal behavior?

**Comment by stsrki** [comment]
Yes, in the current implementation `CommandMode` with `ButtonRow` is only visible if the pager is enabled.

@David-Moreira maybe we can refactor it a little and instead of making button row part of the pagination we wrap everything in one parent component. eg

- `<_FooterComponent>` is basically a row with two columns
  - `<_ButtonRow>`
  - `<_Pagination>`

This way they can be shown separately.

**Comment by angelru** [comment]
I think this proposal would be good, also how can I show ButtonRowTemplate above the table? appears below with pager

**Comment by stsrki** [comment]
How do you mean "over DataGrid"?

**Comment by angelru** [comment]
above the DataGrid, sorry

**Comment by David-Moreira** [comment]
Yes at the moment, it's coupled with the pager. 
We already had ideas to make it more decoupled, by being able to fully customize the pager, but having to expose the API.
However the FooterComponent seems like a good idea and we'll also need an HeaderComponent.

You should be able to display pager on top too. There should be a Parameter that sets the `PagerPosition`! I think the parameter is actually missing on the docs, but you should be able to find it on the Datagrid.
There's algo a good demo here that shows it: 
https://bootstrapdemo.blazorise.com/tests/datagrid
![image](https://user-images.githubusercontent.com/22283161/110456700-c9f12680-80c1-11eb-9c58-773dfe073b1a.png)

**Comment by angelru** [comment]
thanks, `PagePosition `was what I was missing, I agree that undocking it offers more flexibility, `FooterComponent `and `HeaderComponent `seems like a good idea as I want to have `ButtonRowTemplate `at the top of the table and the pager at the bottom.

**Comment by angelru** [comment]
Is this fixed? I'm still using the hack provided by @David-Moreira 

```
.data-grid .row.justify-content-between:nth-child(3) .col-auto.d-flex:first-child {
    display: none !important;
}

.data-grid .row.justify-content-between:first-child .col-auto.d-flex:nth-child(2) {
    display: none !important;
}

.data-grid .row.justify-content-between:first-child .col-auto.d-flex:nth-child(3) {
    display: none !important;
}
```

**Comment by David-Moreira** [comment]
@strski mind reopening? Proposal still seems good to you? Assign to me if so.
