### ISSUE TITLE
Allow to trigger a DataGrid column sort by code

### ISSUE THREAD

**Issue by cwinland** [stsrki/Blazorise#1993]
Problem:
I currently use DataGrid single column sort. Clicking on a column works great, but I cannot trigger it outside of that. I need to be able to tell the grid to sort by a specific column via code.

Solution: 
It would be nice to be able to "refresh" data with a custom sort and/or filter on demand. You could either allow us to change the column data in the arguments OR provide a sort method that either changes the sort for the current column or allows the developer to specify another column. Examples:
Specific column: grid.Sort(column, direction) 
Current column: grid.Sort(direction) 

I can make the changes if you would allow it.

**Comment by stsrki** [comment]
You can define the initial sort for the column by parameter `Direction="SortDirection.Descending"`. After that, it will behave as usual.

Regarding the API to control the grid from the outside, it is still in the planning stage. While I would appreciate the help at this time it is still too early. Once we come up with first prototype we can proceed with adding additional APIs, and you can also help.

**Comment by cwinland** [comment]
That initial sort will help the functionality some.  Thanks and please keep in touch when you would like some assistance.
