### ISSUE TITLE
Rating Components

### ISSUE THREAD

**Issue by andreatosato** [stsrki/Blazorise#1996]
Hi blazorise team,
I have created Rating component, but I need to color **Icon**.
Can I color Icon?
My component [code](https://github.com/andreatosato/AwesomeBlazorise/tree/main/src/AwesomeBlazor/Components/Rating)

Preview
![2021-03-09_21h52_46](https://user-images.githubusercontent.com/24985956/110536812-2e43d280-8122-11eb-8a92-3e8022e4cf9d.gif)

I think that this component is basic and can it add in blazorise library. What do you think?

**Comment by stsrki** [comment]
It looks good. I also started work on a rating component but didn't finish it yet. Your seems to have more features. If you want you can create a PR and I can see into it.

**Comment by andreatosato** [comment]
Can I add pull request to new branch?
I create this commit in my [github repo](https://github.com/andreatosato/Blazorise/commit/bcaa999de5e120f7565afbe60e59f80ddae33154)

**Comment by stsrki** [comment]
Yes, follow this guide to contribute https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md#branch-organization

**Comment by stsrki** [comment]
I think its best to make it part of `Blazorise.Components` project

**Comment by andreatosato** [comment]
I want to create branch feature... dev094-rating. 
How can I create new branch?

**Comment by stsrki** [comment]
You checkout(switch) to dev094 branch, and then create new branch from it, Everything can be done in VS.

![image](https://user-images.githubusercontent.com/900302/110850366-fd91a380-82af-11eb-9b11-664fb6419cbf.png)

**Comment by andreatosato** [comment]
No, I want to create new branch on my pull request. 
I create this pull #2017 on dev094 branch.

**Comment by WillianGruber** [comment]
Why don't you accept the values of the icons as string, so we can pass our own icons? Something like emptyItemIcon and filledItemIcon? I would have an use for this. Of course, the default could be filled and empty stars.

**Comment by andreatosato** [comment]
I accept:
```
[Parameter] public string FullIcon { get; set; }
[Parameter] public string EmptyIcon { get; set; }
```

But i think that I need to accept also
```
[Parameter] public string FullIconStyle { get; set; }
[Parameter] public string EmptyIconStyle { get; set; }
```
So I can manage FontAwesome or Material
