### ISSUE TITLE
v0.9.3 - HorizontalBarChart not working (Material)

### ISSUE THREAD

**Issue by vamsitp** [stsrki/Blazorise#1999]
Doesn't display any bars... The bottom-right chart here repros the issue...
https://materialdemo.blazorise.com/tests/livecharts
![image](https://user-images.githubusercontent.com/1181198/110599597-0c416300-81a9-11eb-8512-20e02c85d8e9.png)

**Comment by stsrki** [comment]
Nice catch. Thanks.
