### ISSUE TITLE
Documentation for Modal

### ISSUE THREAD

**Issue by richbryant** [stsrki/Blazorise#2]
I know docs are a work in progress but I'm determined to test every part of this.

Do you think you could throw something together?

Thanks.

(Incidentally, my app is now looking absolutely lovely).

**Comment by stsrki** [comment]
I'm really glad that you like the product :)

Can you please explain what you mean by throw something together? Do you want some specific part of documentation explained or something else?

**Comment by richbryant** [comment]
I mean that I know Modal dialogs work because they're in your demo apps.  But they're not in the documentation and I'd like to put my implementation of Jwt/AspNet Identity Registration/Login in a modal dialog to demonstrate doing it right.

**Comment by stsrki** [comment]
There's not much that I could tell you that you already don't know. Basically you can just place a button in the modal footer and  just do the login logic inside the button clicked event. From there you should call your login api and then save the jwt token in session or cookie.
I have a full login implemented but can write it tomorrow when I got home.

**Comment by richbryant** [comment]
god no, don't do Login.  I can the JWT stuff, all I really want is some documentation on your implementation of Modal, such as what attributes it has, how to centre and size it, that kind of thing.

I did some guessing so far and it's okay but I hit compile errors every time I guess at a property that the Blazor class doesn't expose so it's quite slow going.

**Comment by stsrki** [comment]
I completely misunderstood you. Anyways I have just published modals section in the documentation so have a look.
