### ISSUE TITLE
DataGrid : Sorting

### ISSUE THREAD

**Issue by jerpic** [stsrki/Blazorise#2000]
Hello,

I hope you are doing well.

Currently, the sorting feature seems to work only on the current page (when pager is active), so that means that the sorting feature works on the client side. Is there a way to get the sort columns through an event (may be)  in order to pass them to the OnReadData function ? The objective is to realize the sort in the server side.

Best Regards,

**Comment by stsrki** [comment]
You have all information in `e.Columns`. Note that you will implement all your sorting on the server. This will give only information on how to sort.

![image](https://user-images.githubusercontent.com/900302/110609217-4a308e00-818d-11eb-897e-524f2c9d850c.png)
