### ISSUE TITLE
DataGrid : Cell Event

### ISSUE THREAD

**Issue by jerpic** [stsrki/Blazorise#2005]
Hello,

Is there a way to intercept an event when the user make a **right-click** on a cell? The objective is to filter the data with the value of the current selected cell.

In fact, is it possible to have the property @oncontextmenu on the datagrid?

Best Regards,

**Comment by stsrki** [comment]
Click event is only available on a row with RowClicked and RowDoubleClicked events.

But, you can use DisplayTemplate and handle cell click yourself, eg.

```cshtml
<DataGridColumn TItem="Employee" Field="@nameof( Employee.City )" Caption="City" Editable="true">
    <DisplayTemplate>
        <span @oncontextmenu="@OnContextMenu">@context.City</span>
    </DisplayTemplate>
</DataGridColumn>
```

**Comment by jerpic** [comment]
Hi,

Thanks for your answer, that works fine.

Regards,
