### ISSUE TITLE
AutoComplete MinLength doesn't work as intended

### ISSUE THREAD

**Issue by ivancavlek** [stsrki/Blazorise#2006]
Hi,

As I understand, the MinLength in AutoComplete should prevent SearchChanged event from firing if the length of a searched string is less than MinLength. If that is so, then there is a bug, because the event is being fired at any length of a query.

My razor configuration is the following:
```
<Autocomplete
                  TItem="InsideVirtualGroupDto"
                  TValue="Guid"
                  Data="_virtualGroupRepositoryData"
                  Disabled="!IsEnabled"
                  Filter="AutocompleteFilter.Contains"
                  TextField="@(group => group.Name)"
                  ValueField="@(group => group.Id)"
                  DelayTextOnKeyPress="true"
                  DelayTextOnKeyPressInterval="300"
                  MinLength="3"
                  SearchChanged="OnSearchVirtualGroupRepositoryData"
                  SelectedValue="_virtualGroupSelectedId"
                  SelectedValueChanged="OnSelectVirtualGroupRetrievedData" />
```

Backend code is:
```
private async void OnSearchVirtualGroupRepositoryData(string searchParameter)
{
    Console.WriteLine($"Ivan - {(string.IsNullOrWhiteSpace(searchParameter) ? 0 : searchParameter.Length)}");

    // Code omitted
   
    StateHasChanged();
}
```

It doesn't matter what's the length of the string I enter in AutoComplete, SearchChanged is always fired, except when it's null or empty.

I have the latest version of Blazorise, v0.9.3, although this didn't work in the previous version as well.

Ivan

**Comment by paulosdfigueiredo** [comment]
Reading the documentation we have the following:
```
SearchChanged | Occurs on every search text change.
MinLength | Minimum number of character needed to start search.
```
I believe that SearchChanged should not be affected by MinLength, it indicates that something has changed in search text. MinLength is used internaly to decide if it should filter the data or not.

**Comment by ivancavlek** [comment]
@paulosdfigueiredo, I don't agree.

MinLength has no meaning to be publicly available if that's true. It should prevent unnecessary search firing, i.e., not initiating an event if certain circumstances are not met (length and e.g. time delay between key strokes, which btw. works fine).

Except that, what does it filter in data?

**Comment by paulosdfigueiredo** [comment]
SearchTextChanged is different from SearchFired. 

There's no "SearchFired" event, but if there was one, i agree that should be affected by MinLength.

**Comment by stsrki** [comment]
SearchChanged should always be called, whenever something is written in the input field. It has nothing to do with MinLength.

MinLength controls the visibility of the dropdown menu and filtering. Meaning filtering will be triggered only when the searched text length has reached the MinLength.
