### ISSUE TITLE
Datagrid: Resize feature: js should always check if exists even if halfway through work

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#2008]
Hello @stsrki 
I noticed this:
It's not that easy to reproduce, but has to do, with immediately closing a grid while it still is running the initial rendering process. I kinda only noticed because I have an app with various tabs(similar to the browser tabs) that each have grids, and I was closing them all quickly.

I have to investigate, if I remember correctly we do have a check at the begin of the JS, but it probably happens when it already is halfway through the work. So additional checks should be in place.
Microsoft.JSInterop.JSException: Cannot read property 'querySelectorAll' of null TypeError: Cannot read property 'querySelectorAll' of null     at Object.initResizable (-/_content/Blazorise.DataGrid/blazorise.datagrid.js:7:28)

**Comment by stsrki** [comment]
So `querySelectorAll` breaks in the middle of the work because the elements were removed from DOM? Makes sense to add more null checks in between?

**Comment by stsrki** [comment]
I will put it on the support for fixing.

If you start first, the branch is **sup093**.

**Comment by David-Moreira** [comment]
I think I have enough time today. I'll be on it.
