### ISSUE TITLE
Datagrid: Multiselect: Shift+click

### ISSUE THREAD

**Issue by David-Moreira** [stsrki/Blazorise#2009]
Hello @stsrki ,
I find myself wanting to select multiple records by shift clicking when I'm testing stuff on the grids. It's a somewhat common feature when selecting various records. 

So shift clicking, selects from the currently selected index(the last normal clicked index) to the index that has been shift clicked. 
Also when shift clicking to somewhere between selected records. It will unselect the records farther away from the selected index vs shift clicked index.

When taking a look at for example: Outlook. they consider the starting index to be the last normal clicked index like described above.

I think it's a good feature to add, what do you think?

**Comment by stsrki** [comment]
Oh yeah, I do that all the time whenever I need to select multiple items. Well with every new feature the number of even more new features frows exponentially 😅

Do I assign this to you?

**Comment by David-Moreira** [comment]
Ya, you can assign this to me. :)
