### ISSUE TITLE
DataGrid's Modal/Popup behaviour

### ISSUE THREAD

**Issue by Lorenz5600** [stsrki/Blazorise#2030]
Hi,

when editing a data row in popup mode, the modal window accidentally closes very often, e.g. when you leftclick-select the content of a textfield and release the mouse button outside the window.

Is there any chance to override this behaviour, e.g. by hooking into it's closing event?

Thanks in advance,

Stefan

**Comment by stsrki** [comment]
As far as I can see there is no way to override it. To fix it I will need to change it on the Blazorise side.

It's not very often for people to do make this behavior so I think it's not a priority. But in any case, I will try to fix it for the next patch.
