### ISSUE TITLE
Add missing features to DataGrid

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#204]
## Styling

- [x] Striped
- [x] Bordered
- [x] Borderless
- [x] Hoverable
- [x] Narrow

## Behavior

- [x] Unselect already selected row
- [x] Disable selection of rows if any row is currently being edited

## Customization

- [x] Popup editing mode
- [x] Template(s) for custom command buttons

**Comment by dinhduongha** [comment]
How about custom event handler for New/Edit/Delete?
For example:
-User must be confirm before call Http Api to delete the record.
-Add new/Edit: We can display a popup dialog for input data, (not in-grid editing).

**Comment by stsrki** [comment]
@dinhduongha 
1. You already have cancelable events on DataGrid. They're named `RowRemoving` and `RowSaving`
2. Popup was already planned for 0.8.2 but after the release of Blazor p8 I had to move it to 0.8.3 so I don't loose too much time before the release.
3. Still figuring this one but I thunk it will not be a problem.

**Comment by cherron4113** [comment]
is there a way to programmatically deselct the seleted row so no row is selected?

**Comment by stsrki** [comment]
@cherron4113 There is no at the moment. Can you open new issue? This one is old and already closed.
