### ISSUE TITLE
JSException when viewed on Edge mobile app

### ISSUE THREAD

**Issue by mtbayley** [stsrki/Blazorise#2044]
**Describe the bug**
Client side exception (blazor server)

Callsite: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.ReportUnhandledException
Exception: Microsoft.JSInterop.JSException: Could not find 'blazorise.button.initialize' ('blazorise' was undefined).
Error: Could not find 'blazorise.button.initialize' ('blazorise' was undefined).

**To Reproduce**

1. Create a blazor server app, add some blazorise controls to the page.
2. View the page on Edge app (android)
3. Buttons do not respond to user input

**Additional context**
Also occurs with
blazorise.numericEdit.initialize
blazorise.textEdit.initialize

Might occur with other browsers as well. Still testing.
Reverting to 0.9.2.5 fixed the issue

**Comment by stsrki** [comment]
I'm unable to reproduce. Can you create a small project for testing, and push it on GitHub?

**Comment by mtbayley** [comment]
I was able to recreate this with
https://github.com/mtbayley/BlazoriseJSExceptionTest

**Comment by mtbayley** [comment]
I have only been able to recreate this with Edge on mobile. That being said, I am getting many logs from other users and browsers having this same issue.
![image](https://user-images.githubusercontent.com/34929316/111341529-fa037100-864f-11eb-8248-d30fa7801215.png)

**Comment by stsrki** [comment]
You need to move `<script src="_framework/blazor.server.js"></script>` at the end of body element.

**Comment by stsrki** [comment]
Strange. That fixed it for me 🤔

**Comment by mtbayley** [comment]
It's only Edge chrome which is the problem for me. All other browsers seem to work just fine. The exception is thrown when the page loads

**Comment by mtbayley** [comment]
Here's the stack trace from the edge mobile client:

```
Microsoft.JSInterop.JSException: Could not find 'blazorise.button.initialize' ('blazorise' was undefined).
Error: Could not find 'blazorise.button.initialize' ('blazorise' was undefined).
    at http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:67390
    at Array.forEach (<anonymous>)
    at e.findFunction (http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:67350)
    at v (http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:69092)
    at http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:70038
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:70011)
    at http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://192.168.2.10/BlazoriseJSExceptionTest/_framework/blazor.server.js:1:26263)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Button.<OnInitialized>b__9_0()
   at Blazorise.Base.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by David-Moreira** [comment]
Hello, 
I haven't tested it, but is there any way you can you take a look at the dev tools and making sure blazorise.js is actually being loaded on your environment? From the error, either the js isn't being loaded, or there's some specific js that's not being interpreted successfully by the browser. At least, that's what it looks like to me from the error.

**Comment by mtbayley** [comment]
@David-Moreira I was able to debug the Edge mobile app via remote debugging [https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/)
I can confirm that if I set a breakpoint on the blazorise.button.initialize method in the blazorise.js file, it is not hit. If I do the same thing in Chrome mobile, the breakpoints are hit.

**Comment by David-Moreira** [comment]
I see. Can you access an actual online site with Blazorise without that error. Like for example the demo? 
https://bootstrapdemo.blazorise.com/tests/buttons
That seems like it might be blocked by some setting on the browser or something. Who knows might have something blocked with requets from localhost.

And do you actually have access to other developer tools on your environment like the console or the network?
![image](https://user-images.githubusercontent.com/22283161/112047102-bd9aae00-8b44-11eb-9777-79d4094986bc.png)

**Comment by mtbayley** [comment]
![blazor](https://user-images.githubusercontent.com/34929316/112203632-220f4900-8be9-11eb-8901-116b35c30b36.gif)

**Comment by mtbayley** [comment]
The demo throws exceptions in the console. The network traffic shows the blazorise.js file. Here's the log from the console
[bootstrapdemo.blazorise.com-1616526502316.log](https://github.com/stsrki/Blazorise/files/6192150/bootstrapdemo.blazorise.com-1616526502316.log)
There's one exception I haven't noticed before: Unexpected token
![image](https://user-images.githubusercontent.com/34929316/112204268-d90bc480-8be9-11eb-9002-3e322e5f3b23.png)

**Comment by David-Moreira** [comment]
Weird, I use edge on my mobile phone. Those pages work just fine.
Can you confirm your mobile browser version? My version is Edge 46.02.4.5152

Here's the refrence for that js feature: 
There's a version reference at the bottom. Every modern browser should support it by now. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by mtbayley** [comment]
I'm on the same version - 46.02.4.5152. I tried re-installing the app also

**Comment by mtbayley** [comment]
If you go to edge://flags on your mobile. What is your version there? Mine says 77.0.3865.116 Which looks like it's behind the required version of 80

**Comment by David-Moreira** [comment]
The same. 77.0.3865.116
This is gonna be hard to track. Either way do you also have an error on your own app on the exact same place?
The "?." optional chaining, feature?

**Comment by mtbayley** [comment]
Yes, The same error occurs in my test app above

**Comment by David-Moreira** [comment]
Can you copy. Blazorise.js modify it and load it into your app removing the optional chaining by a normal null check? Just to be sure it solves all your problems.

**Comment by stsrki** [comment]
To me also looks like optional chaining could be an issue. But as far as I know, all major browsers support it by now. Even edge as it is on chromium.

**Comment by David-Moreira** [comment]
Yea. My thoughts are edge mobile may actually be behind the actual standards. And the reason it works on mine and not on my batley's is that they sometimes rollout some features only on some installations.

**Comment by stsrki** [comment]
I feel like IE era is till here 🤣

**Comment by mtbayley** [comment]
https://github.com/mtbayley/Blazorise/commit/620a114f8c69256b39dee76bee464b963e85aec8

Changing this resolved all of my issues.

According to this, edge on android is using the older 77 version. I can't find a time estimate when they will update this! This might be the only current browser not supporting this feature.
[https://techcommunity.microsoft.com/t5/discussions/why-edge-on-android-is-using-super-old-chromium-engine/m-p/1223145](https://techcommunity.microsoft.com/t5/discussions/why-edge-on-android-is-using-super-old-chromium-engine/m-p/1223145)

**Comment by stsrki** [comment]
That's a shame.

OK I will change the optional chaining and release it with next patch.
