### ISSUE TITLE
Extension documentation missing

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#2049]
Looks like extension docs are missing from: https://blazorise.com/docs/

**Comment by stsrki** [comment]
Not sure what you mean. They're still there

![image](https://user-images.githubusercontent.com/900302/111377307-c6046c00-86a0-11eb-9af0-af7b092b9638.png)

**Comment by njannink** [comment]
ahh I see it now. The scrollbar for the menu is only visible on mouseover. So thats why I didnt see it
