### ISSUE TITLE
Debug symbols for Blazorise

### ISSUE THREAD

**Issue by Jossec101** [stsrki/Blazorise#2054]
Hey there, 
**Is your feature request related to a problem? Please describe.**
Sometimes I have the need to check any potential bug in the library (or mine) but I cannot debug Blazorise without symbols.

**Describe the solution you'd like**
Is it possible @stsrki to provide the symbols for debugging the code with the [nuget symbol server?](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)

**Comment by stsrki** [comment]
I must admit this is the first time I hear about `.snupkg`. As far as I can see there shouldn't be a problem. 

I will release the, with the next patch once it is ready. Is that OK?

**Comment by Jossec101** [comment]
Yes, I think so, I have debugged other public libraries this way and it greatly reduces the time to debug the nuget, this can lead to more detection of bugs for the great blazorise project!

Best ;)
