### ISSUE TITLE
SideBarNavigation doesn't display drop down arrow with upgrade of Blazorise.Bootstrap and Blazorise.Icons.FontAwesome.

### ISSUE THREAD

**Issue by BrandonH333** [stsrki/Blazorise#2066]
**To Reproduce**
1. Update Blazorise.Bootstrap and Blazorise.Icons.FontAwesome from v0.9.2.5 to v0.9.3.0 or v0.9.3.1
2. Notice the side bar navigation is missing drop down arrows for menu items with side bar sub items.

**Comment by paulosdfigueiredo** [comment]
Maybe your first step should be "read the migration guide" 😋

https://blazorise.com/news/release-notes/093/#migration-

**Comment by stsrki** [comment]
As @paulosdfigueiredo said, please follow the migration guide. And don't forget to clear the browser cache, Ctrl+F5 usually helps.

**Comment by BrandonH333** [comment]
The screenshots below are after upgrading.  This is not a caching issue.  The drop down arrow image is removed on upgrade and comes back on downgrade.  I don't see anything in the migration guide regarding this but seems like just a minor thing anyways.  Functionality is not broken.

![image](https://user-images.githubusercontent.com/71057273/111812637-8fdc0d80-8895-11eb-84ab-686c24625a69.png)

![image](https://user-images.githubusercontent.com/71057273/111812073-f6146080-8894-11eb-8c45-62aa00a5c4d9.png)

**Comment by stsrki** [comment]
I was able to reproduce. Indeed I have changed some things regarding the internal Link component and since Sidebar is obsolete I didn't test it. I will fix it for the next patch.
