### ISSUE TITLE
Enhancement: Disable button when Command can't execute

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#2067]
When you assign a `Command` to a `Button` it would be nice if the `Disabled` property of the `Button` would listen to the `ICommand.CanExecute(parameter)` and the `ICommand.CanExecuteChanged` event.

**Comment by stsrki** [comment]
Can you explain better? To tell you the truth I'm not that familiar with IComand.

The `Disabled` is checked before executing the command

```cs
protected async Task ClickHandler()
{
    if ( !Disabled )
    {
        await Clicked.InvokeAsync( null );

        if ( Command?.CanExecute( CommandParameter ) ?? false )
        {
            Command.Execute( CommandParameter );
        }
    }
}
```

**Comment by njannink** [comment]
I will have a look if I can make a PR for this.

Mainly what should happen is that when you set the `Command` or `CommandParameter` property of a button that you check the `CanExecute` method of the ICommand and disable the button when this returns false. Also there is an event `ICommand.CanExecuteChanged` that you should listen to.

This is also how a Wpf button works.

**Comment by David-Moreira** [comment]
Hello, 
How does this affect normal clicking? On the Web, we do have javascript to consider. Does this affect javascript in any way? I might not want the button to disable automatically and still execute bound javascript?

**Comment by njannink** [comment]
I don't really understand your question, but when you don't assign a command the behavior stays exactly the same as it is now. When you assign a command you will get the expected MVVM behavior as is with Wpf and frameworks like ReactiveUI

**Comment by David-Moreira** [comment]
Well thanks for the explanation. 
It's just me not knowing this feature.

**Comment by njannink** [comment]
https://www.reactiveui.net/blog/2020/07/article-blazor-compelling-example
