### ISSUE TITLE
Validation component @bind-Status

### ISSUE THREAD

**Issue by Jimmys20** [stsrki/Blazorise#2073]
Hello, I would like to be able to update the Status of the Validation component manually, using the Status parameter, e.g.

```
<Validation @bind-Status="validationStatus">
    ...
    ...
</Validation>

@code {
    private ValidationStatus validationStatus = ValidationStatus.None;

    private void LoadData()
    {
        ...
        // http request return validation error
        validationStatus = ValidationStatus.Error;
    }
}
```

But if I use Validation component without specifying a Validator or a HandlerType I get the following exception

![Capture123](https://user-images.githubusercontent.com/34100964/111878126-6e6f4480-89af-11eb-8e3c-6a1b8f1c6fe5.PNG)

**Comment by stsrki** [comment]
That should work. What version do you use?

**Comment by Jimmys20** [comment]
I'm using version 0.9.3.1. The following method throws when you don't set the HandlerType or Validator parameter.

```
protected virtual Type DetermineHandlerType()
        {
            if ( HandlerType == null )
            {
                if ( Validator != null )
                {
                    return typeof( ValidatorValidationHandler );
                }
                else if ( UsePattern && hasPattern )
                {
                    return typeof( PatternValidationHandler );
                }
                else if ( EditContext != null && hasFieldIdentifier )
                {
                    return typeof( DataAnnotationValidationHandler );
                }
                else
                    throw new ArgumentNullException();
            }

            return HandlerType;
        }
```

**Comment by stsrki** [comment]
Yes, the validator is needed or otherwise, input components would not be validated. You could create a dummy validator by inheriting from `IValidationHandler` and then assign it to `HandlerType`, eg. `HandlerType="typeof(DummyValidationHandler)"`.

But even then I'm not sure if it's going to work. Manually changing validation Status was never my plan. Why do you want to do it that way?

**Comment by Jimmys20** [comment]
I want to implement server-side validation similar to this https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#server-validation

**Comment by stsrki** [comment]
Ah, so you need to set validation based on the result from the server. Well, even in that case you still need to have client-side validators defined.

**Comment by stsrki** [comment]
This works for me:

```
<Validation Validator="@ValidationRule.IsNotEmpty" @bind-Status="@status">
    <Field Horizontal="true">
        <FieldLabel ColumnSize="ColumnSize.IsFull.OnTablet.Is2.OnDesktop">Full Name</FieldLabel>
        <FieldBody ColumnSize="ColumnSize.IsFull.OnTablet.Is10.OnDesktop">
            <TextEdit Autofocus="true" Placeholder="First and last name">
                <Feedback>
                    <ValidationError>Enter full name!</ValidationError>
                </Feedback>
            </TextEdit>
        </FieldBody>
    </Field>
    @code{
        ValidationStatus status = ValidationStatus.None;

        protected override void OnInitialized()
        {
            status = ValidationStatus.Error;

            base.OnInitialized();
        }
    }
</Validation>
```

**Comment by Jimmys20** [comment]
I think your example works because of the IsNotEmpty ValidationRule and not because you set the status inside OnInitialized().

```
<Validation @ref="validationRef" Validator="ValidationRule.IsNotEmpty">
  <TextEdit @bind-Text="text">
    <Feedback>
      <ValidationError>Error Message</ValidationError>
    </Feedback>
  </TextEdit>
</Validation>

<Button Color="Color.Primary" Clicked="Fetch">Fetch</Button>

@code {
  private Validation validationRef;
  private string text;

  private async Task Fetch()
  {
    await Task.CompletedTask;

    validationRef.NotifyValidationStatusChanged(ValidationStatus.Error);
  }
}
```

**Comment by stsrki** [comment]
Yes, that was what I was mentioning before. You still need to have some validator defined.

**Comment by Jimmys20** [comment]
Yeah, and `ValidationRule.None` is probably the best fit for that. The question is, which is the correct way to change the Status of the Validation component manually. Binding with the Status parameter doesn't seem to work. Calling NotifyValidationStatusChanged on the Validation reference a correct approach?

**Comment by stsrki** [comment]
I would say NotifyValidationStatusChanged is the better option. Internally it is using the same approach.

**Comment by Jimmys20** [comment]
Cool, and I can also set the error message based on the server response.
`validationRef.NotifyValidationStatusChanged(ValidationStatus.Error, new string[] { "{error message from server}" })`
This solves my problem so I'm closing the issue. Thanks for your help!
