### ISSUE TITLE
Snackbar color 

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#2076]
Something strange happens to me, the color does not correspond to the sample css:

https://bootstrapdemo.blazorise.com/tests/elements
![Captura](https://user-images.githubusercontent.com/11645585/111994512-24ee3900-8b18-11eb-8f17-f980714f850f.PNG)

My page:
![Captura1](https://user-images.githubusercontent.com/11645585/111994570-333c5500-8b18-11eb-99c8-e8ceaf568bfb.PNG)

**Comment by stsrki** [comment]
Do you have Theme BackgroundOptions defined maybe?

**Comment by angelru** [comment]
thanks!
