### ISSUE TITLE
Problem creating stacked bar chart .NET5

### ISSUE THREAD

**Issue by Fridakornsater** [stsrki/Blazorise#2077]
I am trying to create a stacked bar chart using _BarChartOptions_ from the Blazorise Chart extension using .NET5. I have created a .razor file, where I add the below code in my @code {}. However, I cannot get the stacked property to work. My code looks like the following:

```cs
public BarChartOptions barchartOptions = new BarChartOptions { 
        Scales = new Scales
        {
            XAxes = new List<Axis> {
                new Axis
                {
                    Stacked = true
                }
            },
            YAxes = new List<Axis> {
                new Axis
                {
                    Stacked = true
                }
            },
        },
        Legend = new Legend
        {
            Display = false
        }
    };

```
The Legend is hidden successfully, so my feeling is that the stacked property should work. I refer to my html as follows:

<BarChart @ref="barChart" TItem="int" Options="barchartOptions" />

Thank you in advance!

**Comment by stsrki** [comment]
Your code seems to work

![image](https://user-images.githubusercontent.com/900302/112002899-aa75e700-8b20-11eb-96c0-c292ec2082ef.png)

I have just slightly modified the demo source at https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/ChartsPage.razor to add additional dataset

```diff
async Task HandleRedraw<TDataSet, TItem, TOptions, TModel>( Blazorise.Charts.BaseChart<TDataSet, TItem, TOptions, TModel> chart, Func<TDataSet> getDataSet )
    where TDataSet : ChartDataset<TItem>
    where TOptions : ChartOptions
    where TModel : ChartModel
{
    await chart.Clear();

    await chart.AddLabelsDatasetsAndUpdate( Labels,             
        getDataSet(), 
+        getDataSet() );
}
```

and

```
List<double> RandomizeData()
{
    return new List<double> {
        random.Next( -100,100 ) * random.NextDouble(),
        random.Next( -100,100 ) * random.NextDouble(),
        random.Next(  -100,100 ) * random.NextDouble(),
        random.Next(  -100,100) * random.NextDouble(),
        random.Next(  -100,100 ) * random.NextDouble(),
        random.Next(  -100,100) * random.NextDouble() };
}
```

**Comment by stsrki** [comment]
PS. you can also look at the page source for reference at https://www.chartjs.org/samples/latest/charts/bar/stacked-group.html
