### ISSUE TITLE
HorizontalBar Chart not showing any bars

### ISSUE THREAD

**Issue by seantrace** [stsrki/Blazorise#2084]
I have not been able to get the HorizontalBar chart to display any bars when using it in the same way as the Bar chart.

**To Reproduce**
In the ChartsPage.razor file of the Blazorise.Demo project change line 27 to use a ChartType.HorizontalBar

 ```
           <CardBody>
                <Chart @ref="barChart" Type="ChartType.HorizontalBar" TItem="double" />
            </CardBody>

```

**Expected behavior**

Should display a bar chart with bars in a horizontal orientation.

**Screenshots**
Before Change
![image](https://user-images.githubusercontent.com/7689011/112143051-43fbd200-8bcf-11eb-95a6-defb2596407d.png)

After Change
![2021-03-23 11_54_10-Bootstrap Demo](https://user-images.githubusercontent.com/7689011/112142729-de0f4a80-8bce-11eb-986f-265b8d38bdaa.png)

**Comment by stsrki** [comment]
Recently I have made charts data to automatically set Type based on the context. But the problem with horizontalBar is that it shares the same data as the regular bar. So once applied we would have a mismatch in the data configuration.

The solution is to also set the type in data explicitelly:

```diff
BarChartDataset<double> GetBarChartDataset()
{
    return new BarChartDataset<double>
    {
+        Type = "horizontalBar",
        Label = "# of randoms",
        Data = RandomizeData(),
        BackgroundColor = backgroundColors,
        BorderColor = borderColors,
        BorderWidth = 1
    };
}
```

![image](https://user-images.githubusercontent.com/900302/112153333-70b9e480-8be3-11eb-8052-aefa444b3036.png)

PS. it might be a good idea to mention this in the documentation.
