### ISSUE TITLE
BUG: Styling fails on Blazorise classes within a CarouselSlide

### ISSUE THREAD

**Issue by richbryant** [stsrki/Blazorise#2087]
**Describe the bug**

Classes are not applied to Blazorise elements within a CarouselSlide element

**To Reproduce**
Create a default Blazor project
Add Blazorise as per the Start instructions
Add a stylesheet file in Pages named `Index.razor.css`

Add to following code to Index.razor.css

```
.cssTest {
    color:blue;
}

.cssTest p {
    font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
```

Replace the code in `Index.razor` with the following code

```
@page "/"

<div class="container cssTest">
    <p>Welcome to your new app.</p>
</div>

<p>Carousel with div elements - works</p>
<Carousel @bind-SelectedSlide="@divSlide">
    <CarouselSlide Name="1">
        <div>
            <Paragraph>text 1</Paragraph>
        </div>
    </CarouselSlide>
    <CarouselSlide Name="2">
        <div class="container cssTest">
            <Paragraph>blue text</Paragraph>
        </div>
    </CarouselSlide>
    <CarouselSlide Name="3">
        <div>
            <Paragraph>text 3</Paragraph>
        </div>
    </CarouselSlide>
</Carousel>

<p>Now with Container elements</p>
<Carousel @bind-SelectedSlide="@containerSlide">
    <CarouselSlide Name="1">
        <Container>
            <Paragraph>text 1</Paragraph>
        </Container>
    </CarouselSlide>
    <CarouselSlide Name="2">
        <Container Class="cssTest">
            <Paragraph>blue text?</Paragraph>
        </Container>
    </CarouselSlide>
    <CarouselSlide Name="3">
        <Container>
            <Paragraph>text 3</Paragraph>
        </Container>
    </CarouselSlide>
</Carousel>

@code{
    private string divSlide = "2";
    private string containerSlide = "2";
}
```

**Expected behavior**
Both carousels text should turn blue and use SegoeUI font when on the second slide

**Actual Behaviour**

Only the the upper carousel applies the cssTest class.

**Comment by stsrki** [comment]
Ahh, you need to have CSS isolation. It is not supported quite yet. See #1599

I still need to figure how to enable it for Blazorise. Going on a list along with another ticket so it can be a new feature for 0.9.4 :)

**Comment by richbryant** [comment]
CSS Isolatiojn is only used to make the reproduction easier.  It does the same thing without.

**Comment by stsrki** [comment]
I have test it and it works on my side

![image](https://user-images.githubusercontent.com/900302/112290980-04e18580-8c90-11eb-8b4d-5717c8f4ef77.png)

**Comment by stsrki** [comment]
![image](https://user-images.githubusercontent.com/900302/112291059-13c83800-8c90-11eb-945c-1b8d1a275ac4.png)

**Comment by stsrki** [comment]
@richbryant Should I close it?

**Comment by richbryant** [comment]
give me today, I swear I'll find time to test it

**Comment by KroMignon** [comment]
@richbryant @stsrki 

Enabling CSS isolation for children component is easy, you have to add `::deep` to make the style 'visible'
and place the children component into a div, to enable ascendant relation chip.

cf. https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0

**Comment by stsrki** [comment]
@richbryant Any news?
