### ISSUE TITLE
Select component don't have select function

### ISSUE THREAD

**Issue by yorytang** [stsrki/Blazorise#2088]
Select component don't have select function

**Comment by stsrki** [comment]
It is for a reason. Blazor, like all other similar frameworks, provides us with a declarative syntax. And that means that components should receive their states through the parameters. eg `<Select SelectedValue="1" >`.

Adding a `.Select(1)` would lead us more into the imperative syntax and I don't want to go that way too much.

It's true there are some cases where imperative is used, like `modal.Show()` for example, but those cases are really rare.
