### ISSUE TITLE
Accordion header color and height change

### ISSUE THREAD

**Issue by sdditg** [stsrki/Blazorise#2089]
Hello everyone,

First of all, great components.

I need to mention that I'm not a frontend programmer, and all of my knowledge here in Blazor are assumptions based in WPF xaml logic :)

Question I have to ask is:
How I can change color of accordion component? I would like to change that color manually or theme based color?

Second question is how I can change Accordion header height? I tried to set child component's (button) margins to 0px and a few more options, but it wasn't successful. My best shoot was to to change button size, but it's not good enough, because I changed the font size too.

Thanks in advance!

**Comment by stsrki** [comment]
This is not possible without some simple CSS. If you used the example from the demo you can do it like this

```css
.accordion .card .card-header {
    height: 100px;
}
```
