### ISSUE TITLE
DataGrid only showing 5 Rows

### ISSUE THREAD

**Issue by ftrueck** [stsrki/Blazorise#2090]
I have a IEnumerable<CustomClass> with 16 entries but only 5 get rendered.

<img width="772" alt="Screenshot 2021-03-24 132024" src="https://user-images.githubusercontent.com/6458957/112309523-b9d16d80-8ca3-11eb-8871-dd1c7d48dbec.png">
<img width="671" alt="Screenshot 2021-03-24 131811" src="https://user-images.githubusercontent.com/6458957/112309309-7e36a380-8ca3-11eb-8e15-2b332581835c.png">
<img width="192" alt="Screenshot 2021-03-24 131744" src="https://user-images.githubusercontent.com/6458957/112309337-8393ee00-8ca3-11eb-8d00-36ba3a2f6e4d.png">

**Comment by stsrki** [comment]
You need to increase page size. eg `PageSize="100"`
