### ISSUE TITLE
In RTL mode, menu dropdown toggle icons are on the wrong side.

### ISSUE THREAD

**Issue by MarshMallowEgg** [stsrki/Blazorise#2093]
As you can see here, in RTL mode, the dropdown icon is overlapping the menu item:
![image](https://user-images.githubusercontent.com/20819930/112341882-6bae7100-8c87-11eb-9a7f-7290b44972ae.png)

It should look like this (screenshot in LTR mode):
![image](https://user-images.githubusercontent.com/20819930/112342168-9ef10000-8c87-11eb-95ef-1395003a321e.png)

I believe this can be fixed by setting "float: end" instead of "float: left" on 
.b-bar-vertical-popout:not([data-collapse]) .b-bar-dropdown .b-bar-dropdown-toggle:before

**Comment by stsrki** [comment]
We currently don't have support for RTL. It's planned but it's not going to be done any soon. So until we do a proper implementation, as a workaround it's best for you to override those classes through CSS.

**Comment by MarshMallowEgg** [comment]
I understand, thanks for your help.
