### ISSUE TITLE
Every chart shows up at Line Chart on latest package upgrade

### ISSUE THREAD

**Issue by katiep23** [stsrki/Blazorise#210]
Here's piece of my code:
```
<div class="mat-layout-grid">
    <div class="mat-layout-grid-inner">
        <div class="mat-layout-grid-cell"><div class="text-center font-weight-bold">Lead Time (Days)</div><BarChart @ref="leadTimeBarChart" @ref:suppressField TItem="double" /></div>
        <div class="mat-layout-grid-cell"><div class="text-center font-weight-bold">Number of Requests by Type</div><PieChart @ref="numRequestsPieChart" @ref:suppressField TItem="int"></PieChart></div>
        <div class="mat-layout-grid-cell"><div class="text-center font-weight-bold">Number of Requests by Month</div><LineChart @ref="numRequestsLineChart" @ref:suppressField TItem="int"></LineChart></div>
        
    </div>
</div>
```

And picture of output:
![image](https://user-images.githubusercontent.com/51712098/63220379-9b140800-c14b-11e9-8db3-0356d2516a1a.png)

Had all 3 charts working correctly in .NET preview 7.  Preview 8 completely broke the chart rendering but latest package upgrade at least got a bunch of line charts trying to render!

**Comment by stsrki** [comment]
There was in issue in preview 8 where I couldn't override `Type` property in the chart components so I removed it thinking it would work anyway. As it turns out it' not. Anyway until I fix it can you try setting the Type manually like:

```
<BarChart @ref="leadTimeBarChart" @ref:suppressField TItem="double" Type="ChartType.Bar" />
<PieChart @ref="numRequestsPieChart" @ref:suppressField TItem="int" Type="ChartType.Pie" />
```
