### ISSUE TITLE
Css-Cache for the ThemeGenerator

### ISSUE THREAD

**Issue by FStolte** [stsrki/Blazorise#2103]
We recently started using the Blazorise Theme in one of our projects to get our custom primary color into the Blazorise css (for the Stepper component). Now, we noticed a performance impact of using the Theme which slowed down initial site loading from about 600ms to 1.7s. This is on Server-side Blazor, btw.

Since likely most projects will only use a few different Themes, or even just one, I think it might be useful to implement a cache for the ThemeGenerator. If the same Theme is passed several times to the generator, it should not be necessary to generate the css again every time. If this performance impact is not just on our side, then a cache could bring a nice performance boost to the framework.

Of course this only really helps Server-side Blazor, since Blazor Webassembly would have to generate each Theme for each user once, anyway.

**Comment by stsrki** [comment]
It all depends on where the actual problem is. Does the generator takes too much time to build or does it takes slow to read HTML once the styles are loaded? I think I can easily cache the built styles. It's just a matter of few boolean flags. Hope it will help a little.

**Comment by stsrki** [comment]
@FStolte Are you sure we need caching? I'm testing to see how many times Blazor could re-render ThemeProvider and re-generate the theme and I found it only happens once on the app start. Later when I navigate to any page it still doesn't re-generate. Unless I specifically call `ThemeHasChanged()`.

**Comment by FStolte** [comment]
I think you might've misunderstood me. In a *single session*, the generation only happens once in the beginning as you say. But it happens once for *every* session, so for everyone accessing the page, the first load is delayed. I was talking about caching the css *across sessions* in a singleton service, so that it ideally only needs to happen once each time the app is deployed (for Server-side Blazor, of course).

**Comment by stsrki** [comment]
Ahhh that. Well, it is working as expected. Remember, even if you have 100 users, one of those users can still choose to have a different theme color. That is, if you have a way to choosing a theme in your app.

The only thing I can do is to maybe move a generator into a service class that can be injected through the DI. That way you could re-register it as singleton maybe.

**Comment by FStolte** [comment]
"even if you have 100 users, one of those users can still choose to have a different theme color"
That's why I was thinking of basically storing the css for every unique Theme if it was requested once, with an upper limit on how many Themes are cached totally. If the same Theme is requested twice, we don't need to re-generate it as long as it is still in the cache. So if 98 of those 100 users have the default theme and 2 picked custom ones, 97 users could still benefit from having the default theme cached.

I understand that this might not be a priority for you, but would you be open to a PR from me about this topic?

**Comment by stsrki** [comment]
Let the code speaks for itself :) Yes, if possible open a new PR and we'll see how it goes.

Don't forget to read our CONTRIBUTING https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md#branch-organization guidelines.
