### ISSUE TITLE
SelectedText on Autocomplete not showing for previously selected item

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#2108]
I have an autocomplete (within a modal) as follows:

```cshtml
<Autocomplete @ref="studyControl" TItem="Study" 
TValue="object" 
Data="@studiesList" 
TextField="@(item=>item?.StudyName)" 
ValueField="@(item=>item.StudyId)" 
SearchChanged="@StudyAutoCompleteChanged" 
SelectedValue="@allocation.StudyId" 
SelectedValueChanged="@(e => { allocation.StudyId = Convert.ToInt32(e); } )" MinLength="@minStudySearchLength" ChangeTextOnKeyPress="true" 
DelayTextOnKeyPressInterval="500" />
```

The autocomplete works fine the first time an item is selected, the selected value/text is shown and the StudyId is correctly set.

However, when I reopen a previously selected study Modal, and load in the Data as follows (in the Show method)  :

`   studiesList = await cairsRepository.GetStudiesListForAutoComplete(allocation.Study.StudyName, allocation.StudyId);`

which will (in this case) only have one item in the studiesList (the previously selected study), the SelectedValue and SelectedText of the autocomplete is blank:

![image](https://user-images.githubusercontent.com/6608640/112529468-35631580-8d9d-11eb-93ff-23d24af9fac9.png)

This situation does not occur for SelectList even though I am using the same pattern, e.g.:

```
  <SelectList TItem="Delivery" TValue="object" Data="@deliveriesList" TextField="@(item => item?.ShipmentNo)" ValueField="@(item => item?.DeliveryId)" SelectedValue="@animal.DeliveryId" SelectedValueChanged="@(e => { animal.DeliveryId = Convert.ToInt32(e); } )" Class="@DeliveriesListEnabledStatus">
                                </SelectList>
```

I can workaround/hack this so it works by manually setting the SelectedValue and SelectedText after loading the studiesList:

```
                    studiesList = await cairsRepository.GetStudiesListForAutoComplete2(allocation.Study.StudyName, allocation.StudyId);

                    studyControl.SelectedValue = allocation.Study.StudyId;

                    PropertyInfo studyControlSelectedTextProperty = studyControl.GetType().GetProperty("SelectedText", BindingFlags.NonPublic | BindingFlags.Instance);
                    studyControlSelectedTextProperty.SetValue(studyControl, allocation.Study.StudyName);
```

What is the correct way of getting the SelectedValue of an Autocomplete to bind correctly?

**Comment by stsrki** [comment]
Well you are using it right from what I can see. But I'm still not sure what is the problem from your description. Is it that the Autocomplete is not filled with items? Or selected value getter is not working?

**Comment by robalexclark** [comment]
The autocomplete SelectedValue is not set when the modal window is opened (the value is 0, rather than the Id of the Study (StudyId). Basically I have to manually set the SelectedValue of the autocomplete:

`studyControl.SelectedValue = allocation.Study.StudyId;`

and then set the SelectedText using reflection to ensure that the autocomplete visually shows the selected value correctly:

```
  PropertyInfo studyControlSelectedTextProperty = studyControl.GetType().GetProperty("SelectedText", BindingFlags.NonPublic | BindingFlags.Instance);
studyControlSelectedTextProperty.SetValue(studyControl, `allocation.Study.StudyName);
```

Im thinking that this could be due to the Autocomplete not knowing that it has to update its data bindings when the Modal is shown - is there anyway to manually ask the control to update its bindings?

**Comment by stsrki** [comment]
`InvokeAsync(StateHasChanged);` ussually helps. Other than that there is no way to make refresh outside of the component.

**Comment by robalexclark** [comment]
It didn't work, StateHasChanged didn't work either. 

I tried creating a demo project, copying in what I was doing and it worked fine. I have seen this sort of thing before and it usually comes down to some sort of async race condition or order of initialization. So for now I will use the reflection method to force the SelectedText correctly.

**Comment by stsrki** [comment]
In either case, it would be great if you could at some point create a code to reproduce it so I can fix it.
