### ISSUE TITLE
DataGrid Column Attributes

### ISSUE THREAD

**Issue by EnsignPayton** [stsrki/Blazorise#2111]
**Is your feature request related to a problem? Please describe.**

I'd like a way to access the `Attributes` of a `DataGridColumn` to attach additional metadata to each column.

**Describe the solution you'd like**

Adding a `CaptureUnmatchedValues` parameter to `BaseDataGridComponent` would allow me to access these values:

```cs
[Parameter( CaptureUnmatchedValues = true )]
public Dictionary<string, object> Attributes { get; set; }
```

### Additional context

I've implemented a user-editable column filter for the DataGrid, but we'd like some columns to always be shown. Rather than adding in logic to specify this based on `Field`, it would be nice to add an attribute in the Razor.

On the other hand, having an `Attributes` property that does not perform the same function as 0.8.7's attribute splatting ( #236 ) might introduce some unnecessary confusion into the API. Maybe they could be splatted onto the cells, so it performs the expected function while exposing the data I need to work with.

**Comment by stsrki** [comment]
There are few problems with this approach. First, DataGridComponent is used only for describing the behavior and visuals of the DataGrid. It is never rendered on its own. Second, DataGridComponent is responsible for cells, header cells, and group cells. To which of these should we apply unmatched attributes? All of them or just the body cells?

**Comment by EnsignPayton** [comment]
A user can already specify the display of body cells with `CellClass` or `DisplayTemplate`, and regardless an `Attributes` property on a component that doesn't render on its own is confusing. Agreed, the suggestion as-is has some problems.

I'll come up with a workaround. Thanks for the quick reply

**Comment by stsrki** [comment]
Yes, CellClass is used for body cells. There are also HeaderCellStyle, FilterCellStyle, and GroupCellStyle, each for their own part of the table. Similar is for templates.
