### ISSUE TITLE
Syntax highlighting not working when using <Select> (in Rider)

### ISSUE THREAD

**Issue by naefp** [stsrki/Blazorise#2114]
**Describe the bug**
Syntax highlighting and code completions are not working no more, when a razor file contains an instance of Blazorise.Select component - at least in the JetBrains Rider IDE. The Code can be complied correctly and the application is working as expected.

**To Reproduce**
Not 100% sure if this is bug coming from Blazorise, .net or Rider. I'm experiencing this since the latest updates of .net v5.0.4 and Blazorise v0.9.3.x. (I did not test it with VS yet)

**Screenshots**
![image](https://user-images.githubusercontent.com/42241289/112705874-f8804700-8ea0-11eb-8724-a0822bef02cc.png)
![image](https://user-images.githubusercontent.com/42241289/112705899-12ba2500-8ea1-11eb-8ee4-20cad0f604b1.png)

Did anyone else see this behavior as well?

**Comment by stsrki** [comment]
I would say it is a bug in Rider IntelliSense.  The same thing can sometimes happen with Visual Studio. A restart usually helps.

**Comment by naefp** [comment]
Thanks for the answer. I agree that most probably this is a Rider bug, but I was wondering why it only appears when a Blazorise.Select component is used.

**Comment by Jossec101** [comment]
I can confirm that this also happens in Visual Studio 2019 (Windows) 16.9.2, 

When I comment the Select component, I get intellisense back to work.

**Comment by naefp** [comment]
I can only imagine that there is a naming conflict with the Select component

**Comment by stsrki** [comment]
Might be a naming conflict. What other packages are you using? If any.

**Comment by stsrki** [comment]
Guys and news with this? Is it a naming conflict issue? Did you tried with `Blazorise.Select`?

**Comment by Jossec101** [comment]
> Guys and news with this? Is it a naming conflict issue? Did you tried with `Blazorise.Select`?

I confirm that this works, on VS with Jetbrains Resharper

**Comment by naefp** [comment]
`Blazorise.Select` seems not to help in JetBrains Rider.

I did not investigate further, but there is no other package with a Select component. If this is a naming conflict issue, it can only be caused by a conflict with the HTML <select> Tag.

Anyway, I agree that this should be fixed by JetBrains. We will renew our JetBrains licenses soon, and then we will open a ticket there.

Regardless of that, I would prefer more explicit or more unique names for components like Select, Label or Text.

**Comment by naefp** [comment]
To use `Blazorise.Select` seems not to help in JetBrains Rider.

I did not investigate further, but there is no other package with a Select component. If this is a naming conflict issue, it can only be caused by a conflict with the HTML <select> Tag.

Anyway, I agree that this should be fixed by JetBrains. We will renew our JetBrains licenses soon, and then we will open a ticket there.

Regardless of that, I would prefer more explicit or more unique names for components like Select, Label or Text.

**Comment by stsrki** [comment]
I would like to keep naming as simple as I can, so I have no plans for renaming them to something else at this point.

Please keep me posted once you report the issue on JetBrains.

**Comment by Sephiroth018** [comment]
Hi, I had the same issue in VS with Resharper and was able to narrow it down just a bit. As soon as I removed the TValue attribute, IntelliSense worked again. Maybe that helps.

**Comment by naefp** [comment]
it seems to be fixed in Rider 2021.1.2

**Comment by Sephiroth018** [comment]
Can confirm it being fixed for Resharper 2021.1.2.

**Comment by stsrki** [comment]
I'm happy to see the error was on the Rider side :)

Closing the ticket now!
