### ISSUE TITLE
RTE: don't force users to use external source files

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#2115]
https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.RichTextEdit/RichTextEditJsInterop.cs#L175

Some users are not able to use CDN or any external source to download JS or CSS files. We should find a way to customize these or include them as static content files in the project.

@njannink

**Comment by njannink** [comment]
The `RichTextEditOptions.DynamicLoadReferences` you can put that one to false and then use your own way to load the references, eg static content or a different CDN

**Comment by njannink** [comment]
Possibly we should open up the `RichTextEditJsInterop.LoadElementAsync` for users to be able to load there own references asynchronous. Like what is happening with the current implementation

**Comment by stsrki** [comment]
We can rename `DynamicLoadReferences` to `DynamicallyLoadReferences`. It gives more context to what it is used for. Also, we can add an array to the options, something like `DynamicReferences`. And then load those instead of the ones that are hard coded.

**Comment by njannink** [comment]
Seems fine to me.
