### ISSUE TITLE
Switch "circle" sits on the bottom. Feature or a bug?

### ISSUE THREAD

**Issue by sturlath** [stsrki/Blazorise#2117]
Just wondering if this should look like this because the [switches on the demo ](https://bootstrapdemo.blazorise.com/tests/carousel) page doesn't seem to behave like this...

![image](https://user-images.githubusercontent.com/2386572/112761755-540b1b80-8fec-11eb-8b8e-fd67b311e598.png)

The code (lots of nested stuff
```xml  
<Row>
    <Column ColumnSize="ColumnSize.Is3">
        <Switch TValue="bool" Size="Size.Medium">Active</Switch>
    </Column>
    <Column ColumnSize="ColumnSize.Is3">
        <Switch TValue="bool" Size="Size.Large">Allow subscription</Switch>
    </Column>
</Row>
````

I'm using version 0.9.3-preview6 with WASM within apb.io

**Comment by stsrki** [comment]
I would guess something is messing with the Blazorise styles for the Switch component. Can you inspect in dev tools?

**Comment by sturlath** [comment]
Am using the abp.io framework (Lepton theme) and it doesn't seem to matter where I add the switch, it's always on the bottom.

I'm as far from CSS literate as you can get so screenshots are all I can offer :-) Hope they can help...

![image](https://user-images.githubusercontent.com/2386572/112886739-d74a7100-90c1-11eb-9db7-5a5eccc9d7ec.png)

And closer 
![image](https://user-images.githubusercontent.com/2386572/112886798-eaf5d780-90c1-11eb-8a5d-4c4f5a09d632.png)

**Comment by stsrki** [comment]
You should definitely report it on the ABP repository. Seems like something is messing on their side.
