### ISSUE TITLE
Unable to select items using Autocomplete extension

### ISSUE THREAD

**Issue by gkapelevich** [stsrki/Blazorise#2122]
User types a character into autocomplete component.  Matching items are displayed in a dropdown.  User clicks on one of the items and nothing happens: item is not selected.

It seems to work occasionally but fails most of the time.  Tested in Chrome and Edge.

You can see this in Blazorise demo under Autocomplete: https://bootstrapdemo.blazorise.com/tests/components

**Comment by stsrki** [comment]
I suspect it has something with a new `onblur` event introduced with the latest update. Going on the list. Thanks
