### ISSUE TITLE
Blazorise DataGrid Item Counter

### ISSUE THREAD

**Issue by InzeNL** [stsrki/Blazorise#2128]
I am trying to change the text of the item counter for the DataGrid extension (see example in screenshot)
Currently, the text seems to be dynamic according to system language. In my case, that's English, in my colleague's case, that's Dutch.
I would like to see a way to customise this part.

A possible way to handle this would be to have a method call set in the header (like with PageButtons). This could look something like this. This code would make the text something like "5 - 8 out of 10 items".
```razor
<DataGrid ItemCountTemplate="@ItemCount">
</DataGrid>
```
```csharp
void ItemCount(RenderTreeBuilder renderTreeBuilder, int start, int end, int total) {
    renderTreeBuilder.AddContent(0, $"{start} - {end} out of {total} items");
}
```

This would help with keeping my website in a consistent locale (not everything is translated by Blazorise), and it could also help with customisation. With this example, you could also make it "Showing person 5 to 8 out of 10 people total."

### Additional context
On my device:
![image](https://user-images.githubusercontent.com/2505862/112995683-c35b4980-916b-11eb-9f6c-c580b946dbd5.png)

On my colleague's device:
![image](https://user-images.githubusercontent.com/2505862/112995722-cb1aee00-916b-11eb-90fa-87e85d1dcaab.png)

**Comment by stsrki** [comment]
There are two ways to do it.

1. Use TotalItemsTemplate

```cshtml
<TotalItemsTemplate>
    <span>@($"{context.CurrentPage} page of {context.LastPage}")</span>
</TotalItemsTemplate>
```

2. Use localization to add custom Dutch source

https://blazorise.com/docs/helpers/localization/#custom-languages

**Comment by InzeNL** [comment]
With the first solution, I seem to get this error:

```
Unrecognized child content inside component 'DataGrid'. The component 'DataGrid' accepts child content through the following top-level items: 'PopupTit
leTemplate', 'EmptyTemplate', 'EmptyCellTemplate', 'LoadingTemplate', 'ButtonRowTemplate', 'FirstPageButtonTemplate', 'LastPageButtonTemplate', 'PreviousPageButtonTemplate', 'NextPageButtonTemplate', 'PageButtonTemplate', 'ItemsPerP
ageTemplate', 'TotalItemsShortTemplate', 'TotalItemsTemplate', 'DetailRowTemplate', 'DataGridColumns', 'DataGridAggregates', 'ChildContent'.
```

I got this error as well when I modified the buttons, but managed to resolve this with a callback in my code-behind.

Do I need to place the `TotalItemsTemplate` within another element? Right now I put it directly into the `DataGrid`

```razor
<DataGrid>
    <TotalItemsTemplate>
        <span>@($"{context.CurrentPage} page of {context.LastPage}")</span>
    </TotalItemsTemplate>
</DataGrid>
```

**Comment by stsrki** [comment]
It is because of Blazor limitation when using ChildContenet and templates at the same time. Just wrap columns around `<DataGridColumns>` tag.

**Comment by InzeNL** [comment]
Alright, that fixed it, thank you!
