### ISSUE TITLE
Checkbox binding doesn't work Indeterminate= true

### ISSUE THREAD

**Issue by mathi82** [stsrki/Blazorise#2137]
Check with Indeterminate="true" does not bind properly until the user manually clicks the checkbox. 

**Expected behavior**
In the image below, i expect Check 2 to be checked. The binding starts to work after i manually check the checkbox once. 

```
@page "/test"

<Check TValue="bool?" Checked="@Check1" CheckedChanged="@OnCheck1Changed" >Check 1</Check>
<Check TValue="bool?" Checked="Check2" Indeterminate="true">Check 2</Check>

@code {

    bool? Check1 { get; set; }
    bool? Check2 { get; set; }

    void OnCheck1Changed(bool? value)
    {
        Check1 = value;
        Check2 = Check1;
    }
}

```

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
![image](https://user-images.githubusercontent.com/68622190/113166183-85643100-9210-11eb-9ee2-ac4bc95bc46d.png)

**Comment by stsrki** [comment]
That is how Indeterminate work. Check this link https://css-tricks.com/indeterminate-checkboxes/. It says

> The **indeterminate** state is visual only. The checkbox is still either checked or unchecked as a state. That means the visual indeterminate state masks the real value of the checkbox, so that better make sense in your UI!

Try removing `Indeterminate` and you will see that with or without it `Checked` value is updated properly.

```cshtml
<Check TValue="bool?" Checked="@Check1" CheckedChanged="@OnCheck1Changed">Check 1</Check>
<Check TValue="bool?" @bind-Checked="@Check2">Check 2</Check>

@code {

    bool? Check1 { get; set; }
    bool? Check2 { get; set; }

    void OnCheck1Changed( bool? value )
    {
        Check1 = value;
        Check2 = Check1;
    }
}
<Text>@Check1</Text>
<Text>@Check2</Text>
```

**Comment by mathi82** [comment]
Now i understand how it works, so bool? is useless. 
i thought by providing a nullable type, I should be able to cycle between checked/unchecked/indeterminate.

**Comment by stsrki** [comment]
I wish also it was that simple. But this is the strange web world with all the edge cases and weird stuff... 🤦‍♂️
