### ISSUE TITLE
Problems starting up

### ISSUE THREAD

**Issue by jeromv** [stsrki/Blazorise#2141]
With the visual studio template 'Blazor server app' I have created the default sample app
after that installed the nugets

Install-Package Blazorise.Bootstrap
Install-Package Blazorise.Icons.FontAwesome

after that followed the steps in https://blazorise.com/docs/start/#2-source-files and changed the _Host.cshtml file as instructed

![image](https://user-images.githubusercontent.com/12947760/113308823-d5bdba80-9306-11eb-95ff-0e4fbc688cde.png)

after that I get an exception when I start the application

also, I am missing  _content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" in my solution. 
What am I doing wrong here?

**Comment by stsrki** [comment]
Did you also finish the other steps? 

- https://blazorise.com/docs/start/#3-usings
- https://blazorise.com/docs/start/#4b-blazor-server

Can you also confirm Blazorise nuget packages are installed correctly?

![image](https://user-images.githubusercontent.com/900302/113309453-7318ee80-9307-11eb-8a21-82d76b8aac30.png)

**Comment by jeromv** [comment]
Yes, I did that.

**Comment by jeromv** [comment]
Probably it is something in the _host.cshtml file that is wrong
It is not clear to me if need to add or replace certain items there

**Comment by jeromv** [comment]
![image](https://user-images.githubusercontent.com/12947760/113313090-37802380-930b-11eb-98b3-413d3573a283.png)

**Comment by stsrki** [comment]
You're missing 

`<script src="_framework/blazor.server.js"></script>`

at the end of `<body>` element.

**Comment by jeromv** [comment]
Thanks!

**Comment by jeromv** [comment]
Sorry, just added this, stil get the same exception. Is there a sample project with Blazorise that can be downloaded so I can see where I am going wrong?

**Comment by stsrki** [comment]
Look through the demo apps https://github.com/stsrki/Blazorise/tree/master/Demos

Blazorise.Demo.Bootstrap.RC is for Blazor Server side.

**Comment by jeromv** [comment]
Ok, will do, thanks again for your help
