### ISSUE TITLE
DataGrid accents

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#2146]
How can I show the accents in Spanish well? "Próximo" "Último"

![Captura](https://user-images.githubusercontent.com/11645585/113395699-89bc5580-939a-11eb-9d4f-f867ed01db71.PNG)

**Comment by stsrki** [comment]
Hmm, this was working just fine before. For some reason localizations, json files are again changed from UTF8 encoding to ANSI. Could Git/GitHub do this somehow?

I will fix it in the next milestone. In the meantime, you can override them NextPageButtonTemplate and LastPageButtonTemplate.
