### ISSUE TITLE
DataGrid DataGridCommandColumn new action

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#2157]
I want to add a new row detail "action", at the moment I don't want to use "master-detail" (client requirement), I think this is related to this:
https://github.com/stsrki/Blazorise/issues/853

I thought it would be nice to have several custom templates and add a new one: DetailCommandTemplate, this is based on edit mode. This is all because I want to add one called "Detail". I have multiple hidden fields in the datagrid, I would like to display a modal and / or form with read-only fields, in detail mode, would this be possible in the future or do it now, without having to create a manual modal with all the fields?

**Comment by stsrki** [comment]
Do you mean to have an action to trigger the visibility of detail row?

**Comment by angelru** [comment]
It would be another button like the edit button, but with the fields in readonly

**Comment by stsrki** [comment]
I think you can already do this. YOu can add a button into any current column by using the DisplayTemplate and also showing or hiding the detail row by controlling the DetailRowTrigger.

```cshtml
<DataGridColumn TItem="Employee" Field="@nameof( Employee.City )" Caption="City" Editable="true">
    <DisplayTemplate>
        <Button Color="Color.Info" Clicked="@SwitchDetailRow">Show/Hide</Button>
    </DisplayTemplate>
</DataGridColumn>
@code{
    bool detailtRowVisible;

    Task SwitchDetailRow()
    {
        detailtRowVisible = !detailtRowVisible;
        return Task.CompletedTask;
    }
}
```

`DetailRowTrigger="@((item)=>item.Salaries?.Count > 0 && item.Id == selectedEmployee?.Id && detailtRowVisible)"`
