### ISSUE TITLE
Visual Studio intellisense breaks when using a Select

### ISSUE THREAD

**Issue by jeromv** [stsrki/Blazorise#2158]
https://stackoverflow.com/questions/66933591/intellisense-does-not-recognize-partial-class 

I have narrowed this down to me using a select in my .razor class.
The code just works fine and there are of course no build errors . It is just that Visual Studio shows odd behaviour. When I leave the select out of the razor code, it does not show this behaviour anymore

![image](https://user-images.githubusercontent.com/12947760/113505285-13585880-953e-11eb-851b-71aa50ba053a.png)

**Comment by stsrki** [comment]
This is "normal" behavior for VS. It happens to me all the time in various different projects. I guess it is a _bug_ in `.razor` IntelliSense builder os something. Nothing to do with Blazorise.
