### ISSUE TITLE
affter update blazor to preview 8 Autocomplete does not work!

### ISSUE THREAD

**Issue by MarvynHarry** [stsrki/Blazorise#216]
![image](https://user-images.githubusercontent.com/44927942/63317307-b8320d80-c2e8-11e9-9d87-685dbe5d24df.png)
affter update blazor to preview 8 Autocomplete Dosent Work!  any suggestions to solve this problema ?  it would be helpful, thanks!

**Comment by stsrki** [comment]
It seems like you're using server-side Blazor and you're missing necessary java-script files. Can you look at this guide and see if it helps? https://github.com/stsrki/Blazorise#server-side

**Comment by MarvynHarry** [comment]
> Parece que usas servidor Blazor y te estás perdiendo archivos de java-script necesario. ¿Puedes mirar esta guía y ver si ayuda? https://github.com/stsrki/Blazorise#Server-Side
thanks, that solved the problem
