### ISSUE TITLE
DataGrid: Columns Dictionary accessible by C# code

### ISSUE THREAD

**Issue by ftrueck** [stsrki/Blazorise#2164]
**Is your feature request related to a problem? Please describe.**
I want to access the defined columns of the DataGrid so that I can read their Attributes which are configured in the markup. In my special case I need to access the column display format (e.g. DisplayFormat="{0:0.000}" )

**Describe the solution you'd like**
Change Columns Dictionary from protected to public

### Additional context
---

**Comment by stsrki** [comment]
The use of DataGridColumn should be one-way only. It is used just to tell the DataGrid how to build itself and to define the initial state. After that, it should not be used directly. So, I don't like to make it public.

That said, you can make a reference to the column to access its fields.

```
<DataGridColumn @ref="@column1" TItem="Employee" Field="@nameof( Employee.LastName )" />
@code{
    DataGridColumn<Employee> column1;
}
```

**Comment by ftrueck** [comment]
OK, that is a posibility. I understand that the Column List is fragile as the code uses them to build up.
The thing is: Many datagrids also allow to configure the columns via code which  enables features like dynamic configurable grids in intermediate frameworks, etc. This would make the DataGrid extension way more powerful. Maybe there is a better way to acheive this as well.

**Comment by ftrueck** [comment]
I solved it with the formats predefined as strings and assigning them to the columns. Anyways: It would be cool if the columns are configurable at runtime. It would be nice to make columns visible dynamically e.g.
