### ISSUE TITLE
Material SideBar Error After Install

### ISSUE THREAD

**Issue by joseazevedo** [stsrki/Blazorise#2179]
in Material, if i install the Sidebar from nuget i got runtime an error, even without using it: TypeLoadException: Method 'Buttons' in type 'Blazorise.Bootstrap.BootstrapClassProvider' from assembly 'Blazorise.Bootstrap, Version=0.9.3.3, Culture=neutral, PublicKeyToken=null' does not have an implementation. ...

**Comment by stsrki** [comment]
I have just answered it on Gitter :)

> Check that all Blazorise packages have the same version. I made some changes in the internal Buttons method in 0.9.3.4, so by the error, it seems like versions are not match

**Comment by joseazevedo** [comment]
Thanks. Was version problems indeed.
