### ISSUE TITLE
Datagrid: Row span

### ISSUE THREAD

**Issue by rohitshres** [stsrki/Blazorise#2188]
I was going through the documentation of DataGrid but I didn't find a way to implement row span.

**Comment by stsrki** [comment]
It is not possible. Each DataGridColumn gives information to the DataGrid on how to render itself. Other than that DataGridColumn is almost not used after that. I'm not even sure how would row-span work or behave if it would occupy the space of other column/cell in a row, even if it was possible. Do you have any use case why would you want it or have a proposal API?

**Comment by rohitshres** [comment]
I have been using datagrid on my project, where i have list of rows which shows pricing information n a column with buttons to manage

Now I want a single button for all of the rows to manage data where all the rows information is binded with single value 

So, i could not merger the rows of that particular column which should contain only single button.

**Comment by stsrki** [comment]
Can you make a visual example? Maybe a drawing or screenshot of a similar design?

**Comment by rohitshres** [comment]
![image](https://user-images.githubusercontent.com/26213220/114394558-0f21e000-9bbb-11eb-897c-6138e1d9d005.png)

I need this button to be merged in all the rows that are will be populated. Is there any other way to achieve this rather than row span?

**Comment by stsrki** [comment]
You might be able to do it with javascript http://help.dottoro.com/ljiivjwl.php

You can assign an ID to the table with the ElementId

![image](https://user-images.githubusercontent.com/900302/114396440-dfb0aa80-9b9d-11eb-8c5b-0e11af3e9e58.png)

![image](https://user-images.githubusercontent.com/900302/114396463-e7704f00-9b9d-11eb-822f-35fefbadfa1c.png)

With this ID, getting the element with javascript should not be a problem.

**Comment by rohitshres** [comment]
Thank you very much, it worked.
