### ISSUE TITLE
Question about Vertical Bar Animations

### ISSUE THREAD

**Issue by JasonTFifer** [stsrki/Blazorise#2190]
Is there a way to disable the animations on the vertical bar? I'm trying to get the vertical bar to be in it's final state, without the initial animation. I tried the following:

```
.b-bar-vertical-small * {
	animation: none !important;
}
```
This will stop the animation, but the icons are in their initial state. Can someone provide some guidance? Ideally, it would be nice if there were a Parameter on the Bar control to disable the animations if they're unwanted. Thank you!

**Comment by stsrki** [comment]
The first time someone requested no animation. It is usually the opposite :)

For now, you can only do it with some CSS. But I can try adding a rule to disable it.

**Comment by JasonTFifer** [comment]
I can tend to be the odd man out. If it would be easier to keep it how it is, maybe you could give me some pointers on how I could disable and get it to the final state using CSS. I'm more of a backend dev and a noob when it comes to more advanced CSS topics, which is how I ended up at Blazorise in the first place. You've done an excellent job with this project; it's been a lifesaver for me. Thank you!

**Comment by stsrki** [comment]
Try this

```css
.b-bar-vertical-inline[data-collapse=small]
{
  transition: none;
}

.b-bar-vertical-inline
{
  transition: none;
}
```

**Comment by JasonTFifer** [comment]
Unfortunately, it's not working. I may have something messed up. Thanks for the suggestion though.

**Comment by JasonTFifer** [comment]
I think I figured out a hack. If I do:

`.b-bar-item * {
	animation-delay: 0ms !important;
}`
I don't notice the animation any more. I'm assuming it's still happening, just with no delay, I don't see it and I think this will work. Thanks again for all your help.
