### ISSUE TITLE
DataGrid ReadData rendering

### ISSUE THREAD

**Issue by angelru** [stsrki/Blazorise#2199]
I have noticed that when using `ReadData `the components are rendered more than once, is it working correctly? For example: in a page where you have a `DataGrid `with `ReadData` (although the event does nothing) and in another part of the page (nothing to do with the `DataGrid`) you have a `foreach `with a list, put a breakpoint. If you delete `ReadData` just 1 time. It is working well?

**Comment by stsrki** [comment]
Yes, that is how Blazor works. Whenever you have an event with EventCallback it will trigger a re-render.

YOu can track this ticker to learn more https://github.com/dotnet/aspnetcore/issues/18919#issuecomment-819124874
