### ISSUE TITLE
Could not find 'blazorise' in 'window'

### ISSUE THREAD

**Issue by ajai1109** [stsrki/Blazorise#220]
TextEdit @bind-text not working the first time and getting "Microsoft.JSInterop.JSException: Could not find 'blazorise' in 'window'. Error: Could not find 'blazorise' in 'window'." error in internet explorer console.

**Comment by stsrki** [comment]
I guess you're using server-side Blazor. For SSB you must set the js files manually. See this guide https://github.com/stsrki/Blazorise#server-side

**Comment by ajai1109** [comment]
Thanks @stsrki! Now the particular component issue is resolved when I download the bundle.zip and added into _Host.cshtml. I wondered how it was working in other components without doing this.

**Comment by stsrki** [comment]
Most of other components are not using javascript. TextEdit, NumericEdit etc are using js because currently there is no api in Blazor that can work directly with DOM.

**Comment by ajai1109** [comment]
Thanks very much for the explanation

**Comment by niem94** [comment]
@stsrki I get this error on https after upgrading to botnet 3.1.1. It works as expected on http, which is super odd.

Any ideas?

<img width="661" alt="image" src="https://user-images.githubusercontent.com/26203420/72827850-d4f9b500-3c7b-11ea-80d3-c396229da343.png">

**Comment by stsrki** [comment]
@niem94 sometimes browser will cache old content files. Try ctrl+F5.

**Comment by niem94** [comment]
@strski It is not that. I've cleared caches multiple times. 
I tried going back to an older commit im sure worked with https, but using dotnet 3.1.1 gives the same error. I suspect it has something to do with blazorise and dotnet 3.1.1, but the error description is really not giving away much other than it seems it can't find the static files.

**Comment by stsrki** [comment]
It would be 404 if the files could not be found. In this case they're found but cannot be read. I guess it is something with 3.1.1

**Comment by niem94** [comment]
Okay, I will downgrade for now, and see if this is resolved in a later release :-) Thanks for the quick response.

**Comment by niem94** [comment]
Problem resolved: 
My issue was due to static files not being consumed by default when using other environments than development in with "dotnet run". The solution to that is to call UseStaticWebAssets in the Program.CreateHostBuilder like mentioned in the number 1 answer in this SO question:
https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments

**Comment by stsrki** [comment]
@niem94 Thank you for giving us the solution :)

**Comment by kimz-petsure** [comment]
I am still having the issue, I am using the Blazor Client one.

**Comment by stsrki** [comment]
@kimz-petsure That's strange. This usually happen if you didn't set js files or if browser is using old-cached files.

- Try pressing Ctrl+F5 to clear the browser cache
- See if @niem94 solution works for you

Also give us a version of Blazorise you're using and version of Visual Studio or .Net Core.

**Comment by kimz-petsure** [comment]
thx @stsrki 
I have solved the issue now, it was caused by browser cache, it is working fine now. Thx
