### ISSUE TITLE
Provide uncompiled source file for blazorize.animate.js

### ISSUE THREAD

**Issue by codethug** [stsrki/Blazorise#2207]
I'm trying to understand how animations in Blazorize work (or might work in the future), so I started digging around the source code.  It looks like the animations are done in [blazorize.animate.js](https://github.com/stsrki/Blazorise/blob/master/Source/Extensions/Blazorise.Animate/wwwroot/blazorise.animate.js).

Unfortunately, that file appears to contain minified javascript.  Where can we find the source for this minified javascript?  I'd like to see what's available so I can better understand animations.

I looked at the [similar file](https://github.com/mikoskinen/Blazor.Animate/blob/master/src/BlazorAnimate/wwwroot/blazorAnimateInterop.js) in the Blazor.Animate repository, but it had the same problem.

**Comment by stsrki** [comment]
The source is available in the original repo of the animation library: https://github.com/michalsnik/aos

**Comment by codethug** [comment]
Thanks!
