### ISSUE TITLE
Sorting (single mode) is not working

### ISSUE THREAD

**Issue by dilip1234567** [stsrki/Blazorise#2210]
**Describe the bug**
we just downloaded nuget latest package today, and started with a basic grid with one column and three records. 
1) First time when we click on the sort column the up arrow shows and the sorting records works. 
2) second time when i click on the same column to sort, the up arrow doesnot change to down arrow but the records are sorted.
3) finally when i again click on the same column i get error 'Cannot read property 'removeChild' of null'.

We followed per the documentation and still getting error. any recommendation?
```html
<html>
<head>
  <!-- inside of head section -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

  <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
  <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
</head>
<body>
  <div id="app"></div>

  <!-- inside of body section and after the div/app tag  -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <script src="_content/Blazorise/blazorise.js"></script>
  <script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
</body>
</html>
```
![Error](https://user-images.githubusercontent.com/32101423/114939366-5358ee80-9e0e-11eb-99e2-7ee28051e457.JPG)

**Comment by stsrki** [comment]
Did you copy the entire `index.html`? Seems like you're missing ` <script src="_framework/blazor.webassembly.js"></script>`

**Comment by stsrki** [comment]
@dilip1234567 Did you see my last message? Any status?

**Comment by stsrki** [comment]
Unable to replicate. Closing now.
