### ISSUE TITLE
Blazorise.Animate: Delay does nothing

### ISSUE THREAD

**Issue by PaulSinnema** [stsrki/Blazorise#2213]
**Describe the bug**
Tried to get this working with Delay but the animation start immediately. 

Tried it with DelayMs = "5000" with Delay=@TimeSpan.FromSeconds(5). Same issue.

Solved it like this but it's not nice:

```
<Animate Animation="Animations.FadeIn"
		 DurationMs="1000"
		 @ref=@UnAuthorizedAnimation
		 IsManual="true">
	<h3>UnAuthorizedDisplay</h3>
</Animate>
```
```
using BlazorAnimate;
using System.Threading.Tasks;

namespace Wur.GroupTool.Blazor.Shared
{
	public partial class UnAuthorizedDisplay
	{
		private Animate UnAuthorizedAnimation;

		protected override async void OnInitialized()
		{
			await Task.Delay(5000);

			UnAuthorizedAnimation.Run();

			base.OnInitialized();
		}
	}
}
```
**To Reproduce**
1. Install Blazorise.Animate
2. Add an Animate tag with attributes Animation="Animations.FadeIn" Delay=@TimeSpan.FromSeconds(10) Duration=@TimeSpan.FromSeconds(1) (see below)
3. Add some content to the Animate tag.
4. Run the application

**Expected behavior**
Delay should postpone the animation for the duration of the time specified. I.e. if I specify Delay=@TimeSpan.FromSeconds(10) I would expect the animation to kick in after 10 seconds.

```
<Animate Animation="Animations.FadeIn"
		 Duration=@TimeSpan.FromSeconds(1) 
                 Delay=@TimeSpan.FromSeconds(10) >
	<h3>Test</h3>
</Animate>

<Animate Animation="Animations.FadeIn"
		 DurationMs="1000"
                 DelayMs="10000" >
	<h3>Test</h3>
</Animate>
```

**Comment by stsrki** [comment]
This is the limitation in AOS library. Max Delay is set to 3000ms.

> Values from 0 to 3000, with step 50ms.

Look at this answer to increase the time: https://github.com/michalsnik/aos/issues/558
