### ISSUE TITLE
Modal is not centered when it is set to center

### ISSUE THREAD

**Issue by bestpika** [stsrki/Blazorise#2215]
**Describe the bug**

When "Centered='true'" is set, "padding-right" appears in the element when it is displayed, causing it to be incorrectly centered.
This problem also occurs in the example.
<https://bootstrapdemo.blazorise.com/tests/modals>

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5698157/115360819-9215ec80-a1f2-11eb-82c3-5a7a843f44cb.png)
![image](https://user-images.githubusercontent.com/5698157/115361493-37c95b80-a1f3-11eb-9dd1-7cd893ce47ac.png)

**Additional context**

**Comment by stsrki** [comment]
It is coming from Bootstrap. If you go to their page you will see the same thing

![image](https://user-images.githubusercontent.com/900302/115365344-95927f00-a1c4-11eb-80ea-0c4b54343e2c.png)

BTW. the parameter should be `Centered`, not `IsCentered`. I dropped `Is*` prefixes long time ago :)

**Comment by bestpika** [comment]
This parameter is not fixed in your example document.
<https://blazorise.com/docs/components/modal/>
And even if I use the correct parameter, I still have "padding-right" in the element, so it can't center.

**Comment by bestpika** [comment]
Oops I forgot to mention that this issue appeared on the Mobile page.

**Comment by stsrki** [comment]
It was a typo in documentation. I have fixed it now.

Regarding the `margin-right`, I could easily change it. But wouldn't that work differently than in Bootstrap's own example?

**Comment by stsrki** [comment]
> Oops I forgot to mention that this issue appeared on the Mobile page.

Ah, that makes sense. Must be something with scrollbars. They are not visible on mobile.

**Comment by stsrki** [comment]
As I suspected: https://stackoverflow.com/a/47924156/833106
