### ISSUE TITLE
NumericEdit set ShowSpinButtons option globally

### ISSUE THREAD

**Issue by Jimmys20** [stsrki/Blazorise#2230]
Hello, it would be nice if there was a way to globally disable the NumericEdit spin buttons or maybe if ShowSpinButtons parameter was set to false by default.

Personally, I use a different spin button style for my app
![Capture](https://user-images.githubusercontent.com/34100964/115776975-6b57e180-a3bd-11eb-808b-07db1c053b46.PNG)

**Comment by stsrki** [comment]
I would say you tried the preview :)

Yeah, I think it makes sense to disable it globally. Going on the list!
