### ISSUE TITLE
Modal Title HeadingSize

### ISSUE THREAD

**Issue by EnsignPayton** [stsrki/Blazorise#2232]
**Is your feature request related to a problem? Please describe.**

Minor one, but I'd like to specify the heading size for a `ModalTitle`. It's currently hard-coded to `h4`.

**Describe the solution you'd like**

I can easily replace my `ModalTitle` with a plain `Heading` and add the class myself, but it would be slightly more convenient to have a `Size` property exposed directly on the `ModalTitle` with it using `Heading` internally.

```razor
@* <ModalTitle>@Title</ModalTitle> *@
<Heading Size="HeadingSize.Is5" Class="modal-title">@Title</Heading>
```

**Comment by stsrki** [comment]
Makes sense. It is an easy fix.
