### ISSUE TITLE
Allow Data binding in DataGrid in Edit/insert mode

### ISSUE THREAD

**Issue by JaredMRomano** [stsrki/Blazorise#2237]
I am using 0.9.3.5 of DataGrid.

I was wondering if there a way, or if you could add a way, to use binding when editing/inserting using the datagrid?

I use INPC for pretty much everything so I don't really need, or understand the concept of setting only CellValues. CellValues pose a challenge because I need to be able to disable fields under certain conditions and I have not found a way of accessing other cells.

For example, say if I'm inserting a new row, I just want to be able to make a new instance of the item type, then two-way bind all the edit template logic to those values.  I have tried doing that using @bind-. For example:

```cshtml
<EditTemplate>
    <Select TValue="PromotionDiscountType"
            @bind-SelectedValue="DataContext.SelectedPromotionCode.PromotionDiscountType">
        <SelectItem TValue="PromotionDiscountType"
                    Value="PromotionDiscountType.Percent">Percent</SelectItem>
        <SelectItem TValue="PromotionDiscountType" Value="PromotionDiscountType.FixedDollarAmount">
            Fixed
            Amount
        </SelectItem>
        <SelectItem TValue="PromotionDiscountType" Value="PromotionDiscountType.BOGO">BOGO</SelectItem>
    </Select>
</EditTemplate>
```

But it seems then the cell values then overwritten at some point.  What is even more odd is it always seems to do it about part way through the RowInserting call back, which tells me it is happening async and the timing is a bit off.

**Comment by stsrki** [comment]
With `@bind-SelectedValue="DataContext.SelectedPromotionCode.PromotionDiscountType"` you're basically skipping the DataGrid internal object state. So when you click Save whatever you had will get overwritten by the DataGrid internals.

You can disable that behavior with `UseInternalEditing="false"`. In that case you should be in control over your data while still be able to use input fields.

**Comment by JaredMRomano** [comment]
Got it, that makes sense. Thanks!
