### ISSUE TITLE
Blazorise not working in internet explorer

### ISSUE THREAD

**Issue by ajai1109** [stsrki/Blazorise#224]
Without any issues I am able to run blazor app with blazorize component, but when I run the same with internet explorer getting following errors.
1. JavaScript critical error at line 6, column 42 in https://localhost:44311/blazorise.js\n\nSCRIPT1002: Syntax error
2. JavaScript critical error at line 2, column 87 in https://localhost:44311/blazorise.charts.js\n\nSCRIPT1002: Syntax error
Could you please guide me to run the same in internet explorer
![image](https://user-images.githubusercontent.com/32535598/63876002-43468e00-c9e2-11e9-87e5-d96960f44d84.png)

**Comment by stsrki** [comment]
Browser compatibility is entirely done by Blazor. I guess you're using client-side Blazor and that is not supported on Internet Explorer. See this link https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0

**Comment by ajai1109** [comment]
> Browser compatibility is entirely done by Blazor. I guess you're using client-side Blazor and that is not supported on Internet Explorer. See this link https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0

No, I am using server-side Blazor. Thanks for your reply.

**Comment by stsrki** [comment]
The only other solution I can think of is that you're missing JavaScript files. See this if it helps https://github.com/stsrki/Blazorise#server-side

**Comment by ajai1109** [comment]
I have used all the js file mentioned and event if I created a new server-side Blazor application with Blazorise (by following all the Blazorise steps) in ie 11 I am getting the error. But in google chrome, I am not getting any issues.

**Comment by stsrki** [comment]
I've tried to run server-side Demo application in IE11 and it's working while client-side is crashing as expected. I guess something must be messing on your side. Can you post content of your `_Host.cshtml` file?

**Comment by ajai1109** [comment]
@page "/"
@namespace BlazorApp8.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlazorApp8</title>
    <base href="~/" />
    @*<link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="blazorise.css" rel="stylesheet" />
    <link href="blazorise.bootstrap.css" rel="stylesheet" />
    <link href="blazorise.sidebar.css" rel="stylesheet" />
    <link href="blazorise.snackbar.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
</head>
<body>
    <app>
        @* Remove the following line of code to disable prerendering *@
        @(await Html.RenderStaticComponentAsync<App>())
    </app>

    <script type="text/javascript" src="blazor.polyfill.min.js"></script>
    <script src="~/blazorise.js"></script>
    <script src="~/blazorise.bootstrap.js"></script>
    <script src="~/blazorise.charts.js"></script>
    <script src="~/blazorise.sidebar.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="_framework/blazor.server.js"></script>
</body>
</html>

**Comment by stsrki** [comment]
Without full code sample I cannot do or see much. Please look at this example in the demo app https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo.Bootstrap.RC/Pages/_Host.cshtml. Maybe it can help you.

**Comment by ajai1109** [comment]
We are not going to check with our blazorise project with internet explorer so i am closing this issue.

**Comment by intiharj** [comment]
@stsrki, I am also seeing this problem posted by @ajai1109 in IE 11.1069.17134.0CO

I see the problem when I navigate to Counter.  Attached image shows the console errors.  Source code also attached.  This is not happening with recent versions of Chrome, Firefox and Edge.  Thank you.

![errors](https://user-images.githubusercontent.com/6271320/69059480-9fb6b980-09e3-11ea-9b75-a626139c8697.png)
[IEProblem.zip](https://github.com/stsrki/Blazorise/files/3858959/IEProblem.zip)

**Comment by stsrki** [comment]
Hi @intiharj 

Blazor generally doesn't support IE. Based on your errors I can assume you're using a server-side Blazor project. According to the [official documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.0) you need to include polyfills to make it work. I never tried so I really don't know if it's going to work.

**Comment by intiharj** [comment]
Ah, I see.  Thank you.  I can steer my users away from IE.  If I do get around to trying pollyfill, I'll write back here.
