### ISSUE TITLE
FileEdit filename text overflows the component

### ISSUE THREAD

**Issue by Sephiroth018** [stsrki/Blazorise#2240]
**Describe the bug**
When selecting many files via a FileEdit component, the text of the filenames overlaps everything below

**To Reproduce**
1. Have a FileEdit component and some others below, example:
```
            <Validations @ref="_fileImportValidationRef" Mode="ValidationMode.Manual" Model="@_fileImportModel" ValidateOnLoad="false">
                <ValidationSummary/>
                <Validation @ref="_fileImportUploadValidationRef" Validator="@ValidateFileImport">
                    <Field>
                        <FieldLabel>Screenshots (max 500KB per file, jpeg only)</FieldLabel>
                        <FileEdit Multiple="true" Filter="Image/jpeg" Changed="@InputFilesChanged" AutoReset="false"></FileEdit>
                    </Field>
                </Validation>
                <Field>
                    <Check TValue="bool" @bind-Checked="@_fileImportModel.OverwriteExistingCollection">Overwrite existing collection</Check>
                </Field>
                <Button Type="ButtonType.Submit" Color="Color.Primary" Clicked="@ImportFiles" Disabled="@_isImporting">Import</Button>
            </Validations>
```
2. Select a large number of files via the FileEdit
3. Text of the filenames now overlaps the checkbox and the button

**Expected behavior**
Overflowing text of FileEdit should either stop with "..." or FileEdit could just display "x files selected".

**Screenshots**
Initial:
![grafik](https://user-images.githubusercontent.com/7352086/115968500-87cc5900-a538-11eb-9748-66fd406418d7.png)
After selecting a large number of files:
![grafik](https://user-images.githubusercontent.com/7352086/115968565-d1b53f00-a538-11eb-85a4-8e0b6e221370.png)

**Comment by stsrki** [comment]
Thanks for reporting it. I will try to fix it soon.
