### ISSUE TITLE
Closing tag matches nothing error with Link component (Rider)

### ISSUE THREAD

**Issue by NoahLavelle** [stsrki/Blazorise#2241]
**Describe the bug**
Link component errors saying `Closing tag matches nothing` when using Rider

**To Reproduce**
1. Create a new project using Rider
2. Create a Link tag

**Screenshots**
![image](https://user-images.githubusercontent.com/39242025/115990476-5779ce80-a5bb-11eb-959e-13b1428b2e00.png)

**Comment by stsrki** [comment]
It is a known issue https://github.com/stsrki/Blazorise/issues/1353#issuecomment-702176924

Just write it as `<Blazorise.Link>`.
