### ISSUE TITLE
Add Condition to Display utility

### ISSUE THREAD

**Issue by damianog** [stsrki/Blazorise#2243]
I want to conditionally display a message by using the Text component to simplify the code and avoid a strange compile behavior 

![image](https://user-images.githubusercontent.com/2786682/116042063-48078d80-a66e-11eb-802b-d2c98a970e49.png)

By adding a Visible attribute on BaseTypography.cs and use a "display: none" style or implement a conditional render on each derived components.

**Comment by stsrki** [comment]
For this, you can use `Display` utility. It has much more feature than regular Visible flag.

```cshtml
<Text Display="Display.None"></Text>

// or

<Text Display="Display.Always"></Text>
```

**Comment by damianog** [comment]
OK 

(condition) ? Display.None : Display.Always

it is fine.

Could you consider to add some helpers to he fluent Display class?

Maybe Display.If(condition).None?

Thanks

**Comment by stsrki** [comment]
Sounds like y good idea. How it never occur to me?! 😅

Can't promise but I will do my best to add the feature. Thanks for the idea!

**Comment by damianog** [comment]
Hi @stsrki,

You solved the issue fasten than light! I think this solution will cover the 99,9% of the cases at least for me. More complex situations should be circumvented by a property or a function return.

I owe you another coffee  :wink:

Good job.
