### ISSUE TITLE
Link-Type Button cannot be Disabled

### ISSUE THREAD

**Issue by FStolte** [stsrki/Blazorise#2253]
When a button has the type link, it is implemented by an anchor tag. Anchor tags don't support the html-attribute "disabled", therefore they're still active with `Disabled="true"`. The anchor tag instead needs the bootstrap class "disabled" (https://getbootstrap.com/docs/4.4/components/buttons/#disabled-state)

```
<Button Type=ButtonType.Link Disabled="true" To="https://www.google.com">My Link-Button</Button>
```
results in
```
<a role="button" href="https://www.google.com" class="btn" disabled="">My Link-Button</a>
```
when it should result in
```
<a role="button" href="https://www.google.com" class="btn disabled" tabindex="-1" aria-disabled="true">My Link-Button</a>
```

**Comment by stsrki** [comment]
Makes sense. I will fix it with the next patch release.
