### ISSUE TITLE
Validations for MemoEdit

### ISSUE THREAD

**Issue by davidjhurtado** [stsrki/Blazorise#2258]
I need to validate an address field, and i choose to use a MemoEdit component but it doesn't support a Validation.

I thought this component inherit the same properties from TextEdit but looks like is a different component.

I need to validate this field  is not empty.

*Is possible to add this feature in the future?*

**Comment by stsrki** [comment]
It should work the same as TextEdit. Can you tell me what version you use? Also, can you share some code samples on how you use validation and memo?

**Comment by davidjhurtado** [comment]
I'm using Blazorise v. 0.9.3-preview6 on a solution with abp.io framework v 4.2.1
This is an example of code
`<DataGridColumn TItem="AddressDetailCreateDto" Field="@nameof(AddressDetailCreateDto.Address)" Caption="Address" Editable="true">`

> `   <EditTemplate>`

>> `           <Validation UsePattern="true">`

>>>`                           <MemoEdit Text="@((string)((CellEditContext)context).CellValue)" TextChanged="@(v=>((CellEditContext)context).CellValue=v)" MaxLength=" AddressDetailCreateDtoConsts.AddressMaxLength" Pattern="([A-Z,a-z,0-9]+)" >`

>>>>`                                     <Feedback>`

>>>>> `                                                   <ValidationNone>Enter an address.</ValidationNone>`

>>>>> `<ValidationError />`

>>> `</Feedback>`

>>>`</MemoEdit>`

>> `</Validation>`

 >`</EditTemplate>`

  `</DataGridColumn>`

I have another row for an email field and its run validation correctly

**Comment by stsrki** [comment]
The problem is MemoEdit does not have a Pattern parameter. Also, 0.9.3-preview6 is a little older and there were some major improvements in validation recently. If possible update your projects. New ABP was also released a couple of days ago.

**Comment by davidjhurtado** [comment]
Thanks for your help
We gonna update to probe.
I tried to probe making a manual validation like this
<Validation Validator="@ValidateAddress">
                                            <MemoEdit Text="@((string)((CellEditContext)context).CellValue)" TextChanged="@(v=>((CellEditContext)context).CellValue=v)" MaxLength=" AddressDetailCreateDtoConsts.AddressMaxLength" >

But it doesn't works

Anyway we gonna update, really thanks
