### ISSUE TITLE
Decimal and negative values in NumericEdit

### ISSUE THREAD

**Issue by TorbjornEliasson** [stsrki/Blazorise#2266]
I have tried to enter decimal values with "," as decimal separator (culture="sv"). This works if I set Culture to "sv" and DecimalSeparator to ",". But when entering av negative value the value is not binded, neither with @bind-Value or ValueChanged. Have I missed something here?

Example code with ValueChanged:
`<NumericEdit Value="@Value"
             ValueChanged="@OnValueChanged"
             TValue="double"
             Culture="sv"
             DecimalsSeparator=","
             />
`
Example code with @bind-Value:
`<NumericEdit @bind-Value="@Value"
             TValue="double"
             Culture="sv"
             DecimalsSeparator=","
             />
`

**Comment by stsrki** [comment]
Min and Max constraints were improved in 0.9.4-preview only. There were some refactorings and breaking changes so I could not bring them into the 0.9.3.x, unfortunately.

If you want to try the latest preview you can get it here: https://github.com/stsrki/Blazorise#try-preview

**Comment by TorbjornEliasson** [comment]
I see. Its really good that there is a solution on this issue on the way. Thanks for a great work!

Med vänlig hälsning
Torbjörn Eliasson
Mobil: 070-536 56 82
E-post: ***@***.******@***.***>
Ekelundsgatan 1, Box 2522
411 18 Göteborg
[http://corptrade.se/site/templates/images/logo-email.jpg]
Corptrade Exitstrategi Väst AB
www.corptrade.se<http://corptrade.se/>
https://corptrade.se/artiklar/varfor-corptrade/
Vi ber dig lägga märke till att detta e-postmeddelande kan innehålla konfidentiell information. Om du felaktigt blivit mottagare av detta meddelande ber vi dig informera avsändaren om felet genom att använda svara-funktionen. Vi ber dig också att radera e-postmeddelandet utan att skicka det vidare eller kopiera det.
Trots att vi intygar att e-postmeddelandet och eventuella bilagor inte innehåller virus och andra fel som kan påverka datorn eller IT-systemet där det mottages och läses, öppnas det på mottagarens eget ansvar. Vi tar inte på oss något ansvar för förlust eller skada, som har uppstått i samband med att e-postmeddelandet mottagits och använts.


Från: Mladen Macanović ***@***.***>
Skickat: den 28 april 2021 13:38
Till: stsrki/Blazorise ***@***.***>
Kopia: Torbjörn Eliasson ***@***.***>; Author ***@***.***>
Ämne: Re: [stsrki/Blazorise] Decimal and negative values in NumericEdit (#2266)


Min and Max constraints were improved in 0.9.4-preview only. There were some refactorings and breaking changes so I could not bring them into the 0.9.3.x, unfortunately.

If you want to try the latest preview you can get it here: https://github.com/stsrki/Blazorise#try-preview

**Comment by stsrki** [comment]
No problem :)

I will close the ticket now since it is(should be) fixed.
