### ISSUE TITLE
`SetDeltaAsync` API in Rich Text control does not work

### ISSUE THREAD

**Issue by Smurf-IV** [stsrki/Blazorise#2268]
**Describe the bug**
Calling `SetDeltaAsync` at **anytime** does not set the contents of the Editor control

**To Reproduce**
Modify the demo app `RichTextEditPage.razor`
Add the following (Or add it in button press etc.):
```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await richTextEditRef.SetDeltaAsync("{\"ops\":[{\"attributes\":{\"bold\":true},\"insert\":\"Not Hello \"},{\"attributes\":{\"italic\":true},\"insert\":\"world\"},{\"insert\":\"!\\n\\nbased on: \"},{\"attributes\":{\"link\":\"https://quilljs.com/\"},\"insert\":\"Quill\"},{\"insert\":\"\\n\"}]}");
        await base.OnAfterRenderAsync(firstRender);
    }
```
Remove the contents between the `<Editor>` labels of `richTextEditRef`

**Expected behavior**
For the **Not** word to be visible

**Actual behavior**
No text is displayed in the Editor on the screen.

- Edit
**More info**
- I'm running the latest code downloaded from GitHub (As of yesterday)
- Launched via the `Blazorise.Demo.Bootstrap` project with Visual Studio (Not IIS)

**Comment by stsrki** [comment]
@njannink Can you help with this?

**Comment by Smurf-IV** [comment]
**More info**
- Adding the following to the end of `OnContentChanged`
- `await richTextEditRef.SetDeltaAsync(contentAsDeltaJson);`
- just clears the editor region !

**Comment by njannink** [comment]
I will have a look.
