### ISSUE TITLE
Materials CSS checkbox with clickable outside

### ISSUE THREAD

**Issue by mathi82** [stsrki/Blazorise#2279]
Hi all, 

I have the following two issues with checkbox, hoping anyone can help. 
 
1. When using materials version of the CSS, the Checkbox clickable area is larger than the actual checkbox. I couldn't figure how to change the size (if it is even possible, doesn't look like it is controlled by CSS). You can see this on the demo site https://materialdemo.blazorise.com/tests/forms. 

![image](https://user-images.githubusercontent.com/68622190/116704373-4fde6f00-a999-11eb-9409-5ef68be7abbf.png)

The bootstrap version works fine.

2. I set the checkbox colour, which works fine as shown in the image below when the checkbox is checked. 

![image](https://user-images.githubusercontent.com/68622190/116704706-b6fc2380-a999-11eb-9f62-83068c8e1ad3.png)

When the checkbox is indeterminate, the default colour is being used. 
![image](https://user-images.githubusercontent.com/68622190/116704819-d4c98880-a999-11eb-8b39-4c93df27f165.png)

Thanks
Mathi

**Comment by stsrki** [comment]
It is controlled with this CSS

![image](https://user-images.githubusercontent.com/900302/116786803-fe210c00-aaa0-11eb-8df0-4ad72e240c14.png)

And I think it is the right behavior for the material checkbox.

Regarding the color for the indeterminate state, it is a bug and I will fix it.

**Comment by mathi82** [comment]
Yes, removing the height and width does remove the clickable area outside of the checkbox, but it also removes the click transition effect. 
The checkbox on angular materials web site https://material.angular.io/components/checkbox/overview, doesn't allow the checkbox to be checked by clicking outside of it.

**Comment by stsrki** [comment]
The one on https://material-ui.com/components/checkboxes/ allows to check it by clicking outside 😄

I tend to not change the behavior of CSS framework providers if I don't need to. The original Blazorise material was done with http://daemonite.github.io/material/docs/4.1/components/forms/#checkboxes-and-radios-1, and today it is done for its fork https://djibe.github.io/material/docs/4.6/components/forms/#checkboxes

They both allow for checked change outside of the check area.

**Comment by stsrki** [comment]
Closing since it is the "issue" is with material CSS.

**Comment by mathi82** [comment]
agreed.
