### ISSUE TITLE
Datagrid PageSize bugs

### ISSUE THREAD

**Issue by Wolfenry** [stsrki/Blazorise#2280]
A few things regarding Datagrid PageSize feature:

1- `PageSize` parameter won't work together with `ShowPageSizes="true"` or custom `PageSizes`, probably because they doesn't change `PageSize` original value.

2- Setting only `PageSizes` doesn't affect the page size on load, `PageSize` it's always 5.
  i.e: i have  `List<Int32> itemRange = new List<Int32>() { 15, 50, 100 };` and `PageSizes="itemRange"` but grid first load size value is always 5.
  This could be solved by setting `PageSize="15"`, my lowest default. But this disables the size function because of bug in point 1.

3- My `<ItemsPerPageTemplate>` isn't working, i have v0.9.3.5, in Spanish ver it says 'artículos por página', this is OK but i want to change it and the template doesn't work
(Only this template, all the other ones are fine).

![image](https://user-images.githubusercontent.com/33076177/116740081-e11a0980-a9ca-11eb-9354-2090f404e31c.png)
(number is kinda odd but i think its a problem of mine)

My code is ordered like:
```
  <DataGrid Params...>
      <DataGridColumns>
          ...
      </DataGridColumns>
      <ItemsPerPageTemplate>
          Registros por página.
      </ItemsPerPageTemplate>
  </DataGrid>
```

**Comment by Wolfenry** [comment]
I don't know where `<PageButtonTemplate/>` applies but it doesn't seem to work either

**Comment by stsrki** [comment]
This is working as expected. PageSizes is only meant to be used for giving hints to choose how many items each page can show. It is not meant to affect the PageSize parameter. For PageSize you need to adjust it yourself manually. I would advise on `@bind-PageSize="@yourVariable"` syntax.

The issue with templates will be fixed.
