### ISSUE TITLE
Data grid refresh button

### ISSUE THREAD

**Issue by StephenOTT** [stsrki/Blazorise#2288]
A refresh button as part of the command buttons.  Something to re-trigger readData on your current page.  Common use case is when there is no data and/or only 1 one page of data.  

If a timer is viable for recurring refresh that would be nice too. But not the most common use case.

**Comment by stsrki** [comment]
The refresh button can be easily added by the user and I don't see much reason to add it natively. You can see an example in the demo app.

https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor#L217
https://github.com/stsrki/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/DataGridPage.razor.cs#L202

Not to mention that DataGrid is already quite cluttered with commands so there is not much room to add a refresh button. And not everyone needs it. So I will close this one.

**Comment by StephenOTT** [comment]
Thanks for the examples!
