### ISSUE TITLE
Defining components with the same name as HTML tags

### ISSUE THREAD

**Issue by danroth27** [stsrki/Blazorise#229]
Hi @stsrki,

I was looking through the [Blazorise FAQ](https://blazorise.com/docs/faq/) and I saw this comment:  

"it’s not not possible to have components that have the same name as regular html tags(form, button, text)."

I just wanted to make sure you saw that in our more recent Blazor releases we've now made component resolution case sensitive and we assume tags that follow Pascal casing are intended to be components, so you can define a `Button` component, and still also have `<button>` HTML tags. Perhaps the FAQ could be updated?

Nice job on this component library!

**Comment by stsrki** [comment]
@danroth27 I have already mentioned that in the release notes for latest version https://blazorise.com/docs/release-notes/release083/

I forgot about the note in the FAQ, I will remove that part. Thanks for noting :)
