### ISSUE TITLE
NumericEdit Decimals Property Handling

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#230]
Hello

I'm working on a page with the `NumericEdit` component with `TValue = "decimal?"`, but the `Decimals` property doesn't work like I think it should: 

I'm working on an user-defined field system, so the user can set the scale property themselves:

```html
<NumericEdit TValue="@(decimal?)"
    @bind-Value="@(myModel.DefaultValue)"                                         
    Decimals="@(myModel.Scale)">
</NumericEdit>
```

1) `Decimals = "null"` (or not provided / default) - any decimal allowed. So "10", "-10", "10.0", "10.123123", "-10.123123", ".12323", etc is all allowed. I guess the regex mask something like this `^((-)*\d)*(.(\d)*)?$` - although should also be limited to the [`decimal` overall max in dotnet which I think is 28 digits](https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=netframework-4.8). Currently if not provided then defaults to 2.

2) `Decimals = "1"` to `Decimals = "28"` - Then masked according to your regex at [blazorise.js](https://github.com/stsrki/Blazorise/blob/a571f003545db24c0ce2ad640a4dd6a1abb46876/Tests/Blazorise.Demo.Bootstrap.RC/wwwroot/blazorise.js). This works ok.

3) `Decimals = "0"` then no decimal allowed. So basically becomes an int type, but datatype is decimal. You have regex `^(-)?(\d*)$` in blazorise.js is ok, but its not wrapped in the RegExp() function so it seems `this.regex = function ()` just returns a string if dec ===`false`/`undefined`? 

```js
return dec 
    ? new RegExp("^(-)?(((\\d+(" + sep + "\\d" + reg + ")?)|(" + sep + "\\d" + reg + ")))?$") 
    : /^(-)?(\d*)$/;
```

Note I know little about javascript and even less about regex, so in js/regex pseudocode maybe like this? 

```js
    switch(dec) {
        case null:
            //any decimal 0.1231231, 0, -123.123123
            return new RegExp("^((-)?\d)+(.(\d)*)?$");
            break;
        case 0:
            //no decimal 0, 10, -120123123
            return new RegExp("^(-)?(\d*)$");
            break;
        default:
            //current system
            return new RegExp("^(-)?(((\\d+(" + sep + "\\d" + reg + ")?)|(" + sep + "\\d" + reg + ")))?$");
    }


```

**Comment by stsrki** [comment]
So basically you're saying we need to have rules for decimals.

- When it's null then allow any number, be it negative or positive with any number of decimals(max 28).
- When 0 then allow only integers
- Anything else do it as it is now

I think the first rule can actually be modified for the third. When null then set it to max decimals, in this case 28. So that leave us with only the 0 decimals rule that need to be special.

**Comment by brettwinters** [comment]
yeah, you're right about (1) and (3). So actually just the default changes from 2 -> 28 (The reason I separated is because I thought you were masking (like 4 -> #,##0.0000), but after testing I see you're not)

for issue (2) : currently if set `Decimals="0"` it allows up to two decimals to be input

I guess `float' and 'double' should work the same way. 

If `TValue = "int?"` then decimals default to "0"? if this is set to any other value then its ignored?

**Comment by stsrki** [comment]
I think the problem is actually in JavaScript and it's behavior when checking for valid values.

`this.decimals = decimals || 2;` will check for `null`, `undefined`, `NaN`, `0`, `empty string` and `false`. So that's why it walls back to 2 decimals when you send it 0.

**Comment by brettwinters** [comment]
yeah could be. You were too courageous doing `decimals || 2` haha The problem with js is that its too unpredictable...
