### ISSUE TITLE
FileEdit label text change

### ISSUE THREAD

**Issue by dkezri** [stsrki/Blazorise#2304]
Hi
I have to change the label text in FileEdit , is there a way to do that without using javascript calls?

**Comment by stsrki** [comment]
Currently, it is possible only with javascript. Although I think you might have to do it every time the `Changed` is raised.

I think it is best if I add a new parameter to change it. It will be ready for 0.9.4.

**Comment by dkezri** [comment]
i tried javascript to change the attribute "data-browse" of the label, but it didnt work?

**Comment by stsrki** [comment]
Somehow I misunderstood your question. It is actually possible to change the label/button text and is fairly easy to do. eg

`<FileEdit BrowseButtonLocalizer="@((name, args) => "Your text")" />`

**Comment by dkezri** [comment]
Thanks @stsrki ,  it worked fine.
