### ISSUE TITLE
BarBrand visual defects. Do I have to use CSS?

### ISSUE THREAD

**Issue by nightroman** [stsrki/Blazorise#2307]
# BarBrand visual defects. Do I have to use CSS?

[Brand.MyApp.zip](https://github.com/stsrki/Blazorise/files/6437312/Brand.MyApp.zip)

Please find attached the minimal Blazor + Blazorise app with `LayoutSider` and
`LayoutHeader`, both using `BarBrand`.

Here is what I get in Chrome:

![image](https://user-images.githubusercontent.com/927533/117357916-6f9bf880-aead-11eb-9eca-1587512a55fc.png)

**(1)** Minor but unpleasant issue: header bar height does not match the brand area
height in sider. Maybe it's just my opinion but it would be aesthetically
better if they match.

**(2)** Bigger issue: `BarBrand` `BarLink` text is not visible in the header bar.
It only appears only on mouse hovering:

![image](https://user-images.githubusercontent.com/927533/117357998-85a9b900-aead-11eb-96b1-717f4f25446d.png)

Am I doing something wrong here? Or do I have to use some CSS in order to
deal with these issues? My understanding is Blazorise is all about staying away
from CSS (ideally, of course).

P.S. Blazorise 0.9.3.6

**Comment by stsrki** [comment]
Ideally, it would be best to stay away from CSS but it is perfectly fine to use CSS. With Blazorise you get the basic tools to layout the UI but in the real world, you can use any Bootstrap theme with any custom CSS. It would be impossible to cover it all without some CSS fixes.

Also, for this case you can adjust horizontal bar height with theme setting, eg. (taken from the demo)

```cs
private Theme theme = new Theme
{
    BarOptions = new ThemeBarOptions
    {
        HorizontalHeight = "64px"
    },
}
```

**Comment by nightroman** [comment]
No problem, I understand. The problem is: how do I "fix" these issues? I am a noob in CSS (that's why Blazorise is cool) and do not really know what to do in this case.

NB I've added your suggested snippet but it is not enough. Should I do anything else in order to engage/apply it?

**Comment by stsrki** [comment]
You can try this CSS to fix brand color

```css
.navbar.bg-primary .navbar-brand .nav-item .nav-link {
    color: #FFFFFF;
}
```

**Comment by stsrki** [comment]
PS. I'm also coming from backend background and I'm far from CSS expert. But I just keep learning :)

**Comment by nightroman** [comment]
CSS worked like a charm, thank you. Still cannot make the right bar height...

Thank you for your great work and product!

**Comment by nightroman** [comment]
> Still cannot make the right bar height...

Got it, it should be in App.razor.
Solved, closing, thanks again!

**Comment by stsrki** [comment]
I sometimes forget not everyone is familiar with Blazorise.. Sorry about that 😅

**Comment by nightroman** [comment]
No problem, it was my fault after all, I should have transfer demo bits to my app more carefully.

On that note:
- Do you have plans to create a template for `dotnet new` with some minimal project with all but essentials and **free of silly mistakes** like mine?
- Perhaps it makes sense to mention in Getting Started that Blazorise theme is somewhat important and point to Demo App.razor.

**Comment by stsrki** [comment]
Yep, everything is planned. It's just the time that is the problematic

**Comment by nightroman** [comment]
>Yep, everything is planned. It's just the time that is the problematic

Good. Yes, I know exactly what you mean :)
