### ISSUE TITLE
App Unstyled

### ISSUE THREAD

**Issue by andrewwilkin** [stsrki/Blazorise#231]
Love the idea of this package, very well laid out so could not wait to use it.

So I have a Client Side Blazor App that have been working on using the latest version (preview 8) and also got cookie authentication.

Have followed the instructions laid out in the getting started section (apart from the final optional step as have nothing Razor in this project). When I start up the app the app is not styled in anyway, though can see in the sources that it has loaded all the CSS for bootstrap

Any ideas what I might have done wrong? Thanks in advance.

**Comment by stsrki** [comment]
If you have followed the instructions you should be able to see the styling. At least the default css that comes with the Blazor should work.

Look at this demo html, maybe you're missing something: https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo.Bootstrap/wwwroot/index.html

Also this: https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo.Bootstrap/Startup.cs

**Comment by andrewwilkin** [comment]
So I've created a brand new project and followed the steps, and gone through your demo repos to see if I've missed anything and for the life of me cannot see why it is not working.

Example
https://github.com/andrewwilkin/Blazorize

Master branch is following the steps in the startup. The WithSideBarAdded branch has the Sidebar nuget package added and can at least see a sidebar but then the main content is no longer visible.

**Comment by stsrki** [comment]
I'm outside now so I cannot test it. Remove last using from here
https://github.com/andrewwilkin/Blazorize/blob/master/Blazorize/Client/_Imports.razor
You only need Blazorise namespace.

**Comment by andrewwilkin** [comment]
Thanks tried that (checked into master) and made no difference. No rush, enjoy your Sunday :)

**Comment by stsrki** [comment]
OK, so I tried you app and I see why it doesn't work.

First you tried to copy layout from demo app but from the wrong place. The real demo app is actually **Blazorise.Demo** instead of **Blazorise.Demo.Bootstrap**. So you must copy css from here: https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/wwwroot/demo.css

After you're done with that, then we got a second problem. Except for the `Sidebar` component you didn't used any other Blazorise component. Here is the modified counter page in your test app just as an example.

```
@page "/counter"
<h1>Counter</h1>

<p>Current count: @currentCount</p>

<Button Color="Color.Primary" Clicked="IncrementCount">Click me</Button>

@code {
    int currentCount = 0;

    void IncrementCount()
    {
        currentCount++;
    }
}
```

Also here is the **_Imports.razor**

```
@using System.Net.Http
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.JSInterop
@using Blazorize.Client
@using Blazorize.Client.Shared
@using Blazorise;
@using Blazorise.Sidebar;
```

And don't forget to read the [documentation](https://blazorise.com/docs/).

**Comment by andrewwilkin** [comment]
Thanks for your time, can see some stuff working at least now 👍 
Will look to incorporate in my app and make switch to the Blazorise components. Really appreciate your nudge in the right direction.
