### ISSUE TITLE
[DataGrid] Allow insert or visibile but not edit

### ISSUE THREAD

**Issue by damianog** [stsrki/Blazorise#2312]
During insert mode I would like to allow insert a key field value, but in edit mode it should be readonly or visible.

Maybe the Editable="true" could be changed in "EditMode" and have a enum of values to allow a combination of edit, insert, display, readonly

I have also a situation where inserting a code field a description field should display.

**Comment by stsrki** [comment]
It seems like NewItemDefaultSetterPermalink will help you https://blazorise.com/docs/extensions/datagrid/#newitemdefaultsetter

**Comment by damianog** [comment]
I think it works only to fill default values.

Let me make a better example.

A table with 3 columns: code, description, quantity.

On insert I need to fill code, after code is typed description display a value (automatically filled by me) than I fill quantity value.

Somebody else when edit the row could only edit the quantity, but should still see code and description in popup mode to be sure that is setting the value to the right record.

Is should say that I am trying to create the table dynamically by reflection of the entity class.

**Comment by stsrki** [comment]
It should be possible with the Readonly parameter. eg 

`Editable="true" Readonly="true"`

But you will need to figure how to still enable editing when the item is created. Maybe use NewCommandTemplate or EditCommandTemplate?

**Comment by damianog** [comment]
So I could set Editable="true" by default and play around Readonly and check the state for Edit or Insert,

Which is the cleanest way to intercept the insert,edit,cancel,save commands without defining custom command templates? So a could set a variable to the proper value. Maybe this could be included in the source DataGrid.

**Comment by stsrki** [comment]
Well, the "cleanest" is using command templates. I don't see another way without changing the DataGrid API and that will take some time.

**Comment by damianog** [comment]
OK I close this issue and I will investigate for a DataGridCommand event.
Thanks!
