### ISSUE TITLE
Multi-select SelectedValues returns distinct values

### ISSUE THREAD

**Issue by Rubenisme** [stsrki/Blazorise#2324]
**Describe the bug**
The select component in multiple mode has a SelectedValues property, that's great but this returns distinct values (which probably gets used in that way 99% of the time).

**To Reproduce**
Have multi select with multiple same items. Select those items and the SelectedValues property is a single value.

**Expected behavior**
I would have expected the value there as many times as it is selected.

```
@code
{
    Select<string> multiSelect;

    void GetSelectedValues()
    {
        // when selecting all, they are distinct and 'John' does not appear 3 times
        var selected = multiSelect.SelectedValues;
    }
}

<Select @ref="multiSelect" TValue="string" Multiple="true" MaxVisibleItems="6">
    <SelectItem Value="@("Matthew")">Matthew</SelectItem>
    <SelectItem Value="@("Mark")">Mark</SelectItem>
    <SelectItem Value="@("Luke")">Luke</SelectItem>
    <SelectItem Value="@("John")">John</SelectItem>
    <SelectItem Value="@("John")">John</SelectItem>
    <SelectItem Value="@("John")">John</SelectItem>
</Select>

<Button Color="Color.Primary" Clicked="@GetSelectedValues">GetSelectedValues</Button>
```

All in all not a big deal for me now and thanks for the awesome project. Very much appreciated. If you want and this fix will be sped up much more then I can spend some time after next week and see if I can make a pull request.

**Comment by stsrki** [comment]
Hmm I don't think it is much of a problem but it should be an easy fix. No worries. I will fix it for next 0.9.3 patch :)
