### ISSUE TITLE
 The value of DataGrid aggregate column will not be automatically updated with filtering?

### ISSUE THREAD

**Issue by wartim** [stsrki/Blazorise#2345]
There are a total of 10 records in the "Data" data set of the DataGrid. When "Filterable" is set, the filter box is displayed. When the filter text is filled in, the filtering result of the DataGrid is 3 records, but the aggregate column (DataGridAggregateType.Count) is always displayed as "10" instead of being automatically corrected to "3". Whether it can be automatically recalculated, including other "Sum", etc.

**Comment by stsrki** [comment]
I was sure this was working but after I tested it, it seems it is not. Thanks for reporting it. I will do my best to fix it.
