### ISSUE TITLE
 Autocomplete and DropdownList can actually be merged

### ISSUE THREAD

**Issue by wartim** [stsrki/Blazorise#2349]
The problem with DropdownList is that you can only drop down selections, but you cannot directly enter text (and you can filter when you manually enter the option text).

Autocomplete can use MinLength="0" to simulate automatic drop-down, but it does not have a drop-down arrow pattern, so when one is selected, it must be cleared before it can be selected, and you cannot directly click the drop-down button to select another.

So it is recommended that it is perfect if there is such a control:
1 The default appearance and behavior are the same as DropdownList.
2 The main body is an embedded textfield (the same effect as Autocomplete), you can enter text and display the filtering results.
3 You can either manually enter text or click the drop-down list button to select.
4 If the manually entered content is not in the selectable list, it will be saved in the "Text" property, and "SelectedItem/SelectedValue" is NULL, otherwise Text=SelectedItem/SelectedValue=selected item.

**Comment by stsrki** [comment]
I'm not sure if it would be best to merge these two components. Autocomplete is quite complex now, and adding a new set of APIs to make it behave like a regular dropdown would be much harder than just using the DropdownList directly.

So while I appreciate it, it's best to leave them separate. Thanks.
