### ISSUE TITLE
DateEdit picker is not working for material provider

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#239]
DateTime picker automatically closes as soon as it's opened.

#238

**Comment by stsrki** [comment]
@ajai1109

I have tried date picker on the **daemonite** site and it seems the same problem is occurring. Can you confirm also?
http://daemonite.github.io/material/docs/4.1/material/pickers/#date-pickers

**Comment by ajai1109** [comment]
> @ajai1109
> 
> I have tried date picker on the **daemonite** site and it seems the same problem is occurring. Can you confirm also?
> http://daemonite.github.io/material/docs/4.1/material/pickers/#date-pickers

@stsrki  Yes I have tried date picket on the daemonite site and facing the same issue. Thanks!

**Comment by ajai1109** [comment]
> > @ajai1109
> > I have tried date picker on the **daemonite** site and it seems the same problem is occurring. Can you confirm also?
> > http://daemonite.github.io/material/docs/4.1/material/pickers/#date-pickers
> 
> @stsrki Yes I have tried date picker on the daemonite site and facing the same issue. Thanks!

@stsrki FYI but the same date picker is working on mobile

**Comment by stsrki** [comment]
Maybe they're using different event handler in their JavaScript.

**Comment by stsrki** [comment]
After investigation I thing something has changed in on of latest Chrome version on how it handles JavaScript. For Firefox and other browsers the picker works just fine.  So moving to backlog since I don't want to prolong release of 0.8.5 any more.
