### ISSUE TITLE
i cant  display the components

### ISSUE THREAD

**Issue by MarvynHarry** [stsrki/Blazorise#241]
with the update to preview 9 I can't see the components on the screen, it doesn't throw an error but it doesn't let me see them either.

I don't know if the new way in which the components are rendered affects, but therefore I use the static mode
![image](https://user-images.githubusercontent.com/44927942/64399150-cea4cc80-d03d-11e9-8752-a50bfa177bb9.png)

**Comment by ajai1109** [comment]
> date to preview 9 I can't see

Please add following line in program.cs -> CreateHostBuilder then you will get exact error.

webBuilder.UseSetting(WebHostDefaults.DetailedErrorsKey, "true");

You might get the following error.
Could not load type 'Microsoft.AspNetCore.Components.UIKeyboardEventArgs' from assembly 'Microsoft.AspNetCore.Components.Web, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by stsrki** [comment]
You're getting the error because Blazorise is still on p8. I'm finished with upgrade to p9, just need to write release notes and prepare the nuget packages. It will be published. today.

**Comment by ajai1109** [comment]
> se notes and prepare the nuget packages. It will be published. today.

Thank you very much @stsrki

**Comment by stsrki** [comment]
0.8.4 is published. See the [release notes](https://blazorise.com/docs/release-notes/release084/).

**Comment by MarvynHarry** [comment]
> You're getting the error because Blazorise is still on p8. I'm finished with upgrade to p9, just need to write release notes and prepare the nuget packages. It will be published. today.

Tank you @stsrki
