### ISSUE TITLE
Chart errors after updating topreview9 and v0.8.4

### ISSUE THREAD

**Issue by ToraSnow** [stsrki/Blazorise#245]
Getting this error after the update,

Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.Charts.JS.ToChartDataSet[T](ChartData`1 data)
   at Blazorise.Charts.JS.SetChartData[TItem,TOptions](IJSRuntime runtime, String id, ChartType type, ChartData`1 data, TOptions options, String dataJsonString, String optionsJsonString)
   at Blazorise.Charts.BaseChart`3.Update()
   at Blazorise.Charts.BaseChart`3.OnAfterRenderAsync(Boolean firstRender)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'BtAVL1pPT3PRYXp5JS8tO3fiDyGlWbDvQSSIi_2g74g'.

**Comment by stsrki** [comment]
I'm not familiar with this error. Can you provide me with more information? 

- Is this fresh project using Blazorise and you just upgraded it?
- Do you use client-side or server-side Blazor?
- If it's server-side, do you have all js files? [see this](https://github.com/stsrki/Blazorise#server-side)
- Do you use any provider(Bootstrap, Bulma, Material) or just Charts?

**Comment by ToraSnow** [comment]
This is a project I started under preview 8 that was working, with the update to preview9 and 0.8.4 I see this error after removing the @ref:suppressFields. It is a server side project, and I did update  to the v0.8.3 js files, I don't see any for the 0.8.4 from today. I use the material provider as well as charts.

**Comment by stsrki** [comment]
JavaScript files didn't change since 0.8.3 so they're not an issue if you already have them. It's strange that you see the error after you removed `@ref:suppressFields` because in the [Blazor release notes](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/) it's stated to remove it completely. So I guess it should be safe.

**Comment by ToraSnow** [comment]
So this looks like my fault, with the change to preview9 im having issues with parameters for components on a server side app.
