### ISSUE TITLE
launchSettings.json warning

### ISSUE THREAD

**Issue by PhilPJL** [stsrki/Blazorise#248]
If I add blazorise to a source controlled (Azure DevOps/TFS) project then I get a warning message:

![image](https://user-images.githubusercontent.com/271656/64494099-83c6c700-d280-11e9-8801-94869fe4e576.png)

I get the message if launchSettings.json is or isn't already added to source control.
I haven't seen this exact issue before, but there was a similar warning when adding Tewr's filer reader component https://github.com/Tewr/BlazorFileReader/issues/55 which is now fixed.

**Comment by stsrki** [comment]
U must say this is the first time I see this message. The only thing I can think of is to remove the `launchSettings.json` from NuGet package but I don't know if that will break something else. I will investigate this more and let you know.

**Comment by PhilPJL** [comment]
That will almost certainly fix the issue.  I think VS always has a launchSettings.json for any .NET core app  so there probably shouldn't be one in your NuGet package.

**Comment by stsrki** [comment]
Moving to current 0.8.5 milestone.

**Comment by stsrki** [comment]
I have published a preview version to the MyGet so please try it and let me know how it works for you,

The feed url is https://www.myget.org/feed/Packages/blazorise

**Comment by PhilPJL** [comment]
That looks good, no warning when adding the package or opening the solution.
