### ISSUE TITLE
ModalHeader Title attribute has been removed?

### ISSUE THREAD

**Issue by richbryant** [stsrki/Blazorise#25]
Currently this code throws errors - is it still valid?

`<ModalHeader Title="Some Text">
            <CloseButton Clicked="@ClickEvent" />
</ModalHeader>`

**Comment by stsrki** [comment]
I forgot to update the docs, sorry about that. You need to use `ModalTitle` component eg:

```
<ModalHeader>
  <ModalTitle>Employee edit</ModalTitle>
  <CloseButton Clicked="@HideModal" />
</ModalHeader>
```

**Comment by richbryant** [comment]
Cheers, it all works nicely again.
