### ISSUE TITLE
SelectEdit : Handling for No-Match

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#252]
Hi @stsrki 

Currently if the `SelectedValue` does not match any of the `SelectItem`s, the `SelectEdit` displays the first item. This is a problem since the displayed value does not match the actual value. 

This issue mostly occurs with initial values (null, empty, etc) when the model is initialised and nothing has yet been set yet, or due to a logic change previous set values are no longer in the list

Options : 

(1) Allow users to set `Visibility` on `SelectItem` so we can do this : 

```html
<SelectItem Value="default(int)" style="display:none;">None</SelectItem>
```
Then the initial value is initially set to this item, and displayed in the select as "None", but once the user selects away from this default `SelectItem` its no longer visible/selectable. Visibility was fixed here  ( #183 ) but not for  `SelectItem`

as a work-around, I'm doing this now, but using your `Class` since the `style` is not available for us (yet).

(2) Allow us to set the `title` attribute on the select (but this option is mostly used if none of the items match - not necessarily if it matches the default) say by a property on the "SelectEdit" which allows us to specify what to display if nothing is selected, like this:

```html
<SelectEdit NothingSelectedText="None" SelectedValue="0"
    <SelectItem Value="1">one</SelectItem>
    <SelectItem Value="2">two</SelectItem>
    <SelectItem Value="3">three</SelectItem>
</SelectEdit>
```
Then in this case the select would display "None" (not "one" as currently). In this case you'd 
Then you'd have to add the add the `title` yourself

Preferred : allow all options

**Comment by stsrki** [comment]
If I understood you correctly you want to have an item field that will internally be used to represent an empty or default item? So for example if `NothingSelectedText` attribute is used than there would need to be created `SelectItem` with default value and `NothingSelectedText` for the display?

**Comment by stsrki** [comment]
I think your first example is the best way to go for, as it's not hiding a behavior from other developers.
