### ISSUE TITLE
Technical writer(s) wanted

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#255]
A technical writer for Blazorise [documentation](https://blazorise.com/docs/) is wanted. As a single developer and maintainer of Blazorise I have less time to focus on a documentation. So any help would be appreciated.

In which areas you can help:

- proofreading of existing documentation (english native speaker is a +)
- writing missing and improving existing documentation
- writing articles on Blazorise features
- writing tutorials
- updating existing documentation to reflect changes in new releases

From my side I can offer help with understanding existing functionality to make it easier to document using a Slack or Gitter chat.

Please post below if you are interested.

**Comment by brettwinters** [comment]
Hi @stsrki 

I don't have a lot of time to dedicate to this (I'm waaaay behind on my own project), but I see you've open sourced the documentation so **we** (i.e your community of users) can submit pull requests on the docs as we go along? 

...although it seems from your post that you're looking for consistent / professional approach from a dedicated technical writer to join you as a team, right? 

Another issue is that there seems to be only a handful of users of Blazor (I'm definitely not one of them) that know what's going on under the hood (you see the same group of people on gitter) so it won't be easy to find anyone

Brett

**Comment by stsrki** [comment]
@brettwinters The best person(s) would be good in all of the things listed above. But it's not required. Mostly I need help with some spellchecking because English is not my native language so sometimes it can sound a little off. Also a lot of times I don't write some use-cases for components so that is also something to mention.

What I miss most are articles and tutorials. That is something I plan to do all the time but never have time to do. It would be used mostly to spread the word about Blazorise.

Back to your question. Yes it would work with PR as that is the best option in my opinion. I know there are not too many people around who use Blazor but hopefully that will change once it goes official.

**Comment by Herdo** [comment]
@stsrki Maybe as suggestion, join the [Hacktoberfest](https://hacktoberfest.digitalocean.com/details) and add some issues that are good for beginners. This could encourage people to do some documentation or other work on this awesome project 😁

**Comment by stsrki** [comment]
@Herdo Interesting approach. I might try it actually and see how it goes. tnx

**Comment by jhedgepeth** [comment]
Hi @stsrki I am a certified Technical Writer and also an English primary speaker/writer and I interested in helping you with your project

**Comment by lucamorelli** [comment]
hi, english is not my native language but I would like to be of help. still interested?

**Comment by stsrki** [comment]
Hi @lucamorelli 

Yes, still interested. You can start by going through the [CONTRIBUTING](https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md) page. Running documentation locally is the first step.

After that if you manage to change or fix anything just create the PR.

**Comment by lucamorelli** [comment]
done. do you have a todo list for documentation?

**Comment by stsrki** [comment]
@lucamorelli Not at the moment. For now you can focus on form components and proof read them. In case something is wrong or missing then change it.

In the meantime I will try to write a list of most critical ones. Is that OK?

**Comment by lucamorelli** [comment]
ok

**Comment by houstonhaynes** [comment]
@stsrki I volunteer as tribute! OK - so I can't jump in exactly at the moment - but soon. I found Blazorise as I was searching for a solution to my own project - and once I found it I was so happy I didn't sleep for nearly two days. I'm spending lots of time with the current docs as-is and definitely want to help. 

Once I get past the initial "growing pains" of my current project I'll probably know much more about Blazorise - and by extension - also places in documentation that could use more clarity.

So - it won't be immediate but help is on the way.

**Comment by stsrki** [comment]
@houstonhaynes That's good to hear, except for the no-sleep part :)

As you go through the pains of learning Blazor and Blazorise you will also learn about parts in the documentation that need to be fixed. Take your time, and when you're ready please let me know. Thank you!

**Comment by stsrki** [comment]
@Yuuliya That would be great, thanks. Please let me know if you need any help!

**Comment by stsrki** [comment]
Since by now nobody truly started to work on the documentation I guess it is time to close this ticket. 😥

**Comment by lucamorelli** [comment]
do as you want, but I'm waiting since April

@lucamorelli Not at the moment. For now you can focus on form components and proof read them. In case something is wrong or missing then change it.

In the meantime I will try to write a list of most critical ones. Is that OK?

**Comment by stsrki** [comment]
@lucamorelli Sorry about that. I didn't hear anything from you after your first message so I assumed you've moved on. If you still want to help we can communicate over https://gitter.im/stsrki/Blazorise, or just sent me a PM.

**Comment by Yuuliya** [comment]
Hi Mladen,

Thank you for coming back to me.
It's been a busy time, I am working full time now, but I am always
interested in technical writing and proofreading.
I guess I'll be able to devote a few hours a week, I'll certainly be able
to proofread whatever you have.

Please message me as soon as you have something for proofreading and I'll
take it right away.

Yuliya



вт, 1 дек. 2020 г. в 07:29, Mladen Macanović <notifications@github.com>:
