### ISSUE TITLE
Tab not work with blazor preview 9

### ISSUE THREAD

**Issue by whitedevils** [stsrki/Blazorise#259]
I have problem with blazorise tab with asp net core preview 9. 
I have followed the usage guide to install all things, but when i try to select tabs, content does't change. Anyone has same problem?
Thanks

**Comment by stsrki** [comment]
Can you please provide more information?

- Do you use server-side or client-side Blazor?
- What version of Blazor preview 9 you're using
- Post a sample code for tabs usage

**Comment by whitedevils** [comment]
I use server-side blazor project with version 9.19424.4 (the last)
This is the snippet
```
<EmbeddedContent BaseType="@(typeof(Tab))" Debug="true" />

<Tabs>
    <Tab Name="home" IsActive="true">Home</Tab>
    <Tab Name="profile">Profile</Tab>
    <Tab Name="messages">Messages</Tab>
    <Tab Name="settings">Settings</Tab>
</Tabs>
<TabsContent>
    <TabPanel Name="home" IsActive="true">
        ...
    </TabPanel>
    <TabPanel Name="profile">
        ,,,
    </TabPanel>
    <TabPanel Name="messages">
        ---
    </TabPanel>
    <TabPanel Name="settings">
        òòò
    </TabPanel>
</TabsContent>
```
```
@code
{
    bool hasConnected = false;
    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        if (firstRender)
        {
            StateHasChanged();
            hasConnected = true;
        }
    }
}
```

And i've imported these css and js
```
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
```

**Comment by stsrki** [comment]
For `Tabs` you're still required to set active tabs manually. I plan to fix this in the future but for know you can see a working example in [demo page](https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/TabsPage.razor).

Also since you're using server-side you should include js and css files. [example](https://github.com/stsrki/Blazorise#server-side)

**Comment by whitedevils** [comment]
Ah ok, so i'm not crazy! it will be usefull to report it in tutorial. 
For server-side i'm using BlazorEmbedLibrary that seems to work quite well

**Comment by stsrki** [comment]
You're right, it should be good to have note in the documentation.

**Comment by rzmz** [comment]
> Ah ok, so i'm not crazy! it will be usefull to report it in tutorial.
> For server-side i'm using BlazorEmbedLibrary that seems to work quite well

Can you provide an example? I have been trying to get that to work with no luck :(

**Comment by stsrki** [comment]
@rzmz I believe this is the line necessary for `BlazorEmbedLibrary` to work:

`<EmbeddedContent BaseType="@(typeof(Tab))" Debug="true" />`

But maybe @whitedevils will know more..

**Comment by whitedevils** [comment]
> @rzmz I believe this is the line necessary for `BlazorEmbedLibrary` to work:
> 
> `<EmbeddedContent BaseType="@(typeof(Tab))" Debug="true" />`
> 
> But maybe @whitedevils will know more..

Yes i did these! i put that row in mainlayout

**Comment by stsrki** [comment]
Done with #528
