### ISSUE TITLE
Could not find 'button' in 'window.blazorise'.

### ISSUE THREAD

**Issue by ToraSnow** [stsrki/Blazorise#265]
After updating to the newest version, I get this error.

Warning: Unhandled exception rendering component: Could not find 'button' in 'window.blazorise'.

Ive double checked that the blazorize.js files are referenced in my _Host file.

**Comment by stsrki** [comment]
Sorry about that. I completely forgot to upload new bundle for 0.8.5 release. You can find it now in https://github.com/stsrki/Blazorise/releases

**Comment by stsrki** [comment]
Closing the issue as I think the answer should fix the error. If you need more help please reopen.
