### ISSUE TITLE
DataGrid

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#266]
Is it possible to have all DataGrid rows editable, such as a spreadsheet?

**Comment by stsrki** [comment]
You need to set the `AllowEdit="true"` on column. eg.

`<DataGridColumn TItem="Employee" Field="@nameof(Employee.City)" Caption="City" AllowEdit="true" />`

Also you must set the `EditMode` to `Inline` on DataGrid: see https://blazorise.com/docs/extensions/datagrid/#editing

If you want to have **all** cells in the grid to be editable at once that's not possible at the moment.

**Comment by WillianGruber** [comment]
@stsrki if in inline mode, all lines editable would be very nice. May I open an issue about this?

**Comment by stsrki** [comment]
I'm not sure. I think it's best to leave it as it is now. If we're going to enable editing cell regardless of `AllowEdit` when `EditMode` is `Inline`, it is a special case and it would lead to confusion. Better to leave it as it now to allow for more control.

**Comment by WillianGruber** [comment]
@stsrki I still think a mass/bulk edit mode that supports copy/paste from something like excel should be great. Maybe a new component like BlazoriseSpreadsheet? Should I open a new issue as a pending suggestion?

**Comment by stsrki** [comment]
I'm really not sure. I think Spreadsheet should be entirely different component.

**Comment by WillianGruber** [comment]
OK, I'll try to implement it when my project needs it. Unfortunatelly, there are months of work ahead this.
