### ISSUE TITLE
DataGridNumericColumn does not sort numerically

### ISSUE THREAD

**Issue by ajmck** [stsrki/Blazorise#267]
When sorting a column with the component type DataGridNumericColumn, I expected it to sort in integer order (1, 2, 3, 10, 100), but instead it is sorted as if it were a column of strings (1, 10, 100, 2, 3).

**Comment by stsrki** [comment]
You're right it's sorted by string. I had trouble with Mono version that is used by Blazor so I had to fallback to string comparison when sorting. I will try to see if it's fixed in latest version and if it is I will add support for other data types.
