### ISSUE TITLE
ValidateAll() when ValidationMode.Manual does not work as expected

### ISSUE THREAD

**Issue by brettwinters** [stsrki/Blazorise#268]
Hi @stsrki 

Thanks for fixing the `validations.ClearAll()`, but I just noticed that the `validations.ValidateAll()` also doesn't work as expected: 

```html
@page "/main"
<Validations @ref="validations" Mode="ValidationMode.Manual">
    <Validation Validator="@ValidationRule.IsNotEmpty">
        <Field>
            <TextEdit Text="@TextValue">
                <ValidationError>Empty!!</ValidationError>
            </TextEdit>
        </Field>
    </Validation>
    <Blazorise.Button Clicked="@(() => validations.ValidateAll())">validate</Blazorise.Button>
    <Blazorise.Button Clicked="@(() => validations.ClearAll())">Clear</Blazorise.Button>
    <Blazorise.Button Clicked="@(() => {  TextValue = "two"; validations.ValidateAll(); })">Next Record and ReValidate</Blazorise.Button>
    <Blazorise.Button Clicked="@(() => { validations.ClearAll();  TextValue = "three"; })">Clear then Next Record</Blazorise.Button>
</Validations>
@code{
    Validations validations;
    string TextValue { get; set; } = "one";
}
```

Steps to reproduce: 

(1) navigate to "/main"
(2) clear contents of `TextEdit` and press "Validate" (ie `ValidateAll()`) note that validation fails as expected
(3) press "next record" button which updates the `TextValue = "two"` and calls ValidateAll() but note that the TextEdit continues to show a validation error from the previous 'record'.  Pressing Validate button also doesn't clear the validations.

Choosing the ClearAll() works as expected, but if you go to `TextValue = "three"` and go back, the validation error returns!? (even when clearing multiple times)

I would expect that calling  `validations.ValidateAll()` would clear the previous validation and re-run the validator.

Regards

Brett

**Comment by stsrki** [comment]
It's probably the same problem as with ClearAll(). I will look into it.

**Comment by stsrki** [comment]
So I've being playing with this for a last few days. And the conclusion so far is that there is no simple way to do this.

When you click on a button, Blazor is setting the `TextValue` but it will be actually binded to `TextEdit` **after** the event is over. So no matter if you call `validations.ValidateAll()`, the text value is still the same as before. Only after the event has finished the `StateHasChanged()` will be called internally by Blazor. 

I made it to work by setting it like this but it's a hack and it must be avoided as generally setting the parameters manually is not recommended.

```diff
<Validations @ref="validations" Mode="ValidationMode.Manual">
    <Validation Validator="@ValidationRule.IsNotEmpty">
        <Field>
-            <TextEdit Text="@TextValue">
+            <TextEdit @ref="textEdit" @bind-Text="@TextValue">
                <ValidationError>Empty!!</ValidationError>
            </TextEdit>
        </Field>
    </Validation>
    <Blazorise.Button Clicked="@(() => validations.ValidateAll())">validate</Blazorise.Button>
    <Blazorise.Button Clicked="@(() => validations.ClearAll())">Clear</Blazorise.Button>
-    <Blazorise.Button Clicked="@(() => { TextValue = "two"; validations.ValidateAll(); })">Next Record and ReValidate</Blazorise.Button>
+    <Blazorise.Button Clicked="@(() => { textEdit.Text = TextValue = "two"; validations.ValidateAll(); })">Next Record and ReValidate</Blazorise.Button>
    <Blazorise.Button Clicked="@(() => { validations.ClearAll();  TextValue = "three"; })">Clear then Next Record</Blazorise.Button>
</Validations>
@code{
    TextEdit textEdit;
    Validations validations;
    string TextValue { get; set; } = "one";
}

```

**Comment by brettwinters** [comment]
Hmmmm I’m on my annual holiday now. Is see the issue and workaround. Does this mean that manual validation shouldn’t really be used?

**Comment by stsrki** [comment]
So I made a simple test that demonstrate an issue with Blazor two-way binding and how Blazor cannot handle it.

Full example can be found on https://github.com/stsrki/BlazorBindingTestIssue

```cshtml
<h1>Bind Test</h1>

<p>Current value: @value</p>

<Textbox @ref="textbox" @bind-Value="@value"></Textbox>

<button class="btn btn-primary" @onclick="Test">Click me</button>

@code {
    Textbox textbox;
    string value = "one";

    void Test()
    {
        value = "two";
        
        Console.WriteLine( textbox.Value );
    }
}
```

Result:

`WASM: ﻿one`

The same problem is happening with validation because it's expecting new value bit is getting previous, and so it will fail. Manual validation should still be used for "submit" but not with this kind of scenarios where you need to reset input by setting it through variable. Automatic validation should be used instead.

I will report this problem to Blazor team and see how it goes.

PS. enjoy your holiday :)

**Comment by stsrki** [comment]
I've been thinking more about this over the weekend and I think there is not much I can do. As I see it it's a limitation in Blazor and there is no way I can think of that can keep track of changing variable before the event-callback has finished. That's just how the render tree builder is working.
I know the posted workaround is not the best way to do it but unfortunately it's the only way. For now I will close this issue.

If you have some idea or maybe find another way please reopen.
