### ISSUE TITLE
Feature Request: Add ability to display close button on badge

### ISSUE THREAD

**Issue by kamilkosek** [stsrki/Blazorise#281]
Hi,
see i.e. this fiddle : [https://codepen.io/gijsbotje/pen/OjOmby](https://codepen.io/gijsbotje/pen/OjOmby )
An additional event CloseClicked would be necessary.

**Comment by stsrki** [comment]
@kamilkosek Sorry it took me way too long to do this feature. It's finally done and will be available in the next version soon.
