### ISSUE TITLE
Static assets problem

### ISSUE THREAD

**Issue by PhilPJL** [stsrki/Blazorise#282]
With build 0.8.6 I'm now getting this error

![image](https://user-images.githubusercontent.com/271656/65671645-81fe5100-e03f-11e9-83a2-e7ccf7ac50af.png)

I previously had the same issue with [ tewr's file reader ]  (https://github.com/Tewr/BlazorFileReader/issues/55).

You may need to ask him how he fixed that issue.

**Comment by stsrki** [comment]
It seems like a bug in `dotnet pack` to me. It's working just fine for projects that have static css and js files. But for projects like `Blazorise.Icons.FontAwesome` that doesn't have any static files it generates content files in `nupkg` and everything fails.

I'm trying to come up with solution.

**Comment by stsrki** [comment]
I have uploaded new version. Can you try it and see if the error is still there?

**Comment by PhilPJL** [comment]
@stsrki. Fixed thanks.
