### ISSUE TITLE
Live data charts

### ISSUE THREAD

**Issue by Flearz** [stsrki/Blazorise#284]
Hello,
I got a server constantly calculating a sine wave, and I would like to represent it using a chart that would be updating in "real-time". I get my values by making constant http requests. Do you think it would be possible with blazorise ? Thanks for you job you're awesome.

**Comment by stsrki** [comment]
Do you mean something like this https://nagix.github.io/chartjs-plugin-streaming/ ?

**Comment by Flearz** [comment]
Yeah exactly, but I don't want to use pure JS in my project :)

**Comment by stsrki** [comment]
For now you can just update dataset manually every n seconds. Although that would look pretty weird every time it updates.

I need to see how to handle third-party plugins for chartjs.

**Comment by Flearz** [comment]
Thank, hope it will be successful.

**Comment by 199621616** [comment]
@stsrki 你很棒！

**Comment by MaxThom** [comment]
Hi, is it possible to instead of refreshing the data every X seconds, add data as the api request comes in ?

**Comment by stsrki** [comment]
Yes, you can use `AddData` or `SetData` methods on the chart.

**Comment by MaxThom** [comment]
But when I do, the dots are not linked by a line.

**Comment by stsrki** [comment]
You could also try live-streaming https://blazorise.com/docs/extensions/chart/#third-party-plugins

**Comment by MaxThom** [comment]
Thats what I use, my data is coming from SignalR. I made work by timing the refresh and the incoming data. But I would prefer to each time a data comes in, it is added to the chart. When I try to use AddData() and Update(), the dots are not linked.
![image](https://user-images.githubusercontent.com/26239574/98551129-f78ca700-226a-11eb-84a3-a49cc81ba7dd.png)

**Comment by stsrki** [comment]
It looks to me like chart options are not properly configured. Look at these

https://github.com/chartjs/Chart.js/issues/800
https://www.chartjs.org/docs/latest/charts/line.html
