### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by dtitovgis** [stsrki/Blazorise#285]
Autocomplete not set the value in HTML after choose.

**Comment by stsrki** [comment]
Please post complete code sample so I can reproduce it and also please give me more information of what you expect to happen. Thanks

**Comment by dtitovgis** [comment]
After click on item values is set in code but not in browser.
Version components 0.8.6.1
 
       <Autocomplete Data="@ITSO"
                      TextField="@((item) => item.Name)"
                      ValueField="@((item) => item.Id)"
                      SelectedValue="@SelectedITSOId"
                      SelectedValueChanged="@((item)=>ITSOChange(item))"
                      Placeholder="asd" />
@code {
    ITSO SelectedITSO;
    object SelectedITSOId;

    void ITSOChange(object itso)
    {
        SelectedITSO = ITSO.Find(i=>i.Id == (int)itso);
        SelectedITSOId = itso;
    }

**Comment by stsrki** [comment]
I tried Autocomplete in the demo and the value is set just fine.

![image](https://user-images.githubusercontent.com/900302/65761206-a846ee00-e11e-11e9-897d-b7e6124c7254.png)

If you want to see the value attribute in the html that is not going to work as by default browsers are hiding that attribute from html.

**Comment by dtitovgis** [comment]
maybe something missed in docs? For example in docs 
<Autocomplete Data="@myDdlData"
    TextField="@((item)=>item.MyTextField)"
    ValueField="@((item)=>item.MyTextField)"
    SelectedValue="@selectedSearchValue"
    SelectedValueChanged="@MySearchHandler"
    Placeholder="Search..." />
SelectedValueChanged="@MySearchHandler" - will not work

**Comment by dtitovgis** [comment]
not work if value is id for example:

>     TextField="@((item)=>item.MyTextField)"
>     ValueField="@((item)=>item.MyValueField)"

it works only for text :(

>               TextField="@((item) => item.MyTextField)"
>               ValueField="@((item) => item.MyTextField)"

**Comment by stsrki** [comment]
You're right, search field does not update when value field is different than `MyTextField`. I will investigate more.
