### ISSUE TITLE
Tabs styling is a bit off. what might i be doing wrong?

### ISSUE THREAD

**Issue by githubfanster** [stsrki/Blazorise#287]
i created a new Server-Side project to learn how to use the Tabs group of components.
i deleted the default bootstrap css that came with the default Blazor project template but retained the site.css file because eventually i will use the Blazorise Tabs page i'm working on into our "real" development project, which currently uses the default Sidebar and NavMenu (we've added stuff to the default Home / Counter / Fetch Data razor pages so we dont want to lose our work.)

Enclosed zip includes only the default sidebar pages + the added Blazorise (version 08.6.1) Tabs Page that's not displaying quite right. The code is from the Blazorise Demo , and our experience is that the "Home" tab is displaying always below the three other tabs (Profile, Messages, Setting).

Might you be able to tell what we're doing wrong? Probably a conflicting or missing css style in the site.css?? 

Thanks for helping!
[BlazoriseTabs.zip](https://github.com/stsrki/Blazorise/files/3663529/BlazoriseTabs.zip)

**Comment by stsrki** [comment]
Hi,
I checked your test project and the problem is in the `site.css.` You should remove all `.nav-item` classes and it should work. In case you want to keep them you should add the `.sidebar` class-name so that they don't interfere with native Bootstrap styles.

eg.

```css
.sidebar .nav-item {
   ...
}
```

**Comment by githubfanster** [comment]
thank you. that worked!
