### ISSUE TITLE
Using Blazorise Charts - Could not find 'blazoriseCharts' in 'window'

### ISSUE THREAD

**Issue by andrewwilkin** [stsrki/Blazorise#288]
Not sure where I'm going wrong, probably something I'm doing for sure.  Trying to create a Sparkline bar chart, before I connect real data want to see how it looks but get this error in the console:
`blazor.webassembly.js:1 WASM: Microsoft.JSInterop.JSException: Could not find 'blazoriseCharts' in 'window'.`

I've done the following:
- Add Blazorise Charts Nuget
- Add reference to it in the _Imports.razor
- Add a reference to the Chart JS in the index.html

Have looked through the example code here and cannot see anything obvious though am using BarChart instead of Chart:
https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/ChartsPage.razor

I can see the canvas generated in the source. Can you point me to the likely error of my ways please :)

**Comment by stsrki** [comment]
You also need to add path to the charts js. See [here](https://github.com/stsrki/Blazorise/blob/473ba8b6714d2196812922dc3f2d820c0d457ec4/Tests/Blazorise.Demo.Bootstrap/wwwroot/index.html#L46)
This is now a preferred way to handle static files for razor class libraries.

It seems I will also need to mention this in documentation for chart extension.

**Comment by andrewwilkin** [comment]
Thanks - that works now 👍 

Is there much control over how the chart appears? As wanted to create a Sparkline chart so no axis, labels, etc?

**Comment by stsrki** [comment]
I guess it can be done, but you would probably need to look at the official chartjs documentation for that kind of stuff.

**Comment by stsrki** [comment]
Added to documentation
