### ISSUE TITLE
Impossible to use charts

### ISSUE THREAD

**Issue by Flearz** [stsrki/Blazorise#289]
Hello,
I got issue using charts.
I create a new WASM Blazor (3.0.0-preview9.19465.2) project and I follow the Blazorise installation steps conscientiously (I'm not sure I understood the "static files" part, but I looked at your test project and the same index.html... ). Then I install the charts but when I write the test code in my page, firstly I got "CS011: '__generated__Counter.OnAfterRenderAsync()' " and If I comment this my chart doesn't draw when I click "Redraw". Thanks in advance

**Comment by stsrki** [comment]
Make sure that you add static files to index.html
`<script src="_content/Blazorise.Charts/blazorise.charts.js"></script>`

Also maybe you're missing a line `@using Blazorise.Charts` from `_Imports.razor` file

**Comment by Flearz** [comment]
Thanks for your answer, I did this, but it is still not working, a friend who's using charts too used it in version 3.0.0-preview9.19457.4 and it is working (With a lot of errors in the browser console). I will upload my project on my github pages if you want to have a look (flearz.github.io). Thanks in advance.

**Comment by stsrki** [comment]
Please upload your project so I can get a better look.

**Comment by Flearz** [comment]
It's done, https://github.com/Flearz/flearz.github.io in source

**Comment by stsrki** [comment]
Just add this and it should work

```
protected override async Task OnAfterRenderAsync( bool firstRender )
{
    if ( firstRender )
    {
        await HandleRedraw();
    }
}
```

**Comment by Flearz** [comment]
Woaw, fixed it, maybe it would be good to change it too in the example code on your website. Thank you :)

**Comment by Flearz** [comment]
Woaw, fixed it, maybe it would be good to change it too in the example code on your website. Thank you :)

**Comment by stsrki** [comment]
Docs updated!
