### ISSUE TITLE
Demo project available?

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#294]
I'm struggling a bit to get a test project working and it would be beneficial to see the demo code that you have at:
https://bootstrapdemo.blazorise.com/

Are you able to make this demo solution available on github?

**Comment by stsrki** [comment]
You have everything available under the Tests folder.

**Comment by stsrki** [comment]
This is the base project for all the demo apps: https://github.com/stsrki/Blazorise/tree/master/Tests/Blazorise.Demo

Client side project: https://github.com/stsrki/Blazorise/tree/master/Tests/Blazorise.Demo.Bootstrap
Server side hosting project: https://github.com/stsrki/Blazorise/tree/master/Tests/Blazorise.Demo.Bootstrap.Server

If you need more help please let me know.

**Comment by robalexclark** [comment]
Sorry my mistake I was looking in the wrong place.
