### ISSUE TITLE
Autocomplete is not works fine

### ISSUE THREAD

**Issue by ShikaTech** [stsrki/Blazorise#300]
Hi!
I found two problems on `Autocomplete` component.
I will update program codes on my forked Repository.

Problems
--
1. Simple string value on `SelectedValue`, was not equals.
1. `SelectedValue` and `SelectedText` are not initialized when `SelectedValue` has an initial value and it is updated with an empty value.

Guess
--
1. Boxed string values are of type `object` and are considered different objects even if the duplicate string is the same.
1. `SelectedText/Value` is set only when the `HandleDropdownItemClicked` event is fired, and there is not enough consideration when the string disappears from the input area.

**Comment by ShikaTech** [comment]
My forked repository was updated.
https://github.com/ShikaTech/Blazorise/commit/b75cfe04f16a15346457b6cb4522837b15686ff3
May I create a pull request?

Thanks.

**Comment by stsrki** [comment]
Could be the same issue as with #285. I have fixed those already.

Can you switch to **dev087** branch and see if the your issues are still present. And if not you can create a PR, but if possible do it on dev branch. tnx

**Comment by ShikaTech** [comment]
Thank you for your reply. And I'm sorry for the late comment.

It seems that problem 1 is certainly solved by "dev087".
However, since problem 2 did not continue to work as expected, I corrected it in my repository.
Can you see this? https://github.com/ShikaTech/Blazorise/commit/4fb600efcc51e6f1e7587d911e3e623aaee4931b

Expected behavior
--
Set the initial value to the property of SelectedValue.
If this input area is emptied, the property value will also be empty (or NULL).

Actual behavior
--
SelectedValue does not become empty even if the input area is empty.

What happens
--
For example, this component was used to select “Favorite Country” in the profile settings. After that, even if the input area is emptied to clear the profile settings, the property value does not change, so the update cannot be performed.


Regards
