### ISSUE TITLE
Fix RenderCustomComponent and usage of ParameterView

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#315]
Using of `ParameterView` has changed in 3.1. It's no longer possible to save it for later usage in `RenderCustomComponent()` because it's raising an error:

> throw new InvalidOperationException($"The {nameof(ParameterView)} instance can no longer be read because it has expired. {nameof(ParameterView)} can only be read synchronously and must not be stored for later use.");

Blazorise need to save parameters so it can override components structure in Bulma, eFrolic and later in Ant Design. Currently I have made a workaround to save parameters as a Dictionary but in the long term this should be avoided.

The reason for this ticket is to find a better way to handle rendering of custom components.

**Comment by VR-Architect** [comment]
I am having the same error on 3.1 when trying to call my async DAL class via an await inside the SetParametersAsync.

LoginDisplay.razor file
```
// The goal of this code is to enrich the logged in user with data from the database to put in memory
    public override async Task SetParametersAsync(ParameterView parameters)
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        var user = authState.User;

        if (user.Identity.IsAuthenticated)
        {
            if (GlobalsService.CurrentUser.UserId == Guid.Empty)
            {
                Guid UserId;
                Guid.TryParse(UserManager.GetUserId(user), out UserId);

                OrgPersonDAL orgPersonDAL = new OrgPersonDAL();
                // Fails on next line
                GlobalsService.CurrentUser = await orgPersonDAL.GetOrgPersonByUserId(UserId);
            }
        }
        else
        {
            GlobalsService.CurrentUser = new DbModels.OrgPerson();
            GlobalsService.SelectedAssociation = new Voogu.Areas.Association.AssociationPickerItem();
            GlobalsService.SelectedTenant = new Voogu.Areas.Tenant.TenantPickerItem();
        }

        // comment next line results no errors, but the login bar is missing information
        await base.SetParametersAsync(parameters);
    }
```
