### ISSUE TITLE
Datepicker does not allow you to change the date a second time, Material

### ISSUE THREAD

**Issue by stevenfellows** [stsrki/Blazorise#318]
Tried using date in my app..

Allows you to pick the date  once but not change it.

Your web site does the same
https://materialdemo.blazorise.com/tests/forms

**Comment by stsrki** [comment]
It's an issue in Chrome and `Daemonite css`. See here https://github.com/Daemonite/material/issues/232

**Comment by srebelo001** [comment]
https://github.com/Daemonite/material/issues/232 Updated with a workaround.

Please let me know if it helped.

Regards,

Sérgio

**Comment by stsrki** [comment]
Waiting until [djibe](https://github.com/djibe) updates material to the newest bootstrap version.

https://github.com/Daemonite/material/issues/197

**Comment by WillianGruber** [comment]
Just so everybody knows, there is a way to change it a second time...
With the mouse over the date field:
1)Click and hold left mouse button
2)Click right mouse button
3)Release left mouse button (the browser context menu will stay open)
4)Move the cursor to the popup and left click any part of it so the context menu closes.
5)The date picker will stay open, just use it normally now...

**Comment by WillianGruber** [comment]
Using the up-to-date version of djibe, this happens:
![image](https://user-images.githubusercontent.com/56033692/84837017-6132bd00-b00d-11ea-9dc0-e318e7eef09f.png)

When implementing his css, please remember to check double popup when first clicking the control.

**Comment by stsrki** [comment]
Replacing material javascript file in **index.html** or **_Host.cshtml** with the one from https://djibe.github.io/material/docs/4.5/getting-started/introduction/ fixes the problem. The same fix is also done in our demo application. 
Since this is the external problem I think this is the best option.

I will close this issue as I feel there is no need to have it opened anymore.
