### ISSUE TITLE
Can't find bundle.zip

### ISSUE THREAD

**Issue by intech-paul** [stsrki/Blazorise#319]
Hi, I have made a sample blazor app using vs2019 and have been converting to use blazorise, it picks  up the sidebar settings ok, but I can't get the chart to work. I see other comments about bundle.zip, where do I download that from ? Thanks.

**Comment by stsrki** [comment]
Bundle is obsolete now. It's being used in previous versions for server-side Blazor project. Now static files must be defined manually in the `index.html` for client-side or in `_Host.cshtml` server-side projects.

https://github.com/stsrki/Blazorise#5-static-files

**Comment by stsrki** [comment]
Closing the issue as I think the question has being answered. If you need more help please reopen. tnx
