### ISSUE TITLE
Validation not updating after reference is changed

### ISSUE THREAD

**Issue by mfitconsultants** [stsrki/Blazorise#320]
In my code I have a popup for basic CRUD on a POCO. When using the Blazorise Validations to enforce field requirements and reusing the same popup I need to reset the validations back. However, the validation is seemingly holding onto the initial validation and `ValidateAll()` is returning true when in fact it is not.

Calling `Clear()` on the validation seems to reset the UI however I can still bypass validations onb a second run through. 

I bind the Validation to a reference as follows;

                   <Validations @ref="companyValidations" Mode="ValidationMode.Auto">
                        <Fields>
                            <Field IsHorizontal="true" ColumnSize="ColumnSize.Is5.OnDesktop">
                                <Validation Validator="@ValidationRule.IsNotEmpty">
                                    <FieldLabel ColumnSize="ColumnSize.Is3.OnDesktop">Company</FieldLabel>
                                    <FieldBody ColumnSize="ColumnSize.Is9.OnDesktop">
                                        <TextEdit @bind-Text="@Company.Name" Placeholder="Enter the Company Name..">
                                            <Feedback>
                                                <ValidationError>Please enter a Name for the Company!</ValidationError>
                                            </Feedback>
                                        </TextEdit>
                                    </FieldBody>
                                </Validation>
                            </Field>

                            <Field IsHorizontal="true" ColumnSize="ColumnSize.Is5.OnDesktop">
                                <Validation Validator="@ValidationRule.IsNotEmpty">
                                    <FieldLabel ColumnSize="ColumnSize.Is3.OnDesktop">Website</FieldLabel>
                                    <FieldBody ColumnSize="ColumnSize.Is9.OnDesktop">
                                        <TextEdit @bind-Text="@Company.Website" Placeholder="Enter the Web Address..">
                                            <Feedback>
                                                <ValidationError>Please enter a Website Address for the Company!</ValidationError>
                                            </Feedback>
                                        </TextEdit>
                                    </FieldBody>
                                </Validation>
                            </Field>
                        </Fields>
                    </Validations>

with

    Validations companyValidations = new Validations();

in my `Code` section. This works fine the first time, however, if I then reuse the component and reset the `Company` instance, the previous validation are being shown? For example I would load the popup containing the Form, enter a valid `Company.Name` and `Company.Email`. I would then reload the popup and reset the referenced variable using `Company = new Company();` which clears the text box data, but for some reason calling `companyValidations.ValidateAll()` is returning true still?

For completion I do this through a public method on the component;

    public void Reset()
    {
        Company = new CompanyInputModel();      
        
        companyValidations.ValidateAll();
        companyValidations.ClearAll();     
        StateHasChanged();
    }

I have played around with the order however, I cannot seem to reset the validations to 'refresh' when I reset the bound model??

I have tried setting hte `ValidationMode` to both `Validation.Auto` and `Validation.Manual` but the issue persists?

**Comment by stsrki** [comment]
I have tried your example and you're right. The validation is not working as expected. I'm currently in the middle of refactoring validations and input fields so I can probably include this in the process. It should be in the v0.8.7

**Comment by stsrki** [comment]
The bug is fixed and it should be available in the next version.
