### ISSUE TITLE
Change appearance of DataGrid

### ISSUE THREAD

**Issue by kamilkosek** [stsrki/Blazorise#322]
Hi, is there a possibility to change the appearance of the DataGrid ?
i.e. 

- Change Color of row on hover 
- change Color of row based on centextual values

Thanks :)

**Comment by stsrki** [comment]
Not at the moment, at least not in the way you want it. Currently it only supports simple table styling like  bordered, border-less, stripped, etc.

I plan to add support for styling sometime in the 0.9+ milestone. But for now the best way for you is to play with CSS for hover rules. But for centextual values you'll have to wait a little.

**Comment by kamilkosek** [comment]
Thanks so far, I think I will fiddle around  with the usual Table Componen.t
