### ISSUE TITLE
[Notice] Development temporarily slowed down

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#323]
I want to give some info of why the **v0.8.7** is taking so much time to finish. The reason is I'm currently moving between jobs. A lot of stuff is happening and due to that the development of Blazorise is temporarily slowed down.

Everything is still going as planned and will be done eventually. It's just going to be a little slower until I settle down.

**Comment by jzabroski** [comment]
You have probably one of the coolest names for a project out there.
