### ISSUE TITLE
grid sort

### ISSUE THREAD

**Issue by dtitovgis** [stsrki/Blazorise#327]
Sort in DataGrid only as a string.

**Comment by stsrki** [comment]
Hi @dtitovgis 

Can you describe little more what you want to accomplish? tnx

**Comment by dtitovgis** [comment]
1,2,3,4,5,6,7,8,9,10,11 will sort as 1,10,11,2,3,4,5,6,7,8,9.

**Comment by stsrki** [comment]
It's already fixed in v0.8.7 with #267 

Only thing left now before the release is to write the release notes. It should be in a day or two.
