### ISSUE TITLE
TextEdit focus cursor

### ISSUE THREAD

**Issue by Saeidasadi32** [stsrki/Blazorise#332]
hi
how do i set focus cursor to textedit
I write 
window.EFocus = {
    focusElement: function (element) {
        element.focus();
    }
}
and then call 
    public async Task  NewCompany()
    {
        newItem = true;
        selectedCompany = new Company();
        await JSRuntime.InvokeVoidAsync(
            "EFocus.focusElement", Cmid);        
    }
but after run this page has error :
Object of type 'Blazorise.TextEdit' does not have a property matching the name 'id'.

**Comment by stsrki** [comment]
I will reopen this as I think this should be pretty good feature to have.

## Solution

Add new method `Focus()` to `TextEdit` >`BaseInputComponent `.
