### ISSUE TITLE
is it possible to draw multi line chart in one chart?

### ISSUE THREAD

**Issue by Saeidasadi32** [stsrki/Blazorise#336]
Hi again
is it possible to draw multi line chart in one chart?
I have multi column data and i need to draw multi line in one chart like Execl
Thank you

**Comment by intiharj** [comment]
Yes, you can do this by adding multiple datasets (one for each line series).  Look for the LineChart.AddDataSet method.

**Comment by Saeidasadi32** [comment]
Thank you for your answer and i check it.
if I have datatable with many column and i need to draw line chat i must be call for any column LineChart.AddDataSet method or not?
