### ISSUE TITLE
Update Blazorise to the new Razor Components

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#34]
NET Core 3.0 preview 2 is now released and Blazorise should be updated to the latest version of Razor Components. There are two options now.

- Wait for the Razor Components to exit _preview_ version
- Upgrade now and keep track of any changes as they go

**Comment by stsrki** [comment]
Both Blazor and the new Razor Components are targeting the same **netstandard2.0** framework, and so it's difficult to setup projects files for different libraries. Also all of the namespaces should be changed. Therefore Blazorise will be updated for Razor Components in the next **0.6** version.

Since Razor Components are still marked as preview the Blazorise 0.6 will also be marked as such eg. _0.6-preview-19075-0444_ where the preview number will match the Razor Components version number.

**Comment by jonmiller1** [comment]
Looking forward to the Razor Components update!

**Comment by stsrki** [comment]
Tried to update to Razor Components but there were some issues with the library class project. It seems RC still doesn't support content files. Hopefully it will be fixed.

Instead Blazorise is now updated to the new Blazor 0.8 preview. The new Blazor version is now a weird mixture of Razor Component and Blazor namespaces. I guess it is just temporary.

Anyways, the Blazorise is now running fully on Blazor 0.8 preview and as far as I can see it feels noticeably faster.
