### ISSUE TITLE
Effect of Gradient Colors in Theme Selector

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#345]
Turning on and off the Gradient Colors in the demo page https://materialdemo.blazorise.com/tests/forms changes nothing. Is this a bug?

**Comment by stsrki** [comment]
Input fields doesn't have support for gradient colors. If you scroll a little down the forms page you can see that dropdowns and buttons are changing the color.

**Comment by WillianGruber** [comment]
I see. It is a subtle change, didn't even notice. Is there a way to increase/configure the gradient level?

**Comment by stsrki** [comment]
Not for now. But I can consider adding the option in v0.8.8
