### ISSUE TITLE
Checkbox component color 

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#346]
What is the Theme option to change the default pink fill in the Check component?
![image](https://user-images.githubusercontent.com/56033692/68868510-6970f580-06d6-11ea-8cf3-55dd6b9ba7b6.png)

I've tried:
`Theme.InputOptions.Color = value;`
`Theme.ColorOptions.Secondary = value;`
and it does not change.

Thank you!

**Comment by stsrki** [comment]
I believe that's the CSS rule from daemonite _material.css_, specifically `custom-control-label:after`. Currently it cannot be changed through Blazorise theme settings.
