### ISSUE TITLE
Sidebar width and Bar height

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#350]
When using the Bar and the Sidebar components, if we use JSInterop to get window.innerWidth and window.innerHeight to get the window size (in my case, I'll draw a canvas), the result doesn't account for sidebar width and bar height.

So, in order to get the real value we should subtract sidebar width and bar height.
Is it possible to implement a public getter on them? Sidebar width is 220px as in blazorise.sidebar.css but I couldn't find the Bar height.

Optional:
Can we define the sidebar width with code (in px and % of window)? What about a draggable border?

Edit: Just found the Bar height. My fault.

**Comment by stsrki** [comment]
The only option for now is for you to use java-script to get the bar and sidebar elements to get the width/height.

I can consider adding width and height properties to the Sidebar and Bar.
