### ISSUE TITLE
Automatically set Breadcrumb active state based on navigation url

### ISSUE THREAD

**Issue by gallwood** [stsrki/Blazorise#351]
Hi,
Can someone explain a little more how to use the Breadcrumb component? I thought I should be able to place one at the top of the MainLayout page, and using the `To` property it matched what page was displays and adjusted it's rendering accordingly. Or should I be putting logic in to may pages to make BreadcrumbItems active on certain pages?

FYI, I have 3 pages, p1, p2 and p3 using a route of /p1, /p2, /3. In my Breadcrumb component, I define three Items with links. Each link has a `To` property set to `p1`, `p2` and `p3`

Thanks for your help.

**Comment by stsrki** [comment]
Hi @gallwood 

You should use `IsActive` attribute on `BreadcrumbItem` when you navigate to your specific page url.

**Comment by gallwood** [comment]
Hi, thanks for getting back to me so quick.

Ah, right. I think I know what I can do then. It's a pity the Breadcrumb doesn't set each item as active when the items associated link matches the current page.

**Comment by stsrki** [comment]
I might do that but I need to think it through. What if someone need to control breadcrumb items without using the urls for navigation? 🤔 

Anyways it's going on backlog.

**Comment by gallwood** [comment]
Thank you @stsrki
