### ISSUE TITLE
NavBar rework on BS demo page

### ISSUE THREAD

**Issue by peterblazejewicz** [stsrki/Blazorise#352]
Thanks for the project!
Could we rework some details on the demo pages?
For example on the BS demo the navbar looks like this once loaded:

![navbar-demo](https://user-images.githubusercontent.com/14539/68929919-9502e700-078d-11ea-8298-cae96d48659a.PNG)

While I believe it should (with corrected component markup details like component class) looks like:

![navbar-demo-1](https://user-images.githubusercontent.com/14539/68929942-a3510300-078d-11ea-8912-dabc273bef42.PNG)
![navbar-demo-2](https://user-images.githubusercontent.com/14539/68929943-a3e99980-078d-11ea-84dd-5ffcc0ddd814.PNG)

**Comment by stsrki** [comment]
Hi @peterblazejewicz 

I agree with you. The _brand_ color should be calculated based on the bar background color(light/dark).

Since this is a theming issue it needs to be done through the `ThemeGenerator`. And it seems I forgot to add implementation for the navigation bar.
