### ISSUE TITLE
SidebarSubItem expand when you navigate away from it

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#359]
**Describe the bug**
The subitem expands when you navigate away from it.

**To Reproduce**
1. Go to https://materialdemo.blazorise.com/
2. Click on 'Test Pages'. The subitem 'Test Pages' collapses.
3. Click on 'Dashboard'. The subitem 'Test Pages' expands.

**Expected behavior**
The subitem 'Test Pages' shouldn't expand when you navigate away from it.
This issue occurs in my application too, not only in the demo page.

**Comment by OscarCanek** [comment]
When I use the sidebar It shows like this:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/3521524/69102208-512b0e80-0a27-11ea-998e-2555df9a313c.png">

Could you help me?

**Comment by stsrki** [comment]
@OscarCanek Have you included `sidebar.css` into your `index.html` or `_Host.cshtml`?

eg. 
```html
<link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />
```

PS. FYI if you want to ask questions in the future please open new issue. tnx

**Comment by WillianGruber** [comment]
If it helps, expanding the subitem, clicking on an item inside it, and then clicking on an item not inside that subitem won't collapse the subitem.

**Comment by stsrki** [comment]
The problem is in the `IsShow` where it's always set to true. I will fix it.

```cshtml
<SidebarLink Toggled="(isOpen)=> sidebarSubItemTests.Toggle(isOpen)" IsShow="true">
    <Icon Name="IconName.Edit" Margin="Margin.Is3.FromRight" />Test Pages
</SidebarLink>
```

**Comment by WillianGruber** [comment]
@stsrki did you fix this?

**Comment by WillianGruber** [comment]
This is a workaround:
```
<SidebarLink Toggled="(isOpen)=> { SidebarSubItemOthersShow = isOpen; SidebarSubItemOthers.Toggle(isOpen); }" IsShow="@SidebarSubItemOthersShow">
```
And to base class add:
```
        protected bool SidebarSubItemOthersShow { get; set; }
```

will leave this open in case you want to change it internally to the component

**Comment by stsrki** [comment]
@WillianGruber Sorry for answering before. I'm on a business trip and doing meetings all day. It's great you managed to come up with solution.

**Comment by WillianGruber** [comment]
Nice, I hope it all goes well.
About this subject, if the way I did it is the intended way, we I can close this issue

**Comment by stsrki** [comment]
Sure, this is actually a preferred way of doing it.

**Comment by WillianGruber** [comment]
Ok, closing. Thanks
