### ISSUE TITLE
Expand list of Icon types/names

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#36]

**Comment by stsrki** [comment]
[Material.x.FontAwesome.Icons.xlsx](https://github.com/stsrki/Blazorise/files/3913361/Material.x.FontAwesome.Icons.xlsx)

List if icons, done by @WillianGruber

**Comment by WillianGruber** [comment]
Remember it's only the free icons. Many material icons exist only in paid version of FA.

**Comment by stsrki** [comment]
I don't have much experience with paid icons. Maybe there can be a provider included in Blazorise that can handle paid icons via credentials or whatever the requirements are.
