### ISSUE TITLE
Feature request: Switchers

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#363]
The Check actually only implements checkboxes and radiobuttons.
Is it possible to extend the Check component to accept switches as well?
Example: https://material.io/components/selection-controls/
Also, the 3 of them could have their color customized by the Theme Provider.

Thank you!

**Comment by stsrki** [comment]
The Switch component is planned to be done but with all other work in the way it won't be before the v0.9

**Comment by WillianGruber** [comment]
hi @stsrki , is this already included in theme?

**Comment by stsrki** [comment]
You mean the color? it is controlled with the same variable as regular `CheckEdit`: `ThemeInputOptions.CheckColor`

**Comment by WillianGruber** [comment]
Nice!
