### ISSUE TITLE
Feature request: Sliders

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#364]
Is it possible to implement a component for sliders?
Ref: https://material.io/components/sliders/#

Thank you!

**Comment by stsrki** [comment]
Is something like this OK:?

Bootstrap: https://getbootstrap.com/docs/4.3/components/forms/#range-inputs
Bulma: https://wikiki.github.io/form/slider/

**Comment by WillianGruber** [comment]
The Bulma one is very nice.

**Comment by WillianGruber** [comment]
Nice! Will fit perfectly on my theme designer!

**Comment by WillianGruber** [comment]
hi @stsrki , is this already included in theme?

**Comment by stsrki** [comment]
Slider is still left without any theme coloring. I plan to add it later.

**Comment by WillianGruber** [comment]
OK, may I open an issue so we remember it for later?

**Comment by stsrki** [comment]
Sure
