### ISSUE TITLE
Feature request: Time Picker

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#365]
Is it possible to implement a Time Picker component?

**Comment by stsrki** [comment]
I think this should be done as an extension for Blazorise as there is no native support for time-picker in Bootstrap or Bulma, or any other supported css framework.

**Comment by WillianGruber** [comment]
Yes, that would be nice

**Comment by MarkStega** [comment]
It would be very nice if there was a combined date-time picker that prevented picking an illegal hour in the transition to daylight/summer time and resolved the overlapping hour in the transition back.

**Comment by WillianGruber** [comment]
Please check:
https://openui5.hana.ondemand.com/entity/sap.m.TimePicker/sample/sap.m.sample.TimePicker

and

https://openui5.hana.ondemand.com/entity/sap.m.DateTimePicker/sample/sap.m.sample.DateTimePicker
