### ISSUE TITLE
Feature request: Color Picker

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#366]
Is it possible to implement a Blazorise version of color picker?

**Comment by stsrki** [comment]
Currently I don't have plans for color picker. At least not in the near future.

**Comment by WillianGruber** [comment]
Just for reference, Syncfusion has a nice version of it.
(https://www.syncfusion.com/blazor-components/blazor-color-picker)
Please notify if I shouldn't mention that link here...

**Comment by stsrki** [comment]
Blazorise supports Bootstrap, Bulma, daemonite material(bootstrap) and eFrolic. Syncfusion is not one of them and since it's a proprietary framework I don't think I will support it.

**Comment by WillianGruber** [comment]
I wasn't thinking about "supporting Syncfusion", maybe I expressed myself bad. I mean to implement as an extension component, many frameworks have them (I mean outside of Blazor)

**Comment by stsrki** [comment]
It's doable. But since I'm still struggling with finding the time to finish v0.8.7 it will take some time to create some custom component that is fairly complex, like color picker.

If you have time to give it a try and contribute I will gladly help you in the process :)

**Comment by WillianGruber** [comment]
I look forward to Blazorise become the greatest Blazor framework out there.
I've been a self-taught SAP developer (ABAP/PO/WF) for many years, and I'm a senior at my field. But I started delving into other technologies only 3 months ago, so I am very new to this (even learned the basics of github about 2 months ago, C# 3 months ago, etc).
I think about collaborating to Blazorise but I'm not sure I'm able yet. Anyway, I'll try my best :)

**Comment by stsrki** [comment]
It's great that you're trying to learn new tech. I know it can be hard at first but in time everything will just click.
You can always start with some simple task and see how it goes.

**Comment by WillianGruber** [comment]
@stsrki  please check:
https://openui5.hana.ondemand.com/entity/sap.ui.unified.ColorPicker/sample/sap.ui.unified.sample.ColorPickerLarge

**Comment by stsrki** [comment]
I will for now create just a simple native color input. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

This is the last feature for **v0.9** so don't want to spend too much time. Basic API will be the same anyways so if needed I can customize color dialog later.

Is that ok @WillianGruber ?

**Comment by WillianGruber** [comment]
Sure @stsrki , no problem! Thanks a lot!
