### ISSUE TITLE
Feature request: File Upload Component

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#367]
Is it possible to implement a File upload component, with progress bar, drag and drop, etc?

**Comment by WillianGruber** [comment]
Just for reference, Syncfusion also has a nice version of it. (Delete this comment if not allowed)

**Comment by stsrki** [comment]
Currently I don't plan to add support for File upload component. If you wan't you can create one b yourself based on this https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

**Comment by iberisoft** [comment]
> Currently I don't plan to add support for File upload component. If you want you can create one by yourself based on this https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

Please note that this component tends to hang up after processing 20MB (server-based Blazor); it looks very disappointing: https://github.com/SteveSandersonMS/BlazorInputFile/issues/17

**Comment by iberisoft** [comment]
> Currently I don't plan to add support for File upload component. If you want you can create one by yourself based on this https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/
> 
> Please note that this component tends to hang up after processing 20MB (server-based Blazor); it looks very disappointing: SteveSandersonMS/BlazorInputFile#17

Not fixed in your version. :(

**Comment by stsrki** [comment]
@iberisoft I tested on files larger than 20 MB and it works. The work is based on Steves, not a direct copy :)

**Comment by iberisoft** [comment]
Good! Let me reproduce it then report exactly how to get it.
