### ISSUE TITLE
[Bug] Outlined Button Color after click

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#368]
**Describe the bug**
After clicking on an outlined button the text color changes to Daemonite defaults.

**To Reproduce**
1. Go to https://materialdemo.blazorise.com/tests/buttons, using a non-purple primary color on theme selector, and scroll to section "OUTLINE BUTTONS".
2. Click on button PRIMARY. After clicking, with the cursor hovering the button, the color is ok. Moving the cursor outside the boundaries of the button changes the colors to grey background and purple text.
3. Go to https://daemonite.github.io/material/docs/4.1/components/buttons/, section "Outline buttons".
4. Click on button PRIMARY. After moving the mouse away, the background and font colors are grey and purple too, but in this case the purple was the initial value of the text.

**Expected behavior**
On https://materialdemo.blazorise.com/tests/buttons, the color of the text after clicking and moving the cursor should be the color selected by the theme as primary.
This issue also happens with the secondary button.

**Screenshots**
![image](https://user-images.githubusercontent.com/56033692/69260373-86a63800-0b9e-11ea-8cb8-0f420d4d5f68.png)
![image](https://user-images.githubusercontent.com/56033692/69260402-94f45400-0b9e-11ea-8310-e5feb0468c00.png)

**Additional context**
As an addicional question, is it possible to change the grey background with the Theme component?

Thank you, and as always, great work!

**Comment by WillianGruber** [comment]
Probably related to https://github.com/stsrki/Blazorise/blob/9f13775a6472df2bd2a802fa91656f5b61275585/Tests/Blazorise.Demo.Material/wwwroot/css/material/material.css#L1070

**Comment by stsrki** [comment]
Thanks for very detailed report. I managed to reproduce the problem on my side. It will be fixed in b0.8.8.

**Comment by WillianGruber** [comment]
Nice!

About the grey background, did you change it to white (transparent)?
