### ISSUE TITLE
Snackbar documenation

### ISSUE THREAD

**Issue by NXTwoThou** [stsrki/Blazorise#372]
There's documentation for the other extensions except Snackbar.

**Comment by stsrki** [comment]
You're right. I will add it to the documentation. In the meantime if you need help to see the use case please look at the example in the [demo](https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Pages/Tests/ElementsPage.razor)

**Comment by NXTwoThou** [comment]
That's where I've been poking through.  About to start digging through the code looking for display duration and any other possible properties.
