### ISSUE TITLE
Column widths are ignored when using Material

### ISSUE THREAD

**Issue by gallwood** [stsrki/Blazorise#374]
**Describe the bug**
When using Material, the normal column sizes used for layout are ignored. They work ok in other frameworks.

**To Reproduce**
If I have two columns, one with a size of is10, I expect to see a wide column and a narrow column. The demo pages show this
https://materialdemo.blazorise.com/tests/layout

**Expected behavior**
If I have two columns, one with a size of is10, I expect to see a wide column and a narrow column.

If I switch to Bootstrap, I see the expected behaviour.

**Comment by gallwood** [comment]
There is a slight difference in the css!. Looking at a column with a width of Is2, it generates in Bootstrap and Material this `<div class="col col-2">`. If I examine using the dev tools the css for Bootstap equate to

![image](https://user-images.githubusercontent.com/6881336/69407173-cfbfce80-0cfb-11ea-959f-11bfd9b0eaba.png)

but Material it's

![image](https://user-images.githubusercontent.com/6881336/69407249-fc73e600-0cfb-11ea-9015-88eb35fdcd02.png)

The 100% width seems to be overriding the col-2 width in this case.

Sorry, not a css expert. Don't know if this helps.

**Comment by gallwood** [comment]
Ok, so I can see now, its the order in which the two styles have been defined. Don't know how to fix this though.

**Comment by stsrki** [comment]
It seems material is not working when there is `col` class defined on column element along.

**Not working:**
```html
<div class="col col-10"></div>
```

If I remove `col` and leave just the `col-10` it will work

```html
<div class="col-10"></div>
```

I think the main reason for this behavior is because material is using older version of bootstrap and I guess this was fixed later.

**Comment by stsrki** [comment]
I can go and remove the `col` class for material provider but I think the best way is to upgrade it to latest version of bootstrap. There is already some progress but I'm not sure how far they got: [see here](https://github.com/Daemonite/material/issues/197)

**Comment by gallwood** [comment]
Thanks @stsrki . I think you're right. The best way is for Deamonite to upgrade to later version of Bootstrap. I might switch to Bootstrap for now whilst in Dev.

Out of interest, does Blazorise need these underlying providers, could it go straight to the Material CSS?

**Comment by stsrki** [comment]
The whole idea of Blazorise it to not bound itself to any specific framework but to be abstract enough so it can support any one of them. While for example [MatBlazor](https://github.com/SamProf/MatBlazor) and [BlazorStrap](https://github.com/chanan/BlazorStrap) are strictly following their own frameworks I don't see a reason to go the same way.

**Comment by stsrki** [comment]
The best option is to upgrade to latest version done by https://github.com/djibe/material
