### ISSUE TITLE
Blazorise Time picker

### ISSUE THREAD

**Issue by emiliojoseav** [stsrki/Blazorise#375]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I am trying to do [...] but [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by emiliojoseav** [comment]
Hi, how are you doing!
In a development that we are doing on my business, we are using the "Date" component, that is wonderfull. But we will really pleased if we could use also a Blazorise "Time" component, just for picking the time.

It is any way to do it with Blazorise, or are you planing a future implementation?

Even better, a componente with both "Date + Time".

Best regards.
Emilio.

**Comment by stsrki** [comment]
It's definitely on the road-map. As soon I finish current release I will consider it. I think I can do the `<TimeEdit>` component for only the times and maybe also to expand `<DateEdit>` with time part. That way I think every scenario will be covered.

**Comment by stsrki** [comment]
TimeEdit already done
