### ISSUE TITLE
Please upate SideBar Dodcs

### ISSUE THREAD

**Issue by Bitobux** [stsrki/Blazorise#377]
In the SideBar documentation (https://blazorise.com/docs/extensions/sidebar/)
is missing one step in the istallation description:

After:

**Imports**
In your main Imports.razor add:

`@using Blazorise.Sidebar`

Please add something like:

**You must set the path for static file** 
` <link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />`

**Comment by stsrki** [comment]
Fixed, thanks for posting!
