### ISSUE TITLE
Material with Razor Components

### ISSUE THREAD

**Issue by jonmiller1** [stsrki/Blazorise#38]
I'm trying to use the new preview with Razor components with VS 2019 Preview + ASP.net 3.0 Preview.  I followed the instructions to install the Blazorise.Material nuget packages, index.htm css and js changes, and registrations.  I can add components to the default application and don't get any errors.  However, I don't get any styling of any kind.  Can someone give me a sample solution or step-by-step of getting Material working starting from a new Razor Components app?  It looks like I'm missing something.  I've tried adding references to the Material css and Material js files without any changes.

**Comment by stsrki** [comment]
I'm not sure it will work with Razor components. There are some issues with content files(css and js) in the RC preview2. That's why I have updated Blazorise for Blazor 0.8 instead of Razor Components. Until they fix that, it's best for you to try to create project for Blazor 0.8.

**Comment by stsrki** [comment]
Hi, I have just saw that I have forgot to include description on how to download and add css and js files for material framework. Please check the [documentation](https://blazorise.com/docs/usage/material/#download-css) for updated usage.

**Comment by jonmiller1** [comment]
So is it closed because it works now or are you still waiting on for the new .NET Core 3 preview?   If it is working can you post a sample application using razor components that works with material?

**Comment by stsrki** [comment]
Still waiting for the ,Net Core 3. As I mentioned before, content files are not working in Razor Components. That's basically the only thing that is missing and the main reason why Blazorise will not work. You should instead try the latest Blazor 0.8-preview as it's using the Razor Components anyways and content files are working without any problem.

**Comment by stsrki** [comment]
I have stumbled upon the library that can handle static files for Razor Component projects. I have tried it and it seems it works. Please give it a try and let me know how it goes

https://github.com/SQL-MisterMagoo/BlazorEmbedLibrary

**Comment by stsrki** [comment]
@jonmiller1 Just released the latest version that now works with Razor Components. For instructions on how to use it please look at the readme on docs.
