### ISSUE TITLE
[Question] Redirect to another page in Button

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#385]
Hello,
This is probably a dumb question, but with <SidebarLink To=""> and <BarLink To=""> we can redirect to other pages. How can I do it with the Button component?

**Comment by stsrki** [comment]
It's fairly easy. Just use a NavigationManager

**YourPage.razor**
```cshtml
@page "/page1"
@inject NavigationManager navigationManager;

<Button Color="Color.Primary" Clicked="@(()=>navigationManager.NavigateTo("some/page2"))">Click me</Button>
```
