### ISSUE TITLE
[Question] How to redirect to other page in Button component?

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#386]
Hi,
Probably a dumb question, but how to redirect to other page in Button component?

**Comment by stsrki** [comment]
Hi @WillianGruber 

I'm sorry but isn't this already answered in #385 ?

**Comment by WillianGruber** [comment]
Sorry, I thought I didn't post that issue (closed tab?) because I couldn't find it... and that was because it was already closed. You were too fast...

Thank you!
