### ISSUE TITLE
Datagrid: SelectedRowChanged not fired when Edit Button is pressed

### ISSUE THREAD

**Issue by bombel1959** [stsrki/Blazorise#387]
My Edit Command template looks like this:

```cshtml
<EditCommandTemplate>
    <Button Color="Color.Primary" Clicked="@context.Clicked">Edit</Button>
</EditCommandTemplate>
```

When clicking on the Button no SelectedRowChanged Event is fired!

Is this the correct behaviour or a bug?

**Comment by stsrki** [comment]
Hi, yes this is the expected behavior.
