### ISSUE TITLE
More of a personal request - Permission to Fork?

### ISSUE THREAD

**Issue by richbryant** [stsrki/Blazorise#392]
I'm currently breaking my brain trying to make ReactiveUI (you may know if it) work with Blazor.

One of my requirements is for components that expose an ICommand property (or rather a ReactiveCommand but you get the idea) and well, rather than reinvent the wheel, I'd like permission to fork your work and amend the components.

Thanks!

**Comment by stsrki** [comment]
Yeah, I think you can safely fork the project and and the changes. I would just want you to keep the note somewhere about the original repository and author.

**Comment by richbryant** [comment]
Of course.  Very prominently.

And thank you very much, you've saved me weeks of work.
