### ISSUE TITLE
Feature request: Custom filtering for DataGrid

### ISSUE THREAD

**Issue by paiden** [stsrki/Blazorise#394]
**Is your feature request related to a problem? Please describe.**
The current filter operates on a per field basis as far as I can tell and only supports the given filter methods. I'd like to see a API to allow setting custom filters for a row to e.g. allow deep filtering etc.

**Describe the solution you'd like**
```xml
<TextBox @bind-Text="@this.ItemText" />
<DataGrid TItem="DataItem" CustomFilter="@this.ItemFilter"... />
```

```csharp
string ItemText {get;set;}
static bool ItemFilter(DataItem item) 
   => item.Name.Equals(this.ItemText) || item.Description.Contains(this.ItemText);
```

Ideally there also is some way to trigger the filter when needed, e.g.
 
- Filter gets upated when text of the above binding changes
- Filter can be triggered via another button in the UI etc.

I have no idea if and how this can be implemented in Blazor in a performant way, I'm not experienced enough with this tech yet, but I hope you get the idea I'm outlining here. Maybe there is a much better way to implement custom filtering with Blazor.

BTW: Thank you very much for this awesome project, It saves me a lot of time for one of my hobby projects.

**Comment by stsrki** [comment]
Hi @paiden 

This is a good idea and I think it shouldn't be a problem to implement. Going on the list!

**Comment by stsrki** [comment]
PS. I would really like to know how people are using Blazorise so if you have your project somewhere I would like to have a look :)

**Comment by paiden** [comment]
> PS. I would really like to know how people are using Blazorise so if you have your project somewhere I would like to have a look :)

It's a little too early to show this to someone else than myself. But once it is in a state I'm OK with showing to others, I hopefully will remember to give you and update so you can take a look.
