### ISSUE TITLE
Autocomplete no longer works in 0.8.7

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#395]
Autocomplete no longer works in 0.8.7. It only accepts the first letter.

The Blazorise demo site can be used to demonstrate the issue:

[https://bootstrapdemo.blazorise.com/tests/components](https://bootstrapdemo.blazorise.com/tests/components)

Press A, you get countries starting with A. But pressing N does not filter to "Andorra" but brings up countries starting with N.

**Comment by stsrki** [comment]
I can confirm the bug on my side. I will try to see what can be done and release a quick fix.

tnx

**Comment by stsrki** [comment]
Fixed #396
