### ISSUE TITLE
Question: Where did you get material.css and material.min.css in the material example?

### ISSUE THREAD

**Issue by DerekChasse** [stsrki/Blazorise#40]
I am leveraging libman to handle client side references in my blazor app and I would like to leverage cdnjs and/or unpkg to reference the material styling.

Could you please tell me where you pulled these files from?

**Comment by stsrki** [comment]
They can be downloaded from [daemonite](http://daemonite.github.io/material/)

**Comment by DerekChasse** [comment]
Thanks!
