### ISSUE TITLE
No download link for static files

### ISSUE THREAD

**Issue by mobinseven** [stsrki/Blazorise#402]
Where should I find these static files?
```
blazorise.css
blazorise.js
```

**Comment by stsrki** [comment]
You don't need to download them as they're part of the assembly(.dll) files when you get them from nuget. To use them you only need to define them as sources in your `index.html` or `_Host.cshtml`.

```
<script src="_content/Blazorise/blazorise.js"></script>
<script src="_content/Blazorise.Bootstrap/blazorise.bootstrap.js"></script>
```

Then the Blazor will do the its's magic and make it work.

**Comment by mobinseven** [comment]
I did (index.html in my case) and I'm getting this:
`
Failed to load resource: the server responded with a status of 404 (Not Found)
`

**Comment by stsrki** [comment]
It's hard to find the reason for error without any context. Can you create a test repository of your project so I can take a look?

**Comment by mobinseven** [comment]
I forked this project and trying Blazorise in it:
[https://github.com/enkodellc/blazorboilerplate](url)

**Comment by mobinseven** [comment]
I have to mention that using DevTools I can see that "blazorise.css" is generated - it is an empty file though. but still browser signals the 404 error.

**Comment by stsrki** [comment]
I will test it tonight. But I must warn you, blazorboilerplate is created with MatBlazor so I don't think it will work as you expected. Unless you remove all MatBlazor components and replace them with Blazorise.

**Comment by stsrki** [comment]
So, I tried blazorboilerplate and I also got 404 after I followed all the steps required when installing Blazorise. But I made it work after I uncommented `app.UseStaticFiles();` found in **Startup.cs** in `BlazorBoilerplate.Server`

```cs
app.UseStaticFiles(); // uncomment this line
app.UseClientSideBlazorFiles<Client.Startup>();
```
