### ISSUE TITLE
Limiting the height of a Modal, by percentage

### ISSUE THREAD

**Issue by gallwood** [stsrki/Blazorise#409]
**Describe the solution you'd like**
I'd like to restruct the size of a Modal to no more than a percentage of the screen height. For example, If I display a table with 30 rows in, I don't want to see scrollbars on the page, I would rather scroll the Modal.

### Additional context
I see there is a MaxHeight on the ModalBody, but I don't know the size of the ViewPort so don't want to use a fix value..

**Comment by stsrki** [comment]
Can you give me more information. Using the `MaxHeight` is exactly for this scenarios. If the content is too big it will show scrollbars.

**Comment by gallwood** [comment]
Thanks for the reply. I wasn’t sure if this max height could cope with a responsive layout.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stsrki** [comment]
Please try it and let me know. I'm not expert in front-end but I think it should work.
