### ISSUE TITLE
How to use api in Autocomplete

### ISSUE THREAD

**Issue by ioer2008** [stsrki/Blazorise#410]
I want to use the ajax method in select2 to call the api, how can I do this?

**Comment by stsrki** [comment]
Hi @ioer2008 

It's currently not possible with Autocomplete.

**Comment by stsrki** [comment]
Closing since I have no plans to incorporate select2 into Autocomplete. If I would, it would probably be completely new component.

**Comment by omer-repo** [comment]
Is there any news about ajax style Autocomplete? I don't want to load all data onLoad, but instead it should be fetch data on typing. Is there any way to do this?

**Comment by stsrki** [comment]
@David-Moreira I believe we already support this, right?

**Comment by omer-repo** [comment]
I used https://github.com/Blazored/Typeahead. I hope there is similar in Blazorise also
