### ISSUE TITLE
[Bug] Error when using SelectEdit with dictionary in DataGrid

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#412]
**Describe the bug**
Null Exception:
![image](https://user-images.githubusercontent.com/56033692/70174482-c3e8ea80-16b3-11ea-8083-7a93f27a65f7.png)

**To Reproduce**
1. Create a page with the following code in a datagrid:
```html
...
<DataGridSelectColumn TItem="Abc" Field="@nameof( Abc.ExampleField )" Caption="ExF" Editable="true">
   <EditTemplate>
        <SelectEdit TValue="string" SelectedValue="@((string)( ( (CellEditContext)context ).CellValue ))" SelectedValueChanged="@(( v ) => ( (CellEditContext)context ).CellValue = v)">
            <SelectItem TValue="string" Value="null"></SelectItem>
            @foreach (KeyValuePair<string, string> line in Lines)
            {
                <SelectItem TValue="string" Value="line.Key">@line.Value</SelectItem>
            }
        </SelectEdit>
    </EditTemplate>
</DataGridSelectColumn>
...
```
Lines is a dummy filled dictionary<string,string>
2. Open the app, go to the page.
3. Click New to create a new line.
4. Cancel.
5. See console log in browser for error.

**Expected behavior**
Cancelling should just go back to previous status.

**Additional context**
Removing `<SelectItem TValue="string" Value="null"></SelectItem>` changes nothing. It is not related.

**Comment by stsrki** [comment]
Cannot reproduce the error. I have copied the code as you have. Created dummy dictionary with few items. Everything works as expected, I can create, edit and cancel without any issue.
