### ISSUE TITLE
Button colors

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#413]
Hi,
Couple of aesthetic points:

- Is there a way to change the font color of the success and info buttons to white? It is not very convenient as black.

- The blue info background color is strange, could it be as daemonite?

- Is it possible to change the color of the warning button (font and background) aswell?

![image](https://user-images.githubusercontent.com/56033692/70175255-2393c580-16b5-11ea-8222-512f479d01d0.png)

Daemonite:
![image](https://user-images.githubusercontent.com/56033692/70176244-eaf4eb80-16b6-11ea-92e7-32495b0305d8.png)

I think that makes the buttons more homogeneous. If that is not for your liking, I would probably change it in my app, although it would be nice as standard Blazorise. Maybe change together with #368? 

Thank you!

**Comment by stsrki** [comment]
The colors are calculated by the `ThemeGenerator` and it's following a Bootstrap rules for font colors based on the background colors. The same rules are used for material provider. But maybe the contrast threshold should be a little easier for material.

**Comment by stsrki** [comment]
I think this line can be modified or maybe better to have it customized through theme options:

```
if ( luminance > 0.5 )
    d = 0; // bright colors - black font
else
    d = 255; // dark colors - white font
```

**Comment by WillianGruber** [comment]
So, you mean it is possible to achieve the daemonite colors with ThemeGenerator?

Sorry, I couldn't understand the luminance. Where is this line? Will you include in Themes?

**Comment by stsrki** [comment]
Just need to play a little with `ThemeGenerator` so, yeah, it is possible.

Here is the line/method: https://github.com/stsrki/Blazorise/blob/ccd671b5925ca7797c0d3b34c353ca34e337e9eb/Source/Blazorise/ThemeGenerator.cs#L405

**Comment by stsrki** [comment]
Linked to #369
