### ISSUE TITLE
Filter position in DataGrid

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#416]
**Describe the solution you'd like**
Is it possible to merge the sort and filter lines? Maybe an option in `<DataGrid>` component?
This is how I am using the component now (not finished, using datagrid for the first time):
![image](https://user-images.githubusercontent.com/56033692/70179805-85f0c400-16bd-11ea-8ebe-6e7925faf943.png)

I think there is too much wasted space in the filter line and would like to merge this way:
![image](https://user-images.githubusercontent.com/56033692/70179958-cbad8c80-16bd-11ea-8dc8-fa8aa164e4ba.png)
(made with mspaint, not really alligned...)

Also, I think it is not user-friendly/counter-intuitive that when clicking in the "New" button, that is located **above the filter**:
![image](https://user-images.githubusercontent.com/56033692/70180156-3b237c00-16be-11ea-895f-2bda67645535.png)
The new blank line to add new data appears **under the filter**:
![image](https://user-images.githubusercontent.com/56033692/70180284-73c35580-16be-11ea-893c-63c4357eab9f.png)

I would like to display it this way:
![image](https://user-images.githubusercontent.com/56033692/70180517-f3512480-16be-11ea-830c-4a45ee9cf257.png)
(mspaint...)

Is possible to achieve this with configuration? If not, would you consider looking at it after 0.8.8 (with #393)?

**Comment by stsrki** [comment]
It's really hard to handle all possible scenarios regarding the UI. There can be a zillion different styles and rules. I tried to find out how other people have designed their sorting/filtering for data grid and this is the standard way of doing it.

So, I'm not sure. I can give it a try sometimes in the future. For now, it's going to be as it is until I had some more time to figure it.

**Comment by WillianGruber** [comment]
Sure, thank you very much!

**Comment by WillianGruber** [comment]
Just FYI, I'm developing a rather large app with Blazorise, and for now I have lots of things to do...
When the time comes to polish it before going live, I'll try to grab some issues and help fixing :)

**Comment by stsrki** [comment]
Any help is appreciated :)
