### ISSUE TITLE
Modal not displayed above some other Blazorize components

### ISSUE THREAD

**Issue by intiharj** [stsrki/Blazorise#417]
Example source code attached.  Click the Test Modal button while the Index.razor component page is visible.  You may need to resize the browser to see the problem.  I can see the problem using Chrome or Firefox, but it works properly when using Edge.

![image](https://user-images.githubusercontent.com/6271320/70186708-876cbd00-16ba-11ea-9d32-48d413cde628.png)
[BlazorApp12.zip](https://github.com/stsrki/Blazorise/files/3924207/BlazorApp12.zip)

**Comment by stsrki** [comment]
The problem is somewhere in `site.css`. It messes too much with bootstrap classes. It's good for Blazor demo apps but as soon you try to create anything you will have problems. I tend to remove it for every Blazor project when I create it.

**Comment by intiharj** [comment]
Confirmed.  I'm still using the default nav bar that comes with the Blazor Server project template in visual studio.  If I comment out  **position: sticky;** in .sidebar, the app behaves as expected in Chrome, Firefox, and Edge.  Also, I have not been able to discover any side-effects to the menu function after making this change.  Thank you.

```
@media (min-width: 768px) {
    app {
        flex-direction: row;
    }

    .sidebar {
        width: 250px;
        height: 100vh;
        /*position: sticky;*/
        top: 0;
    }...
```
