### ISSUE TITLE
Chart Line Graph - can it display time series data ?

### ISSUE THREAD

**Issue by intech-paul** [stsrki/Blazorise#418]
I have  a blazorise project with a chart on it. I have run the demo ok.
I have changed to use a custom class and set TItem to suit, but the chart control does not seem to pick up any data.

The chart displays an empty grid, with a scale that goes from -1.0 to +1.0

Relevant code:

```cs
<LineChart @ref="lineChart" TItem="MyData" />

@code{
    async Task HandleRedraw()
    {

        lineChart.AddDataSet( GetLineChartDataset());

        string[] str = new string[mydata.Count];

        for (int i = 0; i < mydata.Count; i++)
            str[i] = (i+1).ToString();

        lineChart.AddLabel(str);

        await lineChart.Update();
    }

    List<MyData> mydata;

    LineChartDataset<MyData> GetLineChartDataset()
    {
        mydata = GetMyData();

        return new LineChartDataset<MyData>
        {
            Label = "Line 1 South Probe " + mydata.Count.ToString() + " Items",
            Data = mydata,
            ShowLine=true,
            BackgroundColor = backgroundColors,
            BorderColor = borderColors,
            Fill = false,
            PointRadius = 2,
            BorderDash = new List<int> { }
        };
    }

    List<MyData> GetMyData()
    {
        List<MyData> mydata = new List<MyData>();
        DateTime now = DateTime.Now;
        var r = new Random();

        mydata.Add(new MyData((double)50));
        for (int i=0;i<3;i++)
        {
            now.AddMinutes(-5);
            mydata.Add(new MyData((double)(40+r.Next(0,20))));
        }

        mydata[0].value = 20;


        return mydata;
    }


    class MyData
    {
        public MyData(double v1)
        {
            value = v1;
        }
        public double value;
    }

}
```

PS:
I had a  DateTime in MyData, but stripped it out to test the class was getting to the chart ok.
Rest of the code is per sample chart.

time series data looks like this:

```cs
List of items:
{
DateTime
linevalues[n]
}
```

n= number of lines.

Thanks & Regards
Paul

**Comment by stsrki** [comment]
Hi @intech-paul 

The problem is your `MyData`. It cannot be used for data point. You have to use simple types like `int`, `double`, `decimal`, etc.

Just remove `MyData` class and use `double` instead for your data. Please let me know.

**Comment by intech-paul** [comment]
Hello

Thankyou, can the built in .net data types be used to load several chart traces at the same time for example multiple data point values for the same point in time ?

Perhaps a documentation update that TItem can only be used for standard .net data types ?

Regards
Paul

**Comment by stsrki** [comment]
I'm not sure what you mean by _several chart traces at the same time_. Can you give me an example?

**Comment by intech-paul** [comment]
Hello

Yes an example:

[cid:image001.png@01D5AB83.82B0ADA0]

We have a trace of two temperatures over time.

Regards
Paul

**Comment by stsrki** [comment]
Hi @intech-paul 

Image link is not valid.

**Comment by intech-paul** [comment]
![line graph](https://user-images.githubusercontent.com/56703036/70269093-95c7ef80-1806-11ea-80b7-ba44f5e301ee.png)

**Comment by stsrki** [comment]
Yes, that is possible with chartjs. You can use `lineChart.AddDataSet(/*some data*/);` method, where every dataset will be a separate line.

**Comment by intech-paul** [comment]
![line graph test](https://user-images.githubusercontent.com/56703036/70273243-95cbed80-180e-11ea-8787-02ef8a2c78c9.png)

Line Graph working, thank you.

**Comment by stsrki** [comment]
Glad I could help :+1:

**Comment by Flearz** [comment]
Hello, sorry to re-open this, and to bother you for a lot of things, but when i add a Dataset, colors doesn't change like his line graph, all my lines are red. Do you know why ? Here is my code:
` protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        values = new List<double>();
        if (firstRender)
        {

            await HandleRedraw();
        }
        while (true)
        {

            response = await Http.GetJsonAsync<WoopsaObject>("http://localhost:80/woopsa/read/Signal");
            currentValue = response.Value;
            values.Add(currentValue);
            if (values.Count > 100)
            {
                values.RemoveAt(0);
            }
            await HandleRedraw();
            await Task.Delay(100);
        }
    }

    async Task HandleRedraw()
    {
        lineChart.Clear();
        if (test)
            lineChart.OptionsJsonString = "{\"animation\": {\"duration\": 0}}"; //Disable animation
        else
            lineChart.OptionsJsonString = "{\"animation\": {\"duration\": 0}}"; //Disable animation
        test = !test;


        lineChart.AddLabel( Labels );

        lineChart.AddDataSet( GetLineChartDataset() );
        lineChart.AddDataSet(GetLineChartDataset2());



        await lineChart.Update();
    }

    LineChartDataset<double> GetLineChartDataset()
    {
        return new LineChartDataset<double>
        {
            Label = "# of randoms",
            Data = values,
            BackgroundColor = backgroundColors,
            BorderColor = borderColors,
            Fill = false,
            PointRadius = 2,

            //BorderDash = new List<int> { }

        };
    }
    LineChartDataset<double> GetLineChartDataset2()
    {
        return new LineChartDataset<double>
        {
            Label = "# of randoms",
            Data = values.Select(value => value/2).ToList(),
            BackgroundColor = backgroundColors,
            BorderColor = borderColors,
            Fill = false,
            PointRadius = 2,

            //BorderDash = new List<int> { }

        };
    }`

**Comment by stsrki** [comment]
@Flearz I guess it's because you're setting the same color on both of your data-sets:
eg
`BackgroundColor = backgroundColors,`

**Comment by Flearz** [comment]
Thanks for you fast answer, yeah I know, but this is an array of colors (string), isn't it supposed to take the first one for the first dataset, the second for the second, and so on ? When I use the array with PointBorderColor, this is what happen, each point is a different color.

I also tried to do something like this 
`List<List<string>> backgroundColors = new List<List<string>>  {{new List<string> ChartColor.FromRgba(255, 99, 132, 0.2f)}, {new List<string> ChartColor.FromRgba(54, 162, 235, 0.2f)}}`
and select backgroundColors[0] for the first dataset and backgroundColors[1] for the second but it's the same problem, the two lines are the same color (the last one setted). 

What do you think ?

**Comment by stsrki** [comment]
I tried it now. You actually need to define `BorderColor`, but like i said before they must be the different colors array.

```diff
LineChartDataset<double> GetLineChartDataset()
{
    return new LineChartDataset<double>
    {
        Label = "# of randoms",
        Data = values,
        BackgroundColor = backgroundColors,
        BorderColor = borderColors,
        Fill = false,
        PointRadius = 2,

        //BorderDash = new List<int> { }

    };
}
LineChartDataset<double> GetLineChartDataset2()
{
    return new LineChartDataset<double>
    {
        Label = "# of randoms",
        Data = values.Select(value => value / 2).ToList(),
        BackgroundColor = backgroundColors,
-        BorderColor = borderColors,
+        BorderColor = borderColors2,
        Fill = false,
        PointRadius = 2,

        //BorderDash = new List<int> { }

    };
}
```

**Comment by Flearz** [comment]
Yeah, I did that like this, but it just change both lines to the new color... 
`        List<List<string>> borderColors1 = new List<List<string>> {  new List<string> { ChartColor.FromRgba(255, 99, 132, 0.2f) },  new List<string> { ChartColor.FromRgba(54, 162, 235, 0.2f) } } ;
 foreach (List<TraceValue> data in LiveTuningContainerTrace.Datas.Values)
                { 
                    LineChartDataset<double> dataset = new LineChartDataset<double>
                    {
                        Label = "",
                        Data = data.Select(value => value.Value).ToList(),
                        BackgroundColor = backgroundColors,
                        BorderColor = borderColors1[LiveTuningContainerTrace.Datas.Count-1],
                        Fill = false,
                        PointRadius = 0,

                        //BorderDash = new List<int> { }

                    }; 

                  lineChart.AddDataSet(dataset);
                
                }
`
With the first dataset, BorderColor will be bordercolors[0] and the second dataset it will be bordercolors[1] which are different (they are List<string> with only one color inside).
Result: [https://imagizer.imageshack.com/img924/7088/swHoKL.png](url)

**Comment by Flearz** [comment]
@intech-paul  Could you send me your piece of code as I can see how you got the two datasets in different colors ?
Thanks in advance

**Comment by intech-paul** [comment]
Hello Flearz

Here it is below, the only difference is I am changing both BorderColor and BackgroundColor.
and these are both separate List<string>. 

Paul

    LineChartDataset<double> GetLineChartDataset(int line)
    {
        mydata = GetMyData(line);

        return new LineChartDataset<double>
        {
            Label = "Line 1 South Probe " + mydata.Count.ToString() + " Items",
            Data = mydata,
            ShowLine=true,
            BackgroundColor = (line==0 ? backgroundColors : backgroundColors2),
            BorderColor = (line==0 ? borderColors : borderColors2),
            Fill = false,
            PointRadius = 2,
            BorderDash = new List<int> { }
        };
    }

    List<string> backgroundColors = new List<string> { ChartColor.FromRgba( 255, 99, 132, 0.2f ), ChartColor.FromRgba( 54, 162, 235, 0.2f ), ChartColor.FromRgba( 255, 206, 86, 0.2f ), ChartColor.FromRgba( 75, 192, 192, 0.2f ), ChartColor.FromRgba( 153, 102, 255, 0.2f ), ChartColor.FromRgba( 255, 159, 64, 0.2f ) };
    List<string> borderColors = new List<string> { ChartColor.FromRgba( 255, 99, 132, 1f ), ChartColor.FromRgba( 54, 162, 235, 1f ), ChartColor.FromRgba( 255, 206, 86, 1f ), ChartColor.FromRgba( 75, 192, 192, 1f ), ChartColor.FromRgba( 153, 102, 255, 1f ), ChartColor.FromRgba( 255, 159, 64, 1f ) };
    List<string> backgroundColors2 = new List<string> { ChartColor.FromRgba( 54, 162, 235, 0.2f ), ChartColor.FromRgba( 255, 206, 86, 0.2f ), ChartColor.FromRgba( 75, 192, 192, 0.2f ), ChartColor.FromRgba( 153, 102, 255, 0.2f ), ChartColor.FromRgba( 255, 159, 64, 0.2f ) };
    List<string> borderColors2 = new List<string> { ChartColor.FromRgba( 54, 162, 235, 1f ), ChartColor.FromRgba( 255, 206, 86, 1f ), ChartColor.FromRgba( 75, 192, 192, 1f ), ChartColor.FromRgba( 153, 102, 255, 1f ), ChartColor.FromRgba( 255, 159, 64, 1f ) };

**Comment by Flearz** [comment]
Ok I understood what I was doing wrong. Many thanks to you two. The fault was mine by using the count of the list, when the dataset are created , the count is the same for both datas! 
A nice day to you

**Comment by Krumelur** [comment]
@stsrki Is there any documentation how colors for LineChart are supposed to work? Whatever colors I set, the result is either totally random or all gray :-)

I'd like to know what the properties `BackgroundColor`, `BorderColor` and `PointBorderColor` are used for and what values are expected (single, array...?).
