### ISSUE TITLE
Tabs documentation doesn't match Tabs Demo (documentation solution doesn't work)

### ISSUE THREAD

**Issue by shadowbane1000** [stsrki/Blazorise#424]
The documentation for Tabs simply states that they need matching Name properties between \<Tab\> and \<TabContent\>.  However, the demo has (and usage requires) a handler for Tabs.OnSelectedTabChanged, as well as code behind Tab.IsActive, TabContent.IsActive, and a ref to \<TabsContent\>.  

One way or another, these should be reconciled. (Preferably with the simpler case) :)

**Comment by stsrki** [comment]
Part of the same refactoring as #521

**Comment by stsrki** [comment]
Done as part of #528
