### ISSUE TITLE
Demo code/test code does not match Demo site. 

### ISSUE THREAD

**Issue by taylorjimbo** [stsrki/Blazorise#426]
The code file for the DataGrid.razor 

/Blazorise/Tests/Blazorise.Demo/Pages/Tests/DataGridPage.razor

Does not match what is displayed on https://bootstrapdemo.blazorise.com/

The sort icons ascending and descending are not showing. I set ShowCaptions = "true" and Sortable = true" for the grid and all columns, but still don't get icons. So I referenced the Demo/Test code and it also does not show the sort icons.

**Comment by stsrki** [comment]
Did you include FontAwesome or Material icons pack into your project?

**Comment by taylorjimbo** [comment]
FontAwesome.

**Comment by taylorjimbo** [comment]
Here is my Startup.cs... Did I miss something? It's based off the Test/Demo stored on GitHub, which also does not show the ascending and descending icons. 

`;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSignalR();
            services.AddScoped<HttpClient>();
            services.AddSingleton<HeartBeatService>();
            services.AddSingleton<CardDataService>();
            services.AddBlazoredLocalisation(); // This adds the IBrowserDateTimeProvider to the DI container
            services
                    .AddBlazorise(options =>
                    {
                        options.ChangeTextOnKeyPress = true; // optional
                    })
                    .AddBootstrapProviders()
                    .AddFontAwesomeIcons();
                    }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            // Blazorize
            app.ApplicationServices
                .UseBootstrapProviders()
                .UseFontAwesomeIcons();

            //app.UseBlazoredLocalisation(); // This adds the middleware to setup the correct Culture Info based on the users browser.

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });


        }
    }

**Comment by taylorjimbo** [comment]
Found the issue... I changed to Material icons and everything worked, so changing back to font awesome I noticed that the style sheet was not loading in the _Host.cshtml file. 

Thanks for the guidance!
