### ISSUE TITLE
Modal Footer Buttons do not follow theme

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#430]
**Describe the bug**
The buttons in modal footer do not follow the theme. Is this a bug? Or intentional?
![image](https://user-images.githubusercontent.com/56033692/70369645-8fd01e00-189b-11ea-97ec-ba05c9f5cf37.png)
I checked Themes but the modal part only refs border radius.

**To Reproduce**
1. Go to https://materialdemo.blazorise.com/tests/modals
2. Click on STANDARD MODAL
3. See button theme

**Expected behavior**
Buttons with same theme as buttons in the page body

**Comment by stsrki** [comment]
Could be some special css rule for buttons in modal dialog that I didnt see. I will check it after I get home.

**Comment by stsrki** [comment]
I completely forgot about this. Sorry about that. Anyways it really seems there are some special rules for button inside of modal footer. Gonna fix that.

**Comment by WillianGruber** [comment]
I confirm it is fixed in 0.91. Thank you!

**Comment by bourne17** [comment]
I have the same issue in 1.3.1, how can I fixed ? 

![Screenshot 2023-08-21 192943](https://github.com/Megabit/Blazorise/assets/17529815/944e4114-ec45-4a66-a198-dc61095054e0)

**Comment by stsrki** [comment]
Did you maybe accidentally leave `bootstrap.css` link in your `_Layout.cshtml` or `index.html`? @bourne17
