### ISSUE TITLE
[Question]SelectedRow not updated

### ISSUE THREAD

**Issue by jeroenmolenkamp** [stsrki/Blazorise#434]
I'am using a custom EditCommandTemplate with a custom function like so: 

     

```
    <DataGrid TItem="ProductViewModel"
              Data="@products"
              @bind-SelectedRow="@selectedProduct"
              Sortable="true"
              Filterable="true"
              ShowPager="true"
              PageSize="10"
              CurrentPage="1"
              Editable="true"
              UseInternalEditing="false">

        <DataGridCommandColumn TItem="ProductViewModel">
            <NewCommandTemplate>
                <Button Color="Color.Success" Clicked="ToCreateProduct">New</Button>
            </NewCommandTemplate>
            <EditCommandTemplate>
                <Button Color="Color.Primary" Clicked="@ToUpdateProduct">Update Product</Button>
            </EditCommandTemplate>
        </DataGridCommandColumn>
```

I expected that when I pressed the custom Edit button the SelectedRow would be updated. But Right now the Selected row isn't updated(or set). To give a little bit of context after I press the edit button it should redirect to a other page. 

So how do I send a parameter to this function? Or update the selectedRow without pressing the line first. Or should this happen?

**Comment by stsrki** [comment]
Selecting the row by clicking the Edit button is not supported scenario.

If you wan't to navigate to another page in your `ToUpdateProduct` you can use `NavigationManager`:

```
void ToUpdateProduct()
{
    NavigationManager.NavigateTo( "your/page" );
}

[Inject] private NavigationManager NavigationManager { get; set; }
```

**Comment by jeroenmolenkamp** [comment]
Hi Yeah I know how to navigate. I Wanted to pass the id( on my viewmodel) in to the navigate. I worked around it by setting Editable="false" and creating a extra Column: 

```
  <DataGridColumn TItem="ProductViewModel" Field="@nameof(ProductViewModel.Name)" Caption="Actie" Editable="false" Sortable="false" Filterable="false">
            <DisplayTemplate>
                @{
                    var id = (context as ProductViewModel).Id;
                    <button class="btn btn-primary" @onclick="(()=> ToUpdateProduct(id))">Edit</button>
                }           
            </DisplayTemplate>
        </DataGridColumn>

```
This works, thanks for your fast reply

**Comment by stsrki** [comment]
Well, `EditCommandTemplate` has a `CommandContext<TItem>` as a context so you can also get the product id that way.

```cshtml
<EditCommandTemplate>
    <Button Color="Color.Primary" Clicked="@(()=>YourMethod(context.Item.Id))">Edit</Button>
</EditCommandTemplate>
```

**Comment by jeroenmolenkamp** [comment]
That worked! I couldn't figure out how to access the context in that scenario. And casting it didn't work.
Thanks !

**Comment by stsrki** [comment]
Yeah, the intellisense in VS is not that great so unless you know exactly what to start typing it will give you only the default options.
