### ISSUE TITLE
Autocomplete  show textvalue after selectchange

### ISSUE THREAD

**Issue by Saeidasadi32** [stsrki/Blazorise#437]
Hi
how do show full textvalue after search compatible inside Autocomplete component

**Comment by stsrki** [comment]
@Saeidasadi32 Can you please explain a little more of what you're trying to accomplish? tnx

**Comment by Saeidasadi32** [comment]
when I writing part of text and find in autocomplete full text, I need to show the selected text in autocomplete textbox.
at now this component just show the part of text.
your demo show text in another field but I need show inside autocomplete

**Comment by stsrki** [comment]
I'm still not sure if I understood it correctly. The text is populated after the searched item is selected

**1, Start typing:**

![image](https://user-images.githubusercontent.com/900302/70699861-120c7800-1cca-11ea-8454-a6c551f4bd9f.png)

**2, After selecting one of the items:**

![image](https://user-images.githubusercontent.com/900302/70699902-26e90b80-1cca-11ea-8ffd-0e1bccb4050c.png)

Maybe you can show me an example from some other autocomplete that has the feature you want?

**Comment by Saeidasadi32** [comment]
when TextField and ValueField have same Item, It's OK. like this code
TextField="@((item)=>item.CNamad)"
ValueField="@((item)=>item.CNamad)"
but when use defernet Item It's Not OK like this code
TextField="@((item)=>item.CNamad)"
ValueField="@((item)=>item.CID)"

**Comment by JRC86** [comment]
My textfield is also cleared efter selecting an item in the list.

**Comment by stsrki** [comment]
I think this can be solved by introducing new `SelectedText` and `SelectedTextChanged` properties.

@JRC86 So, `SearchChanged `should not be called when the autocomplete is cleared?

**Comment by JRC86** [comment]
Well, searchchanged is passed CurrentText or something, which is set to null at an earlier time. I think that's the problem.

Whenever SelectionChanged is fired and a valid item is selected, I save it as SelectedItem.
I then set a bool to true and have the following code in Autocomplete-tag:
`SearchChanged="@((item) => OnInputChanged(item ?? ((ItemPicked)? SelectedItem.Text:item)))"`
I still want nulls to go through but not if it comes after a valid itemselection.

**Comment by bestpika** [comment]
Or can we reverse the process and have the drop-down options have more input filters?

**Comment by SuriyaArul** [comment]
Hi all,
Actually, I have one blocker, regarding Blazorise Autocomplete. I have done autocomplete field in my project, after that, I have updated the version of abp.io CLI. so the autocomplete SelectedValueChanged event was not working... previously object arguments were taken, but now it's showing (cannot convert EventCallBack to EventCallBack<System.Guid?>)... can anyone help out this issue...
![autocmpCsl](https://user-images.githubusercontent.com/68591063/106611943-8b31f300-658e-11eb-9205-7254bc314047.png)
![autocmpl](https://user-images.githubusercontent.com/68591063/106611985-9553f180-658e-11eb-9856-ce493d0857d1.png)

**Comment by stsrki** [comment]
@SuriyaArul Autocomplete was converted into a generic component recently. That means you now need to define `TItem` and `TValue`, eg.

```diff
<Autocomplete
+                TItem="MySelectModel"
+                TValue="string"
                Data="@myDdlData"
                TextField="@((item)=>item.MyTextField)"
                ValueField="@((item)=>item.MyTextField)"
                SelectedValue="@selectedSearchValue"
                SelectedValueChanged="@MySearchHandler"
                Placeholder="Search..." Filter="AutocompleteFilter.StartsWith" />
```

**Comment by SuriyaArul** [comment]
Hi @stsrki Thanks for your reply, I already tried this one, In my case TValue is Guid, so it's not taken properly. so I want to get Guid of selected value.

**Comment by stsrki** [comment]
Do you also have `SearchDiseasesHandlerAsync` as `Task SearchDiseasesHandlerAsync(Guid value)`?

**Comment by SuriyaArul** [comment]
yes

**Comment by stsrki** [comment]
@SuriyaArul Please open a new issue with the example of your code so I can reproduce it.

**Comment by SuriyaArul** [comment]
Sure @stsrki... will one new issue.., Thanks for your reply

**Comment by stsrki** [comment]
done with #1858
