### ISSUE TITLE
How to set static scales on LineChart

### ISSUE THREAD

**Issue by Flearz** [stsrki/Blazorise#440]
Hi,
I would like to set static states to a LineChart but I don't know how to do it...
Like xmin = -1, xmax = 1 and ymin =-4, ymax = 4
I don't want my chart to change the scales automatically when changing the data.
Thanks in advance

**Comment by stsrki** [comment]
Haven't tried it but according to [this source](https://stackoverflow.com/a/41218536/833106) you have to set the min and max values.

You can set it with an attribute `OptionsJsonString`, eg:

```
<LineChart @ref="lineChart" TItem="double"
    OptionsJsonString="@("{\"scales\": {\"xAxes\": [{\"ticks\": {\"max\": 1, \"min\": -1}}]}}")" />
```
