### ISSUE TITLE
NumericEdit DecimalsSeparator localization

### ISSUE THREAD

**Issue by robigit** [stsrki/Blazorise#442]
**Describe the bug**
If the default DecimalsSeparator of the OS is not the point (as in Italian) the NumericEdit doesn't allow to insert decimal numbers unless if you set the attribute DecimalsSeparator  equal to the OS one. (Convert.ChangeType eliminates the point)
**To Reproduce**
Try to put a number after the separator in a Italian OS.

However a great job. Thank you

**Comment by stsrki** [comment]
Hi @robigit 

This is by design. The default decimal point is set to the point as I had difficulties with sync between _blazor_ input and the _browser/system_ locale. The decimal separator must explicitly be defined so that it can work as expected.

**Comment by robigit** [comment]
Ok thank you. I wanted only stress that the attribute DecimalsSeparator  have to be set equal to that used in the OS of the server.
