### ISSUE TITLE
Active Button

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#444]
**Describe the bug**
In the demo pages (all 5 of them), in the section Buttons, there is an "Active Button". Is it really working? It behaves exactly like a normal button. Should it have a status like "pressed"? If so, I believe it is bugged.

Thank you!

**Comment by stsrki** [comment]
I just checked and it is working as expected. It has an `.active` class properly applied.

**Comment by WillianGruber** [comment]
I am sorry but I couldn't understand the purpose of the .active then. Shouldn't it have something distinguishable from a normal button? Or it is something in my side?

Default button:
![image](https://user-images.githubusercontent.com/56033692/71094731-349b0700-218a-11ea-91c1-31950b8dbbff.png)
Hovered: 
![image](https://user-images.githubusercontent.com/56033692/71094746-3d8bd880-218a-11ea-98b8-a6a912d2dbd6.png)
Clicked:
![image](https://user-images.githubusercontent.com/56033692/71094773-4da3b800-218a-11ea-9f7b-37a792ea3bd0.png)
Unfocused:
![image](https://user-images.githubusercontent.com/56033692/71094798-56948980-218a-11ea-9b48-bc7c4bef4ecb.png)


Active Button:
![image](https://user-images.githubusercontent.com/56033692/71094842-6744ff80-218a-11ea-908c-f42762d7dd5f.png)
Hovered (does not change):
![image](https://user-images.githubusercontent.com/56033692/71094867-7461ee80-218a-11ea-8703-3ee41200279c.png)
Clicked: 
![image](https://user-images.githubusercontent.com/56033692/71094895-80e64700-218a-11ea-818f-95e194776a1c.png)
Unfocused:
![image](https://user-images.githubusercontent.com/56033692/71094971-9fe4d900-218a-11ea-8d56-9a3609b18700.png)

By what I see, the difference is that the active hovered does not change visually, and the active button has a greater shadow. I guess I was expecting a greater change, maybe keeping the light blue outline of "Clicked" after unfocusing.

**Comment by stsrki** [comment]
As far as I know that is the expected behavior. Here is the description from bootstrap documentation: https://getbootstrap.com/docs/4.4/components/buttons/#active-state

**Comment by WillianGruber** [comment]
Yes, that is true. I think when the time comes I'll try to implement something like a "toggle button".
Thank you!
