### ISSUE TITLE
DetailRowTemplate - Remove empty td or change size

### ISSUE THREAD

**Issue by AjaxSantos** [stsrki/Blazorise#447]
**Is your feature request related to a problem? Please describe.**
I try to remove first empty td element of detail row, but i have no idea how to remove it.
![grafik](https://user-images.githubusercontent.com/56487025/71134224-b4ae8480-21fd-11ea-8719-7a5ea5d90615.png)
**Describe the solution you'd like**
An option to remove or change size of this first td.

**Comment by stsrki** [comment]
Why would you want to remove it? The preferred behavior for DetailRowTemplate is to stretch across data-columns, while command columns are not used.

**Comment by AjaxSantos** [comment]
Because it is just empty and take space, that i want to use this space for my detail information. For small displays or large detail information are 100px - 200px much space.
My expected behavior of detail row was, that it has full width of table with command column, because without command column it has it.

**Comment by stsrki** [comment]
Makes sense. In fact, it was working like that but I changed it to current state in the previous release. I will revert it in the next 0.8.8

**Comment by AjaxSantos** [comment]
Thank you. :)
