### ISSUE TITLE
Clear a Dropdown via reference

### ISSUE THREAD

**Issue by mfitconsultants** [stsrki/Blazorise#451]
This may already be possible but intellisense and the documentation do not seem to provide a solution. 

we require to show a reusable add/edit form which in turns contains a `Dropdown`

```cshtml
<Dropdown @ref="manufacturerDropDown">
	<DropdownToggle @ref="manufacturerDropDownToggle" Color="Color.Primary">
		@manufacturerDropDownText
	</DropdownToggle>
	<DropdownMenu @ref="manufacturerDropDownMenu">
		@if (manufacturers != null)
		{
			foreach (var manufacturer in manufacturers)
			{
				<DropdownItem Clicked="@(() => SetManufacturer(manufacturer))" Value="@manufacturer.Id">@manufacturer.Name</DropdownItem>
				<DropdownDivider />
			}
		}
	</DropdownMenu>
</Dropdown>
```

If I initially load the form and select a manufacturer, for example Samsung. Then I close the form and reopen `Samsung` is still selected.

How can I reset the dropdown to show the `@manufacturerDropDownText` please?

**Comment by stsrki** [comment]
Hi @mfitconsultants 

I cannot see your full code but I think you should just have to set `@manufacturerDropDownText ` to some default value every time you open a form. eg

```
void ShowForm()
{
    manufacturerDropDownText = "something";
  
    // do other stuff
}
```

**Comment by mfitconsultants** [comment]
@stsrki Sorry, yes you are correct this resets it perfectly
