### ISSUE TITLE
[Docs] Update FontAwesome css links

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#454]
Ref. #452 
Some icons do not show when using FA icons. Ex: bacon, baby, etc.
Probably because it is in the new version of FA Icons. Maybe the provider implements an old one in the references?
See #452 for print.

Thank you!

**Comment by WillianGruber** [comment]
@stsrki , if this is a simple version update, any chance of bumping it to .88?

**Comment by stsrki** [comment]
I will check it.

**Comment by stsrki** [comment]
Can you explain what actually is the problem? If some icons are missing I think all you need is to define newer css link. From here maybe: https://cdnjs.com/libraries/font-awesome

**Comment by WillianGruber** [comment]
You are right. Closing this issue.

**Comment by WillianGruber** [comment]
Maybe update documentation (quick start guide)?
