### ISSUE TITLE
Blazorized getting started

### ISSUE THREAD

**Issue by rad765** [stsrki/Blazorise#463]
I'm trying to get stated with Blazorised, using a Client side Blazor project.

1) Your "Getting started" state that I should add references to Blazorised in the index.html file. 
In a newly created Blazor client side project, this file does not exist. I guess that it should be included in the "_host.cshtml" file in stead?

2) You mention that a "js" file should be removed. I cant find this file in my project?

3) I'm not sure I understand point 5. Static files. Where would i put these lines?
As a start I have put these files into the _host.cshtml file as well.

**Comment by stsrki** [comment]
Hi @rad765 

1. The `index.html` is placed in `wwwroot` folder of your client-side Blazor app. In case it's not there it means you have a server-side app. Then it needs to be placed in the `_Host.cshtml`.
2. You need to remove links to the bootstrap css and js files that comes with the Blazor project template and that are usually placed inside of `wwwroot`. Sometimes they are of older _Bootstrap_ versions and if you leave them there they would interfere with the css and js files mentioned in the Blazorise usage guide. So you just replace them.
3. You can see an example in the Demo app: https://github.com/stsrki/Blazorise/blob/4b0917bad042eb863640c247bdea4134fafdc816/Tests/Blazorise.Demo.Bootstrap/wwwroot/index.html#L17

**Comment by rad765** [comment]
Hi Mladen

 

Thank you for your answers, an apologise for my amateurish questions… I’m pretty much a beginner to Web-development, but found Blazor and Bootstrap / Blazorise very exciting.

 

1.	You are completely right, I was in a server app. (still the documentation for Blazorise should mention both the index and the host file, as you actually do in the doc for the sidebar).
2.	Still I do not find any .js files in a newly created Blazor project. Just a minor thing thought, I remove the bootstrap css files and Balzorised seems to work.
3.	I have downloaded your demo, and has started to investigate this, and I see that in order to get things working this is necessary. 
The doc in itself will, in some cases not be sufficient reading. As example below – where you (according to your demo app) miss an “IsActive” test in all the tabs, and TabPanel lines. (As an beginner I like/need working copy-paste examples)





Thank you again for your time.

René

 

 

Fra: Mladen Macanović <notifications@github.com> 
Sendt: mandag 30. desember 2019 22:32
Til: stsrki/Blazorise <Blazorise@noreply.github.com>
Kopi: rad765 <rene@astaddupont.dk>; Mention <mention@noreply.github.com>
Emne: Re: [stsrki/Blazorise] Blazorized getting started (#463)

 

Hi @rad765 <https://github.com/rad765> 

1.	The index.html is placed in wwwroot folder of your client-side Blazor app. In case it's not there it means you have a server-side app. Then it needs to be placed in the _Host.cshtml.
2.	You need to remove links to the bootstrap css and js files that comes with the Blazor project template and that are usually placed inside of wwwroot. Sometimes they are of older Bootstrap versions and if you leave them there they would interfere with the css and js files mentioned in the Blazorise usage guide. So you just replace them.
3.	You can see an example in the Demo app: https://github.com/stsrki/Blazorise/blob/4b0917bad042eb863640c247bdea4134fafdc816/Tests/Blazorise.Demo.Bootstrap/wwwroot/index.html#L17

**Comment by stsrki** [comment]
You're absolutely right. Documentation can definitely be improved to be easier to understand. It's always hard for me to communicate it in a right way. I will see what I can do. tnx
