### ISSUE TITLE
DataGrid: Pre-define sort by column(s)

### ISSUE THREAD

**Issue by Herdo** [stsrki/Blazorise#465]
I want to pre-define a sorting for a `DataGrid` component, that cannot be changed by the user.

Therefore, I'd like to set `Sortable` to false, so that users cannot change the sorting, but define my own sorting (e.g. sort descending by column xyz).
So no matter in which order the `Data` collection is provided, which I may not be able to influence every time, I want it to be sorted in a specific order.

Possible solutions:
- Rename `Sortable` to `UserSortable`.
- When `TItem` implements `IComparable<T>`, provide an (opt-in) property to sort by the `IComparable<T>` (e.g. `MyType : IComparable<MyType>` and `UserSortable = false` and `SortByComparable = true`).
- Provide a property that accepts an `IComparer<T>` which will be used for default sorting.

**Comment by stsrki** [comment]
I think the best solution is for you to just sort your data-set before you provide it to DataGrid. eg:

```cs
void SetData()
{
    var myData = ( from q in someSource
                    orderby q.Field1
                    orderby q.Field2 descending
                    select q ).ToList();

    dataGrid.Data = myData;
}
```

You want to disable sorting anyway so I think that's the best solution.

Later I can maybe add an option to define sort columns.

**Comment by stsrki** [comment]
Already done with `Direction` parameter on DataGridColumn.
