### ISSUE TITLE
Alert Close Button

### ISSUE THREAD

**Issue by Qu3uk** [stsrki/Blazorise#471]
**Describe the bug**
On the bootscrap demo site as well as in own code the documented <CloseButton/> doesn't result in the alert closing. If you override Clicked on the Close Button to run Hide() the alert disappears but leaves behind whitespace on the UI.

0.8.7.2
Server Side

**To Reproduce**
1. Go to https://blazorise.com/docs/components/alert/#with-close
2. Click on the X on the green alert.
4. See that nothing happens

**Expected behavior**
When the alert is shown the element below are moved down to create space for the alert. When the Close Button is closed it hides the alert, elements below the alert when show ride up the screen in its place when its closed/hidden.

**Comment by stsrki** [comment]
I can confirm the bug on my side. Thank you for the report!
