### ISSUE TITLE
Justification of TableRowCell

### ISSUE THREAD

**Issue by gallwood** [stsrki/Blazorise#474]
**Is your feature request related to a problem? Please describe.**
I don't know if this is possible at the moment, but would it be possible to add Jjustification to a Table cell. For example, I would like to right justify a column that contains numeric values.

**Comment by stsrki** [comment]
Hi @gallwood 

I will add support for Alignment attribute to TableRowCell. In the meantime you try to workaround by assigning the `text-right` css class. eg.

```cshtml
<TableRowCell Class="text-right">123.45</TableRowCell >
```

**Comment by stsrki** [comment]
Done with v0.9
