### ISSUE TITLE
Bootstrap Demo | Opening Modal atop Data Grid breaks page scroll

### ISSUE THREAD

**Issue by roberestarkk** [stsrki/Blazorise#476]
## Expected Behavior
When a modal is opened on the datagrid page, and then closed again, the page should be scrollable once more.

## Current Behavior
After opening the modal to edit a row, and then closing it again, the page can no longer scroll down.

## Steps to Reproduce
1. Visit [https://bootstrapdemo.blazorise.com/tests/datagrid](https://bootstrapdemo.blazorise.com/tests/datagrid)
2. Scroll the page (resize window if necessary until scroll-able)
2. Change the 'Edit Mode' to 'Popup'
3. Click 'Edit' on one of the rows
4. Close the modal by clicking any of the three main buttons (Save, Cancel, X)
5. Attempt to scroll

**Comment by stsrki** [comment]
This is already fixed with #296 and it's going to be released with v0.8.8
