### ISSUE TITLE
How to specify text alignment in Blazorise bootstrap components?

### ISSUE THREAD

**Issue by AlmostRemember** [stsrki/Blazorise#481]
What is the preferred method to specify text alignment within Blazorise (bootstrap) components? For example, how should you center text in a `<Paragraph>` or `<CardText>` component?

I've found some approaches that work, but it wasn't obvious. I couldn't find anything in the documentation or demo site explaining how alignment should be done. 

```xml
<CardText class="text-center">
    This text should be centered
</CardText>
```

```xml
<CardText>
    <Text Alignment="TextAlignment.Center">
        This text should be centered
    </Text>
</CardText>
```
It would be nice for some of the text-focused components to have an alignment property directly on them. I'd also like to see some mention of text alignment in the documentation somewhere. The `<Text>` component _does_ have an alignment property, but it isn't mentioned in the documentation.

**Comment by stsrki** [comment]
Hi @AlmostRemember 

I already have plans for adding alignment to some of the component. For example this issue #474 

Since this is a minor change I will push this to the next release and update text-focused components. Also I will update documentation to make it more clear.

Thanks for your feedback.

**Comment by stsrki** [comment]
PS.

```cshtml
<CardText class="text-center">
    This text should be centered
</CardText>
```

Using attributes like in this example is called attribute splatting and basically all it does is pass through all of the attributes that not match any defined attribute. Blazorise also supports it but it is advised only as a last resort.

**Comment by AlmostRemember** [comment]
Great, thanks for your help.
