### ISSUE TITLE
[DataGrid] Aggregate columns

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#489]
- Sum
- Average
- Min
- Max
- Count
- TrueCount
- FalseCount

**Comment by ricardoromaobr** [comment]
I believe that will be necessary a handle to be used when ReadData handle is used. So developer side make this manually. What means TrueCount and FalseCount?

**Comment by stsrki** [comment]
@ricardoromaobr Yes, I plan to also add handlers so that developers can have better control over aggregations.

Regular Count will count all items. TrueCount and FalseCount means it will count only the items that have handlers that return true or false.
