### ISSUE TITLE
Safari rendering issues

### ISSUE THREAD

**Issue by vignatov** [stsrki/Blazorise#49]
I noticed that on Safari browser rendering of some elements is not correct. Breadcrumbs are rendered other 2 lines (same on demo project). And table row heights are indirect if the table is not full length. I think there is some issue with padding.

**Comment by stsrki** [comment]
I see there is also problem with breadcrumbs in chrome and firefox. As far as I can see all of the css classes are defined as they should be. I will need to investigate more to see whats the real problem.

Can you explain more whats the problem with tables? I dont see it. Screenshot would also be great.

**Comment by vignatov** [comment]
I noticed that the breadcrumb issue happens in chrome too.
The table one is very weird, I am still not sure if it is the style issue or a bug. Basically if the width of the table is not full the row with longest text always adds an extra line. It happens only in Safari. the screenshot:
<img width="352" alt="Screenshot 2019-03-18 at 12 44 18" src="https://user-images.githubusercontent.com/17622017/54530803-aa640f00-497b-11e9-91cc-0335709be21b.png">

I also noticed that the Dropdown button on [this page](https://bootstrapdemo.blazorise.com/tests/buttons) is rendered over 2 lines too.
<img width="170" alt="Screenshot 2019-03-18 at 12 48 06" src="https://user-images.githubusercontent.com/17622017/54530970-1b0b2b80-497c-11e9-8a3a-5c5431a56ca4.png">

**Comment by stsrki** [comment]
So I was playing with this for a couple of hours and so far I could not find a solution. 

1. For Breadcrumbs every css class is defined as should be. There is not any special style that override them and still it goes to second line. Really weird :/
2. Dropdown works in the newest Bootstrap(4.3.1) while for the current version(4.2.1) it's not working only in Firefox. Maybe I can upgrade projects to the newest Bootstrap.

Since I don't have Safari I really cannot do much regarding your problems with table.

**Comment by vignatov** [comment]
I played a little bit with it, I did not find a cause, but I found a quick workaround:
`white-space: nowrap;` in breadcrumbs css solves it (the same works for my safari table issue).
<img width="259" alt="Screenshot 2019-03-19 at 09 53 00" src="https://user-images.githubusercontent.com/17622017/54599460-9b8c6380-4a32-11e9-9287-553ddedb49b5.png">

There is a weird spacing which is partly defined by `padding-right` setting on the `before` element and partly by the text padding, this can be fixed with styling.

**Comment by stsrki** [comment]
Fixed in the latest version!
