### ISSUE TITLE
[DataGrid] Add First and Last pagination buttons

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#492]

**Comment by geersjake** [comment]
Does this issue encapsulate setting a maximum number of pages as well? For example a grid with lots of pages it would go [First, 1, 2, 3, 4, 5, ..., Last] or some such instead of displaying all possible pages. Or is this just for the first/last buttons?

**Comment by stsrki** [comment]
It's for the first and last page mainy, but I can consider adding pages in between for large datasets.

**Comment by geersjake** [comment]
I would be very interested as currently they are not limited.

![image](https://user-images.githubusercontent.com/16827334/72525112-69ee4f80-3831-11ea-9ff8-91f10502624b.png)

**Comment by stsrki** [comment]
What version of Blazorise are you running? This was fixed in the last v0.8.8

**Comment by geersjake** [comment]
Awesome. I was running 0.8.5 which I thought was current according to [Releases](https://github.com/stsrki/Blazorise/releases). I see in now the Nuget feed has the 0.8.8 though. Thanks for your hard work!

**Comment by stsrki** [comment]
Aaah, the release tab was used only for older versions when the content files were meant to be included manually. I will remove it now so it doesn't confuse people. Thanks for pointing me.

**Comment by Timovzl** [comment]
Can these buttons actually be hidden? I prefer to limit the number of pages and keep things looking a bit more neat, with only previous and next buttons, like the `Pagination` component!

Using an empty template for the First and Last buttons them only makes them look weird, unfortunately.

**Comment by stsrki** [comment]
@Timovzl not at the moment. Although it is a good feature to have. 

One workaround could be to use CSS and select those elements. Then just set `display: none;`
