### ISSUE TITLE
[DataGrid] Multi-Sorting 

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#493]
Currently only one column can be sorted. This was due to the limitations in Mono runtime. Hopefully this can be now done.

**Comment by ricardoromaobr** [comment]
Maybe this can helped. I'm trying to get time to experiment it
[take a look](https://github.com/ricardoromaobr/monoreports/blob/dd930beb7d695b48c7163e93c27fb3dc8a2d4fa6/src/MonoReports.Model/Data/ObjectDataSource.cs#L122-L177)
but was't possible yet

**Comment by ricardoromaobr** [comment]
Because it is a project to running with mono I believe  that will works.I'm running it in linux and Mac OS X.

**Comment by ricardoromaobr** [comment]
Implemented I will made pull request

**Comment by ricardoromaobr** [comment]
I made a pull request to complete this item.
