### ISSUE TITLE
[Bug] InvalidOperationException: Unsupported type System.UInt64 for NumericEdit

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#496]
**Describe the bug**
Hi @stsrki ,
After the update for 0.8.8 this exception is raised. It worked before.
![image](https://user-images.githubusercontent.com/56033692/72169701-64ff4b00-33ae-11ea-8c24-a075c5942430.png)

Could you take a look at it?
Thanks!

**Comment by WillianGruber** [comment]
The following integer types are not supported in https://github.com/stsrki/Blazorise/blob/c2eec51d108e71f38a51abcdc5c24ce3b688ff1f/Source/Blazorise/NumericEdit.razor.cs#L88
sbyte
byte
short
ushort
uint
ulong

**Comment by stsrki** [comment]
No problem, I will do this in the 0.8.8 quick fix.

**Comment by stsrki** [comment]
Done. I will wait with publish a day or two to see if there is going to be more bugs with 0.8.8.

**Comment by WillianGruber** [comment]
Thank you!
