### ISSUE TITLE
SelectedValueChanged on SelectEdit

### ISSUE THREAD

**Issue by cr1t** [stsrki/Blazorise#498]
Hi 

I'm new to blazorise and Blazor. 
I'm trying to use the SelectedValueChanged as in the documents but I keep getting this error
Argument 2: cannot convert from 'method group' to 'EventCallback'

Sorry if this is not the place to post this question

![image](https://user-images.githubusercontent.com/4394765/72200611-4489cc00-3454-11ea-99dd-aa3ab4084f33.png)

**Comment by cr1t** [comment]
My fault the input parameter was and int not an string

**Comment by stsrki** [comment]
Can you post full code sample?

FYI: `OnSelectedValueChanged `must have defined parameter as an input. Also you must define `TValue `type on `SelectEdit`

**Comment by cr1t** [comment]
Hi I Literally copied it from the documentation


> <SelectEdit SelectedValue="@selectedValue" SelectedValueChanged="@OnSelectedValueChanged">
    <SelectItem Value="1">1</SelectItem>
    <SelectItem Value="2">2</SelectItem>
    <SelectItem Value="3">3</SelectItem>
    <SelectItem Value="4">4</SelectItem>
</SelectEdit>

> @code{

    int selectedValue = 2;

    void OnSelectedValueChanged(int value)
    {
        selectedValue = value;
        Console.WriteLine(selectedValue);
    }
}

**Comment by stsrki** [comment]
As I thought, you need to add TValue to define data type:

```cshtml
<SelectEdit TValue="int" SelectedValue="@selectedValue" SelectedValueChanged="@OnSelectedValueChanged">
    <SelectItem Value="1">1</SelectItem>
    <SelectItem Value="2">2</SelectItem>
    <SelectItem Value="3">3</SelectItem>
    <SelectItem Value="4">4</SelectItem>
</SelectEdit>

@code{
    int selectedValue = 2;

    void OnSelectedValueChanged( int value )
    {
        selectedValue = value;
        Console.WriteLine( selectedValue );
    }
}
```

Anyways, I will also update documentation as it is for older version of Blazorise before I have added support for generic types. Thank you for letting me know.
