### ISSUE TITLE
BaseNumericEdit.FormatValueAsString throwing InvalidOperationException

### ISSUE THREAD

**Issue by Herdo** [stsrki/Blazorise#500]
**Describe the bug**
Due to the changes in the commit [`fix: NumericEdit decimal separator`](https://github.com/stsrki/Blazorise/commit/2dfcae44d30c01dbbc58a066bcf1fc4c85001544), binding multiple value types, like `byte`, `ulong`, or nullable types `byte?`, `ulong?` will throw an `InvalidOperationException` in `BaseNumericEdit.FormatValueAsString`.

**To Reproduce**
1. Create a model having one `byte?` and one `ulong` property.
2. Create a form with two `NumericEdit` components.
3. Bind the model properties to the `NumericEdit` components.
4. The component will throw an exception and won't render.

**Expected behavior**
All numeric data types should be bindable to a `NumericEdit` component, including the `nullable` versions.

**Example**
```cs
// Model
public ulong AppId { get; set; }
public byte? DecayPeriod { get; set; }
```
```html

// Razor
<Field>
    <FieldLabel>App Id</FieldLabel>
    <NumericEdit @bind-Value="@MyModel.AppId"
                  TValue="ulong"
                  Decimals="0"
                  Step="1"/>
</Field>
<Field>
    <FieldLabel>Decay period</FieldLabel>
    <NumericEdit TValue="byte?"
                @bind-Value="@MyModel.DecayPeriod"
                 Decimals="0"
                 Step="1"/>
</Field>
```

**Comment by stsrki** [comment]
Thanks for the report. I will check and see what can be done.

**Comment by stsrki** [comment]
Tested and it's working. Probably it was fixed in one of the previous versions.
