### ISSUE TITLE
Strange Error after update to 0.8.8 with Modals

### ISSUE THREAD

**Issue by kamilkosek** [stsrki/Blazorise#505]
Hi all,
today i´ve updated our project to 0.8.8 and we are now facing a strange issue with modal´s. 
Until 0.8.7.1 I´ve used @ref and the Show() and Hide() Methods to display/hide the modals. But now I am getting an exception stating "modal" is not found inside the browser: 
![image](https://user-images.githubusercontent.com/3264948/72331801-19ec7d00-36b9-11ea-93aa-850cb73e3586.png)

Have i missed something ?

**Comment by stsrki** [comment]
Try refreshing browser with Ctrl+F5. It also happens to me sometimes.

**Comment by kamilkosek** [comment]
Ok thank you, this led me to my issue. 
Since I am using your project for quite a time, I´ve had some old references to the js files - from a time when you´ve had to copy them by yourself to the wwwroot folder.
Thanks so much for your effort.
