### ISSUE TITLE
Support for MVVM with ICommand

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#506]
Feature requested by @richbryant 

The idea is to add support for ICommand that will fire along with current event handlers.

https://docs.microsoft.com/hr-hr/archive/blogs/mikehillberg/icommand-is-like-a-chocolate-cake

**Comment by richbryant** [comment]
This feature was tested [here](https://github.com/richbryant/CommandTesting) and works really well, although I'll have to add another test using `CommandParameter`.
