### ISSUE TITLE
BootStrap Alert Close Button

### ISSUE THREAD

**Issue by Qu3uk** [stsrki/Blazorise#507]
**Describe the bug**
So following on from #471 I see the Alert button working on the following site https://blazorise.com/docs/components/alert/ but it appears to still not work on the bootstrap demo https://bootstrapdemo.blazorise.com/tests/elements under dismissable alerts as well my own code using the bootstrap blazorise.

Wondering if this site hasn't been updated to .8.8 or something is still a miss which would explain why it doesn't work in my own code.

**To Reproduce**
1. Go to 'https://bootstrapdemo.blazorise.com/tests/elements
2. Click on the X on the green alert Under Dismissable Alerts
3. See that the alert doesn't disappear.

**Expected behavior**
When the alert is shown the element below are moved down to create space for the alert. When the Close Button is closed it hides the alert, elements below the alert when show ride up the screen in its place when its closed/hidden.

**Comment by stsrki** [comment]
The reason why it doesn't work is cause I still didn't update the demo pages. Thanks for letting me know.
