### ISSUE TITLE
[Question] How to reset button state after click?

### ISSUE THREAD

**Issue by AlmostRemember** [stsrki/Blazorise#508]
When a blazorise button is clicked it changes to the active/clicked state and will remain that way until you click somewhere else on the page. How do you reset the button back its normal state? Is there something you need to do in the click event handler?

**Comment by stsrki** [comment]
Thats the expected behavior. The button is only focused after you click on it.

**Comment by AlmostRemember** [comment]
I understand that. I'm asking how to reset the button back to the normal state after it is clicked. It doesn't look right for the button to remain in the clicked state until you happen to click somewhere on the page.

**Comment by stsrki** [comment]
@AlmostRemember You can see the same behavior on the bootstrap documentation page: https://getbootstrap.com/docs/4.4/components/buttons/

You can change it only if you override bootstrap css with your own.

**Comment by AlmostRemember** [comment]
Ok, thanks for explaining.
