### ISSUE TITLE
Blazorize?

### ISSUE THREAD

**Issue by alexsaalberg049** [stsrki/Blazorise#512]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Blazorize kind of looks better than Blazorise (Z's are just naturally cool letters. See: Blazor)

Maybe it could be called that?

Probably too confusing at this point, but :man_shrugging:

**Comment by stsrki** [comment]
It's made-up word so there's no the right way. But I think _rise_ is better because it has a meaning like "_To move upwards_". And renaming domain, branding, all source code would not make any sense at this point.
