### ISSUE TITLE
Alerts are always visible

### ISSUE THREAD

**Issue by iberisoft** [stsrki/Blazorise#518]
**Describe the bug**
The alerts are always visible under version 0.8.8.1.

**To Reproduce**
Create a page like:
```
<Alert Color="Color.Warning" IsShow="alertMessage != null">@alertMessage</Alert>

@code {
    string alertMessage;
}
```
Then see the `Alert` visible even `alertMessage` is always `null`.

**Expected behavior**
Version 0.8.7.2 hides the `Alert` when `alertMessage` is `null`.

**Comment by stsrki** [comment]
@iberisoft I cannot reproduce bug. I tried to follow your example and for me everything works as expected.

**Comment by iberisoft** [comment]
Got it. Let me share a dummy project later.

**Comment by stsrki** [comment]
Hi @iberisoft, have you managed to create dummy project? tnx

**Comment by iberisoft** [comment]
> Hi @iberisoft, have you managed to create dummy project? tnx

As you can see in my repo, it was not needed. Just change `IsShow` in your test then see: the `Alert` is visible.

**Comment by stsrki** [comment]
I see the problem now. 

```diff
[Parameter]
public bool IsShow
{
    get => isShow;
    set
    {
        // prevent alert from calling the same code multiple times
+        if ( value == isShow )
+            return;

        isShow = value;

        HandleVisibilityState( value );

        DirtyClasses();
    }
}
```

Basically the code from above will skip because `IsShow` is by default set to false.
