### ISSUE TITLE
data grid : Size of grid, font size and filter size problems

### ISSUE THREAD

**Issue by Swdvader** [stsrki/Blazorise#529]
Using Data Grid:
Maybe I am missing something don't think its a bug.  I don't see any controls for sizing the grid, filter boxes and text.
To change the font size, I wrapped the grid in a div container and set font-size. This works to reduce the font in the grid, but the filter boxes remain the same full size?   How do I reduce the filter boxes to match?  I found the column width and that works to reduce the individual column (not text) size. 
Also, is there are no built in functions for grid height.  Example grid is displaying 100 but will scroll because height is only 500px.  
Thanks.

**Expected behavior**
Everything to be same font size

**Screenshots**
![Capture](https://user-images.githubusercontent.com/14371980/73138441-83ad4500-4030-11ea-842e-ff898d5a251f.PNG)
***code***
![Capture](https://user-images.githubusercontent.com/14371980/73138652-4c8c6300-4033-11ea-9fb7-98305d65b138.PNG)

<div style="font-size:.6em;">
    <DataGrid TItem="SearchModel" ShowPager="true" PageSize="10" Filterable="true" IsStriped="false" IsHoverable="true" IsNarrow="true" CurrentPage="1"
              Data="@trans"
              @bind-SelectedRow="@selectedEmployee">
        <DataGridCommandColumn TItem="SearchModel" Width="20px"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.Account)" Caption="Account" Width="50px"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.Visit)" Caption="Visit" Width="10px"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.DOB)" Caption="DOB"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.Charges)" Caption="Charges" Width="20px"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.Balance)" Caption="Balance" Width="20px"/>
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.Status_Resolution)" Caption="Status/Resolution" />
        <DataGridColumn TItem="SearchModel" Field="@nameof(SearchModel.ProductLine)" Caption="Product Line"/>
    </DataGrid>
</div>

**Comment by stsrki** [comment]
Hi @Swdvader, currently there is no way to control size of a grid controls, other than the column width. I plan to add this feature in the future. As a workaround, you can try to target specific parts of datagrid by playing with CSS. I think that is the best way for now.

**Comment by Swdvader** [comment]
Ok.  I was able to resolve the issue by adding some css

//to control the filter box size
input[type="text"] {
    font-size: 10px;
}
//puts grid in window and scrolls
.bgrid {
     height:500px; overflow:scroll;
}
