### ISSUE TITLE
Grid freeze header and filter row

### ISSUE THREAD

**Issue by rpascalegh** [stsrki/Blazorise#530]
Would be a great option, when grid is larger then screen heading row and filters scroll.  Would like to see  these remain fixed on top and have grid scroll.  Ive done this on a table in CSS, Im going to try and get it to work on this grid.

**Comment by Swdvader** [comment]
This css code will freeze the top row of the grid.  Only issue is when you add the filters it freezes the filter row.

Wrap grid in DIV with a  class="outer2"

.outer2 {
    overflow-y: auto;
    height: 600px;
}


        
.outer2 table th {
    text-align: left;
    top: 0;
    position: sticky;
    background-color: mediumpurple;
}

**Comment by Swdvader** [comment]
Is there a way for me to edit the grid component?  When you generate the html the header row and filter row have all the same tags.  So when I freeze the row they are sitting on top of each other.  All I would need to do is add a class or ID to filter row and I could freeze both rows of the grid.

![image](https://user-images.githubusercontent.com/14371980/73142607-c4bc4e00-405e-11ea-815d-902af5e39343.png)

**Comment by stsrki** [comment]
Currently there is no option to control class or style attributes. I can add this option to the next release of 0.9-preview.

**Comment by stsrki** [comment]
All of this is now possible with RowStyling, HeaderRowStyling and FilterRowStyling.
