### ISSUE TITLE
Blazorise.Demo.Material index.html has extraneous javascript (or a lack of documentation)

### ISSUE THREAD

**Issue by MarkStega** [stsrki/Blazorise#533]
**Describe the bug**
Index.html in Blazorise.Demo.Material has
```
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
```
which I believe is extraneous.

**To Reproduce**
1. Clone the Blazorise repository
2. Examine the code in index.html in the Blazorise.Demo.Material project
3. Observe the jquery/bootstrap javascript includes.

**Expected behavior**
Expect only required javascript.

**Screenshots**
n/a

**Additional context**
If the javascript is required then documentation as to how it is being used would be useful. The current documentation shows only the required setup for Bootstrap. It woulds be better to have a section of setup for Bulma, Frolic, & Material also (plus whatever other providers get added).

**Comment by stsrki** [comment]
There are usage for other css frameworks also: https://blazorise.com/docs/usage/

**Comment by MarkStega** [comment]
Consider adding to the section in the readme.md that starts with "This guide will show you how to setup Blazorise with Bootstrap and FontAwesome icons." with "To setup Blazorise for other CSS frameworks, please refer the Usage page in the documentation." which is now found at the very end of the document.

Or consider just referring to the documentation for setup & use and not repeating in the readme.md. In the readme.md perhaps a general description of what each aspect of the css & js includes do would be appropriate.

**Comment by stsrki** [comment]
@MarkStega Will do. Thank you for the suggestion. This is the exact reason why I'm searching for someone who can help me with the documentation. https://github.com/stsrki/Blazorise/issues/255
