### ISSUE TITLE
BUG: Uncaught Type Error: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by RobertChanphakeo** [stsrki/Blazorise#535]
**Describe the bug**
Multiple errors "Uncaught TypeError: Cannot read property 'children' of null"
https://materialdemo.blazorise.com/

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://materialdemo.blazorise.com/
2. Right-click on inspect to open "Developer's tool" 
3. Click on the console tab

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/1288153/73221132-3b1e9480-41b4-11ea-8434-cfa652bcbabe.png)

**Additional context**
The issue also occurs at https://bootstrapdemo.blazorise.com/

**Comment by stsrki** [comment]
I cannot reproduce. I tried on Chrome, Firefox and Edge. Everything works without any errors.
