### ISSUE TITLE
Demo sites and Blazorise templates

### ISSUE THREAD

**Issue by timahrentlov** [stsrki/Blazorise#537]
It would be really nice to have a couple of demo sites and Blazorise templates that is constructed using Blazorise. Rewrittes of popular Dashboards and the like. That could catapult Blazorise into fame.

**Comment by stsrki** [comment]
@timahrentlov Can you explain more what you mean by dashboard? There already exists demo app(s) that simulates dashboard templates: https://bootstrapdemo.blazorise.com/

**Comment by timahrentlov** [comment]
I was thinking templates more like https://startbootstrap.com/themes/sb-admin-2/ that perhaps is easier to grab and modify for real-life purposes. The current demo is excellent, but it I experience it not as something to copy and run with. Do I makes sense?

**Comment by stsrki** [comment]
This was my inspiration for Blazorise demo app(s): https://coderthemes.com/minton/layouts/vertical/blue/index.html

As far as I can see it's quite similar to what you propose. The only things that are missing are pages like Login, Register, Email client, etc. And with that I agree completely. It's just that I'm too busy with other things in Blazorise.

**Comment by timahrentlov** [comment]
Yes, that would be a boon. I fully appreciate that you're working fulltime on other free stuff. Justed wanted to chime in on something that might help proliferate your excellent work.

**Comment by stsrki** [comment]
I will close this issue as I plan to do templates for Blazorise in another project.
