### ISSUE TITLE
DataGrid: Sort icon is missing after load even if sortable is set to true

### ISSUE THREAD

**Issue by rgeike** [stsrki/Blazorise#539]
**Describe the bug**
In version 0.8.8.1 of DataGrid for Bulma the sort icon is not shown anymore. Only if you click on the column header to sort by, the sort icon appears again.

**To Reproduce**
1. Go to a page with DataGrid
2. Click on a header of a column to sort
3. Sort icon appears

**Expected behavior**
The sort icon should be visible on load or at least on mouseover. Best would be if you can set the behaviour via a property.

**Comment by stsrki** [comment]
Thats by the design. In latest version I introduced `SortDirection.None` enum and its set to default for all columns. The reason for `None` is so that users can know if sorting must be applied when DataGrid is in _manual_ data loading mode.

**Comment by rgeike** [comment]
I tried to set Direction.Ascending as you suggest. After loading the grid, sorting is not applied but the icon is visible. I also can only hit the sorting twice (ascending and descending) then it does nothing. Though hitting other columns sorting (which works) enables the broken sorting for my column with Direction.Ascending again.

**Comment by stsrki** [comment]
That is a bug it seems. When DataGrid is first initialized it should also figure Direction is pre-applied. I will move this to 0.8.8.2.

**Comment by stsrki** [comment]
@rgeike I just realized this should be better in moved to next v0.9. The reason is that in v0.8.8 sorting was limited for only one column at a time, while in v0.9 sorting is enabled on all columns.

New preview version will be available in the next couple of days. Hopefully that is OK with you?
