### ISSUE TITLE
Color Improvement

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#540]
It would be nice to enable the Color attributes in all components to receive string variables with custom colors, i.e:
name: "red"
hex: "#ff0000"
rgb: "rgb(255,0,0)"

In my case I am using custom colors to represent the colors of the theme in an icon.
I can mitigate it by surrounding with a ```<p style="color:red">```, but the Color doen't work in Icon, and the style/Style doesn't work in Blazorise.Paragraph.

Thanks!

**Comment by stsrki** [comment]
Hi @WillianGruber 

Not sure how this could work. We already have `Color` enums that are used as abstraction for predefined color variants in Bootstrap or Bulma.

**Comment by WillianGruber** [comment]
Yes. My intention is to enable customer brand colors by overloading the Color attribute to receive not only the Color Enum. But this is really low priority, it's only a thing that could be useful.

**Comment by stsrki** [comment]
In that case it can be done through the theme generator. I will need to see what is currently possible and is required.

**Comment by WillianGruber** [comment]
Yes, once the ColorPicker is released, it would be needed to have the overload in the Color. Check my ThemeEditor at https://github.com/stsrki/Blazorise/issues/564 in some minutes

**Comment by stsrki** [comment]
Closing since I have no plans to add support for color parameter.
