### ISSUE TITLE
Modal should not close when clicking outside of the modal window

### ISSUE THREAD

**Issue by HeathU** [stsrki/Blazorise#549]
**Is your feature request related to a problem? Please describe.**
Expected behaviour for a modal window is that it can't be dismissed by clicking outside of the window area. Although the Closing event can be used to prevent the modal from closing, it can require substantial code to prevent users from accidentally cancelling the modal, that may of includes substantial changes in a form, therefore losing their changes. When an app includes many modals, using the Closing event isn't easy to implement.

**Describe the solution you'd like**
Change the modal behaviour to prevent closing when clicking outside of the modal area.

**Comment by stsrki** [comment]
Hi @HeathU 

If I understood you correctly, you only want to disable closing of modal by clicking on backdrop? What about the ESC key?

**Comment by HeathU** [comment]
> If I understood you correctly, you only want to disable closing of modal by clicking on backdrop? What about the ESC key?

Good point. I would handle ESC key and clicking outside of the area as cancelling, as opposed to closing. I would like cancelling to be disabled.

**Comment by stsrki** [comment]
Unfortunately it's not that easy to do. The way how it currently works is the default behavior of Bootstrap or Bulma CSS frameworks. That's the reason why I implemented `Closing` event handler so that it can be controlled.

So both clicking on backdrop and pressing the ESC key are calling the `Closing` event, and eventually if it's not cancelled it will close. Now, I can add one additional parameter to the `Closing` event that will tell you what's the reason for closing. Something like:

```cs
enum CloseReason
{
    User, // regular close
    Backdrop, // click
    Escape, // key press
}
```

**Comment by HeathU** [comment]
Yes, perfect!

**Comment by WillianGruber** [comment]
User means CloseButton and CancelButton together??
What about if it was:
```
enum CloseReason
{
    CancelButton //Button on footer
    CloseButton, // X in top-right
    Backdrop, // out-of-bounds clicking
    Escape, // key press
}
```
?

**Comment by stsrki** [comment]
@WillianGruber @HeathU I'm just working on this. It is something like this

```cs
/// <summary>
/// Specifies the reason that a component was closed.
/// </summary>
public enum CloseReason
{
    /// <summary>
    /// The cause of the closure was not defined or could not be determined.
    /// </summary>
    None,

    /// <summary>
    /// The user is closing the form through the user interface.
    /// </summary>
    UserClosing,

    /// <summary>
    /// The component has lost focus or gone out of bounds.
    /// </summary>
    FocusLostClosing,
        
    /// <summary>
    /// Pressing the escape key is closing the component.
    /// </summary>
    EscapeClosing,
}
```

I'm not sure how to name `FocusLostClosing`. Any suggestions?

**Comment by HeathU** [comment]
> FocusLostClosing

I can't think of anything better to describe it. Perhaps just extend the comment to include clicking outside of the component?

**Comment by WillianGruber** [comment]
Couldn't find a better term either...

**Comment by stsrki** [comment]
OK, I will leave it as it is. I think it's fairly explainable.

**Comment by sturlath** [comment]
Hi you might want to add this to the docs ;-)

**Comment by stsrki** [comment]
@sturlath The Closing example is already in the docs https://blazorise.com/docs/components/modal

**Comment by sturlath** [comment]
But not `CloseReason`. I at least had to add the following code so my modal wouldn´t close except on the x and the buttons. Without it I can close it by clicking outside of the modal. 

`
  private Task OnModalClosing(ModalClosingEventArgs e)
  {
      if (e.CloseReason != CloseReason.UserClosing)
      {
          e.Cancel = true;
      }

      return Task.CompletedTask;
  }
`

Maybe there have been some changes somewhere I haven't implemented on my side?

**Comment by stsrki** [comment]
Yes, you're right. I could add that to be docs.

**Comment by HariKrishnaPatta** [comment]
Inside model we can write 
keyboard={false}  
 maskClosable={false}
