### ISSUE TITLE
Fade Option in Tooltip as ThemeTooltipOptions

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#553]
Hi,
I just thought that Fade Option in Tooltip could be included in a new ThemeTooltipOptions...
If using the attribute directly in the tooltip, it should overwrite the Theme option.

Also, it could include the Placement as well, same behavior, (attribute prioritized over theme option).

Basically this means the default value could be parametrized through themes.

What do you think?

**Comment by stsrki** [comment]
Sounds fairly reasonable. Going on the list ;)

**Comment by WillianGruber** [comment]
Thanks!

Basically, all cosmetic attributes could be included in theme, and leave it as attribute to forcefully define it in some cases.

**Comment by stsrki** [comment]
I agree. It's just that there are just too many attributes to handle. But yeah, I agree completely.

**Comment by WillianGruber** [comment]
OK, whenever I find something that could be cool in theme I'll open an issue for control :)
