### ISSUE TITLE
Add generic animations

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#556]
It would be nice if blazorise had configurable animations.
I am actually planning to use https://github.com/mikoskinen/Blazor.Animate , but it blazorise implements animations integrated with the theme component it would be awesome.

Do you think this is a possibility? Or anyone needing animations should use https://github.com/mikoskinen/Blazor.Animate ?
I would wait for this implementation, just need to know if it will ever come...
Also, I think this relies heavily in jquery, and you said you wouldn't like to mess with that.

**Comment by stsrki** [comment]
I would go with Blazor.Animate library for now, if it works for you, why not. There is much more work for Blazorise that needs to be done, that doing animation library as good as this one is not going to happen any time soon.

**Comment by WillianGruber** [comment]
Thank you, I'll implement it with the blazorise theme in my custom theme provider.
