### ISSUE TITLE
[Question] Image in SidebarBrand

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#557]
Hello,
I'm trying to insert an image in the SidebarBrand but it isn't working... is it even possible?
I tried 2 ways:
```
<SidebarBrand>
    <FigureImage Source="~/logos/Logo 192x192.png" AlternateText="AlternateText"></FigureImage>
    <a href=""><img src="~/logos/Logo 192x192.png" alt="AlternateText"></a>
</SidebarBrand>
```
Any help is appreciated.
Thank you!

**Comment by stsrki** [comment]
Just tried it

![image](https://user-images.githubusercontent.com/900302/73577785-25dc8b00-447e-11ea-86e5-aad86712172b.png)

probably you have an invalid path to the image: Have it like this:

`<a href=""><img src="logos/Logo 192x192.png" alt="AlternateText"></a>`

**Comment by WillianGruber** [comment]
Removing ~/ from src worked. Thanks!
