### ISSUE TITLE
Modal closing attribute not working (Server-Side)

### ISSUE THREAD

**Issue by brycehewett** [stsrki/Blazorise#558]
I'm trying to prevent the modal from closing when clicking the backdrop or pressing the escape key. I'm using the attribute as I found it from the documentation, but i get an error that says: "No overload for 'OnModalClosing' matches delegate 'Action<CancelEventArgs>'"

Also the method for OnModalClosing is getting an error saying: "The type 'CancelEventArgs' could not be found.

I'm using Blazorize.Bootstrap 8.8.2

Any help would be great, thanks!

My code below:
```
<Modal @ref="orderConfirmationModal" Closing="@OnModalClosing">
    <ModalBackdrop />
    <ModalContent IsCentered="true" Size="ModalSize.Small">
        <ModalHeader>
            <ModalTitle>Are you sure?</ModalTitle>
        </ModalHeader>
        <ModalBody>
            The order for @Dto.FirstName  @Dto.LastName  has been added successfully!
            Record #@addOrderAsycResponse.patientLocalId
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Primary" Clicked="@ResetPage" Size="ButtonSize.Large">Done</Button>
        </ModalFooter>
    </ModalContent>
</Modal>
```

```
private void OnModalClosing(CancelEventArgs e)
{
        // just set Cancel to true to prevent modal from closing
        e.Cancel = true;
}
```

**Comment by stsrki** [comment]
Probably you're missing namespace `System.ComponentModel`. Try adding it to _Imports file

**Comment by brycehewett** [comment]
Yes, that was the issue! Thanks for the quick response!
