### ISSUE TITLE
Vertical center of captionless Figure

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#559]
**Describe the bug**
Create a Inline component.
Inside it, use a Blazorise.Figure without the FigureCaption.
Add a Text component.
Close the Inline component.

This makes the text appears in the right of the image, but not really centered, as the vertical center is calculated with the Caption in mind.
When using a img tag, the text stays really centered vertically from the image.

** Expected behavior**
When using a Figure without a Caption, dont include the caption height in the total Figure height. Should display the same as img tag.

**Comment by WillianGruber** [comment]
Just set Margin.Is0.FromBottom on Figure

**Comment by stsrki** [comment]
Sorry I completelly forgot about your issue. It's great you managed to find the solution.

**Comment by WillianGruber** [comment]
My bad, I should have invested some more time figuring that out.
