### ISSUE TITLE
[Question] How should these theme attributes be filled?

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#564]
What are the default values for the following attributes? 

- Theme.ButtonOptions.Padding
- Theme.ButtonOptions.Margin
- Theme.ButtonOptions.BoxShadowSize

They are null in the theme for me

**Comment by stsrki** [comment]
They're set to null. Not sure if I'm going to use that one. I'm thinking to split it into `PaddingX`(left-right) and `PaddingY`(top-bottom). The same for Margin.

**Comment by WillianGruber** [comment]
Ohh ok. As I'm building a theme editor, knowing the default values would be a good idea to fill the fields.

**Comment by stsrki** [comment]
I could be really interested in that theme editor 😉

**Comment by WillianGruber** [comment]
> I could be really interested in that theme editor 😉

Will paste the code here soon. Use as you wish.

**Comment by WillianGruber** [comment]
Here it is.
I think all dependencies are here. The FontAwesome dependencies were already published as you know.

Remember I have to annonymize the code, so replace CUSTOMPROJECT....

https://gist.github.com/WillianGruber/40356e25b2b7612b30bd65edc04031a4
https://gist.github.com/WillianGruber/e4ccca236ffe7ac112993cd012f3d243
https://gist.github.com/WillianGruber/e1b7364434d33b7377405aa3e4aa30a7
https://gist.github.com/WillianGruber/64ace710ec9da07d91b453314058f45d

My ColorPicker is a placeholder until you release the official one.

**Comment by stsrki** [comment]
I must say it looks really great. Thank you for publishing :)

**Comment by WillianGruber** [comment]
It will be upgraded once you release **sliders** for % and so, and the **divider** to have a instant preview of a dummy page with all components. Check the TODOs :)

**Comment by WillianGruber** [comment]
Btw, thats why I needed all defaults for the parameters, to show them in the customizer page

**Comment by stsrki** [comment]
Hi @WillianGruber I've just tried to looking at this. The reason why padding and margin are not set to some default is actually done on purpose. Problem is that these options are too specific, meaning that each provider have a different spacing settings. I think the best it to leave it as it is as currently too much breaks if I go and set it.

**Comment by WillianGruber** [comment]
I see. So I'll exclude them from theme customizer for now. Thanks!

**Comment by WillianGruber** [comment]
I was looking at it. Normally buttons have X and Y margin/padding with different values.
Could you separate
Theme.ButtonOptions.Padding
Theme.ButtonOptions.Margin
into
Theme.ButtonOptions.PaddingX
Theme.ButtonOptions.PaddingY
Theme.ButtonOptions.MarginX
Theme.ButtonOptions.MarginY ?

About BoxShadowSize, changing it apparently affects nothing. There is a small shadow in my button but nothing changed. Maybe I'm looking at a button that it has no effect?

**Comment by stsrki** [comment]
Well actually, Theme.ButtonOptions.Padding and Theme.ButtonOptions.Margin are strings so you can define them as ".75rem 1rem". First value is Y and second is X.

**Comment by WillianGruber** [comment]
Perfect! Thank you! What about boxshadowsize?

**Comment by stsrki** [comment]
BoxShadowSize is visible on button focus. Here you see the example when I set it to `3rem`

![image](https://user-images.githubusercontent.com/900302/81326059-812fa200-9099-11ea-9d29-e8624b34efcc.png)

**Comment by WillianGruber** [comment]
Nice! Thanks!

**Comment by WillianGruber** [comment]
Just finished filling the defaults of those attributes for Material:
        public string ButtonBoxShadowSize { get; set; } = ".25rem";
        public string ButtonMargin { get; set; } = "0rem 0rem 0rem 0rem";
        public string ButtonPadding { get; set; } = ".6875rem 1rem .6875rem 1rem";
Thanks!
