### ISSUE TITLE
Implement Bar Color as a specific parameter in BarThemeOptions

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#567]
Hello,

Would it be possible to implement Bar Color as a specific parameter in BarThemeOptions? That class is actually empty (aside from inherited members). I think it would make sense since the Sidebar has their own parameters.

What do you think?
Thanks!

**Comment by stsrki** [comment]
I think it can be done.

**Comment by MitchellNZ** [comment]
@stsrki I will try include this one in my Bar refactor

**Comment by stsrki** [comment]
@MitchellNZ Yeah that would be great. If you need help just let me know.
