### ISSUE TITLE
Implement IsHorizontal field attribute as theme parameter

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#568]
Hello!

Could it be possible to implement the **IsHorizontal** attribute in the Field component in the theme?
Of course if explicitly specifying in a Field on a page, it would take precedence over the theme.

Thanks!

**Comment by stsrki** [comment]
You mean like a replacement for `<Inline>` component?

**Comment by WillianGruber** [comment]
No, I mean for the Inline Label:
https://github.com/stsrki/Blazorise/blob/9714bd56a01af6eea7ee7d0c0beb52670c6d2314/Tests/Blazorise.Demo/Pages/Tests/FormsPage.razor#L274

Sorry, just saw it is named **IsHorizontal**.

**Comment by stsrki** [comment]
Hmm. I can see the potential use case. You want to allow for users to switch the form layout from inline to ordinary.

**Comment by WillianGruber** [comment]
> Hmm. I can see the potential use case. You want to allow for users to switch the form layout from inline to ordinary.

That is correct.
I am building a page to allow users to highly customize the look and feel of the application.
My project's Theme object mirrors all attributes of Blazorise plus some other parameters. I'll include the animations from the other issue, for example.

**Comment by WillianGruber** [comment]
They also build some pages dinamically with treebuilder editor I built

**Comment by stsrki** [comment]
I will need to investigate this one. Horizontal property is a bit tricky because children of each `<Field>` must be notified every time the `Horizontal` property is changed. I cannot just inherit it from the some theme flag.

**Comment by stsrki** [comment]
OK. I think it can be done with a little of refactoring.

**Comment by WillianGruber** [comment]
Nice! But if it is difficult to propagate to children, it could work only when selecting other page in sidebar or so

**Comment by stsrki** [comment]
I need to refactor field component anyways as it's still using an old way of propagating to children. It's not a problem.

**Comment by stsrki** [comment]
This is a tricky. `Horizontal` Field requires use of `FieldBody` so when you switch `Horizontal` property it will not work as expected.

**Comment by WillianGruber** [comment]
Hi @stsrki , was this feature too cumbersome to be implemented? Or it didn't worth the effort?

**Comment by stsrki** [comment]
I was thinking about it and I came to the conclusion that it would require too much internal work and changes for little benefit on very small use cases. So I decided to focus my work on more requested features. Hope you can understand...
