### ISSUE TITLE
Using DataGrid RowRemoving Action

### ISSUE THREAD

**Issue by taylorjimbo** [stsrki/Blazorise#570]
I have having a time trying to implement a confirm message when the user attempts to delete a row. I have RowRemoving="@OnRowRemoving" in the DataGrid. 

Here is the code:

```
@inject IJSRuntime JsRuntime

 private Action<CancellableRowChange<CaseRec>> OnRowRemoving = o =>
    {
      
        o.Cancel = DeleteCase(o.Item.EmployeeName); // can't call non-static method

    };

    private bool DeleteCase(string id)  // If this is static, then I can't use JsRuntime
    {

        bool confirmed = JsRuntime.InvokeAsync<bool>("confirm", "Are you sure?").Result;
        if (confirmed)
        {
            return true;
            // Delete!
        }
        return false;
    }
```

**Comment by stsrki** [comment]
Thanks for the report @taylorjimbo 

I tried it on my side and the problem is that you're calling async code from synchronous method. To make it work I will have to convert RowRemoving to EventCallback that can supports async. 

It will be available in the next version.
