### ISSUE TITLE
Material dynamic sidebar only expands to one level

### ISSUE THREAD

**Issue by eschleinkofer** [stsrki/Blazorise#573]
Hi, I'm running into an unexpected behavior with the dynamic sidebar:

Expected: dynamic sidebar items should expand at any nesting level.
What happens: Dynamic sidebar items at nesting levels greater than 2 do not expand on click.

![blazorise-sidebar](https://user-images.githubusercontent.com/7085225/73853878-90375780-47ff-11ea-8be0-2683d7fa7f12.gif)

Is there any way around this?

Thanks

Code sample:

```
<Sidebar Data="@sidebarInfo" />

@code{
    Sidebar sidebar;

    SidebarInfo sidebarInfo = new SidebarInfo
    {
        Brand = new SidebarBrandInfo
        {
            Text = "Blazorise Demo"
        },
        Items = new List<SidebarItemInfo>
        {
            new SidebarItemInfo
            {
                Text = "Level 1",
                SubItems = new List<SidebarItemInfo>
                {
                    new SidebarItemInfo
                    {
                        Text = "Level 2",
                        SubItems = new List<SidebarItemInfo>
                        {
                            new SidebarItemInfo
                            {
                                To = "test",
                                Text ="Level 3"
                            }
                        }
                    }
                }
            }
        }
    };
}
```

**Comment by stsrki** [comment]
I just tried to create sidebar manually and it seems it works. Although the styles are a bit off, the collapse is working. 

It seems something is missing when sidebar is generated dynamically. Thanks for reporting.

**Comment by stsrki** [comment]
The sidebar is not maintained actively anymore and all work is now focused on the new vertical Bar component that much more features.
