### ISSUE TITLE
Adding @attributes to Blazorise.Components such as SelectList

### ISSUE THREAD

**Issue by ZiringTawfique** [stsrki/Blazorise#575]
I am trying to add custom html attributes to the SelectList element and it looks like there is no support for that for the components that exist in Blazorise.Components. 

When I add  "@attributes" to <SelectList /> I get the following error messages

 _Object of type 'Blazorise.Components.Autocomplete`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' does not have a property matching the name "custom-html-attribute"_

I want to be able to add my own html attributes to the html elements that the blazorise components create.

**Comment by WillianGruber** [comment]
Please paste here your code

**Comment by stsrki** [comment]
`SelectList` is created around the `SelectEdit` component and it doesn't have `Attributes` parameter. That's why it cannot pass it through to the `SelectEdit`.

It's fairly easy to it.

**Comment by ZiringTawfique** [comment]
Exactly! should I do a pull request or is it being added ?

**Comment by stsrki** [comment]
I will do the necessary changes.

**Comment by stsrki** [comment]
Done with #628
