### ISSUE TITLE
Add an event for Snackbar fading finished

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#576]
Hi, I'd like to implement a reaction after a Snackbar disappears. Could this be possible?

**Comment by stsrki** [comment]
Is should not be a problem. Going in the list.

**Comment by stsrki** [comment]
@WillianGruber What is the right naming for this event? I'm thinking one of

- Faded
- Closed
- Elapsed

**Comment by WillianGruber** [comment]
Probably Closed as most events are already named that way (Modal)?
Faded binds the event to the animation. If someday there is an option to close instantly instead of animated (Hi, theme customizer!), then naming Faded for an instantly closed Snackbar would be strange

**Comment by WillianGruber** [comment]
Tested and worked perfectly :)
