### ISSUE TITLE
SidebarLink Click event makes the sidebar item have expand icon

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#577]
I need to intercept the click in SidebarLink before navigation occurs.
I am trying with:
```
<SidebarItem>
    <SidebarLink Click="@(() => Navigation.NavigateTo(""))">
        <Icon Name="@FontAwesomeIcons.Home" Margin="Margin.Is3.FromRight" />Home
    </SidebarLink>
</SidebarItem>
```
Using the Click attribute instead of the To attribute.
When doing this, the expand icon appears:
![image](https://user-images.githubusercontent.com/56033692/73984691-fa432000-4917-11ea-9ea1-b941d08f73bc.png)
But this is not an item that have subitems.
Is this the right way of intercepting the click? Is the icon a bug in this case?

**Comment by WillianGruber** [comment]
Just explaining a little more, the Navigation object in that code is a custom object redirects to NavigationManager once some injected attributes are cleared.

**Comment by stsrki** [comment]
It'a a bug it seems. Probably because of this attributes `data-toggle="sidebar-collapse" aria-expanded="@IsShow"`.

**Comment by stsrki** [comment]
The right behavior would be to detect if the `SidebarItem` have any child items and then implement those attributes.

**Comment by stsrki** [comment]
Closing, since Sidebar is not maintained anymore in favor of new vertical Bar mode.
