### ISSUE TITLE
Checkbox UI not right in ClientSide

### ISSUE THREAD

**Issue by hutchcodes** [stsrki/Blazorise#581]
**Describe the bug**
Not sure why, but the HTML output by the CheckEdit component is different between SSB and CSB

**To Reproduce**
Put a CheckBox control on a page in both CSB and SSB

**Expected behavior**
Should be the same output

**Additional context**

On the server it outputs
```
<div class="custom-control custom-checkbox">
    <input id="0HLTBULKG48IU" type="checkbox" class="custom-control-input" style="" _bl_8d9a4372-dd4f-4a00-8a07-116e75f17f29=""><label class="custom-control-label" style="" for="0HLTBULKG48IU">
        IsActive
    </label>
    </div>

```
Client Side it outputs 
```
<input id="0HLTBUL5CAN46" type="checkbox" class="custom-control-input" style="" _bl_4="">
IsActive

```
The result is the actual checkbox is hidden.

**Comment by stsrki** [comment]
Maybe you forgot to add

```
app.Services
    .UseBootstrapProviders()
    .UseFontAwesomeIcons();
```

**Comment by hutchcodes** [comment]
I did. That's some amazing fast support for open source. Thanks so much.

**Comment by stsrki** [comment]
Trying my best :)
