### ISSUE TITLE
How to set initial value in Autocomplete

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#582]
I have an AutoComplete on a form that needs to be automatically filled in when a page is entered.

The autocomplete is defined as:

`    <Autocomplete Data="@policyNumbers" TextField="@(x => x)" ValueField="@(x => x)" SelectedValue="@selectedPolicyRef" SelectedValueChanged="@MySearchHandler" Placeholder="Enter Policy Ref..." />`

and I am trying to set the selected value automatically on component/page entry by:

```
  [Parameter]
        public string PolicyRef { get; set; }

        protected override void OnInitialized()
        {
            selectedPolicyRef = PolicyRef;
        }
```

However the SelectedValue of the autocomplete is not updated and the search handler does not execute.

How can I preset a value in the autocomplete box?

**Comment by stsrki** [comment]
You're setting the item object as autocomplete value. Only primitive types are supported, ints, strings, etc.

Try setting it like this
`ValueField="@(x => x.SomeValue)"`

**Comment by stsrki** [comment]
@robalexclark What is the data type of `policyNumbers` ?

**Comment by robalexclark** [comment]
policyNumbers is a list of strings:

protected IEnumerable<string> policyNumbers;

I’m just using the AutoComplete to select a single string value from a list of strings.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by stsrki** [comment]
I really don't know whats the problem. I have now tried to reproduce the bug and for me it works. Can you please create some small repro project where I can test? Or post entire code for your page?

**Comment by robalexclark** [comment]
As I was preparing a simplified project I too could not repeat the problem. Further investigation found that it was a race condition. I was setting the selectedPolicyRef in the OnInitialized method which is BEFORE the policyNumbers are retrieved from the db. If I set the selectedPolicy after the policyNumbers are available it works.
