### ISSUE TITLE
Material Provider - mandatory .css and .js in index.cshtml?

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#59]
Hello,

Sorry to bother you again. Reading the [documentation on the Material provider](https://blazorise.com/docs/usage/material/), its not clear to me what mandatory .css and .js files need to be included in the index.cshtml file. Specifically, whether the .bootstrap.css/js need included as well as the .material.css/js files.

See below my current index.cshtml inclusions. Are there any that MUST NOT be there if I want to use the Material provider and theme? Perhaps the documentation could be updated to make this a bit more explicit too...

material.min.css
blazorise.css
blazorise.bootstrap.css
blazorise.material.css
blazorise.sidebar.css
blazorise.snackbar.css
https://use.fontawesome.com/releases/v5.4.1/css/all.css
https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i|Roboto+Mono:300,400,700|Roboto+Slab:300,400,700
https://fonts.googleapis.com/icon?family=Material+Icons

blazorise.js
blazorise.bootstrap.js
blazorise.material.js
blazorise.charts.js
blazorise.sidebar.js

**Comment by stsrki** [comment]
The easiest solution is to add all of those files. The ones that you really need are those directly related to the nuget package that you have included in your project. But nothing is going to happen if you just add all of them. They're just a temporary solution until Razor team adds support for the static files.

You still need to have _bootstrap_, _material_, _fontawesome_ or any other js/css files that you use. Those are still mandatory.

I can fix documentation to be more specific about the meaning of these files, just to prevent the confusion in the future.

**Comment by aford22** [comment]
Perfect response. Thank you. This closes the issue.
