### ISSUE TITLE
Blazor 3.2 webAssembly Modals fills the full with of screen

### ISSUE THREAD

**Issue by rad765** [stsrki/Blazorise#591]
I think that with Blazor 3.2 WebAssebly, the Modals always fills the full with of the screen.

**Comment by stsrki** [comment]
Can you provide more information, possibly screenshot, or actual html structure of rendered modal?

I'm using a Blazor 3.2 also and on my side it works without any issue.

**Comment by rad765** [comment]
If you try the «Center Card»  in the attaced project I think you will see what I mean.

 

Great tool you are creating, I will by you a coffee someday.

 

René

 

Fra: Mladen Macanović <notifications@github.com> 
Sendt: onsdag 12. februar 2020 09:31
Til: stsrki/Blazorise <Blazorise@noreply.github.com>
Kopi: rad765 <rene@astaddupont.dk>; Author <author@noreply.github.com>
Emne: Re: [stsrki/Blazorise] Blazor 3.2 webAssembly Modals fills the full with of screen (#591)

 

Can you provide more information, possibly screenshot, or actual html structure of rendered modal?

I'm using a Blazor 3.2 also and on my side it works without any issue.

**Comment by stsrki** [comment]
I don't see any attachment. Might be because you replied over email..

**Comment by rad765** [comment]
Sorry, will this work?

[BlazorTest.zip](https://github.com/stsrki/Blazorise/files/4200675/BlazorTest.zip)

**Comment by stsrki** [comment]
OK I found the problem. You didn't finished Blazorise setup and it was rendering default html structure. 

Here is the full code that works:

```cs
namespace BlazorTest
{
    public class Program
    {
        public static async Task Main( string[] args )
        {
            var builder = WebAssemblyHostBuilder.CreateDefault( args );

            builder.Services
                .AddBlazorise( options =>
                {
                    options.ChangeTextOnKeyPress = true;
                } )
                .AddBootstrapProviders()
                .AddFontAwesomeIcons();

            builder.RootComponents.Add<App>( "app" );

            var host = builder.Build();

            host.Services
                .UseBootstrapProviders()
                .UseFontAwesomeIcons();

            await host.RunAsync();
        }
    }
}
```

**Comment by rad765** [comment]
👍 Yes - four lines missing.
Thnak you.

**Comment by stsrki** [comment]
No problem, glad I could help!
