### ISSUE TITLE
Loading Chart Data after long running task

### ISSUE THREAD

**Issue by intech-paul** [stsrki/Blazorise#592]
Hello

I am reading data from a database, and want to load the data to the chart when all the data is read.
I can't seem to get the datraread/load to chart sequence correct.

At the moment I have
   ```cs
 protected override async Task OnInitializedAsync()
    {
        await LoadChartData();         //read from db
    }
```

and

   ```cs
 protected override async Task OnAfterRenderAsync( bool firstRender )
    {
        if ( firstRender )
        {
            lineChart.AddDataSet( GetLineChartDataset(0));
            await lineChart.Update();
        }
    }
```
    
When I have the both OnAfterRenderAsync in, the OnInitializedAsync does not get called and the chart is drawn, and and  when I have OnAfterRenderAsync commented out, OnInitializedAsync does get called and the chart is not drawn.

What is the correct way to read data, and then populate the chart once the data is read ?

Thanks.

**Comment by stsrki** [comment]
Could be the same problem as #590

**Comment by stsrki** [comment]
The right way to initialize chart data is to do it on first render, in `OnAfterRenderAsync()`. The reason is that chart is using JavaScript to set chart data, and JSInterop can only be used AFTER the component is rendering.

I might do some fixes in chart component to not allow any calling to JS until the rendering is done. This should at least leave is without errors.

**Comment by intech-paul** [comment]
I found the issue was an exception in my loading code that stopped the chart from being displayed.
Once I put a try/catch block in and loaded the exception message to a string to be displayed I saw it. Also the chart would not display anything unless the AddLabel entries was called as well as the AddDataSet.

**Comment by stsrki** [comment]
So we can close this issue?
