### ISSUE TITLE
Need to add state suf at the bottom of the main window

### ISSUE THREAD

**Issue by 199621616** [stsrki/Blazorise#593]
Need to add state suf at the bottom of the main window.Can it be realized?

**Comment by stsrki** [comment]
Sorry can you explain better? What is as state suf?

**Comment by WillianGruber** [comment]
I think he refers to Chinese Government Tag:
https://en.wikipedia.org/wiki/ICP_license

**Comment by 199621616** [comment]
@stsrki   StatusBar

**Comment by stsrki** [comment]
StatusBar can have many meanings. Do you have any example or screenshot?

**Comment by stsrki** [comment]
This feature is too specific and everyone can create it on their own web app. So closing the ticket.
