### ISSUE TITLE
BarDropdown "caret" icon not rendering properly using Material provider and Razor components

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#60]
Hi there, me again! I am using the Material provider for Blazorise and Razor Components. I am rendering the same top menu bar as you do in your demo app. However, the "v" icon that toggles the dropdown menu is not rendering properly for me. 

Specifically, the following code:
`<BarDropdownToggle>More</BarDropdownToggle>`

Renders as shown in the attached "caret.png" file.
![caret](https://user-images.githubusercontent.com/11410374/55552028-237d9900-56d4-11e9-8497-612d123926ca.png)

I can see that the difference between my rendered page and the demo's rendered page is the inclusion of the following from _caret.scss, which I think is auto-included by bootstrap or material:

`.dropdown-toggle::after {
    border-top: .3em solid;
    border-right: .3em solid transparent;
    border-bottom: 0;
    border-left: .3em solid transparent;`

If I use Chrome debugger to disable "border-top: .3em solid;" then the "v" icon displays perfectly.
![caret2](https://user-images.githubusercontent.com/11410374/55552362-101efd80-56d5-11e9-8450-32e6799f0cef.png)

So the question is, do you know what I should do to fix this? Your demo's icon does not include anything from _caret.scss, which leads me to think it might be a Material mixin causing this... :-(

**Comment by stsrki** [comment]
Can you show me your index.cshtml code? Also the code in startup.cs where you setup the Blazorise.

**Comment by aford22** [comment]
Of course!!! index.cshtml and startup.cs follow:

within index.cshtml "head" tag:
```
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="~/css/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="~/css/blazorise.css" rel="stylesheet" />
    <link href="~/css/blazorise.material.css" rel="stylesheet" />
    <link href="~/css/blazorise.sidebar.css" rel="stylesheet" />
    <link href="~/css/demo.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i|Roboto+Mono:300,400,700|Roboto+Slab:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/css/material.min.css" rel="stylesheet">

    <script src="~/js/blazorise.js"></script>
    <script src="~/js/blazorise.bootstrap.js"></script>
    <script src="~/js/blazorise.material.js"></script>
    <script src="~/js/blazorise.sidebar.js"></script>
    <script src="~/js/demo.js"></script>
```

within "body" tag:
```
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="~/js/material.min.js"></script>

    <script src="_framework/components.server.js"></script>
```

and

ConfigureServices():
```
    services
              .AddBlazorise()
              .AddMaterialProviders()
              .AddMaterialIcons();
```

Configure():
```
     app.UseStaticFiles();
     app
         .UseMaterialProviders()
         .UseMaterialIcons();
     app.UseRouting(routes =>
     {
        routes.MapRazorPages();
        routes.MapComponentHub<App>("app");
    });
```

**Comment by stsrki** [comment]
You should remove first link, bootstrap.min.css

**Comment by aford22** [comment]
Score!!! Worked a treat. Thanks so much for your prompt attention.

Your Blazorise package is brilliant, by the way. One of the best packages I have seen in a long while. Well done!

**Comment by stsrki** [comment]
Glad I could help. And thank you for the praise :)
