### ISSUE TITLE
More customization for table / table header

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#600]
Would it be possible to add a parameter to customize the color of the table header? I know we have Theme="Theme.Light" and Theme="Theme.Dark", but it would be nicer to pick the color so it can merge with the color pallete from the customer.

In fewer words: Add a Color attribute to table header and retire the Theme attribute.

What do you think?

Thanks!

**Comment by stsrki** [comment]
Technically I don't see why it cannot be done. But I'm not sure if it needs to have colors like primary, secondary, etc. Maybe I missunderstood you?

What about having it controlled over theme parameters? That would make more sense.

**Comment by WillianGruber** [comment]
You are right, Theme parameters would fit perfectly, but if it is possible to also have Color attributes in the Header that overwrites the theme, even better. Color should accept the color enum and direct hex values overloaded :)

**Comment by WillianGruber** [comment]
Oh, and if possible to add to Theme:
IsStriped
IsHoverable
IsBordered
IsBorderless
IsNarrow

Still keeping them as attributes for forced values, that would make table totally customizable.

**Comment by stsrki** [comment]
Color variants have some meaning behind them, danger, warning, info... To have them on table header does not make sense.

**Comment by WillianGruber** [comment]
> Color variants have some meaning behind them, danger, warning, info... To have them on table header does not make sense.

Agreed.

**Comment by stsrki** [comment]
> Oh, and if possible to add to Theme:
> IsStriped
> IsHoverable
> IsBordered
> IsBorderless
> IsNarrow
> 
> Still keeping them as attributes for forced values, that would make table totally customizable.

This can be done.

**Comment by WillianGruber** [comment]
Btw, if you are changing this, what about EvenLineColor, OddLineColor, HoveredEvenLineColor and HoveredOddLineColor?
If this is implemented, we could have this kind of themes:
![image](https://user-images.githubusercontent.com/56033692/74687743-0058bc80-51b4-11ea-8d56-abc0f10e5bb9.png)

**Comment by stsrki** [comment]
I think this should not be a problem.

**Comment by stsrki** [comment]
Closing as #648 is the tracking ticket.
