### ISSUE TITLE
Validation on DataGridColumn

### ISSUE THREAD

**Issue by tarafdarmansour** [stsrki/Blazorise#601]
It's very wonderful if I can "Validate" data when I edit DataGrid data.
for example suppose this code :
`<DataGridColumn TItem="Employee" Field="@nameof( Employee.EMail )" Caption="EMail" Editable="true" />`
It's very good if I can have such property
`<DataGridColumn TItem="Employee" Field="@nameof( Employee.EMail )" Caption="EMail" Editable="true"  **Validator="@ValidationRule.IsEmail"** />`
or
`<DataGridColumn TItem="Employee" Field="@nameof( Employee.EMail )" Caption="EMail" Editable="true"  **Validator="@CustomValidationFunc"** />`
Thanks.

**Comment by stsrki** [comment]
Seems like a pretty good idea. I think I can do add it on the list.

**Comment by JoseAntonioIdener** [comment]
Hello!

What's the status of this? I think it is very important feature. Is there any workaround to validate edition on Datagrid?

Amazing library @stsrki !
