### ISSUE TITLE
Bug - Table border vertical lines not displaying

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#602]
**Describe the bug**
According to documentation at
https://blazorise.com/docs/components/table/#bordered
this table should have vertical lines:

```
        <Table IsBordered="true">
            <TableHeader>
                <TableRow>
                    <TableHeaderCell>ID</TableHeaderCell>
                    <TableHeaderCell>Name</TableHeaderCell>
                    <TableHeaderCell>Description</TableHeaderCell>
                    <TableHeaderCell>Created at</TableHeaderCell>
                    <TableHeaderCell>Changed at</TableHeaderCell>
                </TableRow>
            </TableHeader>
            <TableBody>
                @foreach (object obj in objs)
                {
                    <TableRow>
                        <TableRowHeader>@obj.Id</TableRowHeader>
                        <TableRowCell>@obj.Name</TableRowCell>
                        <TableRowCell>@obj.Description</TableRowCell>
                        <TableRowCell>@obj.CreationDateTime</TableRowCell>
                        <TableRowCell>@obj.ModificationDateTime</TableRowCell>
                    </TableRow>
                }
            </TableBody>
        </Table>
```
but this is the output:
![image](https://user-images.githubusercontent.com/56033692/74688626-d654c980-51b6-11ea-8aa5-51d92e6e92f7.png)

Am I missing something?

Also, there are 2 parameters, IsBordered and IsBorderless, which confuses me. Are these the common naming for borders? Would VerticalInnerBorder, VerticalOuterBorder, HorizontalInnerBorder and HorizontalOuterBorder be more easily understood?

**Comment by stsrki** [comment]
What version of Blazorise you have? It should work https://bootstrapdemo.blazorise.com/tests/tables

**Comment by WillianGruber** [comment]
0.8.8.1

**Comment by stsrki** [comment]
_Bordered_ and _Borderless_ are common names used by the bootstrap and other css frameworks. All I can think of is that you have some custom css that is overriding the table styles.

**Comment by WillianGruber** [comment]
Thanks, I'll check tomorrow with more details and post here what is happening

**Comment by stsrki** [comment]
Hi, any info on this?

**Comment by WillianGruber** [comment]
Sorry, I changed my focus to the workflow editor I am building and forgot about this.
I'm updating to 0.9. Soon will test this.

**Comment by WillianGruber** [comment]
I'm using:
```
<Table FullWidth="true" Hoverable="true" Bordered="true" Borderless="false" Narrow="true">
```
and this is what I get:
![image](https://user-images.githubusercontent.com/56033692/80000317-5f2c0200-8493-11ea-9593-614978d25315.png)

Still no vertical lines... am I doing it wrong?

**Comment by stsrki** [comment]
Tested and working in the latest 0.9.3 version.
