### ISSUE TITLE
[DataGrid] Themes

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#603]
Firstly, great library! 
Thank you very much for all the work you've put into this!

Currently, I haven't been able to find a way to theme the `DataGrid`.
I was just wondering if it would be possible for you to add the ability to provide an "out of the box" way to apply a theme?

Similar to the standard table component, I'm really wanting a dark table header.
However the `DataGrid Class="thead-dark"` is applying to the top level table, not the header.

Thanks!

**Comment by stsrki** [comment]
I see the problem and you're right, there should also be an option to handle header and other table styles. Until I implement this, as a workaround you can try setting some custom CSS targeting your table.

**Comment by stsrki** [comment]
I added bunch of new properties to handle class-names and styles for row, cell, header, footer and filter. It is available in v0.9.

**Comment by srs-adamr** [comment]
Is there plans to create a ThemeOptions for DataGrids as the rest of the components have? Or is the intended use to be to use custom CSS styling?

**Comment by srs-adamr** [comment]
> > Is there plans to create a ThemeOptions for DataGrids as the rest of the components have? Or is the intended use to be to use custom CSS styling?
> 
> The purpose of ThemeOptions is to adjust the app on a global app scale. From there, extensions like DataGrid should pick those options as part of the UI components. DataGrid still uses regular Blazorise components internally. Also, DataGrid is already quite customizable through its parameters so another theme provider would not be needed.

I assumed so as well, however, the global styles do not seem to be applied to the Pagination portion of DataGrid, unless we're doing something wrong :( 

![image](https://github.com/Megabit/Blazorise/assets/145586788/bafb773a-9f40-4be6-88b4-2a3795be574d)

**Comment by srs-adamr** [comment]
Seems I spoke to soon, I cannot seem to correct the background of the Pagination for DataGrid with any exposed options

![image](https://github.com/Megabit/Blazorise/assets/145586788/e7608057-5ab0-4e34-800d-1aa6638e4d91)

**Comment by stsrki** [comment]
It seems to me that `<Span Background="Background.Dark" TextColor="TextColor.Dark">` works but the `.page-item` element doesn't have any background color.

By inspecting the pagination in devtools I think you can make it by adding the padding to the span element. Try 

`<Span Background="Background.Dark" TextColor="TextColor.Dark" Style="padding: 0.5rem 0.75rem">`

**Comment by srs-adamr** [comment]
> Style="padding: 0.5rem 0.75rem"

Thanks for your help! Unfortunately there is a background color set by default on the page items
![image](https://github.com/Megabit/Blazorise/assets/145586788/6c801645-1a54-4998-9c5a-e965272e779b)

DevTools
![image](https://github.com/Megabit/Blazorise/assets/145586788/b4502b28-1491-4d57-bc4e-af2cc42341ce)
