### ISSUE TITLE
Custom validation error not showing

### ISSUE THREAD

**Issue by gijsstrik** [stsrki/Blazorise#604]
When using validation the custom message is not shown.
After a call to valLogin.ValidateAll(). 
In stead the 'normal' message is shown (the username field is required). 
Expected message 'Error'.

The username has a data annotation of [required] in the loginmodel.

```cshtml
<Validations @ref="valLogin" Mode="ValidationMode.Manual" Model="@loginModel">
    <Field IsHorizontal="true">
        <FieldLabel ColumnSize="ColumnSize.Is5">Username</FieldLabel>
        <FieldBody ColumnSize="ColumnSize.Is7">
            <Validation>
                <TextEdit @bind-Text="@loginModel.Username">
                    <Feedback>
                        <ValidationError>Error</ValidationError>
                    </Feedback>
                </TextEdit>
            </Validation>
        </FieldBody>
    </Field>
</Validations>
```

**Comment by stsrki** [comment]
When you have annotations like `[Required]` they will have it's own error messages and they will have precedence over Blazorise messages. This is by design.

One possible solution to this is to add some flag to validation that will override this behavior but I'm not sure if that' the right choice.

**Comment by gijsstrik** [comment]
Thank you for your speedy response!

Pitty: I would say if no errormessage is supplied use the annotations error message otherwise the supplied one.
I’ll have to think a way around that.

Is it also by design that if I close(hide) a modal window with a validation error.
The validation error is still there even if I clear the validation before opening the modal again like:
if (annotationsValidations != null) annotationsValidations.ClearAll();

If l call validateall after reopening the modal with the error corrected the error message is still there.

[cid:image001.png@01D5E702.568C6510]

Kind regards,
Gijs

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Mladen Macanović<mailto:notifications@github.com>
Verzonden: dinsdag 18 februari 2020 22:38
Aan: stsrki/Blazorise<mailto:Blazorise@noreply.github.com>
CC: gijsstrik<mailto:gijsstrik@msn.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [stsrki/Blazorise] Custom validation error not showing (#604)


When you have annotations like [Required] they will have it's own error messages and they will have precedence over Blazorise messages. This is by design.

One possible solution to this is to add some flag to validation that will override this behavior but I'm not sure if that' the right choice.

**Comment by stsrki** [comment]
The problem with modal is that it is part of page and only the _Visible_ property is used to control it's appearance. So when you show or hide it, it will not change states of other components. In this case the validation. As far as I know the ClearAll should be enough to reset them all.

**Comment by gijsstrik** [comment]
Dear Mladen,
But I call ClearAll and it doesn’t clear the error messages.
<Validations @ref="annotationsValidations" Mode="ValidationMode.Manual" Model="@email">
private void CloseEmailModal()
{
   annotationsValidations.ClearAll();
   emailModal.Hide();
}
I don’t know what I am doing wrong.

Thanks again!
Regards,
Gijs
Outlook for Android<https://aka.ms/ghei36> downloaden

**Comment by stsrki** [comment]
Without more code I cannot know or tell you much. My guess is because you are using data annotations you also must reset your model fields to their default values.

**Comment by gijsstrik** [comment]
Dear Mladen,

I wrote a test page (test.razor) (see attachement).

Open the modal.
Click Send.
Close modal.
Open the modal again.
Type in a subject.
Click Send => The error message ‘The Subject field is required.’ Is shown even with a subject ??

What am I missing.

Regards Gijs.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Mladen Macanović<mailto:notifications@github.com>
Verzonden: woensdag 19 februari 2020 09:43
Aan: stsrki/Blazorise<mailto:Blazorise@noreply.github.com>
CC: gijsstrik<mailto:gijsstrik@msn.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [stsrki/Blazorise] Custom validation error not showing (#604)


Without more code I cannot know or tell you much. My guess is because you are using data annotations you also must reset your model fields to their default values.

**Comment by stsrki** [comment]
Sorry I don't see any attachment? Can you post it with GitHub instead of email reply? tnx

**Comment by gijsstrik** [comment]
[Test.zip](https://github.com/stsrki/Blazorise/files/4224293/Test.zip)

**Comment by stsrki** [comment]
I found your problem.

First, you had `@if ( email != null )` in render tree. That means nothing bellow will be rendered until email exists. Which means every time you do `email = new` everything will be re-rendered also.

Second, I initialized `EmailDetails email = new EmailDetails();` only once so it always stays the same. And I removed the part `@if ( email != null )`.

Third I set the model fields like this:

```cs
email.EmailTo = "test@test.nl";
email.EmailFrom = "test@test.nl";
email.Subject = "";
email.Body = "Testing";
```
Full example bellow:

```cshtml
@using System.ComponentModel.DataAnnotations

<h3>Test</h3>

<Button Clicked="@(() => ShowEmailModal())">Show Modal</Button>

<Modal @ref="emailModal">
    <ModalContent Size="ModalSize.Large">
        <ModalHeader>
            <ModalTitle>Email</ModalTitle>
            <CloseButton Clicked="@(() => emailModal.Hide())" />
        </ModalHeader>
        <ModalBody Style="min-height: 400px" MaxHeight="50">
            <Validations @ref="annotationsValidations" Mode="ValidationMode.Manual" Model="@email">
                <Field IsHorizontal="true">
                    <FieldLabel ColumnSize="ColumnSize.Is2">Email To</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.Is10">
                        <Validation>
                            <TextEdit @bind-Text="@email.EmailTo">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </TextEdit>
                        </Validation>
                    </FieldBody>
                </Field>
                <Field IsHorizontal="true">
                    <FieldLabel ColumnSize="ColumnSize.Is2">Email From</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.Is10">
                        <Validation>
                            <TextEdit @bind-Text="@email.EmailFrom">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </TextEdit>
                        </Validation>
                    </FieldBody>
                </Field>
                <Field IsHorizontal="true">
                    <FieldLabel ColumnSize="ColumnSize.Is2">Subject</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.Is10">
                        <Validation>
                            <TextEdit @bind-Text="@email.Subject">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </TextEdit>
                        </Validation>
                    </FieldBody>
                </Field>
                <Field IsHorizontal="true">
                    <FieldLabel ColumnSize="ColumnSize.Is2">Body</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.Is10">
                        <Validation>
                            <MemoEdit @bind-Text="@email.Body" Rows="8">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </MemoEdit>
                        </Validation>
                    </FieldBody>
                </Field>
            </Validations>
        </ModalBody>
        <ModalFooter>
            <Button PreventDefaultOnSubmit="true" Color="Color.Secondary" Clicked="@(() => SendEmail())">Send</Button>
            <Button PreventDefaultOnSubmit="true" Color="Color.Secondary" Clicked="@(() => CloseEmailModal())">Close</Button>
        </ModalFooter>
    </ModalContent>
</Modal>

@code {
    Modal emailModal;
    EmailDetails email = new EmailDetails();
    Validations annotationsValidations;

    protected void SendEmail()
    {
        if ( annotationsValidations.ValidateAll() )
        {
            annotationsValidations.ClearAll();
            // Do Stuff
            emailModal.Hide();
        }
    }


    private void CloseEmailModal()
    {
        annotationsValidations.ClearAll();
        emailModal.Hide();
    }

    protected void ShowEmailModal()
    {
        if ( annotationsValidations != null )
            annotationsValidations.ClearAll();

        email.EmailTo = "test@test.nl";
        email.EmailFrom = "test@test.nl";
        email.Subject = "";
        email.Body = "Testing";

        emailModal.Show();
    }

    public class EmailDetails
    {
        [Display( Name = "Email To" )]
        [EmailAddress( ErrorMessage = "Invalid email." )]
        [Required]
        public string EmailTo { get; set; }
        [Display( Name = "Email From" )]
        [EmailAddress( ErrorMessage = "Invalid email." )]
        [Required]
        public string EmailFrom { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Body { get; set; }
    }
}

```

**Comment by gijsstrik** [comment]
Thanks very much.

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________
