### ISSUE TITLE
Set DataColumn visibility to true/false but still allow popup/form to show field for editing

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#605]
Is it possible to allow items to be editable on a popup but not visible in the grid. 

If not then do we have to write our own editor in a Modal popup and Show() the popup from a New or Edit button click?

**Comment by stsrki** [comment]
Not at the moment. You can only make column editable.

Do you have any use case why you want this behavior so I can understand it better and maybe consider it for the future?

**Comment by robalexclark** [comment]
I have a table with about 15 fields that need to be updated through the UI, Some of these fields are 50 chars long which means that all these fields will not fit on the screen. I require only 5 short fields to be visible on the screen so the user can identify the row to edit and then provide values for all 15 fields,

**Comment by WillianGruber** [comment]
> I have a table with about 15 fields that need to be updated through the UI, Some of these fields are 50 chars long which means that all these fields will not fit on the screen. I require only 5 short fields to be visible on the screen so the user can identify the row to edit and then provide values for all 15 fields,

I'll need that in the future too.

**Comment by stsrki** [comment]
In that case I will schedule this feature for 0.9.1

**Comment by robalexclark** [comment]
There is a pull request regarding this functionality for your consideration:

https://github.com/stsrki/Blazorise/pull/615

**Comment by stsrki** [comment]
Done with #730
