### ISSUE TITLE
Update Step 4a of Documentation and readme.md for new WebAssembly template

### ISSUE THREAD

**Issue by SandroRiz** [stsrki/Blazorise#606]
With the new Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1  there is anymore the startup.cs file.

Please update how to register the services in the Program.cs with the new builder object

**Comment by stsrki** [comment]
Hi @SandroRiz , I'm aware of the change but I'm currently on the business trip so I have no much time to update it. If you could do the PR I would gladly merge it. tnx

**Comment by SandroRiz** [comment]
You’re too fast :-)

 

Well Done.

 

Sandro
