### ISSUE TITLE
Make BaseAutocomplete.CurrentSearch public accessible.

### ISSUE THREAD

**Issue by Stefan6440** [stsrki/Blazorise#612]
First I want to say thank You for Blazorise - great work!   👍  🥇

I am using AutoComplete and can't get the current value of the textbox, when the user types in a value using the keyboard.

The purphose for this change is I want to save the new value, and insert it in the Autocomplete-dropdown list.

Something like :   
public string GetCurrentSearch()  
{
     return CurrentSearch;
}

**Comment by stsrki** [comment]
So basically, you want to have `TextChanged`?

**Comment by Stefan6440** [comment]
Yes, I think an event will be great.
In my case a simple Get-function like above GetCurrentSearch() will do the job - since the function will be called when user clicks a button.

**Comment by stsrki** [comment]
Not sure if I understood you completely. Please fix me if I'm wrong. 

Let's say we have colors in autocomplete.

- `Red`
- `Green`
- `Blue`
- `Yellow`

1. User starts to write in autocomplete, key **g**, key **r**, and then key **e**
2. For each key-press `TextChanged` will be raised
  - `TextChanged` > **g**
  - `TextChanged` > **gr**
  - `TextChanged` > **gre**

3. Now you have **gre** entered and you want that value to use somewhere?

**Comment by Stefan6440** [comment]
Yes exactly.   Now the value **gre** will be in the property CurrentSearch. But since CurrentSearch is a private member I cant reach it from code. 

If the user types Brown , then the GetCurrentSearch() (or TextChanged, if you prefer TextChanged-event) will return Brown.
-------------------------------
- Just to explain (not a part of the pull request) :  My intention is then to add Brown in the dropdown, next time the user opens the page.  
I am aware of Autocomplete is not designed to be a TextEdit, but I think above changes will add value/flexibility to the component, since it will be possible to accept user-input and save them for later use. 
-------------------------------

**Comment by stsrki** [comment]
I think it shouldn't be a problem to implement.

**Comment by Stefan6440** [comment]
Thanks, it looks good with the SearchChanged event, I checked the code, it's spot on.
