### ISSUE TITLE
DataGrid Row Double click

### ISSUE THREAD

**Issue by vmakharashvili** [stsrki/Blazorise#617]
I need to make double click on DataGrid row. I'm trying to access to table tr tag to bind dblClick event, but it's not possible. Please add this feature to the DataGrid component.

**Comment by stsrki** [comment]
Do you have a use-case for this feature? Also a proposal API would be great! tnx

**Comment by vmakharashvili** [comment]
We had a table which had double-click event on the row. The table looked like this:
`<Table IsHoverable="true" IsBordered="true">
        <TableHeader ThemeContrast="ThemeContrast.Light">
            <TableRow>
                <TableHeaderCell Class="text-left">Name</TableHeaderCell>
                <TableHeaderCell Class="text-left">IBAN</TableHeaderCell>
                <TableHeaderCell Class="text-left">Currency</TableHeaderCell>
                <TableHeaderCell Class="text-left">Balance</TableHeaderCell>
                <TableHeaderCell Class="text-left">Priority</TableHeaderCell>
                <TableHeaderCell Class="text-left">Id</TableHeaderCell>
                <Blazorise.TableHeaderCell></Blazorise.TableHeaderCell>
            </TableRow>
        </TableHeader>
        <TableBody>
            @foreach (var account in _accounts)
            {
                <tr @ondblclick="(() => OnAccountRowClick(account))">
                    <TableRowCell Class="text-left">@account.Name</TableRowCell>
                    <TableRowCell Class="text-left">@account.AccountNumber</TableRowCell>
                    <TableRowCell Class="text-left">@account.Ccy</TableRowCell>
                    <TableRowCell Class="text-right">@account.Balance.ToString("N")</TableRowCell>
                    <TableRowCell Class="text-left">@account.Priority</TableRowCell>
                    <TableRowCell Class="text-left">@account.Id</TableRowCell>
                    <TableRowCell Class="text-center">
                        <Button Color="Color.Primary" IsOutline="true" @onclick="(() => OnAccountRowClick(account))">
                            <i class="oi oi-eye" aria-hidden="true"></i>
                        </Button>
                    </TableRowCell>
                </tr>
            }
        </TableBody>
    </Table>`
There was a double-click on table row. 
For other reason we changed the table into DataGrid. Here we just have DataGridColumn. There is no notion about table-row. How can I make table row click events in DataGrid?

**Comment by stsrki** [comment]
I understand now. For now there is no way to do this. If you're willing to try new 0.9 **preview 2** I can try to add this feature today before the release.

**Comment by stsrki** [comment]
I have added new section to the readme about how to connect to preview feed Blazorise https://github.com/stsrki/Blazorise#try-preview

**Comment by vmakharashvili** [comment]
I tried it. It works fine.

**Thanks you very much.**
