### ISSUE TITLE
[DataGrid] [Material] Issue with DetailRowTemplate in Editable DataGrid

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#622]
**Describe the bug**
I'm using Material Design UI and I have setup an editable _DataGrid_ that also has a _DetailRowTemplate_.

The issue I get is that when the row is selected and the _DetailRowTemplate_ is added, an extra empty **_<td>_** is being added.
The backing control for this (**__DataGridDetailRow.razor_**) has the following code which is causing me a problem:

`        if ( location == "end" && ParentDataGrid.Editable )
        {
            <TableRowCell>
            </TableRowCell>
        }`

This seemed to work fine when I was using Bootstrap, but now I'm using Material, it is causing the whole table to be push inwards (please see screenshots below).

**To Reproduce**
1. Use Material Design
2. Create an editable _DataGrid_ with a _DetailRowTemplate_
3. Select a row to expand the data grid detail row
4. See the issue

**Expected behavior**
I think this was added to make Bootstrap look as intended, but it seems to be breaking Material.

**Screenshots**
Before selection:
![image](https://user-images.githubusercontent.com/6387861/75599661-e43a1100-5b0b-11ea-9306-c4dc73e7d649.png)

After selection:
![image](https://user-images.githubusercontent.com/6387861/75599651-d71d2200-5b0b-11ea-8a7d-71cb80b5c4b7.png)

**Comment by stsrki** [comment]
Hi @MitchellNZ, sorry for not answering before. It seems this is a bug indeed.

In the meantime you can try to use an updated version of material from https://github.com/djibe/material. The guy who maintain it is almost done but I think it's already safe to use.

**Comment by MitchellNZ** [comment]
@stsrki No worries.

Thanks for the workaround suggestion.
However, I tried importing the CSS from that library and it makes my UI look very different to the official _Daemonite material_ library.
Is this going to be what you use in the next release?

Also, it doesn't fix the issue, unfortunately!
But I'm in no rush for a workaround.

**Comment by stsrki** [comment]
Yes I plan to use this one after it's finished. Unfortunately the original Daemonite material is not actively maintained and as far as I know there is no better alternative.
