### ISSUE TITLE
Following the tutorial for installation ends up removing the sidebar blazor comes with.

### ISSUE THREAD

**Issue by Syltis** [stsrki/Blazorise#626]
If you start a new server-side Blazor project (.Net Core 3.1), and follow the tutorial to add server-side Blazorise, you will notice that the sidebar that Blazor came with will be gone. It can be replaced with Blazorise components, but this should maybe be adressed in the tutorial. It is sure to put of a lot of new users that they're sidebar is gone without any clues as to why.

1. Create new server-side Blazor project
2. Install Blazorise
3. Launch application

**Comment by Syltis** [comment]
The sidebar still works on lower breakpoints though. Pretty weird.

**Comment by stsrki** [comment]
The reason for this is that default project templates for Blazor are changing the bootstrap class styles. This is the known issue and I always advise to remove all the default styles and add the Blazorise components. 

But I agree it should be noted somewhere in the documentation.

**Comment by Syltis** [comment]
Thank you for the response. That makes sense, though I'm sure it has an easy fix, I just can't find it. As mentioned, the sidebar works fine except for on large breakpoints.

Mentioning it in the docu would be great, but I think a fix should also be added. I really like Blazorise, and it would be sad if new users got deterred because of something like this.

I will try to figure out how to fix it,please let me know if you have any ideas.

**Comment by pekatete** [comment]
"**_remove all the default styles_**" - what does that entail? Simply commenting out the links in _Host.cshtml or is it more involved that that? (ps that did not work for me!) A good description in the instructions would be nice.

**Comment by stsrki** [comment]
@pekatete You can find `site.css` in the `wwwroot/css`. If you look at the content of that file you will see that some of bootstrap classes like `navbar-toggler`, `nav-item`, etc. are having their styles changed. Also there are some media breaking points that can also influence app behavior. 

I think this is good enough for basic Blazor "hello world" apps. But as soon as you start to change anything and start building your custom web, you will come to conclusion that it's easier to remove everything and start from scratch.

**Comment by pekatete** [comment]
@stsrki - thanks and yes I get it that starting from scratch is the way to go. I did try commenting out the site.css but, if I recall correctly, that broke even more stuff! I'll keep an eye out for the fix as for now I chose to work on other areas.

**Comment by Syltis** [comment]
Closing this, will update with quickfix to the missing sidebar if I figure it out.
