### ISSUE TITLE
Tables questions: Paginator and sort icons

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#63]
Hello,

I have a couple of questions about Blazor tables:

1) Is there a recommended method of connecting your Blazor Tables to the Paginator element ? I.e. so that the Paginator knows how many table items there are, and clicking on the Paginator causes the table rows displayed to change to that page

2) Again, is there a recommended way to implement sorting on the table headers? Such that when I click a table header an arrow icon is displayed and the table gets sorted by that column?

Just wanted to know if you had tackled these yourself and had a recommended way of doing them...

**Comment by stsrki** [comment]
1. There's no connection between table and pagination components. The idea behind Blazorise components is they need to be as generic and as flexible enough so that developers can use them however they choose. That's why there is no preferred way of doing this.

2. You will have to manually wire up PaginationItem and PaginationLink eg

**SimplePagination.cshtml** (copy/paste from one of my oldest project)
```
<Pagination Alignment="@Alignment" Background="@Background">
    @if ( IsFirstPage )
    {
        <PaginationItem IsActive="@(CurrentPage == 1)">
            <PaginationLink Clicked="@HandlePaginationItemClick" Page="1">
                First
            </PaginationLink>
        </PaginationItem>
    }
    @for ( int i = 1; i <= LastPage; ++i )
    {
        var pageNum = i;
        <PaginationItem IsActive="@(CurrentPage == pageNum)">
            <PaginationLink Clicked="@HandlePaginationItemClick" Page="@pageNum.ToString()">
                @pageNum
            </PaginationLink>
        </PaginationItem>
    }
    @if ( IsLastPage )
    {
        <PaginationItem IsActive="@(CurrentPage == LastPage)">
            <PaginationLink Clicked="@HandlePaginationItemClick" Page="@LastPage.ToString()">
                Last
            </PaginationLink>
        </PaginationItem>
    }
</Pagination>
@functions{
    [Parameter] Alignment Alignment { get; set; } = Alignment.None;

    [Parameter] Background Background { get; set; } = Background.None;

    [Parameter] int TotalItems { get; set; }

    [Parameter] int PageSize { get; set; } = 10;

    [Parameter] bool IsFirstPage { get; set; }

    [Parameter] bool IsLastPage { get; set; }

    [Parameter]
    int CurrentPage
    {
        get { return currentPage; }
        set
        {
            if ( currentPage == value )
                return;

            currentPage = value;

            PageChanged?.Invoke( new PageChangedEventArgs
            {
                Page = currentPage,
                Offset = ( currentPage - 1 ) * PageSize,
                Limit = PageSize,
            } );

            StateHasChanged();
        }
    }

    [Parameter] Action<PageChangedEventArgs> PageChanged { get; set; }

    int currentPage = 1;

    private int LastPage
    {
        get
        {
            return Math.Max( (int)Math.Ceiling( TotalItems / (double)PageSize ), 1 );
        }
    }

    void HandlePaginationItemClick( string page )
    {
        CurrentPage = int.Parse( page );
    }

    public void SetCurrentPage( int page )
    {
        CurrentPage = page;
    }

    public void SetPageSize( int pageSize )
    {
        PageSize = pageSize;

        CurrentPage = 1;
    }
}
```

However, I'm planning to create new **Blazorise.Grid** extension, just like there is Chart and Sidebar nuget extension package. The plan is to have sorting for columns, inline and popup editing, pagination etc. Basically all of the "grid" features while internally it will use basic Blazorise components.

**Comment by aford22** [comment]
Thank you for the source code... will give it a try!

And #thumbsup to the Blazorise.Grid idea. Sounds ideal and something I could help you test when you are ready...

**Comment by ikkyGH** [comment]
I would also find this super useful.  Thanks for all the work so far!!
