### ISSUE TITLE
DateEdit @bind-Date not working with non-nullable dates

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#630]
I am trying to use data annotations to validate that a date is not in the future (I'm using a custom data annotation).

However the following will not compile:

  ```
<Field>
                        <FieldLabel>Date Allocated</FieldLabel>
                        <Validation>
                            <DateEdit @bind-Date="@allocation.DateAllocated">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </DateEdit>
                        </Validation>
                    </Field>
```

Resulting in the following error:
Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.DateTime>' to 'Microsoft.AspNetCore.Components.EventCallback'

Only Nullable<DateTime> types will work with DateEdit @bind-Date. I can use the Date=".." DateChanged="..." syntax, but this does not work with data annotations!

**Comment by robalexclark** [comment]
Seems like I have a similar problem with SelectList when using @bind-SelectedValue:

                          `  <SelectList Data="@fatesList" TextField="@((item) => item?.FateName)" ValueField="@((item) => item?.FateId)" @bind-SelectedValue="@allocation.FateId" >`

Doesn't seem to work with <int> as a selected value:
Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<int>' to 'Microsoft.AspNetCore.Components.EventCallback'

**Comment by stsrki** [comment]
`DateEdit` only accepts nullable `DateTime?` type. I will need to convert it to generic component to make it work. Since this is going to be breaking change I will see if it's going to be for 0.9 or 0.9.1.

Regarding the `SelectList`. Here the value is of `object` type and Blazor cannot convert it to int when you use `@bind-`. You need to use `SelectedValue` and `SelectedValueChanged` to get and set the value.

**Comment by robalexclark** [comment]
Just to clarify: The @date-bind syntax only appears to work with Nullable<DateTime>, the longer Date="@.." syntax works with both.

I will probably fall back to manual validation for these entities.

**Comment by stsrki** [comment]
The problem with `@bind-Date` is that Blazor expects the same type as in the specified field.
