### ISSUE TITLE
Simple example with layout?

### ISSUE THREAD

**Issue by vindberg** [stsrki/Blazorise#631]
Hi all, great work on this. Is there a simple example with layout (like the dashboard) that can be used as a starting template for a new project?

It looks like I can extrapolate it from the current code but its not apparent what parts I need for example the Material template?

Thanks.
Anders

**Comment by robalexclark** [comment]
I would clone/download the code and look at the Blazorise.Demo project. In the Pages/Tests folder you will find the source code that drives the Blazorise Demo at blazorise.com

**Comment by stsrki** [comment]
@vindberg The best option is to look at the demo app, as @robalexclark already mentioned. I have plans to create templates but it's not going to be done any time soon.

**Comment by vindberg** [comment]
Thanks guys, I will copy the code from the demo project into a new.

**Comment by xpoajith** [comment]
what is the reference for LayoutSiderContent tag

**Comment by stsrki** [comment]
> what is the reference for LayoutSiderContent tag, trying to resolve the below error, can someone help. ![image](https://user-images.githubusercontent.com/28868045/156693145-ba9cc41c-93b7-4e7d-887b-636eef672bcf.png)

Seems to me that is the VisualStudio IntelliSense error. It tends to happen from time to time. For me, it helps to close and reopen VS.

**Comment by xpoajith** [comment]
sorry, I tried multiple times but got the same error.

**Comment by stsrki** [comment]
That's an old version. Why you don't use the newer version? To tell you the truth I don't think we had the Layout component before v0.9.x.

**Comment by xpoajith** [comment]
The application was developed in .net core 3.1, Layout component is not allowing me to install  > 0.8.8.4 NuGet version. Throwing compatibility error.
Thanks for the response I will try to upgrade the app.

**Comment by stsrki** [comment]
You will need to cover many migration steps. Go through our release notes and update where necessary. Startring from oldest to newest.

- https://v094.blazorise.com/news/ (our old documentation)
- https://blazorise.com/news
