### ISSUE TITLE
DataGridColumn Filter Template

### ISSUE THREAD

**Issue by vmakharashvili** [stsrki/Blazorise#633]
In DataGrid there is a very useful filter textboxes. I use them really well as server-side filtering. However, there is an issue: this filter is only string type and when we need int, Date, multiple-choice or other type filters, this filter becomes useless.

I think there will be good idea to have a filter-template inside DataGridColumn. This will give us ability to have our own custom filter which will be super-useful.

For example:
```cshtml
<DataGrid TItem="Customer" Data="@_customers" PageSize="CustomerService.PageState[Page.Customers].PageSize" Filterable="true"
          RowDoubleClicked="((e) => OnCustomerRowClick((e.Item as Customer)))" Narrow="true" Hoverable="true"
          ReadData="(e => ReadData(e))">
    <DataGridColumn TItem="Customer" Field="@nameof(Customer.Id)" Caption="Id" Sortable="true" Filterable="true" Filter="@Filter("Id")">
        <DataGridColumnFilterTemplate>
            ... some code
        </DataGridColumnFilterTemplate>
    </DataGridColumn>
    </DataGridNumericColumn>
</DataGrid>
```

**Comment by stsrki** [comment]
I tried that already #331

The problem is in how Blazor works when building the render-tree and I was unable to do anything. To make this work I will either have to rebuild DataGrid internals or do it something like this #394 

I will have to decide after I have more time to investigate.

**Comment by vmakharashvili** [comment]
I downloaded the source and created the FilterTemplate in my local computer. It works fine.
How can I contribute to the source code?
