### ISSUE TITLE
How to databind a dropdown component?

### ISSUE THREAD

**Issue by vindberg** [stsrki/Blazorise#634]
**Is your feature request related to a problem? Please describe.**
I am trying to add a Dropdown component with a dynamic list of DropdownItem to select from. The list is retrieved from the service layer.

**Describe the solution you'd like**
Be able to define the data source of the component.

### Additional context
I could do my own foreach loop, but isn't that what the component does for me?

Thanks again. Much appreciated.

**Comment by stsrki** [comment]
For this you can use `DropdownList` component.

https://blazorise.com/docs/extensions/dropdownlist/

**Comment by vindberg** [comment]
Thanks, am using that now. Maybe a link from the "Dropdown" component to this would be helpful.

Cheers.
