### ISSUE TITLE
Tooltip stacks under the rest of the application.

### ISSUE THREAD

**Issue by Syltis** [stsrki/Blazorise#636]
Hi! I hope you are well.

When using the Tooltip component on th-elements in a vanilla Bootstrap table, the tooltip stacks under the rest of the page. I have attempted to set its CSS position and z-index, but nothing seems to stack it on top. 

![image](https://user-images.githubusercontent.com/13823334/76419050-ff284300-639f-11ea-847f-eaa50a6694ee.png)

I would love to share the entire repo, but it's not open source. Nonetheless, here is the sorrounding code.
```
<div class="table-responsive">
                    <table class="table table-hover table-bordered table-sm">
                        <thead>
                            <tr>
                                @foreach (var property in PipesCopy.ElementAt<BasicPipeInfoResponse>(0).GetType().GetProperties())
                                {
                                    var tooltipString = property.Name + " explanation coming";
                                    <th>
                                        <Tooltip Text="@tooltipString" Class="table-th-tooltip" Placement="Placement.Top">
                                            <span class="sort-link" @onclick='(() => SortTable(property.Name))'>
                                                @AddSpacesToSentence(property.Name)
                                            </span>
                                            <span class="fa fa-sort"></span>
                                        </Tooltip>
                                    </th>
                                }
                                <th>
                                    <span>PDF</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            ....
                        </tbody>
                    </table>
                </div>
```
Would love to be able to use your tooltip, as it looks good.

**Comment by stsrki** [comment]
I'm trying to reproduce it but for me it seems it works. Even for vanilla html elements. Maybe I have misunderstood the original problem!?

**Comment by Syltis** [comment]
Thank you for the response. 

Thats to bad, I'm sorry I am not able to share the repo. 
The issue is that the tooltip stack under the borders of the table. As seen in the photo, the upper part of the tooltip is hidden.

![image](https://user-images.githubusercontent.com/13823334/76554482-40028380-6496-11ea-9f76-f686109962b6.png)

Here you see that the whole tooltip is hidden, except for the arrow. Still if you are not able to reproduce it, it is probably an error on my part. I will try to find the error. I will close the issue soon if I don't.

**Comment by pekatete** [comment]
Maybe you need to put together a sample that replicates the issue you are having. That'll save everyone a bundle of time.

**Comment by stsrki** [comment]
I agree with @pekatete. A small sample application will help us find the problem.

**Comment by Syltis** [comment]
I'm already doing that. Will have to finish it tomorrow though.

**Comment by keg247** [comment]
@Syltis In your case, the element containing the tooltip (looks like th) might have overflow set to hidden.  If you can set it to visible, that might solve the issue.  I had the same issue in a table cell and once I changed overflow to visible, the issue was solved (in my case it was ok for overflow to be visible).

**Comment by stsrki** [comment]
I didn't hear from you for awhile. Have you managed to find the solution?

**Comment by Syltis** [comment]
@keg247 Thank you for the input. Setting overflow to visible on the th did not solve it, but when testing I found that setting it on the table-responsive element solved the issue. 

@stsrki Please excuse my late response, I had to postpone my testing and prioritize other parts of the project. Nevertheless I was able to find the solution from the above suggestion. Thank you for the help and good luck on further development. I am super happy with Blazorise and it's capabilitites.
