### ISSUE TITLE
DataGridCheckBoxColumn - not implemented?

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#640]
Is the DataGridCheckBoxColumn ColumnType implemented? Its mentioned as a column type in the docs, and I was expecting it to render as a checkbox/tick column in a datagrid. But it just displays true/false. I can't find any real checkbox implementation in the codebase either...

**Comment by stsrki** [comment]
Not sure why it will not work. 

Implementation is here: https://github.com/stsrki/Blazorise/blob/d3b80fb38a9dc0362bfde32aa5c7a82a2b0aa8de/Source/Extensions/Blazorise.DataGrid/_DataGridCellEdit.razor#L44

**Comment by robalexclark** [comment]
Using the Blazorise solution, if I go to line 141 of DataGridPage.razor and uncomment and remove the display template so the Check Column is:

`   <DataGridCheckColumn TItem="Employee" Field="@nameof(Employee.IsActive)" Caption="Active" Editable="true" Filterable="false">
                        </DataGridCheckColumn>`

On running the Blazorise.Demo.Bootstrap.RC project the IsActive field is rendered as "True" or "False", not as a checkbox.

**Comment by stsrki** [comment]
I have just checked and this is by design actually. True/False is the boolean result when it's converted `ToString()`. If you want to instead display an actual checkbox you can use `<DisplayTemplate>`.

```cshtml
<DataGridCheckColumn TItem="Employee" Field="@nameof(Employee.IsActive)" Caption="Active" Editable="true" Filterable="false">
    <DisplayTemplate>
        <CheckEdit TValue="bool" Checked="@context.IsActive" />
    </DisplayTemplate>
</DataGridCheckColumn>
```

**Comment by robalexclark** [comment]
Your explanation does help me resolve my issue - thanks, although I had to add onclick="return false;" to make it readonly in the grid

Could you "bake in" a default DisplayTemplate for each type of Column (that can then be overridden with a custom DisplayTemplate?) e.g. for DataGridCheckColumn default to a checkbox.

**Comment by stsrki** [comment]
It's hard to add default template for every column because not everyone can agree what is the "right way". That's why I just convert every value to string as it's the easiest thing for me. And if anyone wants something else that's what DisplayTemplate is used for.
