### ISSUE TITLE
Theme ColorOptions Primary also changes breadcrumb link color

### ISSUE THREAD

**Issue by vindberg** [stsrki/Blazorise#646]
**Describe the bug**
When settings the theme color like this:

```
    private Theme theme = new Theme
    {
        ColorOptions = new ThemeColorOptions
        {
            Primary = "#FFFFFF",
        }
```
it makes the link color of breadcrumb items "white" which makes them unreadable.

**Screenshots**
![breadcrumb](https://user-images.githubusercontent.com/225174/76749721-4423ef00-677d-11ea-99d7-9ae6b91e77ff.png)

**Additional context**

**Comment by stsrki** [comment]
It's a bug it seems. I have set it to primary color instead of adding the color to `ThemeBreadcrumbOptions`. Thanks for noting!
