### ISSUE TITLE
Change a button's disabled properties

### ISSUE THREAD

**Issue by danlbb** [stsrki/Blazorise#647]
**Is your feature request related to a problem? Please describe.**
I've used an instance of the Theme class as described in [your documentation](https://blazorise.com/docs/theming/) to change a variety of display properties.

However, I need to configure a button's disabled properties such as color, background-color and border. Unfortunately, the ThemeButtonOptions don't seem to support this.

**Describe the solution you'd like**
Ideally I would like to be able to change color, background-color and various border properties depending on whether a button is disabled or not.

**Comment by robalexclark** [comment]
This is sorta Blazor generally rather than Blazorise, but you can set the disabled state like this for example

```
<button class="btn btn-primary" @onclick="BulkAllocate" disabled=@bulkAllocationButtonDisabled>Bulk Allocate</button>

Code{
    private bool bulkAllocationButtonDisabled = true;
}

```

Similarly you can set color or anything else through applying a class attribute to the button (or any DOM element for that matter), and then setting the class name in the code:

```
  <div class="@disabledHoldingDiv">
Stuff to Enable/Disable...
</div>

code{
    private string disabledHoldingDiv = "disabled-div"; //You can clear or read this string to enable/diable the div
}

In css:
.disabled-div {
    pointer-events: none;
    opacity: 0.4;
}
```

**Comment by stsrki** [comment]
@danlbb Theme generator is currently overriding CSS styles just like it would do if you're building it from `scss/less` source. For the most part I just use what's already in bootstrap, bulma or any other css framework.

Now regarding the disabled state, I'm missing the **opacity** level and I can add that one to the options. 

But if you want to control color, background etc. you should go with @robalexclark example and add your own styles.

eg.
```cshtml
<Button Color="Color.Primary" Class="my-disabled-button">TEST</Button>
```

```css
.btn-primary.disabled, .btn-primary:disabled
{
    background-color: blue;
    // etc.
}
```

**Comment by vindberg** [comment]
Thanks for the feedback. Will use that. This can be closed

**Comment by stsrki** [comment]
I will leave it open. The opacity still needs to be added to the theme options.
