### ISSUE TITLE
Input Field: Text property

### ISSUE THREAD

**Issue by RobertChanphakeo** [stsrki/Blazorise#651]
https://blazorise.com/docs/components/text/
The input field component, you have a "Text" attribute, in which use case would you decide to use "Text" over "Bind-Text"?

**Comment by stsrki** [comment]
This is more of a Blazor generals. Setting only the `Text` for `TextEdit` does not have much sense. When you work with input fields you expect from them to also **get** the value. Setting the Text will set the value one-way, it will just initialize the text input. If you use the `bind-Text` in that case Blazor will do some magic and enable the getter and the setter for the Text. This is called a two-way binding.

There is also a third option. Using the `Text` along with the `TextChanged` event. This way you have more control but it requires more work from your side. In fact this is what Blazor is actually doing under the hood when you do `bind-SomeProperty`.

More on this link: https://chrissainty.com/a-detailed-look-at-data-binding-in-blazor/
