### ISSUE TITLE
Modal Closed event callback is being invoked twice

### ISSUE THREAD

**Issue by Liversage** [stsrki/Blazorise#652]
I need to perform an action when a `<Modal>` is hidden. To always do that even when the escape key is pressed (at least when using Boostrap) I need to handle the `Closed` event callback. I have noticed that this surprisingly gets invoked twice whenever the `<Modal>` is hidden. Inspecting the code I believe I have found the [source of the problem](https://github.com/stsrki/Blazorise/blob/4129a40f12a41aa2fed5a5a1449b346d3496c69b/Source/Blazorise/Modal.razor.cs#L56):

`Modal.Hide()` will set `IsOpen` to `false` and then invoke the `Closed` event. However, the setter for `IsOpen` will also [intelligently invoke the event](https://github.com/stsrki/Blazorise/blob/4129a40f12a41aa2fed5a5a1449b346d3496c69b/Source/Blazorise/Modal.razor.cs#L138) resulting in the event callback being invoked twice. Even worse, if the `Closed` event callback cancels hiding the modal then the `Closed` event will still be invoked even though the modal hasn't been hidden (but only invoked once, not twice).

If my analysis is correct then this can be fixed be removing `Closed.InvokeAsync( null )` from `Modal.Hide()`. I would be happy to make a pull request for this very minor change if you like.

**Comment by stsrki** [comment]
I believe this is already fixed in v0.9. Modal is refactored and now there should be only one event call. https://github.com/stsrki/Blazorise/blob/dev090/Source/Blazorise/Modal.razor.cs

If you wish to try 0.9 preview you can download it from MyGet. https://github.com/stsrki/Blazorise#try-preview
