### ISSUE TITLE
Expand Table and its subcomponents with additional attributes

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#66]
**Table**
- [x] Narrow rows
- [x] Borderless table

**TableHeader**
- [x] Theme (light or dark)

**TableFooter**
- [x] Create component

**Rows**
- [x] Colors
- [x] IsActive or IsSelected attribute

**Comment by aford22** [comment]
Great!!! Right now I am investigating how to highlight a table row that was clicked. Ideally I could do something like:
```
@foreach (row in table)
{
    @if (row.IsSelected)
    {
        <TableRow style="background-colour:grey">
    }
}
```
or even better:
```<TableRow IsActive="@(row.IsSelected)">```

**Comment by stsrki** [comment]
@aford22 Going on TODO list

**Comment by stsrki** [comment]
@aford22 I have added `IsSelected` attribute to the `TableRow` and also I have enabled Style attribute for row component.

**Default behaviour:**

When you set IsSelected by `<TableRow IsSelected="true">`, the `--primary` css variable from `:root` will be used for row background-color. I think this is a prefered behaviour for bootstrap themes.

So `<TableRow IsSelected="true">` will be `background-color: var(--primary);`

**Using Style:**

In case default behaviour is not good for you there is another way. You can use `Style` attribute like:

`<TableRow Style="background-color:red;">`
