### ISSUE TITLE
Blazorise Table - Multiple components use the tag 'Column'. Components: BlazorTable.Column<TableItem> 

### ISSUE THREAD

**Issue by kamilk91** [stsrki/Blazorise#666]
**Describe the bug**
Okay, so everything was fine yesterday, but today when i opened my project in VS i have Error in every part of project, where Blazorise Table is used. 

**To Reproduce**
I really don't know how it happened. Restarted project in visual studio.

**Expected behavior**
Correctly built Tables (?)

**Screenshots**
![image](https://user-images.githubusercontent.com/26136300/77760862-56344600-7037-11ea-9e60-3ec0fa4f1a6c.png)

**Additional context**

My issue has #666, help me to pay respect!

**Comment by stsrki** [comment]
I looks to me like the problem is with Column. Both Blazorise and BlazorTable have the Column component and compiler does not know which one to use. Try to specify exact namespace like `<Blazorise.Column>` or `<BlazorTable.Column>`, whichever you want to use.

**Comment by maiselsernan** [comment]
remove the "@using Blazorise" statement from the _Imports.razor page, and put it just in the relevant pages.
