### ISSUE TITLE
Support navbar dropdown

### ISSUE THREAD

**Issue by Herdo** [stsrki/Blazorise#668]
I am trying to implement a two-level nav menu as seen on the bootstrap documentation site: https://getbootstrap.com/docs/4.0/components/navbar/ 
![grafik](https://user-images.githubusercontent.com/651191/77846746-6e7f9e80-71b8-11ea-8b77-500b6f124502.png)

Currently, only the `Navigation` and `NavigationItem` components are available.
In my opinion we would need a `NavigationDropdownItem`, which has multiple `NavigationItem`s or even nested `NavigationDropdownItem`s.

**Comment by stsrki** [comment]
@Herdo Please try the `Bar `and it's sub-components. They are actually proper implementation of navbar in bootstrap. `Navigation` and `NavigationItem` are actually some leftovers from first version of Blazorise that I will probably remove sometimes.

**Comment by Herdo** [comment]
Thank you, works like a charm!
Maybe mark `Navigation` and `NavigationItem` as `Obsolete`, and include it as a warning message in the next releases, that the classes will be removed?

**Comment by stsrki** [comment]
Marked as obsolete #690
