### ISSUE TITLE
Doesn't work highlighting of the active page in the DataGrid

### ISSUE THREAD

**Issue by 8VAid8** [stsrki/Blazorise#669]
**Describe the bug**
![alt text](https://downloader.disk.yandex.ru/preview/eb43f712a9e3f3461d73160a63300a0a75d60ad098f6c22cb92fa7f87ef7fef6/5e823333/1d3gClY7Jjg_E3LAUThl3ibGT08Euk7Ut8HwsIv0gPl2skn1P3eGEkcAWPfb8pVXv-D28FAE9z7-9V1eypPtVw==?uid=0&filename=2020-03-30_16-57-48.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=55781054&size=2048x2048)

There is a page 2 is supposed to be selected. DataGrid shows rows from a page 2, but doesn't select pagination item.

The proper variant have to looks like here:
![proper data grid](https://downloader.disk.yandex.ru/preview/34ff6053aa78169102fefcbd5a7cbb6bb6d15e177f45f9aa919d77a25f176213/5e82390b/cv6nHIUihJbeO7aImqP1tPxEVn4XJtfpxbU9B5snS1guZoUQaQKByAWZJ6ua7Ru-cZtnSXKMZqQKXYdYcXohJQ==?uid=0&filename=2020-03-30_17-22-53.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=55781054&size=2048x2048)

My code:
```
<DataGrid 
          TItem="GroupVM"
          Data="@groupsList"
          @bind-SelectedRow="@selectedGroup"
          EditMode="@editMode"
          Editable="@editable"
          Sortable="@sortable"
          Filterable="@filterable"
          ShowPager="@showPager"
          ReadData="@OnReadData"
          TotalItems="@totalGroups"
          RowInserted="@OnRowInserted"
          RowUpdated="@OnRowUpdated"
          RowRemoved="@OnRowRemoved"
          CurrentPage="@currentPage"
          >
    <DataGridCommandColumn TItem="GroupVM" />
    <DataGridColumn TItem="GroupVM" Field="Id" Caption="#" Sortable="false" />
    <DataGridColumn TItem="GroupVM" Field="Name" Caption="Name" Editable="true" />
    <DataGridColumn TItem="GroupVM" Field="SubscriptionId" Caption="SubscriptionId" Editable="true" />
</DataGrid>
```

```
@code {
    DataGridEditMode editMode = DataGridEditMode.Form;
    bool editable = true;
    bool sortable = false;
    bool filterable = false;
    bool showPager = true;

    public GroupVM selectedGroup { get; set; }
    IEnumerable<GroupVM> groupsList;
    int totalGroups;
    int currentPage = 1;

    async Task OnReadData(DataGridReadDataEventArgs<GroupVM> e)
    {
        Console.WriteLine("OnReadData start");

        string req = $"Groups?skip={(e.Page - 1) * e.PageSize}&take={e.PageSize}";
        var response = await Http.GetJsonAsync<GroupsVM>(req);

        Console.WriteLine("finished req");

        Console.WriteLine("e.Page = " + e.Page);
        Console.WriteLine("urrent page = " + currentPage);

        groupsList = response.Groups; // an actual data for the current page
        totalGroups = (int)response.Count;
        currentPage = e.Page;

        // always call StateHasChanged!
        StateHasChanged();
    }

    async Task OnRowInserted(SavedRowItem<GroupVM, Dictionary<string, object>> e)
    {
        var group = e.Item;
        string req = $"Groups";
        group = await Http.PostJsonAsync<GroupVM>(req, group);
        e.Values["Id"] = group.Id;
        e.Values.TryAdd("Id", "dsfdsfsdf");
        e.Values.TryAdd("#", "#dsfdsfsdf");
        StateHasChanged();
    }


    async Task OnRowUpdated(SavedRowItem<GroupVM, Dictionary<string, object>> e)
    {
        var group = e.Item;

        group.Name = (string)e.Values["Name"];
        group.SubscriptionId = (string)e.Values["SubscriptionId"];
        string req = $"Groups/{group.Id}";
        await Http.PutJsonAsync<GroupVM>(req, group);
    }

    async Task OnRowRemoved(GroupVM model )
    {
        string req = $"Groups/{model.Id}";
        await Http.DeleteAsync(req);
    }
}
```

**Comment by kierepka** [comment]
This same problem with standard Pagination/PagintaionItem/PaginationLink buttons. Just checked everything and problem is still this same.

**Comment by kierepka** [comment]
`@if (paginationShow) {
    <Pagination>

        <PaginationItem IsDisabled="@(searchPageNr <= 1)">
            <PaginationLink Page="prev" Clicked="@OnPaginationItemClick">
                @MyText.previous
            </PaginationLink>
        </PaginationItem>
        
        @for ( int i = 1; i <= lastPage; ++i ) {
            var pageName = i.ToString();
            var isSamePage = (i==searchPageNr);
            var bacgroundColor = isSamePage ? Color.Primary : Color.None;

            <PaginationItem IsDisabled="@isSamePage" IsActive="@isSamePage" Background="@bacgroundColor"  >
                <PaginationLink Page="@pageName" Clicked="@OnPaginationItemClick">
                    @pageName @isSamePage
                </PaginationLink>
            </PaginationItem>
        }        

        <PaginationItem IsDisabled="@(searchPageNr >= lastPage)">
            <PaginationLink Page="next" Clicked="@OnPaginationItemClick">
                @MyText.next
            </PaginationLink>
        </PaginationItem>
    </Pagination>
}`

Is rendered:
![image](https://user-images.githubusercontent.com/344056/78009510-728af800-7341-11ea-8ef0-284a9c1089be.png)
![image](https://user-images.githubusercontent.com/344056/78009591-88002200-7341-11ea-89d0-906a29656551.png)

**Comment by stsrki** [comment]
Hi sorry for not responding sooner. There are missing some image from first post so I'm not sure what is the real problem. Can you give me more information or better, can you create a simple demo project that I can test? tnx

**Comment by 8VAid8** [comment]
@stsrki i've made an example - https://github.com/8VAid8/BlazoriseDataGridDemo

**Comment by stsrki** [comment]
I have tested your example and I can confirm it's not working as expected.

Then I copied an example to Blazorise demo and tried it. It's working as expected. Really strange behavior. All I can think of is that the problem can be this part:

```cshtml
@for ( int i = FirstVisiblePage; i <= LastVisiblePage; ++i )
{
    var pageName = i.ToString();

    <PaginationItem Disabled="@(i == CurrentPage)" Active="@(i == CurrentPage)">
        <PaginationLink Page="@pageName" Clicked="@OnPaginationItemClick">
            @pageName
        </PaginationLink>
    </PaginationItem>
}
```

An `i` variable probably should not be used, instead I need to replace it with temp variable `pageName`. This is the famous "feature" with loops in Blazor.

I will try to change it but since I cannot reproduce it within Blazorise I will leave this ticket open until you confirm the bug is gone. Is that OK?

**Comment by stsrki** [comment]
Hi @8VAid8  Blazorise v0.9 is out. Can you confirm this issues is gone?

PS. In case you need to upgrade: https://blazorise.com/news/release-notes/090/

**Comment by 8VAid8** [comment]
Hi, @stsrki! Thank you for a new release! But, unfortunately I can't confirm the issue is gone. May be threre is something wrong with my code. I'll try to check it out.

**Comment by AjaxSantos** [comment]
Hi.
@stsrki I guess, it could be a problem with bulma solution.
In your bulma demo highlighting also does not work.
https://bulmademo.blazorise.com/tests/datagrid
In all other demos it works fine.
I hope, i could help you.

**Comment by stsrki** [comment]
@AjaxSantos Thank you! I didn't realized it is the Bulma provider. I can now confirm the bug on my side.

**Comment by Eastiling** [comment]
I'm seeing this same issue. The DataGrid pages correctly, the buttons work to change the page, but the highlighting is wrong. 

All the links, including the 'active' one, have the 'disabled' class as well which seems to be the issue.

**Comment by lmalsch** [comment]
I'm facing the same issue as @Eastiling with Blazorise Bootstrap.

**Comment by Eastiling** [comment]
This isn't a fix by any stretch, but a liveable workaround for now:

```
.page-link {
    cursor: pointer;
}

.page-item.active .page-link {
    z-index: 3 !important;
    color: #fff !important;
    background-color: #007bff !important;
    border-color: #007bff !important;
    pointer-events: inherit !important;
    cursor: pointer !important;
}
```

**Comment by lmalsch** [comment]
@Eastiling Thank you very much for sharing 👍
