### ISSUE TITLE
[Question] Access TItem of DataGridSelectColumn  within EditTemplate

### ISSUE THREAD

**Issue by CPlusPlus17** [stsrki/Blazorise#670]
Hello

I check the documentation and samples but could't find a way to access the instance of the class defined in DataGridSelectColumn within the EditTemplate.

Is there a chance to archive this?

```cshtml
    <DataGridSelectColumn TItem="Property" Field="Version.Id" Caption="Version" Editable="true">
        <DisplayTemplate>
            @{
                var version = (context as Property)?.Version;
                @(version.Name)
            }
        </DisplayTemplate>
        <EditTemplate>
            <SelectEdit TValue="int" SelectedValue="@((int)( ( (CellEditContext)context ).CellValue ))" SelectedValueChanged="@(( v ) => ( (CellEditContext)context ).CellValue = v)">
                @{
                    foreach (var ver in versionList)
                    {
                      // I need here the Property.Id
                        <SelectItem TValue="int" Value="@(ver.Id)">@(ver.Name)</SelectItem>
                    }
                }
            </SelectEdit>
        </EditTemplate>
    </DataGridSelectColumn>
```

Thanks!

**Comment by stsrki** [comment]
It's not possible as far as I know. When you're inside of `EditTemplate` you can only access an `EditTemplate` context. I don't know a way to access it's parent context. The only way is to implement and add `TItem` to `CellEditContext`.

**Comment by CPlusPlus17** [comment]
Thanks for the information! :)

Is there any other good way to get the id somehow into there? I tried to to something around:

```

<EditCommandTemplate>
            <Button Color="Color.Warning" Clicked="@context.Clicked">Edit</Button>
</EditCommandTemplate>
```

To set the Id into a var in `@Code` but couldn't figure it out how to archive this.

Thanks

**Comment by stsrki** [comment]
Not sure it this will work but try this

```cshtml
<EditCommandTemplate>
            <Button Color="Color.Warning" Clicked="@context.Clicked">Edit</Button>
</EditCommandTemplate>
@code{
    private yourField;

    Task OnEditClicked(CommandContext<Property> context)
    {
        yourField = context.Item.yourField;

        return context.Clicked(context.Item);
    }
}
```

**Comment by CPlusPlus17** [comment]
Hello, thanks again!

This way I tried but the problem is the Clicked uses EventCallback as parameter. So the function like you provided it doesn't work.

> cannot convert from 'method group' to 'EventCallback'

Greets
Manuel

**Comment by stsrki** [comment]
Oh yeah sorry. `Try this Clicked="@((c)=>OnEditClicked(c))"`

**Comment by CPlusPlus17** [comment]
Had to cast it:

```cshtml
<Button Color="Color.Warning" Clicked="@((c)=>OnEditClicked((CommandContext<Property>)c))">Edit</Button>
```

```cshtml
return context.Clicked(context.Item);
```

> Non-invocable member 'CommandContext.Clicked' cannot be used like a method.

If I do an async, return nothing and test it:

- function is called, can write to the chrome console
- context.Item seems null or empty, accessing it stops execution, no error logs in chrome console

**Comment by rdnlsmith** [comment]
@CPlusPlus17 I got it to work like this:

```razor
<EditCommandTemplate>
    <Button Color="Color.Warning" Clicked="(e) => OnEditClicked(e, context))">Edit</Button>
</EditCommandTemplate>

@code {
    private yourField;

    private async Task OnEditClicked(object e, CommandContext<Property> context)
    {
        yourField = context.Item.yourField;

        if (context.Clicked.HasDelegate)
        {
            await context.Clicked.InvokeAsync(e);
        }
    }
}
```

`e` does seem to be empty, but `EventCallback.InvokeAsync()` requires an `object` parameter. You could probably do

```
Clicked="() => OnEditClicked(context)"

...

await context.Clicked.InvokeAsync(context.Item);
```

if you prefer.
