### ISSUE TITLE
Dropdown and DropdownMenu have a IsRightAligned property

### ISSUE THREAD

**Issue by Herdo** [stsrki/Blazorise#672]
**Describe the bug**
When using the `Dropdown` component, it can be confusiong when wanting to right-align it.
Both the `Dropdown`, as well as the `DropdownMenu` provide a `IsRightAligned` property.

**To Reproduce**
1. Implement a `Bar` with a few `BarItems`.
2. Add a `BarEnd` component.
3. Add a `Dropdown` component to the `BarEnd`, to show a user menu on click.
4. Set the `Dropdown.IsRightAligned` to `true`.
5. No effect. The dropdown is partially outside the screen.
6. Set the `Dropdown.IsRightAligned` to `false` and the `DropdownMenu.IsRightAligned` to `true`.
7. Dropdown works perfectly.

**Expected behavior**
Only one, either the `Dropdown`, or the `DropdownMenu` should have a `IsRightAligned` property.

**Comment by stsrki** [comment]
You're right. This is also one of those things from the past when Blazor did not have things like `CascadingValue` so I had to add multiple properties to every component, in this case on both `Dropdown` and `DropdownMenu`. I will remove it from the menu and leave it only on dropdown so there is no more confusion. Thanks for letting me know!
