### ISSUE TITLE
Add a SetFocus method

### ISSUE THREAD

**Issue by gmiseria** [stsrki/Blazorise#676]
I think could be useful to add a SetFocus method on all the components. 
In the base components is possible to make a custom JSRuntime call using the ElementRef property but on complex components like AutoComplete is impossible to reach the TextEdit unless you set the @ref attribute on the TextEdit component and make it public.

Thanks

**Comment by stsrki** [comment]
You already have `Focus()` method on input components. Including `TextEdit`.

Not sure about having it on all the components.

**Comment by stsrki** [comment]
PS. Yeah `AutoComplete` will need custom `Focus()` method to proxy it to `TextEdit`.

**Comment by gmiseria** [comment]
You are right. Sorry I haven't found focus method on the TextEdit doc and I haven't tried with the intellisense.
