### ISSUE TITLE
Some Components can not be styled

### ISSUE THREAD

**Issue by b-straub** [stsrki/Blazorise#681]
**Describe the bug**
Some components e.g. "Text" or "Title" can not be styled because the razor components has no `style="@StyleNames"` parameter.

**To Reproduce**
Create a Text component with custom style:
`<Text Style="white-space:pre-line">`

**Expected behavior**
`element.style {}` will contain the custom style

**Comment by stsrki** [comment]
Style was previously added only on most used components to save performance since Blazor was a lot slower back then. I have now already started to add style to all components for the next release. It will be soon. Thanks for report.
