### ISSUE TITLE
Null reference exception when DataGridColumn Field is not set

### ISSUE THREAD

**Issue by TPIvan** [stsrki/Blazorise#686]
**Describe the bug**
I am trying to add a grid column which is not connected to any data column (computed). So I have created a `DataGridColumn` with `DisplayTemplate` containing e.g.  `@($"{context.Name} - {context.Number}")`. The column is not connected so I have omitted the `Field` attribute. The grid has been rendered, but there was a `NullReferenceException` in the browser console.  

**To Reproduce**
1. Create a component with the following content:

          <DataGrid Data="@expLocItems" TItem="ExpLocItem" Sortable="false">
              <DataGridColumn  TItem="ExpLocItem" Caption="My Column">
                  <DisplayTemplate>
                      @($"{context.Name} - {context.Number}")
                  </DisplayTemplate>
              </DataGridColumn>
          </DataGrid>
          
          @code {
              List<ExpLocItem> expLocItems = new List<ExpLocItem>(){
                                          new ExpLocItem("Petr", 1),new ExpLocItem("Josef", 3),new ExpLocItem("Vintir",5),new ExpLocItem("Franta", 9) };
              public class ExpLocItem
              {
                  public string Name { get; set; }
                  public int Number { get; set; }
          
                  public ExpLocItem(string name, int number)
                  {
                      Name = name; Number = number;
                  }
              }
          }
        
2. Run it in a browser - the grid is rendered but a yellow unhandled exception bar is displayed
3. Check the browser console 
4. See the error:

        System.NullReferenceException: Object reference not set to an instance of an object.
           at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, String fieldName)
           at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[TItem](String fieldName)
           at Blazorise.DataGrid.BaseDataGridColumn`1.<.ctor>b__4_2()
           at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
           at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.get_Value()
           at Blazorise.DataGrid.BaseDataGridColumn`1.GetValue(TItem item)
           at Blazorise.DataGrid._BaseDataGridRow`1.OnFirstAfterRenderAsync()
           at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
5. when an attribute `Field="@nameof(ExpLocItem.Name)"` is added the grid is rendered without any problem

**Expected behavior**
I would expect the grid is rendered without any exception, because the ability to have disconnected columns is useful. When that not possible one would at least expect more meaningful error ideally at design time.

**Additional context**
Whent `TItem` attribute is ommited (because I thought that having it on DataGrid is enough) there is a compile time exception 

>The type arguments for method 'TypeInference.CreateDataGridColumn_0<TItem>(RenderTreeBuilder, int, int, string, int, string, int, RenderFragment<TItem>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by stsrki** [comment]
Computed columns are not supported, At least for now. But maybe you can create additional property on your model and use that one on `DataGridColumn` as any other field?

eg
```
class MyModel
{
    public string Name { get; set; }
    public string Number { get; set; }
    public string NameAndNumber { get { return $"{Name} - {Number}"; } set { /* unused */ } }
}
```

**Comment by TPIvan** [comment]
Yes, I can or I can have a dummy column for computed columns. But the main problem is that the error is difficult to diagnose. The exception occurs **after** the grid is rendered correctly and is not very meaningful. 

The fact that the component is rendered correctly lead me to conclusion that there is only minor issue. That some if `!=null` is missing.

**Comment by stsrki** [comment]
True. I can add null check and raise a meaningful error of field is not present.
