### ISSUE TITLE
Validation for TextEdit in BuildRenderTree

### ISSUE THREAD

**Issue by VR-Architect** [stsrki/Blazorise#69]
The validation for the text edit control is not defaulting to a red outline with validation message below it when it is used in BuildRenderTree. If I put the commented code below directly in a *.razor file, the red outline and message shows. 

I am running VS2019 v16.1.0 Preview 1.0 with Core 3 SDK Preview 4 and Blazorise Bootstrap v0.6.4 Preview1-19154-02

```
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.RenderTree;
using Blazorise;

namespace Alpha.Pages.Test
{
    public class vcTextEdit : ComponentBase
    {
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);

            //<Validation UsePattern = "true"> 
            //  <TextEdit Pattern = "[A-Za-z]{3}"   
            //      <Feedback>  
            //          <ValidationError> Pattern does not match!</ValidationError>     
            //      </Feedback>     
            //  </TextEdit>
            //</Validation>

            builder.OpenElement(0, "Validation");
            builder.AddAttribute(1, "UsePattern", true);

            builder.OpenComponent<TextEdit>(2);
            builder.AddAttribute(3, "Pattern", "[A-Za-z]{3}");

            builder.OpenElement(4, "Feedback");

            builder.OpenElement(5, "ValidationError");
            builder.AddAttribute(6, "ChildContent", (RenderFragment)((builder2) =>
            {
                builder2.AddContent(7, "Pattern does not match!");
            }
            ));
            builder.CloseElement(); // ValidationError

            builder.CloseElement(); // Feedback

            builder.CloseComponent(); // TextEdit

            builder.CloseElement(); // Validation
        }
    }
}
```

**Comment by stsrki** [comment]
I will into this as soon as I switch to Core Preview 4.

**Comment by VR-Architect** [comment]
BTW, the purpose of me moving the TextEdit to a builder is so I can pass binded variables in to turn validation on/off. If you could add that feature to all controls with validations that would be great. The issue is we can't use a razor file with if statements to check for the hasValidation binded variable.

So with the above code I was planning to add these variables:

- String ValidationSuccess
- String ValidationError
- String Pattern (if contains a value, then use UsePattern = "true")
- ?? Validator (for running C# event handler for onValidate)
- All the other TextEdit variables alread in TextEdit

If you could add the above to the TextEdit (and other controls) then we could bind to these variables within the TextEdit control in a razor file.

Thanks for the considerations and excellent library!

**Comment by stsrki** [comment]
Can you please explain a little more what exactly you need to do? I want to be sure we're on the same track. 

Also if you need to manually enable validation please look at the Validations component. It is a container for Validation component(s) with which you can disable automatic validation.
