### ISSUE TITLE
ChartOptions improvement

### ISSUE THREAD

**Issue by gmiseria** [stsrki/Blazorise#693]
In the chartOptions I think is important to manage the **responsive** and **maintainAspectRatio** options. Without the second, for example, is impossible to set an arbitrary width and height in the container.

**Comment by stsrki** [comment]
I can add those fields to the `ChartOptions` class so it's not a problem.

In the meantime if you're on **v0.9 preview3** you can define those fields by using the new `OptionsObject` property.

**Example:**

```cshtml
<LineChart @ref="lineChart" TItem="double" OptionsObject="new { Responsive = true, MaintainAspectRatio = false }" />
```
