### ISSUE TITLE
Update Readme for Preview 4 Client/Server Blazor

### ISSUE THREAD

**Issue by VR-Architect** [stsrki/Blazorise#70]
FYI, the latest Core 3 Preview 4 is using Bootstrap v4.3.1 out of the box. 

Do we still need to install Blazorise.Bootstrap? If yes, you might consider noting that on the readme page. Nevermind on that last question, I just saw in the readme file the instructions to remove the default BootStrap that came with the project.

**Comment by VR-Architect** [comment]
Also, the readme says to add the source file links to the index.html file. It may help others if it says the index.html file located in the wwwroot folder. If that is not the correct file, there is no other index.html file in the client project. Also, does it matter if the scripts go before or after the blazor.webassembly.js script?

**Comment by VR-Architect** [comment]
And lastly, the Readme file says to put this in the startup configure method:

app
    .UseBootstrapProviders()
    .UseFontAwesomeIcons();

however, it results in an error

Reference to type 'IComponentsApplicationBuilder' claims it is defined in 'Microsoft.AspNetCore.Components', but it could not be found

**Comment by stsrki** [comment]
Thanks for the detailed report. Keep in mind that current version of Blazorise is still for preview 3. Most of the issues you get are because of the changes introduced in preview 4. Once I update the project to new version I will also update readme and documentation.
