### ISSUE TITLE
[Feature] Layout components (header/footer/content)

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#700]
**Preface**
This feature request is coming from my biased Ant Design background, and I'm hoping to get some feedback on how you think this would work with other providers and Blazorise in general.

**Request**
I am wanting to create a clearer guide to core page layout, something that would be primarily setup in `MainLayout.razor`.

In the [Ant Design layout world](https://ant.design/components/layout/#components-layout-demo-basic), there is a nice clear and flexible layout structure/pattern.

This quite heavily relies on changes in #6.

**Issue**
Ant Design has Layout features that aren't provided in Blazorise, like `Header` and `Footer`, so this would cover those and provide a cleaner implementation of things like a search field in the `Header` (instead of `Bar`).

Additionally, as mentioned in #6, it does not take advantage of the `Bar` component, and what has been produced is basically two Navigations (although, I understand 1 is an optional extension).

**Idea**
Taking a page heavily from the Ant Design book.

This consists of 5 core components:
- `Layout`: The layout wrapper, in which Header Sider Content Footer or Layout itself can be nested, and can be placed in any parent container.
- `Header`: The top layout with the default style, in which any element can be nested, and must be placed in Layout.
- `Sidebar`: The sidebar with default style and basic functions, in which any element can be nested, and must be placed in Layout.
- `Content`: The content layout with the default style, in which any element can be nested, and must be placed in Layout.
- `Footer`: The bottom layout with the default style, in which any element can be nested, and must be placed in Layout.

In my request, the existing `Bar` component could then either be added to the `Sidebar` or the `Header` (or even the `Footer`).

In the following picture, the `.razor` structure would be like the following:
```
<Layout>
  <Sider>
    <Bar></Bar>
  </Sider>
  <Layout>
    <Header></Header>
    <Content></Content>
    <Footer></Footer>
  </Layout>
</Layout>
```

![image](https://user-images.githubusercontent.com/6387861/78745621-d738f900-79b8-11ea-8d1c-5e110457f12f.png)

Or, alternativley, without a `Sidebar`:
```
<Layout>
  <Header>
    <Bar></Bar>
  </Header>
  <Content></Content>
  <Footer></Footer>
</Layout>

```
![image](https://user-images.githubusercontent.com/6387861/78745805-53334100-79b9-11ea-8618-a21144e18c84.png)

I feel these components are quite simple, yet they would provide a very clear way (that is easily documented) and flexible for layout of your page structure.

I am also (hoping) they would fit in quite well to the existing `ClassProvider` structure.

**Feeback**
As mentioned, hoping to get some feedback on this, and whether or not you think this is do-able in Blazorise, given the other providers? 
As this clearly an Ant Design driven concept!

Sorry for the quite long post, I hope its clear enough!
Thanks again for your time.

**Comment by stsrki** [comment]
As the mater of fact I have already done layout components but I had some issues with sidebar so I just stashed it until I finish 0.9. It's based on AntDesign. I think all it needs to be done is to fix some styles and we're good to go.

**Proof:**

![image](https://user-images.githubusercontent.com/900302/78748058-4982ec80-796b-11ea-8753-c9e782b7051d.png)

**Comment by MitchellNZ** [comment]
Oh awesome! That’s great news then!

Love your work @stsrki!

**Comment by stsrki** [comment]
@MitchellNZ If you're willing to have a look I can push layout changes to new dev branch?

**Comment by MitchellNZ** [comment]
@stsrki yeah sure, more than happy to have look.
Its getting quite late my time now - but can do tomorrow morning.

**Comment by stsrki** [comment]
No problem. Whenever you're ready. It's up on `dev090-layout` branch.

**Comment by WillianGruber** [comment]
Will the Bar component be changed?
And we'll have a footer?

**Comment by stsrki** [comment]
@WillianGruber the Bar stays the same. Layout component are used to give structure to the page. Footer will be there also, just havent created it yet.

**Comment by MitchellNZ** [comment]
@stsrki I have a made a few tweaks and got it working well with the sidebar, also fixed a couple of other minor CSS issues.

I haven't made a PR because I wasn't sure if you want me to PR this into `dev090` or your `dev090-layout` branch?
So please let me know.

Otherwise, you can check it out [here](https://github.com/MitchellNZ/Blazorise/tree/dev090-layout).

I also noticed Ant Design doesn't have padding CSS for `Padding.Is4`, so I just added `Padding.Is4.OnX.Is4.OnY` as a workaround for now, as I'm not sure how these are generated.

**Comment by MitchellNZ** [comment]
Just as an additional note for quick reference, the overall layout needed to be like this:
```
<Layout Sider="true">
    <LayoutSider>
        <LayoutSiderContent>
            <Sidebar></Sidebar>
        </LayoutSiderContent>
    </LayoutSider>
    <Layout>
        <LayoutHeader Fixed="true">
            <Bar></Bar>
        </LayoutHeader>
        <LayoutContent>
            @Body
        </LayoutContent>
    </Layout>
</Layout>
```

**Comment by stsrki** [comment]
I have looked at the changes done in your fork. Looks good so far. When you're ready you can create PR on the `dev090-layout` branch. That will be our working branch until layout is done.

Regarding the layout structure in demo, I think that OK. It's just rearranged a little. Perfectly fine with that.

Oh yeah, there were some changes in Blazorise structure done by @DarthPedro. Demo apps are now moved to Demos folder. So please get the latest changes onto your branch before PR.

**Comment by MitchellNZ** [comment]
Great - I'll pull your latest `dev090-layout` to get those changes and explore some more alternatives around what we were talking about with the `overflow` in `body`  (like the `root` component you mentioned).

Will create a PR when I'm finished.

Thanks for the feedback!

**Comment by stsrki** [comment]
Initially this was not part of `v0.9` but since@MitchellNZ has stepped in and helped with layout components I will push it for next release.
