### ISSUE TITLE
Sidebar not using css

### ISSUE THREAD

**Issue by DanielFawcett** [stsrki/Blazorise#704]
**Describe the bug**
I'm trying to change the sidebar width and colours etc by changing the side bar css but it has 0 effect on the side bar.

**To Reproduce**
Install Side bar nugget,
Add side bar to mainlayout
try changing the generated css
**Expected behavior**
Changing the width of the side bar to actually change the side bar

**Comment by stsrki** [comment]
Can you show us some css that you have tried to apply?

**Comment by DanielFawcett** [comment]
.sidebar {
    width: 150px;
    background-image: linear-gradient(180deg, rgb(5, 39, 103) 0%, #3a0647 70%);
}


@media (min-width: 768px) {
    app {
        flex-direction: row;
    }

    .sidebar {
        width: 150px;
        height: 100vh;
        position: sticky;
        top: 0;
    }

.sidebar .nav-item a.active {
    background-color: rgba(255,255,255,0.25);
    color: white;
}

.sidebar .nav-item a:hover {
    background-color: rgba(255,255,255,0.1);
    color: white;
}

These are the elemets which i would expect to show changes on the side bar but they don't

**Comment by stsrki** [comment]
I see the problem now. You still have styles that comes along when you create new Blazor project. Those styles tend to mess with Blazorise and Bootstrap classes and styles. This is a known problem and usually I advice everyone to remove everything from `site.css` and recreate everything from scratch if needed. You have full example in the demos folder: https://github.com/stsrki/Blazorise/tree/dev090/Demos

Currently I'm working on new Layout components that once done will remove any need(almost) for additional styles as entire page structure will be natively supported by Blazorise. see #700

**Comment by DanielFawcett** [comment]
So I've removed all the css and copied over the demo stuff and then added back in what i need. 

The side bar size is still not changing even with:

```
.sidebar {
    width: 150px;
    background-image: linear-gradient(180deg, rgb(5, 39, 103) 0%, #3a0647 70%);
}
```

**Comment by stsrki** [comment]
Try to also change `min-width` and `max-width`.

**Comment by DanielFawcett** [comment]
Still no effect - Does this look right

`<Sidebar Class="sidebar" @ref="sidebar">`

**Comment by stsrki** [comment]
Sidebar component already have `sidebar` class so you don't need to apply it. Do you have this in our `index.html`?

`<link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />`

**Comment by DanielFawcett** [comment]
Yes - I have these 3 incase any of them make a difference but i can't see how

```
 <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />
```

**Comment by stsrki** [comment]
Not sure why ot wont work for you. it works on my side with this

```css
.sidebar{
    min-width: 150px;
    max-width: 150px;
}
```

Can you upload your project so I can take a look later?

**Comment by DanielFawcett** [comment]
I've added you to the private repo, will be easier than uploading the full source if that's okay?

**Comment by stsrki** [comment]
Yeah no problem. I'm out now so I will look at it later.

**Comment by DanielFawcett** [comment]
No Worries, thank you very much for your help!!

**Comment by stsrki** [comment]
I found your problem(s). First you messed the order of css links. Your _PippitSass_ import must come after the `<link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />`. Next, you modified `PippitSass.css` but you were importing `PippitSass.min.css` instead.

It must be like this

```diff
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Pippit</title>
    <base href="/" />
-    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

    <link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
    <link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
    <link href="_content/Blazorise.Sidebar/blazorise.sidebar.css" rel="stylesheet" />

+    <link href="css/PippitSass.css" rel="stylesheet" />
</head>
```

**Comment by DanielFawcett** [comment]
Great that worked thank you!!! love the work you're doing aswell! keep it up <3
