### ISSUE TITLE
add Null column to create  custom column in datagrid

### ISSUE THREAD

**Issue by imprathamesh** [stsrki/Blazorise#710]
**Is your feature request related to a problem? Please describe.**
I want to add a link on every next to the row so i can redirect each row on the basis of row id or id from table (database). 

**Describe the solution you'd like**
Create a empty column so users can add any custom element into it.

**Comment by stsrki** [comment]
Why not use DisplayTemplate? https://blazorise.com/docs/extensions/datagrid/#displaytemplate

**Comment by imprathamesh** [comment]
this working. On selecting row in datagrid. color of text is grey so its not turn into white after selecting row. its looks bad for readability. Btw this Blazorise is very awesome.

**Comment by imprathamesh** [comment]
> Why not use DisplayTemplate? https://blazorise.com/docs/extensions/datagrid/#displaytemplate

yes its working
