### ISSUE TITLE
Dynamic Sidebar with SidebarLink and stacking

### ISSUE THREAD

**Issue by hardkorehak** [stsrki/Blazorise#712]
I might be missing something in the dynamic section of the sidebar, and am hoping there is a solution. We are using the sidebar to build our application menus - but I can't seem to find a way to build out SidebarLinks instead of Subitems, which show drop-downs.

![2020-04-09_15-52-57](https://user-images.githubusercontent.com/61984061/78939749-53dfdc00-7a7a-11ea-8c44-b88cc5ad2ba3.jpg)

```cs
        gUserName = "user1";
        applist = await s.GetUserApps(gUserName);
        sidebarInfo = new SidebarInfo
        {
            Brand = new SidebarBrandInfo
            {
                Text = "Company Name",
                To = ""
            },
            Items = new List<SidebarItemInfo>
            {
                new SidebarItemInfo
                {
                    Text = "dummy item",
                    To = "dummy page"
                }
            }
        };
        foreach (var app in applist)
        {
            SidebarItemInfo x = new SidebarItemInfo
            {
                Text = app.DBTitle,
                SubItems = new List<SidebarItemInfo>()
            };
            List<SidebarItemInfo> y = new List<SidebarItemInfo>();
            foreach(var cat in app.CatList)
            {
                

SidebarItemInfo z = new SidebarItemInfo
                {
                    Text = cat.DBMenuCategory,
                    To = ""
                    //SubItems = new List<SidebarItemInfo>()
                };
                y.Add(z);
            }
            if (y == null)
            {
                //add nothing
            }
            else
            {
                x.SubItems.AddRange(y);
            }
            sidebarInfo.Items.Add(x);
        }

```

Also, I would be interested to know if anyone has implemented anything like side-by-side sidebars - for example, clicking on a SidebarLink opens a different sidebar to the right of the main sidebar.

**Comment by stsrki** [comment]
It's probably because you have `SubItems = new List<SidebarItemInfo>()` on your link items. Its should be undefined for regular items. So just remove those.

**Comment by hardkorehak** [comment]
The problem I found was, if I didn't create an initial empty list, I couldn't add individual items to it.

I may not need it after all. The concept of Department > Category > Tool was seeming excessive. We are changing the style to Department > Tool. So every item will have a link to it by default.

We'll make sure to include a link to you on our About page.

**Comment by stsrki** [comment]
So, we can close the issue?

**Comment by hardkorehak** [comment]
Yes, I actually intended to hit the Close and comment. Thank you for your assistance.
