### ISSUE TITLE
NumericEdit allow decimal steps

### ISSUE THREAD

**Issue by vignatov** [stsrki/Blazorise#74]
At the moment Step variable of NumericEdit control is of type int? Would make sense to make it string to allow "0.01", ".01" and "any" steps supported by html.

**Comment by stsrki** [comment]
NumericEdit is generic component and so it can have any type for the Value. On what version of Blazorise are you?

**Comment by vignatov** [comment]
The issue is not with Value, but with Step parameter. At the moment it hard coded to be int?. There seems to be nit much point for it to be an integer as it can easily be a string to accommodate other possible step values.

**Comment by stsrki** [comment]
Sorry I misread the the issue. I will see what I can do regarding the Step attribute.

**Comment by stsrki** [comment]
Step attribute converted to decimal type.
