### ISSUE TITLE
Using Validation with SelectEdit element

### ISSUE THREAD

**Issue by mfitconsultants** [stsrki/Blazorise#743]
I have the following element in a form;

            <Field IsHorizontal="false" ColumnSize="ColumnSize.Is12.OnDesktop">
                <Validation Validator="@ValidationRule.IsNotEmpty">
                    <FieldLabel>Contact Type</FieldLabel>
                    <FieldBody ColumnSize="ColumnSize.Is12.OnDesktop">
                        <SelectEdit @bind-SelectedValue="@Contact.ContactTypeId">
                            @if (contactTypes != null)
                            {
                                @foreach (var type in contactTypes)
                                {
                                    <SelectItem Value="type.Id">@type.Name</SelectItem>
                                }
                            }
                        </SelectEdit>
                    </FieldBody>
                </Validation>
            </Field>

This is working and when the form is initially loading the input field is green, however, when I select an element the validation kicks is as invalid? (this happens as soon as an element is selected.)

Could you advise what I am doing wrong here please?

**Comment by stsrki** [comment]
Maybe try with custom validator instead of `ValidationRule.IsNotEmpty`

eg.
```cs
void ValidateSelect( ValidatorEventArgs e )
{
    var selectedValue = e.Value == null ? 0 : Convert.ToInt32( e.Value );
    e.Status = selectedValue != 0 ? ValidationStatus.Success : ValidationStatus.Error;
}
```

**Comment by mfitconsultants** [comment]
@stsrki I can confirm that the above does fix the issue.
