### ISSUE TITLE
Feature Request: Ability to disable tabs

### ISSUE THREAD

**Issue by cr1** [stsrki/Blazorise#744]
I am trying to disable tabs upon an action within one of the tabs contents, but there is currently no way to do that. I do have a workaround which is to disable changing tab state on SelectedTabChanged, but it does not visually show the tabs are diabled.

I would like to have another parameter for <Tab> called IsDisabled

This should apply a disabled class to the link. In bootstraps case, adding the disabled class to nav-link disables the tab. I tried using the "Class" parameter but it adds the class to the nav-item (bootstrap) instead of the nav-link.

Thank you, great library!

**Comment by stsrki** [comment]
It's fairly small feature so I will push it to v0.9. It's going to be in a day or two.
