### ISSUE TITLE
Mono.Cecil.ResolutionException

### ISSUE THREAD

**Issue by Lexx8000** [stsrki/Blazorise#75]
Hello!
When I added only Blazorise.Bootstrap from NuGet to blazor sample - got exception:

1>Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve Microsoft.AspNetCore.Components.Services.IUriHelper
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
1>   at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
1>   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
1>   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.MarkStep.Initialize()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)

Blazorise 0.6.4-preview1-19154-02
Microsoft.AspNetCore.Blazor 3.0.0-preview4-19216-03
Visual Studio 2019 16.0.2

**Comment by toddlang** [comment]
I don't believe it's updated for Preview4 yet, so...not exactly an issue.

**Comment by stsrki** [comment]
Yep, the update to preview 4 should be ready probably tomorrow. It's mostly done, I just need to update documentation.

**Comment by Lexx8000** [comment]
Thank you, will wait it

**Comment by Lexx8000** [comment]
Can I add SidebarItem dynamically?

**Comment by stsrki** [comment]
If you by dynamically mean with an attribute, then no. But you can always use for or foreach loop to create items.

**Comment by Lexx8000** [comment]
didn't understand how can I create new Sidebar Items to Side barSubItem - no Add method, no Text property

**Comment by stsrki** [comment]
You can look at the demo project to see the code example. https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Layouts/MainLayout.cshtml

Keep in mind that Sidebar is still a work in progress. There will be some minor bug fixes in 0.7 but there are still things to be done. If you need a feature or report a bug please open new issue. Tnx

**Comment by Lexx8000** [comment]
Example has no dynamic items. Just wanted specify - it new technology for me, don't know much things.

**Comment by stsrki** [comment]
I'm not home so I cannot give you full example now. Here I will just copy-paste a sample from stackoverflow to give you an idea.

You can just do a:

<ul>
    @foreach (var item in listItems)
    {
        <myComponent bind-myVar="@item"></myComponent>
    }
</ul>

**Comment by Lexx8000** [comment]
Thank you! It's not so difficult)

**Comment by stsrki** [comment]
Blazorise 0.7 is released. Please check it and let me know if the error is still happening

**Comment by Lexx8000** [comment]
OK. Now compiling without problem, I'll write if any errors will appear.
