### ISSUE TITLE
Bar toggle not working

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#76]
Hello again!

I have the following code:

```
    <Bar Breakpoint="Breakpoint.Mobile" Background="Background.Light" Theme="Theme.Light">
        <BarBrand>
            Activity: Audit Entries
        </BarBrand>
        <BarToggler>
        </BarToggler>
        <BarMenu>
            <BarStart>
                <BarItem>
                    <BarLink To="#home">Home</BarLink>
                </BarItem>
                <BarItem>
                    <BarLink To="#docs">Documentation</BarLink>
                </BarItem>
            </BarStart>
            <BarEnd>
                <BarItem>
                    <SimpleButton Color="Color.Primary">Sign up</SimpleButton>
                    <SimpleButton Color="Color.Secondary">Log in</SimpleButton>
                </BarItem>
            </BarEnd>
        </BarMenu>
    </Bar>
```
The bar renders as shown:
![image](https://user-images.githubusercontent.com/11410374/56889666-e7d5b500-6a6e-11e9-8268-8184d937a739.png)
However clicking on the "Collapse" icon does nothing.

I want the bar to show in collapsed state on all devices. When the user clicks on the "Collapse" icon it opens to show the content. Really, what I am looking for is "Acccordion" functionality...

**Comment by stsrki** [comment]
I think that Bar component is still not automated to work like this. For now you can do this manually, please look at the demo example: https://github.com/stsrki/Blazorise/blob/master/Tests/Blazorise.Demo/Layouts/MainLayout.cshtml

In the meantime I will do something about automatic toggle.
