### ISSUE TITLE
[Question]DataGrid

### ISSUE THREAD

**Issue by buzzer83** [stsrki/Blazorise#764]
I started using blazorise for my application. I created a datagrid but I have a problem when I have to use a property with parameter.

This is my object Prova
```
public string Codice { get; set; }  

public string Titolo(short lingua){
    return DizTitolo.TryGetValue(lingua, out string result) ? result : null;
}
```
and this is razor page
```
<DataGridColumn TItem="Prova" Field="@nameof(Prova.Codice)" Caption="Codice" />
<DataGridColumn TItem="Prova" Field="@nameof(Prova.Titolo(1))" Caption="Titolo" />
```

The "campo" field works correctly but I have no idea how to import the "titolo" field. TY.

**Comment by MitchellNZ** [comment]
Unfortunately the `DataGrid` does not support methods like that.

There are two ways I think you could achieve this.

1. Create a new property on your model called `TitoloOne` (or whatever you like):
`public string TitoloOne => Titolo(1);`
Usage:
`<DataGridColumn TItem="Prova" Field="@nameof(Prova.TitoloOne)" Caption="Titolo" />`

2. Use a `DisplayTemplate`:
```
<DataGridColumn TItem="Prova" Field="@nameof(Prova.Titolo)" Caption="Titolo">
   <DisplayTemplate>
      @context.Titolo(1)
   </DisplayTemplate>
</DataGridColumn>
```

@stsrki might have an alternative! Or please correct me if I'm wrong.

Otherwise, let me know how you get on @buzzer83

**Comment by buzzer83** [comment]
Thank you for your answer

**Solution 2** gives me this exception:

System.AggregateException: One or more errors occurred. ('Titolo' is not a member of type 'LibreriaDati.Modelli.Prova' (Parameter 'propertyOrFieldName'))
 ---> System.ArgumentException: 'Titolo' is not a member of type 'LibreriaDati.Modelli.Prova' (Parameter 'propertyOrFieldName')...

**Solution 1** it cannot be used because I should go to write all the n properties in the code

Temporarily  I have solved this but it does not seem to me the optimal solution

```
<DataGridColumn TItem="Prova" Field="@nameof(Prova.TitoloOK )" Caption="Titolo" />

@code {
    private List<Prova> lista;

    private Prova sel;
    private string cerca;

    protected override async Task OnInitializedAsync()
    {
        lista = _dbProva.Lista();

        foreach (Prova item in lista)
        {
            item.TitoloOK = item.Titolo(1);
        }
    }
    }
}
```

**Comment by stsrki** [comment]
DatGrid only supports properties as a Field parameter. You're trying to use function that accepts a parameter and there is no way to know what that parameter might be. Your workaround is OK but the better solution might be something of a mix.

Create a new field on your class that is just a placeholder for your function.

`<DataGridColumn TItem="Prova" Field="@nameof(Prova.TitoloOne)" Caption="Titolo" />`

Then in DataGrid you can use DisplayTemplate to get the right value dynamicaly.

```
<DataGridColumn TItem="Prova" Field="@nameof(Prova.TitoloOne)" Caption="Titolo">
   <DisplayTemplate>
      @context.Titolo(1)
   </DisplayTemplate>
</DataGridColumn>
```

I know it's not ideal but for now it's best option.

**Comment by Marfusios** [comment]
`@nameof` is compile only construction. It just converts C# code to string at build. So there couldn't be any runtime stuff.

**Comment by stsrki** [comment]
@Marfusios Yes, it's just a safe way to make sure the right field name is always set. In case something is refactored or renamed.

**Comment by buzzer83** [comment]
> I know it's not ideal but for now it's best option.
TY
