### ISSUE TITLE
Collapse component?

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#77]
Hello,

I notice your namespace has a "Collapse" component defined. But there is no mention if it in your docs or examples of how to use it. Is this something you intended to publish?

I ask, because I am seeking an Accordion or Collapse right now and am struggling to get one that works...

**Comment by stsrki** [comment]
Yes it's intended to be there. Just haven't documented it yet. When I started working on Blazorise I tried to support as many components from Bootstrap and Bulma to see where they both fit. I guess there is more components from that phase that I forgot of but they should still work. If not please report me an issue and I will look at it. In time those component will also be documented.

**Comment by aford22** [comment]
Tried to use the Collapse component. However the content is always displayed and never collapsed/hidden. I tried two ways of doing this:
```
<Blazorise.Collapse IsOpen="@IsOpen">
    <ChildContent>
        Collapsable content went here...
    </ChildContent>
</Blazorise.Collapse>
```
and 
```
<Blazorise.Collapse IsOpen="@IsOpen">
        Collapsable content went here...
</Blazorise.Collapse>
```
where `@IsOpen` is a boolean member variable toggled using a button.
