### ISSUE TITLE
Spinkit Implementation

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#777]
Implementation of Spinkit: https://tobiasahlin.com/spinkit/

It would be nice to have it implemented with all those options in the ThemeOptions of Blazorise

Thank you!

**Comment by robalexclark** [comment]
I'm currently using BlazorPro.Spinkit by Ed Charbaneau. This is already based on the Tobias Ahlin spinnkit. Do you think we should merge in this repo into the blazorise project (if this is permitted)?

**Comment by WillianGruber** [comment]
Yes, it would be nice, but that repo has no license attributed. Anyway, that level of customization is what I expect to be in ThemeProvider :)
