### ISSUE TITLE
Demo error on sidebar

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#781]
**Describe the bug**
"Forms" item starts with wrong expand/collapse icon, and once clicked, only change the icon. Further clicks start to expand/collapse subitems.

**To Reproduce**
Go to https://materialdemo.blazorise.com/tests/forms
See error in Forms item

**Screenshots**
![image](https://user-images.githubusercontent.com/56033692/79873871-0fc7d200-83be-11ea-81ef-9924cc116565.png)

**Comment by WillianGruber** [comment]
*The bug only happens once, so you can refresh to test it after 1st click*

**Comment by stsrki** [comment]
Already fixed and released with 0.9.0.1
