### ISSUE TITLE
Data Annotations and manual validation not working together

### ISSUE THREAD

**Issue by martinscholz83** [stsrki/Blazorise#782]
**Describe the bug**
When using Data Annotations validation together with manual validation, the Validator event handler ist not called and the TextEdit is showing green even i enter invalid text.
For example
```razor
<Validations @ref="validations" Mode="ValidationMode.Manual" Model="newSetting">
...
...
<Validation Validator="@ValidateDwordValue">
                                <TextEdit id="input_value" class="form-control" @bind-Text="item.IntValue">
                                    <Feedback>
                                        <ValidationError>Not a valid number</ValidationError>
                                    </Feedback>
                                </TextEdit>
                            </Validation>
...
...
@code {
private void ValidateDwordValue(ValidatorEventArgs e)
{
        var val = Convert.ToString(e.Value);

        e.Status = string.IsNullOrEmpty(val) ? ValidationStatus.None :
            Regex.Match(val, "(^0[xX][0-9a-f]+$)|(^[0-9a-f]+$)").Success ? 
        ValidationStatus.Success : ValidationStatus.Error;
}

private async void HandleSubmit()
{
      var validate = validations.ValidateAll();
      ...
     ...
}
```
Validation of the model Annotations are working.

**Expected behavior**
EventHandler should be called.

**Screenshots**

**Comment by martinscholz83** [comment]
[Here](https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Validation.razor.cs#L175-L208) that validatorHandler should checked first, or?

**Comment by stsrki** [comment]
That is by design. You cannot use validation handler and annotation validation at the same time. As soon as you set Model, Blazorise will switch to the data annotation mode.

**Comment by martinscholz83** [comment]
Ok. So only solution is to remove the Model and create validation handlers for that fields. Does it make sense to create a feature request on that at blazer? I didn’t know the details but why it shouldn’t be possible to validate both?

**Comment by stsrki** [comment]
Starting from v0.9.2 you can now mix validation methods where they will be used by the priority(whichever comes first)

1. Method Validator
2. Pattern validator
3. Data Annotation Validator
