### ISSUE TITLE
Blazor 0.9 chart size not being scaled properly - always small

### ISSUE THREAD

**Issue by intech-paul** [stsrki/Blazorise#787]
I initially packaged the line chart demo code into a component, and noticed the size of the chart remained small no matter how I tried to size it. I then took  the normal chart demo code and tried to size it there and I get an identical result of graph size.

![image](https://user-images.githubusercontent.com/56703036/79942242-7cc09200-84ba-11ea-9d20-584a8c10a392.png)

The code to draw a normal chart is:
<LineChart @ref="lineChart" TItem="double" />

and the test code is:

    <Fields>
    <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <FieldLabel>text 1</FieldLabel>
        </Field>
        <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <FieldLabel><LineChart @ref="lineChart" TItem="double" /></FieldLabel>
        </Field>
        <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <FieldLabel>Text 2</FieldLabel>
        </Field>
    </Fields>

Is there a correct way to size the chart that I am missing ?

**Comment by stsrki** [comment]
This should work, source: https://stackoverflow.com/a/49039089/833106

```cshtml
<Fields>
    <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <FieldLabel>text 1</FieldLabel>
    </Field>
    <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <div class="chart-container">
            <LineChart @ref="lineChart" TItem="double" OptionsObject="new {Responsive=true, MaintainAspectRatio =false}" />
        </div>
    </Field>
    <Field ColumnSize="ColumnSize.IsThird.OnDesktop">
        <FieldLabel>Text 2</FieldLabel>
    </Field>
</Fields>
```

**Comment by intech-paul** [comment]
That works for me, heres a really nice sample:

![image](https://user-images.githubusercontent.com/56703036/80060627-2408fc00-8583-11ea-88fb-b9dc81376cd1.png)

This version also solves the chart redrawing issue I had a while ago, when the browser window is sized, the chart position is updated correctly.
