### ISSUE TITLE
Upgraded to 0.7 project fails to render

### ISSUE THREAD

**Issue by toddlang** [stsrki/Blazorise#79]
Have a project happily working on 0.6.4/Preview 3, upgraded to 0.7/Preview 4, now Blazorise appears to completely fail to render.

I can see elements being written out to my browser, for example:
```
<div class="app-main">
    <NavBar Username=@State.Authentication.Name IsAuthenticated=@State.Authentication.IsAuthenticated />
```
comes out as
```
<div class="app-main">
   <navbar username></navbar>
```

So...._something_ is happening, but it's otherwise basically empty content now.

I've checked and re-checked the getting started guide, and the only really significant difference is the missing reference to the tag helper.  Is that still supposed to be added?

**Comment by stsrki** [comment]
I think you failed to name the component. It should be `Bar `instead of `NavBar`.

In preview4 there should be only `@using` namespace, no tag helpers any more.

**Comment by toddlang** [comment]
You're absolutely right, I got hosed by the namespace changes.

My apologies.
