### ISSUE TITLE
Define ElementId on a component

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#791]
I'm now starting to write my unit test for a solution with lots of blazorize components. To produce the unit tests I am using the bunit library https://bunit.egilhansen.com/ which intenally uses anglesharp to determine what markup should look like and whether the expected html matches the actual html.

One minor issue I am finding is that each render by blazorise produces a different DOM id for elements e.g. "0HLULBI8IG3K3" which means that actual html will change on each run (and so won't match the expected html specified in the test).

Are we able to either omit the id or specify it (so it doesn't change) or make it so it is consistent on each run?

**Comment by stsrki** [comment]
There was already some talk about this feature. I've being thinking much about it lately and I will need to investigate more. A lot of components are depending on this ID to work with java-script. If I would allow the change it can lead to possible problems later on. 

Anyways I will investigate and will get back to you.

**Comment by StefH** [comment]
> Are we able to either omit the id or specify it (so it doesn't change) or make it so it is consistent on each run?

I think a better solution would be that the ID-Generator code is made injectable using an interface. In that way unit-tests can provide a mock for that ID-generator,

**Comment by stsrki** [comment]
@StefH That is actually a great idea. I can do it as part of #981

**Comment by stsrki** [comment]
This is only going to be possible with `IComponentActivator` introduced in .Net 5. Since v0.9.2 is going to have support for both .Net Core 3.1 and .Net 5 there is no easy way for me to do this. So after v0.9.2, I will focus on .Net 5 only and I will also add support for custom IDs

So, moving this for 0.9.3.

**Comment by stsrki** [comment]
@robalexclark @StefH I know it's a little late but this was not possible before .Net 5 came along.

Currently, I'm working on this and so far I have implemented:

- `IIdGenerator`, to allow for custom generators
- `ElementId` can now be defined as a component parameter

The result, with default settings, looks like this:

![image](https://user-images.githubusercontent.com/900302/102787853-02764380-43a2-11eb-98d6-b409aebdfef6.png)

Applying ID to all components seems like an overkill but there is no way around it. Do you guys think this is OK? Thanks

**Comment by robalexclark** [comment]
I think, if I understand correctly, that a custom Id can be applied to a component which never changes on each compile/run, then this is exactly what I need - thanks!

**Comment by stsrki** [comment]
@robalexclark yes that is what is going to be possible now. The only problem is that id will also be applied to all other elements. By default it will be some generated string.
