### ISSUE TITLE
Weird graphics for Switch in Material

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#799]
**Describe the bug**
In the end of https://materialdemo.blazorise.com/tests/forms the switch has no background graphics and it appears as a strange circle:

![image](https://user-images.githubusercontent.com/56033692/80005963-a7025780-849a-11ea-865c-6cf0de6de83f.png)
![image](https://user-images.githubusercontent.com/56033692/80006001-af5a9280-849a-11ea-8c3e-50ceb25d8e1e.png)

Is this a bug?

Edit: Material provider

**Comment by stsrki** [comment]
Seems like a bug.
