### ISSUE TITLE
Card Title and Subtitle overlapping

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#800]
![image](https://user-images.githubusercontent.com/56033692/80007818-314bbb00-849d-11ea-8e88-99e96b04d3f0.png)

When using Title and Subtitle in Header, the texts overlap:

```
    <Card Margin="Margin.Is3.OnAll">
        <CardHeader>
            <CardTitle>
                New Business Document Definition
            </CardTitle>
            <CardSubtitle>
                Define properties for the new document.
            </CardSubtitle>
        </CardHeader>
        <CardBody>
            Dummy content
        </CardBody>
    </Card>
```

I'm not using any image, its just Header with title/subtitle and a Body with lots of content

**Comment by stsrki** [comment]
Only `CardTitle` is recomended to be placed inside of `CardHeader`.

Both `CardTitle` and `CardSubtitle` can be saved inside of `CardBody`.

**Comment by WillianGruber** [comment]
OK, thank you!
