### ISSUE TITLE
AutoComplete

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#81]
Blazorize has some autocomplete control?

**Comment by stsrki** [comment]
There is no _high-level_ components like autocomplete for now. That is entirely on the developer to create them by using basic Blazorise components. The idea behind Blazorise is to have basic _low-level_ components that can be combined to create some _high-level_ components like autocomplete, grid, etc.

I could add autocomplete component to some of the future milestones if there is interest. For now your best bet is to create it yourself. It should not be that hard I think.

**Comment by carlosast** [comment]
Will you develop autocomplete?

**Comment by stsrki** [comment]
Well, it's on the to-do list but currently I don't have much time to do it. Maybe sometime in the next few weeks.

If you manage to do it by yourself please create a PR.

**Comment by carlosast** [comment]
I need this control so badly

**Comment by stsrki** [comment]
It will be done in the next release.

**Comment by carlosast** [comment]
thank you

**Comment by stsrki** [comment]
@carlosast Can you tell me more about how you want to use the Autocomplete? What I'm interested the most is:

1. Do you load all your data into the memory and then filter it in Autocomplete component?
2. Search it asynchronously every time you type in the search field?

**Comment by carlosast** [comment]
Hi Mladen,

Search it asynchronously every time you type in the search field

**Comment by carlosast** [comment]
Thank you very much
