### ISSUE TITLE
Docs have a text field in Attribute description

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#811]
![image](https://user-images.githubusercontent.com/56033692/80130706-6f191400-856f-11ea-8f9c-41859673bfc4.png)

https://blazorise.com/docs/components/text/#attributes

Guess that is a misstype

**Comment by stsrki** [comment]
I didn't mark `<input>` as code with back-tick and markdown generated it as an input.

**Comment by stsrki** [comment]
Fixed
