### ISSUE TITLE
Visibility attribute not working on 'Card' component

### ISSUE THREAD

**Issue by paiden** [stsrki/Blazorise#827]
**Describe the bug**
I use cards to display some related fields. If I set the visibility attribute of the card like this:

```html
<Card Visibility="Visibility.Never" ...>
   ... 
</Card>
```
the card is still visible.

**Expected behavior**
Card is not visible in the UI.

**Additional context**
Blazorise version is: 0.9.0-preview2

**Comment by stsrki** [comment]
I tried with all the providers and it works on my machine. `0.9.0-preview2` is quite old but it should still work.

Maybe you have something else defined on Card that can influence the behavior.

**Comment by stsrki** [comment]
OK I know what is the issue. In older version the Style was not applied to every component. This is fixed. You need to update to the latest v0.9.0.1 and it should work.

**Comment by paiden** [comment]
Yes after upgrading it works.

Thanks for the incredibly fast help. You're the best.
