### ISSUE TITLE
Issues with CheckEdit

### ISSUE THREAD

**Issue by Raveen87** [stsrki/Blazorise#83]
Hi!

I'm having issues with the CheckEdit component. If I used bind-Checked the bound variable is not getting updated, and if I use Checked and CheckedChanged I'm not getting a callback.

However, if I used the TextEdit component together with the CheckEdit component, I can get updates to my bound variable or get callbacks.

So if I use a setup like this:

```
<CheckEdit bind-Checked="@bindRemembered">Remember me</CheckEdit>
<p>You will be remembered: @bindRemembered</p>

<CheckEdit Checked="@eventRemembered" CheckedChanged="@OnRememberMeChanged">Remember Me</CheckEdit>
<p>You will be remembered: @eventRemembered</p>

<TextEdit bind-Text="@bindName" />
<p>Your name is: @bindName</p>

<TextEdit Text="@eventName" TextChanged="@OnNameChanged" />
<p>Your name is: @eventName</p>

@functions {
	bool bindRemembered;
	bool eventRemembered;
	string bindName;
	string eventName;

	void OnRememberMeChanged(bool value)
	{
		eventRemembered = value;
	}

	void OnNameChanged(string value)
	{
		eventName = value;
	}
}
```

my bindRemembered  will be set to true when both the checkbox is checked and I enter text into the TextEdit bound to bindName.
And eventRemembered will be set to true when both the checkbox is checked and I enter text into the TextEdit with Text and TextChanged.

Have I misunderstood something or am I doing something wrong?
I've tried it out in an empty project (just using the template: Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview4-19216-03) with only these modifications.

I'm not entirely sure exactly what steps I have to take to "remove default bootstrap css and js files that comes with the Blazor" that you mention in the guide, but the other components I have tried seem to work like expected.
What I have done in this step is to remove the ```<link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />``` that's in index.html.

**Comment by stsrki** [comment]
It's behaving like that because `CheckedChanged` event is still using `Action` instead of newest `EventCallback`. In the oldest versions of Blazor you needed to call `StateHasChanged` on every change. So they introduced `EventCallback` which is calling it automatically for you.

This should be pretty small fix so I will do it in 0.7.1. It will be released probably tomorrow.

Regarding your question about css and js file. Yes you should remove the links to the bootstrap files located in the wwwroot when you created the Blazor app.

**Comment by Raveen87** [comment]
Oh, got it. Thanks for the quick response and keep up the awesome work. 👍

**Comment by armandjordaan-inovo** [comment]
Hello!

I am having a similar problem and I cannot figure out why the code below does not work.
The ```Clicked``` method is only called when the checkbox is ticked. If I removed ```Checked = "@tempbool"```, then the ```Clicked``` method is called for both ticking and unticking.

Am I doing something wrong here?

```
@{
    <div class="row">
        @debug
    </div>
    <div class="row">

        @for(int i=0; i<BoolArray.Count(); i+=ItemsPerColumn)
        {
            <div class="col-3">
                @for(int j=i; j<(i+ItemsPerColumn); j++)
                {
                    var guid = GuidArray[j];
                    var content = j.ToString();
                    var tempbool = BoolArray[j];
                    <CheckEdit Checked="@tempbool" 
                                       CheckedChanged="(bool val) => { Clicked(guid,val); }"> 
                                       @content 
                    </CheckEdit>
                }
            </div>
        }
    </div>
}

@code {
    [Parameter]
    public int ItemsPerColumn {get; set;} = 4;

    [Parameter]
    public bool[] BoolArray {get; set;}

    public string[] GuidArray {get; set;}

    private string debug = "";

    private bool Chk = false;

    protected override void OnInitialized()
    {
        GuidArray = new string[BoolArray.Count()];

        for(int i=0; i<GuidArray.Count(); i++)
        {
            GuidArray[i] = Guid.NewGuid().ToString();
        }  
    }

    void Clicked(string obj, bool value)
    {
        // TODO use guid to identify the bool value that was changed
        Chk = value;
        debug = obj;
        if (Chk)
        {
            debug += " set";
        }
        else
        {
            debug += " clear";
        }
        StateHasChanged();
    }
}
```
