### ISSUE TITLE
Icon Material - not in IconName enum

### ISSUE THREAD

**Issue by andreatosato** [stsrki/Blazorise#837]
I want to use custom [Material icon](https://material.io/resources/icons/)
I read Icon [docs](https://blazorise.com/docs/extensions/icons/) but solution not compile.

**Code**
This not work
```html
<Button OnClick="Create">
	<Blazorise.Icons.Material.Icon Name="create"></Blazorise.Icons.Material.Icon>
</Button>
```
Not work
```html
<Button OnClick="Create">
	<Icon Name="create"></Icon>
</Button>
```

Works
```html
<Button OnClick="Create">
	<Icon Name="IconName.Dashboard"></Icon>
</Button>
```

I can't use icon as string name. Blazor error:
**CS0103	The name 'create' does not exist in the current context**

How can I use all material icon as string?

Thanks in advice, Blazorise is great project!

**Comment by stsrki** [comment]
Blazorise works by giving you the default components that can be overridden with extensions or providers. So, working directly with extension is not recommended:

### Don't do this

```cshtml
<Button OnClick="Create">
    <Blazorise.Icons.Material.Icon Name="create"></Blazorise.Icons.Material.Icon>
</Button>
```

### Do this

```cshtml
<Button OnClick="Create">
    <Icon Name="IconName.Dashboard"></Icon>
</Button>
```

You already figured that out but I just wanted to explain. Now back to your question. `Name` property is of `object` type. This is needed so we can define the icon name as a string or as an enum. For enum is easy as razor will pick it up automatically. But for string it's little trickier. This is a known limitations that will unfortunately never be fixed. Anyways to define name as astring just do:

```cshtml
<Button OnClick="Create">
    <Icon Name="@("icon-name")"></Icon>
</Button>
```

**Comment by andreatosato** [comment]
Thanks a lot @stsrki
