### ISSUE TITLE
FluentValidation support

### ISSUE THREAD

**Issue by andreatosato** [stsrki/Blazorise#838]
Hi folks,
I work in many project with [fluentvalidation](https://fluentvalidation.net/). Can I use it like DataAnnotaion?
I read [docs](https://blazorise.com/docs/components/validation/#data-annotations) but I don't understand if FluentValidation can work already and how.
Thanks a lot

**Comment by stsrki** [comment]
I'm not familiar with FluentValidation so I cannot help you with that.

But regular data annotations are supported and you can see the example in the demo or in the documentation.

**Comment by JeffreySyme** [comment]
@andreatosato I built a dotnet core template with FluentValidation and Blazorise that you can take a look at. I just inject my validator into my component and call ValidateAsync for that field as a part of the validation callback. After validation runs I set the error message manually with the ValidatorEventArgs that is passed in.

[Filter Modal](https://github.com/JeffreySyme/SimpleBlazorServer/blob/master/SimpleBlazorServer.Web/Pages/WeatherForecast/Index/FilterModal.razor)

[ValidationComponent](https://github.com/JeffreySyme/SimpleBlazorServer/blob/master/SimpleBlazorServer.Web/Shared/ValidationComponent.razor.cs)

It is implemented with Blazor Server. I haven't tried this approach with Blazor Client but I think it could still work.

**Comment by andreatosato** [comment]
@JeffreySyme  thanks a lot, I will try it on Blazor client.
If work great, i think that can update blazorize docs.

**Comment by andreatosato** [comment]
@JeffreySyme works on Blazor Client.
Great works!

@stsrki Can we add some docs for this topic?

**Comment by stsrki** [comment]
@andreatosato absolutelly. If you could update validation docs and create a PR that would be great.

**Comment by niem94** [comment]
Another approach similar to the above is to extract the ValidateField logic to a service, and inject it where needed. I did this:

```csharp
public class FluentValidator
    {
        public Tuple<ValidationStatus, string> Validate(IValidator validator, IFluentValidatableModel model, string propertyName)
        {
            var properties = new[] { propertyName };
            var context = new ValidationContext(model, new PropertyChain(),
                new MemberNameValidatorSelector(properties));
            ValidationResult validationResult = validator.Validate(context);
            if (validationResult.IsValid)
            {
                return Tuple.Create<ValidationStatus, string>(ValidationStatus.Success, null);
            }
            return Tuple.Create(ValidationStatus.Error, validationResult.Errors.FirstOrDefault().ErrorMessage);
        }
    }
```

And this can be utilized by Validators like so: 

```csharp
 <Validation Validator="@((e) => (e.Status, e.ErrorText) = FluentValidator.Validate(Validator, Stakeholder, nameof(Stakeholder.Name)))">
```

The code in Validate can be made a quite a bit shorter as seen in @JeffreySyme example, but with the service it is no longer needed to create a validate method on all components.

**Comment by DariusScherle** [comment]
here is my solution for Blazor WebAssembly:

self created validationcomponent:
```
public abstract class ValidationComponent : ComponentBase
{
	protected async Task ValidateFieldAsync(IValidator validator, object model, ValidatorEventArgs args, string fieldName)
	{
		var property = new[] { fieldName };
		var context = new ValidationContext<object>(model, new PropertyChain(), new MemberNameValidatorSelector(property));
		var validationResult = await validator.ValidateAsync(context);

		if (!validationResult.IsValid)
			SetValidationState(args, validationResult);
	}
}
```

.razor:
```
@inherits ValidationComponent
<Validation Validator="async e => await ValidateFieldAsync(new YourFluentValidator(), model, e, nameof(ModelClass.Property))">
```
