### ISSUE TITLE
Rich text editor / markdown control

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#841]
It would be great if Blazorise would contain a rich text editor / markdown control.

Good examples are the ones available in stackoverflow or even the one I use here in github writing this issue.

Keep up the good work

**Comment by WillianGruber** [comment]
That would be awesome

**Comment by njannink** [comment]
In my project I use the javascript simplemde package atm

**Comment by stsrki** [comment]
This one looks good https://quilljs.com/

**Comment by njannink** [comment]
That one looks fine indeed. No markdown support though, but there are libs that do transformation back and forth of html and markdown.

**Comment by stsrki** [comment]
@njannink  I'm open to suggestions so If you could list few possibilities that would be great.

**Comment by WillianGruber** [comment]
I used http://nicedit.com/ in one project some years ago, maybe it could help

**Comment by njannink** [comment]
That nicedit seems a dead project to me. Latest release from okt 2015. QuilJs looks like an active js library with lots of contributors.

@stsrki I used https://github.com/sparksuite/simplemde-markdown-editor but that is more a markdown editor than a rich text editor. I think quiljs is sufficient since for most end-users writing markdown is a no go. So quiljs would be a better match then

**Comment by stsrki** [comment]
We can always have separate component for markdown. I think quilljs is really good candidate.

**Comment by WillianGruber** [comment]
Perfect for me!

**Comment by njannink** [comment]
Im working on creating this extension using QuillJS expect a PR in one of the comming days
