### ISSUE TITLE
Sidebar full width on mobile

### ISSUE THREAD

**Issue by njannink** [stsrki/Blazorise#845]
I'm trying to get my sidebar to full width on mobile when toggling the Sidebar.

Any ideas how to acomplish this?

**Comment by stsrki** [comment]
It's not possible currently. Maybe it can be done by tweeking css on your side.

But I think the best option is to wait a little more for new version of Blazorise. @MitchellNZ is working on support for vertical Bar and I think this could be supported natively by Bootstrap and its navbar.

**Comment by njannink** [comment]
I already tried a bit with tweeking the css, but didnt got very far. I will wait a bit then since I got a working solution now with the navbar from bootstrap and the Blazor templates

**Comment by MitchellNZ** [comment]
This was fixed in 0.9.1 as part of https://github.com/stsrki/Blazorise/pull/954
