### ISSUE TITLE
Modal scrolls to top of page

### ISSUE THREAD

**Issue by erikosterholm83** [stsrki/Blazorise#847]
When clicking up an modal the page scrolls to top of page
in blazorise.bootstrap.js:
element.querySelector('.modal-body').scrollTop = 0;

Maybe have this an option and not always do it? If you check https://getbootstrap.com/docs/4.4/components/modal/ it will not scroll to top of page.

**Comment by stsrki** [comment]
I think this can be done as an option when modal is opened. Since the change is rather small I will push it for v0.9.1.
