### ISSUE TITLE
Roadmap request

### ISSUE THREAD

**Issue by MarkStega** [stsrki/Blazorise#85]
It would be useful to have a roadmap of proposed component additions and enhancements either as an addition to the readme, and additional file, or individual issues.

As examples I'd love to know if a templated listbox or a datetime control is/are in the plans.

**Comment by stsrki** [comment]
Do you mean something like this https://github.com/aspnet/AspNetCore/issues/8177 ?

**Comment by MarkStega** [comment]
Yes, that would be perfect; It doesn't have to have fixed dates or anything; just needs to give a general sense of where the project is headed and where outside contribution would be welcomed. Another example using the issue list is [https://github.com/Blazored/Gitter/issues](https://github.com/Blazored/Gitter/issues)

**Comment by stsrki** [comment]
Well I'm already using issues list as roadmap, kinda. Now I could create a special Roadmap issue and group all of the issues by release numbers.

**Comment by stsrki** [comment]
Created #88
