### ISSUE TITLE
Minor Bar Documentation Update

### ISSUE THREAD

**Issue by Likai-CK** [stsrki/Blazorise#850]
Hello!
Just wanted to share that I ran into a challenge when trying to change colors of components like that nav bar, which still say to use the **Color** and **Theme** attributes in [the documentation](https://blazorise.com/docs/components/bar/). It wasn't until I found the following pull request #130 that I found it was changed and was fulfilling the purpose of Theme in the code example.

**Comment by stsrki** [comment]
I have fixed the documentation. Thank you!
