### ISSUE TITLE
Expose EditContext as an attribute of Validations

### ISSUE THREAD

**Issue by cowsen** [stsrki/Blazorise#851]
I would like to use EditContext,Validate() to disable buttons until the form passes all validations.

As an example:

```cshtml
<Form>
    <Validations Mode="ValidationMode.Auto" Model="@Selections" EditContext="@EditContext">
</Validations>
    <Button Disabled="true"  Clicked="@Import">Import</Button>
</Form>

 protected override void OnInitialized()
    {
        Selections = selectionsService.Get();

        EditContext = new EditContext(UserSpecificSelections);
        EditContext.OnFieldChanged += EditContext_OnFieldChanged;

        SetDisabled();

        base.OnInitialized();
    }

// logic to support page controls
    // Button
    private void EditContext_OnFieldChanged(object sender, FieldChangedEventArgs e)
    {
        SetDisabled();
    }

    private void SetDisabled()
    {
        if (EditContext.Validate())
        {
            IsDisabled = false;
        }
        else
        {
            IsDisabled = true;
        }
    }
```

**Comment by stsrki** [comment]
Hi @cowsen 

You already have event `ValidatedAll` on `Validations` components that can be used for your scenario.

**Comment by cowsen** [comment]
I can get the event callback to call the handler (e.g. (ValidatedAll="eventHandler").  But what event args are passed to check the validation status in the event handler?

**Comment by stsrki** [comment]
ValidatedAll has no parameters. It just notified that all underline validations are successfull.

**Comment by cowsen** [comment]
But, how do I get an event callback when validation fails, so I can disable a button?  If ValidatedAll called a handler in the event of all validation change events and passed an event argument with the validation status, I could check that status in the event handler and toggle the button's disable attribute.  I thought that was the purpose of EditContext - it provided an on change event (OnFieldChanges) that you could register an event handler and it provided method to check the status (ValidateAll()).

**Comment by stsrki** [comment]
I can see the problem. You basically want an event that will fire-on whenever there is a change in any of validation. It can be done.
