### ISSUE TITLE
Allow <Tooltip> to be used around on <SelectItem>

### ISSUE THREAD

**Issue by niem94** [stsrki/Blazorise#856]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to use tooltips with select items. I have a use case where this would be nice.

**Describe the solution you'd like**
I'd like it to be possible to do something like this to show a tooltip when mousing over a select option:

```Csharp
<Select TValue="int" SelectedValue="@value" SelectedValueChanged="@OnSelectedValueChanged">
        <Tooltip Multiline="true" Text="This is a tooltip">
            <SelectItem Value="value">option</SelectItem>
        </Tooltip>
</Select>
```

**Comment by stsrki** [comment]
The reason is simple. `<select>` expects `<option>` element as direct child, and since `Tooltip` acts as a wrapper it will break the semantics. The best you can do is to use native tooltips.

```cshtml
<Select TValue="int" SelectedValue="@value" SelectedValueChanged="@OnSelectedValueChanged">
    <SelectItem Value="value" title="This is a tooltip">option</SelectItem>
</Select>
```

**Comment by niem94** [comment]
Maybe this can be accomplished by supporting the “title” attribute indtead? 

In plain html it can be used like so to provide a tooltip for options:

```html
<select>
<option value="1" title="Cheese">A</option>
<option value="2" title="Mango Chutney">B</option>
<option value="3" title="Key Lime Pie">C</option>
<\select>
```

**Comment by niem94** [comment]
> The reason is simple. `<select>` expects `<option>` element as direct child, and since `Tooltip` acts as a wrapper it will break the semantics. The best you can do is to use native tooltips.
> 
> 
> 
> ```cshtml
> 
> <Select TValue="int" SelectedValue="@value" SelectedValueChanged="@OnSelectedValueChanged">
> 
>     <SelectItem Value="value" title="This is a tooltip">option</SelectItem>
> 
> </Select>
> 
> ```

Thanks that solved it!

**Comment by stsrki** [comment]
Every component has attribute splatting, so title will be automatically picked-up and applied to the `<options`> element

**Comment by niem94** [comment]
> Every component has attribute splatting, so title will be automatically picked-up and applied to the `<options`> element

That is pretty clever, i had been wondering if id loose out on something related to blazorise if using native html attributes :-)
