### ISSUE TITLE
Datagrid pager

### ISSUE THREAD

**Issue by SandroRiz** [stsrki/Blazorise#857]
If you have, let's say 35 items in your grid and pageSize is 10, you correctly present 4 link for the 4 pages
1 - 2 - 3 - 4
The same if you are on page 2 or 3, but if you are on the last page, you present only 3 links ( 2- 3- 4)
Why ?

Addition: how can I translate the terms Prev, Next, etc and do a templating of some aspect (eg. style of current page, etc.)

Thanks

**Comment by stsrki** [comment]
The reason is that `MaxPaginationLinks` is set to 5. So when you're on page 1 you can go from 1 to 5 page links. When you're on page 4 for example you will still need see max of 5 links but they are counted with offset to the left and to the right, 2-3-4-5-6, with 4 in the middle.

Now it seems there is a slight miscalculation as it didn't take in account maximum number of pages. That is a bug.

**Comment by SandroRiz** [comment]
Thank you.
What about the possibility to edit the pager? I read in the 0.9 release notes 
_Added some new templates for previous and next pagination buttons.
New styling properties to allow custom classes and styles for rows, cells, header and filter._

but I don't find any documentation how to change

**Comment by stsrki** [comment]
That is just to option to replace prev and next links with your own markup. For page numbers there is still no alternate styling available.

**Comment by robalexclark** [comment]
@SandroRiz  You can always override classes in your own css, for example to change the size (padding) of the pager boxes:

```
.page-link {
    padding: .3rem .6rem;
}

```

**Comment by omar0402** [comment]
How can I edit the css class for a paging component that it´s part of a DataGrid component?

**Comment by robalexclark** [comment]
There are probably lots of ways to override the default css provided by blazorise but in the past I have created an overriding css class .page-link {...} in my main site.css file and set the desired padding etc there.

**Comment by omar0402** [comment]
@robalexclark 
Yeah, I noticed that, but I'm talking about the pagination component that you invoke on the dataGrid with the attribute *ShowPager*, I want to center it, but it's applying a div tag with the "justify-content-between" class by default.
