### ISSUE TITLE
Lag/Slowness in typing into a bound TextEdit when .razor file is large

### ISSUE THREAD

**Issue by jecourtney** [stsrki/Blazorise#868]
There seems to be a lag in typing and characters/words displaying in pages with a lot of fields/tabs.  My example is about 1,000 lines of code.  It is really not an unreasonably sized page.  At first, I thought this was a Blazor server-side issue, so I tried a client-side version and it seems worse: at least for displaying letters as you type.  *Note, this is all localhost for the client-side example, so no Blazor 100ms lag issue here.  Again, this is a client-side example.  

The best way to illustrate this problem is with a screen capture:
http://files.unitedmcgill.com/owncloud/index.php/s/ssFBPUoIvHP6ugz
The video illustrates there are no issues with bound and unbound Blazor input fields.  Just a problem with bound TextEdit.

Much appreciated if anyone can shed some light on this?  Testing on pages with fewer fields seems more responsive.  Strange that entry responsiveness is affected by the amount of other stuff on the page...

I may make a video later of the server-side.

**Comment by stsrki** [comment]
That is really slow. I think the problem is in how Blazor is doing the updates. Whenever you type you will trigger the `TextChanged` event callback. Blazor will update your variable that have binded with `@bindText="@someText"`, and after that it will call `StateHasChanged()`. Which will trigger the page refresh.

There is not much we can do except to disable update on each key-press. By default all input are triggered with `@oninput`. The alternative is to use `@onchange`. To enable usage of `@onchange` you set `ChangeTextOnKeyPress` to `false`.

```cs
builder.Services
    .AddBlazorise( options =>
    {
        options.ChangeTextOnKeyPress = false;
    } )
    .AddBootstrapProviders()
    .AddFontAwesomeIcons();
```

**Comment by jecourtney** [comment]
The following code snippet lets you play around with more fields.  I have 65 fields on the page, inside some tabs, validations, etc.  However, setting the code below to nSize = 65 is still pretty responsive, noticeable lag though.  Going to 128 better reproduces the slowness of what I showed above.

`@page "/SlowTest"

<h3>SlowTest</h3>
<Divider />

    @for (int i = 0; i < TestList.Count; i++)
    {
        int nBlazor = i;
        <Field Horizontal="true">
            <FieldLabel>Test Field @nBlazor.ToString("000"):</FieldLabel>
            <FieldBody>
                <TextEdit MaxLength="80" @bind-Text="TestList[nBlazor]">
                    <Feedback />
                </TextEdit>
            </FieldBody>
        </Field>
    }


@code
{
    private Validations testValidations;
    private int nSize = 65;
    private List<string> TestList = new List<string>();

    protected override void OnInitialized()
    {
        for (int i = 0; i < nSize; i++)
        {
            TestList.Add(String.Empty);
        }

        base.OnInitialized();
    }
}`

**Comment by jecourtney** [comment]
Just saw your post, I will try and report back.  Thanks

**Comment by jecourtney** [comment]
Setting `@onchange()` made all the difference!  Thanks for the fix.
`options.ChangeTextOnKeyPress = false;`
