### ISSUE TITLE
MemoEdit does not have Feedback Validation Error

### ISSUE THREAD

**Issue by SandroRiz** [stsrki/Blazorise#874]
The MemoEdit component seems not to render the ValidationError (and I guess also *None and *Success) string.

_BTW (in documentation, bad 404 link in the bottom note (Note: For a full source code you can look at the validation page inside of a demo application.)_

**Comment by dfkeenan** [comment]
This is pretty easy to fix. The `@Feedback` just has to be added here: https://github.com/stsrki/Blazorise/blob/794b27446a78f48d408ca07ed3b877f6c141b96d/Source/Blazorise/MemoEdit.razor#L5-L6

**Comment by dfkeenan** [comment]
As a work around you can also use something like:

```html
<MemoEdit Rows="5" @bind-Text="@TheField">
    <ChildContent>
        <ValidationError />
    </ChildContent>
</MemoEdit>
```

**Comment by stsrki** [comment]
Fixed
