### ISSUE TITLE
Question: Streaming charts - howto assign specific "datastreams" to specific datasets

### ISSUE THREAD

**Issue by erikthysell** [stsrki/Blazorise#875]
I have a question that I need some help on: 
I try to use your example for [streaming charts](https://blazorise.com/docs/extensions/chart/#streaming).
However, I do not understand howto push data to specific curves. If I understand correctly, it calls 
```
    Task OnMeasurementRefreshed(ChartStreamingData<LiveDataPoint> data)
        {
           
            data.Value = new LiveDataPoint
            {
                X = DateTime.Now,
                Y = RandomScalingFactor(),
            };

            return Task.CompletedTask;
        }
```

For each dataset when refreshed (?).
However.. I have for example 5 curves that are simultaneously refreshed each second. How do I assign the correct value for each curve? (not just a random value)????
Any help would be most useful and thanks for a great package!

**Comment by stsrki** [comment]
Well it seems I have accidentally forgot to add `DatasetIndex` to the `ChartStreamingData `event argument. Sorry about that. I will add it and will release it with the next preview.

After that you will be able to determine which dataset needs an update.,

**Comment by erikthysell** [comment]
Thanks a lot for the quick action and explanation!
Looking forward to the solution :)

**Comment by stsrki** [comment]
Done!
