### ISSUE TITLE
DataGrid ReadData manual call

### ISSUE THREAD

**Issue by SynapsesConsortium** [stsrki/Blazorise#878]
Is there any way to call ReadData from another component?
I have a FileUpload that processes some data that I want to display on a DataGrid, and I got it working by using the ReadData. The only problem is that for the ReadData to be called I have to do any interaction with the DataGrid, for example, sort a column.
Thanks.

**Comment by stsrki** [comment]
ReadData is used to handle all outside data sources, but it also comes at a cost as you also need to do it by yourself. That is the intended behavior. 

Have you tried calling the StateHasChanged()? If that doesn't help I can consider adding a method on grid to force refresh.

**Comment by SynapsesConsortium** [comment]
Yes, I tried calling StateHasChanged(), but the DataGrid didn't change.

`@code {
    int totalResults;
    List<ResultViewModel> resultViewModelList = new List<ResultViewModel>();

    async Task OnChanged(FileChangedEventArgs fileChangedEventArgs)
    {
        var file = fileChangedEventArgs.Files.FirstOrDefault();
        if (file != null)
        {

            var memoryStream = new MemoryStream();
            await file.WriteToStreamAsync(memoryStream);

            resultViewModelList = await TextractService
                .ProcessFileAsync(memoryStream)
                .ConfigureAwait(false);
        }

    async Task OnReadData(DataGridReadDataEventArgs<ResultViewModel> e)
    {
        resultViewModelList = resultViewModelList;
        totalResults = resultViewModelList.Count;

        StateHasChanged();
    }
}`

**Comment by stsrki** [comment]
I think you don't need to use `OnReadData()` in your case. You can just set resultViewModelList and totalResults directly in `OnChanged()` As long as they are binded to Data and TotalItems it should work.

**Comment by SynapsesConsortium** [comment]
I just tried that, but even after the StateHasChanged(), the grid is still empty.
Even though the resultViewModelList isn't empty anymore, the grid doesn't refresh.

**Comment by stsrki** [comment]
Possible with `.Reload()` method in 0.9.3.

**Comment by AlexTeixeira** [comment]
Hi, 
 
Can you provide an example of **Reload()** usage with the datagrid method ?

**Comment by stsrki** [comment]
Sure. 

First, create a Datagrid variable

```
@code{
  private DataGrid<Employee> dataGrid;
}
```

then assign it to the ref

`<DataGrid @ref="dataGrid" >`

and call the function

`await dataGrid.Reload()`
