### ISSUE TITLE
Databound Sidebar with Icons

### ISSUE THREAD

**Issue by hardkorehak** [stsrki/Blazorise#880]
I am not seeing any way to include an icon into a Sidebar that is bound to a recordsource. In SidebarItemInfo I use Text and To (skipping ToolTip and Visible ) and build out the SubItems. I have tried plugging a <span class="fas fa-users" /> (for example) into the Text, but it gets rendered literally. Would be incredibly helpful to have a way to include my icons field to present for each item.

**Comment by stsrki** [comment]
Haven't thought of that to be honest. Shouldn't be too hard so I think I can do it as part of 0.9.1
