### ISSUE TITLE
<check> CheckChanged

### ISSUE THREAD

**Issue by N8Lentz** [stsrki/Blazorise#885]
**Describe the bug**
Using `<check>` and the checkchanged parameter to add values into a field. Once I add the checkchanged the checkbox will no longer check. Plus the method does not fire. 

**To Reproduce**
   

**Expected behavior**
I expect the check to be check able while still adding the total
Also please provide a sample code or point us to a minimalistic GitHub repo

 ```
<Check TValue="bool" Checked="@cb" CheckedChanged="@Add"></Check>
    <NumericEdit TValue="int" ReadOnly="true" Value="@Total"></NumericEdit>

@code {

    private bool cb { get; set; }
    private int Total { get; set; }
    private int allowance { get; set; } = 1;
    private void Add()
    {
        if (cb == true) { allowance = 1; } else { allowance = 0; }
        Total = allowance;
    }
}
```

**Screenshots**

**Additional context**

**Comment by stsrki** [comment]
When you use manual two-way binding you must also update the variable by yourself. So for your example you must do:

```diff
<Check TValue="bool" Checked="@cb" CheckedChanged="@Add"></Check>
<NumericEdit TValue="int" ReadOnly="true" Value="@Total"></NumericEdit>

@code {

    private bool cb { get; set; }
    private int Total { get; set; }
    private int allowance { get; set; } = 1;
+    private void Add(bool checked)
    {
+        cb = checked;

        if ( cb == true )
        { allowance = 1; }
        else
        { allowance = 0; }
        Total = allowance;
    }
}
```

**Comment by N8Lentz** [comment]
Thanks, for the quick response. However, this does not seem to have the correct syntax. Below is a screen shot showing the errors. 
![GitHubAnnotation 2020-05-14 090635](https://user-images.githubusercontent.com/65310934/81944352-41e5e180-95c2-11ea-8990-7010bfcfeeb9.png)

Thanks again for the help.

**Comment by stsrki** [comment]
Sorry I was writing directly in markdown editor and I forgot that `checked` is a reserved keyword. Just rename it to something like value.

**Comment by N8Lentz** [comment]
Perfect. Thanks. That solved it.
