### ISSUE TITLE
Card figures are stretched in material only

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#889]
https://materialdemo.blazorise.com/tests/cards

Only in material the images are stretched vertically

**Comment by stsrki** [comment]
It seems that class `.card-img-top` is missing `width: 100%`.

**Comment by WillianGruber** [comment]
Hi, any chance this being adressed in 0.93?

**Comment by stsrki** [comment]
I'm using djibe material and it seems it is working now

![image](https://user-images.githubusercontent.com/900302/88259087-e4f16080-ccc1-11ea-93da-3a50e22ecedc.png)

**Comment by WillianGruber** [comment]
The demo is still stretched for me:
![image](https://user-images.githubusercontent.com/56033692/88288668-7d8bde80-ccca-11ea-9a68-18ab9193ed2d.png)
Has the demo page with latest djibe been released?

**Comment by stsrki** [comment]
No, the demo is still on older version.

**Comment by WillianGruber** [comment]
Latest djibe's version really fixed it. Guess its time to move to it, even with some margins need fixing. Thanks!
