### ISSUE TITLE
[New] SelectList component

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#89]
SelectList will be used as dynamically generated option input based on the supplied data.

## Parameters:

- `Data` (generic array type)
- `ValueField` (Func<TItem, object>)
- `TextField` (Func<TItem, object>)
- `SelectedValue` (object)
- `SelectedValueChanged`

## Usage:

```
<SelectList Data="@myList" ValueField="@(item=>item.SomeValue)" TextField="@(item=>item.SomeText)" bind-SelectedValue="@selectedItemValue">
<SelectList>
```

## Background

Internally it will use default Blazorise component SelectEdit and SelectItem.

**Comment by Lasoty** [comment]
Why Multiple selection is not implemented?
