### ISSUE TITLE
efrolic bar is unbalanced after 0.9

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#890]
Hi, looking at the bar at
https://efrolicdemo.blazorise.com/

There are too much space in the beggining ant end of the bar, like a big margin. Also, button distance from top is greater than from bottom

**Comment by stsrki** [comment]
That is actually how the margins for eFrolic bar is supposed to look like https://efraa.github.io/eFrolic/navbars

And for the distance from top and bottom I agree that is the bug.

**Comment by stsrki** [comment]
eFrolic is not maintained anymore by the author so I will slowly make it obsolete. No need to continue support it.
