### ISSUE TITLE
ColorEdit not aligned with horizontal label

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#893]
![image](https://user-images.githubusercontent.com/56033692/81899489-552c8900-9591-11ea-8dd7-3cb1940061b4.png)

Also can be seen on https://materialdemo.blazorise.com/tests/forms

**Comment by stsrki** [comment]
I don't see and problem in the demo. Can you show me your markup.

**Comment by WillianGruber** [comment]
What I mean is that the ColorEdit is above the "center", as in:
![image](https://user-images.githubusercontent.com/56033692/81938941-0cde8c80-95cc-11ea-8fba-1eea9fea3685.png)
(from https://materialdemo.blazorise.com/tests/forms)
Normally in other fields I see the bottom border lower, and the content horizontally alligned with the label, but that is not the case for ColorEdit.

**Comment by stsrki** [comment]
I didn't notice that. Yeah it's a bug. Tnx
