### ISSUE TITLE
Is there any way to Add/Remove Tab dynamically？

### ISSUE THREAD

**Issue by iwaiwang** [stsrki/Blazorise#902]
I love this library and using it in my project. It will be helpfull if current  tab control could support dynamically add/remove tab panel.  thank you for your great job !

**Comment by WillianGruber** [comment]
You can use fragment builder for that

**Comment by iwaiwang** [comment]
Good Idea! But I'm new to blazor, I have no idea about how to achive it. it's really a tough work for me . Could you please show me some piece of code ？

**Comment by WillianGruber** [comment]
Sure, take a look: https://chrissainty.com/building-components-via-rendertreebuilder/

**Comment by iwaiwang** [comment]
Thank you very much! I never did that way before, cool!

**Comment by stsrki** [comment]
@iwaiwang Seems like your questions is answered so I will close this. If you need more help please create a new ticket or reopen this one. tnx
