### ISSUE TITLE
Datagrid - RowInserting Cancel

### ISSUE THREAD

**Issue by vbray1979** [stsrki/Blazorise#903]
Cancellation during row insertion does not work

**To Reproduce**
Attached an EventCallback to the RowInserting event.
Set Cancel to true
Datagrid freeze without error message.

**Expected behavior**
The row insertation process should be cancelled and datagrid being unchanged

```
async void OnRowInserting(CancellableRowChange<AssetPriceModel, Dictionary<string, object>> e)
    {
        e.Cancel = true;
    }
```

**Comment by stsrki** [comment]
I cannot reproduce it on my side. I see you're using `async void`. Maybe that's not the problem but it is advised to have `async Task` or plain `Task` for EventCallback. 

```cs
Task OnRowInserting( CancellableRowChange<AssetPriceModel, Dictionary<string, object>> e )
{
    e.Cancel = true;

    return Task.CompletedTask;
}
```

**Comment by vbray1979** [comment]
Hi Mladen, this is indeed better using "async **Task**". It was the signature for "ReadData" but I missed it for the remaining eventcallback. Thank you for your prompt answer.
