### ISSUE TITLE
Autocomplete SelectedValue is 0 after selection

### ISSUE THREAD

**Issue by mfitconsultants** [stsrki/Blazorise#904]
I am not sure if this is a bug or I need to actually set the value manually with `SelectedValueChanged`

I have the following `.razor` with an autocomplete  input in it.

```
 <Field Horizontal="true" ColumnSize="ColumnSize.Is12.OnDesktop">
        <FieldLabel ColumnSize="ColumnSize.Is12.OnDesktop">Company Positions</FieldLabel>
        <FieldBody ColumnSize="ColumnSize.Is12.OnDesktop">
            <Autocomplete Data="@replacementOptions"
                          Filter="AutocompleteFilter.Contains"
                          TextField="@((item)=>item.Name)"
                          ValueField="@((item)=>item.Value)"
                          SelectedValue="@newId"
                          Placeholder="Select the Company Position to replace the old value with." />
        </FieldBody>
  </Field>
```

The autocomplete is populated by `replacementOptions` which is as follows in the `razor.cs` file;

        private IEnumerable<CompanyPositionOutputModel> replacementOptions { get; set; }

I then want to save the `SelectedValue` to `newId` which is;

        private int newId { get; set; }

The replacementOptions are populated from an API GET call. When typing into the autocomplete I see the list of items appear and I can select a value. However, when I output `newId` after selection it is always 0.

**Comment by stsrki** [comment]
Two-way binding can be done in two different ways.

- `@bind-SelectedValue` 
- `SelectedValue` with `SelectedValueChanged`

Your example is just setting the value one-way. You must use one of the above and the easiest is `@bind-SelectedValue` .

**Comment by mfitconsultants** [comment]
@stsrki Thanks for the reply. 

I tried the following;

<Autocomplete Data="@replacementOptions"
                          Filter="AutocompleteFilter.Contains"
                          TextField="@((item)=>item.Name)"
                          ValueField="@((item)=>item.Value)"
                          @bind-SelectedValue="@newId"
                          Placeholder="Select the Company Position to replace the old value with." />
    
But I get the following error;

> cannot convert from Microsoft.AspNetCore.Components.EventCallback<int> to Microsoft.AspNetCorre.Components.EventCallback

**Comment by stsrki** [comment]
newId needs to be an `object` type

**Comment by stsrki** [comment]
Hi @mfitconsultants , have you made it work?

**Comment by mfitconsultants** [comment]
@stsrki Thanks for the reply, Yes thanks you I managed to get it working.

Thanks you for your help.

**Comment by stsrki** [comment]
Glad I could help!
