### ISSUE TITLE
line chart - axis options missing the tick stepSize

### ISSUE THREAD

**Issue by JamesB49** [stsrki/Blazorise#905]
Hello everyone,

sorry i am still new to this technology, and although I try as much as possible to try/test and look up by myself, today I fail to find how to control the Y axis on my line chart. 

![image](https://user-images.githubusercontent.com/65590339/82298063-24f84680-99e6-11ea-83ec-47e32a56e687.png)

I can't get the chart to only display integers (0, 1, 2...) rather than half integers as displayed above...
I haven't found any option in LineChart to change anything.

Any help will be greatly appreciated.
J.

Edit: sorry for wasting anyone's time. I finally found another issue that use OptionsJsonString to provide more options to the chart. I finally found the chartjs document about the tick configuration and found my solution :
`lineChart_TicketPHour.OptionsJsonString = "{\"scales\": {\"yAxes\": [{\"ticks\": {\"stepSize\": 1}}]}}";`

Hope this help someone one day.

**Comment by stsrki** [comment]
You can also use `OptionsObject`. It might be little easier to configure.
