### ISSUE TITLE
[Question] Having a textarea/input inside a DataGridColumn

### ISSUE THREAD

**Issue by OddMann** [stsrki/Blazorise#907]
I'm trying to send a string input from the user as a parameter to a function.
Right now the comment is sent as an empty string (probably because it is declared empty). Is there any way update the variable when the user presses the button and sends it?

```html
<DataGridColumn TItem="Media" Field="Data" Filterable="false" Caption="Rating">
            <DisplayTemplate>
                @{
                    var comment = String.Empty;
                }

                <textarea placeholder="Optional comment" @bind="@comment" />

                <Buttons>
                    <Button Color="Blazorise.Color.Success" Clicked="@(e => Positive(comment))">POSITIVE</Button>
                </Buttons>

            </DisplayTemplate>
        </DataGridColumn>
```

**Comment by stsrki** [comment]
You can use EditTemplate. https://blazorise.com/docs/extensions/datagrid/#edittemplate

**Comment by OddMann** [comment]
So, i got it working, but now there is another problem.

```html
<DataGridColumn TItem="Media" Field="Data" Filterable="false" Caption="Rating">
            <DisplayTemplate>

                <TextEdit Placeholder="Optional comment" @bind-Text="@comment" />

                <Buttons>
                    <Button Color="Blazorise.Color.Success" Clicked="@(e => Positive(comment))">POSITIVE</Button>
                </Buttons>

            </DisplayTemplate>
</DataGridColumn>

@code{
private string comment;
}
```

The new problem is that every textbox in the grid is getting text into them because of the comment string applying to every item in the list.

![Skjermbilde](https://user-images.githubusercontent.com/26325461/82428582-fed8b200-9a8a-11ea-8810-fa93bd7ae9fe.PNG)

I am not editing a value in the model. I'm simply trying to associate a text with the current item and passing it when the user presses the button.

**Comment by stsrki** [comment]
It's because you're using `DisplayTemplate` and you're passing the same value to every cell. Not sure why you need to have editable field on DisplayTemplate but you need to lose the `comment` variable. Instead, try to use the field from your model, like: `@context.Comment`.

`<TextEdit Placeholder="Optional comment" @bind-Text="@context.Comment" />`

**Comment by OddMann** [comment]
I found my own workaround. Instead of having the text written right into the column, I instead made a modal pop up.

But thanks for the input!
