### ISSUE TITLE
Suggestion rename css sidebar

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#910]
Hi, I took it a while to get sidebar working, and I realize the sidebar css is the same name as default blazor one so the order of css matters.

Can I suggest to change the css to something like .blazorisesidebar so it will not conflict with others

**Comment by stsrki** [comment]
Blazor default project template changes some of the bootstrap classes so when you start using any navigation elements it is advised to remove everything from `site.css`. And if you're started to use Blazorise Sidebar I guess that moment has already come. This is what I always advise to people, as soon as your project start to grow, just remove those styles.

But anyways, soon there will be more advanced Bar component with support for vertical mode that will completelly replace Sidebar component.

**Comment by imtrobin** [comment]
thanks, looking forward to it!
