### ISSUE TITLE
Upload File problems

### ISSUE THREAD

**Issue by gidibloke** [stsrki/Blazorise#919]
The upload file component worked file for single file and multiple files only if the files are selected in one go. However if using multiple upload, users upload a file, then click the browse button to add another file for upload an error pops up

**To Reproduce**
1. Create a file imput that allows multiple uploads and upload a file
2. Click on browse again and upload another file
3. Click submit to submit the form
4. Check Chrome console window to see error 

**Expected behavior**
Adding a break point to the upload code, It fails on the line `file.WriteToStreamAsync(filepath)` where file is the IFileEntry. Error message is `Error: Microsoft.JSInterop.JSException: There is no file with ID 1. The file list may have changed`

**Additional context**
I checked the _content JS and it seems to be failing in the function `getFileById(elem, fileId)` where the field Id variable is 2 instead of 1. Not sure why because the foreach loop has a IFileEntry with Id 1

**Comment by Electriccc** [comment]
Hi gidibloke,
Can you explain what do you mean by submit the form, do you mean the server side application submit ?

**Comment by gidibloke** [comment]
> Hi gidibloke,
> Can you explain what do you mean by submit the form, do you mean the server side application submit ?

Yes. The Blazor application is a Server Side application.

**Comment by stsrki** [comment]
Hi @gidibloke , I think what @Electriccc is trying to ask, are you using **form post back**? Is that what you mean when you say _submit the form_? If that is the case then that behavior is not supported by the FileEdit.

Can you show is the code to reproduce the issue?

**Comment by stsrki** [comment]
We were unable to reproduce this problem. Since there was no response for a long time I will close this ticket. If you think the issue is still present please reopen. Thanks.
