### ISSUE TITLE
Refresh dom tree

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#920]
Hi, I'm doing localization, so I would need a way refresh the whole dom. I know there is StateHasChanged, but that's per component, I want it changed for whole dom (including sidebar which does not get refreshed).  So maybe a method in base classes that can refresh all?

**Comment by stsrki** [comment]
This is something that you can already do by yourself. You just need to create a custom component in your project and then cascade it to be used by child component(s).

**YourComponent.razor**

```cshtml
<CascadingValue Value="this">
    @* add whatever here *@
</CascadingValue>
@code{
    public void Refresh()
    {
        StateHasChanged();
    }
}
```

**Somewhere in child component**

```cs
void OnSomeAction()
{
    ParentComponent.Refresh();
}

[CascadingParameter] protected YourComponent ParentComponent { get; set; }
```

**Comment by imtrobin** [comment]
I see but I want send it across all the items on the page, not its particular instance. I see that there is a BaseCheckedComponent. Is there a list maintained somewhere?

**Comment by stsrki** [comment]
The solution above is exactly for that. When you create that component you just need to put it somewhere that will surround all of your components. It's best to add it to root layout or in the App.razor around the router component.

**Comment by imtrobin** [comment]
It seems like an overkill, I prefer to add it in the base classes, but I think I will just hardcode the classes to refresh, since it's only the sidebar and header/footer.

**Comment by stsrki** [comment]
Placing it in the base class of the component will only do the refresh from that component and all of the component placed inside of it. It will not do anything up in the rendering tree.

**Comment by imtrobin** [comment]
I want to try a different method, I store an static instance of the SideBar, and I call it SidebarInstance.OnStageChange from another component. It works!

Now, I want to try to do it for the Layout, but that doesn't work. So I see you have DirtyClasses but its internal. If I can call it on layout, , maybe it would work?

**Comment by imtrobin** [comment]
So I tried hacking a public function BaseComponent that calls StateHasChanged, DirtyClasses, DirtyStyles, unfortunately it didn't work. I guess its not propagating it ?

**Comment by stsrki** [comment]
I will close this as it's not directly related to Blazorise but Blazor in general. Also I feel the solution from above will work, you just need to place it somewhere at the root of your application. Probably around Router or in Layout.
