### ISSUE TITLE
SelectList with images

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#921]
Hi, I'm doing a selection for languages for localizaton, I want to use SelectList but showing images of country flags instead of Text.

**Comment by stsrki** [comment]
While I could probably be able to implement render fragments into `SelectList `to be able to do these kind if things, I think the best solution for you is to use `Select` and `SelectItem` to manually create select element. `SelectList `is just a simple wrapper around them anyways.

**Comment by imtrobin** [comment]
Gotcha, thanks.
