### ISSUE TITLE
Question: how to implement bootstrap split dropdowns?

### ISSUE THREAD

**Issue by leotsarev** [stsrki/Blazorise#922]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement https://getbootstrap.com/docs/4.5/components/dropdowns/#split-button

**Describe the solution you'd like**
`BarDropdownToggle` should accept `To` parameter. If so, it should behave like a split button

P.S. Thanks for awesome library!

**Comment by stsrki** [comment]
Here is an example from the demo app

```
<Dropdown>
                    <Button Color="Color.Secondary">SPLIT DROPDOWN</Button>
                    <DropdownToggle Color="Color.Secondary" Split="true"></DropdownToggle>
                    <DropdownMenu>
                        <DropdownItem>Action</DropdownItem>
                        <DropdownDivider />
                        <DropdownItem>Another Action</DropdownItem>
                    </DropdownMenu>
                </Dropdown>
```

BarDropdownToggle is used within Bar component.

**Comment by leotsarev** [comment]
Thanks, sorry!
