### ISSUE TITLE
Select's SelectedValue is ignored on load

### ISSUE THREAD

**Issue by claunia** [stsrki/Blazorise#924]
**Describe the bug**
With the following razor code:
```razor
        <Field>
            <FieldLabel>@L["Country"]</FieldLabel>
            <Select ReadOnly="!_editable" TValue="short?" @bind-SelectedValue="@model.CountryId">
                @foreach (var country in _countries)
                {
                    <SelectItem Value="@country.Id">@country.Name</SelectItem>
                }
            </Select>
            <TextEdit ReadOnly="!_editable" @bind-Text="@model.Country.Name" />
        </Field>
```

and the following code-behind:
```csharp
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if(_loaded)
                return;
            
            if(Id <= 0)
            {
                _loaded = true;

                return;
            }

            _countries = await CountriesService.GetAsync();

            model = await Service.GetAsync(Id);

            _loaded = true;

            StateHasChanged();
        }
``` 

The list is correctly populated, but no item is selected.

If I use the following override
```csharp
protected override async Task OnInitializedAsync()
```

The correct item is selected on the prerender, but when the app connects to server again no item is selected. There is no selected attribute in the generated HTML, and the setter of model.CountryId is never called.

As a test, in all cases, the `TextEdit` gets the correct value.
`StateHasChanged` is only needed when inside `OnAfterRenderAsync`, otherwise nothing loads. It is not needed when inside `OnInitializedAsync`.

**Expected behavior**
The correct item is selected on load.

**Additional context**
Blazorise 0.9.0.3
.NET Core 3.1.4

**Comment by claunia** [comment]
As another test I hid the `Select` so it only shows after a button is clicked then added the following:
```
        short? foo
        {
            get => _model.CountryId;
            set => _model.CountryId = value;
        }
```
and changed the binding to it.

On load, getter is not called. When clicking the button, the getter is called three times, but the still no select attribute is emitted on the HTML.

**Comment by stsrki** [comment]
Can you try adding `TValue="short?"` to `SelectItem`?

**eg**

```cshtml
<SelectItem TValue="short?" Value="@country.Id">@country.Name</SelectItem>
```

**Comment by claunia** [comment]
Go figure that did the trick. Thanks @stsrki
