### ISSUE TITLE
Datagrid: How to customize the column? 

### ISSUE THREAD

**Issue by janellesnowy** [stsrki/Blazorise#926]
Issues: I was trying to change the "Width" of the column, but it does not seem to work. 

`<DataGridColumn TItem="Employee" Field="@nameof( Employee.Salary )" Caption="Salary" Editable="true" Width="140px" DisplayFormat="{0:C}" `

May I also find out, where is the code for "DisplayTemplate" and "EditTemplate"? 

https://github.com/stsrki/Blazorise/issues/166
I read from here, how can I change this "DisplayTemplate" so that i can make the changes to the Column wide? 

Thanks in advance

**Comment by stsrki** [comment]
Can you inspect datagrid column in browser developer tools to see if width attribute is applied? It is working on my side.

**Comment by janellesnowy** [comment]
I also spotted the same problem on the Bootstrap demo on Datagrid page, once there are more than 5 column on the table, there is no way to move left & right to view other columns on the right. 

https://bootstrapdemo.blazorise.com/tests/datagrid

![2020-05-27 Blazorise Datagrid cannot slide left right](https://user-images.githubusercontent.com/1131512/83017055-9030c100-a055-11ea-98a0-9dc175a62736.jpg)

**Comment by stsrki** [comment]
Maybe try setting the `Responsive="true"` property on Table/DataGrid?

**Comment by stsrki** [comment]
Adding `Responsive` should work. In case you still have the problem please reopen and provide a sample code to reproduce the issue.
