### ISSUE TITLE
Full screen modal without ModelContant

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#927]
Hi, I'm doing a loading screen  with spinkit in the centre and so I'm thinking of using the Modal to do it.

```
    <Modal @ref="LoadingModalInstance">
        <ModalBackdrop />
        <SpinKitWanderingCube />
        <ModalContent Centered="true">
            <ModalBody />
        </ModalContent>
    </Modal>
```

However, it has white box which is the ModalBody. If I comment out ModelBody, there is an error.

**Comment by stsrki** [comment]
You should probably play with some CSS to make it work. It's hard to help you without any code or example to reproduce the problem.

**Comment by imtrobin** [comment]
I used this https://github.com/faso/Faso.Blazor.SpinKit

It's  a bunch of css. The question is how to remove the ModalContent from Modal

**Comment by stsrki** [comment]
Modal is created with ModalContent in mind. If you want to have it without, the best options is to have regular html elements to achieve your goal.
