### ISSUE TITLE
Theme Color Alpha

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#929]
Hi, it seems when I try to use alpha color, it throw exception.

 E.g black with 66 is alpha value

```
        ColorOptions = new ThemeColorOptions
        {
            Primary = "#0000FF1A"
        },
```

It works fine for BackgroundOptios

**Comment by stsrki** [comment]
Only 6 digit hex color are supported. Not sure why BackgroundOptions works for you as it's using the same parse function.

**Comment by imtrobin** [comment]
It doesn't crash, but it's not working as in the color didn't change, but maybe it's because I don't understand where it is used.

**Comment by stsrki** [comment]
It's probably silently failing to empty color.

`Background `colors are used mostly on Bar, Table, Progress, etc, basically on component that have `Background `parameter.

**Comment by imtrobin** [comment]
I tried on a Bar, the color is grey. Is there a reason why it is not supported?

**Comment by stsrki** [comment]
When you define background colors options on a theme it will override CSS styles that come with current CSS provider.

And to use that color you also must set define it on a component.

```cshtml
<Bar Background="Background.Primary"></Bar>
```

**Comment by imtrobin** [comment]
Ok I see there is enum Background. Transparent in the docs,  what is that for? I really want a alpha color for my background, where should I modify it to make it?

**Comment by stsrki** [comment]
I had to look at it. It seems it is used only by the Bulma and eFrolic providers and it should not be configured by the theme options. Basically it should be used just as it is in CSS: `background-color: transparent;`, to make element transparent in full.

**Comment by stsrki** [comment]
If you wan't to change background just use ordinary CSS, it's not that hard. 

```css
body{
    background-color: rgba(255, 0, 0, 0.3);
}
```

https://www.w3schools.com/css/css3_colors.asp

**Comment by imtrobin** [comment]
I'm not referring to background of the app, it's background of the elements, like datagrid, sidebar, bar etc.

**Comment by imtrobin** [comment]
Hi, I see I can set background transparent, but its alpha color it still not supported?

**Comment by stsrki** [comment]
It's fully supported now so you can define almost any color including the alpha channel. Sorry I forgot to notify you in this ticket :)

**Comment by imtrobin** [comment]
Ok thanks, can you support rgba also instead of just hex?

**Comment by stsrki** [comment]
Unfortunately no. It would complicate theme builder too much as working with `css`, `scss` and C# generator would lead to a mess. You can always create small RGBA function that will convert the entered values into _8-hex_ color.

**Comment by imtrobin** [comment]
I'm not very sure why that is so. If I set a Color via theme, the place I see it is doing that is in ParseColor

```
        protected static System.Drawing.Color ParseColor( string value )
        {
            return value.StartsWith( "#" )
                ? HexStringToColor( value )
                : System.Drawing.Color.FromName( value );
        }
```

If you change it to this, it can support the format hex,rgba, rgb 

https://stackoverflow.com/questions/38493140/how-to-convert-rgba-css-color-format-to-hexadecimal-format#comment96643231_40611610

**Comment by stsrki** [comment]
Having it done in `ParseColor` could work, I admit that part. Problem could be that not every color is parsed. Instead in some cases it is just sent through generator and applied as a CSS variable. Then that CSS variable can be used inside of SCSS files through the `var(--some-color)`. I will need to investigate more to see what else might be affected.

**Comment by imtrobin** [comment]
I don't really need to touch those, they can still be hex, and internally used. It just for the theme, we can use rgba which is abit easier to see the alpha value.

**Comment by imtrobin** [comment]
I changed ParseColor to this, it shouldn't break existing code.

```
 protected static System.Drawing.Color ParseColor (string cssColor)
        {
            //return value.StartsWith( "#" )
            //    ? HexStringToColor( value )
            //    : System.Drawing.Color.FromName( value );

            cssColor = cssColor.Trim ();

            if (cssColor.StartsWith ("#"))
            {
                return HexStringToColor (cssColor);
            }
            else if (cssColor.StartsWith ("rgb")) //rgb or argb
            {
                int left  = cssColor.IndexOf ('(');
                int right = cssColor.IndexOf (')');

                if (0 > left || 0 > right)
                    throw new FormatException ($"rgba format error:{cssColor}");

                string noBrackets = cssColor.Substring (left + 1, right - left - 1);

                string [] parts = noBrackets.Split (',');

                int r = int.Parse (parts [0], CultureInfo.InvariantCulture);
                int g = int.Parse (parts [1], CultureInfo.InvariantCulture);
                int b = int.Parse (parts [2], CultureInfo.InvariantCulture);

                if (3 == parts.Length)
                {
                    return System.Drawing.Color.FromArgb (r, g, b);
                }
                else if (4 == parts.Length)
                {
                    float a = float.Parse (parts [3], CultureInfo.InvariantCulture);
                    return System.Drawing.Color.FromArgb ((int) (a * 255), r, g, b);
                }
                throw new FormatException ($"Invalid rgb format:{cssColor}");
            }
            else
                return System.Drawing.Color.FromName (cssColor);
        }
```
