### ISSUE TITLE
SidebarBrand image not centered

### ISSUE THREAD

**Issue by imtrobin** [stsrki/Blazorise#933]
Hi, I'm trying to an image for SidebarBrand, and it doesn't centered. I've tried

```
<SidebarBrand>
<a href=""><centre><img src="img/image.png" /></centre></a>
</SidebarBrand>
```

I've tried using a Figure, it's the same, aligned to the left instead of centre.

**Comment by stsrki** [comment]
I think you have a typo, it should be `center` tag?

**Comment by WillianGruber** [comment]
Brittish english is centre, american is center. Maybe thats it.

**Comment by imtrobin** [comment]
That's what you get what coding late at night!, you are right. thanks!
