### ISSUE TITLE
DataGrid: Define default value for input on RowInserting

### ISSUE THREAD

**Issue by b-rant** [stsrki/Blazorise#934]
**Is your feature request related to a problem? Please describe.**
I would like to be able to define a default value for an input field when creating a new record using the DataGrid NewCommand. 

Context: We have a list of "config groups", each of which has a list of "configs". We have a view populating DataGrids for each of these "config groups", allowing for CRUD operations on each of their "configs". When we want to add a new "config" to a "config group", we need context on what "config group" this "config" belongs to.

Problem: I cannot seem to get a NumericEdit template that will pre-populate the CellValue with the Id of the corresponding "config group". This is what I have right now, and its obviously not working:

```cshtml
<DataGridNumericColumn TItem="StitchApplicationSettingModel" Field="@nameof(StitchApplicationSettingModel.GroupIdIfExists)" Displayable="false" Caption="Group Id" Editable="true">
                                            <EditTemplate>
                                                <NumericEdit TValue="int" Value="@((int)( settingGroup.Id ))" ValueExpression="@(() => (settingGroup.Id))" ValueChanged="@(v => ( (CellEditContext)context ).CellValue = v)" />
                                            </EditTemplate>
                                        </DataGridNumericColumn>
```

I can see the value in the NumericEdit field when creating a new record, but when the RowInserting callback is triggered, its CancellableRowChange Value for GroupIdIfExists is always the type default value of 0 (since it is an int). If I manually edit the field, the ValueChanged callback does update the CellValue, but I don't want to rely on the user to modify this field just to update the CellValue that gets passed to the RowInserting callback.

**Describe the solution you'd like**
I am not sure what the correct solution for this is... Maybe just provide a DefaultValue parameter that also updates the CellValue when the input field is initialized?

**Comment by ehsangfl** [comment]
I think this is not good idea for default value. the true way is add new event for datagrid, and named it RequestNewItem, and we can handle it and set new item for datagrid. this is the same way on wpf datagrid ....
BR

**Comment by stsrki** [comment]
Well, we already implement event `NewItemDefaultSetter` that is used to set default item values. I guess that's the same behavior as in WPF. The feature is done for v0.9.2.
