### ISSUE TITLE
Sidebar third level items

### ISSUE THREAD

**Issue by santosalvin** [stsrki/Blazorise#935]
I try to populate nested sidebar navigation, but the dynamic sidebar generates only up to second level navigation. Is it posible to generate third level navigation using sidebar?

    SidebarInfo sidebarInfo = new SidebarInfo
    {
        Brand = new SidebarBrandInfo
        {
            Text = "Blazorise Demo"
        },
        Items = new List<SidebarItemInfo>
        {
            new SidebarItemInfo { To = "", Text = "Dashboard" },
            new SidebarItemInfo
            {
                Text = "Email",
                SubItems = new List<SidebarItemInfo>
                {
                    new SidebarItemInfo { To = "email/inbox", Text = "Inbox" },
                    new SidebarItemInfo { To = "email/compose", Text = "Compose Email" },
                    new SidebarItemInfo
                    {
                        Text = "Third Level",
                        SubItems = new List<SidebarItemInfo>
                        {
                            new SidebarItemInfo { To = "", Text = "Third" }
                        }
                    }
                }
            },
            new SidebarItemInfo
            {
                Text = "Applications",
                SubItems = new List<SidebarItemInfo>
                {
                    new SidebarItemInfo { To = "apps/todo", Text = "Todo List" }
                }
            },
        }
    };

**Comment by stsrki** [comment]
Hi, after some considerations I think it's best to move to the new Bar component that now has support for multiple levels of navigation. The sidebar component is slowly going to be abandoned and no new features will be done for it.
