### ISSUE TITLE
MaxMessageSize ignores being set

### ISSUE THREAD

**Issue by claunia** [stsrki/Blazorise#936]
**Describe the bug**
Setting the MaxMessageSize attribute in FileEdit is completely ignored.

**To Reproduce**
```razor
<FileEdit Changed="@OnUploadChanged" Written="@OnUploadWritten" Progressed="@OnUploadProgressed" MaxMessageSize="2097152" Started="@OnUploadStarted" Filter="image/svg+xml" />
```

**Expected behavior**
Uploading any file up to 2097152 bytes work.

**Current behaviour**
Uploading any file bigger than 20480 fails.

**Comment by stsrki** [comment]
I just tested this and it's working as expected. MaxMessageSize is not expected to be used to read an entire file at once, although it can set up like that, but to read files in batches. So, if you have a file of size 1000 bytes and you set MaxMessageSize to be 100, it will read your file 100 by 100, a total of 10 times.
