### ISSUE TITLE
Display tool tip at svg drawing position ?

### ISSUE THREAD

**Issue by intech-paul** [stsrki/Blazorise#937]
I am drawing a graph using svg graphics commands, and would like to display a tool tip when the mouse is over a certain data point. I have the mouse detection and highlight detection working, is there anyway I can force the tooltip to display at a certain mouse position ?

I am looking for something like this:
```cshtml
 @if (matchx1==i)        
                 {
                 //<Blazorise.Tooltip xpos=@(i * step) ypos=@f Text="@DateTime.Now.ToLongTimeString()">
                 <circle cx="@(i * step)" cy="@f" r="4" stroke="black" stroke-width="1" fill="red" />
                 //</Blazorise.Tooltip>    
                 }
```

**Comment by stsrki** [comment]
Tooltip is created by CSS alone so there is no way to specify at which position it would appear, at least dynamically. It works by adding `:before` and `:after` pseudo elements to the tag but the problem is that svg does not support them.

**Comment by stsrki** [comment]
Should be possible with the new Tooltip in 0.9.4
