### ISSUE TITLE
Bug on Sidebar

### ISSUE THREAD

**Issue by Valerio81** [stsrki/Blazorise#939]
**Describe the bug**
If the the sidebar is collapsed (screen dimensions), i open them using the toggle button and I expand the window without closing the bar: the bar collapsed and the toggle disappear.

**To Reproduce**
https://materialdemo.blazorise.com/tests/forms (or any page with the sidebar)

**Screenshots**
![cattura01](https://user-images.githubusercontent.com/16916271/83309686-39b8b380-a20a-11ea-8975-ddb8b65618a7.JPG)
![cattura02](https://user-images.githubusercontent.com/16916271/83309670-2dccf180-a20a-11ea-85cb-e75467e414db.JPG)
![cattura03](https://user-images.githubusercontent.com/16916271/83309681-34f3ff80-a20a-11ea-8ab7-2791b9f77f1c.JPG)

**Comment by stsrki** [comment]
Hi, Sidebar will slowly be obsoleted in favor of new vertical mode for `Bar `component. It will be released with next v0.9.1. In the meantime if you wish to give us a hand and fix the `Sidebar `we would gladly accept the PR!
