### ISSUE TITLE
Implement Fabric Core

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#94]
https://github.com/OfficeDev/office-ui-fabric-core

https://developer.microsoft.com/en-us/fabric#/get-started#fabric-core

**Comment by tscholze** [comment]
This feature would be great! Thanks for working on it!

**Comment by b-straub** [comment]
This is looking already quite promising:
[BlazorFabric](https://github.com/limefrogyank/BlazorFabric)
