### ISSUE TITLE
Implement more Utility classes

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#942]
## Sizing

**Inspiration**

https://getbootstrap.com/docs/4.5/utilities/sizing/

**Proposal:**

```
<Image Source="..." Width="Width.Is100" />
```

## Borders

**Inspiration**

https://getbootstrap.com/docs/4.5/utilities/borders/

## Justify Content

https://getbootstrap.com/docs/4.5/utilities/flex/#justify-content

## Others

- https://getbootstrap.com/docs/4.5/utilities/image-replacement/

**Comment by kofinn** [comment]
Hi,

as we discussed on Gitter, can you implement  Flex wrap?
https://getbootstrap.com/docs/4.5/utilities/flex/#wrap

As part of Display feature?
Thank you

**Comment by stsrki** [comment]
Flex utilities done with https://github.com/stsrki/Blazorise/pull/2231
