### ISSUE TITLE
Could you please add source code in Blazorise Demo

### ISSUE THREAD

**Issue by zhujiancc** [stsrki/Blazorise#945]
I think put the code below the Example , it is very friendly to developer, Thanks
![image](https://user-images.githubusercontent.com/19665595/83342369-4845be80-a321-11ea-9c79-b40f3d2750b7.png)

**Comment by stsrki** [comment]
I'm already thinking about this. The plan is to create new CMS for documentation that will have real Blazorise examples and code samples included. But it will take some time.

**Comment by zhujiancc** [comment]
Thanks for your answer.
So, any source code about the documentation. This is a 404 link in doc now:
![image](https://user-images.githubusercontent.com/19665595/83368497-8effeb00-a3eb-11ea-9de0-cc520dea7393.png)

**Comment by stsrki** [comment]
Demo source code can be found on https://github.com/stsrki/Blazorise/tree/master/Demos/Blazorise.Demo

And documentation source is on https://github.com/stsrki/Blazorise/tree/master/docs

Recently we changed project structure and it seems now the URL to demo source is not working. I will fix this.

**Comment by zhujiancc** [comment]
Thanks~
