### ISSUE TITLE
Unhandled Exception behavior in UI events

### ISSUE THREAD

**Issue by sblakemore** [stsrki/Blazorise#946]
In Blazor all Unhandled Exceptions should be sent to ILogger instances so they can be recorded or acted upon. This is the only way to have any kind of global Exception handling at all.

https://github.com/dotnet/aspnetcore/issues/13452#issuecomment-594088975

Behavior right now throwing an Exception in Blazoise Button click handler in user code:

- with "void" signature - Exception is sent to logger, can be seen in console with "crit" level. This is correct behavior!
- with "async Task" signature - Exception disappears in to nothing, no sign of anything in console. This is very bad!

To make this work correctly all methods for UI events inside Blazorise must be "async Task" and must "await" the call to "InvokeAsync".

https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Button.razor.cs#L47

If you do this then both scenarios correctly send the Exception to the ILogger and nothing nasty happens. I only looked at Button, but this needs to be done for ALL UI events!

**Comment by stsrki** [comment]
Sorry for the late response! You're right, this should be awaited. Although it is already packed and behind the schedule I will push this to 0.9.1 as I find it critical to fix. Thanks for letting me know!

**Comment by sblakemore** [comment]
Thanks for the fix, much appreciated, this is pretty important to my app!
