### ISSUE TITLE
Divider text cut off by other divider

### ISSUE THREAD

**Issue by WillianGruber** [stsrki/Blazorise#950]
The text in the upper dividers gets cut off by the lower one.
![image](https://user-images.githubusercontent.com/56033692/83461210-7ec52b80-a43e-11ea-8332-77a2478e481d.png)

```
<Divider Type="DividerType.TextContent" Text="Technical Apps" />
<Divider Type="DividerType.TextContent" Text="Business Apps" />
```
Provider: Material. Didn't test in others.

**Comment by stsrki** [comment]
Not sure if this is real problem. Are they ever going to be that close to one another?

**Comment by WillianGruber** [comment]
I agree its a minor issue. Probably won't happen anywhere. For me, it may happen in the WYSIWYG page builder in the future temporarily, if the user includes 2 of them.
It is so minor that I'll close this.
