### ISSUE TITLE
FileEdit does not show filename(s) after browsing?

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#952]
When a file has been browsed, the filename(s) is not visible?

Code :
```  html
<FileEdit Changed="@InputFileChanged" Multiple="false" />
```

Screenshot taken from your example site after a file was selected.
![image](https://user-images.githubusercontent.com/249938/83537341-b8586e00-a4f4-11ea-9c7b-e809bbf05de5.png)

Is this by design? Or a bug?

**Comment by minitoma** [comment]
I'm still having trouble displaying selected file after browsing it. Do i need to had a property or something ?

**Comment by stsrki** [comment]
@minitoma It's working in 0.9.2 preview. It should be released by the end of the week.
