### ISSUE TITLE
Mobile View Does Not Work

### ISSUE THREAD

**Issue by frankyjin** [stsrki/Blazorise#959]
Use your phone to visit https://bootstrapdemo.blazorise.com. Initial view looks good. Click on the hamburger button on top-right to view navigation menu. Then click on UI Elements -> Button.

The navigation menu remains and the page does not look correct.

**Comment by stsrki** [comment]
This is known problem with demo application. So far main focus for demo apps was desktop support while I didn't focus much on mobile optimizations. 

With #758 I already have this planned to fix before next release.
