### ISSUE TITLE
SelectEdit - First Value is null

### ISSUE THREAD

**Issue by carlosast** [stsrki/Blazorise#96]
First call to ValidateSelect value is null.

For the example below, when all Value values are not null, when you click Submit in manual validation, the value value in ValidateSelect is null. It should have a value, since the first item (the 1) is selected.

                            <Validation Validator="@ValidateSelect">
                                <SelectEdit TValue="int?">
                                    <ChildContent>
                                        <SelectItem Value="@((int?)1)">1</SelectItem>
                                        <SelectItem Value="@((int?)2)">2</SelectItem>
                                        <SelectItem Value="@((int?)3)">3</SelectItem>
                                        <SelectItem Value="@((int?)4)">4</SelectItem>
                                    </ChildContent>
                                    <Feedback>
                                        <ValidationError>Select one value!</ValidationError>
                                    </Feedback>
                                </SelectEdit>
                            </Validation>

In my case, I use bind-SelectedValue and set a nonnull value initially, but even then value in ValidateSelect is null.

                                    <Validation Validator="@XValidators.ValidateSelect">
                                        <SelectEdit bind-SelectedValue="@Model.StatusId" >
                                            <SelectItem Value="@Constantes.IntNull">@Constantes.Selecione</SelectItem>
                                            @foreach (var item in Carregar.Status)
                                            {
                                                <SelectItem Value="@item.StatusId">@item.StatusNome</SelectItem>
                                            }
                                        </SelectEdit>
                                    </Validation>

**Comment by carlosast** [comment]
Even setting SelectedValue = "@ ((int?) 2)", value in ValidateSelect is null

                            <Validation Validator="@ValidateSelect">
                                <SelectEdit TValue="int?" SelectedValue="@((int?)2)">
                                    <ChildContent>
                                        <SelectItem Value="@((int?)1)">1</SelectItem>
                                        <SelectItem Value="@((int?)2)">2</SelectItem>
                                        <SelectItem Value="@((int?)3)">3</SelectItem>
                                        <SelectItem Value="@((int?)4)">4</SelectItem>
                                    </ChildContent>
                                    <Feedback>
                                        <ValidationError>Select one value!</ValidationError>
                                    </Feedback>
                                </SelectEdit>
                            </Validation>

**Comment by stsrki** [comment]
Can you show me your `ValidateSelect` method?

**Comment by carlosast** [comment]
public static void ValidateSelect(ValidatorEventArgs e)
        {
            var selectedValue = Convert.ToInt32(e.Value);
            e.Status = selectedValue != 0 ? ValidationStatus.Success : ValidationStatus.Error;
        }
