### ISSUE TITLE
CardDeck

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#960]
I'm missing the `CardDeck` component?

https://getbootstrap.com/docs/4.0/components/card/#card-decks

**Comment by stsrki** [comment]
Is this something new in bootstrap? I didn't see it before. Anyway it shouldn't be a problem to add.

**Comment by StefH** [comment]
Can you please add this ? Or should I try to make a PR?

**Comment by stsrki** [comment]
You can try it. From what I can see we have two ways to do it

-  create separate component named `CardDeck`, similar to `CardGroup`
- add bool property named `Deck` to `CardGroup`

I'm leaning more to separate component.

**Comment by stsrki** [comment]
Oh yeah I forgot. In case you're going to implement it, don't forget to add support for all providers(Bulma, AntDesign, eFrolic).

**Comment by StefH** [comment]
And what branch?

**Comment by stsrki** [comment]
dev091

**Comment by WillianGruber** [comment]
Just implemented this. Working great!
