### ISSUE TITLE
ChartOptions : Scales object has typo in "Axe"

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#961]
```
[DataContract]
public class Scales
{
  [DataMember( EmitDefaultValue = false )]
  public List<Axe> XAxes { get; set; }

  [DataMember( EmitDefaultValue = false )]
  public List<Axe> YAxes { get; set; }
}
```

The `XAxes` and `YAxes` are correctly spelled, however I think the `Axe` class should actually be named `Ax` or `Axis`.

This is an `Axe`:
![image](https://user-images.githubusercontent.com/249938/83996263-fa057080-a95b-11ea-9c8b-6d9bf1fff489.png)

**Comment by stsrki** [comment]
Haha I guess you're right. It could be renamed but it's not on my priority list for now as it's going to be a breaking change.

**Comment by stsrki** [comment]
Well, there were a lot bigger breaking changes that I think this one will not be so much of a problem. Going on the list!
