### ISSUE TITLE
DataGrid - Is it possible to force single-column sorting?

### ISSUE THREAD

**Issue by Enritski** [stsrki/Blazorise#967]
The new ability to sort the GridView by multiple columns is great but, sometimes, it would be good to force sorting to be by a single column at a time.  
Currently, if I click on the first column heading, it sorts by that column as expected.  If I then decide to sort by column 2 instead, clicking the second column heading adds an additional level of sorting so that the rows are sorted by the first columns and THEN by the second.  I know that I can click the first column heading a further twice to reverse and then remove the sorting on column 1, leaving only the second column sort in place but that is not very intuitive for my users.  Is there any way to force the sort to be by one column at a time?
Ideally, I would like there to be an option to turn on / off multi-column sorting but, for now, I just want to have single-column sorting.  Another option might be to follow the approach as used in the DevExpress Blazor GridView, where you have to hold down the shift key to have multi-column sorting.

**Comment by thuhaile** [comment]
is this feature currently in the 0.9.2 preview?

**Comment by stsrki** [comment]
@thuhaile No, it still needs to be done. It's scheduled for 0.9.2 release
