### ISSUE TITLE
Tabs features

### ISSUE THREAD

**Issue by amerkoleci** [stsrki/Blazorise#969]
**Is your feature request related to a problem? Please describe.**
Its not a problem, but its a feature request.

**Describe the solution you'd like**
Is possible to have Tabs with Icon?
Is possible to have closeable tabs?
Using router for tab navigation?

**Comment by stsrki** [comment]
@amerkoleci This is all you can already do by playing with Blazorise components. 

Just to give you a basic idea:

Icon and CloseButton example

```cshtml
<Tabs SelectedTab="@selectedTabName1" SelectedTabChanged="@OnSelectedTabChanged1">
    <Items>
        <Tab Name="home" Visibility="@HomeTabVisibility">
            <Icon Name="IconName.Home" />
            Home
            <CloseButton Clicked="@OnHomeTabClose" />
        </Tab>
        <Tab Name="profile">Profile</Tab>
        <Tab Name="messages">Messages</Tab>
        <Tab Name="settings">Settings</Tab>
    </Items>
    <Content>
        <TabPanel Name="home" Visibility="@HomeTabVisibility">
            ...
        </TabPanel>
        ...
    </Content>
</Tabs>
```

And with navigation you can subscribe to `NavigationManager.LocationChanged` and then update `selectedTabName1` accordingly.

**Comment by amerkoleci** [comment]
Thanks you very much @stsrki 
Another question, how can I change tab panel content dynamically?
Basically I need to host the route page inside as TabPanel content.

Not sure If I was clear tho :)

Thanks

**Comment by stsrki** [comment]
Maybe you can do it by doing something like this

```cs
private async void OnLocationChanged( object sender, LocationChangedEventArgs args )
{
    var content = await YourGetContentFromLocation( args.Location );

    // set it to a variable
    yourTabPanelContent = content;

    StateHasChanged();
}
```

```cshtml
<TabPanel Name="home">
    @yourTabPanelContent 
</TabPanel>
```

**Comment by amerkoleci** [comment]
Thanks again, 
I have another question, would be possible to have tab headers scrollable, similar to syncfusion one's:

https://www.syncfusion.com/blazor-components/blazor-tabs

Thanks in advance.

**Comment by amerkoleci** [comment]
I would have another question, I'd like to have context menu on tab with actions like:
- "Close"
- "Close this but others" 
etc

Is it possible? Or I need lib like https://github.com/stavroskasidis/BlazorContextMenu

Thanks

**Comment by stsrki** [comment]
For all of the mentioned features, you have the option to customize them by using your own or some third party solution. So, closing the ticket and if you need some other specific feature please open new ticket.
