### ISSUE TITLE
DropdownList issue with ChangeHandler

### ISSUE THREAD

**Issue by sjthompsonengl** [stsrki/Blazorise#974]
Trying to use your sample as per: https://blazorise.com/docs/extensions/dropdownlist/

The ChangeHandler object has a value of 4120208 which doesn't correspond to my list of 4 values!

The list displays as expected, but selecting a value throws a memory violation error

**Comment by stsrki** [comment]
Can you show me your code?

**Comment by sjthompsonengl** [comment]
I copied your example as per the above page, I've tried a SelectList instead and that seems to work fine

**Comment by stsrki** [comment]
Just copied the code from the example and it works just fine. I will need to see your list of values, maybe there is a problem?

**Comment by stsrki** [comment]
Closing since I cannot reproduce the error.
