### ISSUE TITLE
DataGrid - Integrate filtering with paging for large data sets

### ISSUE THREAD

**Issue by jac12498** [stsrki/Blazorise#977]
The DataGrid supports large data sets through the use of the ReadData handler. This allows the user to perform the server side query to get just the required rows.

However, the Column Filters do not work with this. There is no way to filter a large data set. The DataGrid components from Syncfusion and Telerik both support this by adding the filter (along with the sort) information in their equivalent of DataGridReadDataEventArgs.

Would this be something that you could add?

**Comment by stsrki** [comment]
This is already supported. You have `Columns` property on ReadData event argument. And then for each column there is `SearchValue` field. Along with field name and sort direction.

**Comment by jac12498** [comment]
Thank you. I missed this.
