### ISSUE TITLE
Select component - Multiple selected showing "0 selected" on mobile.

### ISSUE THREAD

**Issue by guillermodimas** [stsrki/Blazorise#978]
When using the Select component with (multiple select enabled) on mobile, if the user selects 1 or more items, the collapsed label will continue to show "0 selected" 

This is true even when testing in your documentation site for the select component. 

**To Reproduce**
1. From your phone
2. Go to [https://blazorise.com/docs/components/select/](https://blazorise.com/docs/components/select/)
3. Click on the multiple select component and select a few items.
3. When you click "Ok", you will see the collapsed label show "0 Selected"
4. See screenshots

![Screenshot_20200612-121219_Chrome](https://user-images.githubusercontent.com/5040055/84523453-56db9080-aca6-11ea-8503-cc634faa2bc1.jpg)
![Screenshot_20200612-121224_Chrome](https://user-images.githubusercontent.com/5040055/84523461-5a6f1780-aca6-11ea-94c2-c778664b4f47.jpg)

**Expected behavior**
The collapsed component should list a count of items selected. (Example: 3 selected)

Thank you for the amazing component library.

**Comment by stsrki** [comment]
Documentation is just for demonstration purposes, and it's not running on Blazor at the moment. A new and fully Blazorise documentation project is in the works and these kinds of problems should be fixed. So, closing this for now.
