### ISSUE TITLE
Question: why are the Style and Class real properties instead of "CaptureUnmatchedValues"

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#979]
In the current code, you can only add/set a style like this:
``` html
<Card Style="color: red;"></Card>
```

It's not possible to use
``` html
<Card Style="color: @MyColor;"></Card>
```

I think the designed way in Blazor for supporting additional html-attributes is by using CaptureUnmatchedValues.

The cs-class should not have twp properties named "Class" and "Style" but just capture all other attributes like:
``` cs
/// <summary>
/// Gets or sets a collection of additional attributes that will be applied to the created <c>label</c> element.
/// </summary>
[Parameter(CaptureUnmatchedValues = true)]
public IReadOnlyDictionary<string, object> AdditionalAttributes { get; set; }
```

The implementation will be like:
``` cs
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
  base.BuildRenderTree(builder);

  builder.OpenElement(0, "xyz"); // normal existing code here ...
  builder.AddMultipleAttributes(1, AdditionalAttributes); // This will write all unnamed attributes
  // ...
  builder.CloseElement();
}
```

Now this can be used like:
``` html
<Card class="abc"  style="color: @MyColor;"/>
```

And simple example can be here:
- https://github.com/Blazored/FormExtensions/blob/master/src/Blazored.FormExtensions/LabelText.cs#L27
- https://github.com/Blazored/FormExtensions/blob/master/src/Blazored.FormExtensions/LabelText.cs#L55
- https://github.com/Blazored/FormExtensions/blob/master/samples/ClientSideBlazor/Pages/Label.razor#L13

**Comment by stsrki** [comment]
`Class` and `Style` properties were created two year ago. Way ago before capture missing attributes was possible. The problem with using regular `class` and `style` is that they will override any Blazorise classnames for that component.

I guess I could have another check for class and style when building the classnames and styles. That could work.

**Comment by StefH** [comment]
Yes, if you could make this more Blazor compatible, that would be very useful.
