### ISSUE TITLE
Can't add csproj in existing VS2019 project

### ISSUE THREAD

**Issue by janellesnowy** [stsrki/Blazorise#98]
Hi, I'm trying to add Blazorise source code into my existing project in VS2019 Preview. When adding the csproj, I get a One way upgrade dialog and it changes it to dotnet framework, which does not run. 

Visual Studi version: 16.0.28902.138 vs the commited version is 16.0.28531.58

**Comment by stsrki** [comment]
It could be a bug in VS2019 because I remember it working in VS2017. I think your best option for now is to add .csproj files manually into **.sln** file. That's how I do it. Hopefully Microsoft will fix the bug sometime.

**Comment by janellesnowy** [comment]
Thanks, I was actually trying it for a hour before I posted, it was challenging, because u are using props. I managed to add to my own new library, but it had trouble compiling. Anyway, I see that VS2019 Preview 16.20 is out, I will give that a go.

**Comment by janellesnowy** [comment]
Ok I got more insights. I'm create a client blazor only, and it only supports .netstandard 2.0, whereas I set blazorise to .netcore 3.0, 

So, does blazorise work with client only without server?

https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.0&tabs=visual-studio#razor-class-libraries-not-supported-for-client-side-apps

**Comment by stsrki** [comment]
It is working in both environments. The one issues with server-side razor components is they don't support static files. You must add those file manually into your _wwwroot_ and _Host.cshtml_.
Blazorise is configured for .netstandard 2.0 and for .netcore 3.0. [see](https://github.com/stsrki/Blazorise/blob/master/Build/Blazorise.props)
