### ISSUE TITLE
Feature request: Add multiline labels support for ChartJS component

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#983]
In ChartJS it's possible to add multi-line labels --> https://www.chartjs.org/samples/latest/scales/multiline-labels.html

But the current `AddLabel` does only support an array of strings, where actually it could be an array of objects.

A proposal would be to add a new method to the Chart component:
``` cs
public Task AddChartLabels(IEnumerable<object> labels)
```

**Usage**
The labels object could be defined like:
``` cs
var labels = new object[]
{
  new [] { "June", "2015" },
  "July",
  // ...
  new [] { "January", "2016" },
  "February",
  // ...
}
```

**Comment by stsrki** [comment]
I think simply converting Labels to `List<object>` could be enough to support this.

**Comment by StefH** [comment]
Yes.

BTW : I think `AddChartLabels` is better then `AddChartLabel` ? Because you add more labels, not just one.
