### ISSUE TITLE
Remove/change mask for DateEdit component

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#984]
I'm trying to figure out where the DateEdit mask comes from in the Blazorise code. for example where does the dd-----yyyy value come from in an unedited DateEdit component?

Ideally I would like to remove this mask entirely so that a user can try and enter a date e.g. 6apr2019 and it would pass or fail conversion to a real date value.

**Comment by stsrki** [comment]
Internal date input is always in format `yyyy-mm-dd`, and display format is controlled by the browser. Usually it's the same as system format.

You can see this answer https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format#:~:text=The%20HTML5%20date%20input%20specification,doing%20an%20ordinary%20form%20submission.

and this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by robalexclark** [comment]
I had no idea that this was a custom implementation based on each browser, probably because previously I've been using jquery.ui implementations. - thanks
