### ISSUE TITLE
Edit Mask not working

### ISSUE THREAD

**Issue by fabiano-ferreira** [stsrki/Blazorise#989]
I'm trying to use TextEdit to allow only a Canadian postal code (eg T5A4Z4). However, when I try to use the following pattern it is not accepting anything:

[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]

This is the textedit control in my code:

  <TextEdit MaxLength="6" MaskType="MaskType.RegEx" EditMask="[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]">
</TextEdit>

**Comment by stsrki** [comment]
The key is to be able to accept postal code while writing it, letter by letter, not just entire string at once. Including the empty string.

Try this: `^[A-Za-z]\d?[A-Za-z]?[ -]?\d?[A-Za-z]?\d?$`

It's still not perfect but you'll get the idea.

**Comment by fabiano-ferreira** [comment]
it is still not working.
What I exactly need is this pattern:

**1st char:**
   - Any of these letters: [ABCEGHJKLMNPRSTVXY]

**2nd char:**
  - only one number 

**3rd char:**
   Any of these letters: ABCEGHJKLMNPRSTVWXYZ

**4th char:**
  - only one number 

**5th char:**
   Any of these letters: ABCEGHJKLMNPRSTVWXYZ

**6th char:**
  - only one number 

**I used this EditMask:**

 EditMask="^[ABCEGHJKLMNPRSTVXY]?\d?[ABCEGHJKLMNPRSTVWXYZ]?\d?[ABCEGHJKLMNPRSTVWXYZ]?\d?$"

But when I type the first letter is still allowing me to type numbers.

**Comment by stsrki** [comment]
I understand, that's why I just gave you an example. Regex is not my strongest side so I cannot give you exact regex that you need. You will have to figure that one for yourself unfortunately.

**Comment by aherbage** [comment]
I think this does what you're looking for: 
^([ABCEGHJKLMNPRSTVXY]\d){0,2}[ABCEGHJKLMNPRSTVWXYZ]\d?$

**Comment by stsrki** [comment]
@aherbage @fabiano-ferreira I just checked it and it seems it works.

**Comment by stsrki** [comment]
Closing since @aherbage solution should work.
