### ISSUE TITLE
there is no way to programmatically deselct the seleted row so no row is selected in the datagrid

### ISSUE THREAD

**Issue by cherron4113** [stsrki/Blazorise#990]
**Describe the bug**

**To Reproduce**

**Expected behavior**

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**

**Additional context**

**Comment by aherbage** [comment]
Sure there is. Set your selected item to null. If that doesn't work, please provide some actual detail so people can try to help.

**Comment by cherron4113** [comment]
Sorry for the lack of details,  
I have tried to set the selected to null and fire statehaschanged and it did not work . 

I then asked this question on another thread - 
"is there a way to programmatically deselct the seleted row so no row is selected?" 
and received the response 

"@cherron4113 There is no at the moment. Can you open new issue? This one is old and already closed." by Mladen Macanović (stsrki)

He original thought it was done but had gone through the code and found it was not implemented.

**Comment by stsrki** [comment]
@cherron4113 it is possible to deselect row just like @aherbage already mentions.

Example

```cshtml
<Button Color="Color.Danger" Clicked="@(()=>selectedEmployee = null)"></Button>
```

But you also need to have the value binded to the grid like this `@bind-SelectedRow="@selectedEmployee"` .

**Comment by cherron4113** [comment]
I am expanding a detail row and allowing editing on that expansion with the submit and cancel buttons active in the parent row. here is a snippet of the code I am using  

DetailRowTrigger="@((item)=>item.Name == selectedEntity?.Name && isEdit)"
@bind-SelectedRow="@selectedEntity">

 <Button Color="Color.Primary" Clicked="@(()=> { CancelEdit(); })" Visibility="@(isEditing.Equals(Visibility.Always) && context.Name == selectedEntity?.Name?Visibility.Always:Visibility.Never)">Cancel</Button>

 public void CancelEdit()
    {
        isEditing = Visibility.Never;
        isEdit = false;
        selectedEntity = null;

        StateHasChanged();
    }

**Comment by stsrki** [comment]
Try setting CancelEdit directly, and convert void to Task.

`<Button Color="Color.Primary" Clicked="@CancelEdit" ...>Cancel</Button>`

```
public Task CancelEdit()
{
    isEditing = Visibility.Never;
    isEdit = false;
    selectedEntity = null;
    return Task.CompletedTask;
}
```

**Comment by cherron4113** [comment]
tried your solution - to compile I needed to change the call from Clicked="@CancelEdit" to 
 Clicked="@(()=>CancelEdit())". Sadly it still did not work.
