### ISSUE TITLE
NumericEdit: add option to allow only positive values

### ISSUE THREAD

**Issue by StefH** [stsrki/Blazorise#993]
In the current NumericEdit there is a parameter for Decimals and DecimalsSeparator.

It would be very useful to extend the NumericEdit to have a parameter which defines if this value must be positive. In that case, when you type a `-` sign, this should not be added to the textbox.

**Comment by robalexclark** [comment]
The NumericEdit already has Min and Max, so set Min=0 and you won't be able to input a -ve number...

**Comment by StefH** [comment]
It's still possible to enter a negative value:

``` html
<NumericEdit @bind-Value="person.Age" Min="0" Max="999"></NumericEdit>
```

![image](https://user-images.githubusercontent.com/249938/85409066-9b4c1380-b565-11ea-92cc-5924c138b1c7.png)

**Comment by robalexclark** [comment]
That's strange because the following markup works for me:

```
  <Validation>
                        <Field>
                            <FieldLabel><strong>Capacity</strong></FieldLabel>
                            <NumericEdit @bind-Value="@room.Capacity" Min="1">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </NumericEdit>
                        </Field>
                    </Validation>
```

I can't enter -1 or even 0....

**Comment by robalexclark** [comment]
I am using the latest preview (0.9.1-preview3) but not sure whether this is why it works for me.

**Comment by StefH** [comment]
I'm still using `0.9.0.3`.

**Comment by StefH** [comment]
@robalexclark I'm using official 0.9.1, and this one does also not work?
Can you double check or maybe create a simple example project?

**Comment by robalexclark** [comment]
I tried it on the blazorise repository and works for me, making a change to FormsPage.razor on line 129 to:

`    <NumericEdit TValue="decimal?" Min="1" />
`

(I'm running Blazorise.Demo.Bootstrap.Server as the startup project and currently on commit e081c94196a3778c8cf7b594b2649961f057d3ea)

**Comment by StefH** [comment]
And what if you use `Min="0"` ?

**Comment by robalexclark** [comment]
Works as expected, I cannot type in a negative sign at all, even if I try and cheat by typing in a number and then moving the cursor to the start and pressing "-"

**Comment by stsrki** [comment]
For me also it not works when `Min` is set to 0:

**Not working:**

```cshtml
<NumericEdit TValue="decimal" Min="0" />
```

**Working:**

```cshtml
<NumericEdit TValue="decimal" Min="1" />
```

**Comment by StefH** [comment]
See this page : https://github.com/StefH/BlazoriseExamples/blob/master/BlazorAppWebAssembly/Pages/Index.razor 
in the project : https://github.com/StefH/BlazoriseExamples/tree/master/BlazorAppWebAssembly

**Comment by robalexclark** [comment]
Still works for me even if I type -99 into notepad and paste it in. Can you run the Server project and see if this is different?

**Comment by SpontaneousDuck** [comment]
Can confirm on server side blazor, setting `Min="0"` still lets me input negative values

**Comment by abelvalle** [comment]
I can confirm that it is still not working. However, if you set the value `Min="1"` it works. But clearly, it doesn't allow to leave a value of 0.
![image](https://user-images.githubusercontent.com/26121474/101624053-a7476700-3a19-11eb-949c-277fbf01390e.png)
