### ISSUE TITLE
Data Annotations validations

### ISSUE THREAD

**Issue by Sprigg4ns** [stsrki/Blazorise#997]
Hello,
First of all thank you for all the work on Blazorise, it's very useful and effective. 
Unfortunately, I have a problem with the Data Annotations validations:

**Describe the bug**
I set up a form linked to a model containing simple data annotations (Required). Validation only works if I don't directly preload the model. Indeed, when I load my model in my OnInitializedAsync, it refuses to validate anything and only displays the error messages.

**To Reproduce**

1. In the razor page : 
```
@page "/User/Index"
@using AgoraMeetin.Manager.Models.Account
@inject HttpClient _HttpClient
@inject TokenAuthenticationStateProvider _TokenAuthenticationStateProvider
@inject IStringLocalizer<CommonProvider> _Localizer
<Validations @ref="mobj_Validations" Mode="ValidationMode.Auto" Model="@mvm_User">
    <Validation>
        <Field Horizontal="true">
            <FieldLabel ColumnSize="ColumnSize.Is2">@_Localizer["Nom"]</FieldLabel>
            <FieldBody ColumnSize="ColumnSize.Is10">
                <TextEdit Placeholder="@_Localizer["Nom"]" @bind-Text="@mvm_User.LastName">
                    <Feedback>
                        <ValidationError />
                    </Feedback>
                </TextEdit>
            </FieldBody>
        </Field>
    </Validation>
    <Button Color="Color.Primary" Clicked="@OnBtnSaveClicked">@_Localizer["Enregistrer"]</Button>
</Validations>

@functions {
    private UserViewModel mvm_User = new UserViewModel();
    private Validations mobj_Validations;

    protected override async Task OnInitializedAsync()
    {
        // CRASH 
        mvm_User = await _HttpClient.GetJsonAsync<UserViewModel>(
            "api/Account/GetUser",
            await _TokenAuthenticationStateProvider.GetTokenAsync());

        // Work fine
        //mvm_User.LastName = "Hello";
    }
}
```

2. My ViewModel : 

```
using AgoraMeetin.Manager.Localization.Validation;
using AgoraShared.Data;
using System.ComponentModel.DataAnnotations;

namespace AgoraMeetin.Manager.Models.Account
{
    public class UserViewModel
    {
        [Required(
            ErrorMessageResourceName = nameof(ValidationProvider.LastNameRequired),
            ErrorMessageResourceType = typeof(ValidationProvider))]
        public string LastName { get; set; }

        public UserViewModel()
        {
        }
    }
}
```

**Expected behavior**

I would like to keep validations working when I directly fill my ViewModel.
Actually it show me this :
![image](https://user-images.githubusercontent.com/16755574/85116949-5f8c1380-b21e-11ea-8aa8-37906cf91347.png)
Even when I update the input value and try to manual ValidateAll(), I still got this error message.

Thank you for you help

Regards
Rémy B.

**Comment by stsrki** [comment]
I would guess the problem is that in `OnInitializedAsync` you're creating new reference of `mvm_User`. And since you have being already used it for `Model="@mvm_User"` it will raise an exception. Internally Blazorise is using Model for `EditContext `and there can only be one at the time of creation.

Try using temporary model when getting the data from API and then assign every field manually.

**Comment by Sprigg4ns** [comment]
Thank you for you quick reply ! 
So I tried :
 
```
protected override async Task OnInitializedAsync()
{
	UserViewModel mvm_Usertemp = await _HttpClient.GetJsonAsync<UserViewModel>(
		"api/Account/GetUser",
		await _TokenAuthenticationStateProvider.GetTokenAsync());
	mvm_User.LastName = mvm_Usertemp.LastName;
}
```

It still doesn't work on the first display :
![image](https://user-images.githubusercontent.com/16755574/85118560-cf9b9900-b220-11ea-8a43-204ecea0714f.png)
But this time, if I update the input field, it works:
![image](https://user-images.githubusercontent.com/16755574/85118662-e8a44a00-b220-11ea-9691-574f3938d660.png)

You are right, It seems that this is a reference problem.

**Comment by Sprigg4ns** [comment]
For those who have this problem, just add a verification of your model (not null) before the validations tag : 
```
    @if (mvm_Usertemp != null)
    {
        <Validations @ref="mobj_Validations" Mode="ValidationMode.Auto" Model="mvm_Usertemp">
            ...
        </Validations>
    }
```
